[FEATURE] Création d'un endpoint pour remonter les lots de places (PIX-14006)
1024pix/pix pull request #10052
Opened 2024-09-04 14:20 UTC by machestla

## :unicorn: Problème
Nous souhaitons afficher les lots de places sur la page places. Pour ça nous avons besoin de créer un nouveau endpoint pour faire remonter les informations.

## :robot: Proposition
Créer un nouveau endpoint

## :rainbow: Remarques
- accessible pour les administrateurs
- ordonné actif -> à venir -> expirés

## :100: Pour tester
les tests au vert

2024-09-04 15:42 UTC, lionelB commented on api/src/prescription/organization-place/infrastructure/repositories/organization-places-lot-repository.js
> +const getAllByOrganizationId = async function (organizationId) {
**suggestion**: je propose de renommer en `findAllActiveByOrganizationId` pour rester cohérent avec les autres méthodes. 
**thought**:  findAllByOrganizationId et findAllByOrganizationIds
qui font sensiblement la même chose et remonte peu ou prou les mêmes infos, comme cette méthode. Est ce qu'on devrait rationaliser le code de ces 3 méthodes (extraire une fonction privée plus générique, modifier les usecases...  ?

2024-09-04 15:44 UTC, lionelB commented on api/src/prescription/organization-place/infrastructure/repositories/organization-places-lot-repository.js
> +    .select('count', 'activationDate', 'expirationDate', 'deletedAt')
**question**  Est ce qu'on a besoin du `deletedAt` ici vu qu'on prend que ceux qui sont `null` ?

2024-09-04 15:52 UTC, lionelB commented on api/src/prescription/organization-place/domain/usecases/get-organization-places-lots.js
> + * @returns {Promise<Array<PlaceLots>>}
**praise** Trop bien les commentaires jsdoc. 👍

2024-09-04 15:58 UTC, lionelB commented on api/src/prescription/organization-place/infrastructure/serializers/jsonapi/organization-places-lots-serializer.js
> +    attributes: ['organizationId', 'count', 'activationDate', 'expirationDate', 'status'],
**thought** : le status est un champ dérivé depuis la date d'expiration / date du jour et date d'activation je pense qu'on devrait seulement le "calculer" dans le front

2024-09-04 16:01 UTC, lionelB commented on api/tests/prescription/organization-place/unit/application/organization-place-controller_test.js
> +      usecases.getOrganizationPlacesLots.resolves(organizationPlacesLots);
**suggestion**: on pourrait utiliser un model pour l'organizationId et rajouter un withArgs dans le usecase pour valider qu'on appelle le usecase correctement

2024-09-04 16:05 UTC, lionelB requested changes
**todo(blocking)**: rajouter un test d'acceptance sur la route pour le cas nominal
pour le test on peut d'identifier sur orga en tant d'admin et récupérer le jwt pour faire un curl sur la route avec.

2024-09-05 07:36 UTC, machestla commented on api/src/prescription/organization-place/infrastructure/serializers/jsonapi/organization-places-lots-serializer.js
> +    attributes: ['organizationId', 'count', 'activationDate', 'expirationDate', 'status'],
Je suis d'accord avec toi mais on le fait déjà dans 2 models différents sur les places et ça de 2 manières différentes... Je voulais vous poser la question au daily mais je pense qu'une PR de nettoyage/rangement serait la bienvenue

2024-09-05 07:44 UTC, machestla commented on api/src/prescription/organization-place/infrastructure/repositories/organization-places-lot-repository.js
> +const getAllByOrganizationId = async function (organizationId) {
Oui, je vais faire ça, cependant je trouve également qu'aucune de ces 3 méthode n'est bien nommée car à part la mise au pluriel rien n'indique ce qu'elles ont de différent et pourtant il n'y a pas que ça qui change. Il m'est d'avis d'améliorer le nommage des méthodes dans une PR de refacto sur le back des places.

2024-09-05 07:49 UTC, machestla commented on api/src/prescription/organization-place/infrastructure/repositories/organization-places-lot-repository.js
> +    .select('count', 'activationDate', 'expirationDate', 'deletedAt')
Oui car je réutilise le model `PlacesLot` qui le require

2024-09-05 08:32 UTC, lionelB commented on api/src/prescription/organization-place/infrastructure/serializers/jsonapi/organization-places-lots-serializer.js
> +    attributes: ['organizationId', 'count', 'activationDate', 'expirationDate', 'status'],
effectivement, je me demande dans quelle mesure on pourrait avoir un modèle de base qui a la méthode qui calcule le status, et avoir des modèles qui hériterait de ce modèle pour des cas spécifique ?

2024-09-05 09:54 UTC, xav-car commented on api/src/prescription/organization-place/infrastructure/repositories/organization-places-lot-repository.js
> +  return placesLots.map((e) => new PlacesLot(e));
**suggestion** le `e` est pas super explicite quand même 🤔

2024-09-05 09:57 UTC, xav-car commented on api/tests/prescription/organization-place/integration/infrastructure/repositories/organization-places-lot-repository_test.js
> +        count: 12,
**suggestion** expliciter le fait que les places ne sont pas deleted

2024-09-05 10:00 UTC, xav-car commented on api/tests/prescription/organization-place/integration/infrastructure/repositories/organization-places-lot-repository_test.js
> +        expect(foundOrganizationPlace[0].count).to.deep.equal(organizationPlace2.count);
**suggestion** : tester avec `activationDate` plutôt que le `count` , puisque c'est ce que le test fait.

2024-09-05 10:01 UTC, xav-car commented on api/tests/prescription/organization-place/integration/infrastructure/repositories/organization-places-lot-repository_test.js
> +        expect(foundOrganizationPlace[0].count).to.deep.equal(organizationPlace2.count);
**suggestion** : idem qu'au dessus . mais tester la `expirationDate`

2024-09-05 10:02 UTC, xav-car commented on api/tests/prescription/organization-place/integration/infrastructure/repositories/organization-places-lot-repository_test.js
> +        expect(foundOrganizationPlace[0].count).to.deep.equal(organizationPlace2.count);
**suggestion** : tester avec le `createdAt`

2024-09-05 12:13 UTC, xav-car commented on api/src/prescription/organization-place/domain/usecases/get-organization-places-lots.js
> + * @returns {Promise<Array<PlaceLots>>}
🏆

2024-09-05 12:14 UTC, xav-car commented on api/src/prescription/organization-place/domain/usecases/get-organization-places-lots.js
> +  return await organizationPlacesLotRepository.getAllByOrganizationId(organizationId);
**suggestion**

`return organizationPlacesLotRepository.getAllByOrganizationId(organizationId);`

Pas besoin d'await le return.

2024-09-05 12:18 UTC, machestla commented on api/src/prescription/organization-place/infrastructure/repositories/organization-places-lot-repository.js
> +const getAllByOrganizationId = async function (organizationId) {
après le "Active" prête à confusion avec le status du lot de place "actif", "expiré", "à venir" donc je propose `findAllNotDeletedByOrganizationId`

2024-09-05 12:40 UTC, xav-car reviewed
toto

2024-09-05 12:40 UTC, xav-car commented on api/tests/prescription/organization-place/unit/application/organization-place-controller_test.js
> +      const organizationId = 9876;
**suggestion** : `Symbol` pas necessaire de définir son type dans le test

2024-09-05 12:40 UTC, xav-car commented on api/tests/prescription/organization-place/unit/application/organization-place-route_test.js
> +    });
**suggestion** ça part plus en test d'acceptance . expect 200 .

2024-09-05 12:40 UTC, xav-car commented on api/tests/prescription/organization-place/unit/application/organization-place-route_test.js
> +    it('should return HTTP code 403 if user do not belong of the organization', async function () {
**suggestion** ajouter un test pour vérifier que lorsque l'id n'est pas un nombre ça pète

2024-09-05 12:40 UTC, xav-car commented on api/src/prescription/organization-place/application/organization-place-route.js
> +        handler: organizationPlaceController.getOrganizationPlacesLots,
**suggestion** ajouter un validate organizationId comme sur une route.

2024-09-05 12:43 UTC, lionelB approved these changes

2024-09-09 14:20 UTC, lionelB commented
test func ok, juste le tri remonte les `pending` avant les `active` alors qu'il faudrait que ce soit l'inverse.

2024-09-10 07:52 UTC, merged