[TECH] Améliorer le mot de passe surveillant (PIX-13007).
1024pix/pix pull request #10154
Opened 2024-09-20 10:36 UTC by AndreiaPena

## :unicorn: Problème

## :robot: Proposition

## :rainbow: Remarques

## :100: Pour tester

2024-09-20 13:18 UTC, P-Jeremy requested changes, later dismissed
Voir GitGuardian...

2024-09-23 07:33 UTC, alexandrecoin commented on api/src/certification/enrolment/infrastructure/serializers/session-serializer.js
> +      return { ...session, status: session.status, supervisorPassword: session.invigilatorPassword };
```suggestion javascript
return { ...session,  supervisorPassword: session.invigilatorPassword };
```

2024-09-23 08:37 UTC, matthieu-octo approved these changes

2024-09-23 14:38 UTC, alexandrecoin approved these changes

2024-09-25 09:16 UTC, Steph0 commented on api/src/certification/enrolment/domain/models/SessionEnrolment.js
> +const INVIGILATOR_PASSWORD_CHARS = '0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ'.split('');
Liste en cours de precision entre metier, dev et secu

2024-09-25 15:49 UTC, Steph0 approved these changes

2024-09-25 15:49 UTC, Steph0 commented on api/tests/certification/enrolment/acceptance/application/session-mass-import-route_test.js
> +            invigilatorPassword: 'KV2CPA',
Vu que finalement pas de A ^^'
```suggestion
            invigilatorPassword: 'KV2CPB',
```

2024-09-25 15:49 UTC, Steph0 commented on api/tests/certification/enrolment/unit/domain/models/SessionEnrolment_test.js
> +    it('should return a invigilator password containing only alphanumeric characters', async function () {
```suggestion
    it('should return a invigilator password containing only allowed characters', async function () {
```

2024-09-25 15:49 UTC, Steph0 commented on api/src/certification/enrolment/domain/models/SessionEnrolment.js
> +const INVIGILATOR_PASSWORD_CHARS = '23456789bcdfghjkmpqrstvwxyBCDFGHJKMPQRSTVWXY!*?'.split('');
thanks @matthieu-octo

2024-09-26 08:46 UTC, Steph0 commented
Re-test, et j'ai obtenu un caractere special

![image](https://github.com/user-attachments/assets/474d7cb0-8ee4-44c5-b7c1-b66188499c09)
![image](https://github.com/user-attachments/assets/36632ecc-815f-4ca2-b175-2d613420ec71)

2024-09-26 08:48 UTC, Steph0 commented on api/tests/certification/enrolment/unit/domain/models/SessionEnrolment_test.js
> +    it('should return a invigilator password containing only alphanumeric characters', async function () {
Done

2024-09-26 08:55 UTC, merged

2024-09-30 10:02 UTC, romain-pix-cyber commented on api/src/certification/enrolment/domain/models/SessionEnrolment.js
> +const INVIGILATOR_PASSWORD_CHARS = '23456789bcdfghjkmpqrstvwxyBCDFGHJKMPQRSTVWXY!*?'.split('');
👀