[BUFIX]  Bloquer l'entrée en certification de candidats cléa sans RT (PIX-15497)
1024pix/pix pull request #10672
Opened 2024-11-28 13:27 UTC by P-Jeremy

## :fallen_leaf: Problème

## :chestnut: Proposition

## :jack_o_lantern: Remarques

## :wood: Pour tester

2024-11-28 13:50 UTC, P-Jeremy commented
Test func inscrit cléa sans RT OK ✅

![image](https://github.com/user-attachments/assets/3a3196ac-8a2a-471b-8ef9-ec7d1e85ed62)

2024-11-28 16:30 UTC, AndreiaPena commented on api/src/certification/enrolment/domain/usecases/verify-candidate-subscriptions.js
> +    if (_hasCoreAndComplementarSubscriptions(candidate)) {
```suggestion
    if (_hasCoreAndComplementarySubscriptions(candidate)) {
```

2024-11-29 08:54 UTC, Steph0 requested changes
C'est mort ca passe pas !!

2024-12-16 09:03 UTC, HEYGUL commented
Fermée car en attente de réponse du métier.

2024-12-16 09:03 UTC, closed without merging