[FEATURE] Traduire la page détails de compétence (PIX-366).
1024pix/pix pull request #1627
Opened 2020-07-08 15:24 UTC by jonasgrilleres

## :unicorn: Problème
Pour lancer l'internationalisation de Pix App, il faut que les templates soient remplis avec des tokens qui représentent les strings à afficher dans les différentes langues, plutôt que les textes directement en dur.

## :robot: Solution
Ember-intl a été préalablement installé, les fichiers `fr.json` et `en.json` crées. Il faut remplacer les strings en dur dans les template et compléter ces deux fichiers.

## :rainbow: Remarques
- suppression de la méthode `computeRemainingDaysBeforeImproving` qui a été remplacée par la fonction de pluralisation de ember-intl. Que faire des tests ? Les supprimer purement et simplement ? Les déplacer ?
- que faire des wordings qui sont fréquemment utilisés à plusieurs endroits ? Ils sont regroupés pour l'instant dans `common`
- comment gérer la capitalisation des mots ? Est-ce qu'on stocke dans les fichiers de traduction les strings avec des majuscules ou est-ce qu'on gère ça en CSS (ou autrement) ?
- tentative de gérer ce genre de logique dans le template `ember-intl`, selon la technique de la pluralisation, en vain : 
```javascript
{{#if @scorecard.hasNotReachLevelOne}}
  {{t 'scorecard.reset.modal.importantMessage' earnedPix=@scorecard.earnedPix}}
{{else if @scorecard.hasReachAtLeastLevelOne}}
  {{t 'scorecard.reset.modal.importantMessage' level=@scorecard.level earnedPix=@scorecard.earnedPix}}
{{/if}}
```

## :100: Pour tester
TBA

2020-07-08 15:29 UTC, pix-service commented
I'm deploying this PR to these urls:

- App: https://app-pr1627.review.pix.fr
- Orga: https://orga-pr1627.review.pix.fr
- Certif: https://certif-pr1627.review.pix.fr
- Admin: https://admin-pr1627.review.pix.fr
- API: https://api-pr1627.review.pix.fr/api/

 Please check it out!

2020-07-09 08:17 UTC, MelanieMEB commented on mon-pix/translations/fr.json
> +      "start": "Commencer"
Dans ce cas, je mettrais "Commencer" en minuscule comme les autres.

2020-07-09 08:17 UTC, MelanieMEB commented on mon-pix/translations/fr.json
> +      "button": "Remettre à zéro",
N'est-ce pas scorecard.global.reset ?

2020-07-09 08:41 UTC, jonasgrilleres commented on mon-pix/translations/fr.json
> +      "button": "Remettre à zéro",
Tout à fait, j'ai oublié de changer ce truc là

2020-07-10 09:08 UTC, celineung commented on mon-pix/tests/integration/components/scorecard-details-test.js
> +  beforeEach(function() {
mettre un saut de ligne avant le `beforeEach`

2020-07-10 09:36 UTC, celineung approved these changes

2020-07-10 14:45 UTC, MelanieMEB approved these changes

2020-07-15 10:01 UTC, ghost requested changes

2020-07-15 10:01 UTC, ghost commented on mon-pix/app/templates/components/scorecard-details.hbs
> +      {{t 'scorecard.global.back'}}
Je trouve que `back` n'est pas suffisamment autoportant + la traduction semble un peu plus complexe que ça https://www.wordreference.com/fren/retour
```suggestion
      {{t 'scorecard.global.return-to-profile'}}
```
```suggestion
      {{t 'scorecard.global.go-back-to-profile'}}
```

2020-07-15 10:01 UTC, ghost commented on mon-pix/app/templates/components/scorecard-details.hbs
> +                <span class="score-label competence-card__score-label--congrats">{{t 'common.level'}}</span>
Pourquoi ne pas utiliser la dénomination du CSS ? 
```suggestion
                <span class="score-label competence-card__score-label--congrats">{{t 'common.score-label'}}</span>
```

2020-07-15 10:01 UTC, ghost commented on mon-pix/app/templates/components/scorecard-details.hbs
> +                <span class="score-label">{{t 'common.level'}}</span>
```suggestion
                <span class="score-label">{{t 'common.score-label'}}</span>
```

2020-07-15 10:01 UTC, ghost commented on mon-pix/app/templates/components/scorecard-details.hbs
> +            <div class="score-label">{{t 'common.pix'}}</div>
Est-ce qu'on prévoit vraiment de traduire Pix ?
```suggestion
            <div class="score-label">pix</div>
```

2020-07-15 10:01 UTC, ghost commented on mon-pix/app/templates/components/scorecard-details.hbs
> +                <span class="scorecard-details-improvement-countdown__label">{{t 'scorecard.improve.label'}}</span>
Pareil qu'au dessus, j'aurais tendance à utiliser 
```suggestion
                <span class="scorecard-details-improvement-countdown__label">{{t 'scorecard.improvement-countdown.label'}}</span>
```

ou alors pour éviter la multitude d'index, pour fitter avec la suite 
```suggestion
                <span class="scorecard-details-improve__countdown-label">{{t 'scorecard.improvement-countdown.label'}}</span>
```

2020-07-15 10:01 UTC, ghost commented on mon-pix/app/templates/components/scorecard-details.hbs
> +                <span class="scorecard-details-improvement-countdown__count">{{t 'scorecard.improve.count'
```suggestion
                <span class="scorecard-details-improvement-countdown__count">{{t 'scorecard.improve.count'
```
```suggestion
                <span class="scorecard-details-improvement-countdown__count">{{t 'scorecard.improve.countdown'
```

2020-07-15 10:01 UTC, ghost commented on mon-pix/app/templates/components/scorecard-details.hbs
> +              <span class="scorecard-details__improving-text">{{t 'scorecard.improve.improvingText' }}</span>
De ce que j'ai vu, le standard que l'on a utilisé jusque là était le `kebab-case`
```suggestion
              <span class="scorecard-details__improving-text">{{t 'scorecard.improve.improving-text' }}</span>
```

2020-07-15 10:01 UTC, ghost commented on mon-pix/app/templates/components/scorecard-details.hbs
> +            {{t 'scorecard.global.startover'}}
On parle plutôt de `start again` apparemment https://www.wordreference.com/fren/reprendre
```suggestion
            {{t 'scorecard.global.start-again'}}
```

2020-07-15 10:01 UTC, ghost commented on mon-pix/app/templates/components/scorecard-details.hbs
> +            <div class="sr-only">{{t 'scorecard.improve.startOverCompetence' competence=@scorecard.name}}</div>
```suggestion
            <div class="sr-only">{{t 'scorecard.improve.start-again-competence' competence=@scorecard.name}}</div>
```

2020-07-15 10:01 UTC, ghost commented on mon-pix/app/templates/components/scorecard-details.hbs
> +            <div class="sr-only">{{t 'scorecard.improve.startOverCompetence' competence=@scorecard.name}}</div>
```suggestion
            <div class="sr-only">{{t 'scorecard.improve.start-again-competence' competence=@scorecard.name}}</div>
```

2020-07-15 10:01 UTC, ghost commented on mon-pix/app/templates/components/scorecard-details.hbs
> +          <div class="sr-only">{{t 'scorecard.improve.startOverCompetence' competence=@scorecard.name}}</div>
```suggestion
          {{t 'scorecard.reset.button-label'}}
          <div class="sr-only">{{t 'scorecard.improve.start-again-competence' competence=@scorecard.name}}</div>
```

2020-07-15 10:01 UTC, ghost commented on mon-pix/app/templates/components/scorecard-details.hbs
> +        <p class="scorecard-details-content-right__reset-message">{{t 'scorecard.reset.label'
Dans la même logique que `improve`, je verrais plutôt 
```suggestion
        <p class="scorecard-details-content-right__reset-message">{{t 'scorecard.reset.countdown'
```

2020-07-15 10:01 UTC, ghost commented on mon-pix/app/templates/components/scorecard-details.hbs
> +            {{t 'scorecard.reset.modal.importantMessage' earnedPix=@scorecard.earnedPix}}
```suggestion
            {{t 'scorecard.reset.modal.important-message' earnedPix=@scorecard.earnedPix}}
```

2020-07-15 10:01 UTC, ghost commented on mon-pix/app/templates/components/scorecard-details.hbs
> +            {{t 'scorecard.reset.modal.importantMessage' level=@scorecard.level earnedPix=@scorecard.earnedPix}}
```suggestion
            {{t 'scorecard.reset.modal.important-message-above-level-one' level=@scorecard.level earnedPix=@scorecard.earnedPix}}
```

2020-07-15 10:01 UTC, ghost commented on mon-pix/app/templates/components/scorecard-details.hbs
> +        <button class="button button--big button--extra-thin button--red" {{action "reset"}}>{{t 'scorecard.global.reset'}}</button>
Dans la même logique que `improve`, je verrais plutôt 
```suggestion
        <button class="button button--big button--extra-thin button--red" {{action "reset"}}>{{t 'scorecard.reset.button-label'}}</button>
```

2020-07-15 10:09 UTC, ghost requested changes

2020-07-15 10:09 UTC, sbedeau commented on mon-pix/app/templates/components/scorecard-details.hbs
> +      {{t 'scorecard.linkToProfile'}}
Echo à ma première review

```suggestion
      {{t 'scorecard.link-to-profile'}}
```
```suggestion
      {{t 'scorecard.go-back-to-profile'}}
```
```suggestion
      {{t 'scorecard.return-to-profile'}}
```

2020-07-15 10:09 UTC, sbedeau commented on mon-pix/app/templates/components/scorecard-details.hbs
> +          {{t 'scorecard.nextLevelInfo' remainingPixToNextLevel=@scorecard.remainingPixToNextLevel
```suggestion
          {{t 'scorecard.next-level-info' remainingPixToNextLevel=@scorecard.remainingPixToNextLevel
```

2020-07-15 10:09 UTC, sbedeau commented on mon-pix/app/templates/components/scorecard-details.hbs
> +                <span class="scorecard-details-improvement-countdown__count">{{t 'scorecard.actions.improve.description.dayBefore'
```suggestion
                <span class="scorecard-details-improvement-countdown__count">{{t 'scorecard.actions.improve.description.countdown'
```

2020-07-15 10:09 UTC, sbedeau commented on mon-pix/app/templates/components/scorecard-details.hbs
> +                <span class="scorecard-details-improvement-countdown__label">{{t 'scorecard.actions.improve.description.waitingText'}}</span>
```suggestion
                <span class="scorecard-details-improvement-countdown__label">{{t 'scorecard.actions.improve.description.waiting-text'}}</span>
```

2020-07-15 10:09 UTC, sbedeau commented on mon-pix/app/templates/components/scorecard-details.hbs
> +                <div class="sr-only">{{t 'scorecard.forCompetence' competence=@scorecard.name }}"</div>
```suggestion
                <div class="sr-only">{{t 'scorecard.for-competence' competence=@scorecard.name }}"</div>
```

2020-07-15 10:09 UTC, sbedeau commented on mon-pix/app/templates/components/scorecard-details.hbs
> +            {{t 'scorecard.actions.continue.label'}}
```suggestion
            {{t 'scorecard.actions.resume.label'}}
```

2020-07-15 10:09 UTC, sbedeau commented on mon-pix/app/templates/components/scorecard-details.hbs
> +            <div class="sr-only">{{t 'scorecard.forCompetence' competence=@scorecard.name}}</div>
```suggestion
            <div class="sr-only">{{t 'scorecard.for-competence' competence=@scorecard.name}}</div>
```

2020-07-15 10:09 UTC, sbedeau commented on mon-pix/app/templates/components/scorecard-details.hbs
> +            <div class="sr-only">{{t 'scorecard.forCompetence' competence=@scorecard.name}}</div>
```suggestion
            <div class="sr-only">{{t 'scorecard.for-competence' competence=@scorecard.name}}</div>
```

2020-07-15 10:09 UTC, sbedeau commented on mon-pix/app/templates/components/scorecard-details.hbs
> +          <div class="sr-only">{{t 'scorecard.forCompetence' competence=@scorecard.name}}</div>
```suggestion
          <div class="sr-only">{{t 'scorecard.for-competence' competence=@scorecard.name}}</div>
```

2020-07-15 10:09 UTC, sbedeau commented on mon-pix/app/templates/components/scorecard-details.hbs
> +            {{t 'scorecard.actions.reset.modal.importantMessageAboveLevelOne' level=@scorecard.level earnedPix=@scorecard.earnedPix}}
```suggestion
            {{t 'scorecard.actions.reset.modal.important-message-above-level-one' level=@scorecard.level earnedPix=@scorecard.earnedPix}}
```

2020-07-15 10:09 UTC, sbedeau commented on mon-pix/app/templates/components/scorecard-details.hbs
> +            {{t 'scorecard.actions.reset.modal.importantMessage' earnedPix=@scorecard.earnedPix}}
```suggestion
            {{t 'scorecard.actions.reset.modal.important-message' earnedPix=@scorecard.earnedPix}}
```

2020-07-15 12:14 UTC, celineung commented on mon-pix/app/templates/components/scorecard-details.hbs
> +                <span class="score-label">{{t 'common.level'}}</span>
Si le texte `Niveau` reste dans `common`, je suggèrerais de laisser `common.level` car le nom de la clé serait plus parlant si on l'utilise dans d'autres parties de l'application.
Mais si on veut garder `score-label`, je pense qu'il serait mieux de l'enlever de `common`. D'ailleurs la classe css s'appelle `score-label` mais ce n'est pas vraiment un label...

2020-07-15 12:54 UTC, celineung commented on mon-pix/translations/fr.json
> +    "forCompetence": "la compétence {competence}",
```suggestion
    "competence": "la compétence {competence}",
```

2020-07-16 13:14 UTC, merged