[FEATURE] Récupérer les scorecards dans la bonne langue (PIX-665).
1024pix/pix pull request #1640
Opened 2020-07-13 15:53 UTC by jonasgrilleres

## :unicorn: Problème
Les traductions des scorecards ne sont pas récupérées par l'API. 

## :robot: Solution
Faire passer la locale depuis le `controller` jusque dans le `repository` pour construire l'objet `domain` avec les bonnes traductions.

## :rainbow: Remarques
- la variable `locale` est trimballée dans toutes les couches 
- la méthode `_getTranslatedText` prend chaque langue en paramètre, cela peut devenir un peu compliqué quand on aura beaucoup de langues :
```javascript
function _getTranslatedText(locale, frenchText, englishText) {
  if (locale === ENGLISH_SPOKEN) {
    return englishText;
  }

  return frenchText;
}
```

## :100: Pour tester
Changer la varenv `LOCALE` à 'en' ou 'fr'.

2020-07-13 15:58 UTC, pix-service commented
I'm deploying this PR to these urls:

- App: https://app-pr1640.review.pix.fr
- Orga: https://orga-pr1640.review.pix.fr
- Certif: https://certif-pr1640.review.pix.fr
- Admin: https://admin-pr1640.review.pix.fr
- API: https://api-pr1640.review.pix.fr/api/

 Please check it out!

2020-07-13 16:01 UTC, MelanieMEB commented on mon-pix/app/adapters/application.js
> +    return this.locale;
J'aurais inversé le if :
- Dans le cas actuelle, il n'y a pas de ENV.APP.LOCALE sur la prod et sur toutes les applications.
- Si on envoie ainsi, on ne rentrera pas dans le if, donc on aura "undefined".

2020-07-13 16:04 UTC, MelanieMEB commented on api/lib/infrastructure/repositories/competence-repository.js
> +
```suggestion
function _getTranslatedText(locale, text) {
    return text[locale];
}

{fr : areaData.titleFrFr, en: ....}
```

2020-07-15 08:36 UTC, MelanieMEB requested changes

2020-07-15 08:36 UTC, MelanieMEB commented on api/tests/tooling/domain-builder/factory/build-competence-airtable-data-object.js
> +  descriptionEnUs = 'Some description',
```suggestion
  nameFrFr = 'Mener une recherche et une veille d’information',
  nameEnUs = 'Browsing, searching and filtering data, information and digital content',
  index = '1.1',
  areaId = 'recvoGdo7z2z7pXWa',
  description = 'Une description',
  descriptionFrFr = 'Une description',
  descriptionEnUs = 'Some description',
```

Je propose de traduire dans le builder qu'il n'y ait pas de problème d'incompréhension plus tard

2020-07-15 08:36 UTC, MelanieMEB commented on api/lib/infrastructure/repositories/competence-repository.js
> +function _list({ locale }) {
Dans ce fichier, on utilise parfois `({ locale })` et d'autres fois `(locale)`
Je propose que nous utilisions `{ locale }` partout

2020-07-15 08:36 UTC, MelanieMEB commented on api/lib/infrastructure/repositories/competence-repository.js
> +
Globalement cette partie pourrait être amélioré, voir sortie dans un service de traduction.
Possiblement à faire quand nous aurons traduit d'autres objets du référentiel

2020-07-15 08:54 UTC, celineung approved these changes

2020-07-15 09:24 UTC, celineung commented on mon-pix/app/adapters/application.js
> +    return this.locale;
Dans `environment.js`, s'il n'y a pas de LOCALE spécifiée dans a config Scalingo, alors la LOCALE prend la valeur de `fr`. Elle ne sera donc pas `undefined`.

2020-07-15 09:26 UTC, MelanieMEB commented on mon-pix/app/adapters/application.js
> +    return this.locale;
👍

2020-07-16 10:03 UTC, sbedeau commented on api/lib/domain/usecases/get-scorecard.js
> +}) {
Pourquoi ne pas tester ?

2020-07-16 10:04 UTC, sbedeau commented on api/lib/domain/usecases/get-user-scorecards.js
> +    competenceRepository.listPixCompetencesOnly({ locale }),
Pourquoi ne pas tester ?

2020-07-17 11:29 UTC, sbedeau commented on api/lib/infrastructure/repositories/competence-repository.js
> +function _toDomain(competenceData, areaDatas, locale) {
Est-ce qu'on ne devrait pas suivre le pattern [RORO](https://medium.com/free-code-camp/elegant-patterns-in-modern-javascript-roro-be01e7669cbd) ici ? 
```suggestion
function _toDomain({ competenceData, areaDatas, locale }) {
```

2020-07-17 11:31 UTC, sbedeau commented on api/lib/infrastructure/repositories/competence-repository.js
> +    name: _getTranslatedText(locale, { frenchText: competenceData.nameFrFr, englishText: competenceData.nameEnUs }),
J'aurais tendance à extraire cette ligne pour gagner en lisibilité 
```suggestion
const translastedName = _getTranslatedText(locale, { frenchText: competenceData.nameFrFr, englishText: competenceData.nameEnUs });

return new Competence({
    id: competenceData.id,
    name: translatedName,
```

2020-07-17 11:31 UTC, sbedeau commented on api/lib/infrastructure/repositories/competence-repository.js
> +    description: _getTranslatedText(locale, { frenchText: competenceData.descriptionFrFr, englishText: competenceData.descriptionEnUs }),
Pareil que pour `translatedName`

2020-07-17 11:31 UTC, sbedeau commented on api/lib/infrastructure/repositories/competence-repository.js
> +      title: _getTranslatedText(locale, { frenchText: areaData.titleFrFr, englishText: areaData.titleEnUs }),
Pareil que pour `translatedName`

2020-07-17 11:41 UTC, sbedeau commented on api/lib/infrastructure/repositories/competence-repository.js
> +function _getTranslatedText(locale, translations = { frenchText: '', englishText: '' }) {
Qu'est-ce qui fait que l'on ait besoin d'utiliser ça ? Je trouve que ça alourdit la compréhension du code et que RORO serait suffisant 
```suggestion
function _getTranslatedText({ locale, frenchText, englishText }) {
```

2020-07-17 11:42 UTC, sbedeau commented on api/lib/infrastructure/repositories/competence-repository.js
>    },
Pareil, pourquoi on a besoin d'utiliser cette syntaxe ? 
Est-ce qu'on l'utilise ailleurs ? Est-ce que ça sera comprit par tout le monde ?

2020-07-17 11:43 UTC, sbedeau commented on api/lib/infrastructure/repositories/competence-repository.js
> +    return _list({ locale }).then((competences) =>
Pareil, pourquoi on a besoin d'utiliser cette syntaxe ? 
Est-ce qu'on l'utilise ailleurs ? Est-ce que ça sera comprit par tout le monde ?

2020-07-17 11:43 UTC, sbedeau commented on api/lib/infrastructure/repositories/competence-repository.js
> +  listPixCompetencesOnly({ locale } = { locale: FRENCH_FRANCE }) {
Pareil, pourquoi on a besoin d'utiliser cette syntaxe ? 
Est-ce qu'on l'utilise ailleurs ? Est-ce que ça sera comprit par tout le monde ?

2020-07-17 11:47 UTC, ghost requested changes
Globalement ok mais `competence-repository.js` me fait me demander où en est l'état de l'art de nos standards Clean Code. On devrait peut-être voir ça ensemble ?

2020-07-17 12:04 UTC, celineung commented on api/lib/infrastructure/repositories/competence-repository.js
>    },
lorsque `list` est appelé sans aucun paramètre, `locale` ne parvient pas à être mappé, c'est pourquoi tout l'objet (plutôt que seulement `locale`) est initialisé

2020-07-17 12:05 UTC, celineung commented on api/lib/infrastructure/repositories/competence-repository.js
> +function _getTranslatedText(locale, translations = { frenchText: '', englishText: '' }) {
`{ locale, translations: { frenchText: '', englishText: '' } }`

2020-07-17 13:52 UTC, ghost approved these changes

2020-07-17 14:07 UTC, merged