[FEATURE] Traduire la page "Oups" (PIX-791).
1024pix/pix pull request #1661
Opened 2020-07-21 09:54 UTC by HEYGUL

## :unicorn: Problème
Dans le cadre de l'internationalisation de Pix, nous devons adapter notre plateforme dans d'autres langues et contextes régionaux.
La page d'erreur (Oups) n'est pas encore traductible.

## :robot: Solution
Ajout des traductions des composants utilisés par la page Oups.

## :rainbow: Remarques
RAS

## :100: Pour tester
ur la review app, mettre la variable d'environnement LOCALE à en.
Se rendre sur la page d'erreur.
Vérifier que les textes sont affichés en langue anglaise.

2020-07-21 12:39 UTC, pix-service commented
I'm deploying this PR to these urls:

- App: https://app-pr1661.review.pix.fr
- Orga: https://orga-pr1661.review.pix.fr
- Certif: https://certif-pr1661.review.pix.fr
- Admin: https://admin-pr1661.review.pix.fr
- API: https://api-pr1661.review.pix.fr/api/

 Please check it out!

2020-07-21 13:01 UTC, MelanieMEB requested changes

2020-07-21 13:01 UTC, MelanieMEB commented on mon-pix/app/templates/error.hbs
> +          <p>{{t "pages.error.content-text-4"}}</p>
Question : est-ce que les text-1-2-3-4 ne devrait pas être dans un seul text et on passerait le html ? 
<p>{{t "pages.error.content-text" htmlSafe=true}}</p>

2020-07-21 13:13 UTC, HEYGUL commented on mon-pix/app/templates/error.hbs
> +          <p>{{t "pages.error.content-text-4"}}</p>
Ah ben c'est surement plus simple. Je change.

2020-07-21 14:34 UTC, MelanieMEB approved these changes

2020-07-21 15:19 UTC, celineung commented on mon-pix/app/templates/error.hbs
> +            {{t "pages.error.back-to-homepage"}}</LinkTo>
Il y a un élément `navigation.back-to-profile` qui existe déjà.
Peut-être rajouter `navigation.back-to-homepage` ?

2020-07-21 15:23 UTC, HEYGUL commented on mon-pix/app/templates/error.hbs
> +          <h1 class="error-page-main-content__title">{{t "pages.error.content-title"}}</h1>
```suggestion
          <h1 class="error-page-main-content__title">{{t "pages.error.first-title"}}</h1>
```

2020-07-21 15:23 UTC, HEYGUL commented on mon-pix/app/templates/error.hbs
> +            {{t "pages.error.back-to-homepage"}}</LinkTo>
```suggestion
            {{t "navigation.back-to-homepage"}}</LinkTo>
```

2020-07-21 15:26 UTC, HEYGUL reviewed
Ajouter un `controller` pour afficher un titre à la page.

2020-07-22 07:43 UTC, MelanieMEB commented on mon-pix/app/templates/error.hbs
> +            {{t "navigation.back-to-homepage"}}</LinkTo>,
Ya une virgule qui est apparu

2020-07-22 08:10 UTC, celineung approved these changes

2020-07-22 08:10 UTC, celineung commented on mon-pix/translations/en.json
> +      "first-title": "Oups, an error has occured!",
`first-title` après `content-text` par ordre alphabétique

2020-07-22 10:32 UTC, ghost approved these changes

2020-07-22 19:46 UTC, merged