[FEATURE] Traduire la page de résultat d'une compétence (PIX-801).
1024pix/pix pull request #1662
Opened 2020-07-21 15:05 UTC by jonasgrilleres

## :unicorn: Problème
Dans le cadre de l'internationalisation de Pix, nous devons adapter notre plateforme dans d'autres langues et contextes régionaux.
La page de résultat d'une compétence n'est pas encore traductible.

## :robot: Solution
Ajout des traductions des composants utilisés par la page de résultat d'une compétence.

## :rainbow: Remarques
J'ai déplacé du texte qui était dans une image svg dans une balise `p` (**.competence-results-panel-header__banner-result-comment**) pour faciliter la traduction.

## :100: Pour tester
Sur la review app, mettre la variable d'environnement LOCALE à en.
Terminer une compétence.
Vérifier que les textes sont affichés en langue anglaise.

2020-07-21 15:09 UTC, pix-service commented
I'm deploying this PR to these urls:

- App: https://app-pr1662.review.pix.fr
- Orga: https://orga-pr1662.review.pix.fr
- Certif: https://certif-pr1662.review.pix.fr
- Admin: https://admin-pr1662.review.pix.fr
- API: https://api-pr1662.review.pix.fr/api/

 Please check it out!

2020-07-22 09:35 UTC, lisequesnel commented on mon-pix/app/templates/competences/results.hbs
> +              <p class="competence-results-panel-header__banner-result-comment">{{t 'pages.competence-result.header.too-bad'}}</p>
du coup on perd les images ?

2020-07-23 08:26 UTC, jonasgrilleres commented on mon-pix/app/templates/competences/results.hbs
> +              <p class="competence-results-panel-header__banner-result-comment">{{t 'pages.competence-result.header.too-bad'}}</p>
Non c'est juste du texte, le fond ne change pas.

2020-07-27 15:28 UTC, jonasgrilleres commented on mon-pix/translations/en.json
> +        "not-bad-subtitle": "Encore quelques petits efforts et vous décrocherez le premier niveau.",
ordre alphabetique

2020-07-27 15:28 UTC, jonasgrilleres commented on mon-pix/translations/fr.json
> +        "too-bad": "Tant pix !",
ordre alphabetique

2020-07-27 15:28 UTC, jonasgrilleres commented on mon-pix/translations/fr.json
> +        "reached-level": "Niveau {reachedLevel}",
utiliser niveau du common

2020-07-27 15:28 UTC, jonasgrilleres commented on mon-pix/translations/fr.json
> +        "you-have-earned": "Vous avez"
vous avez X Pix

2020-07-28 06:30 UTC, HEYGUL commented on mon-pix/app/controllers/competences/results.js
> +  pageTitle = this.intl.t('pages.competence-result.title');
On peut commencer à s'inspirer de la proposition de @jonathanperret.
Pour cela, il faut supprimer le contrôleur, et changer le template pour ajouter l'appel au service de traduction :
```
{{page-title (t 'page.competence-result.title')}}
```

2020-07-28 06:30 UTC, HEYGUL commented on mon-pix/translations/fr.json
> +        "too-bad": "Tant pix !",
Il manque un espace insécable (`&nbsp`) avant le `!`.

2020-07-28 07:08 UTC, frinyvonnick approved these changes

2020-07-28 08:46 UTC, MelanieMEB requested changes

2020-07-28 08:46 UTC, MelanieMEB commented on mon-pix/app/controllers/competences/results.js
> +  pageTitle = this.intl.t('pages.competence-result.title');
+1 pour le commentaire de GUL.
Le controller étant alors vide, je pense qu'on peut retirer aussi `@classic`

2020-07-28 08:46 UTC, MelanieMEB commented on mon-pix/app/styles/pages/_competence-results.scss
> +      background: url(/images/banners/congrats-mobile.png) center -240px no-repeat, linear-gradient(0deg, rgb(18, 163, 255) 0%, rgb(61, 104, 255) 100%);
```suggestion
      background: url('/images/banners/congrats-mobile.png') center -240px no-repeat, linear-gradient(0deg, rgb(18, 163, 255) 0%, rgb(61, 104, 255) 100%);
```
Il manque les `'` autour de l'URL.

2020-07-28 08:46 UTC, MelanieMEB commented on mon-pix/translations/fr.json
> +        "too-bad": "Tant pix !",
A mettre sur tous les textes avec le ! pour éviter que le `!` revienne à la ligne seul

2020-07-28 08:46 UTC, MelanieMEB requested changes
<img width="1205" alt="Capture d’écran 2020-07-28 à 10 45 38" src="https://user-images.githubusercontent.com/31532858/88641490-97109a00-d0bf-11ea-93aa-2354f9a4fe71.png">
Problème de cohérence entre les images et le résultat

2020-07-28 15:21 UTC, MelanieMEB approved these changes

2020-07-29 04:21 UTC, HEYGUL approved these changes

2020-07-29 07:38 UTC, MelanieMEB approved these changes

2020-07-29 07:50 UTC, sbedeau commented on mon-pix/app/styles/pages/_competence-results.scss
> +      font-weight: 700;
```suggestion
      font-weight: $font-bold;
```

2020-07-29 07:51 UTC, sbedeau commented on mon-pix/app/styles/pages/_competence-results.scss
> +      padding-top: 18rem;
Pourquoi est-ce qu'on utilise des rem pour le `padding-top` ?

2020-07-29 07:51 UTC, sbedeau commented on mon-pix/app/styles/pages/_competence-results.scss
> +        padding-left: 22rem;
Pareil qu'au dessus

2020-07-29 07:52 UTC, sbedeau commented on mon-pix/app/styles/pages/_competence-results.scss
> +        padding-top: 1rem;
Idem

2020-07-29 07:52 UTC, sbedeau commented on mon-pix/app/styles/pages/_competence-results.scss
> +      padding-top: 18rem;
Idem

2020-07-29 07:52 UTC, sbedeau commented on mon-pix/app/styles/pages/_competence-results.scss
> +        padding-left: 27rem;
Idem

2020-07-29 07:54 UTC, ghost approved these changes
Quelques modifs à faire dans le css mais sinon ok

2020-07-29 13:02 UTC, merged