Tech reduce orga bundle size
1024pix/pix pull request #1669
Opened 2020-07-22 14:41 UTC by bpetetot

## :unicorn: Problème
La taille du bundle de l'application orga paraît importante. 

## :robot: Solution
Analyser le bundle de l'application et les différentes libraries utilisées.

Voici l'état d'origine du bundle : 

![Screenshot 2020-07-22 at 14 46 42](https://user-images.githubusercontent.com/516360/88186984-3b18c200-cc36-11ea-8b40-49d65fd02368.png)

Donc le détail du fichier vendors de production est : 
```
 - dist/assets/vendor-2057f5ecacaf4eaee35d29b9285b6f2a.js: 2.64 MB (826.18 KB gzipped)
```
.
### 1 : Modification des imports de lodash

La plupart des imports des fonctions de lodash sont importée par le module principal de lodash: 
```
import _ from 'lodash'
```
Nous avons donc décidé d'importer uniquement les modules (fonctions) effectivement utilisés dans le code:
```
import sum from 'lodash/sum'
```

**Gain de 21Kb en gzippé**
```
 - dist/assets/vendor-dffce5870969e6fa3495bc4cd2f4742f.js: 2.59 MB (805.96 KB gzipped)
```

### 2 : N'inclure que les icônes Fontawesome utilisées

Dans le schéma de répartition du bundle, on observe 3 libraries d'icônes de fontawesome qui prennent plus de 300Kb.
Nous décidons d'avoir uniquement les icônes utilisées dans le bundle final ([Subsetting icons](https://github.com/FortAwesome/ember-fontawesome#subsetting-icons))

**Important:** Maintenant les icônes utilisées dans l'application doivent être préalablement déclarées dans le fichier `config/icons.js` 

> Au passage nous avons supprimer les 2 packs d'icônes font-awesome (regular et brands), car aucune icone n'étaient utilisées dans ces packs.

![Screenshot 2020-07-22 at 15 03 26 (2)](https://user-images.githubusercontent.com/516360/88187878-605a0000-cc37-11ea-868f-4f9b1197eab8.png)

**Gain de 415Kb en gzippé !!! 🚀**
```
 - dist/assets/vendor-c89ec174a605a30fdaafa416e7d01e3e.js: 1.45 MB (390.67 KB gzipped)
```

### 3 : Remplacer ember-xregexp et xregexp par regexp native

La validation du mot de passe utilise la librarie `xregexp` qui fait près de 23Kb gzippé. Nous l'avons substitué par du javascript natif.

**Gain de 41Kb en gzippé !!!**
```
 - dist/assets/vendor-e828a9d4423c5039b0ad80d89471f503.js: 1.36 MB (359.84 KB gzipped)
```

### 4: Suppression de ember-freestyle

Bien qu'avec un nom très stylé cette librairie n'est pas du tout utilisée. Elle avait pour but à l'origine de constituer un guide de style et d'UI pour orga. Malgré certaines lignes de codes pour éviter d'inclure cette lib dans le bundle, celle-ci était tout de même incluse.

**Gain de 22Kb en gzippé !!!**
```
 - dist/assets/vendor-fd138102bd382265504cc32551987ebe.js: 1.24 MB (327.52 KB gzipped)
```

## Conclusion

Nous nous sommes arrêté là, car nous somme plutôt satisfait du résultat auquel nous rendu, soit : 

# 2.64 MB (826.18 KB gzipped) => 1.24 MB (327.52 KB gzipped)

# Soit une réduction de 60% de la taille du bundle 🎉

## :rainbow: Remarques
- Toujours importer unitairement les fonctions lodash utilisées
- Déclarer les icônes dans le fichier `config/icons`
- Vérifier les tailles de librairies via [Bundlephobia](https://bundlephobia.com/)

## :100: Pour tester
- Vérifier la présence des icônes dans pix-orga
- Vérifier le bon fonctionnement de la validation de mot de passe à la création de compte

2020-07-22 14:45 UTC, pix-service commented
I'm deploying this PR to these urls:

- App: https://app-pr1669.review.pix.fr
- Orga: https://orga-pr1669.review.pix.fr
- Certif: https://certif-pr1669.review.pix.fr
- Admin: https://admin-pr1669.review.pix.fr
- API: https://api-pr1669.review.pix.fr/api/

 Please check it out!

2020-07-22 19:52 UTC, HEYGUL approved these changes
Hâte de voir le résultat sur `mon-pix` !

2020-07-23 09:20 UTC, lisequesnel commented on orga/package.json
> +    "ember-cli-showdown": "^4.5.0",
on a vraiment besoin de le rajouter ? Si c'est une de nos lib qui en a besoin, elle va pas l'importer?

2020-07-23 09:22 UTC, lisequesnel requested changes
- Supprimer le fichier `style-guide.hbs`

2020-07-23 09:28 UTC, lisequesnel commented
Il manque une icône :
![image](https://user-images.githubusercontent.com/23451175/88271564-9d75cf00-ccd7-11ea-9bb2-3b1a093a21c7.png)

2020-07-23 11:57 UTC, laura-bergoens commented on orga/package.json
> +    "ember-cli-showdown": "^4.5.0",
Justement je pense qu'on en a besoin en direct. A mon avis, dans l'ordre des événements du + vieux au + récent :
- import de ember-freestyle pour le truc de la page de style / UI
- besoin de faire des markdowns (et donc on a rien eu besoin d'importer vu que showdown était embarqué dans freestyle)
- retrait de ember-freestyle (et donc de showdown) et crac !

2020-07-23 12:04 UTC, laura-bergoens commented
En fait certaines icônes provenaient du package `regular` qu'on a retiré. Du coup je le remets.
On le voit à l'aide de l'argument `@prefix='far'`

2020-07-23 12:36 UTC, lisequesnel commented
Testé fonctionnellement 👍

2020-07-23 12:36 UTC, lisequesnel approved these changes

2020-07-23 13:13 UTC, merged