[CLEANUP] Faciliter le changement de langue
1024pix/pix pull request #1673
Opened 2020-07-23 15:55 UTC by MelanieMEB

## :unicorn: Problème
Actuellement, pour tester les version EN/FR, il faut changer la variable LOCALE et relancer le build de mon-pix, ce qui est très long.

## :robot: Solution
Au lieu de passer par une variable d'env, passer par un queryParams `?lang=en` qui change la langue du site

## :rainbow: Remarques
Cette solution est amené à évoluer vers une solution finale pour l'utilisateur

## :100: Pour tester
- Aller sur la review app.
- Voir la page de connexion en français
- Ajouter `?lang=en` à l'url
- Voir le site en anglais

2020-07-23 16:00 UTC, pix-service commented
I'm deploying this PR to these urls:

- App: https://app-pr1673.review.pix.fr
- Orga: https://orga-pr1673.review.pix.fr
- Certif: https://certif-pr1673.review.pix.fr
- Admin: https://admin-pr1673.review.pix.fr
- API: https://api-pr1673.review.pix.fr/api/

 Please check it out!

2020-07-24 08:44 UTC, ghost requested changes
En ce moment : 
La transition du setLocale n'est pas définie ce qui empêche le chargement de l'application 
```
Uncaught (in promise) ReferenceError: transition is not defined
    _setLocale https://app-pr1673.review.pix.fr/assets/mon-pix-ae15b453b8c4969fb46a0a0a7d3bc331.js:1600
```

2020-07-28 05:40 UTC, HEYGUL commented on mon-pix/app/routes/application.js
> +  _setLocale(transition) {
La responsabilité de `setLocale` est de changer de langue, aussi je pense qu'il est mieux de passer en paramètre `transition.to.queryParams.lang`.
```suggestion
  _setLocale(queryLocale) {
```

2020-07-28 07:05 UTC, frinyvonnick approved these changes
J'ai vérifié fonctionnellement ✅

2020-07-28 08:06 UTC, HEYGUL approved these changes

2020-07-28 08:12 UTC, ghost approved these changes

2020-07-28 09:03 UTC, merged