[BUGFIX] Corriger l'affichage du texte de bouton de validation des épreuves au format mobile (PIX-604)
1024pix/pix pull request #1681
Opened 2020-07-24 14:12 UTC by alexandrecoin

## :unicorn: Problème
Le texte sur les boutons de validation des épreuves apparait sur deux lignes sur téléphone iphone 6/7 et sony Xperia XZ1 compact.

![Capture d’écran 2020-07-24 à 16 11 28](https://user-images.githubusercontent.com/36371437/88400260-5fa4a380-cdc8-11ea-986c-77c9fdbe05f8.png)

## :robot: Solution
Retirer le padding au format mobile pour les deux boutons de validation et de passage à la question suivante et adapter la taille du texte au petits écrans.

![Capture d’écran 2020-07-24 à 16 06 45](https://user-images.githubusercontent.com/36371437/88399797-b8c00780-cdc7-11ea-98c7-d6a30efe9ae2.png)

## :100: Pour tester
Sur Chrome, Safari et Firefox, ne pas passer par l'émulation de format mobile (impossible de recréer) mais réduire la taille de la fenêtre manuellement via un cliquer-glisser.

2020-07-24 14:16 UTC, pix-service commented
I'm deploying this PR to these urls:

- App: https://app-pr1681.review.pix.fr
- Orga: https://orga-pr1681.review.pix.fr
- Certif: https://certif-pr1681.review.pix.fr
- Admin: https://admin-pr1681.review.pix.fr
- API: https://api-pr1681.review.pix.fr/api/

 Please check it out!

2020-07-24 14:35 UTC, MelanieMEB requested changes
Coté Pix, on essaie au maximum d'être *mobile-first*, c-a-d qui développe le CSS comme si l'écran de base était l'écran mobile (le plus difficile à faire habituellement), et nous mettons des exceptions pour les écrans larges.

Donc nous ne devrions avoir que des `@include device-is('tablet')`.
Ca signifie remonter le font-size dans le global, et mettre l'actuelle dans le include ci-dessus.

2020-07-24 15:34 UTC, celineung approved these changes

2020-07-24 15:35 UTC, ghost approved these changes

2020-07-24 16:01 UTC, jonasgrilleres approved these changes

2020-07-27 07:19 UTC, MelanieMEB approved these changes

2020-07-27 07:40 UTC, merged