[CLEANUP] Extraction sélection des épreuves de certification (PIX-992)
1024pix/pix pull request #1694
Opened 2020-07-28 13:39 UTC by D0C702WH0

## :unicorn: Problème
La sélection des épreuves de certification se faisait par le placement profile service. ça n'est pas la responsabilité du placement profile.

Suite du #1675 

## :robot: Solution
Déplacer algorithme de sélection dans le certification challenge service.

## :rainbow: Remarques
A SUIVRE: 
 - Remplacer _saveCertificationCourse() de retrieve-last-or-create-certification-course par certificationCourseRepository.save()

## :100: Pour tester
Générer plein de tests de certifs avant et après refacto et comparer les résultats

2020-07-28 13:44 UTC, pix-service commented
I'm deploying this PR to these urls:

- App: https://app-pr1694.review.pix.fr
- Orga: https://orga-pr1694.review.pix.fr
- Certif: https://certif-pr1694.review.pix.fr
- Admin: https://admin-pr1694.review.pix.fr
- API: https://api-pr1694.review.pix.fr/api/

 Please check it out!

2020-08-05 15:34 UTC, sroccaserra submitted a review, later dismissed

2020-08-05 15:34 UTC, sroccaserra commented on api/lib/domain/models/Assessment.js
> +  }
```suggestion
  static createForCertificationCourse({ userId, certificationCourseId }) {
    return new Assessment({
      userId,
      certificationCourseId,
      state: Assessment.states.STARTED,
      type: Assessment.types.CERTIFICATION,
    });
  }
```

2020-08-05 15:34 UTC, sroccaserra commented on api/lib/domain/usecases/retrieve-last-or-create-certification-course.js
> +  const newAssessment = Assessment.createForCertificationCourse({ userId, courseId: savedCertificationCourse.id });
```suggestion
  const newAssessment = Assessment.createForCertificationCourse({ userId, certificationCourseId: savedCertificationCourse.id });
```

2020-08-05 15:34 UTC, sroccaserra commented on api/tests/unit/domain/usecases/retrieve-last-or-create-certification-course_test.js
> +            courseId: savedCertificationCourse.id,
```suggestion
            certificationCourseId: savedCertificationCourse.id,
```

2020-08-06 09:27 UTC, Anne-Gaelle-S reviewed
C'est assez dur de faire la revue commit par commit, je vais tenter de faire la revue générale plutôt

2020-08-06 09:27 UTC, Anne-Gaelle-S commented on api/lib/domain/usecases/retrieve-last-or-create-certification-course.js
> +  // certficationProfile = CertificationProfile.from(placementProfile);
Reste un commentaire (peut être enlevé par la suite ?)

2020-08-06 09:27 UTC, Anne-Gaelle-S commented on api/lib/domain/usecases/retrieve-last-or-create-certification-course.js
> +  // certificationCourseChallenges = identifierLesChallenges(certificationProfile); // $$$
ici aussi commentaire

2020-08-06 09:27 UTC, Anne-Gaelle-S commented on api/lib/domain/usecases/retrieve-last-or-create-certification-course.js
> +  // certificationCourseRepository.save(certificationCourse);
com

2020-08-06 09:27 UTC, Anne-Gaelle-S commented on api/lib/domain/services/certification-challenges-service.js
> +    });
Je crois qu'on peut l'écrire aussi comme ça 
```suggestion
    const challenges = _(userCompetences).flatMap(uc => uc.challenges)
```
ou encore
```suggestion
   const challenges = _.flatMap(userCompetences, (uc) => uc.challenges);
```

2020-08-06 09:27 UTC, Anne-Gaelle-S commented on api/tests/unit/domain/usecases/retrieve-last-or-create-certification-course_test.js
> +          };
```suggestion
          const savedCertificationChallenge1 = { id: 'savedCertificationChallenge1' };
          const savedCertificationChallenge2 = { id: 'savedCertificationChallenge2' };
```

2020-08-06 09:27 UTC, Anne-Gaelle-S commented on api/tests/unit/domain/usecases/retrieve-last-or-create-certification-course_test.js
> +          // TODO : use the domainBuilder to instanciate userCompetences
Reste un TODO ici, peut être enlevé par la suite ?

2020-08-06 09:39 UTC, Anne-Gaelle-S approved these changes
Des petites suggestions de style. 
Bravo pour le travail ! 🎉 
Je n'ai pas encore testé fonctionnellement par contre

2020-08-06 09:39 UTC, Anne-Gaelle-S commented on api/lib/infrastructure/repositories/certification-course-repository.js
> +    const certificationCourseToSaveDTO = _adaptModelToDb(certificationCourse);
C'est quoi DTO ?

2020-08-06 09:39 UTC, Anne-Gaelle-S commented on api/tests/integration/infrastructure/repositories/certification-course-repository_test.js
> +      const savedCertificationCourse = (await certificationCourseRepository.save({ certificationCourse }));
```suggestion
      const savedCertificationCourse = await certificationCourseRepository.save({ certificationCourse });
```

2020-08-06 09:39 UTC, Anne-Gaelle-S commented on api/tests/integration/infrastructure/repositories/certification-course-repository_test.js
> +      ];
```suggestion
      const fieldsToOmitInCertificationChallenge = [ 'id', 'courseId' ];
```

2020-08-10 09:42 UTC, EGI-OCTO commented on api/lib/infrastructure/repositories/certification-course-repository.js
> +    const certificationCourseToSaveDTO = _adaptModelToDb(certificationCourse);
Data Transfer Object => c'est un objet donc la raison d'exister est de faire du mapping entre une source et une destination, ici entre un objet du domain `CertificationCourse` et la table certification-courses. C'est en général un objet sans méthode, directement sérialisable, qui contient que des primitives du language, relativement plat. 
T'as souvent ça au moment des entrée/sorties (enregistrement en DB, récupération depuis la DB, avant un appel réseau pour générer la requête, après un appel réseau pour interpréter la réponse, etc).

2020-08-10 10:11 UTC, laura-bergoens commented on api/lib/domain/models/Assessment.js
> +  }
1) J'ai vu que c'est écrit dans le descriptif de PR, qu'il est prévu d'imaginer un nouveau modèle Assessment qui va contenir le strict nécessaire, donc c'est cool !
2) Le suggested change de @sroccaserra est TRES IMPORTANT :
- Le champ courseId est rempli lorsque l'assessment est lié à une Démo (courseId est une chaîne contenant l'id de la démo). Exemple, si vous allez sur le site de [Pix](https://pix.fr/), vous pouvez "Essayer sans inscription". En cliquant, vous êtes redirigé vers https://app.pix.fr/api/courses/rec8rnpOgmfZyd2Ng  (rec8rnpOgmfZyd2Ng est l'id de la démo). Ca va conséquemment créer un assessment dont le courseId va être rec8rnpOgmfZyd2Ng !
- Le champ `certificationCourseId` est bien une clé étrangère vers un `certification-course`

2020-08-10 10:12 UTC, laura-bergoens commented on api/lib/domain/models/CertificationCourse.js
> +    return new CertificationCourse({
Du coup on fait le même constat que pour `Assessment`, ça pourrait être intéressant de lui trouver son petit modèle dédié + validation. Pas sur cette PR évidemment, mais on prend note

2020-08-10 10:39 UTC, laura-bergoens commented on api/lib/domain/services/certification-challenges-service.js
> +      .findUniqByUserIdGroupedByCompetenceId({ userId: placementProfile.userId, limitDate: placementProfile.profileDate });
Le besoin de grouper les knowledge-elements par compétence est legacy je pense.
Nul besoin de le faire ici (en plus, ça ferait gagner un peu de temps, on crache pas dessus).
Je propose d'appeler `knowledgeElementRepository.findUniqByUserId` suivi d'un `KnowledgeElement.findDirectlyValidated`  .   `KnowledgeElement.findDirectlyValidatedFromGroups` est une méthode créée uniquement pour ce contexte, donc on peut la changer sans problème (on verra d'ailleurs que cette méthode fait actuellement un flat() d'une collection péniblement groupée quelques lignes auparavant !)

2020-08-10 10:40 UTC, laura-bergoens commented on api/lib/domain/services/certification-challenges-service.js
> +      }
A vérifier, mais ce `if` est, je pense, très très superflu. Je doute que `challengeRepository.findOperative()` puisse renvoyer des challenges qui n'existent pas :thinking:

2020-08-10 10:42 UTC, laura-bergoens commented on api/lib/domain/services/certification-challenges-service.js
> +    const challengesAlreadyAnswered = challengeIdsCorrectlyAnswered.map((challengeId) => Challenge.findById(allChallenges, challengeId));
Je vous laisse juger de décider si cet appel à la statique a un grand intérêt de lisibilité plutôt que :
```suggestion
    const challengesAlreadyAnswered = challengeIdsCorrectlyAnswered.map((challengeId) => allChallenges.find((challenge) => challenge.id === challengeId));
```

2020-08-10 10:47 UTC, laura-bergoens commented on api/lib/domain/services/certification-challenges-service.js
> +      }
A la place de tout ce morceau je propose :
```js
if (placementProfile.isCompetenceCertifiable(challenge.competenceId)) {
  return ;
}
```
Et dans la classe PlacementProfile une méthode pour faire le boulot (qu'on pourra tester unitairement) :
```js
isCompetenceCertifiable(competenceId) {
  const userCompetence = this.userCompetences.find((uc) => uc.id === competenceId);
  return userCompetence && userCompetence.isCertifiable();
}
```

2020-08-10 10:49 UTC, laura-bergoens commented on api/lib/domain/services/certification-challenges-service.js
> +        .forEach((publishedSkill) => userCompetence.addSkill(publishedSkill));
En vrai il faudrait aussi déresponsabiliser userCompetence (via le retrait de méthodes telles que `addSkill` ou `orderSkillsOfCompetenceByDifficulty`, mais la PR commence à être grosse alors ça peut être fait dans un deuxième temps

2020-08-10 10:50 UTC, laura-bergoens commented on api/lib/domain/services/certification-challenges-service.js
> +        .forEach((publishedSkill) => userCompetence.addSkill(publishedSkill));
On pourrait aussi imaginer pouvoir se priver de la méthode statique `orderSkillsOfCompetenceByDifficulty` en faisant en sorte que les acquis soit naturellement triés par ordre de difficulté lors de l'ajout `addSkill`

2020-08-10 10:51 UTC, laura-bergoens commented on api/lib/domain/services/certification-challenges-service.js
> +          const challenge = _.sample(challengesPoolToPickChallengeFrom);
on en profiterait pas pour faire un "random" maîtrisé / avec seed lié à l'utilisateur ?

2020-08-10 10:51 UTC, laura-bergoens commented on api/lib/domain/services/certification-challenges-service.js
> +          });
:pray:

2020-08-10 10:54 UTC, laura-bergoens commented on api/lib/infrastructure/repositories/certification-course-repository.js
> +    // FIXME : Save all challenges in a single DB request
Vous le faites dans une PR différente?

2020-08-10 11:00 UTC, laura-bergoens commented on api/lib/infrastructure/repositories/certification-course-repository.js
> +    }));
Ne pas faire de `Promise.all`, ce n'est pas sain pour une situation prod-like, here's why :
avec `Promise.all`, on va lancer plein de `save` en même temps (éventuellement jusqu'à : nbCompetences * nbQuestions, donc 16 * 3 = 48 en même temps!). Ce qui veut dire que potentiellement votre seul usecase va réserver, à lui tout seul, plusieurs connexions BDD. C'est pas cool pour les autres requêtes effectuées au sein du même container.

BIG EDIT : (je laisse le commentaire au dessus car on apprend quand même des choses), mais en fait il n'y aura bien qu'une seule connexion BDD sollicitée (car on passe par une transaction). Après bon, on peut quand même chipoté et dire que les faire de façon séquentielle c'est aussi acceptable.
Cela dit, si c'est prévu de toutes les enregistrer d'un coup, alors j'arrête de vous embêter :cat:

2020-08-10 11:00 UTC, laura-bergoens commented on api/lib/infrastructure/repositories/certification-course-repository.js
> +      const certificationChallengeWithCourseId = { ...certificationChallenge, courseId: savedCertificationCourseDTO.id };
Si vous êtes motivés, renommez `courseId` en `certificationCourseId` dans le modèle `CertificationChallenge`, c'est une abérration et courseId fait référence à autre chose dans d'autres contextes donc c'est confus pour rien !

2020-08-10 11:02 UTC, laura-bergoens requested changes
Je requête des changements, mais franchement je suis ravie que ce soit fait. Ce usecase avait besoin d'un petit coup de balai. Pingez moi si vous avez des questions OU si vous voulez qu'on voit les commentaires ensemble OU si vous avez tout pris en compte et qu'il faut que je repasse ma revue.

Je vous aime :heart: , groove is in the heart

EDIT: j'ai qualifié les commentaires en **(PAS BLOQUANT)** ou **(BLOQUANT)**
Bloquant ça veut surtout dire que j'aimerais bien avoir une réponse, pas forcément que la suggestion soit appliquée

2020-08-10 11:49 UTC, EGI-OCTO commented on api/lib/domain/models/Assessment.js
> +  }
@laura-bergoens Est-ce que du coup "courseId" aurait plus de sens en "demoCourseId" ou alors il sert aussi à autre chose et c'est trop restrictif ?

2020-08-10 11:51 UTC, EGI-OCTO commented on api/lib/domain/services/certification-challenges-service.js
> +          const challenge = _.sample(challengesPoolToPickChallengeFrom);
le seed c'est pas possible en JS sans utiliser une lib qu'on a pas encore, on va étudier le truc...

2020-08-10 11:57 UTC, laura-bergoens approved these changes
Vu avec @EGI-OCTO 
Le déplacement tel qu'il est fait là me paraît ISO par rapport à la version d'avant.
L'ensemble des commentaires que j'ai mis sur cette PR sont à garder en TODO List pour les PRs successives de refacto.

2020-08-10 14:11 UTC, merged