[FEATURE]Translate rest of challenge page (PIX-1046)
1024pix/pix pull request #1715
Opened 2020-07-31 09:02 UTC by alexandrecoin

## :unicorn: Problème
Traduction de différentes pages : 

- warning-page
- time-out-jauge
- qcu-proposals
- challenge-statement
- components/challenge-illustration

## :rainbow: Remarques

Je ne suis pas certain du tout de la structure des différentes traductions au sein du JSON dédié.
Merci d'avance pour vos retours.

## :100: Pour tester
Lancer l'appli mon-pix et réaliser des épreuves comportant les différents éléments mentionnés ci-dessus.
Utiliser le query param ?lang=en pour passer l'app en anglais.

2020-07-31 09:06 UTC, pix-service commented
I'm deploying this PR to these urls:

- App: https://app-pr1715.review.pix.fr
- Orga: https://orga-pr1715.review.pix.fr
- Certif: https://certif-pr1715.review.pix.fr
- Admin: https://admin-pr1715.review.pix.fr
- API: https://api-pr1715.review.pix.fr/api/

 Please check it out!

2020-07-31 13:23 UTC, ghost approved these changes
Il faudra penser à mettre le titre de la PR en français

2020-07-31 13:23 UTC, ghost commented on mon-pix/app/templates/components/timeout-jauge.hbs
> +        <img class="svg-timeout-clock-red" src="/images/icon-timeout-red.svg" alt="{{t 'pages.timeout-jauge.over-placeholder'}}">
```suggestion
        <img class="svg-timeout-clock-red" src="/images/icon-timeout-red.svg" alt="{{t 'pages.time-gauge.timeout-placeholder'}}">
```

2020-07-31 13:23 UTC, ghost commented on mon-pix/app/templates/components/timeout-jauge.hbs
> +        <img class="svg-timeout-clock-black" src="/images/icon-timeout-black.svg" alt="{{t 'pages.timeout-jauge.time-remaining-placeholder'}}">
```suggestion
        <img class="svg-timeout-clock-black" src="/images/icon-timeout-black.svg" alt="{{t 'pages.time-gauge.remaining-time-placeholder'}}">
```

2020-07-31 13:23 UTC, ghost commented on mon-pix/app/templates/components/warning-page.hbs
> +    {{t 'pages.warning.instructions.part1'}}<span class="challenge-item-warning__instruction-time">{{allocatedHumanTime}}</span>{{t 'pages.warning.instructions.part2'}}
Il est possible de faire une traduction avec paramètres comme suit
 
```suggestion
    {{t 'pages.warning.instructions' time=allocatedHumanTime}
```

En trad ça donnera quelque chose comme ça :
```
        "instructions": "'Vous disposerez de '<span class="challenge-item-warning__instruction-time">{{time}}</span>' pour réussir la question suivante.'",

```

2020-07-31 13:23 UTC, ghost commented on mon-pix/app/templates/components/warning-page.hbs
> +    {{t 'pages.warning.secondary'}}
```suggestion
    {{t 'pages.warning.further-instructions'}}
```

2020-07-31 13:30 UTC, ghost requested changes
C'est KO pour les timées (https://app-pr1715.review.pix.fr/challenges/recyRNeHrvhUBgunU/preview)
<img width="1070" alt="Screenshot 2020-07-31 at 15 29 41" src="https://user-images.githubusercontent.com/46371288/89039658-bec36480-d342-11ea-8788-0952c19f507b.png">

2020-07-31 13:33 UTC, HEYGUL commented on mon-pix/app/templates/components/warning-page.hbs
> +    <button {{action hasUserConfirmedWarning}} class="challenge-item-warning__confirm-btn">{{t 'pages.warning.start'}}</button>
Comme c'est une action, on le distingue dans une catégorie dédiée.
Pour simplifier dans cette page, comme il n'y a qu'une seule action, je verrai bien la clé `pages.warning.action`

2020-07-31 13:33 UTC, HEYGUL commented on mon-pix/translations/fr.json
> +      "file-type": "Choisissez le type de fichier que vous voulez utiliser"
A priori c'est plutôt une action.

2020-07-31 13:34 UTC, HEYGUL commented on mon-pix/app/templates/components/warning-page.hbs
> +    {{t 'pages.warning.instructions.part1'}}<span class="challenge-item-warning__instruction-time">{{allocatedHumanTime}}</span>{{t 'pages.warning.instructions.part2'}}
Comme il y a du html dans la traduction, il faudra ajouter `htmlSafe=true` dans l'appel.
```
	 {{t 'pages.warning.instructions' time=allocatedHumanTime htmlSafe=true}
```

2020-07-31 14:51 UTC, celineung commented on mon-pix/translations/fr.json
> +      },
Toutes ces clés concernent un téléchargement de fichier
```suggestion
"statement": {
  "file-download": {
    "actions": {
      "description": "Choisissez le type de fichier que vous voulez utiliser"
      "label": "Télécharger"
    }
    "description": "Pix vous laisse le choix du format de fichier à télécharger. Si vous ne savez pas quelle option retenir, conservez le choix par défaut. Il correspond au format de fichier pris en charge par le plus grand nombre de logiciels.",
     "file-type": "fichier .{fileExtension}"
  }
},
```

2020-07-31 14:59 UTC, celineung commented on mon-pix/translations/fr.json
> +
Il pourrait y avoir aussi `qroc-proposal`, `qrocm-proposal`, etc. Comme ils seront ordonné par ordre alphabétique, et pour éviter de les éparpiller, je propose de les regrouper:
```suggestion
"proposals": {
  "answer": {
    "qcu": "La réponse à la question est : "
  }
}

```

2020-07-31 15:01 UTC, alexandrecoin commented on mon-pix/translations/fr.json
> +      },
Comme il s'agit d'actions, ne faudrait-il pas utiliser des verbes d'action ?

```suggestion
    "actions": {
      "choose-type": "Choisissez le type de fichier que vous voulez utiliser"
      "download": "Télécharger"
    }
```

2020-08-03 08:15 UTC, frinyvonnick approved these changes

2020-08-03 08:20 UTC, MelanieMEB approved these changes
OK au global, je suis pour un changement de texte au passage

2020-08-03 08:20 UTC, MelanieMEB commented on mon-pix/translations/fr.json
> +    },
```suggestion
      "timeout-placeholder": "Le temps alloué est dépassé",
      "remaining-time-placeholder": "Il reste du temps pour accomplir l'épreuve"
    },
```
Au passage :)

2020-08-03 09:43 UTC, ghost requested changes
En question timée, le temps est manquant dans la phrase d'avertissement
<img width="1095" alt="Screenshot 2020-08-03 at 11 43 21" src="https://user-images.githubusercontent.com/46371288/89169495-9b84f900-d57e-11ea-8bfd-ab8d793e081a.png">

2020-08-03 09:50 UTC, HEYGUL commented on mon-pix/translations/en.json
> +      "instructions": "You will have '<span class=\"challenge-item-warning__instruction-time\">{{time}}</span>' to answer the next question.",
Il faut un seul `{`, cf https://ember-intl.github.io/ember-intl/versions/master/docs/guide/service-api#methods

2020-08-04 04:48 UTC, HEYGUL approved these changes

2020-08-05 08:25 UTC, jonasgrilleres commented
Petit décalage entre le texte en anglais et l'icône :
![image](https://user-images.githubusercontent.com/5982021/89389152-5a6b2100-d705-11ea-920e-bc1d248f7a0b.png)


C'est à cause du `justify-content: space-around` et de la `width: 100px;` sur `.embed-reboot__content`. Privilégier un `margin-right: 6px;` sur le svg pour que ça s'adapte à toutes les longueurs de texte.

2020-08-05 08:35 UTC, sbedeau commented
> Petit décalage entre le texte en anglais et l'icône :
> ![image](https://user-images.githubusercontent.com/5982021/89389152-5a6b2100-d705-11ea-920e-bc1d248f7a0b.png)
> 
> C'est à cause du `justify-content: space-around` et de la `width: 100px;` sur `.embed-reboot__content`. Privilégier un `margin-right: 6px;` sur le svg pour que ça s'adapte à toutes les longueurs de texte.

Je pense que ça sort un peu du scope de cette PR. J'ai remarqué que les embeds pouvaient aussi faire des "sauts" au chargement. Tout ça semble dessiner le scope d'une PR de debug pour vendredi

2020-08-05 09:15 UTC, ghost approved these changes

2020-08-05 10:13 UTC, merged