[TECH] Glimmerisation des QROC (PIX-1021)
1024pix/pix pull request #1743
Opened 2020-08-05 14:54 UTC by alexandrecoin

## :unicorn: Problème
Phase de glimmerisation et toute la grappe challenge-item n'est pas encore soumise à ce process.

## :robot: Solution
Commencer par la glimmerisation du component challenge-item-qroc

## :rainbow: Remarques
Suppression du rendu dynamique de composant de l'ancienne version d'Ember pour un rendu composant par composant via des ifs (cf. challenge.hbs)

## :100: Pour tester
> _Les instructions pour reproduire le problème, les profils de test, le parcours spécifique à utiliser, etc._

2020-08-05 14:58 UTC, pix-service commented
I'm deploying this PR to these urls:

- App: https://app-pr1743.review.pix.fr
- Orga: https://orga-pr1743.review.pix.fr
- Certif: https://certif-pr1743.review.pix.fr
- Admin: https://admin-pr1743.review.pix.fr
- API: https://api-pr1743.review.pix.fr/api/

 Please check it out!

2020-08-06 08:56 UTC, celineung commented on mon-pix/app/templates/components/challenge-item-qroc.hbs
> +<div {{will-destroy (action this.removeEventListener)}}>
@HEYGUL 
Le modifier `will-destroy` fonctionne? 
Car d'après la doc Ember, il n'est possible d'utiliser que `did-insert` et `did-update`.
`willDestroy` est un lifecycle côté js. 
https://guides.emberjs.com/v3.18.0/upgrading/current-edition/glimmer-components/

2020-08-06 09:12 UTC, celineung commented on mon-pix/app/templates/components/challenge-item-qroc.hbs
> +<div {{will-destroy (action this.removeEventListener)}}>
j'ai testé avec le modifier `will-destroy`, ça a bien l'air d'être appelé pourtant...

2020-08-06 09:46 UTC, HEYGUL commented on mon-pix/app/templates/components/challenge-item-qroc.hbs
> +<div {{will-destroy (action this.removeEventListener)}}>
oui car on utilise : https://github.com/emberjs/ember-render-modifiers

2020-08-07 09:08 UTC, celineung approved these changes

2020-08-07 13:05 UTC, jonasgrilleres approved these changes

2020-08-07 14:57 UTC, ghost requested changes
Quelques notes techniques sans trop d'importance 

Retours fonctionnel : 
- On peut valider une question timée après tiemout
- Delta visuel au niveau des actions 
<img width="1030" alt="Screenshot 2020-08-07 at 16 00 10" src="https://user-images.githubusercontent.com/46371288/89657862-0eb7a380-d8ce-11ea-9fde-a81d463dbd0e.png">
<img width="1042" alt="Screenshot 2020-08-07 at 16 00 19" src="https://user-images.githubusercontent.com/46371288/89657866-0fe8d080-d8ce-11ea-9289-433dcd8a5ddb.png">

2020-08-07 14:57 UTC, ghost commented on mon-pix/app/templates/components/qrocm-proposal.hbs
> +  {{#each _blocks as |block|}}
```suggestion
  {{#each proposalBlocks as |block|}}
```

2020-08-07 14:57 UTC, sbedeau commented on mon-pix/app/templates/components/qcm-proposals.hbs
> +    {{!-- Surrounding label --}}
Je propose de supprimer cette ligne

2020-08-07 14:57 UTC, sbedeau commented on mon-pix/app/templates/components/qcm-proposals.hbs
> +      {{!-- text of proposal  --}}
Je propose de supprimer cette ligne

2020-08-07 14:57 UTC, sbedeau commented on mon-pix/app/components/challenge-item-qcu.js
> +    return checkedInputValues.join('');
Je propose

```suggestion
    const checkedInputValues = [];
    const rawRadioInputs = document.querySelectorAll('input[type="radio"]:checked');
    rawRadioInputs.forEach(function(rawRadioInput) {
      checkedInputValues.push(rawRadioInput.getAttribute('data-value'));
    });
    return checkedInputValues.join('');
```

Et au passage supprimer le // FIXME

2020-08-07 15:47 UTC, celineung commented
>     * Delta visuel au niveau des actions

Corrigé

2020-08-10 10:01 UTC, ghost approved these changes

2020-08-10 11:13 UTC, merged