[DOC] Ajouter méthode de conexion avec fournisseur d'identité externe
1024pix/pix pull request #1773
Opened 2020-08-13 14:20 UTC by octo-topi

## :unicorn: Problème
La connexion avec le GAR (fournisseur d'identité externe de l'éducation nationale, utilisant [SAML](https://en.wikipedia.org/wiki/Security_Assertion_Markup_Language) doit être modifiée, mais son comportement n'est pas clairement connu.
Notamment: quand l'utilisateur s'authentifie-t-il ?

## :robot: Solution
Créer 2 diagrammes:
- un aperçu global avec les termes génériques (navigateur / IDP / ressource)
- une vue détaillée avec les URL et le contenu des request/response

## :100: Pour tester
Se connecter en intégration avec le GAR et utiliser l'outil Réseau
Examiner la source de la route assert [du saml-controller](https://github.com/1024pix/pix/blob/dev/api/lib/application/saml/saml-controller.js)

2020-08-13 14:25 UTC, pix-service commented
I'm deploying this PR to these urls:

- App: https://app-pr1773.review.pix.fr
- Orga: https://orga-pr1773.review.pix.fr
- Certif: https://certif-pr1773.review.pix.fr
- Admin: https://admin-pr1773.review.pix.fr
- API: https://api-pr1773.review.pix.fr/api/

 Please check it out!

2020-08-20 08:53 UTC, yahyayouness commented on docs/security/authenticate_external_IDP.puml
> +navigateur -> utilisateur: affichage passe d'accueil
affichage page d'accueil

2020-08-20 08:54 UTC, yahyayouness commented on docs/security/authenticate_external_IDP.puml
> +utilisateur -> navigateur: Saisie identifiant et mot de passe \net clic sur "Login"
clique

2020-08-20 08:56 UTC, yahyayouness approved these changes

2020-08-20 09:11 UTC, octo-thlo commented
Vu avec @octo-topi 
Le document s'est basé sur les échanges entre un navigateur, le GAR **d'intégration** et Pix, ce qui ne représente pas complètement la réalité.
Quelques exemples : L'utilisateur ne va jamais se connecter au GAR (qui n'est qu'un fournisseur de ressources), mais à son ENT. Lorsqu'il clique sur son icône Pix, c'est un appel directement chez nous qui est émis, et non vers le GAR.

En attendant d'avoir des informations plus proche d'un cas réel, on bloque le merge

2020-08-20 09:12 UTC, octo-thlo requested changes
Suite à mon commentaire

2020-08-20 09:44 UTC, octo-topi commented on docs/security/authenticate_external_IDP.puml
> +navigateur -> utilisateur: affichage passe d'accueil
Corrigé

2020-08-20 09:45 UTC, octo-topi commented on docs/security/authenticate_external_IDP.puml
> +utilisateur -> navigateur: Saisie identifiant et mot de passe \net clic sur "Login"
Corrigé, j'ai passé tout les phrases au style déclaratif
>  (L'utilisateur) clique sur ..

2020-08-20 14:57 UTC, octo-thlo approved these changes

2020-08-21 15:14 UTC, merged