Ajouter le numéro étudiant du participant dans les exports CSV de campagne d'évaluation (PIX-1090).
1024pix/pix pull request #1780
Opened 2020-08-17 13:44 UTC by ajoanny

## :unicorn: Problème
Le numéro étudiant n'apparait pas dans l'export CSV des campagnes des organisations  SUP.

## :robot: Solution
Afficher dans les exports CSV le numéro étudiant du participant.

## :rainbow: Remarques
RAS

## :100: Pour tester
Se connecter à PixOrga avec le compte sup@example.net.
Télécharger les résultat d'une campagnes avec des participants.
Le fichier doit contenir un colonne avec le numéro étudiants des participants

2020-08-17 13:49 UTC, pix-service commented
I'm deploying this PR to these urls:

- App: https://app-pr1780.review.pix.fr
- Orga: https://orga-pr1780.review.pix.fr
- Certif: https://certif-pr1780.review.pix.fr
- Admin: https://admin-pr1780.review.pix.fr
- API: https://api-pr1780.review.pix.fr/api/

 Please check it out!

2020-08-18 08:41 UTC, lisequesnel commented on api/db/seeds/data/organizations-builder.js
> +  });
je suis pas sûre qu'on aie besoin de rajouter un schooling registration, on a déjà sansa stark et joffrey baratheon dans l'orga SUP (id 2) plus haut dans le fichier

2020-08-18 08:45 UTC, lisequesnel commented on api/lib/domain/usecases/start-writing-campaign-assessment-results-to-stream.js
> +    const schoolingRegistration = await schoolingRegistrationRepository.findOneByUserIdAndOrganizationId({ userId: userId, organizationId: organization.id });
je trouve pas ça ouf de faire une requête supplémentaire pour ça, on pourrait l'inclure dans l'appel à `campaignParticipationRepository.findAssessmentResultDataByCampaignId` en faisant une jointure avec `schooling-registrations` ?
Mais peut-être que c'est pas top de faire une jointure supplémentaire non plus. @laura-bergoens un avis ?

2020-08-18 08:46 UTC, lisequesnel commented on api/tests/unit/domain/usecases/start-writing-campaign-assessment-results-to-stream_test.js
> +    context('when organization is SUP if add studentNumber to the CSV', () => {
```suggestion
    context('when organization is SUP', () => {
```

2020-08-18 08:47 UTC, lisequesnel commented on api/tests/unit/domain/usecases/start-writing-campaign-assessment-results-to-stream_test.js
> +      it('should return the header and the data in CSV styles with all competence, domain and skills', async () => {
ici on s'en fiche de vérifier toutes les en-têtes et toutes les data, seule la présence du numéro étudiant nous intéresse. Je propose de changer ce test.
```suggestion
      it('should return the header and the data with student number', async () => {
```

2020-08-18 08:49 UTC, lisequesnel requested changes
J'ai fait quelques commentaires, il faudrait également revoir l'historique des commits git :)

2020-09-01 19:32 UTC, laura-bergoens commented
Je me dis qu'on va oublier de regarder...

2020-09-01 19:32 UTC, closed without merging