[FEATURE] Donner accès à la récupération d'une organisation (PIX-884).
1024pix/pix pull request #1785
Opened 2020-08-18 16:04 UTC by octo-topi

## :unicorn: Problème
> _Décrivez ici le besoin ou l'intention couvert par cette Pull Request._

## :robot: Solution
> _Ajoutez à cet endroit, si nécessaire, des détails concernant la solution technique retenue et mise en oeuvre, des difficultés ou problèmes rencontrés._

## :rainbow: Remarques
> _Des infos supplémentaires, trucs et astuces ?_

## :100: Pour tester
> _Les instructions pour reproduire le problème, les profils de test, le parcours spécifique à utiliser, etc._

2020-08-18 16:08 UTC, pix-service commented
I'm deploying this PR to these urls:

- App: https://app-pr1785.review.pix.fr
- Orga: https://orga-pr1785.review.pix.fr
- Certif: https://certif-pr1785.review.pix.fr
- Admin: https://admin-pr1785.review.pix.fr
- API: https://api-pr1785.review.pix.fr/api/

 Please check it out!

2020-08-18 16:20 UTC, octo-topi commented on orga/app/components/routes/login-form.hbs
> +      L'accès à Pix Orga est limité aux membres invités. Contactez l’administrateur Pix Orga de votre organisation pour
Le démon du reformatage a encore frappé :angry:

2020-08-18 16:20 UTC, octo-topi commented on orga/app/components/routes/login-form.hbs
> +        <div class="login-form__recover-access-message help-text">(réservé aux personnels de direction des établissements scolaires)</div>
Rajouter un peu d'espace entre les deux

2020-08-18 16:21 UTC, octo-topi commented on orga/app/styles/components/login-form.scss
> +    font-size: 0.7rem;
Je n'ai pas mis 0.875 rem comme indiqué dans mockup, sinon ça passe sur 2 lignes

2020-08-19 07:15 UTC, VincentHardouin approved these changes
Ok pour moi avec la remarque d'@ebarbier prise en compte pour l'espace entre les deux liens.

2020-08-19 07:29 UTC, frinyvonnick commented on orga/app/components/routes/login-form.hbs
> +      L'accès à Pix Orga est limité aux membres invités. Contactez l’administrateur Pix Orga de votre organisation pour
Pas terrible l'indentation au niveau des attributs de composants 😕

2020-08-19 07:35 UTC, frinyvonnick commented on orga/app/styles/components/login-form.scss
> +    font-size: 0.7rem;
Il faut enlever la limite de 352px sur la balise `form` afin que ça reste sur une ligne et que le formulaire soit bien aligné avec le message du dessus comme sur la maquette 😄

2020-08-19 07:37 UTC, frinyvonnick commented on orga/app/styles/components/login-form.scss
> +    font-size: 0.7rem;
Il manque aussi un `line-height: 1.375rem;` pour éviter que les deux lignes soient collées.

2020-08-19 11:49 UTC, octo-topi commented on orga/app/components/routes/login-form.hbs
> +      L'accès à Pix Orga est limité aux membres invités. Contactez l’administrateur Pix Orga de votre organisation pour
C'est corigé !

2020-08-19 11:50 UTC, octo-topi commented on orga/app/styles/components/login-form.scss
> +    font-size: 0.7rem;
C'est corigé !

2020-08-19 12:53 UTC, ebarbier approved these changes

2020-08-19 12:58 UTC, ebarbier requested changes
Le lien doit rediriger vers PixOrga et non PixApp:
https://orga.pix.fr/demande-administration-sco, et non pas app.pix.fr

2020-08-19 14:06 UTC, yahyayouness commented
> Le lien doit rediriger vers PixOrga et non PixApp:
> https://orga.pix.fr/demande-administration-sco, et non pas app.pix.fr

Avec le lien en production aussi ? pas de l'environnement actuelle

2020-08-19 14:10 UTC, yahyayouness commented on orga/app/styles/components/login-form.scss
> +    line-height: 22px;
ligne-height en rem ?

2020-08-19 14:11 UTC, yahyayouness approved these changes

2020-08-19 15:01 UTC, ebarbier approved these changes

2020-08-19 15:16 UTC, octo-topi commented on orga/app/styles/components/login-form.scss
> +    line-height: 22px;
C'est corrigé

2020-08-19 15:17 UTC, octo-topi commented
> > Le lien doit rediriger vers PixOrga et non PixApp:
> > https://orga.pix.fr/demande-administration-sco, et non pas app.pix.fr
> 
> Avec le lien en production , pas de l'environnement actuelle ?
J'y ai pensé.. @ebarbier qu'en penses-tu ?

2020-08-19 15:17 UTC, octo-topi commented
> Le lien doit rediriger vers PixOrga et non PixApp:
> https://orga.pix.fr/demande-administration-sco, et non pas app.pix.fr
C'est corrigé

2020-08-20 07:46 UTC, MathieuGilet approved these changes

2020-08-20 08:09 UTC, octo-topi commented
Remplacer le lien en dur par un LinkTo

2020-08-20 08:33 UTC, VincentHardouin approved these changes

2020-08-20 09:05 UTC, merged