[FEATURE] Afficher le lien de récupération uniquement sur la page de connexioon (PIX-1149).
1024pix/pix pull request #1788
Opened 2020-08-20 13:19 UTC by octo-topi

## :unicorn: Problème
Le lien de récupération fait sens sur la page de connexion simple (/connexion).
Il ne fait pas sens sur le composant de connexion dans la page d'acceptation d'invitation (/rejoindre)

## :robot: Solution
N'afficher le lien que sur la page de connexion (route /connexion)

## :rainbow: Remarques
Faire disparaître la scrollbar introduite par l'ajout du message suivant
> (réservé aux personnels de direction des établissements scolaires)

## :100: Pour tester
Se connecter et constater que le lien est présent
Créer une invitation, cliquer sur le lien dans le mail, et constater que le lien est absent

2020-08-20 13:24 UTC, pix-service commented
I'm deploying this PR to these urls:

- App: https://app-pr1788.review.pix.fr
- Orga: https://orga-pr1788.review.pix.fr
- Certif: https://certif-pr1788.review.pix.fr
- Admin: https://admin-pr1788.review.pix.fr
- API: https://api-pr1788.review.pix.fr/api/

 Please check it out!

2020-08-20 13:36 UTC, octo-topi commented
Voilà le résultat en diminuant la taille du navigateur au maximum
![image](https://user-images.githubusercontent.com/56302715/90776702-b97e8780-e2fa-11ea-94a1-9cb675c57f61.png)

2020-08-20 13:48 UTC, ebarbier approved these changes

2020-08-21 07:54 UTC, VincentHardouin requested changes

2020-08-21 07:54 UTC, VincentHardouin commented on orga/app/components/routes/login-form.hbs
> +      {{#if this.showRecoverLink}}
Pas besoin de rajouter un paramètre, il existe : ìsWithInvitation`. Je propose donc 
```suggestion
      {{#unless @isWithInvitation}}
```

2020-08-21 08:21 UTC, octo-topi commented on orga/app/components/routes/login-form.hbs
> +      {{#if this.showRecoverLink}}
Corrigé !

2020-08-21 08:23 UTC, VincentHardouin commented on orga/app/components/routes/login-form.js
> +  @tracked showRecoverLink = this.router.currentRouteName === 'login';
Tout ce fichier peut-être retiré du commit

2020-08-21 08:37 UTC, VincentHardouin commented on orga/app/styles/components/login-form.scss
> +    max-width: 430px;
Pourquoi ajouter le max-with ?

2020-08-21 08:39 UTC, VincentHardouin commented on orga/app/styles/components/login-form.scss
> +    max-width: 430px;
Le nom du commit ne va pas avec l'intention de la PR

2020-08-21 09:03 UTC, octo-topi commented on orga/app/styles/components/login-form.scss
> +    max-width: 430px;
max-width  => voir description de PR _Faire disparaître la scrollbar introduite par l'ajout du message suivant_

2020-08-21 09:04 UTC, octo-topi commented on orga/app/styles/components/login-form.scss
> +    max-width: 430px;
J'ai changé le nom de la PR pour prendre le même titre que le ticket JIRA / commit
_Ne pas afficher le lien de récupération sur la page d'acceptation d'une invitation_

2020-08-21 09:07 UTC, octo-topi commented on orga/app/components/routes/login-form.js
> +  @tracked showRecoverLink = this.router.currentRouteName === 'login';
Corrigé

2020-08-21 09:07 UTC, VincentHardouin approved these changes

2020-08-21 09:18 UTC, thloesch commented on orga/app/components/routes/login-form.hbs
> +      {{#unless @isWithInvitation}}
Pas super fan du manque de test alors qu'on a un `#unless`, mais je ne trouve pas ça bloquant pour autant.

2020-08-21 09:18 UTC, thloesch approved these changes

2020-08-21 09:20 UTC, octo-topi commented on orga/app/components/routes/login-form.hbs
> +      {{#unless @isWithInvitation}}
ok, je le ferais la prochaine fois (conditionnel dans le template = test)

2020-08-21 10:27 UTC, merged