[CLEANUP] Rename Tag and Github action for auto-merge.
1024pix/pix pull request #1827
Opened 2020-09-02 14:01 UTC by lisequesnel

## :unicorn: Problème
La github action d'auto-merge est maintenant fonctionnelle, cependant, elle s'appelle `check` et porte sur le tag `Merge-auto test`.

## :robot: Solution
- Renommer l'action ;
- Faire porter l'auto-merge sur le tag ":rocket: Ready to merge"

## :rainbow: Remarques
Une présentation sera faite pour expliciter comment ça marche, et comment l'utiliser.

## :100: Pour tester
Lorque l'on va vouloir merger cette PR, mettre le label ":rocket: Ready to merge", cela devrait déclencher le check, rebase si besoin, merger, et supprimer la branche.

2020-09-02 14:06 UTC, pix-service commented
I'm deploying this PR to these urls:

- App: https://app-pr1827.review.pix.fr
- Orga: https://orga-pr1827.review.pix.fr
- Certif: https://certif-pr1827.review.pix.fr
- Admin: https://admin-pr1827.review.pix.fr
- API: https://api-pr1827.review.pix.fr/api/

 Please check it out!

2020-09-03 08:24 UTC, frinyvonnick approved these changes

2020-09-03 08:24 UTC, bpetetot approved these changes

2020-09-03 08:31 UTC, bpetetot requested changes

2020-09-03 08:31 UTC, bpetetot commented on .github/workflows/auto-merge.yml
> +          UPDATE_LABELS: ":rocket: Ready to merge"
```suggestion
          UPDATE_LABELS: ":rocket: Ready to Merge"
```

2020-09-03 08:35 UTC, bpetetot approved these changes

2020-09-03 09:12 UTC, merged