[CLEANUP] Retirer l'appel à /pixscore.
1024pix/pix pull request #1830
Opened 2020-09-02 14:29 UTC by MelanieMEB

## :unicorn: Problème
- Quand on affiche le profil cible de l'utilisateur, sur l'accueil ou lors du partage, on fait 2 appels : 
-> Les scorecards
-> Pix score
Le pix-score est la somme des earnedPix des scorecards.

La séparation avait été faite en pensant afficher le Pix Score à d'autres endroits. Ce n'est pas le cas actuellement (ou dans les semaines à venir).

De plus, les routes /pixscore remontes souvent dans les routes les plus lentes (> 2 sec) sur datadog sur les dernières heures.

## :robot: Solution
- Ne plus faire appel à cette route
- Faire la somme coté front dans le model `user`

## :rainbow: Remarques
- La route /pixscore avait été modifié il y a quelques temps pour s'assurer de la cohérence entre les pix gagnés par compétence et la somme total. Ici, on est sur de ne plus avoir ce problème.

## :100: Pour tester
- Aller sur la review App
- Gagner des pix
- Voir une somme correcte sur la home
- Faire la campagne partage de profil `SNAPS123`
- Voir ses Pix
- Partager son profil
- Voir les pix dans orga.

2020-09-02 14:33 UTC, pix-service commented
I'm deploying this PR to these urls:

- App: https://app-pr1830.review.pix.fr
- Orga: https://orga-pr1830.review.pix.fr
- Certif: https://certif-pr1830.review.pix.fr
- Admin: https://admin-pr1830.review.pix.fr
- API: https://api-pr1830.review.pix.fr/api/

 Please check it out!

2020-09-07 15:36 UTC, laura-bergoens commented
Y'a une raison pour laquelle c'est toujours un draft ?

2020-09-08 08:11 UTC, MelanieMEB commented
> Y'a une raison pour laquelle c'est toujours un draft ?

Les conversations suite au Point Tech, qui proposait de remettre la somme coté API, et possiblement dans la routes des scorecards.

2020-09-24 15:32 UTC, jonasgrilleres approved these changes

2020-09-24 15:32 UTC, jonasgrilleres commented on mon-pix/app/models/user.js
> +    return sum(this.scorecards.mapBy('earnedPix'));
pas possible avec un `sumBy` plutôt qu'un `mapBy` ?

2020-10-01 09:49 UTC, sbedeau requested changes
Ok techniquement
Fonctionnellement, l'actualisation semble mal se faire sur le parcours suivant : 
- Je lance l'évaluation d'une compétence 
- Je marque des points / passe un niveau sur la compétence
- Je quitte en cours de parcours avant le check-point
- Je vois que le score n'est pas actualisé des points gagnés 
- Je dois refresh la page pour trouver le bon score 

C'est probablement lié à un recyclage de la page par Ember

2020-10-22 13:25 UTC, closed without merging

2020-10-22 13:26 UTC, MelanieMEB commented
Cette façon de faire à fait débat, mais il faut aussi le faire. Donc il y aura proposition d'une autre PR