[FEATURE] Redisposer les boutons "c'est parti" et "modifier numéro étudiant"
1024pix/pix pull request #1871
Opened 2020-09-11 11:30 UTC by Laurentlcs

## :unicorn: Problème
Suite à la démo, on a remarqué que le bouton "c'est parti" a été mis à gauche au lieu du milieu, et que le bouton "modifier le numéro étudiant" est au milieu au lieu d'être à gauche du champ numéro étudiant.

## :robot: Solution
Rétablir les positions des éléments

## :rainbow: Remarques
RAS

## :100: Pour tester
Se rendre sur une campagne SUP

2020-09-11 11:34 UTC, pix-service commented
I'm deploying this PR to these urls:

- App: https://app-pr1871.review.pix.fr
- Orga: https://orga-pr1871.review.pix.fr
- Certif: https://certif-pr1871.review.pix.fr
- Admin: https://admin-pr1871.review.pix.fr
- API: https://api-pr1871.review.pix.fr/api/

 Please check it out!

2020-09-14 09:31 UTC, lisequesnel requested changes
- Le padding a disparu :
![image](https://user-images.githubusercontent.com/23451175/93068988-6c819d00-f67d-11ea-9118-1c660c27044d.png)
- "Modifier le numéro étudiant" était aligné à droite et non à gauche, et il y a trop de padding, on le lie pas assez avec le champ du dessus je trouve
![image](https://user-images.githubusercontent.com/23451175/93069094-89b66b80-f67d-11ea-8bf5-e1b12d441132.png)

2020-09-14 09:32 UTC, lisequesnel commented on mon-pix/app/components/routes/campaigns/restricted/join-sup.hbs
> +  <div class="join-restricted-campaign__container">
cette classe est déjà utilisé plus haut dans l'arborescence, ce n'est pas correct d'utiliser 2 fois la même classe

2020-09-15 09:44 UTC, Laurentlcs commented on mon-pix/app/components/routes/campaigns/restricted/join-sup.hbs
> +    <button type="button" disabled class="button button--big join-restricted-campaign"><span class="loader-in-button">&nbsp;</span></button>
```suggestion
    <button type="submit" disabled={{this.isLoading}} class="button button--big join-restricted-campaign" {{on 'click' this.submit}}><span class="loader-in-button">&nbsp;</span></button>
```

2020-09-15 09:44 UTC, Laurentlcs commented on mon-pix/app/styles/pages/_join-restricted-campaign.scss
> +    text-align: left;
```suggestion
    text-align: right;
```

2020-09-15 09:44 UTC, Laurentlcs commented on mon-pix/app/styles/pages/_join-restricted-campaign.scss
> +  &__container {
Créer une class spécifique pour centrer le bouton "C'est parti"
```suggestion
  &__form-wrapper {
```

2020-09-15 11:39 UTC, lisequesnel approved these changes
validé fonctionnellement et techniquement 👍

2020-09-15 12:04 UTC, laura-bergoens approved these changes
J'ai suivi la review générale, ok pour moi

2020-09-15 13:49 UTC, merged