[FEATURE] Gérer l'invalidation du jeton d'identification d'un utilisateur externe ( pix-1278)
1024pix/pix pull request #1887
Opened 2020-09-16 16:20 UTC by yahyayouness

## :unicorn: Problème
Quand le jeton d'identification d'un utilisateur externe est invalide, on affiche le message de l'erreur InvalidTemporaryKey: 
_Demande de réinitialisation invalide_.

## :robot: Solution
Ne pas utiliser la méthode decodeIfValid qui renvoie une erreur InvalidTemporaryKey.
Lever une exception InvalidExternalUserTokenError si le jeton d'identification est invalide.

## :rainbow: Remarques
Ceci est un début de refactorisation de cette partie de gestion de jeton.
Le refacto complet sera dans le ticket PIX-1283.

## :100: Pour tester
Se connecter via un jeton expiré ou invalide depuis le GAR.
Un JDD est en cours de préparation.

2020-09-17 07:27 UTC, chrc commented on api/lib/domain/services/token-service.js
> +    throw new InvalidExternalUserTokenError('Une erreur est survenue. Veuillez réessayer de vous connecter.');
Laisser le usecase spécifier le message d'erreur.
Dans le service, le message d'erreur de la class `InvalidExternalUserTokenError` "L’idToken de l’utilisateur externe est invalide." est adéquate.

2020-09-17 07:31 UTC, chrc commented on api/lib/domain/usecases/update-user-samlId.js
> +    throw new InvalidExternalUserTokenError('Une erreur est survenue. Veuillez réessayer de vous connecter.');
Suggestion : Laisser le front gérer ce message spécifique.

2020-09-17 07:34 UTC, chrc commented on api/tests/unit/domain/services/token-service_test.js
>        const accessToken = 'WRONG_DATA';
```suggestion
      const idToken = 'WRONG_DATA';
```

2020-09-17 07:35 UTC, chrc commented on api/tests/unit/domain/services/token-service_test.js
> +      expect(error.message).to.be.equal('Une erreur est survenue. Veuillez réessayer de vous connecter.');
Voir plus haut

2020-09-17 08:45 UTC, yahyayouness commented on api/lib/domain/services/token-service.js
> +    throw new InvalidExternalUserTokenError('Une erreur est survenue. Veuillez réessayer de vous connecter.');
Vu ensemble, on se le garde pour le prochain ticket de refacto. 
L'api envoie un code est à l'IHM de positionner le message correspondant.

2020-09-17 08:45 UTC, yahyayouness commented on api/lib/domain/usecases/update-user-samlId.js
> +    throw new InvalidExternalUserTokenError('Une erreur est survenue. Veuillez réessayer de vous connecter.');
Yes, sera fait dans le ticket suivant de refacto.

2020-09-17 13:22 UTC, octo-topi commented
Test local KO, j'ai le même message qu'avant la PR : `Demande de réinitialisation invalide`

![image](https://user-images.githubusercontent.com/56302715/93475933-7dd6dd80-f8f9-11ea-991d-00b5c1de3c77.png)

2020-09-17 13:24 UTC, pix-service commented
I'm deploying this PR to these urls:

- App: https://app-pr1887.review.pix.fr
- Orga: https://orga-pr1887.review.pix.fr
- Certif: https://certif-pr1887.review.pix.fr
- Admin: https://admin-pr1887.review.pix.fr
- API: https://api-pr1887.review.pix.fr/api/

 Please check it out!

2020-09-17 13:24 UTC, octo-topi requested changes
Le test en local (car pas de RA) est KO
Sinon, le code est OK

2020-09-17 13:29 UTC, octo-topi commented on api/tests/acceptance/application/users/users-controller-update-user-samlid_test.js
> +    it('should respond with a 401 if externalUserToken is invalid', async () => {
Je trouve que 401 (aunathorized) est une bonne idée, pourrais-tu l'indiquer dans le corps de PR ?
=> dans la section :100: Pour tester, vérifier que la réponse de l'API est 401)

2020-09-17 13:33 UTC, octo-topi commented on api/lib/application/error-manager.js
> +  if (error instanceof DomainErrors.InvalidExternalUserTokenError) {
```suggestion
  if (error instanceof DomainErrors.InvalidExternalUserIdTokenError) {
```

2020-09-17 13:40 UTC, octo-topi commented on api/lib/domain/usecases/update-user-samlId.js
> +    throw new InvalidExternalUserTokenError('Une erreur est survenue. Veuillez réessayer de vous connecter.');
Si la levée d'erreur a lieu dans `token-service.extractSamlId,` elle sera cohérente avec l'autre use-case [token-service.extractExternalUserFromIdToken](url) ?

2020-09-17 13:59 UTC, pix-service commented
> Test local KO sur la branche `pix-1252-change-message-invalid-token` avec l'URL [suivante](http://localhost:4200/campagnes?externalUser=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmaXJzdF9uYW1lIjoiRmlyc3QiLCJsYXN0X25hbWUiOiJMYXN0Iiwic2FtbF9pZCI6IlNhbWxJZCIsImlhdCI6MTYwMDI3Mzc2MiwiZXhwIjoxNjAwMjczNzcyfQ.9dlD_pZdpxqUvjkI5riYf2rWGDlLnnYykrKag9xQXdI).
> 
> Le message est le même que celui avant la PR : `Demande de réinitialisation invalide`
> ![image](https://user-images.githubusercontent.com/56302715/93475933-7dd6dd80-f8f9-11ea-991d-00b5c1de3c77.png)

Elle fonctionne bien , un aperçu en RA

![image](https://user-images.githubusercontent.com/38533756/93481347-bfb65280-f8fe-11ea-86d4-ffd5d2283f8f.png)

2020-09-17 14:01 UTC, octo-topi approved these changes

2020-09-17 16:53 UTC, chrc approved these changes

2020-09-18 07:53 UTC, yahyayouness commented on api/lib/application/error-manager.js
> +  if (error instanceof DomainErrors.InvalidExternalUserTokenError) {
L'exception est assez spécifique, on peut garder token et la réutiliser avec deux messages différents si besoin

2020-09-18 08:09 UTC, merged