[FEATURE] Ajout du design du PDF de l'attestation de certification (PIX-1238)
1024pix/pix pull request #1890
Opened 2020-09-17 13:41 UTC by Anne-Gaelle-S

## :unicorn: Problème
> _Décrivez ici le besoin ou l'intention couvert par cette Pull Request._

## :robot: Solution
> _Ajoutez à cet endroit, si nécessaire, des détails concernant la solution technique retenue et mise en oeuvre, des difficultés ou problèmes rencontrés._

## :rainbow: Remarques
> _Des infos supplémentaires, trucs et astuces ?_

## :100: Pour tester
> _Les instructions pour reproduire le problème, les profils de test, le parcours spécifique à utiliser, etc._

2020-09-17 13:48 UTC, pix-service commented
I'm deploying this PR to these urls:

- App: https://app-pr1890.review.pix.fr
- Orga: https://orga-pr1890.review.pix.fr
- Certif: https://certif-pr1890.review.pix.fr
- Admin: https://admin-pr1890.review.pix.fr
- API: https://api-pr1890.review.pix.fr/api/

 Please check it out!

2020-09-18 08:31 UTC, D0C702WH0 approved these changes

2020-09-18 09:26 UTC, EGI-OCTO requested changes

2020-09-18 09:26 UTC, EGI-OCTO commented on api/lib/infrastructure/utils/pdf/certification-attestation-pdf.js
> +          birthdate: getFormattedDate(certificate.birthdate),
euh... la fonction semble prendre en param un `certificate` et en son sein utiliser `certificate.birthdate`, alors que là on lui file direct `certificate.birthdate`. Sûrs que ça marche ?

2020-09-18 09:26 UTC, EGI-OCTO commented on api/lib/infrastructure/utils/pdf/certification-attestation-pdf.js
> +          birthdate: getFormattedDate(certificate.birthdate),
Et si jamais la signature n'est plus `getFormattedDate(certificate)` mais `getFormattedDate(date)`, j'aurais tendance à appeler cette fonction `formatDate(date)`

2020-09-22 16:08 UTC, closed without merging