[TECH] Upgrade de versions d'Ember de 3.18 à 3.21 et packages.
1024pix/pix pull request #1902
Opened 2020-09-22 10:03 UTC by alexandrecoin

## :unicorn: Contexte et enjeu

La version d'Ember pour Pix-Admin est la 3.18. La version actuelle d'Ember est la 3.21. La 3.22 est sur le point de sortir.

L'objet de cette PR est de se mettre à jour pour bénéficier des dernières nouveautés d'Ember, Ember Data et Ember CLI et se simplifier la vie pour les prochaines montées de version.

## :robot: Méthodologie

Nous sommes passés par l'outil Node ember-cli-update, que nous avons installé en global.
Nous avons décidé d'y aller de façon incrémentale : 3.18 → 3.19 → 3.20 → 3.21.

3.18 --> 3.19 

Problème de règle ESLint ember/no-mixins

La montée de version d'Ember (ember-source + ember-data + ember-cli) s'accompagne, via ember-cli-update, de la montée de version d'ESLint et du plugin eslint-plugin-ember. Ce package en particulier a donné lieu à l'apparition d'erreurs de linter dont nous discuterions ultérieurement, et nous avons fait le choix d'updater l'ensemble des packages ESLint dans un commit ultérieur.

Aucun problème à signaler

3.19 --> 3.20

Font Awesome

Le passage de la v3.19 à la v3.20 a induit des avertissements liés à :

- L'usage interne (pas dans Pix) de la méthode @ember/object/getWithDefault résultant en l'apparition de nombreux warning en console lors du lancement de l'application.

Ce problème a été résolu assez simplement en montant de version le package ember-fontawesome de la v0.2.1 à la v0.2.2 (laquelle embarque le correctif lié à getWithDefault).

3.20 --> 3.21

Aucun problème

## :rainbow: Remarques

ESLint : 

L'upgrade des packages liés à ESLint en 9.0.0 a donné lieu à l'apparition d'une nouvelle règle [no-controller-access-in-routes](https://github.com/ember-cli/eslint-plugin-ember/blob/master/docs/rules/no-controller-access-in-routes.md) qui soulève plusieurs problèmes.

En effet, et bien que correspondant en tout point à l'implémentation officielle préconisée par Ember dans la [documentation officielle](https://guides.emberjs.com/release/routing/preventing-and-retrying-transitions/#toc_preventing-transitions-via-willtransition), l'accès au controller dans la fonction `willTransition(transition) {}` d'une route n'est pas autorisé par ESLint.

Exemple : admin/app/routes/authenticated/certifications/certification/informations.js

<img width="731" alt="Capture d’écran 2020-09-22 à 11 55 14" src="https://user-images.githubusercontent.com/36371437/93868259-826d0e80-fcca-11ea-902f-b9e9d5ecfb1f.png">

Nous avons décidé de désactiver la règle de linting sur la route en question.

Documentation liée à ce problème : 
- [ESLint](https://github.com/ember-cli/eslint-plugin-ember/blob/master/docs/rules/no-controller-access-in-routes.md)
- [Ember](https://guides.emberjs.com/release/routing/preventing-and-retrying-transitions/#toc_preventing-transitions-via-willtransition)
- [Discord](https://discordapp.com/channels/480462759797063690/483601670685720591/754986510578745404)

/!\ A noter également que dans le Discord, il est mentionné que la fonction willTransition() est dépréciée, en contradiction avec ce qu'il est possible de trouver dans la documentation officielle.
 

## :100: Pour tester
> _Les instructions pour reproduire le problème, les profils de test, le parcours spécifique à utiliser, etc._

2020-09-22 10:08 UTC, pix-service commented
I'm deploying this PR to these urls:

- App: https://app-pr1902.review.pix.fr
- Orga: https://orga-pr1902.review.pix.fr
- Certif: https://certif-pr1902.review.pix.fr
- Admin: https://admin-pr1902.review.pix.fr
- API: https://api-pr1902.review.pix.fr/api/

 Please check it out!

2020-10-26 10:42 UTC, sbedeau requested changes
**praise:** Merci pour cet update conséquent qui nous inspirera largement sur les autres app 🙏 

**suggestion:** Je pense que cette PR aurait méritée d'être découpée en trois PR (une par montée de version voire plus si on considère les problèmes de certaines updates comme Eslint) pour : 
- faciliter la revue
- économiser votre énergie (PR ouverte il y a 1 mois et faite en parallèle de vos tâches courantes 😨)
- faciliter la transmission de connaissance (ici il est nécessaire de faire la revue pour comprendre que la montée de version Eslint pose problème et non la montée de version d'Ember) 

**suggestion:** Ma connaissance fonctionnelle de Pix est assez limitée. Aussi, ça me plairait bien de faire la revue fonctionnelle avec quelqu'un et de faire le canard/challenger pour aider à sortir éventuellement des sentiers battus

2020-10-26 10:42 UTC, ghost commented on admin/app/app.js
> +import config from 'pix-admin/config/environment';
**question:** Pourquoi on n'utilise plus le chemin relatif ?

2020-10-26 10:42 UTC, ghost commented on admin/app/router.js
> +import config from 'pix-admin/config/environment';
**question:** Pourquoi on n'utilise plus le chemin relatif ?

2020-10-26 10:42 UTC, ghost commented on admin/config/ember-cli-update.json
> +      "version": "3.21.2",
**question:** Est-ce qu'il n'aurait pas fallu passer en 3.20 dans le commit d'avant pour s'assurer que tout était bien embarqué en 3.20 ? 
![Boy that escalled quickly](https://media.giphy.com/media/XWwIzh5GIWWf6/giphy.gif)

2020-10-26 10:42 UTC, ghost commented on admin/package.json
> -    "ember-cli": "~3.19.0",
**question:** Est-ce qu'il n'aurait pas fallu passer en 3.20 dans le commit d'avant pour s'assurer que tout était bien embarqué en 3.20 ?

2020-10-26 10:42 UTC, ghost commented on admin/package.json
> -    "ember-data": "~3.19.0",
**question:** Est-ce qu'il n'aurait pas fallu passer en 3.20 dans le commit d'avant pour s'assurer que tout était bien embarqué en 3.20 ?

2020-10-26 10:42 UTC, ghost commented on admin/package.json
> -    "ember-source": "~3.19.0",
**question:** Est-ce qu'il n'aurait pas fallu passer en 3.20 dans le commit d'avant pour s'assurer que tout était bien embarqué en 3.20 ?

2020-10-26 10:42 UTC, sbedeau commented on admin/tests/test-helper.js
> +import config from 'pix-admin/config/environment';
**question:** Pourquoi on n'utilise plus le chemin relatif ?

2020-10-26 10:42 UTC, sbedeau commented on admin/package.json
> +    "@ember/jquery": "^1.1.0",
**question (non-blocking):** On en a encore beaucoup du jquery ?

2020-10-26 10:42 UTC, sbedeau commented on admin/package.json
> +    "bootstrap": "^4.5.2",
**question (non-blocking):** On en a encore beaucoup du bootstrap ?

2020-10-26 10:42 UTC, sbedeau commented on admin/package.json
> +    "ember-bootstrap": "^4.1.2",
**question (non-blocking):** On en a encore beaucoup du bootstrap ?

2020-10-26 10:42 UTC, sbedeau commented on admin/app/routes/authenticated/certifications/certification/informations.js
> +    // eslint-disable-next-line ember/no-controller-access-in-routes
**suggestion (non-blocking):** Ajouter le disable en haut du fichier, avec un scope étendu à l'ensemble du fichier. L'idée est d'éviter le bruit des commentaires multiples

2020-10-26 10:42 UTC, sbedeau commented on admin/app/routes/authenticated/certifications/certification/details.js
> +    // this.controllerFor('authenticated.certifications.certification.details').certificationId = model.id;
**nitpick (blocking):** Supprimer le code mort

2020-10-26 10:42 UTC, sbedeau commented on admin/app/routes/authenticated/sessions/session.js
> +    // this.controllerFor('authenticated.sessions.session').inputId = model.id;
**nitpick (blocking):** Supprimer le code mort

2020-10-26 10:42 UTC, sbedeau commented on admin/app/routes/authenticated/certifications/certification/informations.js
> +      // eslint-disable-next-line ember/no-controller-access-in-routes
**question (blocking):** Si on désactive la règle Eslint (ce qui est possible, Ember ne suit pas forcément les recommandations Eslint au même moment), pourquoi changer l'implémentation ? 

**suggestion (blocking):** Si j'ai bien compris la démarche, je suggère de faire 
- soit comme avant avec la règle désactivée en attendant que Ember donne la marche à suivre dans sa doc / son discord 
- soit en suivant la règle et conserver la règle activée

2020-10-26 11:27 UTC, jbuget commented on admin/package.json
> +    "ember-bootstrap": "^4.1.2",
à ma connaissance, un peu trop oui, même si on continue de l'enlever

2020-10-26 11:30 UTC, jbuget commented on admin/app/router.js
> +import config from 'pix-admin/config/environment';
C'est ember-cli-update qui fait ça tout seul. Depuis très longtemps déjà (voire depuis toujours), les nouveaux projets Ember sont en chemin absolu par rapport au projet. Mais ce n'est pas bien supporté par les IDE. C'est pour ça qu'on est passé/resté en écriture relative.

2020-10-26 11:34 UTC, jbuget commented on admin/config/ember-cli-update.json
> +      "version": "3.21.2",
Cette ligne traduit qu'on a essayé de passer directement en 3.21 pour constater l'ampleur des dégats ^^. Pour la suite, il me semble que nous avons bien effectué des montées de version successives et incrémentales (n=1). Cela dit, on s'est peut-être vautré dans nos commits ou des les rebase.

2020-10-26 11:34 UTC, jbuget commented on admin/package.json
> +    "@ember/jquery": "^1.1.0",
aucune idée. au pire, de ce que je crois avoir constaté, on en a via certains addons :-/

2020-10-26 12:00 UTC, alexandrecoin commented on admin/config/ember-cli-update.json
> +      "version": "3.21.2",
Les trois premiers commits indiquent bien des montées de versions incrémentales.

2020-10-28 14:39 UTC, alexandrecoin commented on admin/app/app.js
> +import config from 'pix-admin/config/environment';
Nous suivons désormais la façon de faire du CLI Ember qui propose le path pseudo-absolute.

2020-10-28 14:39 UTC, alexandrecoin commented on admin/app/router.js
> +import config from 'pix-admin/config/environment';
Commentaire obsolète

2020-10-28 14:49 UTC, ghost approved these changes

2020-10-28 14:54 UTC, jbuget approved these changes

2020-10-29 16:00 UTC, HEYGUL commented
> 💯 Pour tester

>    Faire une passe globale sur l'appli Pix Certif

Ce n'est pas Pix Admin plutôt ?

2020-10-30 23:58 UTC, merged