[FEATURE] Affichage de la liste filtrée et paginée des profils cible dans Pix Admin (PIX-1322).
1024pix/pix pull request #1923
Opened 2020-09-28 13:38 UTC by lisequesnel

## :unicorn: Problème
Actuellement, les membres de Pix ne peuvent pas voir quels profils cible existent, ne peuvent pas rechercher un profil cible précisément.

## :robot: Solution
Rendre accessible une page qui liste les profils cible, avec une recherche possible sur l'ID et le nom du profil cible.

## :rainbow: Remarques
D'autres améliorations viendront par la suite (affichage du détail, création de profil cible).

## :100: Pour tester
Se connecter à Pix Admin, aller dans le menu "Profils cible" et voir affiché la liste des profils cible. Filtrer et paginer et s'assurer que tout fonctionne correctement.

2020-09-28 13:56 UTC, pix-service commented
I'm deploying this PR to these urls:

- App: https://app-pr1923.review.pix.fr
- Orga: https://orga-pr1923.review.pix.fr
- Certif: https://certif-pr1923.review.pix.fr
- Admin: https://admin-pr1923.review.pix.fr
- API: https://api-pr1923.review.pix.fr/api/

 Please check it out!

2020-09-28 14:30 UTC, laura-bergoens commented on api/lib/application/target-profiles/index.js
> +      path: '/api/target-profiles',
**suggestion (non-blocking) :**
Il me semble que certaines routes admin sont préfixées `/api/admin/...`, je me demande si ça n'aurait pas sa place ici aussi

2020-09-28 14:31 UTC, frinyvonnick approved these changes

2020-09-28 14:32 UTC, frinyvonnick commented
J'ai testé fonctionnellement ✅

2020-09-28 14:37 UTC, laura-bergoens commented on api/lib/application/target-profiles/target-profile-controller.js
> +    const { models: targetProfiles, pagination } = await usecases.findPaginatedFilteredTargetProfiles({ filter: options.filter, page: options.page });
**suggestion (semi-blocking) :** 
Pardon j'invente une nouvelle caractéristique **semi-blocking** parce que j'ai envie d'insister un peu dessus sans vouloir complètement bloquer la PR.
J'ai toujours été pas contente de débugger du code lié à l'affichage de liste paginée/filtrée car je trouve le code peu expressif sur les options de filtre et de page possibles / autorisés.
A cet effet, on avait côté certif ajouté un validateur niveau controller pour vérifier que les options étaient toutes reconnues (et pas laisser des options invisibles remonter jusqu'à la BDD) :
`api/lib/application/sessions/session-controller.js`, on sollicite le sessionValidator pour valider les filtres :
```js
const sessionFiltersValidationSchema = Joi.object({
  id: idSpecification.optional(),
  status: Joi.string().trim()
    .valid(statuses.CREATED, statuses.FINALIZED, statuses.IN_PROCESS, statuses.PROCESSED).optional(),
  resultsSentToPrescriberAt: Joi.boolean().optional(),
  assignedToSelfOnly: Joi.boolean().optional(),
  certificationCenterName: Joi.string().trim().optional(),
});
/* ... */
  validateAndNormalizeFilters(filters, assignedCertificationOfficerId) {
    const { value, error } = sessionFiltersValidationSchema.validate(filters, validationConfiguration);

    if (error) {
      throw EntityValidationError.fromJoiErrors(error.details);
    }

    if (value.assignedToSelfOnly) {
      value.assignedCertificationOfficerId = assignedCertificationOfficerId;
    }

    delete value.assignedToSelfOnly;

    return value;
  },
```
C'est loin d'être parfait (il manque le contrôle de la pagination par exemple), mais on gagnerait à un peu rendre propre l'arrivée côté controller d'options de filtre et de pagination

2020-09-28 14:39 UTC, laura-bergoens commented on api/lib/domain/usecases/find-paginated-filtered-target-profiles.js
> +  return targetProfileRepository.findPaginatedFiltered({ filter, page });
**thought (non-blocking) :**
C'est très passe-plat ici, on hésite presque à faire communiquer le controller et le répo en live.
J'ai pas vraiment d'avis moi non plus, je me demande si un tel court-circuitage reste clean-archi compliant

2020-09-28 14:44 UTC, laura-bergoens commented on api/lib/infrastructure/repositories/target-profile-repository.js
> +    qb.whereRaw('CAST(id as TEXT) LIKE ?', `%${id.toString().toLowerCase()}%`);
**issue (blocking) :**
Ce cast nous empêche de rechercher par ID via l'index naturel sur la colonne ID. Bon, on n'a pas encore beaucoup de targetProfile donc c'est pas très grave, mais bon de façon générale c'est smelly de devoir faire ce cast. A mon sens, c'est à la charge de l'appelant (direct domaine, ou indirect controller) de faire le cast de cette colonne

2020-09-28 14:46 UTC, laura-bergoens commented on api/lib/infrastructure/repositories/target-profile-repository.js
> +        const targetProfiles = bookshelfToDomainConverter.buildDomainObjects(BookshelfTargetProfile, models);
**suggestion (non-blocking) :**
Ce répo retourne plusieurs type de targetProfiles différents quand on y regarde de plus près. Parfois y'a les skills `(_getWithAirtableSkills`) parfois pas. Donc on a des modèles TargetProfile incomplet. C'est le cas sur cet appel.
Plus généralement, je serais d'avis à créer un read-model spécifique pour cet usage (un genre de summary), destiné à être affiché dans une liste

2020-09-28 14:47 UTC, laura-bergoens requested changes
Je praise l'initiative mais j'ai quelques remarques bloquantes

2020-09-28 16:07 UTC, lisequesnel commented on api/lib/infrastructure/repositories/target-profile-repository.js
> +    qb.whereRaw('CAST(id as TEXT) LIKE ?', `%${id.toString().toLowerCase()}%`);
en fait, je me pose la question, a-t-on vraiment besoin de faire un `LIKE` sur un ID ? Je dirais qu'on a l'ID ou on l'a pas. Du coup je me dis qu'on pourrait faire un match strict.

2020-09-28 16:08 UTC, lisequesnel commented on api/lib/infrastructure/repositories/target-profile-repository.js
> +        const targetProfiles = bookshelfToDomainConverter.buildDomainObjects(BookshelfTargetProfile, models);
Je pense c'est une bonne idée, mais peut-être dans une PR ultérieure plutôt

2020-09-28 16:09 UTC, lisequesnel commented on api/lib/application/target-profiles/index.js
> +      path: '/api/target-profiles',
En fait je ne sais pas si c'est une convention ou pas, puisqu'il y a des routes où ce n'est pas le cas. Ça vaut le coup de poser la question.

2020-09-29 09:05 UTC, bpetetot commented on api/lib/application/target-profiles/index.js
> +      config: {
**suggestion (non-blocking) :**
Ajouter une validation JOI des paramètres de recherche (id, name...)

2020-09-29 09:05 UTC, bpetetot commented on api/lib/domain/usecases/find-paginated-filtered-target-profiles.js
> +  return targetProfileRepository.findPaginatedFiltered({ filter, page });
En effet, dans ce cas ça ne paraît que passe plat. Sur pix-editor, il y a une proposition d'ADR dans ce sens (https://github.com/1024pix/pix-editor/pull/46). Je ne sais pas si c'est quelques chose qu'on souhaite étendre à l'API. Peut-être un point à évoquer en tech time ?
Mais dans l'attente d'une réponse claire, je laisserai tel quel avec le use case.

2020-09-29 09:05 UTC, bpetetot commented on api/lib/infrastructure/repositories/target-profile-repository.js
> +    qb.whereRaw('CAST(id as TEXT) LIKE ?', `%${id.toString().toLowerCase()}%`);
Je suis d'accord, un `LIKE` ne me parait en effet pas nécessaire. Quand on recherche par identifiant, on s'attend à une recherche exacte et non flou.

2020-09-29 09:05 UTC, bpetetot commented on api/tests/integration/infrastructure/repositories/target-profile-repository_test.js
> +        expect(pagination).to.deep.equal(expectedPagination);
**Suggestion (non-blocking):**
Tester à nouveau la pagination dans ce test ne me semble pas nécessaire. Les 2 premiers `expect` sont suffisants

2020-09-29 09:05 UTC, bpetetot commented on api/tests/integration/infrastructure/repositories/target-profile-repository_test.js
> +        expect(pagination).to.deep.equal(expectedPagination);
**Suggestion (non-blocking):**
Tester à nouveau la pagination dans ce test ne me semble pas nécessaire.

2020-09-29 09:05 UTC, bpetetot commented on api/tests/integration/infrastructure/repositories/target-profile-repository_test.js
> +        expect(pagination).to.deep.equal(expectedPagination);
**Suggestion (non-blocking):**
Tester à nouveau la pagination dans ce test ne me semble pas nécessaire. Les 2 premiers `expect` sont suffisants

2020-09-29 09:05 UTC, bpetetot commented on api/tests/integration/infrastructure/repositories/target-profile-repository_test.js
> +        expect(pagination).to.deep.equal(expectedPagination);
**Suggestion (non-blocking):**
Tester à nouveau la pagination dans ce test ne me semble pas nécessaire.

2020-09-29 09:05 UTC, bpetetot commented on api/tests/unit/application/target-profiles/index_test.js
> +    });
**suggestion (non-blocking):**
Ce test me parait pas utile, car j'ai l'impression qu'on teste le fait que le mock retourne juste une 200

2020-09-30 09:40 UTC, lisequesnel commented on api/lib/application/target-profiles/target-profile-controller.js
> +    const { models: targetProfiles, pagination } = await usecases.findPaginatedFilteredTargetProfiles({ filter: options.filter, page: options.page });
dans le `index.js`est-ce ok ?
![image](https://user-images.githubusercontent.com/23451175/94669502-9c819f00-0311-11eb-9ae1-cfdb43c0c23c.png)
Le cas du sessionValidator est dans le `domain`, or je ne pense pas que la validation des filtres sur une route aie sa place dans le domaine

2020-09-30 09:47 UTC, lisequesnel commented on api/lib/application/target-profiles/index.js
> +      config: {
est-ce que ça c'est ok ?
https://github.com/1024pix/pix/pull/1923#discussion_r497378039

2020-09-30 13:46 UTC, lisequesnel commented on api/lib/application/target-profiles/index.js
> +      path: '/api/target-profiles',
j'ai rajouté `/admin`

2020-09-30 13:46 UTC, lisequesnel commented on api/tests/unit/application/target-profiles/index_test.js
> +    });
test changé

2020-10-01 07:12 UTC, laura-bergoens commented on api/lib/application/target-profiles/target-profile-controller.js
> +    const { models: targetProfiles, pagination } = await usecases.findPaginatedFilteredTargetProfiles({ filter: options.filter, page: options.page });
En tout cas je trouve ça très satisfaisant que cela apparaisse sur les routes.
J'ai une dernière **suggestion** mais **non-blocking** ce coup-ci, on peut pousser le bouchon et profiter pour fixer des valeurs limites de pagination ?

2020-10-01 07:14 UTC, laura-bergoens approved these changes

2020-10-01 08:09 UTC, lisequesnel commented on api/lib/application/target-profiles/target-profile-controller.js
> +    const { models: targetProfiles, pagination } = await usecases.findPaginatedFilteredTargetProfiles({ filter: options.filter, page: options.page });
je pense qu'il faut qu'on y réfléchisse, parce qu'il faut définir une valeur etc. Ça se fait pas en 2-2

2020-10-01 10:18 UTC, merged