Gérer la mise à jour des étudiant des établissements supérieurs avec l'import(PIX-1124).
1024pix/pix pull request #1926
Opened 2020-09-28 15:28 UTC by ajoanny

## :unicorn: Problème
Les inscriptions surnuméraire sont mise à jour à partir lors de l'import d'étudiants.
A cause des inscriptions surnuméraires il est possible de se tromper lors de la mise à jour et de changer les informations du mauvais l'élève si celui-ci c'est trompé de numéro étudiant.
Dans ce cas de figure on pourrait attribuer à un élève les résultat d'un autre élève ce qui n'est pas acceptable.

## :robot: Solution
Mettre à jour les inscriptions surnuméraires uniquement s'il y a le bon nom, prénom et date de naissance.

## :rainbow: Remarques
RAS

## :100: Pour tester
Tester la mise à jour des élèves vie l'import (Pour une organisation SUP)

Les différent cas :

![8e7e9570-3901-413b-a228-117600056a2d](https://user-images.githubusercontent.com/28776351/94452597-02561580-01b0-11eb-836b-46b0801299ba.png)

2020-09-28 15:33 UTC, pix-service commented
I'm deploying this PR to these urls:

- App: https://app-pr1926.review.pix.fr
- Orga: https://orga-pr1926.review.pix.fr
- Certif: https://certif-pr1926.review.pix.fr
- Admin: https://admin-pr1926.review.pix.fr
- API: https://api-pr1926.review.pix.fr/api/

 Please check it out!

2020-10-01 09:20 UTC, ajoanny commented on api/lib/domain/models/SchoolingRegistration.js
>      nationalStudentId,
ajouter ce param au builder

2020-10-01 09:20 UTC, ajoanny commented on api/lib/infrastructure/repositories/higher-schooling-registration-repository.js
> +        .save(attributes, { patch: true });
a creuser sans patch true

2020-10-01 09:20 UTC, ajoanny commented on api/lib/domain/usecases/import-higher-schooling-registrations.js
> +const {  areTwoStringsCloseEnough } = require('../services/string-comparison-service.js');
espace en trop

2020-10-01 09:20 UTC, ajoanny commented on api/tests/integration/domain/usecases/import-higher-schooling-registrations_test.js
> +  context('when there is no registrations for the organization',() => {
schooling registration

2020-10-01 09:20 UTC, ajoanny commented on api/tests/integration/domain/usecases/import-higher-schooling-registrations_test.js
> +      context('which matches by student number but noy by birthdate',() => {
not

2020-10-01 09:20 UTC, ajoanny commented on api/lib/infrastructure/repositories/higher-schooling-registration-repository.js
> +    const attributes = _.pick(higherSchoolingRegistration, ATTRIBUTES_TO_SAVE);
vérifier que la réconciliation marche

2020-10-01 09:20 UTC, ajoanny commented on api/lib/domain/usecases/import-higher-schooling-registrations.js
> +const {  areTwoStringsCloseEnough } = require('../services/string-comparison-service.js');
virerles orderby en trop

2020-10-01 09:20 UTC, ajoanny commented on api/lib/domain/usecases/import-higher-schooling-registrations.js
> +  return existingRegistrations.length === 1 && isMatchingWithExistingRegistrationData(registration, existingRegistrations[0]);
length === 1 dans la fonction isMatching

2020-10-01 09:20 UTC, ajoanny commented on api/tests/integration/domain/usecases/import-higher-schooling-registrations_test.js
> +    context('when there is a no supernumerary registration matching by student number',() => {
mauvaise description

2020-10-01 09:51 UTC, ajoanny commented on api/lib/domain/usecases/import-higher-schooling-registrations.js
> +  return existingRegistrations.length === 1 && isMatchingWithExistingRegistrationData(registration, existingRegistrations[0]);
@laura-bergoens 
C'est pas terrible à la lecture je trouve
```js
return existingRegistrations.length == 1 &&
    (!existing.isSupernumerary
      ||
      (areTwoStringsCloseEnough(current.lastName, existing.lastName, 0.2)
        && areTwoStringsCloseEnough(current.firstName, existing.firstName, 0.2)
        && current.birthdate === existing.birthdate)
    );
```

2020-10-01 10:07 UTC, ajoanny commented
@estellelandry @lisequesnel @laura-bergoens @Benjamin1024 @frinyvonnick @Laurentlcs Ca fait des timeout  😢

2020-10-01 12:54 UTC, bpetetot approved these changes

2020-10-01 13:11 UTC, ajoanny commented on api/lib/infrastructure/repositories/higher-schooling-registration-repository.js
> +        .save(attributes, { patch: true });
J'ai trouvé ça dans la doc du `save` de bookshelf.

Le but du  patch c'est pas de réellement de faire un update.  On en passe pas par des instances des models bookshelf du coup le patch n'est pas "utile" il fait ce qu'on veut par effet de bord.
<img width="769" alt="Capture d’écran 2020-10-01 à 15 02 07" src="https://user-images.githubusercontent.com/28776351/94812515-22c3e100-03f7-11eb-97ac-d7b6fd3bf24e.png">

L'option à utiliser c'est plus celle-ci
<img width="643" alt="Capture d’écran 2020-10-01 à 15 11 15" src="https://user-images.githubusercontent.com/28776351/94813517-610dd000-03f8-11eb-8588-0fad470791e2.png">

2020-10-05 15:16 UTC, bpetetot commented
On est bien niveau mémoire 
![image](https://user-images.githubusercontent.com/516360/95098073-83705800-072e-11eb-8622-e98d1ff66733.png)

2020-10-05 15:26 UTC, bpetetot commented on api/lib/infrastructure/perftimer.js
> +module.exports = PerfTimer;
**Info:**
J'ai conservé cette classe car elle peut être utile dans le futur pour des tests de performances ciblés.

2020-10-05 15:38 UTC, bpetetot commented on api/lib/domain/usecases/import-higher-schooling-registrations.js
> +  });
**Info:**
J'ai vraiment du mal avec ce terme **"Supernumerary"** et **"Non supernumerary"** qui est difficilement compréhensible techniquement et fonctionnellement.

Une autre formulation pourrait être **"Inconnu dans l'organisation"** ou **"Connu dans l'organisation"**

Du coup les fonctions pourraient être renommées de cette façon:
- `findStudentNumbersNonSupernumerary ` => `findKnownStudentNumbers`
- `saveNonSupernumerary ` => `updateKnownRegistration`
- `findSupernumerary` => `findUnknownRegistrations`

Vous en pensez quoi ?

2020-10-05 15:43 UTC, bpetetot commented on api/lib/domain/usecases/import-higher-schooling-registrations.js
> +        await higherSchoolingRegistrationRepository.save(registration, domainTransaction);
**Question:**
Je trouve ça étrange de _setter_ l'`id` sur l'objet avant le `save`.
Est-ce qu'il ne faudrait pas plutôt avoir une méthode save de ce type: `updateById(id, attrsToUpdate)`

2020-10-06 09:19 UTC, lisequesnel commented on api/lib/domain/usecases/import-higher-schooling-registrations.js
> +  });
Je suis d'avis de laisser comme ça, jusqu'à ce que côté métier une réflexion ait été mûrie sur cet aspect. Si ce terme change, autant le changer un seule fois.

2020-10-06 09:22 UTC, lisequesnel commented on api/lib/domain/usecases/import-higher-schooling-registrations.js
> +        await higherSchoolingRegistrationRepository.save(registration, domainTransaction);
ok je vois ce qui te dérange. Peut-être que quelque chose comme ça est mieux : 
```
const registration = {
... matchingRegistration,
attributesToUpdate
};
await higherSchoolingRegistrationRepository.save(registration, domainTransaction);
```

2020-10-06 09:23 UTC, lisequesnel commented on api/lib/domain/models/SchoolingRegistration.js
> +    isSupernumerary,
pourquoi on a besoin d'ajouter cet attribut au modèle du domaine ? Il y a déjà un modèle `HigherSchoolingRegistration`

2020-10-06 09:26 UTC, lisequesnel commented on api/lib/domain/usecases/import-higher-schooling-registrations.js
> +}
**suggestion** : est-ce que ce genre de méthode n'aurait pas plutôt sa place dans un service ?

2020-10-06 09:32 UTC, lisequesnel requested changes

2020-10-06 09:32 UTC, lisequesnel commented on api/lib/domain/usecases/import-higher-schooling-registrations.js
> +      && areTwoStringsCloseEnough(registration.firstName, existing.firstName, LEVENSHTEIN_DISTANCE)
**suggestion (blocking)** : là on ne fait la distance de levenshtein que sur le nom et prénom, mais côté import on a aussi deuxième et troisième prénom, ainsi que le nom d'usage. Il faut également faire la distance d'édition pareillement, comme pour le SCO.
D'ailleurs ça m'étonne qu'on ne puisse pas réutiliser ce qui a déjà été réalisé.

2020-10-06 09:53 UTC, bpetetot commented on api/lib/domain/usecases/import-higher-schooling-registrations.js
> +      && areTwoStringsCloseEnough(registration.firstName, existing.firstName, LEVENSHTEIN_DISTANCE)
Oui en effet, après avoir regardé, je pense qu'on peut réutiliser ça. 👍

2020-10-06 09:54 UTC, bpetetot commented on api/lib/domain/usecases/import-higher-schooling-registrations.js
> +}
Suite au commentaire suivant, je vais voir ce qu'on peut réutiliser avec ce qui a été au niveau du SCO

2020-10-06 09:59 UTC, bpetetot commented on api/lib/domain/models/SchoolingRegistration.js
> +    isSupernumerary,
Oui bien vu, c'est étrange, je ne sais pas pourquoi ce modèle a été modifié. Je vais vérifier pourquoi.

2020-10-06 14:07 UTC, bpetetot commented on api/lib/domain/models/SchoolingRegistration.js
> +    isSupernumerary,
J'ai supprimer ces modifications inutiles et en plus j'ai ajouté un commit pour nettoyer un domainBuilder qui avait du code non utilisé

2020-10-06 14:19 UTC, lisequesnel commented on api/tests/tooling/domain-builder/factory/build-schooling-registration.js
>    });
**suggestion** : du coup, 
```
    studentNumber,
    email,
    educationalTeam,
    department,
    group,
    diploma
```
ne sont pas utilisés dans le modèle du domaine, autant également les enlever du builder

2020-10-06 14:22 UTC, lisequesnel approved these changes
sous réserve que mon dernier commentaire soit pris en compte, tout est ok :)

2020-10-06 14:40 UTC, lisequesnel commented
Validé fonctionnellement ✅

2020-10-07 15:33 UTC, merged