[DOC] Mise à jour de la documentation des tests de bout-en-bout.
1024pix/pix pull request #1953
Opened 2020-10-02 09:43 UTC by octo-topi

## :unicorn: Problème
Le document actuel:
- ne mentionne pas l'installation de l'exécutable
- n'explique pas comment visualiser les étapes intermédiaires

## :robot: Solution
Ajouter ces éléments

## :rainbow: Remarques
Le nom de la branche n'est pas parfait, mais je voulais éviter un évasif `doc-enhance-cypress-doc"

## :100: Pour tester
Lire le fichier et exécuter les commandes pour vérifier leur exactitude

2020-10-02 09:48 UTC, pix-service commented
I'm deploying this PR to these urls:

- App: https://app-pr1953.review.pix.fr
- Orga: https://orga-pr1953.review.pix.fr
- Certif: https://certif-pr1953.review.pix.fr
- Admin: https://admin-pr1953.review.pix.fr
- API: https://api-pr1953.review.pix.fr/api/

 Please check it out!

2020-10-02 09:53 UTC, chrc approved these changes

2020-10-02 12:10 UTC, sbedeau approved these changes

2020-10-02 12:10 UTC, sbedeau commented on high-level-tests/e2e/README.md
> +npx cypress install
**thought (non-blocking):** Est-ce qu'on ne devrait pas plutôt mettre en avant ?
```suggestion
npm ci
```

2020-10-02 12:11 UTC, sbedeau commented on high-level-tests/e2e/README.md
> +Cypress est un framework de test end to end qu'on utilise pour les tests de non-régression end to end.
```suggestion
Cypress est un framework de test end to end qu'on utilise pour les tests de non-régression fonctionnelle back-end vers front-end.
```

2020-10-02 12:19 UTC, sbedeau requested changes
**issue (blocking):** Je n'ai pas trouvé de mentions au sujet du cache. Je suggère d'ajouter une section pour reset le cache redis + faire pointer vers le Airtable de Cypress

2020-10-02 12:19 UTC, sbedeau commented on high-level-tests/e2e/README.md
> +Lancer Postgres avec docker via le fichier `docker-compose.yml` (`~/pix`)
```suggestion
Lancer Postgres avec docker grâce au fichier `docker-compose.yml` depuis `~/pix`
```

2020-10-02 12:19 UTC, sbedeau commented on high-level-tests/e2e/README.md
>  >Le navigateur par défaut de Cypress (Electron 59) échoue à une étape de `wait` (potentiellement en relation avec https://github.com/cypress-io/cypress/issues/2387).
**:thought (non-blocking):** Cette issue est fermée, est-ce que le commentaire est toujours pertinent / informatif ?

2020-10-06 07:11 UTC, yahyayouness approved these changes

2020-10-07 07:30 UTC, octo-topi commented on high-level-tests/e2e/README.md
> +Lancer Postgres avec docker via le fichier `docker-compose.yml` (`~/pix`)
J'ai enlevé ce besoin en faisant réféeence au guide d'installation

2020-10-07 07:31 UTC, octo-topi commented on high-level-tests/e2e/README.md
>  >Le navigateur par défaut de Cypress (Electron 59) échoue à une étape de `wait` (potentiellement en relation avec https://github.com/cypress-io/cypress/issues/2387).
Bien vu, j'ai enlevé et rmentionné explicitement les versions supportées (>64) et la raison du choix de Chrome ici

2020-10-07 07:31 UTC, octo-topi commented on high-level-tests/e2e/README.md
> +Cypress est un framework de test end to end qu'on utilise pour les tests de non-régression end to end.
Corrigé !

2020-10-07 07:31 UTC, octo-topi commented on high-level-tests/e2e/README.md
> +npx cypress install
Bien vu, corrigé !

2020-10-07 07:41 UTC, octo-topi commented
> **issue (blocking):** Je n'ai pas trouvé de mentions au sujet du cache. Je suggère d'ajouter une section pour reset le cache redis + faire pointer vers le Airtable de Cypress

C'est tout à fait juste, et ce serait utile ! Tu me l'as expliqué il y a quelques mois, j'en garde un schéma, mais je n'ai jamais pu mettre en pratique. 

![image](https://user-images.githubusercontent.com/56302715/95301640-26d18200-0881-11eb-88d2-50c9151635c2.png)

Je propose de 
- merger cette PR telle quelle
- que tu ouvres une PR pour ajouter cette section
- que je fasse la review avec des yeux de débutant :smile:

2020-10-07 10:20 UTC, sbedeau approved these changes

2020-10-07 14:47 UTC, celineung approved these changes

2020-10-07 14:50 UTC, merged