[BUG] Amélioration dans Mon-Pix de la gestion des erreurs sur la page Réinitialiser le mot de passe (PIX-1385).
1024pix/pix pull request #1986
Opened 2020-10-09 06:43 UTC by chrc

## :unicorn: Problème
> _Décrivez ici le besoin ou l'intention couvert par cette Pull Request._

## :robot: Solution
> _Ajoutez à cet endroit, si nécessaire, des détails concernant la solution technique retenue et mise en oeuvre, des difficultés ou problèmes rencontrés._

## :rainbow: Remarques
> _Des infos supplémentaires, trucs et astuces ?_

## :100: Pour tester
> _Les instructions pour reproduire le problème, les profils de test, le parcours spécifique à utiliser, etc._

2020-10-09 06:48 UTC, pix-service commented
I'm deploying this PR to these urls:

- App: https://app-pr1986.review.pix.fr
- Orga: https://orga-pr1986.review.pix.fr
- Certif: https://certif-pr1986.review.pix.fr
- Admin: https://admin-pr1986.review.pix.fr
- API: https://api-pr1986.review.pix.fr/api/

 Please check it out!

2020-10-09 09:40 UTC, yahyayouness commented
Une petite amélioration est de rendre le champ obligatoire (required) . Si le champ vide, on se retrouve avec un appel voué à l'échec.

2020-10-09 09:46 UTC, yahyayouness commented on mon-pix/app/components/update-expired-password-form.js
>    @tracked authenticationHasFailed = null;
Déclarer la variable errorMessage 
```suggestion
    @tracked errorMessage = null;
```

2020-10-09 09:49 UTC, yahyayouness commented on mon-pix/app/components/update-expired-password-form.js
>    @tracked authenticationHasFailed = null;
Si la variable errorMessage n'est pas réinitialiser, on se retrouve avec les deux erreurs affichées.
[image](https://user-images.githubusercontent.com/10045497/95569158-7d77c100-0a25-11eb-9bea-67e87f52aaa5.png)

2020-10-09 09:51 UTC, yahyayouness commented on mon-pix/app/components/update-expired-password-form.js
>      try {
```suggestion
    try {
    this.errorMessage = null;
```

2020-10-09 10:27 UTC, chrc commented on mon-pix/app/components/update-expired-password-form.js
>    @tracked authenticationHasFailed = null;
Done

2020-10-09 10:28 UTC, chrc commented on mon-pix/app/components/update-expired-password-form.js
>      try {
Done

2020-10-09 10:33 UTC, yahyayouness approved these changes

2020-10-09 11:12 UTC, chrc commented
> Une petite amélioration est de rendre le champ obligatoire (required) . Si le champ vide, on se retrouve avec un appel voué à l'échec.

Plus généralement, la soumission devrait être impossible si le champ n'est pas rempli et le format de mot de passe invalide !

2020-10-12 09:29 UTC, octo-topi commented
Avec Chrome et en mode Offline DevTools/ débranchant le cable réseau, aucun message d'erreur n'est affiché dans l'IHM.
Je ne vois l'erreur que dans la console
![image](https://user-images.githubusercontent.com/56302715/95730174-2caed500-0c7e-11eb-9cc4-a6e211b1b74b.png)

2020-10-12 09:37 UTC, octo-topi requested changes
Test fonctionnel KO sur la RA pour moi sur réinitialisation avec Chrome
https://github.com/1024pix/pix/pull/1986#issuecomment-707002259

2020-10-12 09:41 UTC, octo-topi commented
Je pense qu'il y a un problème de déploiement car cette fonctionnalité ne marche pas non plus  
https://github.com/1024pix/pix/pull/1986#issuecomment-706120409

![image](https://user-images.githubusercontent.com/56302715/95731371-bc08b800-0c7f-11eb-8c30-fe1be34da945.png)

2020-10-12 09:50 UTC, yahyayouness commented
> Je pense qu'il y a un problème de déploiement car cette fonctionnalité ne marche pas non plus
> [#1986 (comment)](https://github.com/1024pix/pix/pull/1986#issuecomment-706120409)
> 
> ![image](https://user-images.githubusercontent.com/56302715/95731371-bc08b800-0c7f-11eb-8c30-fe1be34da945.png)

Je viens de retester avec ton JDD ca marche toujours

2020-10-12 09:56 UTC, yahyayouness commented
> > Une petite amélioration est de rendre le champ obligatoire (required) . Si le champ vide, on se retrouve avec un appel voué à l'échec.
> 
> Plus généralement, la soumission devrait être impossible si le champ n'est pas rempli et le format de mot de passe invalide !
> 
> Done :)

Je viens de rechecker le BSR, il a l'air de ne pas marcher encore ! Il y a toujours un appel au backend

2020-10-12 09:59 UTC, yahyayouness commented on mon-pix/app/templates/components/update-expired-password-form.hbs
> +                         @required={{true}} />
```suggestion
                         @required=true />
```

2020-10-12 10:03 UTC, octo-topi commented
:thinking: On parle de quelle réinitialisation ?

A l'initiative de l'utilisateur, dans mon-pix
![image](https://user-images.githubusercontent.com/56302715/95733792-e5771300-0c82-11eb-9db4-35a5249c6bf3.png)

Ou à l'initiative du professeur, dans pix-orga
![image](https://user-images.githubusercontent.com/56302715/95733665-bd87af80-0c82-11eb-9c55-b38991226774.png)

2020-10-12 10:15 UTC, octo-topi commented
Pour info, non bloquant. 
Si, après avoir perdu la connection, elle est retrouvée, et que le mot de passe n'est pas au bon format, le mssage "Une erreur interne est survenue, nos équipes sont en train de résoudre le problème. Veuillez réessayer ultérieurement." est toujours affiché
![image](https://user-images.githubusercontent.com/56302715/95734882-5c60db80-0c84-11eb-8dbc-e2cce3d8b1d4.png)

2020-10-12 10:17 UTC, octo-topi approved these changes

2020-10-12 10:25 UTC, yahyayouness commented
> Pour info, non bloquant.
> Si, après avoir perdu la connection, elle est retrouvée, et que le mot de passe n'est pas au bon format, le mssage "Une erreur interne est survenue, nos équipes sont en train de résoudre le problème. Veuillez réessayer ultérieurement." est toujours affiché
> ![image](https://user-images.githubusercontent.com/56302715/95734882-5c60db80-0c84-11eb-8dbc-e2cce3d8b1d4.png)

Je pense que ca peut être corriger rapidement en deplacant la réinitiatlisation du this.errorMessage au début de la fonction.

2020-10-12 10:50 UTC, chrc commented
> > Pour info, non bloquant.
> > Si, après avoir perdu la connection, elle est retrouvée, et que le mot de passe n'est pas au bon format, le mssage "Une erreur interne est survenue, nos équipes sont en train de résoudre le problème. Veuillez réessayer ultérieurement." est toujours affiché
> > ![image](https://user-images.githubusercontent.com/56302715/95734882-5c60db80-0c84-11eb-8dbc-e2cce3d8b1d4.png)
> 
> Je pense que ca peut être corriger rapidement en deplacant la réinitiatlisation du this.errorMessage au début de la fonction.

Done

2020-10-12 11:03 UTC, merged