[TECH] Remplacer des boutons par des PixButton pour gérer le chargement.
1024pix/pix pull request #2031
Opened 2020-10-19 15:45 UTC by MelanieMEB

## :unicorn: Problème
- Plusieurs boutons ne gèrent pas le chargement et permettent de cliquer plusieurs fois
- Ce système est présents sur certains boutons, avec des méthodes de dev différentes

## :robot: Solution
- Utiliser PixButton qui permet de gérer le chargement

## :rainbow: Remarques
-

## :100: Pour tester
-

2020-10-19 15:50 UTC, pix-service commented
I'm deploying this PR to these urls:

- App: https://app-pr2031.review.pix.fr
- Orga: https://orga-pr2031.review.pix.fr
- Certif: https://certif-pr2031.review.pix.fr
- Admin: https://admin-pr2031.review.pix.fr
- API: https://api-pr2031.review.pix.fr/api/

 Please check it out!

2020-10-22 13:08 UTC, MathieuGilet approved these changes
Super cool ce composant, merci !

2020-10-22 13:28 UTC, jbuget requested changes
Régression fonctionnelle

2020-10-22 13:28 UTC, jbuget commented on mon-pix/app/templates/components/campaign-start-block.hbs
> +           type="submit"
Il y a une régression fonctionnelle par là, sur la page [`/campagnes`](https://app-pr2031.review.pix.fr/campagnes) : 
- je saisis un identifiant de campagne existant, je fais "entrée" -> rechargement de la page (je suis bloqué)
- je saisis un identifiant de campagne existant, je clique sur le bouton "Commencer" -> je suis redirigé vers la page suivante (code étudiant)

2020-10-22 14:40 UTC, chrc commented on mon-pix/app/templates/fill-in-campaign-code.hbs
>                type="submit"
Question : Cet attribut est-il pris en compte par PixButton ?

2020-10-23 12:02 UTC, celineung commented on mon-pix/app/templates/components/campaign-start-block.hbs
> +           type="submit"
@chrc @jbuget je pense que la régression est lié au fait que l'on ne parvient pas à mettre le `type="submit"` sur le bouton. J'explore cette piste...

2020-10-23 12:29 UTC, jbuget commented on mon-pix/app/templates/components/campaign-start-block.hbs
> +           type="submit"
Avec @celineung nous venons de nous rendre compte qu'il s'agit d'un bug ouvert reconnu sur Ember. La PR qui fixe (mais qui n'est pas encore mergée) est [ici](https://github.com/glimmerjs/glimmer-vm/pull/1178).

2020-10-23 12:35 UTC, celineung commented on mon-pix/app/templates/components/campaign-start-block.hbs
> +           type="submit"
Il y a un bug côté Ember qui fait que le composant ne considère pas l'attribut `type` qui lui est passé (pas de problème concernant les autres attributs, il n'y a que `type` qui pose problème).

2020-10-23 13:26 UTC, sbedeau approved these changes
Techniquement OK 
A voir pour le problème fonctionnel

**praise:** PR stylée 🙏

2020-10-27 09:49 UTC, MelanieMEB commented on mon-pix/app/templates/components/campaign-start-block.hbs
> +           type="submit"
Modification effectué sur PixButton : https://github.com/1024pix/pix-ui/pull/38

Ce problème a été résolu

2020-10-27 09:49 UTC, MelanieMEB commented on mon-pix/app/templates/fill-in-campaign-code.hbs
>                type="submit"
Il ne l'était pas. On a changé le PixButton pour pouvoir passer un type : https://github.com/1024pix/pix-ui/pull/38

2020-10-29 08:47 UTC, jbuget approved these changes

2020-10-30 10:38 UTC, jonasgrilleres approved these changes

2020-11-02 13:27 UTC, merged