[FEATURE] Ajouter le palier dans l'export des résultats d'un campagne d'évaluatuon (PIX-1458).
1024pix/pix pull request #2055
Opened 2020-10-26 15:02 UTC by ajoanny

## :unicorn: Problème
Les prescripteurs n'ont pas l'information sur le palier atteint par un participant pendant une  campagne dans l'export des résultat.

## :robot: Solution
Affichage de la colonne Paliers dans le csv d'export des résultats d'une campagne d'évaluation.

Nom de la colonne : "Palier obtenu (/nbr_paliers_max)"  (par exemple “Palier obtenu (/5)” )
Résultat de la colonne : le nombre de palier (1, 2, 3 etc.)

Position : entre la colonne de "date de partage" ou “Résultat thématique obtenu” et le "% maitrise de l'ensemble des acquis" 

## :rainbow: Remarques
RAS

## :100: Pour tester
Télécharger l'export des résultats de la campagne `Campagne d’évaluation 5.1` (pro.admin@example.net)

2020-10-26 15:07 UTC, pix-service commented
I'm deploying this PR to these urls:

- App: https://app-pr2055.review.pix.fr
- Orga: https://orga-pr2055.review.pix.fr
- Certif: https://certif-pr2055.review.pix.fr
- Admin: https://admin-pr2055.review.pix.fr
- API: https://api-pr2055.review.pix.fr/api/

 Please check it out!

2020-10-26 15:37 UTC, bpetetot commented on api/lib/infrastructure/utils/CampaignAssessmentCsvLine.js
> +    let stageReached = this.stages.findIndex((stage) => percentageSkillsValidated < stage.threshold);
**Question:** Il me semble qu'il ne faut pas compter les paliers avec un seuil égal à 0 au niveau des seuils atteints (en tout cas pour le nombre d'étoile) Si on veut être cohérent avec ce qui est affiché, je pense qu'on doit faire la même chose côté CSV. C'est la même chose sur le nombre total de palier.
@celineung @alexandrecoin Vous confirmez bien cette règle ?

Ça pourrait se calculer de la façon suivante (sans passer par les index)
```suggestion
const stageReached = this.stages.filter((stage) => stage.threshold> 0 && percentageSkillsValidated >=0 stage.threshold).length;
```

2020-10-26 15:37 UTC, bpetetot commented on api/lib/domain/usecases/start-writing-campaign-assessment-results-to-stream.js
> +    ...(stages[0] ? [`Palier obtenu (/${stages.length})`] : []),
Voir remarque sur le fichier `api/lib/infrastructure/utils/CampaignAssessmentCsvLine.js`
Le palier avec un seuil à zero ne doit pas être compté dans le total des paliers

2020-10-27 09:58 UTC, xav-car commented on api/lib/infrastructure/utils/CampaignAssessmentCsvLine.js
> +    let stageReached = this.stages.findIndex((stage) => percentageSkillsValidated < stage.threshold);
il me semble aussi

2020-10-27 10:48 UTC, ajoanny commented on api/lib/infrastructure/utils/CampaignAssessmentCsvLine.js
> +    let stageReached = this.stages.findIndex((stage) => percentageSkillsValidated < stage.threshold);
done ;) merci ! (À l'utilisation c'est pas très  pratique le threshold: 0.)

2020-10-27 11:16 UTC, bpetetot approved these changes
👍

2020-10-27 11:22 UTC, bpetetot commented
@ajoanny En testant fonctionnellement sur la RA, j'ai une erreur 500 quand je clique une campagne 
![image](https://user-images.githubusercontent.com/516360/97294954-fdd45980-184e-11eb-987d-69d726dd4328.png)

2020-10-27 14:10 UTC, ajoanny commented
> @ajoanny En testant fonctionnellement sur la RA, j'ai une erreur 500 quand je clique une campagne
> ![image](https://user-images.githubusercontent.com/516360/97294954-fdd45980-184e-11eb-987d-69d726dd4328.png)

C'est fixé on dirait je pense que j'avais fait un mauvais rebase

2020-10-27 15:17 UTC, bpetetot commented
Test fonctionnel OK 👍

2020-10-28 08:43 UTC, laura-bergoens commented on api/lib/domain/usecases/start-writing-campaign-assessment-results-to-stream.js
> +  const [targetProfile, organization, campaignParticipationInfos, stages] = await Promise.all([
**suggestion (non-blocking):** Je suis de moins en moins fan du Promise.all. Car même si ici le nombre de promesses reste "sous contrôle", il n'en reste pas moins que ce process-ci peut potentiellement utiliser 3 connexions différentes à la BDD à lui tout seul (pas cool, sachant qu'un container API dispose de 20 connexions pour toutes les requêtes qu'il traite en simultané). Je pense que ce serait aussi rapide de tout simplement enchaîner les await

2020-10-28 08:45 UTC, laura-bergoens commented on api/lib/infrastructure/utils/CampaignAssessmentCsvLine.js
> +  _reachedStage() {
**suggestion (non-blocking):** C'est pas commun d'avoir une fonction sans verbe (ou bien c'est un getter)

2020-10-28 08:45 UTC, ajoanny commented on api/lib/domain/usecases/start-writing-campaign-assessment-results-to-stream.js
> +  const [targetProfile, organization, campaignParticipationInfos, stages] = await Promise.all([
D'acc, je corrige ça !

2020-10-28 08:47 UTC, ajoanny commented on api/lib/infrastructure/utils/CampaignAssessmentCsvLine.js
> +  _reachedStage() {
Je corrige ça !  (habitude de Rubyiste)

2020-10-28 13:31 UTC, laura-bergoens commented on api/lib/domain/usecases/start-writing-campaign-assessment-results-to-stream.js
> +  const  organization = await organizationRepository.get(campaign.organizationId);
**typo (non-blocking)** : petit espace de trop ici

2020-10-28 13:36 UTC, laura-bergoens commented on api/lib/domain/usecases/start-writing-campaign-assessment-results-to-stream.js
> +  const reachableStages = stages.filter(({ threshold }) => threshold > 0);
**question (non-blocking)** : je ne suis pas encore bien familière avec les paliers, mais du coup ça existe des paliers dont le threshold est 0 ?

2020-10-28 13:37 UTC, laura-bergoens commented on api/lib/infrastructure/repositories/stage-repository.js
>      return results.map((result) => bookshelfToDomainConverter.buildDomainObject(BookshelfStage, result));
Autant en profiter pour corriger cette petite ligne
```suggestion
    return rbookshelfToDomainConverter.buildDomainObjects(BookshelfStage, results));
```

2020-10-28 13:41 UTC, laura-bergoens commented on api/lib/infrastructure/utils/CampaignAssessmentCsvLine.js
> +      ...(this.stages[0] ? [this._getReachedStage()] : []),
suggestion (blocking) : je trouve risqué cette ligne. Je sais qu'en amont la méthode de répo pour récupérer les stages c'est un find (donc renvoie un tableau vide), mais dans ce scope, et même dans le futur on n'est pas à l'abri d'un mésusage (à savoir quelqu'un qui laisse stages à `undefined`) et donc stages[0] ferait un joli crash.
La première manière qui me vient à l'esprit pour s'en prémunir serait de mettre en valeur par défaut un tableau vide dans le constructor de CampaignAssessmentCsvLine

2020-10-28 13:42 UTC, laura-bergoens commented on api/lib/infrastructure/utils/CampaignAssessmentCsvLine.js
> +    return this.stages.filter((stage) => stage.threshold > 0 && percentageSkillsValidated >= stage.threshold).length;
suggestion (non-blocking): il est redondant ce check `stage.threshold > 0`, j'ai souvenir qu'on l'a fait en amont dans le usecase je crois.
Est-ce qu'on part du principe que les stages passés en paramètre doivent tous êtres des reachableStages ?

2020-10-28 13:44 UTC, laura-bergoens requested changes
Petit request changes sur l'undefined possible, et dès que c'est résolu pour moi ce sera bon

2020-10-28 13:50 UTC, ajoanny commented on api/lib/domain/usecases/start-writing-campaign-assessment-results-to-stream.js
> +  const reachableStages = stages.filter(({ threshold }) => threshold > 0);
Ouais et du coup faut pas les prendre en compte.
Je sais plus la raison (j'ai pas été très attentif quand on a parlé) mais je pense que la team Xp d'éval peut expliquer le choix du design.

2020-10-28 13:52 UTC, laura-bergoens commented on api/lib/domain/usecases/start-writing-campaign-assessment-results-to-stream.js
> +  const reachableStages = stages.filter(({ threshold }) => threshold > 0);
Ok je viens de poser la question sur leur slack

2020-10-28 14:04 UTC, ajoanny commented on api/lib/infrastructure/utils/CampaignAssessmentCsvLine.js
> +      ...(this.stages[0] ? [this._getReachedStage()] : []),
Je corrige ça !
Je pense que ce genre de cas arrive avec l'utilisation des valeur par défaut et l'habitude de ne pas spécifier tout les paramètres d'une méthode quand on l'appelle. Je trouve que c'est plus pratique et plus efficace de laisser le code planter sinon c'est  difficile de trouver un limite à quand est-ce que je vérifie l'existence du paramètre ou pas.
Entre les tests auto / manuels et les revues de code je pense que ce genre de cas n'arriverais pas jusqu'en intégration.

2020-10-28 14:05 UTC, ajoanny commented on api/lib/infrastructure/utils/CampaignAssessmentCsvLine.js
> +    return this.stages.filter((stage) => stage.threshold > 0 && percentageSkillsValidated >= stage.threshold).length;
On le fait deux fois une fois pour le header mais on a pas changer la collection donc on doit le refaire.
Je peux le faire qu'une seul fois par contre si tu veux

2020-10-28 14:06 UTC, ajoanny commented on api/lib/infrastructure/utils/CampaignAssessmentCsvLine.js
> +    return this.stages.filter((stage) => stage.threshold > 0 && percentageSkillsValidated >= stage.threshold).length;
Après dans le cas ou il y a un targetProfile avec un seul palier avec 0 bah ça fera comme s'il n'y avait pas de palier c'est qui est peut-être pas mal

2020-10-28 14:11 UTC, ajoanny commented on api/lib/infrastructure/utils/CampaignAssessmentCsvLine.js
> +    return this.stages.filter((stage) => stage.threshold > 0 && percentageSkillsValidated >= stage.threshold).length;
done

2020-10-28 14:20 UTC, laura-bergoens approved these changes

2020-10-28 16:02 UTC, merged