[FEATURE] Changement du wording de la banière SCO (remplacement Toussaint par Noël)
1024pix/pix pull request #2066
Opened 2020-10-27 13:49 UTC by estellelandry

## :unicorn: Problème
La team métier SCO a décidé de changer la deadline de fin des parcours de rentrée, au lieu de la Toussaint la deadline est reportée aux vacances de Noël.

## :robot: Solution
Changement du wording dans la bannière SCO

## :rainbow: Remarques
/

## :100: Pour tester
Se connecter sur une organisation SCO (non agriculture) qui aurait déjà importé des élèves cette année scolaire, avec le compte suivant : admin.sco2@example.net / pix123
Constater que la date de la bannière a bien été changé.

2020-10-27 13:52 UTC, Laurentlcs approved these changes

2020-10-27 13:54 UTC, yahyayouness approved these changes

2020-10-27 13:54 UTC, jonasgrilleres approved these changes

2020-10-27 13:55 UTC, pix-service commented
I'm deploying this PR to these urls:

- App: https://app-pr2066.review.pix.fr
- Orga: https://orga-pr2066.review.pix.fr
- Certif: https://certif-pr2066.review.pix.fr
- Admin: https://admin-pr2066.review.pix.fr
- API: https://api-pr2066.review.pix.fr/api/

 Please check it out!

2020-10-27 13:57 UTC, MathieuGilet approved these changes

2020-10-27 14:07 UTC, bpetetot approved these changes

2020-10-27 14:08 UTC, bpetetot commented
Test fonctionnels OK 👍  Bien joué ;)

2020-10-27 14:44 UTC, VincentHardouin approved these changes

2020-10-27 14:48 UTC, Anne-Gaelle-S approved these changes

2020-10-27 14:51 UTC, Anne-Gaelle-S requested changes
Manque une petite correction de test dans `orga/tests/integration/components/information-banner-test.js` (ligne 158) : 
```
assert.dom('.pix-banner').includesText('Parcours de rentrée 2020 : les codes sont disponibles dans l’onglet Campagnes. N’oubliez pas de les diffuser aux élèves avant les vacances de Noël. Plus d’info collège et lycée (GT et Pro)');
```

2020-10-28 13:22 UTC, Anne-Gaelle-S approved these changes

2020-10-28 18:09 UTC, merged