[FEATURE] Ajout d'un message de redirection vers le support pour les téléchargement de fichiers (PIX-1451).
1024pix/pix pull request #2111
Opened 2020-11-05 12:42 UTC by alexandrecoin

## :unicorn: Problème

Les utilisateurs peuvent rencontrer des difficultés lors du téléchargement de fichier(s) lors du passage des épreuves.

## :robot: Solution

Ajout d'un message en dessous du bouton de téléchargement des fichiers redirigeant vers le support.

## :100: Pour tester

Réaliser une épreuve contenant un téléchargement de fichier. 
Ex : recC7E3nZmiFH0GHP

2020-11-05 12:47 UTC, pix-service commented
I'm deploying this PR to these urls:

- App: https://app-pr2111.review.pix.fr
- Orga: https://orga-pr2111.review.pix.fr
- Certif: https://certif-pr2111.review.pix.fr
- Admin: https://admin-pr2111.review.pix.fr
- API: https://api-pr2111.review.pix.fr/api/

 Please check it out!

2020-11-06 09:49 UTC, MelanieMEB requested changes

2020-11-06 09:49 UTC, MelanieMEB commented on mon-pix/app/components/challenge-statement.js
> +  fileDownloadHelpCenterUrl= 'https://support.pix.fr/fr/support/solutions/articles/15000036390';
**modification**: Il faudrait mettre cette URL dans les fichiers de traduction, car elle sera différente.

2020-11-06 17:10 UTC, celineung commented on mon-pix/translations/fr.json
> +                    "help": "Besoin d'aide pour '<'a href=\"https://support.pix.fr/fr/support/solutions/articles/15000036390\" class=\"challenge-statement__action-help--link\" target=\"_blank\"'>'ouv
**suggestion**:

```suggestion
                    "help": "'<'a href=\"https://support.pix.fr/fr/support/solutions/articles/15000036390\" class=\"challenge-statement__action-help--link\" target=\"_blank\"'>'Aide pour ouvrir, modifier ou retrouver ce fichier'</a>'."
```

2020-11-06 17:10 UTC, celineung approved these changes

2020-11-09 09:07 UTC, MelanieMEB commented on mon-pix/translations/fr.json
> +                    "help": "Besoin d'aide pour '<'a href=\"https://support.pix.fr/fr/support/solutions/articles/15000036390\" class=\"challenge-statement__action-help--link\" target=\"_blank\"'>'ouv
Je pense qu'on peut aussi laisser "Besoin d'aide pour" dans le lien, ça donne un coté + amicale peut être

2020-11-09 09:07 UTC, MelanieMEB approved these changes

2020-11-09 09:09 UTC, alexandrecoin commented on mon-pix/translations/fr.json
> +                    "help": "Besoin d'aide pour '<'a href=\"https://support.pix.fr/fr/support/solutions/articles/15000036390\" class=\"challenge-statement__action-help--link\" target=\"_blank\"'>'ouv
Le message a été réalisé avec et validé par le métier, je pense pas qu'il faille le changer non plus.

2020-11-09 10:32 UTC, merged