[TECH] Mise à jour des messages d'erreurs de réconciliation dans Mon-Pix (PIX-1426)
1024pix/pix pull request #2135
Opened 2020-11-10 14:53 UTC by AndreiaPena

## :unicorn: Problème
On souhaite ajouter des informations complémentaires dans les messages d'erreur (et d'information de connexion) présents dans la double mire lors de l'inscription et dans la réconciliation ( "R11", "R12", "R13", "R31", "R32", "S51", "S52", "S61", "S62", "S63").

Ces ajouts permettent de : 

1 - Préciser ce qu'est un identifiant car les élèves confondent avec adresse email.
2 - Indiquer aux enseignants où ils doivent se rendre pour aider l'élève.

## :robot: Solution
Ajouter l'information suivante pour le premier cas : "identifiant sous la forme prenom.nom suivi de 4 chiffres"

Ajouter pour le deuxième cas : "(Pour l'enseignant : voir le ‘Kit de dépannage’ dans Pix Orga > Documentation - Code XXX)"

## :rainbow: Remarques

## :100: Pour tester
Il y a plusieurs types de cas à tester ( 10 messages ont étés modifiés ).

Vous pouvez utiliser :  

- First Last (10/10/2010)
- Blue Ivy Carter (07/01/2012)
- User Gar (07/01/2002)

Ci-joint les screens des tests réalisés.
(Le premier montre la structure définitive du texte avec le saut de ligne entre les phrases, pas les suivants. )

<img width="301" alt="Capture d’écran 2020-11-10 à 15 02 25" src="https://user-images.githubusercontent.com/58915422/98686913-6e0fce80-2369-11eb-80a8-b7b03771f459.png">
<img width="338" alt="Capture d’écran 2020-11-10 à 13 12 50" src="https://user-images.githubusercontent.com/58915422/98688738-77019f80-236b-11eb-9139-4c8e3b6ff1ed.png">
<img width="340" alt="Capture d’écran 2020-11-10 à 12 51 58" src="https://user-images.githubusercontent.com/58915422/98689202-fabb8c00-236b-11eb-8a9f-950239f774ae.png">
<img width="352" alt="Capture d’écran 2020-11-10 à 13 19 22" src="https://user-images.githubusercontent.com/58915422/98689480-44a47200-236c-11eb-8f7b-fd67df2c6df1.png">

2020-11-10 15:01 UTC, pix-service commented
I'm deploying this PR to these urls:

- App: https://app-pr2135.review.pix.fr
- Orga: https://orga-pr2135.review.pix.fr
- Certif: https://certif-pr2135.review.pix.fr
- Admin: https://admin-pr2135.review.pix.fr
- API: https://api-pr2135.review.pix.fr/api/

 Please check it out!

2020-11-10 15:24 UTC, yahyayouness approved these changes

2020-11-10 17:21 UTC, ebarbier requested changes
Peux-tu aussi retirer le point après la variable de l'adresse email please sur tous les msgs avec adresse email? On dirait que ça fait partie de l'email alors que non.
"...un compte Pix avec l’adresse e-mail '<br>'{ value }'<br>'Pour continuer..."

2020-11-12 07:48 UTC, chrc approved these changes

2020-11-12 09:25 UTC, MathieuGilet approved these changes

2020-11-12 09:33 UTC, AndreiaPena commented
> Peux-tu aussi retirer le point après la variable de l'adresse email please sur tous les msgs avec adresse email? On dirait que ça fait partie de l'email alors que non.
> "...un compte Pix avec l’adresse e-mail '
> '{ value }'
> 'Pour continuer..."

2020-11-12 09:35 UTC, ebarbier approved these changes

2020-11-12 10:01 UTC, merged