[FEATURE] Ajout de la fonctionnalité "Ajouter un identifiant" pour l'élève disposant d'une adresse e-mail sur pix Orga (PIX-1154)
1024pix/pix pull request #2145
Opened 2020-11-13 14:28 UTC by AndreiaPena

## :unicorn: Problème
Actuellement on ne peut rajouter un identifiant que sur un élève qui a comme méthode de connexion unique: Mediacentre.

Or, beaucoup d'élèves se créent un compte avec une adresse e-mail (mais n’ont pas la majorité numérique).
Les enseignants imposent alors d’utiliser un identifiant. ( L'ajout de cet identifiant se traitait manuellement ).

## :robot: Solution
Ajouter la fonctionnalité "Ajout d'une connexion avec identifiant" pour l'élève ayant pour connexion unique: Adresse e-mail.

## :rainbow: Remarques
Nous avons également fait une refonte wording :

- En supprimant les labels des champs Identifiant et Adresse e-mail, qui faisait doublons avec les span.
- En supprimant "Connecté avec...", pour garder uniquement les méthodes de connexion.
- En modifiant le label du mot de passe lors de la création, pour “Nouveau mot de passe à usage unique”.
- En modifiant également les indications/aides 1 et 3.
- "Ajouter un identifiant" au lieu de "Ajouter" pour le bouton d'ajout de méthode de connexion avec identifiant.

## :100: Pour tester

- Se connecter sur pix Orga : sco.admin@example.net
- Aller sur élèves > Gérer le compte, d'un utilisateur ayant la méthode de connexion unique: Adresse-mail
- Cliquer sur le bouton "Ajouter un identifiant" pour voir l'identifiant et le nouveau mot de passe à usage unique.
<img width="390" alt="Capture d’écran 2020-11-13 à 11 12 44" src="https://user-images.githubusercontent.com/58915422/99081748-8f6bf700-25c3-11eb-95d0-5d6a1d292dfb.png">

2020-11-16 09:11 UTC, chrc commented on orga/tests/unit/models/student-test.js
> +  module.only('#isAuthenticatedWithGarOrEmailOnly', function(hooks) {
Oubli d'un `only`

2020-11-16 09:14 UTC, chrc commented on orga/app/models/student.js
> +    return Boolean(!this.hasUsername && this.isAuthenticatedFromGar || !this.hasUsername && this.hasEmail);
Suggestion :
```javascript
return Boolean(!this.hasUsername && (this.isAuthenticatedFromGar || this.hasEmail));
```

2020-11-16 09:15 UTC, chrc commented on orga/tests/integration/components/manage-authentication-method-modal-test.js
> +module.only('Integration | Component | manage-authentication-method-modal', function(hooks) {
Oubli d'un `only`

2020-11-16 09:18 UTC, AndreiaPena commented on orga/tests/integration/components/manage-authentication-method-modal-test.js
> +module.only('Integration | Component | manage-authentication-method-modal', function(hooks) {
done

2020-11-16 09:19 UTC, AndreiaPena commented on orga/tests/unit/models/student-test.js
> +  module.only('#isAuthenticatedWithGarOrEmailOnly', function(hooks) {
il a été enlevé après celui-ci.

2020-11-16 09:20 UTC, AndreiaPena commented on orga/tests/integration/components/manage-authentication-method-modal-test.js
> +module.only('Integration | Component | manage-authentication-method-modal', function(hooks) {
done

2020-11-16 09:35 UTC, pix-service commented
I'm deploying this PR to these urls:

- App: https://app-pr2145.review.pix.fr
- Orga: https://orga-pr2145.review.pix.fr
- Certif: https://certif-pr2145.review.pix.fr
- Admin: https://admin-pr2145.review.pix.fr
- API: https://api-pr2145.review.pix.fr/api/

 Please check it out!

2020-11-16 15:29 UTC, AndreiaPena commented on orga/app/models/student.js
> +    return Boolean(!this.hasUsername && this.isAuthenticatedFromGar || !this.hasUsername && this.hasEmail);
done

2020-11-16 16:21 UTC, ebarbier requested changes, later dismissed
Si le user a déjà un mot de passe (car il a déjà une connexion adresse email), alors ne pas en re-générer un nouveau.

2020-11-26 09:46 UTC, manux-pix approved these changes

2020-11-26 10:46 UTC, octo-topi commented
Une petit rebase interactive pour passer le nom des commit en anglais ?
![image](https://user-images.githubusercontent.com/56302715/100341579-026e6800-2fdd-11eb-88d7-d3a640d74a3a.png)

2020-11-26 14:09 UTC, MathieuGilet commented on api/lib/domain/usecases/generate-username-with-temporary-password.js
> +    return { username: updatedUser.username, password: undefined  };
```suggestion
    return { username: updatedUser.username  };
```
ou 
```suggestion
    return { username: updatedUser.username, generatedPassword: undefined  };
```
Renvoyer un attribut `password` ici ne sert à rien car, si on regarde l'usage qui est fait de ce retour dans le serailizer `schooling-registration-dependent-user-serializer.js`, seuls les attributs `username` et `generatedPassword` sont utlisés. Personnellement, je préfère la première proposition.

2020-11-26 14:13 UTC, MathieuGilet commented on api/tests/unit/domain/usecases/generate-username-with-temporary-password_test.js
> +    it('should not return a password', async () => {
Si tu suis ma propostion précédente ce test sera à supprimer ou à modifier.

2020-11-26 14:15 UTC, MathieuGilet commented on api/tests/unit/domain/usecases/generate-username-with-temporary-password_test.js
> +  context('when schooling-registration refers to an user with an email', ()=> {
Que le compte soit avec email n'est pas le plus important, ce qui compte c'est qu'il ait déjà un `password` ou non (c'est d'ailleurs le sens de la condition dans le usecase).

2020-11-26 14:27 UTC, MathieuGilet commented on orga/app/components/manage-authentication-method-modal.js
> +      if (this.args.student.email === undefined || this.args.student.email === null) {
```suggestion
      if (!this.args.student.email) {
```
Voir https://developer.mozilla.org/fr/docs/Glossaire/Truthy.

2020-11-26 14:29 UTC, MathieuGilet approved these changes

2020-11-26 15:18 UTC, octo-topi commented on orga/app/components/manage-authentication-method-modal.hbs
> +        {{#if @student.isAuthenticatedWithGarOrEmailOnly}}
Là, je dois faire un effort de réflexion sur ce que veut dire `isAuthenticatedWithGarOrEmailOnly`
C'est bien d'exprimer le fonctionnel, mais ça a des limites
je suggère un `displayAddUserrnameAuthentication` booléen, alimenté dans le JS

2020-11-26 15:22 UTC, octo-topi commented on orga/app/components/manage-authentication-method-modal.hbs
> +        {{#if @student.isAuthenticatedWithGarOrEmailOnly}}
J'ai regardé la suite et ce template est.. :exploding_head: 
Personne ne pense possible de réduire sa complexité ?

2020-11-26 15:49 UTC, octo-topi commented on api/lib/domain/usecases/generate-username-with-temporary-password.js
> +    return { username: updatedUser.username, password: undefined  };
J'avait gardé un password `undefined` pour bien différencier et expliciter l'intention, mais si c'est clair dans le contexte, la première proposition de @MathieuGilet  est OK pour moi !

2020-11-26 15:52 UTC, octo-topi commented on api/tests/unit/domain/usecases/generate-username-with-temporary-password_test.js
> +  context('when schooling-registration refers to an user with an email', ()=> {
Oui, comme dit plus haut, à l'origine le test dans le use-case était sur email. Donc OK pour ta proposition

2020-11-26 15:53 UTC, octo-topi approved these changes

2020-11-27 11:07 UTC, AndreiaPena commented on api/lib/domain/usecases/generate-username-with-temporary-password.js
> +    return { username: updatedUser.username, password: undefined  };
Ok pour la première proposition !

2020-11-27 11:08 UTC, AndreiaPena commented on api/tests/unit/domain/usecases/generate-username-with-temporary-password_test.js
> +    it('should not return a password', async () => {
ok c'est supprimé

2020-11-27 11:08 UTC, AndreiaPena commented on api/tests/unit/domain/usecases/generate-username-with-temporary-password_test.js
> +  context('when schooling-registration refers to an user with an email', ()=> {
done

2020-11-27 12:57 UTC, AndreiaPena commented on orga/app/components/manage-authentication-method-modal.js
> +      if (this.args.student.email === undefined || this.args.student.email === null) {
done !

2020-11-27 12:57 UTC, AndreiaPena commented on orga/app/components/manage-authentication-method-modal.hbs
> +        {{#if @student.isAuthenticatedWithGarOrEmailOnly}}
done

2020-11-27 13:25 UTC, merged