[TECH] Déconnecter les utilisateurs connectés lors de le recréation de la BDD.
1024pix/pix pull request #2164
Opened 2020-11-18 08:20 UTC by octo-topi

## :unicorn: Problème
En local ou en RA, quand le script `npm run db:reset` est lancé pour générer des JDD, le message suivant est parfois affiché

```
> pix-api@2.219.0 db:delete /home/topi/Documents/OCTO/Missions/Pix/code/repo/pix/api
> node scripts/database/drop-database
query: DROP DATABASE pix;
(node:15695) UnhandledPromiseRejectionWarning: error: database "pix" is being accessed by other users
```

## :robot: Solution
Déconnecter sans ménagement les autres utilisateurs

## :rainbow: Remarques
Je ne pense pas que ce soit dangereux de l'envoyer en production car je ne pense pas que l'utilisateur standard puisse faire un `DROP DATABASE `sur une BDD instanciée par l'add PG Scalingo
Une solution plus propre est dispo sur `force-deconnexion-on-database-drop-pg13`, à utiliser lorsque PG 13 sera utilisé

## :100: Pour tester
Etapes:
- se connecter avec un client BDD `psql postgres://postgres@localhost:5432/pix`
- lancer l'API `npm start`
- lancer les seeds `npm run db:seed`
- vérifier qu'on obtient `Ran 1 seed files`

2020-11-18 08:26 UTC, pix-service commented
I'm deploying this PR to these urls:

- App: https://app-pr2164.review.pix.fr
- Orga: https://orga-pr2164.review.pix.fr
- Certif: https://certif-pr2164.review.pix.fr
- Admin: https://admin-pr2164.review.pix.fr
- API: https://api-pr2164.review.pix.fr/api/

 Please check it out!

2020-11-18 09:57 UTC, jonathanperret requested changes
Pas d'objection sur le principe mais dans l'implémentation je crois qu'il y a un souci.

2020-11-18 09:57 UTC, jonathanperret commented on api/scripts/database/drop-database.js
> +(async () => { await client.query_and_log(disconnectAllSessionsButMineQuery); })();
C'est quoi l'intention de ce `(async () => { await …` ?

Si c'est pour lancer la requête sans attendre la résolution,
```suggestion
client.query_and_log(disconnectAllSessionsButMineQuery);
```
marcherait aussi (a priori c'est juste équivalent à ce qui est écrit), mais on s'expose à la possibilité d'une `unhandled rejection`. Et je ne vois pas pourquoi on voudrait ne pas attendre la résolution ici.

Si c'est pour ignorer une éventuelle erreur, mieux vaut utiliser proprement `.then`/`.catch`.

Mais plus simplement, dans ce cas-ci j'ai l'impression qu'on peut fusionner les deux commandes SQL en un seul appel.

```suggestion
client.query_and_log(
 `SELECT pg_terminate_backend(pg_stat_activity.pid)
  FROM pg_stat_activity
  WHERE pg_stat_activity.datname = '${DB_TO_DELETE_NAME}'
  AND pid <> pg_backend_pid();
  DROP DATABASE ${DB_TO_DELETE_NAME};`)
  .then(() => {
	console.log('Database dropped');
	…
```

2020-11-18 13:24 UTC, octo-topi commented on api/scripts/database/drop-database.js
> +(async () => { await client.query_and_log(disconnectAllSessionsButMineQuery); })();
Merci @jonathanperret 
Je vais me pencher un jour sérieusement sur les promesses plutôt que de taper des trucs juqu'à ce que linter passe au vert :smile:

2020-11-18 13:29 UTC, octo-topi commented on api/scripts/database/drop-database.js
> +(async () => { await client.query_and_log(disconnectAllSessionsButMineQuery); })();
Zut, ça marche pas !
`DROP DATABASE cannot run inside a transaction block`

2020-11-18 14:30 UTC, jonathanperret commented on api/scripts/database/drop-database.js
> +(async () => { await client.query_and_log(disconnectAllSessionsButMineQuery); })();
OK, du coup rester sur deux appels distincts au client mais il faut les séquencer correctement. Par exemple :

```
async function dropDatabase(client) {
	await client.query_and_log(
	  `SELECT pg_terminate_backend(pg_stat_activity.pid)
	  FROM pg_stat_activity
	  WHERE pg_stat_activity.datname = '${DB_TO_DELETE_NAME}'
	  AND pid <> pg_backend_pid()`
    );

	await client.query_and_log(`DROP DATABASE ${DB_TO_DELETE_NAME}`);
}

…

dropDatabase(client)
	.then(() => {
		console.log('Database dropped');
		…
```

2020-11-18 15:16 UTC, jonathanperret commented on api/scripts/database/drop-database.js
> +(async () => { await client.query_and_log(disconnectAllSessionsButMineQuery); })();
@octo-topi Par ailleurs, je viens de voir dans la description de cette PR qu'en cas d'échec il y avait un `UnhandledPromiseRejectionWarning` — d'ailleurs en local je constate que l'exécution de `npm run db:delete` ne se termine même pas dans ce cas !

La cause en est ce `throw` : https://github.com/1024pix/pix/blob/6e7e5486ffb6e41928229a5b55f28da938fcd647/api/scripts/database/drop-database.js#L26-L28

En effet on intercepte bien le rejet de la promesse avec le `catch` mais ensuite on crée de nouveau une promesse rejetée avec ce `throw`, qui elle n'est pas interceptée.

Il faudrait remplacer ce `throw` par quelque chose comme :

```
      console.error('Error:', error.message);
      process.exit(1);
```

Je pense que ça irait bien dans cette PR-ci aussi non ?

2020-11-27 08:41 UTC, octo-topi commented on api/scripts/database/drop-database.js
> +(async () => { await client.query_and_log(disconnectAllSessionsButMineQuery); })();
Merci pour les apprentissages !
Parfois, oublier une PR quelques jours aiude à prendre du recul.
Je pense être sur une fausse piste, on n'a pas besoin de supprimer la BDD en fait, juste de supprimer les objets.
Je ferme cette PR et en ouvrirait un autre lundi qui adresse ce besoin spécifique.

2020-11-27 08:41 UTC, closed without merging