Pix 1623 accept only insee code sco
1024pix/pix pull request #2169
Opened 2020-11-18 13:07 UTC by xav-car

## :unicorn: Problème
Certains import des SCO Agri, ont des imports avec de mauvais code INSEE.

## :robot: Solution
Rajouter un paramètre de vérification du code INSEE afin qu'il soit valide.
## :rainbow: Remarques
> _RAS_

## :100: Pour tester
Se connecter avec `sco.admin@example.net` => lycée agricole => élèves => import CSV
enregistrer ces fichiers au format csv
```
Identifiant unique*;Premier prénom*;Deuxième prénom;Troisième prénom;Nom de famille*;Nom d'usage;Date de naissance (jj/mm/aaaa)*;Code commune naissance**;Libellé commune naissance**;Code département naissance*;Code pays naissance*;Statut*;Code MEF*;Division*
456F;Juste;;;Leblanc;Cottonmouth;01/01/1780;;Shangai;99;FRANC;ST;MEF1;Division 2
```
KO

```
Identifiant unique*;Premier prénom*;Deuxième prénom;Troisième prénom;Nom de famille*;Nom d'usage;Date de naissance (jj/mm/aaaa)*;Code commune naissance**;Libellé commune naissance**;Code département naissance*;Code pays naissance*;Statut*;Code MEF*;Division*
457F;Baby;;;Yoda;Cottonmouth;01/01/1780;;Shangai;99;A2222;ST;MEF1;Division 2
```
KO

```
Identifiant unique*;Premier prénom*;Deuxième prénom;Troisième prénom;Nom de famille*;Nom d'usage;Date de naissance (jj/mm/aaaa)*;Code commune naissance**;Libellé commune naissance**;Code département naissance*;Code pays naissance*;Statut*;Code MEF*;Division*
458F;Léa;;;elle est pas;Cottonmouth;01/01/1780;;Shangai;99;2A214;ST;MEF1;Division 2
```
OK

```
Identifiant unique*;Premier prénom*;Deuxième prénom;Troisième prénom;Nom de famille*;Nom d'usage;Date de naissance (jj/mm/aaaa)*;Code commune naissance**;Libellé commune naissance**;Code département naissance*;Code pays naissance*;Statut*;Code MEF*;Division*
459F;Louise;;;Attaque;Cottonmouth;01/01/1780;;Shangai;99;51430;ST;MEF1;Division 2
```
OK

2020-11-18 13:11 UTC, pix-service commented
I'm deploying this PR to these urls:

- App: https://app-pr2169.review.pix.fr
- Orga: https://orga-pr2169.review.pix.fr
- Certif: https://certif-pr2169.review.pix.fr
- Admin: https://admin-pr2169.review.pix.fr
- API: https://api-pr2169.review.pix.fr/api/

 Please check it out!

2020-11-18 13:17 UTC, bpetetot approved these changes
👍  OK mais attention il reste un `only` au niveau des tests

2020-11-18 13:17 UTC, bpetetot commented on api/tests/unit/domain/validators/schooling-registration-validator_test.js
> +    context.only('birthCountryCode', () => {
Attention un `only` à supprimer
```suggestion
    context('birthCountryCode', () => {
```

2020-11-18 13:20 UTC, bpetetot commented
Tests fonctionnels OK 👌

2020-11-18 13:22 UTC, xav-car commented on api/tests/unit/domain/validators/schooling-registration-validator_test.js
> +    context.only('birthCountryCode', () => {
oups :)

2020-11-18 13:51 UTC, xav-car commented on api/lib/infrastructure/serializers/csv/schooling-registration-parser.js
> +      throw new CsvImportError(`Ligne ${index + 2} : Le champ “Code pays naissance*” n'est pas au format INSEE`);
Message vu/validé avec @estellelandry

2020-11-18 14:39 UTC, lisequesnel commented on api/lib/infrastructure/serializers/csv/schooling-registration-parser.js
> +      throw new CsvImportError(`Ligne ${index + 2} : Le champ “Code pays naissance*” n'est pas au format INSEE`);
```suggestion
      throw new CsvImportError(`Ligne ${index + 2} : Le champ “Code pays naissance*” n'est pas au format INSEE.`);
```

2020-11-18 14:43 UTC, lisequesnel requested changes

2020-11-18 14:43 UTC, lisequesnel commented on api/lib/domain/validators/schooling-registration-validator.js
> +const INSEECountryCode = /[0-9]{5}|[0-9]{1}[a,b,A,B]{1}[0-9]{3}/;
il n'y a pas de chiffres du tout dans le champ pays : https://www.insee.fr/fr/information/2028273

2020-11-18 14:43 UTC, lisequesnel commented on api/lib/domain/validators/schooling-registration-validator.js
> +const INSEECountryCode = /[0-9]{5}|[0-9]{1}[a,b,A,B]{1}[0-9]{3}/;
pas contre c'est pour `birthCityCode` où il peut y avoir une seule lettre sur les 5 caractères.

2020-11-18 15:40 UTC, xav-car commented on api/lib/domain/validators/schooling-registration-validator.js
> +const INSEECountryCode = /[0-9]{5}|[0-9]{1}[a,b,A,B]{1}[0-9]{3}/;
mais oui 🤦 .  je suis dessus.

2020-11-19 09:19 UTC, lisequesnel commented on api/lib/domain/validators/schooling-registration-validator.js
> +  birthCountryCode: Joi.string()
**suggestion** : au lieu de mettre une regex, on peux pas mettre `Joi.number()` ?

2020-11-19 09:19 UTC, lisequesnel commented on api/lib/domain/validators/schooling-registration-validator.js
> +  CITY_CODE_FRANCE : /[0-9]{5}|[0-9]{1}[a,b,A,B]{1}[0-9]{3}/,
```suggestion
  FRANCE_CITY_CODE : /[0-9]{5}|[0-9]{1}[a,b,A,B]{1}[0-9]{3}/,
```

2020-11-19 09:30 UTC, xav-car commented on api/lib/domain/validators/schooling-registration-validator.js
> +  birthCountryCode: Joi.string()
ou alors être plus précis pour le code pays ...  `9{2}[1-5]{1}[0-9]{2}` ?

2020-11-19 13:12 UTC, lisequesnel commented on api/tests/acceptance/application/organizations/organization-controller-import-schooling-registrations_test.js
> +        it('should not save any schooling registration missing familly name', async () => {
```suggestion
        it('should not save any schooling registration missing family name', async () => {
```

2020-11-19 13:13 UTC, lisequesnel commented on api/tests/acceptance/application/organizations/organization-controller-import-schooling-registrations_test.js
> +        it('should not save any schooling registration wrong birthCountryCode', async () => {
```suggestion
        it('should not save any schooling registration with wrong birthCountryCode', async () => {
```

2020-11-19 13:14 UTC, lisequesnel commented on api/tests/acceptance/application/organizations/organization-controller-import-schooling-registrations_test.js
> +        it('should not save any schooling registration wrong birthCityCode', async () => {
```suggestion
        it('should not save any schooling registration with wrong birthCityCode', async () => {
```

2020-11-19 13:14 UTC, lisequesnel commented on api/tests/unit/domain/validators/schooling-registration-validator_test.js
> +        it('birthCountryCode respect INSEE Code, only number', async () => {
```suggestion
        it('respect INSEE Code, only number', async () => {
```

2020-11-19 13:15 UTC, lisequesnel commented on api/tests/unit/domain/validators/schooling-registration-validator_test.js
>      context('birthCountryCode', () => {
il manque un test pour tester que le `birthCountryCode` commence bien par 99, non ?

2020-11-19 13:16 UTC, lisequesnel commented on api/tests/unit/domain/validators/schooling-registration-validator_test.js
> +          it('when birthCityCode respect INSEE Code, with one letter', async () => {
```suggestion
          it('respects INSEE Code, with one letter', async () => {
```

2020-11-19 13:16 UTC, lisequesnel commented on api/tests/unit/domain/validators/schooling-registration-validator_test.js
> +          it('when birthCityCode respect INSEE Code, only number', async () => {
```suggestion
          it('respects INSEE Code, only number', async () => {
```

2020-11-19 13:19 UTC, lisequesnel commented on api/tests/unit/domain/validators/schooling-registration-validator_test.js
> +          it('when birthCityCode is undefined and birthCountry is not France', async () => {
```suggestion
          it('is valid with birthCityCode undefined', async () => {
```

2020-11-19 13:27 UTC, lisequesnel commented on api/tests/unit/domain/validators/schooling-registration-validator_test.js
> +        });
```suggestion
      context('is invalid', () => {
          context('when birthCountryCode is equal to France', () => {
            it('throw an error with a birthCityCode of 5 characters', async () => {
              const error = await catchErr(checkValidation)({ ...validAttributes, birthCountryCode: FRANCE_COUNTRY_CODE, birthCityCode: '123456' });
              expect(error.key).to.equal('birthCityCode');
              expect(error.why).to.equal('length');
              expect(error.limit).to.equal(5);
            });
  
            it('throws an error with a birthCityCode which has a letter not in second character', async () => {
              const error = await catchErr(checkValidation)({ ...validAttributes, birthCountryCode: FRANCE_COUNTRY_CODE, birthCityCode: '21B22' });
              expect(error.key).to.equal('birthCityCode');
              expect(error.why).to.equal('not_match_regex');
            });
        });
        
        context('when birthCountryCode is not equal to France', () => {
          it('throws an error with a birthCityCode of not 5 characters', async () => {
            const error = await catchErr(checkValidation)({ ...validAttributes, birthCityCode: '1' });
            expect(error.key).to.equal('birthCityCode');
            expect(error.why).to.equal('length');
            expect(error.limit).to.equal(5);
        });
      });
```

2020-11-19 14:20 UTC, lisequesnel commented on api/tests/unit/domain/validators/schooling-registration-validator_test.js
> +              checkValidation({ ...validAttributes, birthCountryCode: FRANCE_COUNTRY_CODE, birthCityCode: '2B125' });
je l'avais pas vue celle-là ^^ pour coller avec le titre du test, c'est mieux (et l'autre est déjà testé plus haut) :
```suggestion
              checkValidation({ ...validAttributes, birthCountryCode: FRANCE_COUNTRY_CODE, birthCityCode: '21125' });
```

2020-11-19 14:22 UTC, lisequesnel commented on api/tests/unit/domain/validators/schooling-registration-validator_test.js
> +          });
Le contexte `when birthCountryCode is equal to France` doit se fermer avant l'ouverture du contexte `when birthCountryCode is not equal to France `
```suggestion
          });
      });
          
      context('when birthCountryCode is not equal to France', () => {
          it('throws an error with a birthCityCode of not 5 characters', async () => {
          const error = await catchErr(checkValidation)({ ...validAttributes, birthCityCode: '1' });
          expect(error.key).to.equal('birthCityCode');
          expect(error.why).to.equal('length');
          expect(error.limit).to.equal(5);
        });
```

2020-11-19 14:56 UTC, lisequesnel commented
validé fonctionnellement et techniquement 👍

2020-11-19 14:56 UTC, lisequesnel approved these changes

2020-11-19 16:10 UTC, lisequesnel commented on api/lib/domain/validators/schooling-registration-validator.js
> +  FRANCE_CITY_CODE : /[0-9]{5}|[0-9]{1}[a,b,A,B]{1}[0-9]{3}/,
en vrai on oublie les départements à 1 seul chiffre non ? pour eux ça va ressembler à 1234, non ?

2020-11-19 16:24 UTC, lisequesnel commented on api/lib/domain/validators/schooling-registration-validator.js
>      otherwise: Joi.string().length(CITY_CODE_LENGTH).optional(),
```suggestion
    otherwise: Joi.string().optional(),
```
parce qu'en vrai, à l'étranger, on connaît pas le format des villes

2020-11-19 16:39 UTC, lisequesnel commented on api/lib/domain/validators/schooling-registration-validator.js
> +  FRANCE_CITY_CODE : /[0-9]{5}|[0-9]{1}[a,b,A,B]{1}[0-9]{3}/,
à moins qu'on les laisse saisir "0" devant, je crois que c'est ce qu'on avait dit

2020-11-20 10:05 UTC, xav-car commented on api/lib/domain/validators/schooling-registration-validator.js
>      otherwise: Joi.string().length(CITY_CODE_LENGTH).optional(),
j'ai changé pour un `max(MAX_LENGTH)` au lieu du length. comme évoqué ce matin.

2020-11-23 09:33 UTC, laura-bergoens commented on api/lib/domain/validators/schooling-registration-validator.js
> +  FRANCE_CITY_CODE : /[0-9]{5}|[0-9]{1}[a,b,A,B]{1}[0-9]{3}/,
**question (non-blocking) :** je me demande si c'est "toléré" un commentaire dans le code avec un lien vers la réf INSEE ?

2020-11-23 09:35 UTC, laura-bergoens commented on api/lib/domain/validators/schooling-registration-validator.js
> +        err.why = 'not_match_regex';
**suggestion (non-blocking) :** Cette regex permet de valider une norme INSEE. Je le ferais apparaître dans le nom de l'erreur, style `not_valid_insee_code`...

2020-11-23 09:35 UTC, laura-bergoens commented on api/lib/infrastructure/serializers/csv/schooling-registration-parser.js
> +    if (err.why === 'not_match_regex') {
... comme ça ce serait un peu plus lisible ici

2020-11-23 09:36 UTC, laura-bergoens approved these changes
Je valide mais j'aimerais bien réponse à mes questions :smile:

2020-11-23 09:39 UTC, xav-car commented on api/lib/domain/validators/schooling-registration-validator.js
> +        err.why = 'not_match_regex';
oui c'est possible. :)

2020-11-23 09:44 UTC, xav-car commented on api/lib/domain/validators/schooling-registration-validator.js
> +        err.why = 'not_match_regex';
C'est vrai que je me suis plus basé sur le context de l'erreur comme pour les autres "why" . en spécifiant regex. 

Mais, c'est plus parlant comme ça effectivement.

2020-11-23 09:44 UTC, bpetetot approved these changes

2020-11-23 11:25 UTC, merged