[FEATURE] Construction du payload PE au démarrage d'une campagne (PIX-1625)
1024pix/pix pull request #2175
Opened 2020-11-19 10:50 UTC by bpetetot

## :unicorn: Problème
> _Décrivez ici le besoin ou l'intention couvert par cette Pull Request._

## :robot: Solution
> _Ajoutez à cet endroit, si nécessaire, des détails concernant la solution technique retenue et mise en oeuvre, des difficultés ou problèmes rencontrés._

## :rainbow: Remarques
> _Des infos supplémentaires, trucs et astuces ?_

## :100: Pour tester
> _Les instructions pour reproduire le problème, les profils de test, le parcours spécifique à utiliser, etc._

2020-11-19 10:56 UTC, pix-service commented
I'm deploying this PR to these urls:

- App: https://app-pr2175.review.pix.fr
- Orga: https://orga-pr2175.review.pix.fr
- Certif: https://certif-pr2175.review.pix.fr
- Admin: https://admin-pr2175.review.pix.fr
- API: https://api-pr2175.review.pix.fr/api/

 Please check it out!

2020-11-19 14:00 UTC, lisequesnel approved these changes

2020-11-19 14:05 UTC, lisequesnel commented
validé fonctionnellement :
![image](https://user-images.githubusercontent.com/23451175/99676299-976edf80-2a78-11eb-81d4-9aafb2726780.png)

2020-11-23 09:40 UTC, laura-bergoens commented on api/lib/domain/events/handle-pole-emploi-participation-shared.js
> +async function handlePoleEmploiParticipationShared({
:+1:

2020-11-23 09:45 UTC, laura-bergoens commented on api/lib/domain/events/handle-pole-emploi-participation-shared.js
> +  const organization = await organizationRepository.get(organizationId);
**suggestion (blocking) :** Je suis allée voir la tronche de la méthode `organizationRepository.get()`, c'est pas jojo : 
```js
get(id) {
    return BookshelfOrganization
      .where({ id })
      .fetch({                                                       // première requête
        require: true,
        withRelated: [
          { 'memberships': (qb) => qb.where({ disabledAt: null }) }, // +1 
          'memberships.user', // +1
          'targetProfileShares.targetProfile', // +1
          'tags', // +1
        ],
      })
      .then(_toDomain)
      .catch((err) => {
        if (err instanceof BookshelfOrganization.NotFoundError) {
          throw new NotFoundError(`Not found organization for ID ${id}`);
        }
        throw err;
      });
  },
```
Donc 5 requêtes SQL (à chaque fois demande d'obtention d'une connexion au pool, etc...) tout ça pour savoir si l'orga est pole emploi. Je propose d'adapter le répo et d'exposer une méthode supplémentaire qui pourrait être :
-> version très spécifique : `organizationRepository.isPoleEmploi(organizationId)` (mais bon le couplage est fort)
-> version un peu moins spécifique : `organizationRepository.hasTags(tags)`
On en avait parlé, déjà c'est embêtant d'avoir ce handler d'event qui run chez tout le monde, alors si en plus ça pompe plein de connexions à la BDD... :grin:

2020-11-23 09:45 UTC, laura-bergoens commented on api/lib/domain/events/handle-pole-emploi-participation-shared.js
> +  const organization = await organizationRepository.get(organizationId);
EDIT : et du coup si on a fait le même pattern dans d'autres handlers de type PE, on peut essayer d'appliquer la correction un peu partout

2020-11-23 09:47 UTC, laura-bergoens commented on api/lib/domain/events/handle-pole-emploi-participation-shared.js
> +  const { organizationId, campaignId, userId, campaignParticipationId } = event;
**thought (non-blocking) :** On manque un peu de cohérence entre les events. L'event CampaignParticipationResultsShared ne présente que des IDs, tandis que l'event CampaignParticipationStarted lui contient carrément directement la campaignParticipation.

2020-11-23 09:48 UTC, laura-bergoens requested changes
Je réclame re-considération de l'usage de organizationRepository.get() qui est un petit piège perf pour moi

2020-11-23 10:40 UTC, ajoanny approved these changes

2020-11-23 10:40 UTC, ajoanny commented on api/lib/domain/events/handle-pole-emploi-participation-started.js
> +  if (campaign.isAssessment() && organization.isPoleEmploi) {
*question (non-blocking) :**. Je me demande si se serait bien d'avoir ces info dans l'event ?

2020-11-23 10:40 UTC, ajoanny commented on api/lib/infrastructure/externals/pole-emploi/PoleEmploiPayload.js
> +  }
**question (non-blocking). :** J'ai pas mieu comme implem la mais j'ai un peu peur des futurs dev sur ce bout de code on risque de finir avec beaucoup de case ?  Ou il n'y aura que les commencé, terminé, partagé ?
Comme c'est des events différents ou pourrait faire des objet différents

2020-11-23 10:40 UTC, ajoanny commented on api/tests/unit/domain/events/handle-pole-emploi-participation-started_test.js
> +    const error = await catchErr(handlePoleEmploiParticipationShared)({ event, ...dependencies });
**question :** il y a `handlePoleEmploiParticipationShared ` mais on est pas dans le bon fichier ? ou alors c'est pas la bonne méthode qui est appelée ?

2020-11-23 10:40 UTC, ajoanny commented on api/lib/infrastructure/externals/pole-emploi/PoleEmploiPayload.js
> +  }
En fait il y a deux méthode pour build le payload, donc au moment de l'event on sait qu'elle état utilisé, sauf qu'après on passe par PoleEmploiPayload (factorisation) et à la fin on doit faire le switch case pour utilisé les bonne donnée c'est dommage la factorisation nous rajoute du travail.

2020-11-23 16:08 UTC, laura-bergoens commented on api/lib/domain/events/handle-pole-emploi-participation-started.js
> +  if (campaign.isAssessment() && organization.isPoleEmploi) {
oui pourquoi pas, si elles sont dispos en amont ça serait bien pratique

2020-11-23 16:09 UTC, laura-bergoens commented on api/tests/unit/domain/events/handle-pole-emploi-participation-started_test.js
> +    const error = await catchErr(handlePoleEmploiParticipationShared)({ event, ...dependencies });
purée ce sniper

2020-11-23 16:28 UTC, bpetetot commented on api/lib/domain/events/handle-pole-emploi-participation-shared.js
> +  const organization = await organizationRepository.get(organizationId);
Bien vu ! en effet, il limiter ce nombre de requêtes. 
Des 2 solutions, je préfère `organizationRepository.hasTags(tags)`

2020-11-23 16:30 UTC, bpetetot commented on api/lib/domain/events/handle-pole-emploi-participation-shared.js
> +  const { organizationId, campaignId, userId, campaignParticipationId } = event;
C'est lié à l'architecture actuelle avec la gestion des évènements. Ça serait bien que je vous présente rapidement la problématique et qu'on voit ensemble ce qu'on peut faire.

2020-11-23 16:34 UTC, bpetetot commented on api/lib/infrastructure/externals/pole-emploi/PoleEmploiPayload.js
> +  }
> En fait il y a deux méthode pour build le payload, donc au moment de l'event on sait qu'elle état utilisé, sauf qu'après on passe par PoleEmploiPayload (factorisation) et à la fin on doit faire le switch case pour utilisé les bonne donnée c'est dommage la factorisation nous rajoute du travail.

Je vois ce qui peut poser problème mais je ne comprends pas vraiment ce que tu veux dire, je pense qu'il faut qu'on en discute.

2020-11-23 16:34 UTC, bpetetot commented on api/tests/unit/domain/events/handle-pole-emploi-participation-started_test.js
> +    const error = await catchErr(handlePoleEmploiParticipationShared)({ event, ...dependencies });
oups

2020-11-24 14:19 UTC, bpetetot commented on api/lib/domain/events/handle-pole-emploi-participation-shared.js
> +  const organization = await organizationRepository.get(organizationId);
Suite à la mob-review on conserve cette implémentation afin de garder la logique métier au sein du modèle `organization`. Dans une tâche future il faudra revoir l'implementation du `organizationRepository.get` et de la gestion du modèle `organization`

2020-11-24 14:20 UTC, bpetetot commented on api/lib/domain/events/handle-pole-emploi-participation-started.js
> +  if (campaign.isAssessment() && organization.isPoleEmploi) {
Suite à la mob-review, il a été décidé d'éviter de passer des éléments spécifiques à un handler dans l'évènement

2020-11-24 14:21 UTC, bpetetot commented on api/lib/infrastructure/externals/pole-emploi/PoleEmploiPayload.js
> +  }
Suite à la mob-review, il a été décidé de conserver cette implémentation.

2020-11-24 14:21 UTC, bpetetot commented on api/lib/domain/events/handle-pole-emploi-participation-shared.js
> +  const { organizationId, campaignId, userId, campaignParticipationId } = event;
Suite à la mob-review, il a été décidé de passer uniquement des identifiants au niveau des évènements.

2020-11-24 14:58 UTC, laura-bergoens approved these changes

2020-11-24 22:33 UTC, merged