[FEATURE] Création de la page Mon Compte dans Pix App (PIX-452).
1024pix/pix pull request #2183
Opened 2020-11-20 17:54 UTC by octo-thlo

## :unicorn: Problème
Il est trop couteux pour l'équipe support de changer les mails des utilisateurs à chaque demande.

## :robot: Solution
Permettre directement à l'utilisateur de modifier ses informations personnelles.

Dans cette première PR, la page "Mon Compte" est ajoutée au menu déroulant "user logged menu".
Cette page permet dans un premier temps de visualiser son prénom, nom et adresse mail. 

## :rainbow: Remarques
Première version réalisée en mob programming ❤️

## :100: Pour tester
Se connecter à Pix App et cliquer sur "Mon Compte"

2020-11-20 17:59 UTC, pix-service commented
I'm deploying this PR to these urls:

- App: https://app-pr2183.review.pix.fr
- Orga: https://orga-pr2183.review.pix.fr
- Certif: https://certif-pr2183.review.pix.fr
- Admin: https://admin-pr2183.review.pix.fr
- API: https://api-pr2183.review.pix.fr/api/

 Please check it out!

2020-11-23 07:32 UTC, HEYGUL requested changes
Il y a des erreurs de linter + un `only` qui reste.
Je pense qu'on peut également utiliser les sélecteurs `data-test-*` our plus de robustesse des tests.

2020-11-23 07:32 UTC, HEYGUL commented on mon-pix/app/components/user-account-panel.js
> +}
Est-ce qu'on ne peut pas créer un "template only" component ?
cf https://guides.emberjs.com/release/upgrading/current-edition/glimmer-components/#toc_template-only-components

2020-11-23 07:32 UTC, HEYGUL commented on mon-pix/tests/acceptance/user-account-test.js
> +  describe.only('Display', function() {
Attention, `only` à supprimer

2020-11-23 07:32 UTC, HEYGUL commented on mon-pix/tests/acceptance/user-account-test.js
> +      expect(find('span[aria-label="Adresse e-mail"]').textContent).to.include(user.email);
La bonne pratique est d'utiliser les sélecteurs `data-test-*`.
cf https://ember-test-selectors.com/

2020-11-23 07:32 UTC, HEYGUL commented on mon-pix/tests/integration/components/user-account-panel-test.js
> +    expect(find('span[aria-label="Adresse e-mail"]').textContent).to.include(user.email);
Même commentaire pour les sélecteurs `data-test-*`.

2020-11-23 07:32 UTC, HEYGUL commented on mon-pix/tests/integration/components/user-logged-menu-test.js
> +      await render(hbs`{{user-logged-menu _canDisplayMenu=true}}`);
```suggestion
      await render(hbs`<UserLoggedMenu @_canDisplayMenu=true>`);
```

2020-11-23 07:32 UTC, HEYGUL commented on mon-pix/tests/acceptance/user-logged-menu-test.js
> +      await click('a[aria-label="Mon compte"]');
Même commentaire pour les sélecteurs `data-test-*`.

2020-11-23 07:32 UTC, HEYGUL commented on mon-pix/tests/integration/components/user-logged-menu-test.js
> +      await render(hbs`{{user-logged-menu _canDisplayMenu=true}}`);
Je suis surpris que le paramètre du composant commence par un `_` qui est une convention pour indiquer un paramètre privé.

2020-11-24 07:21 UTC, octo-topi commented
> Il y a des erreurs de linter + un `only` qui reste.
> Je pense qu'on peut également utiliser les sélecteurs `data-test-*` our plus de robustesse des tests.

Ta remarque est intéressante, il y a plusieurs écoles:
- `aria-label`
- `data-test`
- texte uniquement

Que penses-tu de créer un ADR pour partager les avantages/inconvénients, quitte à laisser chaque équipe décider ?

2020-11-24 09:00 UTC, octo-thlo commented on mon-pix/app/styles/components/_user-account-panel.scss
> +.user-account-panel {
Tout ce qui est relatif à sa position devrait être déplacé dans le .scss du parent

2020-11-27 06:47 UTC, HEYGUL commented
> > Il y a des erreurs de linter + un `only` qui reste.
> > Je pense qu'on peut également utiliser les sélecteurs `data-test-*` our plus de robustesse des tests.
> 
> Ta remarque est intéressante, il y a plusieurs écoles:
> 
>     * `aria-label`
> 
>     * `data-test`
> 
>     * texte uniquement
> 
> 
> Que penses-tu de créer un ADR pour partager les avantages/inconvénients, quitte à laisser chaque équipe décider ?

Je ne pensais pas qu'il y avait débat. Ok pour en discuter en dehors de cette PR.
Le reste du code me semble ok.
Go merge !

2020-11-27 06:47 UTC, HEYGUL approved these changes

2020-11-27 08:17 UTC, MelanieMEB requested changes

2020-11-27 08:17 UTC, MelanieMEB commented on mon-pix/app/templates/user-account.hbs
> +        <h3 class="user-tutorials-banner__title">{{t 'pages.user-account.title'}}</h3>
Je propose un h1, car les titres doivent être dans l'ordre, et il n'y a pas de H1 ni de H2 dans cette page

2020-11-27 08:17 UTC, MelanieMEB commented on mon-pix/app/templates/user-account.hbs
> +    </header>
Ici on n'est pas particulièrement dans le header (c'est le header du site qui devrait avoir cette sémantique. Je propose de retirer <header> pour ne garder qu'un seul div.

Je propose aussi d'entourer le titre et le AccountPanel de la balise "main".

2020-11-27 08:17 UTC, MelanieMEB commented on mon-pix/app/templates/components/user-account-panel.hbs
> +    <span class="user-account-panel-item__value" aria-label={{t 'navigation.user.account-panel.first-name'}}>{{@user.firstName}}</span>
```suggestion
    <span class="user-account-panel-item__value">{{@user.firstName}}</span>
```
L’attribut aria-label ne doit être utilisé que lorsque le texte d’un label n’est pas visible à l’écran, hors les label sont visibles ici, donc il faut les supprimer.
Je propose d'utiliser des `data-test-*` pour les tests

2020-11-27 08:17 UTC, MelanieMEB commented on mon-pix/app/templates/components/user-account-panel.hbs
> +  <div class="user-account-panel__item">
Si l'idée de la page est d'avoir une liste d'information sur l'utilisateur, je propose d'utiliser `<ul><li>` (et d'en retirer le style)

2020-11-27 08:17 UTC, MelanieMEB commented on mon-pix/app/templates/components/user-logged-menu.hbs
> +            <LinkTo @route="user-account" aria-label={{t 'navigation.user.account'}} class="logged-user-menu__link" >
```suggestion
            <LinkTo @route="user-account" data-test-link={{t 'navigation.user.account'}} class="logged-user-menu__link" >
```
Pareil ici, les aria-label ne sont pas fait pour les tests :)

2020-11-27 13:41 UTC, MathieuGilet commented on mon-pix/app/templates/user-account.hbs
> +        <h3 class="user-tutorials-banner__title">{{t 'pages.user-account.title'}}</h3>
Done

2020-11-27 13:42 UTC, MathieuGilet commented on mon-pix/app/templates/user-account.hbs
> +    </header>
J'ai remplacé `header` par une div

2020-11-27 13:42 UTC, MathieuGilet commented on mon-pix/app/templates/components/user-account-panel.hbs
> +    <span class="user-account-panel-item__value" aria-label={{t 'navigation.user.account-panel.first-name'}}>{{@user.firstName}}</span>
Done

2020-11-27 13:42 UTC, MathieuGilet commented on mon-pix/app/templates/components/user-logged-menu.hbs
> +            <LinkTo @route="user-account" aria-label={{t 'navigation.user.account'}} class="logged-user-menu__link" >
Done

2020-11-27 13:43 UTC, MathieuGilet commented on mon-pix/app/templates/components/user-account-panel.hbs
> +  <div class="user-account-panel__item">
Ca, je n'ai pas fait, on verra dans la prochaine PR que l'on va débuter aujourd'hui (ajout de l'identifiant + logique d'affichage)

2020-11-27 13:53 UTC, octo-topi commented on mon-pix/app/templates/user-account.hbs
> +        <h3 class="user-tutorials-banner__title">{{t 'pages.user-account.title'}}</h3>
Corrigé

2020-11-27 13:53 UTC, octo-topi commented on mon-pix/app/templates/user-account.hbs
> +    </header>
Corrigé

2020-11-27 13:53 UTC, octo-topi commented on mon-pix/app/templates/components/user-account-panel.hbs
> +    <span class="user-account-panel-item__value" aria-label={{t 'navigation.user.account-panel.first-name'}}>{{@user.firstName}}</span>
Corrigé

2020-11-27 13:53 UTC, octo-topi commented on mon-pix/app/templates/components/user-account-panel.hbs
> +  <div class="user-account-panel__item">
Corrigé

2020-11-27 13:53 UTC, octo-topi commented on mon-pix/app/templates/components/user-logged-menu.hbs
> +            <LinkTo @route="user-account" aria-label={{t 'navigation.user.account'}} class="logged-user-menu__link" >
Corrigé

2020-11-27 13:53 UTC, octo-topi commented on mon-pix/tests/acceptance/user-logged-menu-test.js
> +      await click('a[aria-label="Mon compte"]');
Corrigé

2020-11-27 13:53 UTC, octo-topi commented on mon-pix/tests/integration/components/user-account-panel-test.js
> +    expect(find('span[aria-label="Adresse e-mail"]').textContent).to.include(user.email);
Corrigé

2020-11-27 13:53 UTC, octo-topi commented on mon-pix/tests/acceptance/user-account-test.js
> +      expect(find('span[aria-label="Adresse e-mail"]').textContent).to.include(user.email);
Corrigé

2020-11-27 13:54 UTC, MelanieMEB approved these changes

2020-11-27 13:55 UTC, merged