[FEATURE] Prise en compte des 0 après virgules et points dans QROC (PIX-1592)
1024pix/pix pull request #2189
Opened 2020-11-23 15:31 UTC by alexandrecoin

## :unicorn: Problème

Si la réponse à un QCU type nombre est 7 et si l'utilisateur ajoute un ou plusieurs zéro après une virgule OU un point alors la réponse doit être considérée comme valide.

ex : 7 = 7,0 = 7,00 = 7.0 = 7.00 etc

## :robot: Solution

- Ajout d'une méthode de validation du format de la réponse numéraire
- Split du process de validation suivant que la réponse de l'utilisateur est un numéraire ou littérale
- Refactorisation du code et update/ ajout de tests unitaires

## :rainbow: Remarques

Lors de la réalisation des tests, nous avons pris parti sur deux questions pouvant être considérées comme faisant partie du métier et sont donc amenées à être discutées davantage si besoin.

- Toute réponse non entière et inférieure à la solution (exemple: Réponse = 122.1 et Solution = 123) donne lieu à une réponse fausse
- Toute réponse contenant plusieurs caractères spéciaux ( virgules ou points uniquement - ex: 122,,1) donne lieu à une réponse fausse

## :100: Pour tester

Réaliser une épreuve QROC avec des nombres

2020-11-23 15:37 UTC, pix-service commented
I'm deploying this PR to these urls:

- App: https://app-pr2189.review.pix.fr
- Orga: https://orga-pr2189.review.pix.fr
- Certif: https://certif-pr2189.review.pix.fr
- Admin: https://admin-pr2189.review.pix.fr
- API: https://api-pr2189.review.pix.fr/api/

 Please check it out!

2020-11-24 14:35 UTC, MelanieMEB requested changes

2020-11-24 14:35 UTC, MelanieMEB commented on api/tests/unit/infrastructure/utils/string-utils_test.js
> +      { case: '1.00', expectedResult: 1 },
Vu le `expect` et `equal` d'après, c'est normal que ça passe, mais ça fait un peu bizarre d'avoir deux fois le même case avec deux expected différent. On voulait montrer quoi dans ces cas là ?

2020-11-24 14:35 UTC, MelanieMEB commented on api/tests/unit/infrastructure/utils/string-utils_test.js
> +  });
Je propose d'ajouter au moins un test sur `splitIntoWordsAndRemoveBackspaces`, qui est dans cet utils, pour pouvoir voir ce qu'il retourne.

2020-11-24 14:35 UTC, MelanieMEB commented on api/lib/domain/usecases/correct-answer-then-update-assessment.js
> +  }
*suggestion:* Retirer la validation ici.
Si l'utilisateur arrive à envoyer des lettres, il se retrouve avec une erreur et une page blanche, plutôt que seulement une mauvaise réponse. 

J'essaie de réfléchir si votre idée qui vérifie toutes les réponses fonctionnent bien. Il faudrait peut être en discuter avec le contenu, car ça sera à eux de ne mettre que des nombres pour que cela fonctionne (plutôt que d'utiliser le tag format), ce qui peut faire étrange à l'utilisation.

2020-11-24 14:39 UTC, MelanieMEB requested changes

2020-11-24 14:39 UTC, MelanieMEB commented on api/tests/unit/domain/services/solution-service-qroc_test.js
> +      { case:'when two numbers are strictly equal', answer: '0.123', solution: '0.123', expectedAnswerStatus: ANSWER_OK },
Vu dans les épreuves, j'ajouterais le cas : 
` { case:'when number has space', answer: '25 000', solution: '25000', expectedAnswerStatus: ANSWER_OK },`
Ce qui demande un nettoyage des espaces, sinon, le `parseFloat('25 000') === 25`

2020-11-24 14:41 UTC, MelanieMEB requested changes
**Fonctionnelle** : Sur l'épreuve rec9QNW7WaxlowDdL, il y a 3 réponses possible, mais seule la première fonctionne.

2020-11-24 14:42 UTC, MelanieMEB commented on api/tests/unit/domain/services/solution-service-qroc_test.js
> +      { case:'when 0 is added in front of the answer', answer: '0123', solution: '123', expectedAnswerStatus: ANSWER_OK },
**suggestion:** J'ajouterais un test multiple : 

      { case:'(multiple solutions) answer is not the first propose solution', answer: '23', solution: '21\n22\n23\n', expectedAnswerStatus: ANSWER_OK  },

2020-11-24 14:53 UTC, alexandrecoin commented on api/tests/unit/infrastructure/utils/string-utils_test.js
> +      { case: '1.00', expectedResult: 1 },
C'était au cas où une bonne réponse venait à être écrite de manière différente par le contenu, ce qui s'avère peu probable pour le `1.00` mais on l'a gardé.

2020-11-24 14:59 UTC, celineung commented on api/lib/domain/services/solution-service-qroc.js
> +  const pretreatedSolutions = splitIntoWordsAndRemoveBackspaces(solution);
```suggestion
  const pretreatedSolutions = splitIntoPossibleSolutions(solution);
````

2020-11-24 14:59 UTC, celineung commented on api/tests/unit/domain/services/solution-service-qroc_test.js
> +      { case:'when answer is close to actual solution (superior)', answer: '123,4', solution: '123', expectedAnswerStatus: ANSWER_KO },
**question:** est-ce normal que pour un même cas de test, le status est différent?

2020-11-24 15:24 UTC, sbedeau commented on api/lib/domain/services/solution-service-qroc.js
> +  const pretreatedSolutions = splitIntoWordsAndRemoveBackspaces(solution);
IMHO, ce renommage rendrait implicite ce que fait le code. On a mit 30 minutes à obtenir des certitudes sur le patrimoine au moment où on l'a découvert

2020-11-24 15:28 UTC, alexandrecoin commented on api/tests/unit/infrastructure/utils/string-utils_test.js
> +  });
D'après les différents tests de la fonction, le résultat retourné est un tableau contenant les différentes valeurs entrées par l'utilisateur.

2020-11-26 09:39 UTC, celineung approved these changes

2020-11-26 10:51 UTC, sbedeau approved these changes

2020-11-26 11:02 UTC, MelanieMEB requested changes
Fonctionnellement problématique de vérifier le format de toutes les épreuves pour certains cas : 
- Vérification de binaire (ex de réponse : 011110)
- Vérification de mot de passe (ex de réponse : 0000)

Je propose la solution de remonter le format "Nombre" et de se baser aussi dessus.

2020-11-26 11:02 UTC, MelanieMEB commented on api/lib/domain/services/solution-service-qroc.js
> +  return AnswerStatus.KO;
C'est jolie comme méthode !

2020-11-27 11:17 UTC, celineung commented
@MelanieMEB Nous venons de remarquer que sur l'épreuve `rec29qznHvUorePES`, les bonnes réponses sur Airtable sont soit en nombre, soit en toutes lettres. L'épreuve est format `nombre`.

Avec cette épreuve, nous ne rentrons pas dans notre cas de comparaison des solutions et réponses car on s'attend à:
- solution de type nombre
- réponse de type nombre
- format de l'épreuve de type nombre

Il faut prévoir d'uniformiser les épreuves de type `nombre` pour que les bonnes réponses soient numériques.

2020-11-30 11:05 UTC, MelanieMEB approved these changes

2020-11-30 13:40 UTC, merged