[DOC] Décider de la meilleure utilisation des sélecteurs sur les test front-end.
1024pix/pix pull request #2209
Opened 2020-11-27 08:23 UTC by octo-topi

## :unicorn: Problème
Suite à un retour de PR, il semble que la solution [ne soit pas partagée](https://github.com/1024pix/pix/pull/2183#issuecomment-734674614)

## :robot: Solution
Créer un ADR

2020-11-27 08:25 UTC, MelanieMEB commented on docs/adr/0015-utiliser-selecteur-***-test-front-end.md
> +- utiliser un sélecteur sur l'attribut `aria-label`
```suggestion
- utiliser un sélecteur sur l'attribut `aria-label` **seulement si l'attribut est déjà présent (ne pas l'ajouter pour les tests)**
```

2020-11-27 08:28 UTC, pix-service commented
I'm deploying this PR to these urls:

- App: https://app-pr2209.review.pix.fr
- Orga: https://orga-pr2209.review.pix.fr
- Certif: https://certif-pr2209.review.pix.fr
- Admin: https://admin-pr2209.review.pix.fr
- API: https://api-pr2209.review.pix.fr/api/

 Please check it out!

2021-01-13 15:54 UTC, octo-topi commented on docs/adr/0015-utiliser-selecteur-***-test-front-end.md
> +- utiliser un sélecteur sur l'attribut `aria-label`
Corrigé

2021-01-13 16:08 UTC, HEYGUL approved these changes
Top cette PR, on devrait y introduire l'usage de `ember-test-selectors` pour qu'elle soit complète.

2021-01-13 16:08 UTC, HEYGUL commented on docs/adr/0015-utiliser-selecteur-***-test-front-end.md
> +- utiliser un sélecteur sur attribut `data-test`
> - utiliser un sélecteur sur attribut `data-test`

Je milite pour cette solution.

2021-01-13 16:08 UTC, HEYGUL commented on docs/adr/0017-choisir-selecteur-test-front-end.md
> +# 1. Utiliser le sélecteur **** pour les test front-end
```suggestion
# 17. Utiliser le sélecteur **** pour les test front-end
```

2021-01-13 16:08 UTC, HEYGUL commented on docs/adr/0017-choisir-selecteur-test-front-end.md
> +Suite à un échange un PR, il semble que la solution [ne soit pas partagée](https://github.com/1024pix/pix/pull/2183#issuecomment-734674614)
```suggestion
Suite à un échange sur une PR, il semble que la solution [ne soit pas partagée](https://github.com/1024pix/pix/pull/2183#issuecomment-734674614)
```

2021-01-13 16:08 UTC, HEYGUL commented on docs/adr/0017-choisir-selecteur-test-front-end.md
> +- si la balise est déplacée
```suggestion
- la balise est déplacée
```

2021-01-13 16:08 UTC, HEYGUL commented on docs/adr/0017-choisir-selecteur-test-front-end.md
> +- utilisateur choisi une autre langue
```suggestion
- l'utilisateur choisit une autre langue
```

2021-01-13 16:08 UTC, HEYGUL commented on docs/adr/0017-choisir-selecteur-test-front-end.md
> +tests fragiles (lors d'une modification de texte, le test sort à tord en erreur). De plus, l'internationalisation
```suggestion
tests fragiles (lors d'une modification de texte, le test sort à tort en erreur). De plus, l'internationalisation
```

2021-01-13 16:26 UTC, octo-topi commented on docs/adr/0015-utiliser-selecteur-***-test-front-end.md
> +- utiliser un sélecteur sur attribut `data-test`
:exploding_head:

2021-01-18 13:26 UTC, jbuget approved these changes

2021-01-19 08:46 UTC, laura-bergoens requested changes, later dismissed
Je mets en changes requested car je ne veux pas que ce soit mergé de suite. J'ai l'impression qu'on n'est pas encore tous convaincus. A ce titre, j'ai ouvert ça -> https://github.com/1024pix/pix/pull/2410
je trouve que ça met en évidence qu'avoir de l'a11y permet de tester facilement (donc pas autant besoin de data-test-id que ce qu'on croit)

2021-01-19 10:16 UTC, octo-topi commented
Attente de décision

2022-02-03 10:40 UTC, octo-topi commented
PR cloturée faute de contributions depuis quelques mois, l'issue trace le travail à faire https://github.com/1024pix/pix/issues/4025

2022-02-03 10:40 UTC, closed without merging