[BUGFIX] Corriger le problème de timeout pour les tests de checkUserIsAdminAndManagingStudentsForOrganization (Pix-1746).
1024pix/pix pull request #2237
Opened 2020-12-03 10:57 UTC by ajoanny

## :unicorn: Problème
Les tests de checkUserIsAdminAndManagingStudentsForOrganization sont en timeout par moment.

## :robot: Solution
Donner plus de temps au test pour s'executer.

## :rainbow: Remarques
Peut-être qu'on devrait le faire pour tous les tests d'intégrations ?

## :100: Pour tester

2020-12-03 11:02 UTC, pix-service commented
I'm deploying this PR to these urls:

- App: https://app-pr2237.review.pix.fr
- Orga: https://orga-pr2237.review.pix.fr
- Certif: https://certif-pr2237.review.pix.fr
- Admin: https://admin-pr2237.review.pix.fr
- API: https://api-pr2237.review.pix.fr/api/

 Please check it out!

2020-12-03 11:04 UTC, laura-bergoens requested changes
Ca mérite plus d'investigations. Vu le code testé, il n'a aucune raison de bénéficier d'une rallonge de timeout.
Ou alors la rallonge faut la mettre à tout le monde, donc au niveau du cli mocha. 
En tout cas je suis contre allonger que celui-ci en particulier

2020-12-03 11:16 UTC, ajoanny commented
> Ca mérite plus d'investigations. Vu le code testé, il n'a aucune raison de bénéficier d'une rallonge de timeout.
> Ou alors la rallonge faut la mettre à tout le monde, donc au niveau du cli mocha.
> En tout cas je suis contre allonger que celui-ci en particulier

Je sais pas trop comment plus regarder ça,  je peux regarder le temps d'exécution sur la CI mais je sais trop quoi faire d'autre.
Je suis d'accord on pourrait rajouter du temps pour d'autre tests,  mais je ne le ferais pas pour tous les tests, les test unitaires doivent être rapide et 3s pour un test unitaires c'est trop (et 2 secondes aussi). Je vois bien cette rallonge pour les tests qui touchent la BDD (ou une autre dépendance du même genre), mais les autres tests n'en ont pas besoin .

2020-12-03 11:19 UTC, laura-bergoens commented
Ce que je trouve curieux c'est que ce code là en particulier il est assez "simple" et "rapide" je pense. On a des tests plus lourds que ça.

Si y'a une vraie récurrence sur ce flaky, ça vaut le coup d'y réfléchir, mais là c'est arrivé qu'une seule fois non ? peut-être juste un coup de mou de la BDD :shrug:

2020-12-03 12:46 UTC, ajoanny commented
Je pense pas que ce soir un récurrence sur ce test en particulier mais sur ceux qui tape la BDD celui-ci est tout petit est a peu de raison d'être en timeout.
Donc c'est peut-être un facteur externe  à ce test, un autre test qui aurais bloqué la BDD trop longtemps via un delete de quelque chose peut-être, le databaseBuilder aurait mis trop de temps à delete des lignes ?
En relançant les tests d'intégrations un truc comme 20 fois c'est les tests `Integration | Infrastructure | Utils | Knex` qui prennent le plus de temps qui sont parfois en timeout.
Je pense que c'est lié au aux traitements asynchrones en JS et à notre manière d'écrire les tests.

2020-12-04 09:42 UTC, xav-car approved these changes

2020-12-04 09:45 UTC, xav-car commented
ok pour le mini refacto.

on a moyen de logger le temps d'occupation de la BDD lors des test ci ? voir ce lequel prendrais du temps ?

2020-12-07 14:57 UTC, ajoanny commented
> on a moyen de logger le temps d'occupation de la BDD lors des test ci ? voir lequel prendrais du temps ?
Je  vais changer le reporter mais on devra remettre le dot reporter avant de merger

2020-12-07 15:14 UTC, ajoanny commented
Sur CircleCI

2020-12-07 15:16 UTC, ajoanny commented
La j'augmente le temps alloué à tous les tests qui ne sont pas unitaire, je sais pas si c'est mieux

2020-12-07 15:19 UTC, ajoanny commented
En local

✓ Integration | Infrastructure | Utils | Knex utils fetchPage should fetch the given page and return results and pagination data: 698ms
✓ Integration | Infrastructure | Utils | Knex utils fetchPage should correctly count rowCount with a distinct in the select clause: 129ms
✓ Integration | Infrastructure | Utils | Knex utils fetchPage #pagination.page should return the requested page when there are results: 1287ms
✓ Integration | Infrastructure | Utils | Knex utils fetchPage #pagination.page should return the requested page even when there are no results: 1337ms
✓ Integration | Infrastructure | Utils | Knex utils fetchPage #pagination.page should return the page 1 when requesting for page 1 or lower: 1241ms
✓ Integration | Infrastructure | Utils | Knex utils fetchPage #pagination.page should return the DEFAULT_PAGINATION.PAGE when not indicating the page: 1308ms
✓ Integration | Infrastructure | Utils | Knex utils fetchPage #pagination.pageSize should return the requested pageSize when there are results: 1305ms
✓ Integration | Infrastructure | Utils | Knex utils fetchPage #pagination.pageSize should return the requested page even when there less results than expected: 1183ms
✓ Integration | Infrastructure | Utils | Knex utils fetchPage #pagination.pageSize should return the requested page even when there are no results: 1166ms
✓ Integration | Infrastructure | Utils | Knex utils fetchPage #pagination.pageSize should return the DEFAULT_PAGINATION.PAGE_SIZE when not indicating the size: 1382ms
✓ Integration | Infrastructure | Utils | Knex utils fetchPage #pagination.rowCount should return the rowCount for the whole query when pagination has results: 1358ms
✓ Integration | Infrastructure | Utils | Knex utils fetchPage #pagination.rowCount should return the rowCount for the whole query even if there are no results with requested pagination: 1234ms
✓ Integration | Infrastructure | Utils | Knex utils fetchPage #pagination.pageCount should return the pageCount according to the total row count for the whole query according to the requested page size: 1261ms
✓ Integration | Infrastructure | Utils | Knex utils fetchPage #pagination.pageCount should return the pageCount even when the last page would be partially filled: 1485ms
✓ Integration | Infrastructure | Utils | Knex utils fetchPage #pagination.pageCount should return the pageCount even if there are no results with requested pagination: 1421ms

2020-12-27 09:40 UTC, closed without merging