[FEATURE] Déplacement du lien "Mes tutos" du menu utilisateur à la barre de navigation principale (PIX-1649).
1024pix/pix pull request #2239
Opened 2020-12-03 14:02 UTC by alexandrecoin

## :unicorn: Problème

Dans le cadre du développement du tableau de bord, nous souhaitons rendre la section des tutos plus visible.

## :robot: Solution

Déplacement du lien concerné du menu utilisateur (dropdown en desktop/ menu burger en mobile) à la barre de navigation principale.

## :100: Pour tester

Constater le déplacement du lien "Mes tutos" sur la RA.

2020-12-03 14:06 UTC, pix-service commented
I'm deploying this PR to these urls:

- App: https://app-pr2239.review.pix.fr
- Orga: https://orga-pr2239.review.pix.fr
- Certif: https://certif-pr2239.review.pix.fr
- Admin: https://admin-pr2239.review.pix.fr
- API: https://api-pr2239.review.pix.fr/api/

 Please check it out!

2020-12-03 16:15 UTC, jonasgrilleres approved these changes

2020-12-03 16:22 UTC, MelanieMEB requested changes
**Fonctionnel** : Le lien est encore présent dans le menu sous mon nom.

2020-12-04 06:24 UTC, alexandrecoin commented
> **Fonctionnel** : Le lien est encore présent dans le menu sous mon nom.

En effet 🤦 . C'est corrigé.

2020-12-04 13:28 UTC, celineung commented on mon-pix/app/templates/components/navbar-burger-menu.hbs
> -    {{t 'navigation.user.tutorials'}}
**suggestion:** supprimer la clé de traduction car on utilise désormais "navigation.main.tutorials"

2020-12-04 14:25 UTC, sbedeau approved these changes

2020-12-07 11:06 UTC, MelanieMEB approved these changes

2020-12-07 13:00 UTC, merged