[FEATURE] Permettre la connexion à Pole Emploi pour un utilisateur connecté à Pix (PIX-1736).
1024pix/pix pull request #2259
Opened 2020-12-09 09:50 UTC by MathieuGilet

## :unicorn: Problème
Aujourd'hui,  seuls les utilisateurs non connecté à PIx peuvent s'y connecter à travers Pôle Emploi Connect. Cette connexion permet, lors de la première connexion à Pix, de créer un utilisateur et de lui créer une méthode de connexion Pôle Emploi puis, lors des futurs connexion, de pouvoir retrouver l'utilisateur et mettre à jour sa méthode de connexion. Néanmoins, il n'existe aucun mécanisme permettant d'ajouter une méthode de connexion Pôle Emploi à un utilisateur déjà connecté à Pix.

## :robot: Solution
Permettre à un utilisateur connecté à Pix de se connecter à son compte Pôle Emploi afin d'ajouter la méthode d'authentification pole emploi lors de sa première connexion, puis de la mettre à jour lors des prochaines connexions.

## :rainbow: Remarques
Afin de permettre l'accès au endpoint d'authentification d'un utilisateur pole emploi à la fois pour un utilisateur non connecté à Pix et connecté à Pix, nous avons du utiliser un nouveau mode d'authentification: `optional` (https://hapi.dev/tutorials/auth/?lang=en_US#route)

## :100: Pour tester
> _Les instructions pour reproduire le problème, les profils de test, le parcours spécifique à utiliser, etc._

2020-12-09 09:55 UTC, pix-service commented
I'm deploying this PR to these urls:

- App: https://app-pr2259.review.pix.fr
- Orga: https://orga-pr2259.review.pix.fr
- Certif: https://certif-pr2259.review.pix.fr
- Admin: https://admin-pr2259.review.pix.fr
- API: https://api-pr2259.review.pix.fr/api/

 Please check it out!

2020-12-10 10:29 UTC, octo-thlo commented on api/lib/domain/usecases/authenticate-pole-emploi-user.js
> +        await authenticationMethodRepository.updatePoleEmploiAuthenticationComplementByUserId({ authenticationComplement, userId: authenticatedUserId });
**Problème Bloquant** : Vu avec @MathieuGilet , 

Aujourd’hui, si je suis connecté à Pix et que je m’authentifie via PE Connect, on rajoute ou on met à jour la méthode d’authentification pour ce user. 
Dans le cas où on trouve une authenticationMethod PE en base pour ce userId, même si l’identifiant externe PE existe déjà en base (toujours lorsque je suis connecté Pix), on met à jour les authenticationComplements sans modifier l’identifiant externe. On se retrouve donc avec des complements dont les tokens ne correspondent plus au bon identifiant externe PE.

Mathieu a suggéré de renvoyer une erreur pour ce cas dans un premier temps

2020-12-10 10:31 UTC, octo-thlo requested changes, later dismissed
On a discuté avec Mathieu d'un problème bloquant, voir le commentaire sur le canal Slack de l'équipe ou en commentaire du usecase `authenticate-pole-emploi-user`

2020-12-10 14:27 UTC, MathieuGilet commented on api/lib/domain/usecases/authenticate-pole-emploi-user.js
> +        await authenticationMethodRepository.updatePoleEmploiAuthenticationComplementByUserId({ authenticationComplement, userId: authenticatedUserId });
J'ai rajouté le renvoi d'une erreur dans  le cas que tu as cité. Pas de gestion dans le front de cette erreur par contre.

2020-12-11 12:42 UTC, chrc commented on api/lib/domain/usecases/authenticate-pole-emploi-user.js
> +const { UnexpectedUserAccount } = require('../errors');
Suggestion : `UnexpectedUserAccountError`

2020-12-13 20:26 UTC, chrc approved these changes

2020-12-14 09:20 UTC, MathieuGilet commented on api/lib/domain/usecases/authenticate-pole-emploi-user.js
> +const { UnexpectedUserAccount } = require('../errors');
C'est une erreur déjà existante et utilisée à plusieurs endroit mais on pourrait créer un ticket pour la renommer.

2020-12-14 09:43 UTC, merged