[FEATURE] Restreindre l'accès aux parcours Pole Emploi aux utilisateurs ayant un compte Pole Emploi (PIX-1636).
1024pix/pix pull request #2275
Opened 2020-12-14 09:55 UTC by MathieuGilet

## :unicorn: Problème
L'accès au parcours Pole Emploi ne nécessite pas aujourd'hui de posséder un compte Pole Emploi.

## :robot: Solution
Restreindre l'accès au parcours Pole Emploi aux utilisateurs possédant un compte Pole Emploi.

## :rainbow: Remarques
> _Des infos supplémentaires, trucs et astuces ?_

## :100: Pour tester
> _Les instructions pour reproduire le problème, les profils de test, le parcours spécifique à utiliser, etc._

2020-12-14 10:00 UTC, pix-service commented
I'm deploying this PR to these urls:

- App: https://app-pr2275.review.pix.fr
- Orga: https://orga-pr2275.review.pix.fr
- Certif: https://certif-pr2275.review.pix.fr
- Admin: https://admin-pr2275.review.pix.fr
- API: https://api-pr2275.review.pix.fr/api/

 Please check it out!

2020-12-16 13:49 UTC, chrc approved these changes

2020-12-23 15:28 UTC, octo-thlo requested changes
C'est peut-être une histoire de configuration, mais en RA et en local nous n'arrivons pas à accéder à l'authentification PE.

En RA on tombe sur une boucle de redirection infinie dès qu'on tente de renvoyer vers PE
Connect.
En local on arrive sur la page d'authentification mais avec un message d'erreur 
<img width="543" alt="Capture d’écran 2020-12-23 à 16 27 22" src="https://user-images.githubusercontent.com/46494361/103012407-db537980-453b-11eb-826b-c739d52c8fab.png">

2020-12-23 15:36 UTC, AndreiaPena requested changes
J'ai pu rejoindre la campagne QWERTY789 sans avoir à me connecter à Pôle Emploi.

- Je ne suis pas connecté à Pix, je vais sur `/campagnes`.
- Lorsque j'entre le code, j'ai une redirection vers le site PE mais avec une erreur **invalid_client** (remontée par Thierry).
Je n'ai donc pas pu me connecter à Pôle Emploi.

- Je reviens sur Pix, j'obtiens dans mon localStorage : 

<img width="343" alt="Capture d’écran 2020-12-23 à 16 30 03" src="https://user-images.githubusercontent.com/58915422/103013682-d5f72e80-453d-11eb-80a6-358852d27f37.png">


- Je me connecte de façon classique sur Pix et j'arrive sur la page pour commencer mon parcours : 
<img width="508" alt="Capture d’écran 2020-12-23 à 16 32 17" src="https://user-images.githubusercontent.com/58915422/103012884-87956000-453c-11eb-802f-db0ee2b44178.png">

- J'arrive sur la page pour renseigner l'identifiant Pôle Emploi. Je renseigne et j'arrive sur la page suivante : 
<img width="757" alt="Capture d’écran 2020-12-24 à 12 03 43" src="https://user-images.githubusercontent.com/58915422/103085665-a5b59b80-45e2-11eb-9f37-e9242c1dbabd.png">

- Je reviens sur la page précédente ( pour renseigner un identifiant Pole Emploi - avec le chaton ) et je renseigne à nouveau un identifiant, je valide et j'accède au parcours.
<img width="588" alt="Capture d’écran 2020-12-24 à 14 58 04" src="https://user-images.githubusercontent.com/58915422/103092737-86c20400-45f8-11eb-8bfe-3c9cb690a3cf.png">

2020-12-24 11:12 UTC, AndreiaPena reviewed
**Chipotage** En faisant la review, j'arrive sur cette page. Je ne sais pas si c'est c'est lié à la PR mais comme c'est la première fois que je vois cette page, je fais mes retours ici.

Très beau chaton mais... Il va rester ? :) 
Il manque aussi des majuscules pour le label => "Identifiant Pôle Emploi"
<img width="521" alt="Capture d’écran 2020-12-24 à 12 06 22" src="https://user-images.githubusercontent.com/58915422/103084955-9a617080-45e0-11eb-9db9-b02c8c0d0b11.png">

2020-12-24 11:29 UTC, octo-thlo commented
Pour revenir sur mon message précédent, en fait c'est leur environnement de production qui semble cassé pour le moment.

Si je configure la RA pour utiliser leur environnement de recette, tout se passe bien

2020-12-24 11:31 UTC, octo-thlo requested changes
Lorsque l'accès token est expiré (on a attendu 45 minutes), on peut reprendre son parcours de campagne sans avoir à se ré-authentifier via PE Connect

2020-12-24 12:57 UTC, octo-topi commented
> **Chipotage** En faisant la review, j'arrive sur cette page. Je ne sais pas si c'est c'est lié à la PR mais comme c'est la première fois que je vois cette page, je fais mes retours ici.
> 
> Très beau chaton mais... Il va rester ? :)
> Il manque aussi des majuscules pour le label => "Identifiant Pôle Emploi"
> <img alt="Capture d’écran 2020-12-24 à 12 06 22" width="521" src="https://user-images.githubusercontent.com/58915422/103084955-9a617080-45e0-11eb-9db9-b02c8c0d0b11.png">

Je ne sais pas pourquoi je reçois des notifs sur cette PR, mais suite à ce :cat: je me dois de mettre un 
**Chouette**

2020-12-24 13:39 UTC, octo-thlo commented on mon-pix/app/routes/campaigns/start-or-resume.js
> +  get _shouldVisitPoleEmploiLoginPage() {
**BSR non-bloquant** : Un peu compliqué de naviguer dans ce fichier, les méthodes privées ou publiques sont éparpillées sans ordre

2020-12-24 14:38 UTC, AndreiaPena requested changes
Autre comportement causé je pense par la présence de ce nextUrl dans le localStorage :

- Je suis un utilisateur ayant déjà commencé le parcours QWERTY789. 
- Je me connecte sur mon compte Pix, je vois la bannière pour reprendre mon parcours.
- Je clique sur reprendre, on me demande de me connecter à Pôle Emploi.
- Je ne le fait pas, je reviens en arrière, page profil Pix et je me déconnecte.
- Je veux me reconnecter avec le même compte et à la connexion on me renvoie directement sur le début de parcours QWERTY789, causé par la présence du nextURL dans mon LocalStorage.

Il faut peut être envisager un reset lors de la déconnexion Pix pour ne plus avoir le nextURL ?
Parce que ça va être problématique sur les ordinateurs partagés.

2020-12-24 14:39 UTC, octo-thlo commented on mon-pix/app/routes/application.js
> +      this.replaceWith(nextURL);
**Problème bloquant** : Attention, `nextURL` est toujours présent dans la session lorsqu'on se déconnecte.
Si un autre utilisateur complètement différent se connecte après moi sur la même machine, il sera redirigé directement vers la campagne PE.
Il sera bloqué au bout d'un moment à sa première tentative, mais il sera considéré comme ayant commencé le parcours

2020-12-24 14:41 UTC, octo-thlo commented on mon-pix/tests/acceptance/start-campaigns-workflow-test.js
> +        context('When campaign belongs to Pole Emploi organization', function() {
**Remarque bloquante** : Je pense qu'il pourrait manquer certains tests par rapport à nos précédents retours. Par exemple on pourrait tester un clic sur le bouton de reprise du parcours lorsque le demandeur d'emploi l'avait déjà commencé

2020-12-24 16:05 UTC, laura-bergoens commented
> **Chipotage** En faisant la review, j'arrive sur cette page. Je ne sais pas si c'est c'est lié à la PR mais comme c'est la première fois que je vois cette page, je fais mes retours ici.
> 
> Très beau chaton mais... Il va rester ? :)
> Il manque aussi des majuscules pour le label => "Identifiant Pôle Emploi"
> <img alt="Capture d’écran 2020-12-24 à 12 06 22" width="521" src="https://user-images.githubusercontent.com/58915422/103084955-9a617080-45e0-11eb-9db9-b02c8c0d0b11.png">

Tu veux qu'il aille où ? dehors seul dans le froid ? tortionnaire !

2020-12-28 13:10 UTC, MathieuGilet commented
> C'est peut-être une histoire de configuration, mais en RA et en local nous n'arrivons pas à accéder à l'authentification PE.
> 
> En RA on tombe sur une boucle de redirection infinie dès qu'on tente de renvoyer vers PE
> Connect.
> En local on arrive sur la page d'authentification mais avec un message d'erreur
> <img alt="Capture d’écran 2020-12-23 à 16 27 22" width="543" src="https://user-images.githubusercontent.com/46494361/103012407-db537980-453b-11eb-826b-c739d52c8fab.png">

La boucle sur RA est due au fait que l'environnement de production ne gère pas les scopes relatifs à l'envoi des résultats. Le problème en RA concernait un problème de configuration. En effet, l'url de l'host est surchargée un peu plus bas dans le fichier de configuration pour l'environnement de développement.

2020-12-29 08:46 UTC, MathieuGilet commented on mon-pix/app/routes/campaigns/start-or-resume.js
> +  get _shouldVisitPoleEmploiLoginPage() {
D'accord avec toi, je pense qu'il serait mieux de le faire dans une autre PR néanmoins.

2020-12-29 08:48 UTC, MathieuGilet commented on mon-pix/app/routes/application.js
> +      this.replaceWith(nextURL);
Une correction a été apportée afin de corriger ce problème. La variable nextUrl sera toujours présente mais seuls les utilisateurs qui viennent de se connecter à leur compte pôle emploi seront redirigés.

2020-12-29 08:52 UTC, MathieuGilet commented
L'erreur relevée par Andreia, à savoir, la possibilité d'accéder au parcours PE sans avoir été jusqu'au bout de l'authentification PE a été corrigé. Il faut dorénavant posséder un token Pix ayant le scope "pole_emploi_connect" afin d'accéder au parcours (token récupérable uniquement lorsque l'API a effectué un appel au la route de récupération d'un access token pole emploi).

2020-12-29 10:11 UTC, AndreiaPena approved these changes

2021-01-07 09:48 UTC, octo-thlo approved these changes

2021-01-07 16:39 UTC, merged