[FEATURE] Ouvrir les questions de niveau 6 (PIX-1781).
1024pix/pix pull request #2276
Opened 2020-12-14 11:05 UTC by jonasgrilleres

## :unicorn: Problème
Le niveau max des questions du référentiel est réglé en dur sur 5.

## :robot: Solution
Extraire ce paramètre dans une varenv et permettre de changer ce réglage de manière dynamique. 

## :rainbow: Remarques
> _Des infos supplémentaires, trucs et astuces ?_

## :100: Pour tester
Rajouter une varenv `MAX_REACHABLE_LEVEL` et constater que : 
- TBA

2020-12-14 11:09 UTC, pix-service commented
I'm deploying this PR to these urls:

- App: https://app-pr2276.review.pix.fr
- Orga: https://orga-pr2276.review.pix.fr
- Certif: https://certif-pr2276.review.pix.fr
- Admin: https://admin-pr2276.review.pix.fr
- API: https://api-pr2276.review.pix.fr/api/

 Please check it out!

2020-12-15 09:33 UTC, MelanieMEB requested changes
Pour l'instant OK.

Fonctionnellement : 
- J'ai un probleme quand je veux vérifier ma certif avec un niveau 6 (code P-KMKBXT33) sur /verification-certificat
- Le PDF de certification a aussi des valeurs de pix et de niveaux, à variabiliser

2020-12-15 12:59 UTC, HEYGUL commented
>     * J'ai un probleme quand je veux vérifier ma certif avec un niveau 6 (code P-KMKBXT33) sur /verification-certificat

Vu ce matin, c'est un bug déjà existant en production, un ticket spécifique a été créé : https://1024pix.atlassian.net/browse/PIX-1791
 
>     * Le PDF de certification a aussi des valeurs de pix et de niveaux, à variabiliser
Il faut ajouter l'information du nombre de niveaux accessibles lors du passage de la certification (migration à prévoir pour les certifications existantes).
Ensuite, on pourra modifier le template du PDF et variabiliser les champs en utilisant cette nouvelle information.

2020-12-17 09:31 UTC, MelanieMEB requested changes

2020-12-17 09:31 UTC, MelanieMEB commented on mon-pix/app/components/user-certifications-detail-competences-list.js
> +  }
Dans le cas de la certification, le `maxReachableLevel` est celui enregistré en base. Sinon, il y a une différence entre le PDF et la page finale qui a bien le niveau 5 s'il est ancien. 
Il faudrait utilisé l'info qui a l'air d'être remonté déjà.

2020-12-17 14:49 UTC, MelanieMEB approved these changes

2020-12-18 15:11 UTC, sbedeau approved these changes

2020-12-18 15:11 UTC, ghost commented on admin/app/controllers/authenticated/certifications/certification/informations.js
> +  MAX_REACHABLE_PIX_BY_COMPETENCE = this.MAX_REACHABLE_LEVEL * 8;
**nitpick (non-blocking):**  Pour la cohérence entre les apps
```suggestion
  MAX_REACHABLE_PIX_BY_COMPETENCE = this.MAX_REACHABLE_LEVEL * PIX_COUNT_BY_LEVEL;
```

2020-12-18 15:11 UTC, sbedeau commented on api/lib/domain/models/CertificationAttestation.js
> +const MAX_PIX_BY_COMPETENCE = 8;
**nitpick (non-blocking):** Pour la cohérence entre les apps
```suggestion
const PIX_COUNT_BY_LEVEL = 8;
```

2020-12-18 15:53 UTC, merged