[FEATURE] Afficher le nombre correct de signalements d'une certification sur la page de finalisation de session PixCertif (PIX-1487-1)
1024pix/pix pull request #2301
Opened 2020-12-17 14:41 UTC by laura-bergoens

## :unicorn: Problème
Le système d'ajout de signalements sur une certification lors de la finalisation de session a été réalisé de sorte à ce chaque signalement soit enregistré auprès de l'API au fur et à mesure (et non au clic sur "Finaliser"). Cela permet à la personne qui finaliser de pouvoir ajouter des signalements sans forcément finaliser la session de suite, de sorte à ne pas perdre son travail.
A ce jour, l'utilisateur n'avait aucune information concernant le nombre de signalements déjà déclarés sur des certifications en cours de finalisation.

## :robot: Solution
Afficher le nombre correct de signalements déjà déclarés d'une certification sur la page de finalisation de session.

## :rainbow: Remarques
> _Des infos supplémentaires, trucs et astuces ?_

## :100: Pour tester
Lancer l'API avec les toggles appropriés : `FT_CERTIF_PRESCRIPTION_SCO=true FT_REPORTS_CATEGORISATION=true npm start`
Se connecter avec certifsco@example.net, puis se rendre sur la page d'une session à finaliser.
Ajouter un signalement, puis fermer la page et réouvrir (pour vider le storage ember), constater le bon nombre de signalements affiché.

2020-12-17 14:45 UTC, pix-service commented
I'm deploying this PR to these urls:

- App: https://app-pr2301.review.pix.fr
- Orga: https://orga-pr2301.review.pix.fr
- Certif: https://certif-pr2301.review.pix.fr
- Admin: https://admin-pr2301.review.pix.fr
- API: https://api-pr2301.review.pix.fr/api/

 Please check it out!

2020-12-17 14:56 UTC, aceol approved these changes

2020-12-17 14:56 UTC, aceol commented on api/lib/infrastructure/repositories/certification-report-repository.js
> +        });
```suggestion
        return bluebird.mapSeries(certificationReports, (certificationReport) => _finalize({ certificationReport, transaction: trx)}));
```

2020-12-17 14:56 UTC, aceol commented on certif/app/components/session-finalization-reports-informations-step.hbs
> +                  {{/if}}
```suggestion
                  <p data-test-id="finalization-report-has-examiner-comment_{{report.certificationCourseId}}">
                  {{#if (gt report.certificationIssueReports.length 1)}}
                     {{report.certificationIssueReports.length}} signalements </p>
                  {{else}}
                    1 signalement
                  {{/if}}
                  </p>
```

2020-12-17 15:08 UTC, aceol approved these changes

2020-12-17 15:08 UTC, aceol commented on api/lib/infrastructure/repositories/certification-report-repository.js
> +        });
On pourrais aussi faire:
```javascript
const curriedFinalize = (certificationReport) => _finalize({ certificationReport, transaction: trx }) ;
return bluebird.mapSeries(certificationReports, curriedFinalize);
```

2020-12-17 16:02 UTC, Anne-Gaelle-S requested changes
Il me semble que y'a une feature à laisser pour l'ancienne manière de fonctionner ...

2020-12-17 16:02 UTC, Anne-Gaelle-S commented on api/lib/infrastructure/repositories/certification-report-repository.js
**suggestion (bloquante)**
Attention, quand le feature toggle CATEGORIZATION n'est pas activé il faut laisser cet ajout de signalement ici !
Je crois que le premier commit peut être drop

2020-12-17 16:17 UTC, Anne-Gaelle-S approved these changes
![image](https://user-images.githubusercontent.com/38167520/102513663-c97d5c80-408b-11eb-9aa9-8193be1bb20e.png)

2020-12-17 16:17 UTC, Anne-Gaelle-S commented on api/lib/infrastructure/repositories/certification-report-repository.js
> +  }
🎉 
J'avais eu peur en lisant le nom du commit, mais en fait tout vas bien x)

2020-12-17 16:17 UTC, Anne-Gaelle-S commented on api/tests/unit/domain/models/CertificationReport_test.js
> +    EMPTY_BLANK_AND_NULL.forEach((examinerComment) => {
**suggestion (non bloquante)**
Si on a qu'une valeur, pourquoi on boucle dessus ?  C'est pour après ? 
```suggestion
```

2020-12-17 18:13 UTC, laura-bergoens commented on api/lib/infrastructure/repositories/certification-report-repository.js
> +  }
🤗

2020-12-18 09:39 UTC, laura-bergoens commented on api/lib/infrastructure/repositories/certification-report-repository.js
> +  // Remove this behavior when FT_REPORTS_CATEGORISATION is removed
// Remove this behavior when FT_REPORTS_CATEGORISATION is removed (also search for examinerComment)

2020-12-18 10:42 UTC, merged