[FEATURE] Add campaign participation for dashboard api (PIX-1816).
1024pix/pix pull request #2307
Opened 2020-12-21 17:25 UTC by celineung

## :unicorn: Problème

## :robot: Solution
Ajouter un endpoint pour récupérer les campaign participation par users, triées par date de création et filtrées par status

## :rainbow: Remarques
> _Des infos supplémentaires, trucs et astuces ?_

## :100: Pour tester
> _Les instructions pour reproduire le problème, les profils de test, le parcours spécifique à utiliser, etc._

2020-12-21 17:31 UTC, pix-service commented
I'm deploying this PR to these urls:

- App: https://app-pr2307.review.pix.fr
- Orga: https://orga-pr2307.review.pix.fr
- Certif: https://certif-pr2307.review.pix.fr
- Admin: https://admin-pr2307.review.pix.fr
- API: https://api-pr2307.review.pix.fr/api/

 Please check it out!

2020-12-30 10:08 UTC, HEYGUL commented on api/lib/application/users/index.js
> +          '- Les aperçus des participations aux campagnes sont triées par ordre inverse de création' +
```suggestion
          '- Les aperçus des participations aux campagnes sont triés par ordre inverse de création' +
```

2020-12-30 10:08 UTC, HEYGUL commented on api/lib/application/users/index.js
> +          '  (les plus récentes en premier) et filtrées en fonction de la requête',
```suggestion
          '  (les plus récentes en premier) et filtrés en fonction de la requête',
```

2020-12-30 10:08 UTC, HEYGUL commented on api/lib/infrastructure/data/campaign.js
> +    return this.belongsTo('Organization', 'organizationId');
Est-ce qu'il ne manque pas une migration pour ajouter cette relation en base ?

2021-01-04 10:44 UTC, lisequesnel commented on api/lib/domain/models/User.js
> +    campaignParticipationOverviews = [],
c'est utile de le mettre dans le modèle du User ,

2021-01-04 10:55 UTC, lisequesnel requested changes, later dismissed

2021-01-04 10:55 UTC, lisequesnel commented on api/lib/infrastructure/serializers/jsonapi/user-serializer.js
> +      campaignParticipationOverviews: {
je pense qu'il faut regarder autour de l'attribut `nullIfMissing`, qui il me semble d'après la doc : 
```
nullIfMissing: Set the attribute to null if missing from your data input
```
Ça permettrait de ne pas l'inclure dans le modèle du user, de ne pas l'omit à la sauvegarde, etc. On le fait déjà dans pas mal de modèle (ping @laura-bergoens qui l'avait mis en place), exemple avec `campaignCollectiveResult` qui est serialisé à partir du `campaign-serializer` sans être présent dans le modèle `Campaign`.

2021-01-06 09:40 UTC, MelanieMEB requested changes

2021-01-06 09:40 UTC, MelanieMEB commented on api/lib/domain/usecases/find-user-campaign-participation-overviews.js
> +  return campaignParticipationOverviewRepository.findAllByUserId(userId, page);
Question : Ne pourrait-on pas avoir qu'une seule méthode de repository, sachant que la différence c'est un filtre ? 
`campaignParticipationOverviewRepository.findAllByUserId({ userId, page, states })` ?

2021-01-06 09:40 UTC, MelanieMEB commented on api/lib/domain/usecases/find-user-campaign-participation-overviews.js
> +    const newStates = Array.isArray(states) ? states : [states];
Proposition : 

```suggestion
    const newStates = [].concat(states);
```
devrait pouvoir faire l'affaire.

2021-01-06 09:40 UTC, MelanieMEB commented on mon-pix/app/components/campaign-participation-overview/card.hbs
> +    <h2 class="campaign-participation-overview-card-header__subtitle">{{@model.campaignTitle}}</h2>
Problème sur les titres : Il y a déjà un h1 sur la page. 
Il faudrait au moins qu'on soit en H3.
Ou peut être sur du strong

2021-01-06 09:40 UTC, MelanieMEB commented on mon-pix/app/components/dashboard/content.hbs
> +  <CampaignParticipationOverview::Grid @model={{@model}}/>
Sur le header du dessus : Logiquement, ça devrait êtr eun h2 (il manque un H1 dans la page).
Par contre, on affiche le titre même s'il n'y a pas de campagne participation.

Proposition  : pouvoir savoir si la liste des campagnes est vide pour savoir si on affiche la section

2021-01-06 09:40 UTC, MelanieMEB commented on mon-pix/config/environment.js
> +    };
Est-ce qu'on garde cette modification ?

2021-01-06 09:40 UTC, MelanieMEB commented on api/lib/infrastructure/serializers/jsonapi/campaign-participation-overview-serializer.js
> +  },
Question : est-ce qu'on a besoin de ces deux méthodes, est-ce que : 

```suggestion
  serialize(userCampaignParticipationOverview) {
      const { campaignParticipationOverviews, pagination } = userCampaignParticipationOverview;

    return new Serializer('campaign-participation-overview',
      {
        attributes: ['isShared', 'sharedAt', 'createdAt', 'organizationName', 'assessmentState', 'campaignCode', 'campaignTitle'],
        meta : pagination,
      }).serialize(campaignParticipationOverview);
  },
```

ne serait pas fonctionnel ? (même avec le meta vide ? )

2021-01-06 15:55 UTC, MelanieMEB commented on api/lib/infrastructure/repositories/campaign-participation-overview-repository.js
> +  },
Je propose de n'avoir qu'une seule méthode : 

```suggestion
  async findByUserIdWithFilters({ userId, states, page }) {
    const queryBuilder = _findByUserId({ userId });

    if (states && states.length > 0) {
      if (states.includes('ENDED')) {
        queryBuilder.modify(_filterWhithEndedState, states);
      } else {
        queryBuilder.modify(_filterByAssessmentStates, buildAssessementStates(states));
        queryBuilder.modify(_filterBySharedState, false);
        queryBuilder.whereNull('campaigns.archivedAt');
      }
    }

    const { results, pagination } = await _paginateQuery(queryBuilder, page);
    const campaignParticipationOverviews = _toReadModel(results);

    return {
      campaignParticipationOverviews,
      pagination,
    };
  },
```

Ce qui permettrait d'avoir dans le use-case : 

```
module.exports = async function findUserCampaignParticipationOverviews({ userId, states, campaignParticipationOverviewRepository, page }) {
  const newStates = [].concat(states)
  return campaignParticipationOverviewRepository.findByUserIdWithFilters({ userId, states: newStates, page });
};

```

2021-01-06 16:06 UTC, celineung commented on mon-pix/app/components/dashboard/content.hbs
> +  <CampaignParticipationOverview::Grid @model={{@model}}/>
Le titre "Accueil" a été ajouté en h1 avec `sr-only`

2021-01-06 16:59 UTC, celineung commented on mon-pix/config/environment.js
> +    };
config supprimée =)

2021-01-06 17:03 UTC, celineung commented on api/lib/infrastructure/data/campaign.js
> +    return this.belongsTo('Organization', 'organizationId');
@HEYGUL la table `campaigns` possède déjà une référence vers `organization` via `organizationId`

2021-01-06 17:37 UTC, HEYGUL commented on api/lib/domain/usecases/find-user-campaign-participation-overviews.js
> +    const newStates = Array.isArray(states) ? states : [states];
```suggestion
    const newStates = [...states];
```
doit même être possible

2021-01-06 17:38 UTC, HEYGUL commented on api/lib/infrastructure/data/campaign.js
> +    return this.belongsTo('Organization', 'organizationId');
parfait !

2021-01-07 09:18 UTC, MelanieMEB commented on api/lib/infrastructure/serializers/jsonapi/campaign-participation-overview-serializer.js
> +  },
Suggestion : ne pas mettre le deserializer si on ne l'utilise pas pour le moment.

2021-01-07 09:35 UTC, MelanieMEB commented on api/lib/domain/usecases/find-user-campaign-participation-overviews.js
> +    const newStates = Array.isArray(states) ? states : [states];
Si states n'est pas un tableau, tu ne pourra pas utiliser la notation `...` dessus je pense.

2021-01-07 10:51 UTC, francois2metz commented on api/lib/infrastructure/serializers/jsonapi/campaign-participation-overview-serializer.js
> +  },
On a repris la même logique qu'ailleurs, en l'occurence: https://github.com/1024pix/pix/blob/8f5fa350bea61f67e4a83c7c90e49b06f206965f/api/lib/infrastructure/serializers/jsonapi/jury-session-serializer.js#L5-L10

2021-01-08 10:20 UTC, MelanieMEB approved these changes
OK pour moi.
Proposition d'une petite modif : 
- Est-ce qu'on pourrait passer le font-size de pix-tags__compact à 0.7 rem ? (pour éviter le warning "Small text" de Wave ? (si c'est facilement faisable, c'est peut être dans pixui?)

2021-01-08 10:47 UTC, sbedeau requested changes

2021-01-08 10:47 UTC, ghost commented on api/lib/application/users/user-controller.js
> +    const { filter: { states }, page } = queryParamsUtils.extractParameters(request.query);
**nitpick (non-blocking):** Pour la lisibilité / simplicité / maintenabilité / vitesse d'évolutivité, j'ai tendance à préférer les syntaxes qui ne sont pas déstructurées.

Je pense que ça doit donner quelque chose du style : 

```suggestion
    const query = queryParamsUtils.extractParameters(request.query);
    const states = query.filter.states;
    const page = query.page;
```

2021-01-08 10:47 UTC, ghost commented on api/lib/infrastructure/repositories/campaign-participation-overview-repository.js
> +}
**nitpick (non-blocking):** Déplacer la méthode `buildAssessementStates` selon la step down rule (lecture de la méthode après sa première invocation dans `_filterByStates`)

**nitpick (blocking):** Renommer `buildAssessementStates` en `buildAssessmentStates` (sans le e)

**nitpick (non-blocking):** Renommer `buildAssessmentStates` en `_buildAssessmentStates` car c'est une méthode locale

2021-01-08 10:47 UTC, sbedeau commented on api/lib/domain/usecases/find-user-campaign-participation-overviews.js
> +  const newStates = states ? [].concat(states) : undefined;
**nitpick (non-blocking):** Le nom de la variable n'explicite pas vraiment son intention.
 
```suggestion
  const states = rawURIStates ? [].concat(rawURIStates) : undefined;
```
ou 
```suggestion
  const aggregatedURIStated = states ? [].concat(states) : undefined;
```

2021-01-08 10:47 UTC, sbedeau commented on api/tests/acceptance/application/users/users-get-campaign-participation-overviews_test.js
> +      it('should return found user with 200 HTTP status code', async () => {
```suggestion
      it('should return found campaign participation with 200 HTTP status code', async () => {
```

2021-01-08 10:47 UTC, sbedeau commented on api/tests/acceptance/application/users/users-get-campaign-participation-overviews_test.js
> +    context('when user has only one campaign', () => {
```suggestion
    context('when user has only one campaign participation', () => {
```

2021-01-08 10:47 UTC, sbedeau commented on api/tests/acceptance/application/users/users-get-campaign-participation-overviews_test.js
> +      it('should return only the ongoing campaign participation overviews with 200 HTTP status code', async () => {
**nitpick (non-blocking):** Encapsuler les tests liés au filtrage ensemble et encapsuler ceux de la pagination pour mettre en valeur les deux fonctionnalités (indépendantes) distinctement

2021-01-08 10:47 UTC, sbedeau commented on api/tests/acceptance/application/users/users-get-campaign-participations_test.js
> +describe('Acceptance | Controller | GET /user/id/campaign-participations', () => {
**nitpick (non-blocking):** Renommer le fichier en `users-controller-get-campaign-participations_test.js`

2021-01-08 10:47 UTC, sbedeau commented on api/tests/acceptance/application/users/users-get-campaign-participation-overviews_test.js
> +describe('Acceptance | Controller | users-controller-get-campaign-participation-overviews', () => {
**nitpick (non-blocking):** Renommer le fichier en `users-controller-get-campaign-participation-overviews_test.js`

2021-01-08 10:47 UTC, sbedeau commented on api/tests/integration/infrastructure/repositories/campaign-participation-overview-repository_test.js
> +      });
**suggestion (non-blocking):** Décrire les tests en tests paramétrisés

2021-01-08 10:47 UTC, sbedeau commented on api/tests/integration/infrastructure/repositories/campaign-participation-overview-repository_test.js
> +    });
**suggestion (non-blocking):** Décrire les tests en tests paramétrisés

2021-01-08 10:47 UTC, sbedeau commented on api/tests/integration/infrastructure/repositories/campaign-participation-overview-repository_test.js
> +    });
**suggestion (non-blocking):** Décrire les tests en tests paramétrisés

2021-01-08 10:47 UTC, sbedeau commented on api/tests/unit/domain/read-models/CampaignParticipationOverview_test.js
> +      expect(campaignParticipationOverview.campaignTitle).to.equal('campaignTitle');
**nitpick (non-blocking):** Faire le expect sur les valeurs de l'objet en entier plutôt qu'unitairement

2021-01-08 10:47 UTC, sbedeau commented on api/tests/unit/domain/usecases/find-user-campaign-participation-overview_test.js
> +describe('Unit | UseCase | find-user--campaign-participation-overviews', () => {
```suggestion
describe('Unit | UseCase | find-user-campaign-participation-overviews', () => {
```

2021-01-08 10:47 UTC, sbedeau commented on mon-pix/app/components/campaign-participation/grid.js
> -}
**issue (blocking):** Supprimer ce fichier qui n'est plus utile

2021-01-08 10:47 UTC, sbedeau commented on mon-pix/app/components/dashboard/content.hbs
> +  {{#if (gt @model.length 0)}}
**nitpick (non-blocking)** Extraire en méthode

```suggestion
  {{#if this.hasCampaignParticipationOverviews}}
```

2021-01-08 10:47 UTC, sbedeau commented on mon-pix/app/components/dashboard/content.hbs
> +        <p class="dashboard-content__info">{{t 'pages.dashboard.campaigns.subtitle'}}</p>
```suggestion
        <h2 class="dashboard-content-campaign-participation-overviews__title">{{t 'pages.dashboard.campaign-participation-overviews.title'}}</h2>
        <p class="dashboard-content-campaign-participation-overviews__info">{{t 'pages.dashboard.campaign-participation-overviews.subtitle'}}</p>
```

2021-01-08 10:47 UTC, sbedeau commented on mon-pix/app/routes/user-dashboard.js
> +    const nbCampaignParticipationOverviews = 9;
```suggestion
    const campaignParticipationOverviewsMaximumDisplayQuantity = 9;
```

2021-01-08 10:47 UTC, sbedeau commented on mon-pix/app/routes/user-dashboard.js
> +      'userId': user.id,
```suggestion
    const userId = this.currentUser.user.id;
    const nbCampaignParticipationOverviews = 9;
    const queryParams = {
      userId,
```

2021-01-08 10:47 UTC, sbedeau commented on mon-pix/app/styles/components/campaign-participation-overview/_card.scss
> +    line-height: normal;
**question:** Est-ce que ce n'est pas la valeur par défaut ?

2021-01-08 10:47 UTC, sbedeau commented on mon-pix/package.json
> +    "query-string": "^6.13.8",
**question:** Est-ce qu'on peut se passer d'ajouter une dépendance ?

2021-01-08 10:47 UTC, sbedeau commented on mon-pix/tests/integration/components/campaign-participation-overview/card-test.js
> +    expect(find('a').textContent.trim()).to.equal(this.intl.t('pages.campaign-participation-overview.card.send'));
**nitpick (non-blocking):** Utiliser la classe explicitement plutôt que `a`
```suggestion
    expect(find('a').textContent.trim()).to.equal(this.intl.t('pages.campaign-participation-overview.card.send'));
```

2021-01-08 10:47 UTC, sbedeau commented on mon-pix/tests/integration/components/campaign-participation-overview/grid-test.js
> +  it('should display campaign participation overview items', async function() {
**nitpick (non-blocking):** Pour la cohérence du test de rendering + aider à diminuer les confusions possibles avec les tests d'acceptance qui sont lié à du fonctionnel (`display` me semble d'avantage fonctionnel tandis que `rendering` me semble plus lié au technique)
```suggestion
  it('should render campaign participation overview items', async function() {
```

2021-01-08 10:47 UTC, sbedeau commented on mon-pix/tests/integration/components/campaign-participation-overview/grid-test.js
> +    await render(hbs`<CampaignParticipationOverview::Grid @model={{campaignParticipationOverviews}} />}`);
**nitpick (blocking):** Il faut éviter les `this` implicites pour éviter des surprises 
```suggestion
    await render(hbs`<CampaignParticipationOverview::Grid @model={{this.campaignParticipationOverviews}} />}`);
```

2021-01-08 10:56 UTC, celineung commented on api/lib/infrastructure/repositories/campaign-participation-overview-repository.js
> +function buildAssessementStates(states) {
```suggestion
function _buildAssessementStates(states) {
```

2021-01-08 10:56 UTC, celineung commented on api/tests/acceptance/application/users/users-get-campaign-participation-overviews_test.js
> +      user = databaseBuilder.factory.buildUser();
**suggestion:** `user` n'est pas utilisé, on peut le déclarer localement
```suggestion
const user = databaseBuilder.factory.buildUser();
```

2021-01-08 10:56 UTC, celineung commented on api/lib/infrastructure/repositories/campaign-participation-overview-repository.js
> +function _filterWhithEndedState(queryBuilder, states) {
```suggestion
function _filterWithEndedState(queryBuilder, states) {
```

2021-01-08 10:56 UTC, celineung commented on api/tests/integration/infrastructure/repositories/campaign-participation-overview-repository_test.js
> +      it('should retrieve no campaign participation overviews for the user when state is TO_SHARE', async () => {
```suggestion
      it('should retrieve one campaign participation overviews for the user when state is TO_SHARE', async () => {
```

2021-01-08 10:56 UTC, celineung commented on api/tests/integration/infrastructure/repositories/campaign-participation-overview-repository_test.js
> +      it('should retrieve no campaign participation overviews for the user when state is ENDED', async () => {
```suggestion
      it('should retrieve one campaign participation overviews for the user when state is ENDED', async () => {
```

2021-01-08 10:56 UTC, celineung commented on api/tests/unit/application/users/user-controller_test.js
> +      expect(response).to.deep.equal({});
```suggestion
      expect(campaignParticipationOverviewSerializer.serializeForPaginatedList).to.have.been.calledOnce;
      expect(response).to.deep.equal({});
```

2021-01-08 10:56 UTC, celineung commented on api/tests/unit/application/users/user-controller_test.js
> +      expect(response).to.deep.equal({});
```suggestion
      expect(campaignParticipationOverviewSerializer.serializeForPaginatedList).to.have.been.calledOnce;
      expect(response).to.deep.equal({});
```

2021-01-08 10:56 UTC, celineung commented on api/tests/unit/domain/usecases/find-user-campaign-participation-overview_test.js
> +});
**suggestion:** supprimer ce test car il est en doublon

2021-01-08 10:56 UTC, celineung commented on high-level-tests/e2e/cypress/integration/pix-app/user-dashboard.feature
> +  Scénario: Je souhaite voir mes parcours non finis et non partagés et reprendre mon parcours
```suggestion
  Scénario: Je souhaite voir mes parcours non finis et non partagés
```

2021-01-08 10:56 UTC, celineung commented on mon-pix/app/components/campaign-participation-overview/card.js
> +  get campaignCode() {
**suggestion:** supprimer ce get et mettre directement `@model.campaignCode` dans le card.hbs

2021-01-08 10:56 UTC, celineung commented on mon-pix/package.json
> +    "query-string": "^6.13.8",
Cette dépendance n'est plus nécessaire car nous ne passons plus manuellement les queryParam dans l'adapter.

**suggestion:** supprimer cette dépendance

2021-01-08 10:59 UTC, celineung commented on mon-pix/app/styles/components/campaign-participation-overview/_card.scss
> +    line-height: normal;
Cette classe css s'applique sur un `h3`, qui possède un line-height différent par défaut

2021-01-08 15:17 UTC, sbedeau commented on api/db/database-builder/factory/build-campaign-participation-elements-for-overview.js
> +module.exports = ({ userId, index, lastAssessmentState, campaignParticipationCreatedAt, campaignArchivedAt, isShared }) => {
**nitpick (non-blocking):** 
```suggestion
module.exports = function buildCampaignParticipation({
  id,
  campaignId,
  isShared = true,
  createdAt = faker.date.past(),
  sharedAt = faker.date.past(),
  userId,
  participantExternalId = faker.random.word(),
} = {}) {
```

2021-01-08 16:45 UTC, sbedeau approved these changes

2021-01-08 16:55 UTC, alexandrecoin approved these changes

2021-01-08 17:17 UTC, merged