[FEATURE] Ne pas renvoyer de résultat si l'identifiant de l'organization n'existe pas (PIX-1936).
1024pix/pix pull request #2340
Opened 2021-01-04 12:01 UTC by octo-topi

## :unicorn: Problème
Si, dans Pix Admin, lors de la recherche par ID d'organisation, on ne fournit pas un nombre
- une erreur est levée par la BDD
- un message est affiché dans Pix admin  "Erreur dans Ember"

## :robot: Solution
Ne pas causer d'erreur en BDD
Dans Pix Admin, afficher le message "Aucun résultat"

## :rainbow: Remarques
Ceci est un quick fix captain pour ne voir les autres erreurs de BDD

Pour la solution définitive, d'un certain point de vue, le fait que l'on stocke les identifiants sous forme de nombre est un détail d'implémentation, aussi empêcher l'utilisateur de saisir un nombre me laisse :thinking: 

## :100: Pour tester
Tester:
- aucun critère de recherche
- ID existant
- ID texte (foo)

2021-01-04 12:06 UTC, pix-service commented
I'm deploying this PR to these urls:

- App: https://app-pr2340.review.pix.fr
- Orga: https://orga-pr2340.review.pix.fr
- Certif: https://certif-pr2340.review.pix.fr
- Admin: https://admin-pr2340.review.pix.fr
- API: https://api-pr2340.review.pix.fr/api/

 Please check it out!

2021-01-04 13:10 UTC, lisequesnel commented
> L'option Joi native ne fonctionne pas dans le ficheir index.js car le parsing est fait dans le use-case.

Je ne vois aucun parsing dans le usecase, ni nulle part ailleurs 🤔 :
```
module.exports = function findPaginatedFilteredOrganizations({ filter, page, organizationRepository }) {
  return organizationRepository.findPaginatedFiltered({ filter, page });
};
```
Je vois pas pourquoi l'option Joi ne marcherait pas... Avec ce genre de validation (cf par exemple le fichier `target-profiles/index.js` et sa route GET `api/admin/target-profiles`) :
```
query: Joi.object({
            'filter[id]': Joi.number().integer().empty('').allow(null).optional(),
            'filter[name]': Joi.string().empty('').allow(null).optional(),
            'page[number]': Joi.number().integer().empty('').allow(null).optional(),
            'page[size]': Joi.number().integer().empty('').allow(null).optional(),
          }),
```

2021-01-04 15:21 UTC, jbuget requested changes
Tout d'abord, il manque quelques tests.

---

Par ailleurs, je ne suis pas certain que ce soit la bonne façon de régler le problème, qui n'est peut-être pas si simple à résoudre.

Pour commencer et dans un monde idéal, je pense qu'en cas de formattage de la donnée d'entrée, il ne faudrait pas renvoyer une `200 + data: []` mais une `400`. 

Du coup, je pense qu'on devrait utiliser les fonctionnalités de validation / schéma Joi fournit par Hapi, dans la définition de la route.

Autre impact : sur le front, qui devrait alors savoir réagir correctement en cas de `400` pour une requête de type search/filtering.

Morceau qui est actuellement mutualisé dans Pix UI, si ma mémoire est bonne.

2021-01-04 15:21 UTC, jbuget commented on api/lib/application/organizations/organization-controller.js
> +    if (options.filter && options.filter.id && isNaN(parseInt(options.filter.id))) {
Il manque les tests (peut-être TI pour ne pas se prendre la tête avec `queryParamsUtils. extractParameters` et `organizationSerializer.serialize ` et ne pas stubber pour stubber).

2021-01-05 08:29 UTC, octo-topi commented
> > L'option Joi native ne fonctionne pas dans le ficheir index.js car le parsing est fait dans le use-case.
> 
> Je ne vois aucun parsing dans le usecase, ni nulle part ailleurs thinking :
> 
> ```
> module.exports = function findPaginatedFilteredOrganizations({ filter, page, organizationRepository }) {
>   return organizationRepository.findPaginatedFiltered({ filter, page });
> };
> ```
> 
> Je vois pas pourquoi l'option Joi ne marcherait pas... Avec ce genre de validation (cf par exemple le fichier `target-profiles/index.js` et sa route GET `api/admin/target-profiles`) :
> 
> ```
> query: Joi.object({
>             'filter[id]': Joi.number().integer().empty('').allow(null).optional(),
>             'filter[name]': Joi.string().empty('').allow(null).optional(),
>             'page[number]': Joi.number().integer().empty('').allow(null).optional(),
>             'page[size]': Joi.number().integer().empty('').allow(null).optional(),
>           }),
> ```

Bien vu @lisequesnel c'était bien le controller, pas le use-case.
Il semble que la possibilité d'extraire des QS nested soit récente, d'où le code custom de Fortser en 2018 `extractParameters `
J'avais vu une solution avec [QS](https://github.com/ljharb/qs), mais je vois avec plaisir que c'est supporté nativement.
[Ce post SO](https://stackoverflow.com/questions/36125736/validating-json-query-string-as-query-param-using-joi) semble indiquer que le changement est postérieur à la version 20

2021-01-05 14:55 UTC, chrc approved these changes

2021-01-06 01:17 UTC, jbuget approved these changes

2021-01-06 09:00 UTC, merged