[TECH] Aligner la version de node local et CI sur le PAAS
1024pix/pix pull request #2360
Opened 2021-01-07 13:46 UTC by octo-topi

## :unicorn: Problème
Depuis la PR  #2110, la spécification de version de node référencée dans le [package.json](https://github.com/1024pix/pix/pull/2110/files#diff-40864722070f32c50b887df5b4a7b2ed8d67d8c0f634fcb2835da498447661a3) n'inclut plus la version patch ni minor
`"node": "14.x.x",`

Le buildpack Node utilisé par Scalingo utilise [semver.io](https://github.com/Scalingo/nodejs-buildpack#nodejs) pour la résoudre à la dernière version stable disponible (14.15.1 en novembre, 14.15.4 en janvier)

Hors, la version est spécifiée avec minor et patch sur 
- CI (.circleci/config.yml)
- local (.nvmrc)

Cela veut dire que, sans vigilance des développeurs, la version de node peut être différente d'avec le PAAS

## :robot: Solution
Une notation approchante existe sur [CircleCI](https://circleci.com/developer/images/image/cimg/node), mais elle mentionne la minor (ici, 4):
- lts
- 14.15

## :rainbow: Remarques
Le sujet est ouvert, merci de suggérer d'autres solutions

## :100: Pour tester
Lancer les tests 
- en local
- sur la CI

2021-01-07 13:50 UTC, pix-service commented
I'm deploying this PR to these urls:

- App: https://app-pr2360.review.pix.fr
- Orga: https://orga-pr2360.review.pix.fr
- Certif: https://certif-pr2360.review.pix.fr
- Admin: https://admin-pr2360.review.pix.fr
- API: https://api-pr2360.review.pix.fr/api/

 Please check it out!

2021-01-07 17:25 UTC, aceol commented
je serais partant pour la solution 1

2021-01-07 17:26 UTC, aceol requested changes, later dismissed
Je serais pour la solution 1

2021-01-07 22:34 UTC, jonathanperret requested changes, later dismissed
Pareil, je préfèrerais qu'on revienne à un numéro de version complet partout.

2021-01-14 16:10 UTC, chrc approved these changes

2021-01-15 16:50 UTC, octo-thlo approved these changes

2021-01-15 16:59 UTC, merged