[FEATURE] Affiche les clés de lectur associé aux profils cible dans l'admin (PIX-1966)
1024pix/pix pull request #2367
Opened 2021-01-11 11:06 UTC by francois2metz

## :unicorn: Problème

On ne peut pas voir les clés de lecture associé a un profil cible dans l'admin

## :robot: Solution

On les affiche avec leur nom, leur image et leur message.

## :rainbow: Remarques

Dans l'API, j'ai renvoyé l'url des many badges avec une URL /admin, ce qui semble différent des organisations associés mais ce point d'API n'existe que dans ce scope.

## :100: Pour tester

https://user-images.githubusercontent.com/86659/104171641-3ffb4900-5403-11eb-9139-134e3cd39b57.mp4

2021-01-11 11:20 UTC, pix-service commented
I'm deploying this PR to these urls:

- App: https://app-pr2367.review.pix.fr
- Orga: https://orga-pr2367.review.pix.fr
- Certif: https://certif-pr2367.review.pix.fr
- Admin: https://admin-pr2367.review.pix.fr
- API: https://api-pr2367.review.pix.fr/api/

 Please check it out!

2021-01-11 13:46 UTC, alexandrecoin commented on admin/app/components/target-profiles/badges/list-items.hbs
> +      <div class="table__empty content-text">Aucune clés de lecture associée</div>
```suggestion
      <div class="table__empty content-text">Aucune clé de lecture associée</div>
```

2021-01-11 13:46 UTC, alexandrecoin commented on admin/tests/integration/components/target-profiles/badges/list-items_test.js
> +  test('it should display the table', async function(assert) {
```suggestion
  test('it should display an empty table', async function(assert) {
```

2021-01-11 13:48 UTC, alexandrecoin commented on admin/tests/integration/components/target-profiles/badges/list-items_test.js
> +    assert.notContains('Aucune clés de lecture associée');
```suggestion
    assert.notContains('Aucune clé de lecture associée');
```

2021-01-11 13:48 UTC, alexandrecoin commented on admin/tests/integration/components/target-profiles/badges/list-items_test.js
> +  test('it should a message when empty', async function(assert) {
```suggestion
  test('it should display a message when empty', async function(assert) {
```

2021-01-11 13:48 UTC, alexandrecoin commented on admin/tests/integration/components/target-profiles/badges/list-items_test.js
> +    assert.contains('Aucune clés de lecture associée');
```suggestion
    assert.contains('Aucune clé de lecture associée');
```

2021-01-11 13:51 UTC, alexandrecoin reviewed
Je pense qu'il manque le CSS pour la feature.
(Y a-t-il une maquette pour à disposition ?)

2021-01-11 15:06 UTC, HEYGUL approved these changes

2021-01-11 15:08 UTC, MelanieMEB approved these changes
Une proposition et une question, mais ça me semble bon (et testé fonctionnellement)

2021-01-11 15:08 UTC, MelanieMEB commented on admin/app/components/target-profiles/badges/list-items.hbs
> +    {{/if}}
Je propose de mettre tout le tableau dans le premier if, et de faire seulement un else
```suggestion
      {{#if (gt @model.length 0)}}
    <table>
      <thead>
        <th>ID</th>
        <th>Image</th>
        <th>Nom</th>
        <th>Message</th>
      </thead>
        <tbody>
          {{#each @model as |badge|}}
            <tr>
              <td>{{badge.id}}</td>
              <td><img src={{badge.imageUrl}} alt={{badge.altMessage}} /></td>
              <td>{{badge.key}}</td>
              <td>{{badge.message}}</td>
            </tr>
          {{/each}}
        </tbody>
    </table>
    {{else}}
      <div class="table__empty content-text">Aucune clés de lecture associée</div>
    {{/if}}
```

2021-01-11 15:08 UTC, MelanieMEB commented on api/tests/unit/infrastructure/serializers/jsonapi/target-profile-serializer_test.js
> -        ],
Pourquoi on perd ces lignes ?

2021-01-11 17:10 UTC, francois2metz commented on api/tests/unit/infrastructure/serializers/jsonapi/target-profile-serializer_test.js
> -        ],
Parce qu'on n'a pas de champ `organizations` dans le model `TargetProfile`.

2021-01-11 17:27 UTC, francois2metz commented on admin/app/components/target-profiles/badges/list-items.hbs
> +    {{/if}}
J'avais repris la logique comme dans organization mais je préfére comme tu propose. Voici le résultat

![Screen Shot 2021-01-11 at 18 25 46](https://user-images.githubusercontent.com/86659/104216721-b7989a80-543a-11eb-8442-0b5a9b75f42e.png)

2021-01-11 17:41 UTC, sbedeau requested changes

2021-01-11 17:41 UTC, sbedeau commented on admin/app/components/target-profiles/badges.hbs
> +    @model={{@model}} />
**nitpick (~blocking):** 
- Items me semble superflu en présence de badge
- La syntaxe `TargetProfiles::Badges::ListItems` peut être remplacée par `TargetProfileBadgeList`. 

Du coup, je propose le renommage suivant pour respecter la grammaire anglosaxone 

```suggestion
  <TargetProfile::Badge::List @model={{@model}} />
```

ou simplement (la profondeur supplémentaire ne me semble pas forcément utile à ce stade):

```suggestion
  <TargetProfile::BadgeList @model={{@model}} />
```

2021-01-11 17:41 UTC, sbedeau commented on admin/app/components/target-profiles/badges/list-items.hbs
> +  {{#if (gt @model.length 0)}}
**nitpick (non-blocking):** Extraire cette méthode dans le `list-items.js`

```suggestion
  {{#if this.hasBadges}}
```

2021-01-11 17:41 UTC, sbedeau commented on admin/app/models/badge.js
> +export default class Badge extends Model {
**question:** Le terme a été désigné comme obsolète. Est-ce qu'on ne le remplacerait pas par sa terminologie métier actuelle ?

2021-01-12 08:40 UTC, francois2metz commented
> Je pense qu'il manque le CSS pour la feature. (resizer l'image ?)

On va le faire.

> **Question** : Y a-t-il une maquette à disposition ? thinking

:see_no_evil:

2021-01-12 08:41 UTC, francois2metz commented on admin/app/models/badge.js
> +export default class Badge extends Model {
C'est pertinent mais je pense qu'il faudrait tout renommer avec l'API

2021-01-12 10:04 UTC, francois2metz commented
Nous avons découvert que le title n'était pas le title mais une Key (de clef de lecture). Nous avons rajouté la colonne.
![Screenshot_2021-01-12 Pix Admin](https://user-images.githubusercontent.com/86659/104299734-da23c580-54c5-11eb-825f-9cd175268847.png)

2021-01-12 10:30 UTC, francois2metz commented on admin/app/components/target-profiles/badges.hbs
> +    @model={{@model}} />
On a fait ça

2021-01-13 09:26 UTC, celineung approved these changes

2021-01-13 09:34 UTC, sbedeau commented on admin/app/components/target-profiles/badge-list.hbs
> +  {{#if (gt @model.length 0)}}
**question:** Pourquoi préférer cette approche par rapport à celle proposée ?  
```suggestion
  {{#if (gt @model.length 0)}}
```

2021-01-13 09:34 UTC, sbedeau commented on admin/app/components/target-profiles/badges.hbs
> +  <TargetProfiles::BadgeList
**question:** Pourquoi avoir laissé le s de `TargetProfiles` ?  
```suggestion
  <TargetProfile::BadgeList
```

2021-01-13 09:43 UTC, HEYGUL commented on admin/app/components/target-profiles/badge-list.hbs
> +  {{#if (gt @model.length 0)}}
Parce que le composant est un `template-only` pour le moment, et on ne voulait pas créer un fichier .js uniquement pour ce comportement.

2021-01-13 09:54 UTC, HEYGUL commented on admin/app/components/target-profiles/badges.hbs
> +  <TargetProfiles::BadgeList
Parce que le répertoire existait avant cette fonctionnalité, et contenait déjà un `s`.

2021-01-13 15:38 UTC, sbedeau approved these changes

2021-01-13 15:55 UTC, merged