[FEATURE] Modifier le niveau max atteignable et le nombre de pix max atteignable sur pix-admin (PIX-1810).
1024pix/pix pull request #2369
Opened 2021-01-11 14:46 UTC by celineung

## :unicorn: Problème
Sur pix-admin, le sauvegarde de la page de détail d’une certification affiche un message d'erreur car le niveau maximum atteignable est désormais le niveau 6 (et non plus 5) et le nombre de pix max pour une compétence est désormais de 48 (et non plus 40).

## :robot: Solution
Mettre à jour le niveau max atteignable pour une compétence.

## :rainbow: Remarques
> _Des infos supplémentaires, trucs et astuces ?_

## :100: Pour tester
Sur la page de détail d’une certification > onglet “Détails” : lorsqu’un utilisateur Pix Admin clique sur le bouton “Enregistrer” , vérifier qu’aucune des compétences de la certification ne dépasse 48 pix / a un niveau au dessus du niveau 6 :
- si aucune compétence ne déplace le plafond, ALORS ne pas afficher de pop-in 
- sinon si au moins une compétence dépasse 48 pix et/ou dépasse le niveau 6, ALORS afficher la pop-in avec le bon message d’erreur

2021-01-11 14:51 UTC, pix-service commented
I'm deploying this PR to these urls:

- App: https://app-pr2369.review.pix.fr
- Orga: https://orga-pr2369.review.pix.fr
- Certif: https://certif-pr2369.review.pix.fr
- Admin: https://admin-pr2369.review.pix.fr
- API: https://api-pr2369.review.pix.fr/api/

 Please check it out!

2021-01-11 14:59 UTC, MelanieMEB approved these changes

2021-01-12 08:17 UTC, laura-bergoens commented
Je comprends pas pourquoi 90% des fichiers modifiés sont sur mon-pix, j'ai raté un épisode en lisant le descriptif de pr ?

2021-01-12 08:35 UTC, alexandrecoin requested changes
Les deux derniers commit appartiennent à un autre ticket et ont été ajouté à cette branche.
[Ticket](https://1024pix.atlassian.net/browse/PIX-1653?atlOrigin=eyJpIjoiODM2YzM0YTM1MjNiNGM4M2I1NGZkMDAxMWY1OGM4NGQiLCJwIjoiaiJ9)

2021-01-12 13:02 UTC, alexandrecoin approved these changes

2021-01-12 13:03 UTC, francois2metz approved these changes
LGTM

2021-01-12 16:01 UTC, merged