[FEATURE] Affichage des compétences recommandées dans le tableau de bord (PIX-1653).
1024pix/pix pull request #2394
Opened 2021-01-14 16:16 UTC by celineung

## :unicorn: Problème
La nouvelle page Accueil se construit progressivement
 Cette PR ajoute une section montrant les compétences recommandées à l'utilisateur.

## :robot: Solution
Les compétences recommandées affichées sont pour l'instant les 4 premières compétences non commencées dans l'ordre d'apparition sur la page profil (triées par la propriété index).

## :rainbow: Remarques
> _Des infos supplémentaires, trucs et astuces ?_

## :100: Pour tester
- Se rendre sur la page Accueil après avoir activé le feature toggle front FT_DASHBOARD.
- Visualiser la section "Compétences recommandées" en bas de la page
- Cette section affiche au maximum 4 compétences

2021-01-14 16:22 UTC, pix-service commented
I'm deploying this PR to these urls:

- App: https://app-pr2394.review.pix.fr
- Orga: https://orga-pr2394.review.pix.fr
- Certif: https://certif-pr2394.review.pix.fr
- Admin: https://admin-pr2394.review.pix.fr
- API: https://api-pr2394.review.pix.fr/api/

 Please check it out!

2021-01-15 09:13 UTC, MelanieMEB requested changes

2021-01-15 09:13 UTC, MelanieMEB commented on mon-pix/translations/en.json
> +                "title": ""
Je propose de pingé les traducteurs pour ajouter les traductions sur cette zone

2021-01-15 09:13 UTC, MelanieMEB commented on mon-pix/app/components/dashboard/content.js
> +    const MAX_SCORECARDS_TO_DISPLAY = 4;
Proposition : remonter cette variable en haut du composant

2021-01-15 09:13 UTC, MelanieMEB commented on mon-pix/app/components/dashboard/content.js
> +    return scorecards && scorecards.length > 0;
Proposition : 
```suggestion
    return this. recommendedScorecards.length > 0;
```

J'ai l'impression que sinon, on pourrait avoir 0 compétences non commencé mais que la méthode `hasRecommendedCompetences` renvoie true

2021-01-15 09:13 UTC, MelanieMEB commented on mon-pix/app/styles/app.scss
> +@import 'components/competence-card/list';
Question : est-ce qu'il y a conflit de nom css pour avoir besoin de faire attention à l'ordre ? la version mobile et desktop sont deux hbs différents, non ?

2021-01-15 09:48 UTC, sbedeau commented on mon-pix/app/styles/app.scss
> +@import 'components/competence-card/list';
Effectivement la version mobile et desktop sont deux hbs différents. 

Le problème vient du fait que desktop utilise du css qui override pour partie le css utilisé par mobile, d'où le besoin d'avoir mobile avant desktop. 

Il faudrait probablement envisager un refactor de ces cartes à l'occasion d'un point tech

2021-01-15 10:04 UTC, celineung commented on mon-pix/app/styles/app.scss
> +@import 'components/competence-card/list';
Oui, il y a un hbs competence-card-mobile et un autre competence-card-default.
On remarque que dans le fichier les imports sont triés. Ici, nous avons dû casser le tri car nous sommes mobile-first, et c'est le style desktop qui override le mobile. Si on inverse, le css casse.

2021-01-15 13:37 UTC, MelanieMEB commented on mon-pix/app/styles/app.scss
> +@import 'components/competence-card/list';
Ok !

2021-01-15 13:42 UTC, MelanieMEB commented on mon-pix/app/styles/components/competence-card/_list.scss
> +    justify-content: space-between;
J'hésite pour cette valeur de flex : 
Quand on a que 2 cartes,ça fait un grand écartement.
Possiblement ajouter des margin sur les cartes dans ce cas et retirer le space between

2021-01-15 13:48 UTC, celineung commented on mon-pix/app/styles/components/competence-card/_list.scss
> +    justify-content: space-between;
Donc ajouter le `space-between` dynamiquement seulement s'il y a plus de deux cartes à afficher ?

2021-01-18 08:00 UTC, francois2metz commented on mon-pix/app/styles/components/competence-card/_list.scss
> +    justify-content: space-between;
Ou sinon utiliser une grid comme pour les parcours

2021-01-18 09:28 UTC, sbedeau commented on mon-pix/app/styles/components/competence-card/_list.scss
> +    justify-content: space-between;
Je pense que grid est overkill dès lors que l'affichage est mono-dimensionnel. WDYT?

2021-01-18 11:07 UTC, celineung commented on mon-pix/app/styles/components/competence-card/_list.scss
> +    justify-content: space-between;
Après concertation avec Quentin, on est passé sur `display: grid`

2021-01-18 15:37 UTC, MelanieMEB approved these changes

2021-01-19 10:39 UTC, merged