[FEATURE] Amélioration de la phrase sur le consentement dans la landing page pour un parcours(2109).
1024pix/pix pull request #2508
Opened 2021-02-05 11:07 UTC by KaramHaitham

## :unicorn: Problème
Mise à jour de la phrase de consentement avant que le prescrit commence un parcours d'évaluation personnalisé.

## :robot: Solution
Remplacer l'ancienne phrase de consentement par la nouvelle

## :rainbow: Remarques
N/A

## :100: Pour tester
connectez-vous à pix app puis saisissez un code dans la section " j'ai un code ".
vous serez dirigé vers une page de présentation avant de commencer un parcours. Sous le bouton " J commence " , vous trouverez la nouvelle phrase de consentement.

2021-02-05 11:13 UTC, pix-service commented
I'm deploying this PR to these urls:

- App: https://app-pr2508.review.pix.fr
- Orga: https://orga-pr2508.review.pix.fr
- Certif: https://certif-pr2508.review.pix.fr
- Admin: https://admin-pr2508.review.pix.fr
- API: https://api-pr2508.review.pix.fr/api/

 Please check it out!

2021-02-05 15:01 UTC, yaelle6 approved these changes
review func ok

2021-02-08 09:14 UTC, ajoanny commented
test fonctionnel : 👍🏽

2021-02-08 09:15 UTC, ajoanny approved these changes

2021-02-08 10:21 UTC, xav-car approved these changes

2021-02-08 13:10 UTC, lisequesnel requested changes

2021-02-08 13:10 UTC, lisequesnel commented on mon-pix/translations/fr.json
> +                "legal": "En cliquant sur “Je commence”, les informations relatives à votre avancée dans le parcours seront transmises à l’organisateur du parcours pour lui permettre de vous accompag
pas de changement de phrase en anglais ??

2021-02-08 17:06 UTC, KaramHaitham commented on mon-pix/translations/fr.json
> +                "legal": "En cliquant sur “Je commence”, les informations relatives à votre avancée dans le parcours seront transmises à l’organisateur du parcours pour lui permettre de vous accompag
rien n'était indiqué dans le ticket sur l'anglais.

2021-02-09 16:22 UTC, KaramHaitham commented on mon-pix/translations/fr.json
> +                "legal": "En cliquant sur “Je commence”, les informations relatives à votre avancée dans le parcours seront transmises à l’organisateur du parcours pour lui permettre de vous accompag
la phrase en anglais à été changée aussi.

2021-02-10 09:38 UTC, lisequesnel requested changes
oulà, en fait je pense qu'il y a eu un gros problème de rebase : 
![image](https://user-images.githubusercontent.com/23451175/107491969-2416ce80-6b8c-11eb-9b04-dc98373d86ef.png)

2021-02-10 09:38 UTC, lisequesnel commented on CHANGELOG.md
> +
c'est bizarre qu'il y ai le changelog d'inclus dans cette PR... à mon avis c'est un problème de rebase

2021-02-10 10:23 UTC, KaramHaitham commented on CHANGELOG.md
> +
je ne sais pas pourquoi s'est arrivé , peut-être que j'ai mal fait le rebase, du coup j'ai refaite le rebase et c'est bon maintenant :)

2021-02-10 10:49 UTC, lisequesnel approved these changes

2021-02-10 10:50 UTC, lisequesnel commented
validé fonctionnellement en fr et en ✅

2021-02-10 10:51 UTC, merged