[FEATURE] Bloquer l'import des candidats pour tous les formats d'ODS sauf la liste des candidats (PIX-2074)
1024pix/pix pull request #2519
Opened 2021-02-08 12:59 UTC by iwazaru

## :unicorn: Problème

Historiquement, dès qu’un nouveau format de fichier d’import des candidats à une session de certification était mis en place, on faisait de façon à ce que les anciens formats soient toujours supportés. Ainsi, les utilisateurs ayant déjà préparé leurs fichiers sous l’ancien format, n’avaient pas à le convertir dans le nouveau ce qui limitait les frustrations. C’est donc cette même logique que nous avons suivi lorsque nous avons implémenté le nouveau format “liste des candidats”.

Dans ce nouveau format de fichier “liste des candidats”, le champ “Adresse email du destinataire des résultats” a été ajouté. Si les référents de centre laissent ce champ vide, aucun résultats de certification ne seront envoyés automatiquement au prescripteur de la certification. Si on permet d’importer les anciens formats du fichier d’import, il y a un risque que les référents ne se rendent pas compte qu’il est nécessaire de remplir ce nouveau champ, et donc qu’ils passent par le support pour réclamer les résultats de leurs candidats.

## :robot: Solution

Lorsqu’un référent importe un fichier pour ajouter des candidats à une session de certification, ajouter une validation sur le format du fichier :
- SI le format est la “liste des candidats” (et bien sûr que tous les champs obligatoires sont remplis), ALORS l’import fonctionne
- SINON SI le format est différent de la “liste des candidats”, ALORS afficher le message d’erreur suivant : “La version du document est inconnue ou obsolète.

Veuillez télécharger le modèle de liste des candidats et l'importer à nouveau.”

## :rainbow: Remarques
> _Des infos supplémentaires, trucs et astuces ?_

## :100: Pour tester
> _Les instructions pour reproduire le problème, les profils de test, le parcours spécifique à utiliser, etc._

2021-02-08 13:04 UTC, pix-service commented
I'm deploying this PR to these urls:

- App: https://app-pr2519.review.pix.fr
- Orga: https://orga-pr2519.review.pix.fr
- Certif: https://certif-pr2519.review.pix.fr
- Admin: https://admin-pr2519.review.pix.fr
- API: https://api-pr2519.review.pix.fr/api/

 Please check it out!

2021-02-09 09:27 UTC, Anne-Gaelle-S requested changes
Y'a 2 truc qui me chiffonne avec ce ticket :

- si on active pas le toggle `FT_IS_AUTO_SENDING_OF_CERTIF_RESULTS` l'import ne fonctionne plus et pourtant j'ai une notification de succès : 
<img width="1593" alt="image" src="https://user-images.githubusercontent.com/38167520/107342788-f153d400-6ac0-11eb-9477-ca46503d5359.png"> 

- Si on ne souhaite supporter **uniquement** la version avec la colonne `destinataire des résultats` pourquoi est-ce qu'on enlève pas le toggle dans la même PR ? Potentiellement, par erreur ou par manque de connaissance quelqu'un désactive le toggle en prod et on se retrouve avec une version non fonctionnelle, donc autant enlever le toggle si la version sans ne marche pas ?

2021-02-09 09:27 UTC, Anne-Gaelle-S commented on api/tests/integration/domain/services/certification-candidates-ods-service/.~lock.attendance_sheet-1-4_extract_ko_test.ods#
> +,clement,clement-pix.local,08.02.2021 11:01,file:///Users/clement/Library/Application%20Support/LibreOffice/4;
**remarque** 
C'est quoi ce fichier ? Il ne devrait pas être ajouté je pense ?

2021-02-09 11:13 UTC, sroccaserra commented on api/tests/acceptance/application/session/session-controller-import-certification-candidates-from-attendance-sheet_reports_categorization_test.js
> +          it('should return an 204 status after success in importing the ods file', async () => {
```suggestion
          it('should return a 204 status after success in importing the ods file', async () => {
```

2021-02-09 11:23 UTC, sroccaserra commented on api/tests/acceptance/application/session/session-controller-import-certification-candidates-from-attendance-sheet_reports_categorization_test.js
> +      it('should respond with a 400 when user cant import the candidates', async () => {
Proposition : en profiter pour ajouter la raison de l'échec dans la description du test (parce-que le candidat existe déjà en base si j'ai bien compris ?)

2021-02-09 11:29 UTC, sroccaserra commented on api/tests/integration/domain/services/certification-candidates-ods-service/certification-candidates-ods-service_test.js
> +  context('When attendance sheet is of version different than 1.4', () => {
Discussion intéressante pour plus tard : est-ce qu'on a encore cette notion de version si une seule version est supportée / connue, et qu'il n'y a aucun numéro de version dans le fichier ods ? La seule chose qui fait foi maintenant c'est la présence des bons headers je crois.

2021-02-09 11:51 UTC, iwazaru commented on api/tests/integration/domain/services/certification-candidates-ods-service/certification-candidates-ods-service_test.js
> +  context('When attendance sheet is of version different than 1.4', () => {
On s'est posé la question, mais on a choisi de garder "1.4" au cas où il aurait une "1.5". Je dirais que l'avantage des chiffres c'est que ça permet de savoir avec certitude qu'une version est plus récente qu'une autre et que c'est plus simple de dire "la version 1.4" que "la version avec la colonne _adresse du destinataire des résultats_". Après on a vu que ça introduisait des confusions (ex. il n'y avait aucun test pour la 1.4 et a certains endroits la colonne en question apparaissait dans du code qui concernait la 1.3).

2021-02-09 13:32 UTC, iwazaru commented on api/tests/acceptance/application/session/session-controller-import-certification-candidates-from-attendance-sheet_reports_categorization_test.js
> +      it('should respond with a 400 when user cant import the candidates', async () => {
On l'a déjà dans le `context` juste au-dessus a priori : 
```js
context('when at least one candidate is already linked to a user', () => {
```

2021-02-09 14:11 UTC, EGI-OCTO commented
> Y'a 2 truc qui me chiffonne avec ce ticket :
> 
> * si on active pas le toggle `FT_IS_AUTO_SENDING_OF_CERTIF_RESULTS` l'import ne fonctionne plus et pourtant j'ai une notification de succès :
> 
> <img alt="image" width="1593" src="https://user-images.githubusercontent.com/38167520/107342788-f153d400-6ac0-11eb-9477-ca46503d5359.png">
> 
> * Si on ne souhaite supporter **uniquement** la version avec la colonne `destinataire des résultats` pourquoi est-ce qu'on enlève pas le toggle dans la même PR ? Potentiellement, par erreur ou par manque de connaissance quelqu'un désactive le toggle en prod et on se retrouve avec une version non fonctionnelle, donc autant enlever le toggle si la version sans ne marche pas ?

Je suis d'accord que cette PR rend le toggle obsolète. Je serai plus pour merger et faire la PR qui vire le toggle directement ensuite (i.e. pas besoin que ça soit strictement la même PR)

2021-02-09 14:11 UTC, EGI-OCTO approved these changes

2021-02-09 14:17 UTC, Anne-Gaelle-S approved these changes

2021-02-09 14:25 UTC, merged