[TECH] Ajouter un titre sur les liens externes dans les consignes (PIX-2124).
1024pix/pix pull request #2529
Opened 2021-02-09 18:10 UTC by celineung

## :unicorn: Problème
Une icone sur un lien externe permet d'indiquer visuellement qu'il s'agit d'une page qui s'ouvre sur une nouvelle fenêtre.
Or, avec un lecteur d'écran, rien n'indique que la page s'ouvre dans une nouvelle fenêtre. En ouvrant le lien, l'utilisateur a le focus directement dans la nouvelle page et ne sait pas forcément qu'il a quitté Pix.

## :robot: Solution
Ajouter un attribut "title=Nouvelle fenêtre" sur le lien

## :rainbow: Remarques
> _Des infos supplémentaires, trucs et astuces ?_

## :100: Pour tester
Sur un challenges avec des liens (ex: recgzvi9msKskBUf8), vérifier que un `title="Nouvelle fenêtre"` a bien été ajouté sur l'élément lien.

2021-02-09 18:15 UTC, pix-service commented
I'm deploying this PR to these urls:

- App: https://app-pr2529.review.pix.fr
- Orga: https://orga-pr2529.review.pix.fr
- Certif: https://certif-pr2529.review.pix.fr
- Admin: https://admin-pr2529.review.pix.fr
- API: https://api-pr2529.review.pix.fr/api/

 Please check it out!

2021-02-10 09:16 UTC, HEYGUL approved these changes

2021-02-10 09:16 UTC, HEYGUL commented on mon-pix/translations/en.json
> +                "external-link-title": "",
Attention il manque la traduction.

2021-02-10 09:16 UTC, MelanieMEB commented on mon-pix/translations/en.json
> +                "external-link-title": "",
New window ?

2021-02-10 09:16 UTC, MelanieMEB commented on mon-pix/app/components/challenge-statement.js
> +    return formattedInstruction.replace(externalLinkRegex, this._insertLinkTitle.bind(this));
proposition : 
```suggestion
    const formattedEmailAndLinkInstruction = instruction.replace('${EMAIL}', this._formattedEmailForInstruction()).replace(externalLinkRegex, this._insertLinkTitle.bind(this));
    return formattedEmailAndLinkInstruction
```

ou 

```suggestion
    const formattedEmailInstruction = _formattedEmail(instruction);
    const formattedInstruction = _formattedLink(formattedEmailInstruction)
    return formattedInstruction;
```

2021-02-10 09:24 UTC, alexandrecoin commented on mon-pix/app/components/challenge-statement.js
> +    return formattedInstruction.replace(externalLinkRegex, this._insertLinkTitle.bind(this));
♥️ pour la deuxième suggestion.

2021-02-10 09:24 UTC, alexandrecoin approved these changes

2021-02-10 09:48 UTC, MelanieMEB requested changes

2021-02-10 09:48 UTC, MelanieMEB commented on mon-pix/app/components/challenge-statement.js
> +    return formattedInstruction.replace(externalLinkRegex, this._insertLinkTitle.bind(this));
```suggestion
    return formattedInstruction.replaceAll(externalLinkRegex, this._insertLinkTitle.bind(this));
```

Sinon, seul la première occurrence est remplacé. 
Dans le cas de l'épreuve recxDBTrZbLTPiaDi, seul le premier lien a ce title.

2021-02-10 15:41 UTC, MelanieMEB approved these changes

2021-02-10 16:56 UTC, merged