[A11Y] Suppression de tag 'alt' inutile (PIX-1895).
1024pix/pix pull request #2547
Opened 2021-02-12 16:06 UTC by alexandrecoin

## :unicorn: Problème

Le chronomètre utilisé sur les épreuves chronométrées contient une balise `alt` avec une description qui n'est pas utile car l'icône est purement décorative.

## :robot: Solution

Remplacer la description du tag par une chaine de caractères vide.

## :rainbow: Remarques

Les traductions associées ne sont plus utilisées et donc supprimées également.

## :100: Pour tester

Aller sur une épreuve chronométrée (ex : recQgdAOar1PTVeW2 ) et constater la chaine de caractères vide dans la balise `alt` de l'icône chronomètre.

2021-02-12 16:12 UTC, pix-service commented
I'm deploying this PR to these urls:

- App: https://app-pr2547.review.pix.fr
- Orga: https://orga-pr2547.review.pix.fr
- Certif: https://certif-pr2547.review.pix.fr
- Admin: https://admin-pr2547.review.pix.fr
- API: https://api-pr2547.review.pix.fr/api/

 Please check it out!

2021-02-15 09:21 UTC, HEYGUL approved these changes

2021-02-15 09:33 UTC, sbedeau approved these changes
Ok pour moi

Idéalement, ça serait chouette de faire en sorte de ne plus avoir d'exception de template-lint

2021-02-15 09:33 UTC, sbedeau commented on mon-pix/app/templates/components/timeout-jauge.hbs
>        {{/if}}
**suggestion (non-blocking):** Pour avoir un seul rôle, on pourrait récupérer la source de l'image en ternaire ou via une computed. Les classes css ne servent qu'aux tests et n'ont pas lieue d'être par conséquent. On peut éventuellement remplacer par un data-test qui va checker la source de l'image

```hbs
<img src={{#if this.hasFinished "/images/icon-timeout-red.svg" "/images/icon-timeout-black.svg"}} alt="" role="none">
```

2021-02-15 09:39 UTC, alexandrecoin commented on mon-pix/app/templates/components/timeout-jauge.hbs
>        {{/if}}
Top ça, merci !

2021-02-15 10:06 UTC, celineung commented on mon-pix/app/templates/components/timeout-jauge.hbs
>        {{/if}}
**question:** Pourquoi assigner un `role` aux images ? Je suppose qu'implicitement une image a déjà le rôle `role="img"`.

2021-02-15 10:09 UTC, MelanieMEB commented on mon-pix/app/templates/components/timeout-jauge.hbs
>        {{/if}}
+1 pour la suggestion.
J'ajoute que les class actuelles ont l'air d'être inutile au passage.

2021-02-15 10:21 UTC, alexandrecoin commented on mon-pix/app/templates/components/timeout-jauge.hbs
>        {{/if}}
Le `alt` vide doit être accompagné d'un `role`. Voir : 
<img width="1041" alt="Capture d’écran 2021-02-15 à 11 21 02" src="https://user-images.githubusercontent.com/36371437/107934096-eb0d9e00-6f7f-11eb-935c-5ca8f5186946.png">

2021-02-15 10:29 UTC, celineung commented on mon-pix/app/templates/components/timeout-jauge.hbs
>        {{/if}}
Dans ce cas, mettre `role=none` partout ? Puisqu'on ne peut avoir que un `role=presentation` sur la page, pourquoi sur ce composant ci et pas ailleurs ?

2021-02-15 10:49 UTC, alexandrecoin commented on mon-pix/app/templates/components/timeout-jauge.hbs
>        {{/if}}
Je ne pense pas qu'on puisse le mettre partout vu que l'on dispose du temps restant à la question dans le composant, qui doit rester accessible aux lecteurs d'écrans.

2021-02-15 13:08 UTC, celineung approved these changes

2021-02-15 13:46 UTC, MelanieMEB approved these changes

2021-02-16 11:01 UTC, MelanieMEB requested changes
Fonctionnellement : 
Sur l'écran de warning, l'icone de temps s'est décalé et est maintenant collé au temps

Bravo pour le clean !

2021-02-16 11:19 UTC, sbedeau commented
> Fonctionnellement :
> Sur l'écran de warning, l'icone de temps s'est décalé et est maintenant collé au temps
> 
> Bravo pour le clean !

Bien vu merci, c'est corrigé dans le dernier commit

2021-02-17 09:26 UTC, celineung approved these changes

2021-02-17 09:26 UTC, celineung commented on mon-pix/tests/unit/components/timeout-gauge-test.js
> +          component.args.allottedTime = data.allottedTime;
**suggestion:** Je ne pense pas que l'on ait besoin de `allottedTime` dans ce test

2021-02-17 09:35 UTC, MelanieMEB approved these changes

2021-02-17 09:50 UTC, merged

2021-02-17 09:56 UTC, sbedeau commented on mon-pix/tests/unit/components/timeout-gauge-test.js
> +        it(`should return "${data.expected}" when allotting ${data.allottedTime}s and remainingSeconds is ${data.remainingSeconds}s`, function() {
nitpick: Supprimer le `data.allottedTime` résiduel
```js
it(`should return "${data.expected}" when remainingSeconds is ${data.remainingSeconds}s`
```