[FEATURE] Traduction de la page de la liste des participants d'une campagne d'évaluation(PIX-2158).
1024pix/pix pull request #2589
Opened 2021-02-19 11:12 UTC by KaramHaitham

## :unicorn: Problème
La page de la liste des participants d'une campagne d'évaluation n'est pas internationalisée.

## :robot: Solution
Internationaliser la page de la liste des participants d'une campagne d'évaluation

## :rainbow: Remarques
> _Des infos supplémentaires, trucs et astuces ?_

## :100: Pour tester
Se connecter à Pix Orga avec un compte pro et vérifier en anglais (en ajoutant "lang=en" dans l'URL) la page de la liste des participants d'une campaign dévaluation.

2021-02-19 11:16 UTC, pix-service commented
I'm deploying this PR to these urls:

- App: https://app-pr2589.review.pix.fr
- Orga: https://orga-pr2589.review.pix.fr
- Certif: https://certif-pr2589.review.pix.fr
- Admin: https://admin-pr2589.review.pix.fr
- API: https://api-pr2589.review.pix.fr/api/

 Please check it out!

2021-02-19 17:32 UTC, ajoanny commented
Test fonctionnel : Il manque deux traductions
- Palier
- Résultat thématique

 PS: On en a parlé mais je le note ici pour pas l'oublier

2021-02-19 17:38 UTC, ajoanny approved these changes

2021-02-19 17:38 UTC, ajoanny commented on orga/tests/integration/components/routes/authenticated/campaign/assessment/list-test.js
> +module.only('Integration | Component | routes/authenticated/campaign/assessment/list', function(hooks) {
**nitpick :** Il reste un only

2021-02-22 09:55 UTC, ajoanny approved these changes

2021-02-22 09:58 UTC, ajoanny commented
Test fonctionnel : KO
Les statuts des participations ne sont pas traduits
- En cours de test
- En attente

2021-02-22 10:35 UTC, KaramHaitham commented on orga/tests/integration/components/routes/authenticated/campaign/assessment/list-test.js
> +module.only('Integration | Component | routes/authenticated/campaign/assessment/list', function(hooks) {
👍

2021-02-22 10:50 UTC, ajoanny commented
Test Fonctionnel : OK

2021-02-22 15:05 UTC, lisequesnel commented on orga/app/components/routes/authenticated/campaign/assessment/list.hbs
>        </thead>
un `aria-label="Participant"` oublié plus bas ⬇️

2021-02-22 15:07 UTC, lisequesnel commented on orga/translations/en.json
> +      "assessment": {
pourquoi dans `campaign-list` ? C'est une page à part ça a sa place à part non ?

2021-02-22 15:08 UTC, lisequesnel commented on orga/translations/en.json
> -      "filters": {
pourquoi supprimer ça ? Les filtres sont utiles aussi dans les campagnes de collecte de profils, du coup c'est pas correct de les mettre que dans `assessment`

2021-02-22 15:09 UTC, lisequesnel commented on orga/translations/en.json
> +              "pix-label-id": "Company id",
Ceci est quelque chose de configurer par l'organisation, donc on a pas à le traduire

2021-02-22 15:09 UTC, lisequesnel commented on orga/translations/en.json
> +          "table": {
pourquoi `table` est sous `filters` ?

2021-02-22 15:11 UTC, lisequesnel commented on orga/app/components/routes/authenticated/campaign/participation-filters.hbs
>          @showOptionsOnInput={{true}}
le `emptyMessage` a été oublié

2021-02-25 09:12 UTC, lisequesnel commented on orga/app/components/routes/authenticated/campaign/participation-filters.hbs
>          @placeholder="Classes"
penser à remplacer ici aussi par la même chose que `title`
```suggestion
        @placeholder="Classes"
```

2021-02-25 09:50 UTC, KaramHaitham commented on orga/app/components/routes/authenticated/campaign/participation-filters.hbs
>          @placeholder="Classes"
C’était déjà remplacé  ,  j'ai oublié de pusher hier >.<

2021-02-25 11:42 UTC, lisequesnel commented on orga/translations/en.json
> +            "on-hold": "Pending"
ranger par ordre alphabétique

2021-02-25 11:42 UTC, lisequesnel commented on orga/translations/en.json
> +        "title": "Filters"
ranger par ordre alphabétique

2021-02-25 13:27 UTC, lisequesnel approved these changes

2021-02-25 13:29 UTC, lisequesnel requested changes

2021-02-25 13:29 UTC, lisequesnel commented on orga/translations/en.json
> +          "badges": "Filter Badges",
C'est un quiproquo sur le ppt de trad : il faut mettre uniquement "Thematic results" (sans Filter et pas badges)

2021-02-25 13:30 UTC, lisequesnel commented on orga/translations/en.json
> +            "title": "Filter Class"
C'est un quiproquo sur le ppt de trad : il faut mettre uniquement "Class"

2021-02-25 13:49 UTC, lisequesnel approved these changes
validé func & tech

2021-02-25 14:19 UTC, merged