[FEATURE] Tech fix reload timer
1024pix/pix pull request #2591
Opened 2021-02-19 15:04 UTC by celineung

## :unicorn: Problème
Sur une épreuve timée, le temps est limitée.
Mais lorsque l'utilisateur refraichit la page ou la quitte, le timer se reset et l'utilisateur dispose à nouveau de tout le temps nécessaire pour répondre à l'épreuve.

## :robot: Solution
1. Ajouter un listener sur l'évènement `beforeunload`: cet évènement est trigger lorsque la demande de rechargement de la page est faite. En utilisant `event.preventDefault`, on demande confirmation à l'utilisateur pour quitter la page.

2. Si l'utilisateur décide tout de même de quitter/rafraichir la page, alors l'event listener `unload` est triggered et on procède comme si l'utilisateur avait cliqué sur "Je passe".

## :rainbow: Remarques
- Je ne pense pas qu'il soit possible de customiser le message dans la popup de confirmation de quitter la page. J'ai l'impression que les navigateurs ont bloqué cette feature.

Autres pistes explorées:
- dans `router.js`, on écouté déjà sur `routeDidChange`. Cet évènement peut prendre en paramètre la **transition** (savoir de quelle url on vient et vers quel url on va). Mais ça ne marche que si on navigue à l'intérieur de l'app. Si on quitte l'app, l'évènement n'est pas déclenché
- stocker un cookie contenant les épreuves timers en cours, mais les cookies peuvent être supprimés du navigateur

## :100: Pour tester
> _Les instructions pour reproduire le problème, les profils de test, le parcours spécifique à utiliser, etc._

2021-02-19 15:09 UTC, pix-service commented
I'm deploying this PR to these urls:

- App: https://app-pr2591.review.pix.fr
- Orga: https://orga-pr2591.review.pix.fr
- Certif: https://certif-pr2591.review.pix.fr
- Admin: https://admin-pr2591.review.pix.fr
- API: https://api-pr2591.review.pix.fr/api/

 Please check it out!

2021-02-22 09:21 UTC, alexandrecoin reviewed
Fonctionnellement : A première vue, je peux encore avoir l'entièreté du temps à disposition si je rafraîchis la page. (cas de test de l'épreuve timée : rec1cSZ2hePondDBl )

2021-02-22 09:21 UTC, alexandrecoin commented on mon-pix/app/components/challenge-item-generic.js
> +  _hasAbandOrValidateAnswer = false;
```suggestion
  _hasAbandonedOrValidatedAnswer = false;
```
**Suggestion:** Renommage.

2021-02-22 09:21 UTC, alexandrecoin commented on mon-pix/app/components/challenge-item-generic.js
> +    window.addEventListener('unload', this._pageUnloadListener);
```suggestion
  _addQuitTimedChallengeListeners() {
    this._pageBeforeUnloadListener = (event) => {
      event.preventDefault();
    };
    this._pageUnloadListener = (event) => {
      event.preventDefault();
      if (!this._hasAbandOrValidateAnswer) {
        this.skipChallenge();
      }
    };
    window.addEventListener('beforeunload', this._pageBeforeUnloadListener);
    window.addEventListener('unload', this._pageUnloadListener);
  }

  _removeEventListeners() {
    if (this._pageBeforeUnloadListener) {
      window.removeEventListener('beforeunload', this._pageBeforeUnloadListener);
    }
    if (this._pageUnloadListener) {
      window.removeEventListener('unload', this._pageUnloadListener);
    }
  }
```

**Suggestion:** Inverser l'ordre des appels afin de mieux retranscrire l'ordre des évènements.

2021-02-22 10:25 UTC, MelanieMEB requested changes
Cette approche ne semble marcher que sur Firefox (sous Chrome, aucun changement par rapport à avant).

Il va falloir aussi voir avec @PhilippineLoison pour le fonctionnel assez fort de cette PR, mais ça donne enfin de l'espoir pour réussir à gérer ce soucis :)

2021-02-22 10:29 UTC, sbedeau commented on mon-pix/app/components/challenge-item-generic.js
> +  __hasAbandonedOrValidatedAnswer = false;
**question:** Pourquoi utiliser deux underscores ? 
```suggestion
  _hasAbandonedOrValidatedAnswer = false;
```

2021-02-22 10:29 UTC, sbedeau commented on mon-pix/app/components/challenge-item-generic.js
> +  }
**question:** Est-ce qu'on est sûr que la ligne `this._removeEventListeners()` sera bien appelée même après l'appel du super ? 
```suggestion
  willDestroy() {
    this._removeEventListeners();
    super.willDestroy(...arguments);
  }
```

2021-02-22 10:29 UTC, sbedeau commented on mon-pix/app/components/challenge-item-generic.js
> +      this.__hasAbandonedOrValidatedAnswer = true;
**suggestion:** On se trouve dans la méthode `skipChallenge`. J'aurais donc tendance à nommer comme suit :

```suggestion
      this.__hadSkippedOrValidatedAnswer = true;
```

2021-02-22 10:29 UTC, sbedeau commented on mon-pix/app/components/challenge-item-generic.js
> +      }
**thought:** Si je comprend bien, ce listener sera toujours appelé lors d'une question timée et on a besoin du booléen pour décider si on skip ou non. Je trouve qu'il y a une forme de couplage et de complexité qui naît de ça. Est-ce qu'on ne saurait pas détecter autrement / plus explicitement qu'il y a une réponse enregistrée (validée ou passée) ? 

Peut-être simplement en renommant `__hasAbandonedOrValidatedAnswer` par `_hasAnswerBeenRecorded` ?

2021-02-22 10:29 UTC, sbedeau commented on mon-pix/app/components/challenge-item-generic.js
> +    window.addEventListener('unload', this._pageUnloadListener);
**suggestion (non-blocking):** Les explications faites dans la description de la PR devraient pouvoir ressortir dans le code. Je pense qu'on y gagnerait à encapsuler le listener dans des méthodes qui explicitent l'intention pour les néophytes sur le sujet

```suggestion
_addQuitPromptListener() { 
    this._pageBeforeUnloadListener = (event) => {
      event.preventDefault();
    };
    window.addEventListener('beforeunload', this._pageBeforeUnloadListener);
}

_addOnConfirmedQuitPromptListener() {
	this._pageUnloadListener = (event) => {
      event.preventDefault();
      if (!this.__hasAbandonedOrValidatedAnswer) {
        this.skipChallenge();
      }
     } 
     window.addEventListener('unload', this._pageUnloadListener);
 } 
```

Les suggestion plus fines de nommage sont évidemment les bienvenues.

2021-02-22 10:58 UTC, jonasgrilleres commented on high-level-tests/e2e/cypress/integration/pix-app/challenge.feature
> +    Alors je vois que l'épreuve a déjà été répondue
```suggestion
    Alors je vois qu'il a déjà été répondu à l'épreuve
```

2021-02-22 10:58 UTC, jonasgrilleres commented on high-level-tests/e2e/cypress/support/step_definitions/assessment.js
> +then(`je vois que l'épreuve a déjà été répondue`, () => {
```suggestion
then(`je vois qu'il a déjà été répondu à l'épreuve`, () => {
```

2021-02-22 13:17 UTC, celineung commented on mon-pix/app/components/challenge-item-generic.js
> +    window.addEventListener('unload', this._pageUnloadListener);
Pour le premier `_addQuitPromptListener`: cela signifie que l'on met un listener sur la popup (à cause du mot `prompt`). Ce qui n'est pas le cas: on met un listener sur l'évènement rafraichir/quitter la page invoqué par l'utilisateur. Du coup, je suggèrerais juste `_addQuitListener`.

2021-02-22 16:52 UTC, celineung commented
PR fermée car au moment de recharger la page, le POST vers /answers (pour signaler à l'api que l'épreuve a été abandonnée) n'est pas aboutie. Il aurait fallu dans l'event listener `pagehide`/`unload` faire une requete `sendBeacon` ou `XMLHttpRequest`, mais dans ce cas il faudra reformatter la donnée au format JSONApi + mettre à jour la donnée dans EmberData car on sortira du cadre Ember.
Une autre solution pour empêcher de reset les timers sera étudiée dans une autre PR.

2021-02-22 16:52 UTC, closed without merging