[BUGFIX] Corriger le changement de mot de passe à usage unique pour un élève qui tente de se réconcilier (PIX-2196).
1024pix/pix pull request #2615
Opened 2021-02-24 08:50 UTC by chrc

## :unicorn: Problème
> _Décrivez ici le besoin ou l'intention couvert par cette Pull Request._

## :robot: Solution
> _Ajoutez à cet endroit, si nécessaire, des détails concernant la solution technique retenue et mise en oeuvre, des difficultés ou problèmes rencontrés._

## :rainbow: Remarques
> _Des infos supplémentaires, trucs et astuces ?_

## :100: Pour tester
> _Les instructions pour reproduire le problème, les profils de test, le parcours spécifique à utiliser, etc._

2021-02-24 08:56 UTC, pix-service commented
I'm deploying this PR to these urls:

- App: https://app-pr2615.review.pix.fr
- Orga: https://orga-pr2615.review.pix.fr
- Certif: https://certif-pr2615.review.pix.fr
- Admin: https://admin-pr2615.review.pix.fr
- API: https://api-pr2615.review.pix.fr/api/

 Please check it out!

2021-02-26 13:14 UTC, MathieuGilet approved these changes

2021-02-26 14:23 UTC, octo-topi commented on mon-pix/tests/unit/routes/update-expired-password-test.js
> +  it('should retrieve user model with not set id', async function() {
**chipotage**
tech
```suggestion
  it('should retrieve user model with null id', async function() {
```
fonctionnel
```suggestion
  it('should retrieve user model with unset id', async function() {
```
fonctionnel (mais ambigu car `undefined` est un concept JS)
```suggestion
  it('should retrieve user model with undefined id', async function() {
```

2021-02-26 14:25 UTC, octo-thlo commented
Tests fonctionnels OK ✅

2021-02-26 14:26 UTC, octo-topi commented on mon-pix/app/routes/update-expired-password.js
> +    const user = users.find(({ id }) => id === null);
**question**
En définitive, c'est quoi ce user ? C'est lequel, comment le nommer pourqu'on explicite l'intention ?

```suggestion
    const user = users.find(({ id }) => id === null);
```

2021-02-26 14:28 UTC, octo-topi commented on mon-pix/tests/unit/routes/update-expired-password-test.js
> +    ]);
**question**
idem que https://github.com/1024pix/pix/pull/2615/files#r583674909
```suggestion
    const userXXXX = EmberObject.create({ id: null, username: 'user.toupdate1501' });
    const userYYYY = EmberObject.create({ id: 1, username: 'user.name0112' });
    
    peekAllStub.returns([
      userXXXX, user YYYY
    ]);
```

2021-02-26 14:39 UTC, octo-thlo commented on mon-pix/app/routes/update-expired-password.js
> +    const user = users.find(({ id }) => id === null);
Laisser `user` ne me dérange pas, mais s'il faut être plus précis je propose 

```suggestion
    const userWithExpiredPassword = users.find(({ id }) => id === null);
```

2021-02-26 14:47 UTC, octo-thlo approved these changes

2021-02-26 14:56 UTC, octo-topi approved these changes

2021-02-26 14:57 UTC, octo-thlo commented on mon-pix/tests/unit/routes/update-expired-password-test.js
> +    ]);
Ok le test met le problème de lisibilité un peu plus en valeur.
En gros ce que tu recherches, c'est un nom de variable qui illustre clairement **pourquoi** avoir un id `null` ferait qu'on choisit ce user pour la mise à jour du mot de passe.

En proposition rapide dans notre cas, ça pourrait être quelque chose comme 
`userXXXX` = > `userWithCredentialsToMatchTheAccountFrom`
`userYYYY` => `userThatWasPreviouslyConnectedWithWrongAccount`

Quelqu'un a mieux ?

2021-02-26 20:23 UTC, chrc commented on mon-pix/tests/unit/routes/update-expired-password-test.js
> +  it('should retrieve user model with not set id', async function() {
Done

2021-02-26 20:23 UTC, chrc commented on mon-pix/app/routes/update-expired-password.js
> +    const user = users.find(({ id }) => id === null);
Done

2021-02-26 20:34 UTC, chrc commented on mon-pix/tests/unit/routes/update-expired-password-test.js
> +    ]);
Done

2021-03-01 07:49 UTC, octo-topi requested changes
**bloquant** **question**
Si j'ai bien compris:
- l'origine du problème est qu'il y a 2 utilisateurs dans le store
- fonctionnellement, l'un d'eux est hors scope (dans l'exemple `sco.admin @example.net`) lorsqu'on lui dit qu'un autre compte est déjà réconcilié
- lors du renvoi sur l'écran de connexion ("Continuer avec mon compte Pix", après la saisie du nouvel utilisateur (ex:george.decambridge2207) il ne devrait y avoir qu'un utilisateur dans le store, sauf si vous me trouvez un autre cas où il y en a besoin
- la solution est à la racine: après le clic sur "Continuer avec mon compte Pix", le sore ne doit plus contenir d'enregistrement

Note:
- j'avais déjà pensé à ça pendant la review et donné des indices avec la difficulté à nommer les JDD dans les tests
- mais je vois que personne n'a relevé, donc je donne "ma solution"

2021-03-01 09:24 UTC, octo-topi approved these changes
Ce ticket est un quickfix, validation en attente de la solution définitive

2021-03-01 11:55 UTC, merged