[FEATURE] Dans Pix App, ajouter "Mon compte" dans le menu utilisateur (PIX-2106).
1024pix/pix pull request #2616
Opened 2021-02-24 10:50 UTC by chrc

Display My account user menu
Don't display anymore user identifier

## :unicorn: Problème
> _Décrivez ici le besoin ou l'intention couvert par cette Pull Request._

## :robot: Solution
> _Ajoutez à cet endroit, si nécessaire, des détails concernant la solution technique retenue et mise en oeuvre, des difficultés ou problèmes rencontrés._

## :rainbow: Remarques
> _Des infos supplémentaires, trucs et astuces ?_

## :100: Pour tester
> _Les instructions pour reproduire le problème, les profils de test, le parcours spécifique à utiliser, etc._

2021-02-24 10:56 UTC, pix-service commented
I'm deploying this PR to these urls:

- App: https://app-pr2616.review.pix.fr
- Orga: https://orga-pr2616.review.pix.fr
- Certif: https://certif-pr2616.review.pix.fr
- Admin: https://admin-pr2616.review.pix.fr
- API: https://api-pr2616.review.pix.fr/api/

 Please check it out!

2021-02-24 13:32 UTC, octo-topi requested changes
Merci de supprimer le FT par la même occasion qui active le changement d'email

2021-02-24 15:34 UTC, AndreiaPena commented
**Question**: ça ne pose pas de problème de donner accès à la page Mon Compte sans toutes les traductions en anglais ? 

<img width="535" alt="Capture d’écran 2021-02-24 à 15 59 57" src="https://user-images.githubusercontent.com/58915422/109019683-7fcb7680-76b9-11eb-9174-031fb4be5bc1.png">
<img width="535" alt="Capture d’écran 2021-02-24 à 16 01 56" src="https://user-images.githubusercontent.com/58915422/109019860-ac7f8e00-76b9-11eb-9b01-fc6786ab6b1d.png">

2021-02-24 15:51 UTC, chrc commented
> Merci de supprimer le FT par la même occasion qui active le changement d'email dans le back (FT_MY_ACCOUNT)
> Ca évitera de l'oublier de l'alimenter lors de la MEP et de faire un autre ticket plus tard (= jamais)

Supprimer la FT, et aussi modifier les implem front (voir api) pour que la feature soit effective.

2021-02-24 15:53 UTC, octo-topi commented
> **Question**: ça ne pose pas de problème de donner accès à la page Mon Compte sans toutes les traductions en anglais ?
> 
> <img alt="Capture d’écran 2021-02-24 à 15 59 57" width="535" src="https://user-images.githubusercontent.com/58915422/109019683-7fcb7680-76b9-11eb-9174-031fb4be5bc1.png">
> 
> <img alt="Capture d’écran 2021-02-24 à 16 01 56" width="535" src="https://user-images.githubusercontent.com/58915422/109019860-ac7f8e00-76b9-11eb-9b01-fc6786ab6b1d.png">

Quand j'ai préparé la démo j'ai vu ça et suis passé sur une RA, et oublié de le remonter.. bien vu @AndreiaPena  !

2021-02-24 16:47 UTC, chrc commented
Suppression de FT_MY_ACCOUNT : Done

2021-02-24 16:48 UTC, chrc commented
Traduction et demande de traduction en anglais, en cours.

2021-02-25 10:44 UTC, octo-topi commented on api/lib/config.js
> +      reportsCategorization: isFeatureEnabled(process.env.FT_REPORTS_CATEGORISATION),
** suggestion** **bloquant**
Y'a eu un schmurtz de rebase @chrc 
@laura-bergoens a supprimé la ligne dans le commit d'avant
reportsCategorization: isFeatureEnabled(process.env.FT_REPORTS_CATEGORISATION),
```suggestion
      reportsCategorization: isFeatureEnabled(process.env.FT_REPORTS_CATEGORISATION),
```

2021-02-25 10:49 UTC, octo-topi commented
A part ce retour https://github.com/1024pix/pix/pull/2616#discussion_r582730265, c'est tout bon pour moi

2021-02-25 11:04 UTC, chrc commented on api/lib/config.js
> +      reportsCategorization: isFeatureEnabled(process.env.FT_REPORTS_CATEGORISATION),
Done

2021-02-25 11:45 UTC, octo-topi approved these changes

2021-02-26 13:45 UTC, octo-thlo commented on mon-pix/translations/en.json
> +                        "label": "Confirm your email address"
**Suggestion non-bloquante** : J'ai eu des retours en privé sur Slack de personnes qui craignent l'ambiguïté entre ancienne et nouvelle adresse. Pour éviter ce genre de risques je propose :

```suggestion
                        "label": "Confirm your new email address"
```

Modif idéalement à appliquer à la VF aussi

2021-02-26 13:55 UTC, octo-thlo requested changes
Dans la description de PIX-1745, je lis "sur la ligne ‘Adresse email’, seulement SI le champ est rempli, ALORS afficher bouton ‘Modifier’"

J'ai testé la page avec un compte qui ne possédait qu'un identifiant et j'ai vu ça 
![Capture d’écran 2021-02-26 à 14 52 00](https://user-images.githubusercontent.com/46494361/109308572-7d485880-7842-11eb-848b-f71cfd3be51f.png)

À mon avis il faudrait empêcher la modification avant le merge de ce ticket

2021-02-26 14:43 UTC, octo-topi commented
> Dans la description de PIX-1745, je lis "sur la ligne ‘Adresse email’, seulement SI le champ est rempli, ALORS afficher bouton ‘Modifier’"
> 
> J'ai testé la page avec un compte qui ne possédait qu'un identifiant et j'ai vu ça

OMG. @chrc c'est une PR voiture-balai j'ai l'impression

2021-03-01 13:24 UTC, chrc commented
> Dans la description de PIX-1745, je lis "sur la ligne ‘Adresse email’, seulement SI le champ est rempli, ALORS afficher bouton ‘Modifier’"
> 
> J'ai testé la page avec un compte qui ne possédait qu'un identifiant et j'ai vu ça
> ![Capture d’écran 2021-02-26 à 14 52 00](https://user-images.githubusercontent.com/46494361/109308572-7d485880-7842-11eb-848b-f71cfd3be51f.png)
> 
> À mon avis il faudrait empêcher la modification avant le merge de ce ticket.
> 
> Je précise que l'utilisateur ne peut pas aller au bout de la modification parce que l'API vérifie cette règle. Il voit donc une erreur qui ne correspond pas à la réalité
> ![Capture d’écran 2021-02-26 à 14 59 37](https://user-images.githubusercontent.com/46494361/109309211-445cb380-7843-11eb-845e-a210330aab4c.png)

**Done**

2021-03-01 16:04 UTC, octo-thlo approved these changes

2021-03-01 18:23 UTC, merged