[FEATURE] Afficher les paliers liés à un profil cible (PIX-2224).
1024pix/pix pull request #2628
Opened 2021-02-26 14:16 UTC by celineung

## :unicorn: Problème
Sur Pix-Admin, il est possible de voir les résultats thématiques associés à un profil cible, mais pas les paliers. 

## :robot: Solution
Afficher les paliers liés à un profil cible.

## :rainbow: Remarques
- un nouvel appel en DB est fait pour récupérer les paliers

## :100: Pour tester
Dans pix-admin,
- dans le menu à gauche clique sur "profils cibles"
- sélectionner un profil-cible dans la liste
- cliquer sur l'onglet "Clés de lecture" du profile-cible sélectionné

2021-02-26 14:20 UTC, pix-service commented
I'm deploying this PR to these urls:

- App: https://app-pr2628.review.pix.fr
- Orga: https://orga-pr2628.review.pix.fr
- Certif: https://certif-pr2628.review.pix.fr
- Admin: https://admin-pr2628.review.pix.fr
- API: https://api-pr2628.review.pix.fr/api/

 Please check it out!

2021-03-01 09:56 UTC, francois2metz commented on admin/app/styles/components/target-profiles/stage-list.scss
> +    width: 100px;
Un peu court peut être ? Même si j'ai conscience que le plus important c'est le chiffre ;)
![Screenshot_2021-03-01 Pix Admin](https://user-images.githubusercontent.com/86659/109481206-c2f06580-7a7c-11eb-8dc4-899680e00ab7.png)

2021-03-01 09:58 UTC, francois2metz commented on admin/tests/integration/components/target-profiles/stage-list_test.js
> +      imageUrl: 'http://image-url.fr',
Il me semble que l'on va tenter de faire une requête sur `http://image-url.fr`. Une solution pour éviter les requêtes inutiles est d'utiliser une data url, par example 'data:,' pour sa version la plus courte.

2021-03-01 10:05 UTC, francois2metz commented on api/tests/integration/infrastructure/repositories/target-profile-with-learning-content-repository_test.js
> +    afterEach(async () => {
Ma compréhension actuelle du databasebuilder est qu'il fait tout cela pour nous tout seul, sauf si dans les tests on appel quelque chose qui crée des entrées en base de données. Avez vous eu des problèmes pour rajouter cela ?

2021-03-01 10:13 UTC, francois2metz reviewed
J'ai fait quelques remarques mineur. 
Il y a peut être un sujet un peu plus pénible a renommer la route `badges` coté admin en ??? car désormais on affiche les badges et les stages.

2021-03-01 14:57 UTC, MelanieMEB approved these changes
Globalement OK pour la PR, avec quelques petits commentaires d'améliorations.

2021-03-01 14:57 UTC, MelanieMEB commented on api/tests/integration/infrastructure/repositories/target-profile-with-learning-content-repository_test.js
> +      const targetProfileDB = databaseBuilder.factory.buildTargetProfile({ outdated: false, isPublic: true, imageUrl: 'http://image-url.fr' });
Même commentaire que celui de françois sur l'URL

2021-03-01 14:57 UTC, MelanieMEB commented on api/tests/integration/infrastructure/repositories/target-profile-with-learning-content-repository_test.js
> +    afterEach(async () => {
Normalement, le `databasebuilder.clean()` supprime tout ce qui a été ajouté via le databasebuilder.
S'il y a eu des ajouts via les appels api, alors il faudra les supprimer à la main comme ici.
Effectivement, je pense qu'un `databasebuilder.clean()` suffit possiblement ici.

2021-03-01 15:07 UTC, sbedeau requested changes

2021-03-01 15:07 UTC, ghost commented on admin/app/models/stage.js
> +  @attr() message;
**nitpick(non-blocking):** Il est recommandé d'être explicite sur le type des attribus renseignés 

```suggestion
  @attr('number') threshold;
  @attr('string') title;
  @attr('string') message;
```

2021-03-01 15:07 UTC, ghost commented on admin/app/components/target-profiles/stage-list.hbs
> +  {{#if (gt @model.list.length 0)}}
**nitpick(non-blocking):** Expliciter la condition dans une méthode
```suggestion
  {{#if this.hasStages}}
```

2021-03-01 15:07 UTC, ghost commented on admin/app/routes/authenticated/target-profiles/target-profile/badges.js
> +    };
**suggestion(non-blocking):** Pourquoi ne pas préserver l'intégrité de la donnée ? 
```suggestion
    return {
      badges,
      stages,
      targetProfileImageUrl: targetProfile.imageUrl
    };
```

2021-03-01 15:07 UTC, ghost commented on admin/app/styles/app.scss
> +@import 'components/target-profiles/badges';
**nitpick(blocking):** Ce composant contient les RT et les stages. Sa modélisation métier semble donc être une clef de lecture et devrait être nommé par son équivalent métier approuvé (`reading-keys` ?)

2021-03-01 15:07 UTC, ghost commented on admin/app/styles/app.scss
> +@import 'components/target-profiles/stage-list';
**nitpick(~blocking):** Cette dénomination n'est pas conforme à nos conventions. 
```suggestion
@import 'components/target-profiles/stages';
```

2021-03-01 15:07 UTC, ghost commented on admin/app/styles/components/target-profiles/badges.scss
> +    @extend .page-section__title;
**question:** A quoi sert le `extend` ?

2021-03-01 15:22 UTC, lisequesnel commented on admin/app/components/target-profiles/stage-list.hbs
> +          <th class="stages-table__name">Nom</th>
Le titre est en fait un nom ?

2021-03-01 15:43 UTC, celineung commented on admin/app/components/target-profiles/stage-list.hbs
> +          <th class="stages-table__name">Nom</th>
Bonne remarque. C'est vrai que je parlerai plutôt de "nom du palier/RT" que de "titre" 😲
Mais il faudra alors revoir toute la terminologie. Pour coller à la DB, je vais remettre "titre" pour le moment.

2021-03-01 17:41 UTC, celineung commented on admin/app/styles/components/target-profiles/badges.scss
> +    @extend .page-section__title;
Je l'ai supprimé car pas utilisé au final

2021-03-02 13:55 UTC, celineung commented
PR bloquée car en attente du wording anglais pour "clé de lecture"

2021-03-03 10:53 UTC, MelanieMEB approved these changes

2021-03-04 08:23 UTC, francois2metz commented on api/tests/integration/infrastructure/repositories/target-profile-with-learning-content-repository_test.js
> +      await databaseBuilder.clean();
Je ne pense pas qu'il soit nécessaire de le mettre manuellement. Il est appeler dans le hook global `afterEach` https://github.com/1024pix/pix/blob/0bb64ecae1f719c7ab231856e442601e1e02f6cd/api/tests/test-helper.js#L24-L29

2021-03-04 08:23 UTC, francois2metz approved these changes
LGTM :purple_heart: :yellow_heart: :green_heart: :blue_heart:

2021-03-04 09:20 UTC, alexandrecoin approved these changes

2021-03-04 09:41 UTC, sbedeau requested changes

2021-03-04 09:41 UTC, sbedeau commented on admin/app/components/target-profiles/badges.hbs
> +  {{#if (gt @model.length 0)}}
**nitpick(non-blocking):** Pour la cohérence
```suggestion
  {{#if hasBadges}}
```

2021-03-04 09:41 UTC, sbedeau commented on admin/app/components/target-profiles/stages.js
> +    return this.args.stages && this.args.stages.length > 0;
**nitpick(non-blocking):** Pour réduire le nombre d'appels à l'arborescence de l'objet
```suggestion
	const stages = this.args.stages;
    return stages && stages.length > 0;
```

2021-03-04 09:41 UTC, sbedeau commented on admin/app/components/target-profiles/stages.js
> +export default class StageList extends Component {
**nitpick(blocking):**
```suggestion
export default class Stages extends Component {
```

2021-03-04 09:41 UTC, sbedeau commented on admin/app/styles/components/target-profiles/stage-list.scss
> +.stages-table {
**nitpick(blocking):** Le nom du fichier ne correspond pas au reste. Il faut donc le renommer de `stage-list.scss` à `stages.scss`

2021-03-04 09:41 UTC, sbedeau commented on admin/app/components/target-profiles/stages.hbs
> +    <div class="table-admin stages-table">
**nitpick(~blocking):** La classe `stages-table` n'a pas de propriété et est donc inutile
```suggestion
    <div class="table-admin">
```

2021-03-04 09:41 UTC, sbedeau commented on admin/app/components/target-profiles/stages.hbs
> +          <th class="stages-table__title">Titre</th>
**suggestion (non-blocking):** Si le scss avait été plus riche et complexe, j'aurais fini par nommer ces classes comme ça 
```suggestion
          <th class="stages-table-header__id">ID</th>
          <th class="stages-table-header__image">Image</th>
          <th class="stages-table-header__threshold">Threshold</th>
          <th class="stages-table-header__title">Titre</th>
```

2021-03-04 10:34 UTC, celineung commented on admin/app/components/target-profiles/stages.hbs
> +          <th class="stages-table__title">Titre</th>
J'ai laissé les classes sans le `header` car on réutilise `stages-table__image` dans des <td> pour donner une tailler fixe à la cellule.

2021-03-04 10:56 UTC, sbedeau approved these changes
**praise:** C'est un beau morceau cette PR. Merci pour ta patience et ta rigueur dans la prise en compte de mes remarques 🙏

2021-03-04 10:56 UTC, sbedeau commented on admin/app/styles/app.scss
> +@import 'components/target-profiles/badges';
```suggestion
@import 'components/target-profiles/insight';
@import 'components/target-profiles/badges';
```

2021-03-04 11:12 UTC, merged