Pix 2276 transfer profile collect banner to dashboard
1024pix/pix pull request #2676
Opened 2021-03-08 14:31 UTC by alexandrecoin

## :unicorn: Problème
> _Décrivez ici le besoin ou l'intention couvert par cette Pull Request._

## :robot: Solution
> _Ajoutez à cet endroit, si nécessaire, des détails concernant la solution technique retenue et mise en oeuvre, des difficultés ou problèmes rencontrés._

## :rainbow: Remarques
> _Des infos supplémentaires, trucs et astuces ?_

## :100: Pour tester
> _Les instructions pour reproduire le problème, les profils de test, le parcours spécifique à utiliser, etc._

2021-03-11 16:18 UTC, pix-service commented
I'm deploying this PR to these urls:

- App: https://app-pr2676.review.pix.fr
- Orga: https://orga-pr2676.review.pix.fr
- Certif: https://certif-pr2676.review.pix.fr
- Admin: https://admin-pr2676.review.pix.fr
- API: https://api-pr2676.review.pix.fr/api/

 Please check it out!

2021-03-12 11:28 UTC, celineung approved these changes

2021-03-12 11:28 UTC, celineung commented on mon-pix/app/components/dashboard/content.js
> +      campaignParticipation.isShared === false && campaignParticipation.campaign.get('isProfilesCollection'));
**nitpick (non-blocking)**
```suggestion
      !campaignParticipation.isShared && campaignParticipation.campaign.get('isProfilesCollection'));
```

2021-03-12 11:28 UTC, celineung commented on mon-pix/translations/en.json
> +                "resume": "",
Demander la traduction ici ^^

2021-03-12 13:08 UTC, alexandrecoin commented on mon-pix/translations/en.json
> +                "resume": "",
Un oubli. 🤦‍♂️
On avait déjà : `Don’t forget to submit your results!` dans la version précédente, je le remets.

2021-03-15 10:26 UTC, sbedeau requested changes

2021-03-15 10:26 UTC, sbedeau commented on mon-pix/app/styles/components/_new-information.scss
> +    margin-top: 20px;
**question:** Pourquoi utiliser un `margin: auto` suivi d'un `margin-top` ?

2021-03-15 10:26 UTC, sbedeau commented on mon-pix/public/images/profile_collect_TDB_pix.svg
> +<?xml version="1.0" encoding="UTF-8"?>
**nitpick(non-blocking):** Optimiser la taille du fichier avec [svgo](https://github.com/svg/svgo)

2021-03-15 10:26 UTC, sbedeau commented on mon-pix/tests/unit/components/dashboard/content-test.js
> +    it('should return the most recent campaign participation code among campaigns participations not finished', function() {
```suggestion
    it('should return the most recent profile collection campaign participation code among not finished ones', function() {
```

2021-03-15 10:26 UTC, sbedeau commented on mon-pix/tests/acceptance/user-dashboard-test.js
>    describe('new dashboard information', function() {
**suggestion(blocking):** Réordonner les tests autour d'un describe de test pour `{{#if this.hasNewInformationToShow}}` et ajouter éventuellement les cas de tests associés pour vérifier la table de vérité des conditions imbriquées

2021-03-15 10:26 UTC, sbedeau commented on mon-pix/app/templates/components/new-information.hbs
> +            <LinkTo @route="{{@linkTo}}" @model={{@code}} class="new-information-content-text__button button button--extra-thin button--link">{{@linkText}}</LinkTo>
**suggestion(non-blocking):** Ajouter un test qui vérifie qu'on a bien la bonne adresse en présence d'un code

2021-03-15 11:57 UTC, alexandrecoin commented on mon-pix/app/styles/components/_new-information.scss
> +    margin-top: 20px;
Bien vu. Le margin auto n'est pas utile.

2021-03-15 13:57 UTC, MelanieMEB commented on mon-pix/translations/fr.json
> +                "resume": "<h2>N'oubliez pas de finaliser votre envoi de profil !</h2>",
Pour les trads, il y a toute la partie `resume-campaign-banner` qui serait à supprimer normalement.
On peut reprendre ce texte pour l'anglais.

2021-03-15 16:21 UTC, alexandrecoin commented on mon-pix/translations/fr.json
> +                "resume": "<h2>N'oubliez pas de finaliser votre envoi de profil !</h2>",
Il y a encore des traductions de `resume-campaign-banner` utilisées dans `skill-review.hbs` et je trouverais ça bizarre de devoir utiliser celles du tableau de bord. 🤔

2021-03-15 17:09 UTC, sbedeau approved these changes

2021-03-15 17:09 UTC, sbedeau commented on mon-pix/tests/acceptance/user-dashboard-test.js
> +            code: 'campaignCode',
**suggestion(non-blocking):** Utiliser quelque chose de plus proche de la réalité comme `SNAP1234`

2021-03-15 17:09 UTC, sbedeau commented on mon-pix/tests/acceptance/user-dashboard-test.js
> +    describe('when user has new information to see', function() {
**suggestion(non-blocking):** Ajouter un test qui vérifie qu'on n'affiche rien le cas échéant

2021-03-16 09:33 UTC, MelanieMEB commented on mon-pix/translations/fr.json
> +                "resume": "<h2>N'oubliez pas de finaliser votre envoi de profil !</h2>",
Ah zut, effectivement. Bon bah on laisse pour le moment !

2021-03-16 10:51 UTC, merged