[TECH] Mise a jour de Node 14.15.0 vers 14.16.0.
1024pix/pix pull request #2677
Opened 2021-03-08 14:32 UTC by Thomasevano

## :unicorn: Problème
Notre version de Node est 14.15.0 et la version LTS actuelle est 14.16.0.

## :robot: Solution
Mettre à jour vers la version 14.16.0.

## :rainbow: Remarques
R.A.S

## :100: Pour tester
Vérifier que les tests passent en local et sur la CI et que les versions soient correctes: 
```
✔ node was validated with 14.16.0.
✔ npm was validated with 6.14.11.

 Environment looks good!
```

2021-03-08 15:50 UTC, xav-car approved these changes

2021-03-08 15:56 UTC, jonasgrilleres approved these changes

2021-03-08 16:00 UTC, alexandrecoin approved these changes

2021-03-08 16:13 UTC, VincentHardouin commented
Pourquoi on a pas le message avec les RA ?

2021-03-08 16:27 UTC, jbuget commented
> Pourquoi on n'a pas le commentaire avec les liens des RA ?

Problème de [Scalingo et de la zone OSC-FR1](https://scalingostatus.com/details/c887f594ad5e0) au moment du commit j'imagine ?

2021-03-08 17:03 UTC, octo-topi commented
Pi, voilà le changelog de la
-  [14.15](https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V14.md#14.15.0)
-  [14.16](https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V14.md#14.16.0)

2021-03-08 17:03 UTC, octo-topi approved these changes

2021-03-08 17:07 UTC, octo-topi requested changes
Je pense qu'il faut au moins vérifier que ça démarre en "normal", pas qu'en test 
Comment créer la RA mainternant :thinking: ? 
Je tente un "manual RA" sur API et front
https://my.osc-fr1.scalingo.com/apps/pix-api-review/code

2021-03-08 17:11 UTC, pix-service commented
I'm deploying this PR to these urls:

- App: https://app-pr2677.review.pix.fr
- Orga: https://orga-pr2677.review.pix.fr
- Certif: https://certif-pr2677.review.pix.fr
- Admin: https://admin-pr2677.review.pix.fr
- API: https://api-pr2677.review.pix.fr/api/

 Please check it out!

2021-03-08 17:17 UTC, VincentHardouin approved these changes

2021-03-09 07:54 UTC, octo-topi approved these changes
Parcours de Pix App et Pix Orga OK

2021-03-09 09:45 UTC, merged