[FEATURE][i18n] Traduction des en-têtes csv et du contenu pour les résultats d'une campagne
1024pix/pix pull request #2685
Opened 2021-03-10 08:33 UTC by xav-car

## :unicorn: Problème
Pix orga s'internationalise petit à petit

## :robot: Solution
Ajouter la detection de langue côté API sur l'export de résultat de campagnes afin d'avoir un export traduit dans la langue souhaité

## :rainbow: Remarques
WIP

## :100: Pour tester
WIP

2021-03-10 08:38 UTC, pix-service commented
I'm deploying this PR to these urls:

- App: https://app-pr2685.review.pix.fr
- Orga: https://orga-pr2685.review.pix.fr
- Certif: https://certif-pr2685.review.pix.fr
- Admin: https://admin-pr2685.review.pix.fr
- API: https://api-pr2685.review.pix.fr/api/

 Please check it out!

2021-03-12 09:38 UTC, bpetetot requested changes
J'ai mis un request change car je  pense qu'il faut essayer de créer un helper de test i18n pour éviter de redéfinir les traductions dans tous les tests (voir mon commentaire)

2021-03-12 09:38 UTC, bpetetot commented on api/translations/en.json
> +        "items-completed-in": "Items of the target profile successfully completed in the skill {{name}}"
Mettre dans l'ordre alphabétique

2021-03-12 09:38 UTC, bpetetot commented on api/translations/fr.json
> +        "items-completed-in": "Acquis maitrisés dans la compétence {{name}}"
Mettre dans l'ordre alphabétique

2021-03-12 09:38 UTC, bpetetot commented on api/tests/integration/domain/usecases/start-writing-campaign-assessment-results-to-stream_test.js
> +
**suggestion:**
Est-ce qu'il n'y aurait pas un moyen d'éviter de redéfinir les traductions dans tous les tests ?
En regardant la librarie [`hapi-i18n`](https://github.com/funktionswerk/hapi-i18n), je vois qu'elle se base sur la lib [`i18n`](https://github.com/mashpie/i18n-node)

Je pense qu'on pourrait créer un helper de test:
```js
# api/tests/helpers/i18n.js
const path = require('path');
const { I18n } = require('i18n');

function getI18n() {
  const i18n = new I18n({
    locales: ['fr'],
    directory: path.join(__dirname, '../../translations'),
  });
  i18n.setLocale('fr');
  return i18n;
}

module.exports = { getI18n }
```

Et dans le test:
```js
const { getI18n } = require('../../../helpers/i18n.js')

describe('...', () => {
  const i18n = getI18n();

  it('...', async () => {
     await callYourUseCase(param1, param2, i18n);
  })
})
```

2021-03-12 14:57 UTC, bpetetot approved these changes

2021-03-12 15:04 UTC, bpetetot commented
Fonctionnellement OK

2021-03-15 10:27 UTC, lisequesnel commented on api/translations/en.json
> +        "items-completed-in": "Number of items of the target profile in the competence area {{name}}",
"items-completed-in" -> "total-items" ?

2021-03-15 10:27 UTC, lisequesnel commented on api/translations/en.json
> +        "mastery-percentage-acquired": "% of items successfully completed in the competence area {{name}}",
"mastery-percentage-acquired" -> "mastery-percentage" tout court ?

2021-03-15 10:28 UTC, lisequesnel commented on api/translations/en.json
> +        "number-items-target-profile-in": "Items of the target profile successfully completed in the competence area {{name}}"
"number-items-target-profile-in" -> "items-successfully-completed" ?

2021-03-15 10:28 UTC, lisequesnel commented on api/translations/en.json
> +      "mastery-percentage-target-profile":"% of items successfully completed in the target profile",
"mastery-percentage-target-profile" -> "mastery-percentage" tout court ?

2021-03-15 10:34 UTC, lisequesnel commented on api/translations/en.json
> +        "items-completed-in": "Items of the target profile successfully completed in the skill {{name}}",
"items-successfully-completed" ?

2021-03-15 10:34 UTC, lisequesnel commented on api/translations/en.json
> +        "mastery-percentage-acquired": "% of items successfully completed in the skill {{name}}",
"mastery-percentage" tout court ?

2021-03-15 10:35 UTC, lisequesnel commented on api/translations/en.json
> +        "number-items-target-profile-in": "Number of items of the target profile in the skill {{name}}"
"total-items" ?

2021-03-15 14:03 UTC, lisequesnel commented on api/lib/domain/usecases/start-writing-campaign-assessment-results-to-stream.js
> +      translate('campaign-export.assessment.skill.total-items', { name: competence.name }),
j'ai l'impression que ces 2 colonnes sont inversées. Cela devrait être en 1 : nb total et en 2 : nb maitrisés

2021-03-15 14:04 UTC, lisequesnel commented on api/lib/domain/usecases/start-writing-campaign-assessment-results-to-stream.js
> +      translate('campaign-export.assessment.competence-area.total-items', { name: area.title }),
idem ici, j'ai l'impression que c'est inversé

2021-03-15 14:05 UTC, lisequesnel commented on api/translations/en.json
> +        "total-items": "Number of items of the target profile in the competence area {{name}}"
ordre alphabétique :)

2021-03-15 14:05 UTC, lisequesnel commented on api/translations/en.json
> +        "total-items": "Items of the target profile successfully completed in the skill {{name}}"
ordre alphabétique :)

2021-03-15 14:05 UTC, lisequesnel commented on api/translations/en.json
> +        "total-items": "Items of the target profile successfully completed in the skill {{name}}"
j'ai l'impression que les clés-valeurs sont inversées

2021-03-15 14:06 UTC, lisequesnel commented on api/translations/fr.json
> +        "total-items": "Acquis maitrisés dans la compétence {{name}}"
clés-valeurs inversées

2021-03-15 14:06 UTC, lisequesnel commented on api/translations/fr.json
> +        "total-items": "Acquis maitrisés du domaine {{name}}"
clés-valeurs inversées

2021-03-15 15:28 UTC, lisequesnel commented on api/translations/en.json
> +        "total-items": "Items of the target profile successfully completed in the competence area {{name}}"
ya toujours une inversion ici ^^

2021-03-15 15:48 UTC, lisequesnel approved these changes

2021-03-15 15:56 UTC, merged