[BUGFIX] Ne pas afficher les campagnes pour Novice terminé dans les TDB et pages parcours (PIX-2320).
1024pix/pix pull request #2692
Opened 2021-03-10 16:41 UTC by MelanieMEB

## :unicorn: Problème
La campagne ABCDiag est une campagne `isForAbsoluteNovice`. Cette campagne est aussi une campagne à accès simplifié, "sans compte". Mais cela n'empêche pas des personnes avec leur compte de passer cette campagne. 
La campagne ne pouvant être partagé, si l'utilisateur connecté la passe avec son compte, il la verra comme "A partager" sur son tableau de bord et sur la page Mes parcours. Malheureusement, vu qu'il ne peut pas la partager, elle restera là.

## :robot: Solution
Filtrer les `campaign-participation-overviews` pour ne pas remonter les participations aux campagnes qui sont terminés sur ce type de campagne.

## :rainbow: Remarques
Ce cas est normalement à la marge de l'utilisation normal de ces campagnes

## :100: Pour tester
Sur la RA : 
- AZERTY123 devient `isForAbsoluteNovice`
- userpix1 a commencé la campagne AZERTY456, visible, et a terminé la campagne `isForAbsoluteNovice` AZERTY123 (visible en remettant le code, mais pas sur les pages)

2021-03-10 16:45 UTC, pix-service commented
I'm deploying this PR to these urls:

- App: https://app-pr2692.review.pix.fr
- Orga: https://orga-pr2692.review.pix.fr
- Certif: https://certif-pr2692.review.pix.fr
- Admin: https://admin-pr2692.review.pix.fr
- API: https://api-pr2692.review.pix.fr/api/

 Please check it out!

2021-03-11 08:17 UTC, francois2metz approved these changes
LGTM :purple_heart: :yellow_heart: :green_heart: :blue_heart:

2021-03-11 08:32 UTC, celineung approved these changes

2021-03-11 10:13 UTC, lisequesnel commented
Ce serait pas mieux d'avoir une campagne dans les seeds qui soit dédiée à `isAbsoluteNovice` ?
Je pensais à la créer dans l'orga `Médiation Numérique`, avec un code genre "NOVICE123"

2021-03-11 10:17 UTC, lisequesnel requested changes, later dismissed
je pense que c'est quelque chose d'impactant, à vérifier avec Estelle

2021-03-11 10:17 UTC, lisequesnel commented on api/lib/infrastructure/repositories/campaign-participation-overview-repository.js
> +        });
On veut pas du tout les remonter, ou alors, on veut les remonter sous le statut "terminé" ? Je trouverai ça plus pertinent de les remonter sous "terminé", parce que sinon, l'utilisateur peut pas revoir du tout les résultats qu'il a eu, et c'est ce qu'on veut plus avec la page "mes parcours". ping @estellelandry qu'en penses-tu ?

2021-03-11 10:39 UTC, lisequesnel commented on api/lib/infrastructure/repositories/campaign-participation-overview-repository.js
> +        });
c'est confirmé avec @estellelandry, on veut remonter la carte, avec un statut "terminé"

2021-03-11 16:22 UTC, merged