[FEATURE] Afficher la nouvelle solution d'une épreuve si présente dans Airtable (PIX-2265).
1024pix/pix pull request #2703
Opened 2021-03-12 16:43 UTC by celineung

## :unicorn: Problème
On souhaite afficher une réponse personnalisée dans la solution d'une épreuve.

Exemple dans le cas d'une épreuve où:
- les réponse possibles sont 1, 2 ou 3
- on s'attend à avoir un seul chiffre dans l'input de réponse
- on avait dans Airtable le champs "Bonnes réponses" qui contient:
```
1 ou 2 ou 3
1
2
3
```
- dans la correction, on affiche "1 ou 2 ou 3"

Cela pose problème car on mélange deux type d'information dans le champs "Bonnes réponses": les réponses qui sont considérées correctes et celle que l'on veut afficher sur l'écran de solution.

## :robot: Solution
- créer une nouvelle colonne "Bonnes réponses à afficher" dans la table Epreuves de Airtable
- récupérer ce nouveau champs dans LMCS https://github.com/1024pix/pix-editor/pull/121
- afficher ce nouveau champs "Bonnes réponses à afficher" si rempli ou sinon afficher l'ancien champs "Bonnes réponses"

## :rainbow: Remarques
> _Des infos supplémentaires, trucs et astuces ?_

## :100: Pour tester
> _Les instructions pour reproduire le problème, les profils de test, le parcours spécifique à utiliser, etc._

2021-03-12 16:49 UTC, pix-service commented
I'm deploying this PR to these urls:

- App: https://app-pr2703.review.pix.fr
- Orga: https://orga-pr2703.review.pix.fr
- Certif: https://certif-pr2703.review.pix.fr
- Admin: https://admin-pr2703.review.pix.fr
- API: https://api-pr2703.review.pix.fr/api/

 Please check it out!

2021-03-15 08:40 UTC, alexandrecoin reviewed
Tech: OK
Func : En attente du ré-up de la RA. 😊

2021-03-15 08:40 UTC, alexandrecoin commented on api/tests/unit/infrastructure/repositories/correction-repository_test.js
> +        const result = await promise;
```suggestion
        const result = await correctionRepository.getByChallengeId({ challengeId: recordId, userId, locale });

        // then
```

**Question** : Y a t-il une raison de ne pas resolve la promesse immédiatement ?

2021-03-15 08:40 UTC, alexandrecoin commented on api/tests/unit/infrastructure/repositories/correction-repository_test.js
> +
```suggestion
        const result = await correctionRepository.getByChallengeId({ challengeId: recordId, userId, locale });
        
        // then
        return result.hints.forEach((hint) => expect(hint).to.be.an.instanceof(Hint));
```
**Suggestion** : Si pas de raison particulière d'attendre avant de resolve la `promise`

2021-03-15 10:05 UTC, sbedeau reviewed
Tech ok
Func en attente de RA

2021-03-15 14:28 UTC, celineung commented
PR bloquée: on souhaite pouvoir afficher une solution dans le cas des embed auto.
Dans ce cas, déplacer la logique du choix de la solution à afficher faite côté api vers le front.

2021-03-16 16:08 UTC, MelanieMEB requested changes
Globalement OK ! 
Mais je bloque pour qu'on vérifie le cas des qcu/qcm

2021-03-16 16:08 UTC, MelanieMEB commented on mon-pix/tests/unit/components/comparison-window-test.js
> +    it('should return solutionToDisplay when challenge has autoReply=false and correction has a solutionToDisplay', function() {
Il manque le test `should return solutionToDisplay when challenge has autoReply=true and correction has a solutionToDisplay`, et on aura tous les cas :)

2021-03-16 16:08 UTC, MelanieMEB commented on mon-pix/app/components/comparison-window.js
> +    return this.args.answer.correction.get('solutionToDisplay') || solution;
**question** : est-ce qu'il ne faudrait pas limiter aussi d'après le type de challenge ? 
Je me pose la question de l'impact si on met une `solutionToDisplay` dans un QCU ou dans un QROC, ça risque de casser l'affichage qui se base sur ça ensuite, non ?

2021-03-16 16:59 UTC, celineung commented on mon-pix/tests/unit/components/comparison-window-test.js
> +    it('should return solutionToDisplay when challenge has autoReply=false and correction has a solutionToDisplay', function() {
J'ai modifié le nom du test car c'est indépendant du `autoReply`: dès que le `solutionToDisplay` existe, il est affiché.

2021-03-16 23:25 UTC, celineung commented on mon-pix/app/components/comparison-window.js
> +    return this.args.answer.correction.get('solutionToDisplay') || solution;
Corrigé pour afficher toujours `solution` dans le cas de QCU et QCM.
Dans les cas de QROC/QROCM:
- si `solutionToDisplay` est présent, il est affiché
- sinon: 
  - si c'est un embedAuto, ne rien afficher
  - sinon afficher `solution`

2021-03-19 10:23 UTC, MelanieMEB commented on mon-pix/app/styles/components/_qcm-solution-panel.scss
> +}
A supprimer

2021-03-19 10:23 UTC, MelanieMEB commented on mon-pix/app/templates/components/qroc-solution-panel.hbs
> +{{/if}}
Oubli retour à la ligne

2021-03-19 10:23 UTC, MelanieMEB commented on mon-pix/app/components/qroc-solution-panel.js
>    get solutionToDisplay() {
Possibilité de renommage : 
`understandableSolution`

2021-03-19 10:23 UTC, MelanieMEB commented on mon-pix/app/templates/components/qroc-solution-panel.hbs
> +    {{#unless this.isResultOk}}
{{#if this.isNotCorrectlyAnswered}} à voir à modifier partout

2021-03-19 10:23 UTC, MelanieMEB commented on mon-pix/app/templates/components/qroc-solution-panel.hbs
> +{{#if (or @solution this.solutionToDisplay)}}
Sortir dans une méthode : `hasCorrection`

2021-03-19 10:23 UTC, MelanieMEB commented on mon-pix/app/templates/components/qroc-solution-panel.hbs
>    <div class="rounded-panel__row ">
CSS à modifier ?

2021-03-19 10:23 UTC, MelanieMEB commented on mon-pix/app/templates/components/qroc-solution-panel.hbs
>    <div class="rounded-panel__row ">
Inverser le roudned-panel et le correction qrocbox

2021-03-19 10:23 UTC, MelanieMEB commented on mon-pix/app/templates/components/qroc-solution-panel.hbs
> +          <input class="correction-qroc-box-answer {{this.inputClass}}"
Passer par les TextArea et Input ember

2021-03-19 10:23 UTC, MelanieMEB commented on mon-pix/tests/integration/components/qroc-solution-panel-test.js
> +    it('should not show the input answer', async function() {
doublon avec ci-dessous

2021-03-19 10:23 UTC, MelanieMEB commented on mon-pix/app/components/qrocm-dep-solution-panel.js
>    get expectedAnswers() {
renommer en understandableSolution

2021-03-19 10:23 UTC, MelanieMEB commented on mon-pix/app/templates/components/qrocm-dep-solution-panel.hbs
> -      <div class="correction-qrocm__solution">
Supprimer le code CSS

2021-03-19 10:23 UTC, MelanieMEB commented on mon-pix/app/templates/components/qrocm-ind-solution-panel.hbs
> +  {{#unless this.isResultOk}}
Renommer comme vu précédemment

2021-03-19 10:23 UTC, MelanieMEB commented on mon-pix/app/templates/components/qrocm-ind-solution-panel.hbs
> +    {{#if @solutionToDisplay}}
Pas de test

2021-03-19 10:23 UTC, MelanieMEB commented on mon-pix/app/components/comparison-window.js
> +  {
Retour à la ligne

2021-03-22 11:19 UTC, celineung reviewed
✅ testé fonctionnellement sur les différentes types d'épreuves

2021-03-22 13:29 UTC, sbedeau approved these changes

2021-03-22 13:29 UTC, MelanieMEB approved these changes

2021-03-22 13:30 UTC, alexandrecoin commented
J'ai ça lors de l'affichage des réponses, un souci de mon côté ? (Testé sur Chrome et Firefox, même résultat)
<img width="987" alt="Capture d’écran 2021-03-22 à 14 28 48" src="https://user-images.githubusercontent.com/36371437/111997190-135a6080-8b1b-11eb-9b5f-99ba4b170cbf.png">

2021-03-22 13:46 UTC, alexandrecoin approved these changes

2021-03-22 14:53 UTC, merged