[FEATURE] Traduire en anglais la page "Mon équipe / Invitations" dans Pix Orga (PIX-2225).
1024pix/pix pull request #2738
Opened 2021-03-19 09:24 UTC by AndreiaPena

## :unicorn: Problème
Dans Pix Orga, les textes de la page Mon Equipe/Invitations sont en français, et implémentés "en dur" dans le code.
On veut ajouter la version anglaise.

## :robot: Solution
Externaliser dans des fichiers dédiés la version française et anglaise des textes de cette page

## :rainbow: Remarques
> _Des infos supplémentaires, trucs et astuces ?_

## :100: Pour tester
Vérifier la bonne traduction dans la page mon Equipe, onglet Invitations.

2021-03-19 09:29 UTC, pix-service commented
I'm deploying this PR to these urls:

- App: https://app-pr2738.review.pix.fr
- Orga: https://orga-pr2738.review.pix.fr
- Certif: https://certif-pr2738.review.pix.fr
- Admin: https://admin-pr2738.review.pix.fr
- API: https://api-pr2738.review.pix.fr/api/

 Please check it out!

2021-03-19 12:10 UTC, chrc commented on orga/tests/integration/components/routes/authenticated/team/invitations-test.js
> +    assert.contains('Dernière invitation envoyée le 08/10/2019 - 12:50');
Suggestion : Comme fait dans le .hbs, utilisé `intl.t` et `moment`.

2021-03-19 12:11 UTC, chrc approved these changes

2021-03-19 13:48 UTC, AndreiaPena commented on orga/tests/integration/components/routes/authenticated/team/invitations-test.js
> +    assert.contains('Dernière invitation envoyée le 08/10/2019 - 12:50');
**Question** : Il y a deux écoles pour la traduction (ou non) des messages dans les tests. De ton coté je vois que tu appliques le `intl.t` bien qu'il y ai le `setupIntlRenderingTest` mis en place , mais dans d'autres tests ( dont ceux que j'ai fait pour la page Mon équipe ) on se suffit à ajouter le Intl pour les tests et on ne change pas les messages. 
Y'a t-il une bonne et mauvaise façon de faire ? 
Ou c'est uniquement dans en prévision d'un changement de message futur qui nous obligerait à modifier les tests ?

2021-03-19 15:44 UTC, chrc commented on orga/tests/integration/components/routes/authenticated/team/invitations-test.js
> +    assert.contains('Dernière invitation envoyée le 08/10/2019 - 12:50');
Dans un test, je ne peux utiliser `intl.t` que si je l'ai bien paramètré (avec un `setupIntl...`).
En utilisant la fonction en charge des traductions, et selon une locale précise, on rend le test plus déterministe.

2021-03-22 10:15 UTC, octo-thlo commented
Il me semble qu'il nous manque quelques traductions d'erreurs pour ces pages.
Je n'ai pas toute la liste en tête mais j'ai testé ce cas là par exemple

![Capture d’écran 2021-03-22 à 11 13 32](https://user-images.githubusercontent.com/46494361/111974579-d2a11e00-8aff-11eb-85c0-bf4f41e53f46.png)

2021-03-22 10:15 UTC, octo-thlo requested changes
Je propose d'attendre la traduction des erreurs avant de merger

2021-03-22 10:50 UTC, octo-thlo approved these changes

2021-03-22 15:00 UTC, yahyayouness approved these changes

2021-03-22 15:30 UTC, AndreiaPena commented on orga/tests/integration/components/routes/authenticated/team/invitations-test.js
> +    assert.contains('Dernière invitation envoyée le 08/10/2019 - 12:50');
Done

2021-03-23 10:24 UTC, merged