[FEATURE] Ajout du markdown sur le champ réponses des QROC (PIX-2291).
1024pix/pix pull request #2755
Opened 2021-03-23 13:41 UTC by alexandrecoin

## :unicorn: Problème

Les épreuves QROC proposent une liste simple de réponses, on ne peut pas y insérer de liens ou images.

## :robot: Solution (non-définitive, voir section remarques ci-après)

- Utiliser le component `MarkdownToHtml` pour afficher les propositions des QROC.
- Ajout de CSS pour supprimer des `margin` trop importantes liées au problème 

## :rainbow: Remarques

Suite à l'utilisation de ce composant `MarkdownToHtml` dans le fichier `qcu-proposals.hbs`, nous remarquons que : 

- Le champ des réponses est rendu dans le template par un `{{#each}}`, créant une séparation des différents éléments passés en paramètres en `blocks` créés par la fonction `proposalsAsBlocks` indépendants les uns des autres.

Il nous est donc impossible via ce procédé d'obtenir un bloc de `code` unique, puisque les ` ``` ` délimitant la section sont comptés comme des lignes uniques.

--> Ainsi, nous obtenons des listes comme ressemblant à la capture d'écran ci-dessous.
<img width="377" alt="Capture d’écran 2021-03-23 à 14 25 39" src="https://user-images.githubusercontent.com/36371437/112153540-a8289100-8be3-11eb-9515-b9bb22e2ae3a.png">

Via la capture d'écran ci-dessous, nous remarquons que cela engendre des problèmes d'accessibilité, de par l'utilisation de plusieurs `label` identiques, malgré la présence d'un seul input puisqu'il s'agit d'épreuves de type `QROC`.

Un autre problème que nous rencontrons est le manque d'informations quant à l'usage du markdown qui sera fait par les équipes contenu sur ce type d'épreuves, et en particulier de l'utilisation (ou non) du bloc `code`.

A partir de là, nous avons la possibilité de : 
 
- Garder l'implémentation en l'état, et ne pas.
- Garder ce qui a été fait sur cette PR (plus les possibles retours qui lui seront faits), et acquérir de la dette dont on se débarrassera lors de la refonte des épreuves (comprenant la suppression du `{{#each}}` de `qcu-proposals.hbs` mentionné auparavant.

D'autres idées ? 🙂

## :100: Pour tester

TBA

2021-03-23 13:46 UTC, pix-service commented
I'm deploying this PR to these urls:

- App: https://app-pr2755.review.pix.fr
- Orga: https://orga-pr2755.review.pix.fr
- Certif: https://certif-pr2755.review.pix.fr
- Admin: https://admin-pr2755.review.pix.fr
- API: https://api-pr2755.review.pix.fr/api/

 Please check it out!

2021-03-24 11:09 UTC, MelanieMEB requested changes

2021-03-24 11:09 UTC, MelanieMEB commented on mon-pix/app/templates/components/qroc-proposal.hbs
> +        <MarkdownToHtml @extensions="remove-paragraph-tags" @markdown={{block.text}} />
Possiblement un problème sur des épreuves comme : recapeyyYxjdRRyCv  où le retour à la ligne est un peu difficile.
Peut être rajouter `display: inline` sur la div qui se crée pour pouvoir avoir une alignement sur les qroc

2021-03-24 13:47 UTC, alexandrecoin commented on mon-pix/app/templates/components/qroc-proposal.hbs
> +        <MarkdownToHtml @extensions="remove-paragraph-tags" @markdown={{block.text}} />
En effet, c'est un comportement que l'on a noté après coup et ajouté lors de l'ajout du markdown sur les QROCm.

2021-03-24 14:06 UTC, celineung approved these changes

2021-03-26 08:30 UTC, MelanieMEB approved these changes

2021-03-26 13:24 UTC, merged