[FEATURE] Affichage de l'information certifiable sur les badges dans l'admin
1024pix/pix pull request #2822
Opened 2021-04-08 09:30 UTC by francois2metz

## :unicorn: Problème
Le nouveau champ `isCertifiable` des badges n'est pas affiché.

## :robot: Solution
On affiche le champ dans l'admin.
![Screenshot 2021-04-08 at 11-26-55 Pix Admin](https://user-images.githubusercontent.com/86659/114002955-a9052800-985d-11eb-9564-e6d751cda1a9.png)
- vert quand certifiable
- jaune quand non certifiable

## :rainbow: Remarques

## :100: Pour tester
1. Aller sur un badge
2. Voir l'information certifiable sur la page

2021-04-08 09:35 UTC, pix-service commented
I'm deploying this PR to these urls:

- App: https://app-pr2822.review.pix.fr
- Orga: https://orga-pr2822.review.pix.fr
- Certif: https://certif-pr2822.review.pix.fr
- Admin: https://admin-pr2822.review.pix.fr
- API: https://api-pr2822.review.pix.fr/api/

 Please check it out!

2021-04-08 15:18 UTC, MelanieMEB approved these changes

2021-04-09 08:22 UTC, jonasgrilleres approved these changes

2021-04-09 08:47 UTC, MelanieMEB requested changes

2021-04-09 08:47 UTC, MelanieMEB commented on admin/app/components/badges/badge.hbs
>          Key : {{@model.key}}<br>
Changer `key` en `clé` ?

2021-04-09 08:47 UTC, MelanieMEB commented on admin/app/components/badges/badge.hbs
>        <div class="page-section__details">
Voir pour ajouter de l'espacement pour que pixtag ne soit pas trop collé. Soit dans __details soit sur PixTag directement

2021-04-09 08:47 UTC, MelanieMEB commented on admin/tests/integration/components/badges/badge-test.js
> +    assert.ok(detailsContent.match(badge.altMessage), 'Certifiable');
Pourquoi le test sur altMessage ?

2021-04-09 08:47 UTC, MelanieMEB commented on admin/tests/integration/components/badges/badge-test.js
> +    assert.ok(detailsContent.match(badge.altMessage), 'Certifiable');
A voir si on test bien

2021-04-09 08:47 UTC, MelanieMEB commented on admin/app/components/badges/badge.hbs
>          Key : {{@model.key}}<br>
Idée : renommer model en badge pour une meilleure lecture du hbs

2021-04-09 11:39 UTC, MelanieMEB approved these changes

2021-04-09 12:04 UTC, alexandrecoin approved these changes

2021-04-09 12:48 UTC, sbedeau approved these changes

2021-04-12 08:52 UTC, merged