[FEATURE] Création de la page de plan de site (PIX-1958).
1024pix/pix pull request #2831
Opened 2021-04-09 13:47 UTC by alexandrecoin

## :unicorn: Problème

Les utilisateurs de Pix-App n'ont pour l'instant pas accès à une page de plan de l'application.
Ce manque entraîne des problèmes d'accessibilité ainsi qu'un référencement affaibli.

## :robot: Solution

Nous créons une nouvelle page `/plan-du-site` accessible depuis le `footer` dans Pix-App
Cette page comporte notamment des liens vers Pix-site afin de répondre aux questions concernant l'accessiblité.

## :rainbow: Remarques

## :100: Pour tester

Accéder à la page nouvellement créée depuis le footer et vérifier que les liens fonctionnent, soient accessibles au clavier, le tout sur la version `fr` et `en`.

2021-04-09 13:59 UTC, pix-service commented
I'm deploying this PR to these urls:

- App: https://app-pr2831.review.pix.fr
- Orga: https://orga-pr2831.review.pix.fr
- Certif: https://certif-pr2831.review.pix.fr
- Admin: https://admin-pr2831.review.pix.fr
- API: https://api-pr2831.review.pix.fr/api/

 Please check it out!

2021-04-09 15:15 UTC, sbedeau approved these changes

2021-04-09 15:15 UTC, ghost commented on mon-pix/app/styles/components/_sitemap.scss
> +    line-height: 66px;
**chipotage:** 
```suggestion
    line-height: 4,125rem;
```

2021-04-09 15:15 UTC, ghost commented on mon-pix/app/styles/components/_sitemap.scss
> +    margin-left: 25%;
**suggestion:** Utiliser des propriétés flex et des valeurs en px plutôt que des %. Conventionnellement et historiquement, nous avons pu remarquer que les % pouvaient amener des incohérences visuelles

2021-04-09 15:15 UTC, ghost commented on mon-pix/app/routes/sitemap.js
> +      scorecards,
**suggestion:** Retourner uniquement les informations utilisées dans le front. 

**thought:** Dans l'idéal, est-ce qu'il n'aurait pas fallu consommer une route API qui renvoie uniquement l'information nécessaire ? 🤔

2021-04-09 15:15 UTC, sbedeau commented on mon-pix/app/templates/components/sitemap.hbs
> +      <a href="https://support.pix.fr/en/support/home" target="_blank" rel="noopener noreferrer">
**question:** Pourquoi cette URL est en dur ?

2021-04-09 15:18 UTC, sbedeau commented on mon-pix/app/components/sitemap/sitemap.hbs
> +<main class="sitemap">
**thought:** Est-ce qu'on ne devrait pas renommer `sitemap/sitemap` en quelque chose du genre `sitemap/content` ?

2021-04-09 15:27 UTC, alexandrecoin commented on mon-pix/app/components/sitemap/sitemap.hbs
> +<main class="sitemap">
En train de corriger ça au moment de ton commentaire :)

2021-04-09 15:30 UTC, alexandrecoin commented on mon-pix/app/styles/components/_sitemap.scss
> +    margin-left: 25%;
J'avoue avoir hésité à partir sur les pixels. Je change ✌️

2021-04-09 15:31 UTC, alexandrecoin commented on mon-pix/app/templates/components/sitemap.hbs
> +      <a href="https://support.pix.fr/en/support/home" target="_blank" rel="noopener noreferrer">
Un oubli parmi les autres redirections. 🙇🏼‍♂️

2021-04-12 08:48 UTC, celineung commented on mon-pix/app/components/sitemap/sitemap.hbs
> +            {{t 'navigation.footer.eula'}}
**question:** que signifie eula ?

2021-04-12 08:50 UTC, alexandrecoin commented on mon-pix/app/components/sitemap/sitemap.hbs
> +            {{t 'navigation.footer.eula'}}
End-User License Agreement, c'est la traduction de CGU, qui est utilisée ailleurs dans la codebase. :)

2021-04-12 08:53 UTC, MelanieMEB requested changes
Testé fonctionnellement : 
- La version en anglais n'a pas de site map
- Sur petit mobile (environ 300 px), le texte est coupé

2021-04-12 08:53 UTC, MelanieMEB commented on mon-pix/translations/en.json
> +        "sitemap": {
Penser à remplir les textes en anglais

2021-04-12 12:08 UTC, celineung approved these changes

2021-04-13 07:38 UTC, MelanieMEB approved these changes
Manque seulement du texte en anglais :)

2021-04-15 07:34 UTC, merged