[Refacto] Corriger le changement de mot de passe à usage unique pour un élève qui tente de se réconcilier (Pix-2274).
1024pix/pix pull request #2861
Opened 2021-04-15 15:53 UTC by yahyayouness

## :unicorn: Problème
Le quick fix [2196](https://1024pix.atlassian.net/browse/PIX-2196) qui permet de corriger le changement de mot de passe à usage unique pour un élève qui tente de se réconcilier fonctionne, mais la présence de deux utilisateurs dans le store:
- Rend les tests complexes à comprendre
- Peut occasionner de nouveau bugs

![image](https://user-images.githubusercontent.com/10045497/114897481-9072b000-9e11-11eb-955f-8c96eedb398f.png)

## :robot: Solution
Création d'un nouveau model front, reset-expired-password-demand, comprenant trois champs : username,  nouveau MDP, MDP à usage unique.

Il sera appelé à la place du model user dans le UpdateExpiredPasswordRoute.

## :100: Pour tester

Scénario 1:

1. Se connecter à Pix avec le user userpix1@example.net
2. Rejoindre la campagne BADGES123
3. Remplir les champs du formulaire de réconciliation avec les informations George / De Cambridge / 22/07/2013
4. L'erreur R32 s'affiche et nous invite à nous connecter au compte, déjà réconcilié, `george.decambridge2207`
5. Cliquer sur Continuer avec mon compte Pix
6. Rejoindre Pix Orga avec le compte sco.admin@example.net
7. Aller sur l'organisation Collège The Night Watch (1237457A)
8. Réinitialiser le mot de passe du compte de George De Cambridge
9. Revenir sur Pix App et, dans le formulaire de connexion de la double mire, se connecte avec le compte george.decambridge2207 et le mot de passe à usage unique
10. On arrive sur la page `/mise-a-jour-mot-de-passe-expire`
11. Saisir un mot de passe valide.
12. Vérifier que le mot de passe s'est bien mis à jour et que dans le store existe un seul user qui correspond à george.decambridge2207.

Scénario 2: Sans passer par une campagne et en étant déconnecté. 

2.1 Depuis Pix Orga: Réinitialiser le mot de passe d'un élève avec un compte email .
2.2 Depuis Pix Orga: Réinitialiser le mot de passe d'un élève avec un compte GAR
3. Se connecter dans Pix App et vérifier que les mise à jour de mots de passe se passe bien pour l'utilisateur concerné.

2021-04-15 15:57 UTC, pix-service commented
I'm deploying this PR to these urls:

- App: https://app-pr2861.review.pix.fr
- Orga: https://orga-pr2861.review.pix.fr
- Certif: https://certif-pr2861.review.pix.fr
- Admin: https://admin-pr2861.review.pix.fr
- API: https://api-pr2861.review.pix.fr/api/

 Please check it out!

2021-04-16 09:21 UTC, MathieuGilet commented on mon-pix/app/routes/update-expired-password.js
> +    const resetExpiredPasswordDemand = resetExpiredPasswordDemands.objectAt(0);
```suggestion
    const resetExpiredPasswordDemand = resetExpiredPasswordDemands.firstObject;
```

2021-04-16 09:26 UTC, MathieuGilet approved these changes

2021-04-16 09:43 UTC, AndreiaPena commented
**Question** : Pourquoi avoir choisi de ne mettre que le username dans le model `reset-expired-password-demand` ?

Les élèves ont également des adresse e-mail pour se connecter et on se retrouve avec cette adresse dans le champ `username `

<img width="1312" alt="Capture d’écran 2021-04-16 à 11 38 51" src="https://user-images.githubusercontent.com/58915422/115006219-eb0b1b00-9ea8-11eb-8757-d1f15d9968c4.png">

2021-04-16 12:05 UTC, yahyayouness commented on mon-pix/app/routes/update-expired-password.js
> +    const resetExpiredPasswordDemand = resetExpiredPasswordDemands.objectAt(0);
Done thanks. PeekAll renvoie un array sous forme d'objet ember. On peut pas accéder avec obj[i] mais plutôt avec firstObject , lastObject ou objectAt

2021-04-16 12:14 UTC, yahyayouness commented
> **Question** : Pourquoi avoir choisi de ne mettre que le username dans le model `reset-expired-password-demand` ?
> 
> Les élèves ont également des adresse e-mail pour se connecter et on se retrouve avec cette adresse dans le champ `username `
> 
> <img alt="Capture d’écran 2021-04-16 à 11 38 51" width="1312" src="https://user-images.githubusercontent.com/58915422/115006219-eb0b1b00-9ea8-11eb-8757-d1f15d9968c4.png">
> 
> En grooming il a été convenu d'ajouter aussi le champ email, d'où ma question 🙂
> 
> <img alt="Capture d’écran 2021-04-16 à 11 40 02" width="550" src="https://user-images.githubusercontent.com/58915422/115006412-21e13100-9ea9-11eb-8c7a-164ef793a774.png">

La raison est que l'implémentation front et l'api existante qui permet de mettre à jour le mot de passe n'utilise que 3 champs:

            data: {
              attributes: {
                username: Joi.string().required(),
                expiredPassword: Joi.string().required(),
                newPassword: Joi.string().pattern(XRegExp(passwordValidationPattern)).required(),
              },
              type: Joi.string(),
            }

Et dans le repository, on cherche avec username or email    
const foundUser = await userRepository.getByUsernameOrEmailWithRolesAndPassword(username);

Je peux faire un Scout Rule de bout en bout, pour renommer username en login. le field login pourrait contenir à la fois un username et email ?

2021-04-16 13:24 UTC, AndreiaPena commented on mon-pix/app/models/reset-expired-password-demand.js
> +
**chipotage** : espace en trop ligne 7

2021-04-16 13:24 UTC, AndreiaPena commented on mon-pix/tests/unit/adapters/reset-expired-password-demand-test.js
> +      // then
**chipotage**: saut de ligne avant les `// when` et `// then`

2021-04-16 13:24 UTC, AndreiaPena commented on mon-pix/tests/unit/routes/login-test.js
> +        { username, oneTimePassword },
**chipotage**: tout mettre à la ligne ou bien 
```suggestion
      sinon.assert.calledWith(
        createRecordStub,
        'reset-expired-password-demand',
        { username, oneTimePassword },
      );
```

2021-04-16 13:24 UTC, AndreiaPena commented on mon-pix/mirage/factories/reset-expired-password-demand.js
> +    return faker.random.words();
```suggestion
    return faker.internet.userName(),
```

2021-04-16 13:24 UTC, AndreiaPena commented on mon-pix/tests/unit/routes/update-expired-password-test.js
> +  it('should retrieve a reset expired password demand', async function() {
**Suggestion** : On peut s'éviter un beforeEach dans ce fichier qui ne contient qu'un test 

```suggestion
  describe('Unit | Route | update-expired-password', function() {

  setupTest();

  it('should retrieve a reset expired password demand', async function() {
    // given
    const route = this.owner.lookup('route:update-expired-password');
    const peekAllStub = sinon.stub();
    const storeStub = Service.create({
      peekAll: peekAllStub,
    });
    route.set('store', storeStub);

    const resetExpiredPasswordDemand = EmberObject.create({ username: 'user.name0112', oneTimePassword: 'password' });
    peekAllStub.returns([
      resetExpiredPasswordDemand,
    ]);

    // when
    const model = await route.model();

    // then
    expect(model).to.equal(resetExpiredPasswordDemand);
  });
});
```

2021-04-16 14:49 UTC, Anne-Gaelle-S commented on mon-pix/app/components/update-expired-password-form.js
> +        await this.resetExpiredPasswordDemand.unloadRecord();
**question**
Est-ce que l'await est nécessaire ici ? On a d'autres exemples dans le code qui ne semblent pas le mettre

2021-04-16 14:51 UTC, Anne-Gaelle-S approved these changes

2021-04-19 07:41 UTC, octo-topi commented
Je propose de changer le titre de la PR 
- de  _[TECH] Corriger le changement de mot de passe à usage unique pour un élève qui tente de se réconcilier (PIX-2274)._
- à _[TECH] Introduire un modèle dédié à la réinitialisation de mot de passe (PIX-2274)._

Après tout, ce modèle sera aussi utilisé hors SCO

2021-04-19 08:17 UTC, AndreiaPena requested changes
Bloqué: remplacer "username" du model par un nom plus générique ?

2021-04-19 08:57 UTC, yahyayouness commented on mon-pix/app/components/update-expired-password-form.js
> +        await this.resetExpiredPasswordDemand.unloadRecord();
C'est enlevé.

2021-04-19 09:24 UTC, octo-thlo commented
> > **Question** : Pourquoi avoir choisi de ne mettre que le username dans le model `reset-expired-password-demand` ?
> > Les élèves ont également des adresse e-mail pour se connecter et on se retrouve avec cette adresse dans le champ `username `
> > <img alt="Capture d’écran 2021-04-16 à 11 38 51" width="1312" src="https://user-images.githubusercontent.com/58915422/115006219-eb0b1b00-9ea8-11eb-8757-d1f15d9968c4.png">
> > En grooming il a été convenu d'ajouter aussi le champ email, d'où ma question 🙂
> > <img alt="Capture d’écran 2021-04-16 à 11 40 02" width="550" src="https://user-images.githubusercontent.com/58915422/115006412-21e13100-9ea9-11eb-8c7a-164ef793a774.png">
> 
> La raison est que l'implémentation front et l'api existante qui permet de mettre à jour le mot de passe n'utilise que 3 champs:
> 
> ```
>         data: {
>           attributes: {
>             username: Joi.string().required(),
>             expiredPassword: Joi.string().required(),
>             newPassword: Joi.string().pattern(XRegExp(passwordValidationPattern)).required(),
>           },
>           type: Joi.string(),
>         }
> ```
> 
> Et dans le repository, on cherche avec username or email
> const foundUser = await userRepository.getByUsernameOrEmailWithRolesAndPassword(username);
> 
> Je peux faire un Scout Rule de bout en bout, pour renommer username en login ou autres suggestion. le field login pourrait contenir à la fois un username et email ? WDYT , on décide en point tech

On met effectivement le doigt sur un problème de vocabulaire où username est utilisé pour désigner 2 choses différentes.
En plus de l'exemple que tu donnes, on voit que l'id et le nom du champ de saisie sur la page de connexion est... `login` (d'où ta suggestion j'imagine).

Après discussions en point tech on trouve que login est trop ambigu (il pourrait représenter les credentials username + MDP), on propose donc avec @AndreiaPena de l'appeler `identifier`. 
En plus ça fait echo à notre champ `externalIdentifier`.

2021-04-19 14:15 UTC, AndreiaPena approved these changes

2021-04-19 15:52 UTC, yahyayouness commented
> > > **Question** : Pourquoi avoir choisi de ne mettre que le username dans le model `reset-expired-password-demand` ?
> > > Les élèves ont également des adresse e-mail pour se connecter et on se retrouve avec cette adresse dans le champ `username `
> > > <img alt="Capture d’écran 2021-04-16 à 11 38 51" width="1312" src="https://user-images.githubusercontent.com/58915422/115006219-eb0b1b00-9ea8-11eb-8757-d1f15d9968c4.png">
> > > En grooming il a été convenu d'ajouter aussi le champ email, d'où ma question 🙂
> > > <img alt="Capture d’écran 2021-04-16 à 11 40 02" width="550" src="https://user-images.githubusercontent.com/58915422/115006412-21e13100-9ea9-11eb-8c7a-164ef793a774.png">
> > 
> > 
> > La raison est que l'implémentation front et l'api existante qui permet de mettre à jour le mot de passe n'utilise que 3 champs:
> > ```
> >         data: {
> >           attributes: {
> >             username: Joi.string().required(),
> >             expiredPassword: Joi.string().required(),
> >             newPassword: Joi.string().pattern(XRegExp(passwordValidationPattern)).required(),
> >           },
> >           type: Joi.string(),
> >         }
> > ```
> > 
> > 
> > Et dans le repository, on cherche avec username or email
> > const foundUser = await userRepository.getByUsernameOrEmailWithRolesAndPassword(username);
> > Je peux faire un Scout Rule de bout en bout, pour renommer username en login ou autres suggestion. le field login pourrait contenir à la fois un username et email ? WDYT , on décide en point tech
> 
> On met effectivement le doigt sur un problème de vocabulaire où username est utilisé pour désigner 2 choses différentes.
> En plus de l'exemple que tu donnes, on voit que l'id et le nom du champ de saisie sur la page de connexion est... `login` (d'où ta suggestion j'imagine).
> 
> Après discussions en point tech on trouve que login est trop ambigu (il pourrait représenter les credentials username + MDP), on propose donc avec @AndreiaPena de l'appeler `identifier`.
> En plus ça fait echo à notre champ `externalIdentifier`.

Pour info, j'ai regardé comment s'est implementé dans Keycloak. Dans l'ihm on a bien username or Email mais lors de l'envoie dans l'api on a l'username. Suite à notre échange, Jeremy nous a signalé que c'est marqué dans la RFC d'auth.

1.3.3.  Resource Owner Password Credentials

   The resource owner password credentials (i.e., username and password)
   can be used directly as an authorization grant to obtain an access
   token.

Du coup, on garde l'attribut username.

2021-04-19 16:48 UTC, merged