[Feature] Empêcher de se connecter avec son mot de passe à usage unique lorsque l'utilisateur doit changer son mot de passe (Pix-2035).)
1024pix/pix pull request #2902
Opened 2021-04-26 11:18 UTC by yahyayouness

## :unicorn: Problème

Le flag 'shouldChangePassword' passe de true à false quand on clique sur le bouton réinitialiser mon mot de passe [](https://app.recette.pix.fr/mot-de-passe-oublie)

Par conséquent:

1- Si un prof reset le password d’un éléve dans Pix Orga et que l'élève fait une demande de reset via [app.pix.fr](url). Et qu'il ne change pas son mot de passe depuis l’email qu’il a reçu. Mais qu'il retrouve le mot de passe à usage unique fourni par son prof. Il peut donc se connecter avec ce mot de passe à usage unique et ne sera pas invité à le changer. Le mot de passe à usage unique n’est plus à usage unique. De plus, le format de ce dernier n'est pas acceptable.

2- Si un utilisateur X fait le reset d'un user Y, cela change l'état du 'shouldchangepassword' de l'utilisateur Y alors que ce dernier n'as rien demandé !

## :robot: Solution
Attendre que le mot de passe oublié soit vraiment mise à jour par l'utilisateur via sa demande de reset de mot de passe avant de désactiver le 'shouldchangepassword'.
Si ce dernier ne le met pas à jour, il pourra toujours utiliser le mot de passe à usage unique fourni pas son professeur.

## :100: Pour tester

Scénario 1:

1- Se rendre sur Pix Orga, réinitialiser le mot de passe d'un élève qui dispose d'une connexion par email.
2- Se rendre sur Pix App, et faire une demande d'oublie de mot de passe.
3- Vérifier qu'on peut plus accéder via le mot de passe à usage unique et qu'on est redirigé vers l'écran de mise à jour de mot de passe expiré.

Scénario 2:

1- Se rendre sur Pix Orga, réinitialiser le mot de passe d'un élève qui dispose d'une connexion par email.
2- Se rendre sur Pix App, et faire une demande d'oublie de mot de passe.
3- Réinitialiser son mot de passe depuis la demande recue par email.
4- Vérifier qu'on se connecte bien avec le mot de passe mise à jour.

2021-04-26 11:23 UTC, pix-service commented
I'm deploying this PR to these urls:

- App: https://app-pr2902.review.pix.fr
- Orga: https://orga-pr2902.review.pix.fr
- Certif: https://certif-pr2902.review.pix.fr
- Admin: https://admin-pr2902.review.pix.fr
- API: https://api-pr2902.review.pix.fr/api/

 Please check it out!

2021-04-28 14:28 UTC, chrc approved these changes

2021-04-30 10:06 UTC, Anne-Gaelle-S approved these changes

2021-04-30 10:06 UTC, Anne-Gaelle-S commented on api/lib/infrastructure/repositories/authentication-method-repository.js
> +    });
**suggestion**
Je ne crois pas que c'est la responsabilité du repository d'instancier un objet du domain.
Je propose de remonter ça côté usecase : 

dans `api/lib/domain/usecases/update-user-password.js` :
```js
    const authenticationComplement = new AuthenticationMethod.PixAuthenticationComplement({
      password: hashedPassword,
      shouldChangePassword: false,
    });
    const updatedUser = await authenticationMethodRepository.updateChangedPassword({
       userId: user.id,
       authenticationComplement,
  });
```

puis dans ` api/lib/infrastructure/repositories/authentication-method-repository.js` : 
```js 
updateChangedPassword({ userId, authenticationComplement }) {
return BookshelfAuthenticationMethod
   .where({
   // ...
 });
 ```

2021-04-30 10:16 UTC, octo-topi requested changes
Si le professeur génère un mot de passe et que l'utilisateur essaye de l'utiliser, il est rejeté
"L'adresse e-mail ou l'identifiant et/ou le mot de passe saisis sont incorrects."

Cas de test: https://app-pr2902.review.pix.fr/connexion 
Orga Collège The Night Watch  
Professeur: sco.admin@example.net
Utilisateur: blueivy.carter@example.net

2021-04-30 10:27 UTC, octo-topi commented on api/lib/infrastructure/repositories/authentication-method-repository.js
> +    });
:thinking: 
En général, les repository remontent des object du domain avec le `_toDomainConverter` qui est là par défaut, non ?

2021-05-03 09:34 UTC, Anne-Gaelle-S commented on api/lib/infrastructure/repositories/authentication-method-repository.js
> +    });
Oui en retour, mais là je parle des entrées de la méthode du repo :)

2021-05-03 09:50 UTC, octo-topi approved these changes

2021-05-03 09:59 UTC, yahyayouness commented on api/lib/infrastructure/repositories/authentication-method-repository.js
> +    });
J'ai suivi la cohérence des méthodes du repository, selon moi un repo peut être orienté métier dans le nommage des fonctions et avoir des objets du domain dans ses arguments. Je veux bien échanger en point tech sur la conception de ce repo, pour avoir l'avis de la team.

2021-05-03 15:59 UTC, merged