[FEATURE] Vérifier la validité des badges certifiables avant leur certification (PIX-2513).
1024pix/pix pull request #2923
Opened 2021-04-29 09:57 UTC by alexandrecoin

## :unicorn: Problème

Jusqu'à maintenant, pour tous les badges certifiables, nous posions les questions des acquis associés sans se soucier de savoir si les badges étaient encore valides (ex: possibilité pour l'utilisateur de remettre à zéro une compétence et donc d'invalider l'acquisition de son badge)

## :robot: Solution

Re-création d'un service `certification-badge-service` qui retourne les badges acquisitions valides.

## :rainbow: Remarques

N/A

## :100: Pour tester
> _Les instructions pour reproduire le problème, les profils de test, le parcours spécifique à utiliser, etc._

2021-04-29 10:02 UTC, pix-service commented
I'm deploying this PR to these urls:

- App: https://app-pr2923.review.pix.fr
- Orga: https://orga-pr2923.review.pix.fr
- Certif: https://certif-pr2923.review.pix.fr
- Admin: https://admin-pr2923.review.pix.fr
- API: https://api-pr2923.review.pix.fr/api/

 Please check it out!

2021-04-29 10:14 UTC, MelanieMEB commented on api/lib/domain/services/certification-badges-service.js
> +
```suggestion
    const badgeAcquisitions = bluebird.mapSeries(highestCertifiableBadgeAcquisitions, (badgeAcquisition) => {
      const badge = badgeAcquisition.badge;
      const targetProfile = await targetProfileRepository.get(badge.targetProfileId);
      const isBadgeValid = badgeCriteriaService.areBadgeCriteriaFulfilled({
        knowledgeElements,
        targetProfile,
        badge,
      });
     return isBadgeValid ? badgeAcquisition : null;
    });
    
   return _.compact(badgeAcquisitions);
```

2021-04-29 10:25 UTC, MelanieMEB requested changes

2021-04-29 10:25 UTC, MelanieMEB commented on api/tests/unit/domain/services/certification-badges-service-test.js
> +        // targetProfileRepository.get.withArgs(targetProfile.id).resolves(targetProfile);
Il reste des commentaires

2021-04-29 10:25 UTC, MelanieMEB commented on api/lib/domain/services/certification-badges-service.js
> +  async findStillValidBadgeAcquisitions({ userId, domainTransaction }) {
On n'utilise pas la domainTransaction dans toutes les requetes au Repository ci-dessous, je pense qu'on devrait l'ajouter dans les repo appeler si on veut éviter un soucis.
@laura-bergoens

2021-04-29 12:44 UTC, celineung commented on api/lib/domain/services/certification-badges-service.js
> +  async findStillValidBadgeAcquisitions({ userId, domainTransaction }) {
Nous avons passé la transaction aux méthodes de repo

2021-04-30 14:16 UTC, sbedeau approved these changes

2021-04-30 14:16 UTC, sbedeau commented on api/tests/integration/domain/services/certification-badges-service_test.js
> +      expect(badgeAcquisitions[0].badge.badgePartnerCompetences.length).to.equal(1);
**suggestion:** Je pense qu'il vaut mieux vérifier des données qu'une taille

2021-04-30 14:16 UTC, sbedeau commented on api/tests/integration/infrastructure/repositories/badge-acquisition-repository_test.js
> +      expect(certifiableBadgesAcquiredByUser[0].badge.badgeCriteria.length).to.deep.equal(1);
**suggestion:** Je pense qu'il vaut mieux vérifier des données qu'une taille

2021-05-04 08:40 UTC, laura-bergoens reviewed
Je me suis permis d'ajouter un commit pour démontrer que la domainTransaction n'était pas fonctionnel dans le `knowledge-element-repository.js`. Absorbez-bien la bonne syntaxe propre à knex (pour Bookshelf rien à redire c'est la bonne syntaxe) et n'hésitez pas à ajouter un test qui vérifie le bon fonctionnement de transaction dans le répo. C'est pas vraiment fait ailleurs malheureusement (et je blâme aussi la Laura du passé qui ne l'a pas fait à plusieurs occasions 😢 )

2021-05-04 12:34 UTC, MelanieMEB approved these changes

2021-05-05 12:48 UTC, celineung approved these changes

2021-05-05 13:00 UTC, merged