[TECH] Refacto technique préalable avant affichage des macarons sur le certificat utilisateur (PIX-2543)
1024pix/pix pull request #2939
Opened 2021-05-03 14:21 UTC by laura-bergoens

## :unicorn: Problème
Je propose un petit refacto technique plutôt simple en préparation à l'affichage des macarons pix+ sur les certificats.
Ces macarons sont supportés par un modèle nommé PrivateCertificate. J'ai trouvé ça dommage que ce modèle n'ait pas son repository dédié (ainsi on cache aussi les spécificités).

## :robot: Solution
- Ajout d'un répo dédié pour PrivateCertificate
- Gestion du statut du certificat (fonction de l'assessment-result, annulation possible, etc...) dans le modèle et non plus dans le répo
- Remplacement des anciens usages par le nouveau répo fraîchement créé

## :rainbow: Remarques
> _Des infos supplémentaires, trucs et astuces ?_

## :100: Pour tester
Non régression des certificats utilisateurs. Le plus facile reste à mon sens d'afficher les certificats de certif-success@example.net / pix123 sur cette RA et sur une autre, de comparer et de ne constater aucune différence

2021-05-03 14:28 UTC, pix-service commented
I'm deploying this PR to these urls:

- App: https://app-pr2939.review.pix.fr
- Orga: https://orga-pr2939.review.pix.fr
- Certif: https://certif-pr2939.review.pix.fr
- Admin: https://admin-pr2939.review.pix.fr
- API: https://api-pr2939.review.pix.fr/api/

 Please check it out!

2021-05-03 15:33 UTC, sroccaserra commented on api/tests/unit/domain/models/PrivateCertificate_test.js
> +    it('builds a PrivateCertificate cancelled', async () => {
Description de test : ici et dans les descriptions suivantes, je propose d'inverser le nom et l'adjectif, par exemple `it('builds a cancelled PrivateCertificate', ...)`.

2021-05-03 15:36 UTC, sroccaserra commented on api/lib/infrastructure/repositories/private-certificate-repository.js
> +      throw new NotFoundError(`Not found certification for ID ${id}`);
Description : "Certification not found for ID ..." ?

2021-05-03 16:02 UTC, sroccaserra approved these changes

2021-05-03 16:03 UTC, sroccaserra requested changes
Des tests échouent : https://app.circleci.com/pipelines/github/1024pix/pix/24954/workflows/dc001f7f-4299-4e71-8a9f-995c26dd7245/jobs/206644

2021-05-05 12:34 UTC, EGI-OCTO commented on api/lib/domain/usecases/find-user-private-certificates.js
> +};
Je comprend pas bien ce qu'on fait ici... je veux bien qu'on en parle

2021-05-05 13:34 UTC, sroccaserra approved these changes

2021-05-06 07:54 UTC, EGI-OCTO approved these changes

2021-05-06 13:58 UTC, P-Jeremy commented on api/tests/integration/infrastructure/repositories/private-certificate-repository_test.js
> +        birthplace: 'Saint-Ouen',
A chaque génération il y a une Elue, seule elle devra affronter les vampires, les démons et les forces du Mal. Elle s'appelle Buffy, elle vient du 9-3

2021-05-06 14:12 UTC, P-Jeremy approved these changes

2021-05-06 14:22 UTC, merged