[FIXUP] Changer le texte de la bannière pour les orga SCO sur Pix Orga (PIX-2545)
1024pix/pix pull request #2944
Opened 2021-05-04 10:13 UTC by yaelle6

## :unicorn: Problème
On souhaite prévenir les organisation du SCO que la certification est possible jusqu'en juin .

## :robot: Solution
Le dire dans la bannière sur Pix orga.

## :rainbow: Remarques
Il manque encore la trad ENG

## :100: Pour tester
Se connecter à Pix orga avec le compte d'une orga SCO

2021-05-04 10:18 UTC, pix-service commented
I'm deploying this PR to these urls:

- App: https://app-pr2944.review.pix.fr
- Orga: https://orga-pr2944.review.pix.fr
- Certif: https://certif-pr2944.review.pix.fr
- Admin: https://admin-pr2944.review.pix.fr
- API: https://api-pr2944.review.pix.fr/api/

 Please check it out!

2021-05-04 14:02 UTC, lisequesnel requested changes

2021-05-04 14:02 UTC, lisequesnel commented on orga/app/components/information-banner.js
> +    return this.currentUser.isAgriculture ? 'https://view.genial.ly/6034cdf633f5220dc1eb101d' : 'https://view.genial.ly/6077017b8b37870d98620200';
```suggestion
    return 'https://view.genial.ly/6077017b8b37870d98620200';
``

2021-05-04 14:02 UTC, lisequesnel commented on orga/app/styles/components/information-banner.scss
> +  }
les couleurs choisies devraient normalement être dans le design system (et donc disponible en variables $...). Si elles n'y sont pas c'est qu'il faut revoir le design system.

2021-05-11 13:02 UTC, ajoanny commented
Test fonctionnels : OK 👍🏽

2021-05-11 13:08 UTC, ajoanny approved these changes

2021-05-26 08:10 UTC, lisequesnel commented on orga/app/components/information-banner.js
>    }
**suggestion** : on est plus obligé d'avoir un getter, on peut directement le mettre dans le hbs si on veut :)

2021-05-26 08:13 UTC, lisequesnel commented on orga/translations/fr.json
> +      "message": " La certification en collège et lycée est possible jusqu'au 25 juin. Pour reporter des sessions déjà programmées, il vous suffit de changer la date de la session en cliquant sur « m
**suggestion** : j'ai une interrogation concernant le message. ici on est dans Pix Orga alors qu'on parle de manipulations dans Pix Certif.

à moindre frais, je propose de mettre :
```suggestion
      "message": "La certification en collège et lycée est possible jusqu'au 25 juin. Pour reporter des sessions déjà programmées, il vous suffit, dans Pix Certif, de changer la date de la session en cliquant sur « modifier ».",
```

2021-05-26 08:17 UTC, lisequesnel approved these changes
validé techniquement et fonctionnellement, modulo le retour sur la phrase

2021-05-26 10:06 UTC, merged