[TECH] Ajoute des logs de debug sur http agent
1024pix/pix pull request #2945
Opened 2021-05-04 10:46 UTC by francois2metz

## :unicorn: Problème
Nous n'avons pas de détails dans les logs sur les requêtes externes qui sont faites.

## :robot: Solution
Ajouter des logs de debug en début et fin de requête.

## :100: Pour tester
1. S'assurer que `LOG_LEVEL=debug`
2. Se connecter sur Pix admin
3. Dans l'onglet Outils, cliquer sur recharger le cache
4. Dans les logs doivent apparaitre des lignes similaire à:
```
{"name":"pix-api","hostname":"e780697f77a9","pid":32,"level":20,"msg":"Starting GET request to https://lcms.pix.fr/api/releases/latest","time":"2021-05-04T10:40:33.338Z","v":0}
{"name":"pix-api","hostname":"e780697f77a9","pid":32,"level":20,"msg":"End GET request to https://lcms.pix.fr/api/releases/latest success: 200","time":"2021-05-04T10:40:35.265Z","v":0}
```

2021-05-04 10:50 UTC, pix-service commented
I'm deploying this PR to these urls:

- App: https://app-pr2945.review.pix.fr
- Orga: https://orga-pr2945.review.pix.fr
- Certif: https://certif-pr2945.review.pix.fr
- Admin: https://admin-pr2945.review.pix.fr
- API: https://api-pr2945.review.pix.fr/api/

 Please check it out!

2021-05-04 14:05 UTC, VincentHardouin approved these changes

2021-05-04 14:14 UTC, VincentHardouin commented on api/lib/infrastructure/http/http-agent.js
> +      logger.debug(`End POST request to ${url} error: ${code}`);
On souhaite pas avoir l'erreur en question et non juste le code ?

2021-05-04 15:42 UTC, francois2metz commented on api/lib/infrastructure/http/http-agent.js
> +      logger.debug(`End POST request to ${url} error: ${code}`);
Ma foi pourquoi pas. Peut être rajouter plus de détails (en début et fin de requêtes) en mode TRACE ?

2021-05-11 15:20 UTC, MathieuGilet approved these changes
*Question*: Est-ce que la finalité sera de passer le niveau de log à debug en prod ponctuellement pour débugguer certains appels ?

2021-05-12 07:37 UTC, francois2metz commented
> _Question_: Est-ce que la finalité sera de passer le niveau de log à debug en prod ponctuellement pour débugguer certains appels ?

Oui, surtout si on rajoute des TRACE.

2021-05-14 16:17 UTC, octo-topi requested changes
:cry: As-tu vu les commits précédents sur ce fichier ?
Il y avait du log avant, mais pour pouvoir le réutiliser dans d'autres contextes, [la responsabilité a été déléguée à l'appelant](
https://github.com/1024pix/pix/pull/2871#discussion_r622808155)

Au pire, je suis OK pour logger sur NODE_ENV=development, mais pas plus

On peut noter la décision [dans l'ADR](https://github.com/1024pix/pix/blob/dev/docs/adr/0023-encapsuler-appel-http.md) qu'on s'en souvienne, voire ajouter une règle de lint :smiling_imp:

2021-05-20 12:08 UTC, lisequesnel commented on api/lib/infrastructure/http/http-agent.js
> +      logger.debug(`End POST request to ${url} error: ${code}`);
oui je pense que le code peut ne pas suffire dans certains cas

2021-05-20 12:09 UTC, lisequesnel approved these changes

2021-05-26 08:57 UTC, octo-topi approved these changes
Comme vu avec @francois2metz, `logger.debug` ne loggue pas systématiquement les appels
Cela dépend de la configuration de l'API, voir `LOG_LEVEL`
https://github.com/1024pix/pix/blob/dev/api/sample.env#L214

2021-05-27 08:05 UTC, francois2metz commented on api/lib/infrastructure/http/http-agent.js
> +      logger.debug(`End POST request to ${url} error: ${code}`);
J'ai rajouté le log du body de la requête

2021-05-27 08:07 UTC, merged