[FEATURE] Ajout de sous-catégories de support pour les embed (PIX-2436).
1024pix/pix pull request #2954
Opened 2021-05-05 09:49 UTC by alexandrecoin

## :unicorn: Problème

Il manque aux utilisateurs la possibilité de contacter le support  pour des problèmes liés aux simulateurs dans les cas suivants :

- Difficulté d'affichage sur desktop
- Difficulté d'affichage sur écrans mobiles (téléphone/tablette)

## :robot: Solution

Ajout de nouvelles sous-catégories répondant à cette problématique.
Ces nouvelles sous-catégories sont constituées d'une partie `tutoriel` et d'un `textarea`.

## :rainbow: Remarques
N/A

## :100: Pour tester

Lors d'une épreuve, aller sur : 
- Signaler un problème
- Le simulateur / l'application
- Choisir les deux dernières options.

Pour chacune des options, vérifier la présence de la partie tutoriel et du textarea et du bon fonctionnement de ce dernier lors de l'envoi en DB.

2021-05-05 09:55 UTC, pix-service commented
I'm deploying this PR to these urls:

- App: https://app-pr2954.review.pix.fr
- Orga: https://orga-pr2954.review.pix.fr
- Certif: https://certif-pr2954.review.pix.fr
- Admin: https://admin-pr2954.review.pix.fr
- API: https://api-pr2954.review.pix.fr/api/

 Please check it out!

2021-05-06 08:14 UTC, MelanieMEB requested changes

2021-05-06 08:14 UTC, MelanieMEB commented on mon-pix/translations/fr.json
> +                  "solution": "Nous faisons notre possible pour que les simulateurs fonctionnent sur tous les appareils, tous les OS et tous les navigateurs mais il se peut que vous utilisiez un syst
Suggestion : Le texte`[ou bien capture automatique de ces informations dans ce cas précis]` ne doit pas être dans la phrase

2021-05-06 08:14 UTC, MelanieMEB commented on mon-pix/translations/fr.json
> +                    "solution": "Nous faisons notre possible pour que les simulateurs fonctionnent sur tous les appareils, tous les OS et tous les navigateurs mais il se peut que vous utilisiez un sy
Suggestion : Le texte[ou bien capture automatique de ces informations dans ce cas précis] ne doit pas être dans la phrase

2021-05-06 08:14 UTC, MelanieMEB commented on mon-pix/translations/en.json
> +                    "solution": ""
En attente des version anglaise pour le ✅

2021-05-06 08:32 UTC, sbedeau commented on mon-pix/tests/integration/components/feedback-panel_test.js
> +        await fillIn('.feedback-panel__dropdown', PICK_SELECT_OPTION_WITH_NESTED_LEVEL);
**suggestion:** Remplacer `.feedback-panel__dropdown` par `.select[data-test-feedback-category-dropdown]`

2021-05-06 08:58 UTC, celineung commented on mon-pix/tests/integration/components/feedback-panel_test.js
> +      await click(TOGGLE_LINK);
**nitpick (non-blocking):** renommer la variable pour expliciter de quel bouton il s'agit:

```suggestion
      await click(OPEN_FEEDBACK_BUTTON);
```

2021-05-06 08:58 UTC, celineung commented on mon-pix/tests/integration/components/feedback-panel_test.js
> +        await fillIn('.feedback-panel__dropdown', PICK_SELECT_OPTION_WITH_NESTED_LEVEL);
Il existe un const déclaré en haut du fichier `const DROPDOWN = '.feedback-panel__dropdown';`.

**suggestion:** ajouter `CATEGORY_DROPDOWN` et `SUBCATEGORY_DROPDOWN`:

```
const DROPDOWN = '.feedback-panel__dropdown';
const CATEGORY_DROPDOWN = 'select[data-test-feedback-category-dropdown]';
const SUBCATEGORY_DROPDOWN = 'select[data-test-feedback-subcategory-dropdown]';
```

Et donc ici:
```suggestion
        await fillIn(CATEGORY_DROPDOWN, PICK_SELECT_OPTION_WITH_NESTED_LEVEL);
```

2021-05-06 09:09 UTC, celineung commented on mon-pix/tests/integration/components/feedback-panel_test.js
> +      it('should directly display the message box and the submit button when category has a textarea', async function() {
**suggestion:** Il manque la vérification de l'affichage du message box:

```
expect(findAll(TEXTAREA).length).to.equal(1);
```
ou

```
expect(find(TEXTAREA)).to.exist;
```
?

2021-05-06 09:09 UTC, celineung commented on mon-pix/tests/integration/components/feedback-panel_test.js
> +        // debugger;
**suggestion:** supprimer cette ligne ^^

2021-05-06 09:35 UTC, alexandrecoin commented on mon-pix/translations/en.json
> +                    "solution": ""
Demande effectuée.

2021-05-06 15:03 UTC, Thomasevano commented on mon-pix/tests/integration/components/feedback-panel_test.js
> +      it('should directly display the tuto without the textbox nor the send button when category has a tutorial', async function() {
```suggestion
      it('should directly display the tuto without the textbox or the send button when category has a tutorial', async function() {
```

2021-05-07 05:34 UTC, alexandrecoin commented on mon-pix/translations/en.json
> +                    "solution": ""
Update : traductionss mises à jour.

2021-05-07 07:35 UTC, MelanieMEB approved these changes

2021-05-07 07:55 UTC, Thomasevano approved these changes

2021-05-07 09:02 UTC, celineung approved these changes

2021-05-07 09:28 UTC, merged