[TECH] Pouvoir spécifier des KE dans les tests d'algo
1024pix/pix pull request #2956
Opened 2021-05-05 13:06 UTC by celineung

## :unicorn: Problème
Dans les tests d'algo, on devait spécifier en entrée via le paramètre `userResult` le comportement de l'utilisateur souhaité (parmi ['ok', 'ko', 'random', 'firstOKthenKO', 'firstKOthenOK']).
Or il faudrait se rapprocher de la réalité et pouvoir fournir des KE (récupérés depuis un utilisateur réél) à notre algo.

## :robot: Solution
Dans l'algo, si un fichier de KE est donné en paramètre, alors ce fichier est lu et le statut de réussite de la question dépend des KE.

## :rainbow: Remarques
> _Des infos supplémentaires, trucs et astuces ?_

## :100: Pour tester
Tester en local avec : npm start -- --competenceId recsvLz0W2ShyfD63 --userKEFile ~/path/to/usertest.json
Le fichier usertest.json se trouve en pièce jointe du ticket Jira.

2021-05-05 13:11 UTC, pix-service commented
I'm deploying this PR to these urls:

- App: https://app-pr2956.review.pix.fr
- Orga: https://orga-pr2956.review.pix.fr
- Certif: https://certif-pr2956.review.pix.fr
- Admin: https://admin-pr2956.review.pix.fr
- API: https://api-pr2956.review.pix.fr/api/

 Please check it out!

2021-05-06 07:35 UTC, MelanieMEB commented on high-level-tests/test-algo/algo.js
> +    case 'KE': {
Soucis avec ce cas : à aucun moment on ne met le userResult en 'KE'. Donc quand je test, je me retrouve dans le cas de base 'ok'.
Si je le force, on voit qu'il y a un soucis et qu'on récupère comme ke des undefined.

2021-05-06 07:36 UTC, MelanieMEB requested changes

2021-05-06 07:36 UTC, MelanieMEB commented on high-level-tests/test-algo/algo.js
> +  const userKE = _read(userKEFile);
Peut-être mettre `userResult` à `KE` si des KE existe ?

2021-05-06 08:34 UTC, MelanieMEB commented on high-level-tests/test-algo/algo.js
> +    case 'KE': {
J'ai fait un commit de correction

2021-05-06 08:34 UTC, MelanieMEB approved these changes

2021-05-07 09:12 UTC, sbedeau approved these changes

2021-05-07 09:20 UTC, merged