[FEATURE] Afficher tous les tags existants dans Pix Admin (PIX-1332).
1024pix/pix pull request #3010
Opened 2021-05-17 15:41 UTC by AndreiaPena

## :unicorn: Problème
Pour implémenter la fonctionnalité d'attribuer de nouveaux tags aux organisations sur Pix Admin, il nous faut dans un premier temps afficher tous les tags existants.

## :robot: Solution

- Afficher tous les tags existants dans un onglet "Tags", dans la page de détail d'une organization.
- Distinguer les tags déjà attribués et non attribués par la couleur.

Tag "actif" (attribué) = tag violet
Tag "inactif" = tag gris

## :100: Pour tester
Aller sur Pix Admin > Toutes les organisations > Dragon & Co
Cette organisation n'a aucun tag donc vérifier que tous les tags sont gris.

Toutes les organisations > Pôle Emploi
Vérifier que le tag "POLE EMPLOI" est violet, les autres gris.

2021-05-17 15:47 UTC, pix-service commented
I'm deploying this PR to these urls:

- App: https://app-pr3010.review.pix.fr
- Orga: https://orga-pr3010.review.pix.fr
- Certif: https://certif-pr3010.review.pix.fr
- Admin: https://admin-pr3010.review.pix.fr
- API: https://api-pr3010.review.pix.fr/api/

 Please check it out!

2021-05-17 18:42 UTC, chrc approved these changes

2021-05-18 12:21 UTC, octo-thlo commented
**Bloquant** Après tests fonctionnels, on a remarqué avec @octo-topi que la liste n'était pas triée par ordre alphabétique comme spécifié dans le ticket

2021-05-18 12:21 UTC, octo-thlo requested changes
Après tests fonctionnels, on a remarqué avec @octo-topi que la liste n'était pas triée par ordre alphabétique comme spécifié dans le ticket

2021-05-18 12:57 UTC, octo-thlo commented on api/tests/acceptance/application/tags/tag-api_test.js
> +      const tag3 = databaseBuilder.factory.buildTag({ id: 3, name: 'TAG3' });
**Chipotage non-bloquant** Pourquoi 3 tags et pas 2 si l'objectif est de tester lorsqu'il y en a plusieurs ?

2021-05-18 13:02 UTC, octo-thlo commented on api/tests/acceptance/application/tags/tag-api_test.js
> +      const tag1 = databaseBuilder.factory.buildTag({ id: 1, name: 'TAG1' });
**Suggestion non-bloquante**

```suggestion
      const tag1 = databaseBuilder.factory.buildTag({ name: 'TAG1' });
```

2021-05-18 13:06 UTC, octo-thlo commented on api/lib/application/tags/index.js
> +      config: {
**Suggestion Bloquante**

config: {
        pre: [{
          method: securityPreHandlers.checkUserHasRolePixMaster,
          assign: 'hasRolePixMaster',
        }],
        handler: tagController.findAllOrganizationsTags,
        notes: [
          '- ** Cette route est accessible aux utilisateurs Pix authentifiés \n' +
          '- ** Récupère la liste de tout les tags.',
        ],
        tags: ['api', 'tags'],
      },

2021-05-18 13:07 UTC, octo-thlo commented on api/lib/application/tags/index.js
> +      },
**Suggestion Bloquante**

```suggestion
      config: {
        pre: [{
          method: securityPreHandlers.checkUserHasRolePixMaster,
          assign: 'hasRolePixMaster',
        }],
        handler: tagController.findAllOrganizationsTags,
        notes: [
          '- ** Cette route est accessible aux utilisateurs Pix authentifiés \n' +
          '- ** Récupère la liste de tout les tags.',
        ],
        tags: ['api', 'tags'],
      },
```

2021-05-18 13:15 UTC, octo-thlo commented on api/lib/application/tags/index.js
> +      path: '/api/tags',
**Suggestion Bloquante**

```suggestion
      path: '/api/admin/tags',
```

2021-05-18 13:17 UTC, octo-thlo commented on api/lib/domain/usecases/find-all-organizations-tags.js
> +module.exports = async function findAllOrganizationsTags({
**Suggestion Bloquante**

```suggestion
module.exports = async function findAllTags({
```

2021-05-18 13:18 UTC, octo-thlo commented on api/lib/application/tags/tag-controller.js
> +  async findAllOrganizationsTags() {
**Suggestion Bloquante**

```suggestion
  async findAllTags() {
```

2021-05-18 13:18 UTC, octo-thlo commented on api/lib/application/tags/tag-controller.js
> +  async findAllOrganizationsTags() {
Pour éviter l'ambiguïté avec la table OrganitationTags

2021-05-18 13:21 UTC, octo-thlo commented on api/tests/acceptance/application/tags/tag-api_test.js
> +      const userId = databaseBuilder.factory.buildUser().id;
Pour faire suite au commentaire sur l'ajout d'un pre-handler pour ne pas rendre accessible cette route à tous les utilisateurs authentifiés :

```suggestion
      const userId = databaseBuilder.factory.buildUser.withPixRolePixMaster().id;
```

2021-05-18 13:29 UTC, octo-thlo commented on api/tests/acceptance/application/tags/tag-api_test.js
> +
**Suggestion Bloquante** Rajouter un nouveau test pour le cas non-passant

```suggestion
it('should return 403 HTTP status code when the user authenticated is not PixMaster', async () => {
      // given
      const server = await createServer();
      const userId = databaseBuilder.factory.buildUser().id;

      await databaseBuilder.commit();

      const options = {
        method: 'GET',
        url: '/api/tags',
        headers: { authorization: generateValidRequestAuthorizationHeader(userId) },
      };

      // when
      const response = await server.inject(options);

      // then
      expect(response.statusCode).to.equal(403);
      expect(response).to.equal(403);
    });
```

2021-05-18 13:32 UTC, octo-thlo commented on api/lib/application/tags/index.js
> +          '- ** Cette route est accessible aux utilisateurs Pix authentifiés \n' +
```suggestion
          '- **Cette route est restreinte aux utilisateurs authentifiés avec le rôle Pix Master +
```

2021-05-18 13:32 UTC, octo-thlo commented on api/lib/application/tags/index.js
> +          '- ** Récupère la liste de tout les tags.',
**Chipotage**

```suggestion
          '- ** Renvoie la liste de tous les tags.',
```

2021-05-18 13:45 UTC, octo-thlo commented on api/tests/unit/application/tags/index_test.js
> +describe('Unit | Application | Router | tag-router', () => {
**Suggestion Bloquante**

Déplacer ce test dans les tests d'intégration puisqu'il teste l'intégration entre le router et le controller.
Un test unitaire rigoureux serait inintéressant puisque les fichiers index.js ne sont que des fichiers de configuration pour le router. (voir ADR)

2021-05-18 13:47 UTC, octo-thlo commented on api/tests/unit/application/tags/index_test.js
> +
Toujours suite à la remarque sur l'accès à la route par un utilisateur non PixMaster, l'ajout du pre-handler rend ce test invalide.

Il faudrait rajouter la ligne suivante 

```suggestion
const securityPreHandlers = require('../../../../lib/application/security-pre-handlers');

```

2021-05-18 14:17 UTC, octo-topi commented on api/tests/unit/application/tags/tag-controller_test.js
> +      expect(usecases.findAllOrganizationsTags).to.have.been.called;
**chipotage**

```suggestion
      expect(usecases.findAllOrganizationsTags).to.have.been.calledOnce;
```

2021-05-18 14:17 UTC, octo-topi commented on api/tests/unit/application/tags/tag-controller_test.js
> +      const allOrganizationTags = [ tag1, tag2, tag3 ];
**chipotage**
```suggestion
      const tags = [ tag1, tag2, tag3 ];
```

2021-05-18 14:34 UTC, octo-topi commented on api/tests/unit/domain/usecases/find-all-organizations-tags_test.js
> +  it('should find all organizations tags', async () => {
**suggestion**
Tester l'appel au repository "avec les bons paramètres" (once)
```suggestion
  it('should return tags', async () => {
```

Tester que le use case renvoie ce que le reposlui renvoie
```suggestion
  it('should return all tags', async () => {
```

2021-05-18 14:36 UTC, octo-topi commented on api/tests/unit/domain/usecases/find-all-organizations-tags_test.js
> +    expect(allTags.length).to.equal(3);
**suggestion**
```suggestion
    const expectedTags = [tag1, tag2, tag3];
    expect(allTags.length).to.deep.equal(expectedTags);
```

2021-05-18 14:40 UTC, octo-topi commented on api/tests/unit/domain/usecases/find-all-organizations-tags_test.js
> +  });
**question**
Ce cas de test est-il nécessaire ?
```suggestion
```

2021-05-18 15:02 UTC, octo-topi commented on api/tests/integration/infrastructure/repositories/tag-repository_test.js
> +      expect(result[0]).to.be.instanceOf(Tag);
**suggestion**
Instancier les objets du domaine permet de faire les deux assertions en une fois
=> à discuter en récap tech
```suggestion
      // given
      const tag1 = new Tag({ id: 100000, name: 'PUBLIC' });
      const tag2 = new Tag({ id: 100001, name: 'PRIVE' });
      databaseBuilder.factory.buildTag(tag1);
      databaseBuilder.factory.buildTag(tag2);
      await databaseBuilder.commit();
      const expectedResult = [
        tag1,
        tag2,
      ];

      // when
      const result = await tagRepository.findAll();

      // then
      expect(result).to.be.deep.equal(expectedResult);
```

2021-05-18 15:04 UTC, octo-topi commented on api/tests/unit/infrastructure/serializers/jsonapi/tag-serializer_test.js
> +    it('should convert a tag model object into JSON API data', () => {
**chipotage**
```suggestion
    it('should convert a tag model to JSON', () => {
```

2021-05-18 15:10 UTC, octo-topi commented on api/tests/unit/infrastructure/serializers/jsonapi/tag-serializer_test.js
> +      };
**chipotage**
```suggestion
      const expectedSerializedTag = {
        data: {
          attributes: {
            name: tag.name,
          },
          id: `${tag.id}`,
          type: 'tags',
        },
      };
```

2021-05-19 08:49 UTC, AndreiaPena commented on api/tests/acceptance/application/tags/tag-api_test.js
> +      const tag3 = databaseBuilder.factory.buildTag({ id: 3, name: 'TAG3' });
Pas de raison particulière, on peut en mettre 2

2021-05-19 08:51 UTC, AndreiaPena commented on api/tests/acceptance/application/tags/tag-api_test.js
> +      const tag1 = databaseBuilder.factory.buildTag({ id: 1, name: 'TAG1' });
Pourquoi le supprimer ? On l'utilise dans le tableau attendu

2021-05-19 09:03 UTC, AndreiaPena commented on api/lib/application/tags/index.js
> +      },
Done

2021-05-19 09:03 UTC, AndreiaPena commented on api/lib/application/tags/index.js
> +      path: '/api/tags',
Done

2021-05-19 09:03 UTC, AndreiaPena commented on api/tests/acceptance/application/tags/tag-api_test.js
> +      const tag3 = databaseBuilder.factory.buildTag({ id: 3, name: 'TAG3' });
Done

2021-05-19 09:04 UTC, AndreiaPena commented
> Après tests fonctionnels, on a remarqué avec @octo-topi que la liste n'était pas triée par ordre alphabétique comme spécifié dans le ticket
> 
> ![Capture d’écran 2021-05-18 à 14 22 09](https://user-images.githubusercontent.com/46494361/118650259-86631900-b7e4-11eb-80f3-3247503ea557.png)

Bien vu, on avait oublié de le faire. J'ai fait un orderBy dans le usecase.

2021-05-19 09:13 UTC, AndreiaPena commented on api/lib/application/tags/tag-controller.js
> +  async findAllOrganizationsTags() {
Done

2021-05-19 09:13 UTC, AndreiaPena commented on api/lib/domain/usecases/find-all-organizations-tags.js
> +module.exports = async function findAllOrganizationsTags({
Done

2021-05-19 09:13 UTC, AndreiaPena commented on api/tests/acceptance/application/tags/tag-api_test.js
> +      const userId = databaseBuilder.factory.buildUser().id;
Done

2021-05-19 09:21 UTC, AndreiaPena commented on api/tests/acceptance/application/tags/tag-api_test.js
> +
Pourquoi ces deux expect ? 

```
// then      
expect(response.statusCode).to.equal(403);      
expect(response).to.equal(403);
```

Done

2021-05-19 09:21 UTC, AndreiaPena commented on api/lib/application/tags/index.js
> +          '- ** Cette route est accessible aux utilisateurs Pix authentifiés \n' +
Done

2021-05-19 09:21 UTC, AndreiaPena commented on api/lib/application/tags/index.js
> +          '- ** Récupère la liste de tout les tags.',
Done

2021-05-19 09:24 UTC, AndreiaPena commented on api/tests/unit/application/tags/index_test.js
> +describe('Unit | Application | Router | tag-router', () => {
On en revient à notre discussion de standard d'équipe, la question de l'unitaire first, à en discuter. 
https://1024pix.atlassian.net/wiki/spaces/DEV/pages/1534361658/Standard+quipe#Usage-des-tests

2021-05-19 09:24 UTC, AndreiaPena commented on api/tests/unit/application/tags/index_test.js
> +
Done

2021-05-19 09:24 UTC, AndreiaPena commented on api/tests/unit/application/tags/tag-controller_test.js
> +      expect(usecases.findAllOrganizationsTags).to.have.been.called;
Done

2021-05-19 09:25 UTC, AndreiaPena commented on api/tests/unit/application/tags/tag-controller_test.js
> +      const allOrganizationTags = [ tag1, tag2, tag3 ];
Done

2021-05-19 09:30 UTC, AndreiaPena commented on api/tests/unit/domain/usecases/find-all-organizations-tags_test.js
> +  it('should find all organizations tags', async () => {
Je n'ai pas saisi pour le premier , on passe aucun paramètre au repo

2021-05-19 12:22 UTC, octo-thlo commented on api/tests/unit/application/tags/index_test.js
> +describe('Unit | Application | Router | tag-router', () => {
On est toujours unitaire first, mais tel qu'il est écrit, ce test est plutôt un test d'intégration

2021-05-19 12:22 UTC, octo-thlo commented on api/tests/acceptance/application/tags/tag-api_test.js
> +
Oups ! C'est un oubli de notre part, on voulait proposer un deuxième expect qui teste le message d'erreur

2021-05-19 12:24 UTC, octo-thlo commented on api/tests/acceptance/application/tags/tag-api_test.js
> +      const tag1 = databaseBuilder.factory.buildTag({ id: 1, name: 'TAG1' });
Qu'on le précise ou non au builder, le tag aura un id. 
Dans notre test sa valeur exacte n'a pas d'importance en revanche

2021-05-19 12:29 UTC, octo-thlo commented on api/tests/unit/domain/usecases/find-all-organizations-tags_test.js
> +  it('should find all organizations tags', async () => {
On cherche à tester deux choses :
- Qu'on fait le bon appel au repository
- Qu'on retourne ce que nous retourne cet appel

@octo-topi suggérait un expect qui utiliserait un `calledOnce` par exemple

2021-05-19 12:31 UTC, AndreiaPena commented on api/tests/unit/infrastructure/serializers/jsonapi/tag-serializer_test.js
> +    it('should convert a tag model object into JSON API data', () => {
Done

2021-05-19 12:33 UTC, AndreiaPena commented on api/tests/unit/infrastructure/serializers/jsonapi/tag-serializer_test.js
> +      };
j'ai opté pour un tag.id.toString() 😄 
Done !

2021-05-19 12:38 UTC, AndreiaPena commented on api/tests/acceptance/application/tags/tag-api_test.js
> +      const tag1 = databaseBuilder.factory.buildTag({ id: 1, name: 'TAG1' });
même chose pour name alors non ?

2021-05-19 12:40 UTC, AndreiaPena commented on api/tests/acceptance/application/tags/tag-api_test.js
> +
Je peux ajouter une ligne pour le message d'erreur si vous pensez que c'est pertinent :)

2021-05-19 12:54 UTC, octo-topi commented on api/tests/integration/infrastructure/repositories/tag-repository_test.js
>        expect(result).to.be.deep.equal(expectedResult);
**chipotage**
Pour éviter davoir un test flaky, mettre une assertion non sensible à l'ordre

```suggestion
      expect(result).to.have.membersl(expectedResult);
```

2021-05-19 12:57 UTC, octo-topi commented on admin/app/components/organization-all-tags.hbs
> +          {{#if tag.isTagAssociateToOrganization}}
**chipotage**
J'aimerai un autre verbe, car ça ressemble à du français, et il y a d'autres verbes plus courants (linked, tagged, assigned..)
```suggestion
          {{#if tag.isTagAssociatedToOrganization}}
```

2021-05-19 12:58 UTC, octo-topi commented on admin/app/components/organization-all-tags.js
> +    const allTagsAssociatedToCurrentOrganization = [];
**chipotage**
Pourquoi `all` ?
```suggestion
    const tagsAssociatedToCurrentOrganization = [];
```

2021-05-19 13:00 UTC, octo-topi commented
J'ai fini la review, j'attends que les changes bloquants soient résolus avant de :heavy_check_mark:

2021-05-19 13:00 UTC, octo-topi requested changes
J'ai fini la review
J'attends que les changes bloquants soient résolus avant de heavy_check_mark

2021-05-19 14:54 UTC, AndreiaPena commented on admin/app/components/organization-all-tags.hbs
> +          {{#if tag.isTagAssociateToOrganization}}
j'opte pour assigned

2021-05-19 14:54 UTC, AndreiaPena commented on admin/app/components/organization-all-tags.js
> +    const allTagsAssociatedToCurrentOrganization = [];
bien vu ! Done

2021-05-19 15:51 UTC, AndreiaPena commented on admin/app/components/organization-all-tags.hbs
> +          {{#if tag.isTagAssociateToOrganization}}
Done

2021-05-19 15:54 UTC, AndreiaPena commented
> Après tests fonctionnels, on a remarqué avec @octo-topi que la liste n'était pas triée par ordre alphabétique comme spécifié dans le ticket
> 
> ![Capture d’écran 2021-05-18 à 14 22 09](https://user-images.githubusercontent.com/46494361/118650259-86631900-b7e4-11eb-80f3-3247503ea557.png)

On avait oublié ça, merci ! Fait coté IHM

2021-05-20 09:16 UTC, octo-thlo commented on admin/app/components/organization-all-tags.js
> +    return orderBy(tagsAssignedToCurrentOrganization, ['name']);
`Remarque bloquante`

Il me semble que ce comportement n'est pas testé.

2021-05-20 09:19 UTC, octo-thlo commented on admin/app/components/organization-all-tags.js
> +        tagsAssignedToCurrentOrganization.push({ name: tag.name, isTagAssignedToOrganization: false });
**Remarque**

À la lecture je trouve ça un peu déroutant de rajouter des tags non assignés à l'orga courante dans un objet qui s'appelle `tagsAssignedToCurrentOrganization`

2021-05-20 09:35 UTC, octo-thlo commented on admin/app/components/organization-all-tags.hbs
> +            </PixTag>
**Question**

C'est cool d'être resté simple pour cette première PR. Je me demande si pour les prochaines ça ne se rapprochera pas plus des PixButtons

2021-05-20 09:56 UTC, AndreiaPena commented on admin/app/components/organization-all-tags.hbs
> +            </PixTag>
Oui on en a déjà discuté avec Anne-Gaëlle et Youness, on partira sur des pixButton pour la suite :)

2021-05-20 10:14 UTC, octo-thlo commented
Review terminée de mon côté également !

2021-05-20 10:18 UTC, AndreiaPena commented on admin/app/components/organization-all-tags.js
> +        tagsAssignedToCurrentOrganization.push({ name: tag.name, isTagAssignedToOrganization: false });
je comprends, que proposes-tu ?

2021-05-20 10:19 UTC, AndreiaPena commented on admin/app/components/organization-all-tags.js
> +    return orderBy(tagsAssignedToCurrentOrganization, ['name']);
Done !

2021-05-20 14:36 UTC, octo-thlo approved these changes

2021-05-20 15:27 UTC, octo-topi approved these changes

2021-05-20 15:48 UTC, merged