[FEATURE] Permettre de récupérer le challengeId depuis le bouton magique (PIX-2618).
1024pix/pix pull request #3044
Opened 2021-05-27 10:14 UTC by jonasgrilleres

## :unicorn: Problème
Depuis https://github.com/1024pix/pix/pull/3020, on n'indique plus les ids des challenges dans l'URL. Le bouton magique ne fonctionne plus.

## :robot: Solution
Depuis https://github.com/1024pix/pix/pull/3023, on sauvegarde l'id du dernier challenge dans la table `assessments`. On récupère l'id du challenge à partir de l'assessment en cours.

## :rainbow: Remarques
Rajouter un mécanisme d'authentification sur l'addon bouton magique ?

## :100: Pour tester
Utiliser `curl` pour voir si la route retourne le bon `challengeId`.

2021-05-27 10:20 UTC, pix-service commented
I'm deploying this PR to these urls:

- App: https://app-pr3044.review.pix.fr
- Orga: https://orga-pr3044.review.pix.fr
- Certif: https://certif-pr3044.review.pix.fr
- Admin: https://admin-pr3044.review.pix.fr
- API: https://api-pr3044.review.pix.fr/api/

 Please check it out!

2021-05-27 12:24 UTC, francois2metz commented on api/lib/application/assessments/assessment-controller.js
> +  async getLastChallengeId(request, h) {
Je propose de le nommer `getCurrentChallengeId`.

2021-05-27 14:46 UTC, jonasgrilleres commented on api/lib/application/assessments/assessment-controller.js
> +  async getLastChallengeId(request, h) {
> Je propose de le nommer `getCurrentChallengeId`.
C'est naturellement c'est ce qui nous est venus, mais on s'est finalement calés sur le nom de la colonne dans la table `assessments`

2021-05-31 07:43 UTC, VincentHardouin commented on api/lib/application/assessments/assessment-controller.js
> +    const { lastChallengeId } = await assessmentRepository.get(assessmentId);
Il me semble que l'[ADR](https://github.com/1024pix/pix/blob/dev/docs/adr/0020-caractere-obligatoire-use-case.md) impose de créer dans tous les cas un fichier d'use-case.

2021-05-31 07:44 UTC, francois2metz commented on api/lib/application/assessments/assessment-controller.js
> +  async getLastChallengeId(request, h) {
ah effectivement. Un peu dommage mais ca fait sens.

2021-05-31 12:44 UTC, MelanieMEB requested changes

2021-05-31 12:44 UTC, MelanieMEB commented on api/tests/acceptance/application/assessments/assessment-controller-get-last-challenge-id_test.js
>      it('should return 200 HTTP status code', async () => {
J'ajouterais un test pour vérifier le code d'erreur en cas de demande d'un assessment qui n'est pas le sien

2021-05-31 13:34 UTC, sbedeau reviewed
Vu une première fois, RAS pour le moment. 
J'attends le merge du bugfix pour finir ma revue

2021-05-31 15:40 UTC, jonathanperret commented on api/lib/application/assessments/index.js
> +        auth: false,
**suggestion**: exiger un compte avec le droit pixmaster pour obtenir cette info.

2021-06-01 10:06 UTC, jonasgrilleres commented on api/lib/domain/usecases/get-last-challenge-id-from-assessment-id.js
> +  return assessment;
retourner directement l'id du challenge

2021-06-02 11:49 UTC, francois2metz commented on api/lib/application/assessments/index.js
> +          method: securityPreHandlers.checkHasPixAutoAnswerApiKey,
Pour info ce endpoint va être utilisé par au moins 2 extensions, auto-answer et pix-editor. Je proposerais bien un nom plus générique, mais pas trop d'idées :(

2021-06-02 12:19 UTC, celineung commented on api/lib/application/assessments/index.js
> +        auth: false,
Pour avoir le droit pixmaster, il faudra l'attribuer à l'utilisateur, ce qui est plutôt embêtant car on utilise le plugin sur des environnements différents et des users différents 😕
Nous avons opté pour avoir une variable d'environnement PIX_AUTO_ANSWER_API_KEY qu'il faudra passer dans le header `Authorization` de la requête.

2021-06-02 12:20 UTC, celineung commented on api/lib/application/assessments/index.js
> +          method: securityPreHandlers.checkHasPixAutoAnswerApiKey,
```suggestion
          method: securityPreHandlers.checkHasReadOnlyPixApiKey,
```
?

2021-06-02 12:30 UTC, francois2metz commented on api/lib/application/assessments/index.js
> +          method: securityPreHandlers.checkHasPixAutoAnswerApiKey,
Un peu trop générique pour le coup. Je pencherais pour quelque chose autour de quelque chose de privé/restreinte. `checkHasPrivateApiKey` ?

2021-06-02 16:05 UTC, celineung commented on api/lib/config.js
> +    pixAutoAnswer: {
Penser à renommer la clé pour avoir un nom plus générique

2021-06-02 16:18 UTC, jonathanperret commented on api/lib/application/assessments/index.js
> +        auth: false,
C'est quand même pas terrible comme pratique parce que ça veut dire que le seul moyen de révoquer l'accès d'un utilisateur sera de modifier cette clé secrète, ce qui impactera tous les utilisateurs de la fonctionnalité d'auto-réponse.

Cette fonctionnalité me paraît suffisamment sensible pour mériter une gestion d'habilitations un peu sérieuse…

2021-06-02 16:18 UTC, jonathanperret commented on api/lib/config.js
> +    pixAutoAnswer: {
Qu'est-ce qui serait un nom générique ? Et pourquoi faut-il renommer la clé ?

2021-06-02 16:23 UTC, jonathanperret commented
J'ai un petit doute sur le principe de mettre en place une API sécurisée pour récupérer l'info qui était précédemment utilisé par l'extension d'auto-réponse (le `challengeId`), pour ensuite aller interroger le LCMS pour obtenir la bonne réponse. À partir du moment où on a un _endpoint_ API sécurisé réservé aux gens qui ont le droit d'utiliser l'auto-réponse, pourquoi ne pas directement renvoyer la bonne réponse depuis cet _endpoint_ ? Ceci simplifierait largement l'extension d'auto-réponse qui n'aurait plus besoin d'aller se connecter au LCMS (et on éviterait ainsi d'avoir à donner un accès au LCMS à des gens juste pour qu'ils puissent utiliser l'auto-réponse).

2021-06-03 08:08 UTC, MelanieMEB requested changes

2021-06-03 08:08 UTC, MelanieMEB commented on api/lib/application/assessments/index.js
> +        auth: false,
Dans les deux cas, je laisserais quand même l'auth à true.
Certes, mettre en PixMaster est peut être compliqué, surtout quand on test certains cas users, mais en total déconnexion, c'est un cas que l'on voit moins.

2021-06-03 08:08 UTC, MelanieMEB commented on api/lib/domain/usecases/get-challenge-answer-for-pix-button.js
> +  const assessment = await assessmentRepository.get(assessmentId);
En obligeant à la connexion, j'ajouterais une ligne pour vérifier que le userId connecté est celui de l'assessment, pour éviter qu'on puisse trop regarder ceux des autres.

2021-06-03 08:08 UTC, MelanieMEB commented on api/lib/domain/usecases/get-last-challenge-id-from-assessment-id.js
> +  const assessment = await assessmentRepository.get(assessmentId);
En obligeant à la connexion, j'ajouterais une ligne pour vérifier que le userId connecté est celui de l'assessment, pour éviter qu'on puisse trop regarder ceux des autres.

2021-06-03 08:08 UTC, MelanieMEB commented on api/lib/domain/usecases/get-last-challenge-id.js
> +  const { lastChallengeId } = await assessmentRepository.get(assessmentId);
En obligeant à la connexion, j'ajouterais une ligne pour vérifier que le userId connecté est celui de l'assessment, pour éviter qu'on puisse trop regarder ceux des autres.

2021-06-03 08:08 UTC, MelanieMEB commented on api/lib/domain/usecases/get-last-challenge-id.js
> +  const { lastChallengeId } = await assessmentRepository.get(assessmentId);
Ce usecase n'est plus utilisé si je ne me trompe pas

2021-06-03 08:34 UTC, celineung commented
> À partir du moment où on a un _endpoint_ API sécurisé réservé aux gens qui ont le droit d'utiliser l'auto-réponse, pourquoi ne pas directement renvoyer la bonne réponse depuis cet _endpoint_ ?

@jonathanperret oui nous avons changé pour cette stratégie en cours de route.
Un nouveau endpoint `/api/assessments/{id}/challenge-answer-for-pix-button` est apparu pour ne récupérer que la solution afin que le bouton magique n'ait pas à requêter LCMS.

Nous avons laissé le endpoint `/api/assessments/{id}/last-challenge-id` car nous en aurons finalement besoin pour l'addon qui ouvre pix-editor.

C'est devenu pas mal le bazar ici, nous pensons à découper la PR en deux.

2021-06-03 09:15 UTC, celineung commented on api/lib/config.js
> +    pixAutoAnswer: {
Cette clé est supprimée.
Nous avons modifié l'authent: chacun se connecte depuis l'extension avec son compte Pix Master login/mdp

2021-06-03 09:43 UTC, alexandrecoin commented on api/lib/domain/usecases/get-last-challenge-id.js
> +  const { lastChallengeId } = await assessmentRepository.get(assessmentId);
Ce usecase est utilisé par le plugin pix-editor.

2021-06-03 10:08 UTC, sbedeau requested changes

2021-06-03 10:08 UTC, ghost commented on api/lib/application/assessments/index.js
> +        handler: assessmentController.getChallengeSolutionForPixButton,
**suggestion:** Utiliser un nommage similaire entre la route et le usecase

```suggestion
        handler: assessmentController.getChallengeSolutionForPixAutoAnswer,
```

2021-06-03 10:08 UTC, sbedeau commented on api/lib/application/security-pre-handlers.js
> +function _replyWithForbiddenError(h) {
**suggestion:** L'ancien nommage me semblait plus pertinent dans le sens où "on rencontre un problème à l'authentification donc on envoie une erreur"

Le nommage actuel m'évoque d'avantage : "on rencontre un problème à l'interdiction donc on envoie une erreur" 

ou alors faire en sorte que le nommage suive le title de l'erreur JSON API
```suggestion
function _replyWithForbiddenAccessError(h) {
```

2021-06-03 10:08 UTC, sbedeau commented on api/lib/application/security-pre-handlers.js
> +    detail: 'Insufficient permissions.',
**question:** Pourquoi enlever missing ?

2021-06-03 10:08 UTC, sbedeau commented on api/lib/infrastructure/repositories/challenge-repository.js
> +    return challenge.solution;
**question:** Est-ce qu'il ne faut pas exploiter un domain object plutôt que la datasource en brut ?

2021-06-03 10:08 UTC, sbedeau commented on api/tests/acceptance/application/assessments/assessment-controller-get-challenge-answer-for-pix-button_test.js
> +describe('Acceptance | API | assessment-controller-get-challenge-answer-for-pix-button', () => {
```suggestion
describe('Acceptance | API | assessment-controller-get-challenge-answer-for-pix-auto-answer', () => {
```

2021-06-03 10:08 UTC, sbedeau commented on api/tests/acceptance/application/security-pre-handlers_test.js
> +      detail: 'Insufficient permissions.',
**question:** Pourquoi enlever missing ?

2021-06-03 10:08 UTC, sbedeau commented on api/tests/acceptance/application/assessments/assessment-controller-get-challenge-answer-for-pix-button_test.js
> +  describe('GET /api/assessments/:id/challenge-answer-for-pix-auto-answer', () => {
**suggestion:** Ajouter un test qui check l'erreur d'authentification en cas de user non pix master

2021-06-03 12:19 UTC, celineung commented on api/lib/application/security-pre-handlers.js
> +function _replyWithForbiddenError(h) {
Le code 403 correspond à une erreur Forbidden, d'où le renommage.
On modifie pour `_replyWithForbiddenAccessError` pour rendre l'intention plus clair.

2021-06-03 12:31 UTC, celineung commented on api/lib/infrastructure/repositories/challenge-repository.js
> +    return challenge.solution;
Nous n'avons pas compris: est-ce que tu proposes de retourner un objet `challenge` et de récupérer sa solution, ou bien le problème est que l'on fasse `challengeDatasource.get(id)` ?

2021-06-03 13:01 UTC, celineung commented on api/lib/infrastructure/repositories/challenge-repository.js
> +    return challenge.solution;
Oui, on devrait renvoyer un challenge à la fin de cette fonction.
Mais on remarque que dans d'autres repo, cette convention n'est pas toujours suivie.
Un débat est en cours sur ce qui est attndu en sorti de repo. En attendant, nous laissons cette fonction.

2021-06-03 14:18 UTC, sbedeau commented on api/lib/application/security-pre-handlers.js
> +function _replyWithForbiddenError(h) {
Du coup il faut changer le title

2021-06-03 14:25 UTC, MelanieMEB approved these changes

2021-06-03 14:41 UTC, sbedeau commented on api/lib/application/security-pre-handlers.js
> +function _replyWithForbiddenError(h) {
**suggestion:** `_replyForbiddenError`

2021-06-04 14:59 UTC, celineung commented on api/lib/application/assessments/assessment-controller.js
> +    const answer = await usecases.getChallengeForPixAutoAnswer({ assessmentId });
```suggestion
    const challenge = await usecases.getChallengeForPixAutoAnswer({ assessmentId });
```

2021-06-04 15:04 UTC, celineung approved these changes

2021-06-04 15:15 UTC, sbedeau approved these changes

2021-06-04 15:24 UTC, merged