[TECH] Mettre à jours les dépendances de e2e
1024pix/pix pull request #3047
Opened 2021-05-28 10:13 UTC by ajoanny

## :unicorn: Problème
DependaBot remonte des alertes de sécurités sur des dépendances qui ne sont pas a jours

## :robot: Solution
Mettre a jours les dépendances

## :rainbow: Remarques
> _Des infos supplémentaires, trucs et astuces ?_

## :100: Pour tester
> _Les instructions pour reproduire le problème, les profils de test, le parcours spécifique à utiliser, etc._

2021-05-28 10:17 UTC, pix-service commented
I'm deploying this PR to these urls:

- App: https://app-pr3047.review.pix.fr
- Orga: https://orga-pr3047.review.pix.fr
- Certif: https://certif-pr3047.review.pix.fr
- Admin: https://admin-pr3047.review.pix.fr
- API: https://api-pr3047.review.pix.fr/api/

 Please check it out!

2021-05-31 08:12 UTC, HEYGUL approved these changes

2021-05-31 09:00 UTC, sbedeau requested changes

2021-05-31 09:00 UTC, sbedeau commented on high-level-tests/test-algo/package.json
> +    "lodash": "^4.17.21",
**question:** Pourquoi est-ce qu'on a besoin d'ajouter lodash ?

2021-06-02 07:23 UTC, francois2metz commented on high-level-tests/test-algo/package.json
> +    "lodash": "^4.17.21",
Le fichier `algo.js` en a besoin. Il était installé par une autre dépendance donc le problème n'a pas été détecté.

2021-06-02 07:23 UTC, francois2metz approved these changes
:purple_heart: :yellow_heart: :green_heart: :blue_heart: LGTM  :blue_heart: :green_heart: :yellow_heart: :purple_heart:

2021-06-02 07:42 UTC, VincentHardouin approved these changes
Je pense qu'il va juste falloir enlever le commit avec la montée de version de redis, cela a été embarqué sur : https://github.com/1024pix/pix/pull/3051

2021-06-07 07:24 UTC, alexandrecoin approved these changes

2021-06-08 16:09 UTC, octo-topi commented on high-level-tests/test-algo/package.json
> +    "lodash": "^4.17.21",
@sbedeau c'est bon pour toi, je peux résoudre la conversdation ?

2021-06-08 16:09 UTC, octo-topi commented
> Je pense qu'il va juste falloir enlever le commit avec la montée de version de redis, cela a été embarqué sur : #3051

Je prends avec @P-Jeremy

2021-06-09 10:59 UTC, sbedeau commented on high-level-tests/test-algo/package.json
> +    "lodash": "^4.17.21",
Moyen convaincu mais ok

2021-06-09 10:59 UTC, sbedeau approved these changes

2021-06-09 12:29 UTC, merged