[FEATURE] Détecter lorsque l'utilisateur perd le focus de l'onglet actif (PIX-2616).
1024pix/pix pull request #3088
Opened 2021-06-10 08:45 UTC by celineung

## :unicorn: Problème
Les épreuves focus sont des types d'épreuves où l'utilisateur ne devrait pas quitter la plateforme Pix pour aller chercher de l'information sur internet.
Pour ce type d'épreuve, nous avons besoin de détecter si l'utilisateur n'a plus le focus sur le site de Pix.

## :robot: Solution
Nous utilisons un `setInterval` pour vérifier constamment à l'aide de la méthode `document.hasFocus()` si l'utilisateur a toujours le focus sur Pix.

## :rainbow: Remarques
Nous avons testé avec [Page Visibility API](https://developer.mozilla.org/fr/docs/Web/API/Page_Visibility_API), mais la perte de focus n'était pas dectecté lorsue l'on mettait une autre application en premier plan.

## :100: Pour tester
Aller sur la RA et ouvrir la console.
Vérifier que l'on log bien dans la console si l'utilisateur perd le focus.

2021-06-10 08:50 UTC, pix-service commented
I'm deploying this PR to these urls:

- App: https://app-pr3088.review.pix.fr
- Orga: https://orga-pr3088.review.pix.fr
- Certif: https://certif-pr3088.review.pix.fr
- Admin: https://admin-pr3088.review.pix.fr
- API: https://api-pr3088.review.pix.fr/api/

 Please check it out!

2021-06-10 13:22 UTC, HEYGUL commented on mon-pix/app/components/challenge-item-generic.js
> +      console.log('user lose focus');
```suggestion
      console.log('user lost focus');
```

2021-06-10 13:22 UTC, HEYGUL commented on mon-pix/app/components/challenge-item-generic.js
> +      console.log('user lose focus');
est-ce qu'on veut envoyer des `console.log` en prod ?

2021-06-10 13:23 UTC, sbedeau requested changes

2021-06-10 13:23 UTC, sbedeau commented on mon-pix/app/controllers/assessments/challenge.js
> +
**question:** Où est-ce qu'on utilise cette action ?

2021-06-10 13:23 UTC, sbedeau commented on mon-pix/app/components/challenge-item-generic.js
> +  checkFocus() {
**suggestion:** 
```suggestion
  verifyUserIsStillFocusingOnPage() {
```

2021-06-10 13:23 UTC, sbedeau commented on api/lib/domain/models/Challenge.js
> +    this.focusable = focusable;
**chipotage:** On a appris que focusable = focalisable et on a utilisé focalisé ce qui donnerait focused

```suggestion
    this.focused = focused;
```

2021-06-10 13:36 UTC, jonasgrilleres commented on mon-pix/app/templates/components/challenge-item-qroc.hbs
> +<article id="test-focus" class="challenge-item"
On se sert de cet id ?

2021-06-11 08:45 UTC, celineung commented on mon-pix/app/components/challenge-item-generic.js
> +      console.log('user lose focus');
Il n'y a pas encore d'épeuves focus en prod.
L'objectif de cette première étape est juste de détecter la perte de focus. Ce console.log sera viré dès le prochain ticket.

2021-06-11 08:48 UTC, celineung commented on api/lib/domain/models/Challenge.js
> +    this.focusable = focusable;
J'ai pris en compte la modif, par contre côté repo et mapping depuis LCMS, on est forcé d'avoir du:
```
focused: challengeDataObject.focusable
```
Il faudrait renommer côté LCMS

2021-06-14 08:14 UTC, francois2metz approved these changes
:rose: :hibiscus: :white_flower: :wilted_flower:  :tulip: :sunflower: :cherry_blossom:  LGTM :cherry_blossom: :sunflower:  :tulip: :wilted_flower: :white_flower: :hibiscus: :rose:

2021-06-14 08:28 UTC, HEYGUL approved these changes

2021-06-14 08:35 UTC, alexandrecoin approved these changes

2021-06-14 09:28 UTC, sbedeau approved these changes

2021-06-14 09:35 UTC, merged