[BUGFIX] Suppression de la barre de défilement horizontal sur la page compétences (PIX-2726).
1024pix/pix pull request #3100
Opened 2021-06-14 14:18 UTC by alexandrecoin

## :unicorn: Problème

Nous avons remarqué depuis quelques temps l'apparition d'une barre de défilement horizontal sur la page compétences au format Desktop pour les compétences de `communication` et de `création de contenu`.

<img width="960" alt="Capture d’écran 2021-06-14 à 16 15 50" src="https://user-images.githubusercontent.com/36371437/121906912-de316900-cd2b-11eb-964f-7d5d1ae9eb32.png">

## :robot: Solution

Nous ajoutons la propriété `overflow: visible` (valeur par défaut) à partir du format `large-screen` afin de conserver la barre de défilement au format tablette et la faire disparaitre à partir d'une taille d'écran supérieure.

<img width="954" alt="Capture d’écran 2021-06-14 à 16 16 55" src="https://user-images.githubusercontent.com/36371437/121907018-f2756600-cd2b-11eb-86fa-de60cb8920d7.png">

## :rainbow: Remarques

N/A

## :100: Pour tester

Aller sur la page compétences et constater de la disparition de la barre de défilement horizontale sur les compétences de `communication` et de `création de contenu`

2021-06-14 14:23 UTC, pix-service commented
I'm deploying this PR to these urls:

- App: https://app-pr3100.review.pix.fr
- Orga: https://orga-pr3100.review.pix.fr
- Certif: https://certif-pr3100.review.pix.fr
- Admin: https://admin-pr3100.review.pix.fr
- API: https://api-pr3100.review.pix.fr/api/

 Please check it out!

2021-06-14 14:39 UTC, VincentHardouin approved these changes

2021-06-14 14:54 UTC, sbedeau requested changes
réflexion: je pense qu'on traite ici davantage la conséquence du problème que sa cause. Est-ce qu'on sait pourquoi ce problème est apparu ?

2021-06-14 15:27 UTC, alexandrecoin commented
> **réflexion (bloquant):** je pense qu'on traite ici davantage la conséquence du problème que sa cause. Est-ce qu'on sait pourquoi ce problème est apparu ?

Je suis remonté dans le CHANGELOG de Pix jusqu'en novembre 2020 (là où le défilement n'était clairement pas présent sur la page), pour constater que cette barre horizontale est toujours présente en local.
J'en déduis une mise à jour des navigateurs ? 🤔

2021-06-14 15:31 UTC, sbedeau commented
> > **réflexion (bloquant):** je pense qu'on traite ici davantage la conséquence du problème que sa cause. Est-ce qu'on sait pourquoi ce problème est apparu ?
> 
> Je suis remonté dans le CHANGELOG de Pix jusqu'en novembre 2020 (là où le défilement n'était clairement pas présent sur la page), pour constater que cette barre horizontale est toujours présente en local.
> J'en déduis une mise à jour des navigateurs ? 🤔

Intéressant, c'est possible 🤔
De mon côté je suspecte que ça soit lié au déséquilibre des gouttières. WDYT? 
<img width="1001" alt="Screenshot 2021-06-14 at 16 53 04" src="https://user-images.githubusercontent.com/46371288/121918438-5309a080-cd36-11eb-84b1-3f33d59d0feb.png">

2021-06-14 15:37 UTC, alexandrecoin commented
> > > **réflexion (bloquant):** je pense qu'on traite ici davantage la conséquence du problème que sa cause. Est-ce qu'on sait pourquoi ce problème est apparu ?
> > 
> > 
> > Je suis remonté dans le CHANGELOG de Pix jusqu'en novembre 2020 (là où le défilement n'était clairement pas présent sur la page), pour constater que cette barre horizontale est toujours présente en local.
> > J'en déduis une mise à jour des navigateurs ? 🤔
> 
> Intéressant, c'est possible 🤔
> De mon côté je suspecte que ça soit lié au déséquilibre des gouttières. WDYT?

Je l'ai remarqué aussi, et je pense effectivement que cela a pu avoir une influence si MAJ des navigateurs il y a eu.

2021-06-14 15:50 UTC, sbedeau commented
> > > > **réflexion (bloquant):** je pense qu'on traite ici davantage la conséquence du problème que sa cause. Est-ce qu'on sait pourquoi ce problème est apparu ?
> > > 
> > > 
> > > Je suis remonté dans le CHANGELOG de Pix jusqu'en novembre 2020 (là où le défilement n'était clairement pas présent sur la page), pour constater que cette barre horizontale est toujours présente en local.
> > > J'en déduis une mise à jour des navigateurs ? 🤔
> > 
> > 
> > Intéressant, c'est possible 🤔
> > De mon côté je suspecte que ça soit lié au déséquilibre des gouttières. WDYT?
> 
> Je l'ai remarqué aussi, et je pense effectivement que cela a pu avoir une influence si MAJ des navigateurs il y a eu.
> Même si en scrollant, on remarque que la taille des gouttières est identiques de part et d'autre de la première et dernière carte de la rangée.
> S'il y a un problème, je dirais qu'il s'agit plutôt de l'écartement entre les cartes trop large pour la largeur donnée.

suggestion (si-mineure): Ça me semble être une démarche de résolution plus durable. Si c'est trop galère on garde ce qu'on a là mais il faudra recentrer (ça se voit un peu)

2021-06-14 16:01 UTC, bpetetot commented
J'ai jeté un oeil et il semble avoir un problème au niveau de la largeur max du conteneur par rapport à la largeur de chaque carte.

Le conteneur principal a une `max-width: 980px` avec un `padding` de `30px` de chaque côté.
Soit un contenu qui peut avoir une largeur maximum de `920px`

```
.profile__panel {
    padding-left: 30px;
    padding-right: 30px;
}

@media (min-width: 768px)
.rounded-panel--over-background-banner {
  max-width 980px
}
```

Or les cartes ont une largeur fixe de `212px` avec une margin de `10px` de chaque côté, soit pour 4 cartes:
`212*4px + 8*10px = 928px`

```
.rounded-panel-body__competence-card {
    margin: 16px 10px;
    width: auto;
}

.competence-card {
    flex-direction: column;
    width: 212px;
    height: 310px;
}
```

Donc on a un contenu plus large de `8px` (`928px`) par rapport au conteneur parent `920px`. Je pense que c'est pour ça qu'on a le scroll horizontal qui apparaît.

2021-06-14 16:04 UTC, alexandrecoin commented
Quelle solution vous semble la plus pertinente du coup ? 

- Augmentation de la largeur du conteneur principal (et changements dans le header de façon à réaligner l'ensemble des éléments)
- Réduction des marges latérales de la première et de la dernière carte de manière à fitter dans le conteneur principal, ne changeant pas l'alignement existant.
- Autre ?

2021-06-14 16:10 UTC, sbedeau commented
> Quelle solution vous semble la plus pertinente du coup ?
> 
>     * Augmentation de la largeur du conteneur principal (et changements dans le header de façon à réaligner l'ensemble des éléments)
> 
>     * Réduction des marges latérales de la première et de la dernière carte de manière à fitter dans le conteneur principal, ne changeant pas l'alignement existant. (J'opte pour celle-ci)
> 
>     * Autre ?

https://media.giphy.com/media/ZP7FB58dcRKX6/giphy.gif

La B me semble bien

2021-06-14 16:11 UTC, sbedeau commented
> Quelle solution vous semble la plus pertinente du coup ?
> 
>     * Augmentation de la largeur du conteneur principal (et changements dans le header de façon à réaligner l'ensemble des éléments)
> 
>     * Réduction des marges latérales de la première et de la dernière carte de manière à fitter dans le conteneur principal, ne changeant pas l'alignement existant. (J'opte pour celle-ci)
> 
>     * Autre ?

La B me semble bien

2021-06-15 07:58 UTC, sbedeau approved these changes

2021-06-15 09:08 UTC, merged