[FEATURE] Modifier bouton vert de l'écran intermédiaire (PIX-2701).
1024pix/pix pull request #3119
Opened 2021-06-18 12:54 UTC by celineung

## :unicorn: Problème
Le bouton est carré alors qu'il devrait être ovale selon pix UI

## :robot: Solution
- Mettre à jour la version de pix-ui utilisée
- Utiliser PixButton sur les écran intermédiaires des épreuves focus et timée

## :rainbow: Remarques
> _Des infos supplémentaires, trucs et astuces ?_

## :100: Pour tester
Se rendre sur une épreuve timée (ex: recqBuazz0O9mhm5e) et constater que le bouton vert est maintenant rond au lieu de carré.

2021-06-18 12:59 UTC, pix-service commented
I'm deploying this PR to these urls:

- App: https://app-pr3119.review.pix.fr
- Orga: https://orga-pr3119.review.pix.fr
- Certif: https://certif-pr3119.review.pix.fr
- Admin: https://admin-pr3119.review.pix.fr
- API: https://api-pr3119.review.pix.fr/api/

 Please check it out!

2021-06-18 15:24 UTC, sbedeau requested changes
Ok pour moi fonctionnellement.

**réflexion :** Mutualiser le scss des instruction de challenge entre timé et focused (à voir dans la PR parente #3117)

**réflexion:** Le focus du bouton créé une différence très visible avec le focus des boutons (Je passe / Je valide / etc.) dans le challenge en lui même. Est-ce qu'on ne devrait pas les modifier eux aussi ?

2021-06-18 15:24 UTC, sbedeau commented on mon-pix/package.json
> +    "pix-ui": "git://github.com/1024pix/pix-ui.git#v5.2.0",
**problème (bloquant):** Pix-UI est déjà en 5.2.0 sur dev :)

**suggestion:** Rebase la branche parente sur dev

2021-06-21 09:48 UTC, alexandrecoin approved these changes

2021-06-21 09:52 UTC, celineung commented
> Le focus du bouton créé une différence très visible avec le focus des boutons (Je passe / Je valide / etc.) dans le challenge en lui même. Est-ce qu'on ne devrait pas les modifier eux aussi ?

Je propose de le faire dans une autre PR

2021-06-21 16:05 UTC, jonasgrilleres commented on mon-pix/app/templates/components/challenge-item-qroc.hbs
> +    {{#unless this.hasUserConfirmedFocusWarning}}
Le combo maléfique 🤯

2021-06-21 16:06 UTC, jonasgrilleres commented on mon-pix/app/templates/components/challenge-item-qroc.hbs
> +      <FocusChallengeInstructions @hasUserConfirmedWarning={{this.setUserFocusChallengeConfirmation}} />
On peut pas injecter la bonne string dans `ChallengeInstructions` en fonction de si c'est un `isTimedChallenge` ou `isFocusedChallenge` ?

2021-06-24 08:39 UTC, celineung commented
@jonasgrilleres ce sont des retours sur #3117.
Cette branche se base dessus, elle n'était pas à jour quand tu as fait la revue ^^

2021-06-24 12:42 UTC, MelanieMEB approved these changes

2021-06-24 12:43 UTC, MelanieMEB commented
> Ok pour moi fonctionnellement.
> 
> **réflexion :** Mutualiser le scss des instruction de challenge entre timé et focused (à voir dans la PR parente #3117)
> 
> **réflexion:** Le focus du bouton créé une différence très visible avec le focus des boutons (Je passe / Je valide / etc.) dans le challenge en lui même. Est-ce qu'on ne devrait pas les modifier eux aussi ?

Les boutons ont changés dans une dernière version, c'est une repasse complète qu'il faudrait faire :)

2021-06-24 12:51 UTC, sbedeau approved these changes

2021-06-24 12:54 UTC, jonasgrilleres approved these changes

2021-06-24 13:01 UTC, merged