[BUGFIX/CLEANUP] Déplacer la détermination du numéro de question dans back-end
1024pix/pix pull request #3147
Opened 2021-06-30 12:12 UTC by EGI-OCTO

## :unicorn: Problème
Il existe des situation où le numéro de la question affichée dans le front au candidat de certification n'est pas le même que celui qui apparait dans Pix Admin. Par le passé, cette incohérence était compenser par les membres du pôle certif. Depuis peu, les signalements du surveillant sont en partie traité automatiquement, ce qui ne fonctionne pas avec l'incohérence du numéro de question. 

Aujourd'hui, la numéro de la question est calculé par le front (numéro de question = nb d'answers ayant un id, présentes dans le store)

## :robot: Solution
Déplacer la détermination de question dans le backend pour uniformiser cette valeur.

Faire émerger/rendre explicite la différence entre la notion d'épreuve (= consignes + contenu) et de question (= une épreuve ayant une position donnée dans un test donné). Le back-end retourne donc plus l'épreuve suivante mais la question suivante.

Dans le cadre de la certif : associer un index dans certification-challenges.
Dans le cadre des autres tests : TO DO, à voir avec l'équipe xp d'éval. En particulier il existe des test dans la question suivante est déterminée à la volée, ceci n'empêche pas qu'elle soit aussi numérotée à la volée.

## :rainbow: Remarques
Cette PR représente une proposition pour corriger le comportement du compteur d'épreuve en certif et poser les bases d'une approche orientée "question" plutôt qu' "épreuve" qui serait à étendre aux autres types de tests (positionnement, démo, campagne, preview, ...). 

## :100: Pour tester
Lancer différents tests (positionnement, démo, campagne, preview, ...).

2021-06-30 12:18 UTC, pix-service commented
I'm deploying this PR to these urls:

- App (.fr): https://app-pr3147.review.pix.fr
- App (.org): https://app-pr3147.review.pix.org
- Orga: https://orga-pr3147.review.pix.fr
- Certif: https://certif-pr3147.review.pix.fr
- Admin: https://admin-pr3147.review.pix.fr
- API: https://api-pr3147.review.pix.fr/api/

 Please check it out!

2021-07-05 10:04 UTC, aceol approved these changes

2021-07-05 10:04 UTC, aceol commented on api/lib/infrastructure/repositories/certification-course-repository.js
> +    const savedChallenges = await certificationChallengeRepository.saveWithOrder({ certificationCourseId: savedCertificationCourseDTO.id, certificationChallenges: certificationCourse.challenges, doma
_Question:_ Comment est gérée cette notion d'ordre? On ne le voit pas ici

2021-07-05 10:04 UTC, aceol commented on api/lib/domain/services/certification-result-service.js
>      return result;
Une raison pour muter result au fur et à mesure plutôt que de le créer à la fin?

2021-07-05 10:04 UTC, aceol commented on api/lib/domain/services/certification-result-service.js
> +  // userService.getPlacementProfile() + filter level > 0 => avec allCompetence (bug)
Est-ce d'actualité? Pas certain de comprendre

2021-07-05 10:04 UTC, aceol commented on api/lib/domain/services/certification-result-service.js
> +  // userService.getPlacementProfile() + filter level > 0 => avec allCompetence (bug)
Pas certains que les commentaires dans ce fichier soit pertinent. Sont-ils voués à disparaitre?

2021-07-05 10:04 UTC, aceol commented on api/lib/domain/models/CertificationAssessment.js
> +    return _.find(this._certificationChallenges, { challengeId }) || null;
_nitpick:_ est-ce que le `|| null` apporte quelque chose?

2021-07-05 10:04 UTC, aceol commented on mon-pix/app/components/progress-bar.js
> +    }
```suggestion
    return this.args.challenge.index 
        ?? progressInAssessment.getCurrentStepNumber(this.args.assessment, this.args.answerId);
   
```

2021-07-05 10:04 UTC, aceol commented on api/lib/domain/services/certification-result-service.js
> +      skill: certificationChallengeRelatedToAnswer.associatedSkillName || '',
Privillegier `??` plutot que `||` pour conserver le 0 (même si ca ne devrait pas etre possible ici)
const toto = 0;
console.log(toto || 'nope') //=> nope
console.log(toto ?? 'nope') //=> 0

```suggestion
      competence: competenceValidatedByCertifChallenge.index ?? '',
      skill: certificationChallengeRelatedToAnswer.associatedSkillName ?? '',
```

2021-07-05 10:05 UTC, aceol commented on api/lib/infrastructure/repositories/certification-course-repository.js
> +    const savedChallenges = await certificationChallengeRepository.saveWithOrder({ certificationCourseId: savedCertificationCourseDTO.id, certificationChallenges: certificationCourse.challenges, doma
Il semble que ce soit fait au commit d'après

2021-07-06 07:41 UTC, MelanieMEB requested changes
Voici mes points négatifs : 
- La route getNextChallenge se retrouve à renvoyer 2 types d'objet
- Le controller devient par conséquent assez lourd
- Je m'interroge encore sur la notion de Question, et je ne sais pas si cette notion serait utile dans l'idée qui avait été proposé coté XP Eval que l'Assessment porte les informations de son évaluation (et notamment l'état de la progress bar, etc.). Je ne sais pas si on risque de tout retirer derrière.
- Actuellement, dans cette PR, c'est coté front qu'on se retrouve avec un objet (challenge) qui pourrait ne pas être complet (ne pas avoir d'index).
- Si on voulait un objet Question sur tous les assessments, il faudrait sauvegarder aussi coté back la liste des questions qui ont été posé, ce qui n'est actuellement faisable que pour la certif.
- Globalement, cette modification "spécial certif" ne me parait pas cohérente avec l'idée qu'au sein de l'évaluation (une fois les écrans spécifiques passées), tous les assessments se comportent de la même manière. C'est peut être une idée à challenger, mais cette idée me parait encore importante.

De mon point de vue, cette PR est plus un gros refacto (qu'il faudrait appliquer partout si on choisissait cette direction, mais pas applicable partout) qu'un Cleanup/bugfix.

(après, testé fonctionnellement, ça marche)

2021-07-06 08:22 UTC, EGI-OCTO commented
> De mon point de vue, cette PR est plus un gros refacto qu'il faudrait appliquer partout

Oui, c'est comme ça qu'on l'a pensé aussi. La proposition est en effet à propager aux autres types de tests (positionnement, démo, campagne, preview, ...).  C'est pour cela que coté back, on permet de choisir un serializer en fonction du type retourné (question ou challenge), de manière à pouvoir faire ce refacto petit à petit, type de test par type de test pas pas en mode "gros refacto" big bang. 

La considération ci-dessus devrait également adresser les points suivants : 
>  * La route getNextChallenge se retrouve à renvoyer 2 types d'objet
>  * Actuellement, dans cette PR, c'est coté front qu'on se retrouve avec un objet (challenge) qui pourrait ne pas être complet (ne pas avoir d'index)

(il le sera quand tous les tests renverront des questions ayant donc un index)


Concernant ce point :
> * Si on voulait un objet Question sur tous les assessments, il faudrait sauvegarder aussi coté back la liste des questions qui ont été posé, ce qui n'est actuellement faisable que pour la certif.

Est-ce que tu dis ça par rapport au fait qu'il existe des tests pour lesquels les épreuves sont choisies au fil de l'eau ? Si oui, il est quand même possible de les numéroter au fil de l'eau également au moment de l'appel à getNext non ?

Si la proposition ci-dessus est faisable, on ne devrait pas avoir de coloration "certif" sur le déroulé d'un test.
> * Globalement, cette modification "spécial certif" ne me parait pas cohérente avec l'idée qu'au sein de l'évaluation (une fois les écrans spécifiques passées), tous les assessments se comportent de la même manière. C'est peut être une idée à challenger, mais cette idée me parait encore importante.

> * Le controller devient par conséquent assez lourd

Il n'est globalement pas beaucoup plus lourd qu'aujourd'hui, il permet simplement de choisir le serializer qui correspond au type renvoyé (challenge ou question). Ceci est voué à disparaitre, une fois l'homogénéisation finie, lorsque qu'on renverra plus que des questions (et non plus des challenges) pour tous les types de tests. Quoiqu'il en soit, il y a un travail à faire sur le controller qui fait déjà un certain nombre de choses qui relèvent de la couche métier aujourd'hui.

2021-07-06 08:31 UTC, sroccaserra commented
Salut @jonathanperret, je serais intéressé par ta vision ou tes propositions si tu en as ? On peut aussi organiser une visio à plusieurs pour éviter les ping pongs et trouver un chemin intéressant ? On est dispos ce matin par exemple.

2021-07-06 09:14 UTC, MelanieMEB commented
> Est-ce que tu dis ça par rapport au fait qu'il existe des tests pour lesquels les épreuves sont choisies au fil de l'eau ? Si oui, il est quand même possible de les numéroter au fil de l'eau également au moment de l'appel à getNext non ?

Donc à un appel à GetNext, il faudra recalculer à quel numéro de question on est, ce qui est possible en effet, mais qui ne règle pas nos bugs (d'où le fait que pour moi, cette PR n'est pas un bugfix).
S'il y a eu des soucis d'affichages des épreuves, ça a pu être lié : à des doublons de réponses (bugs à régler), à un manque de question posés, ou à une mauvaise récupération des infos en front.
Si on recalcule en back à chaque fois, on peut, mais il faut d'abord régler les autres soucis.

Dans tous les cas, ce changement est un gros changement sur tout le fonctionnement du scope XP eval et des assessments, j'attends aussi d'autres retours de l'équipe, car ce n'est pas dans la direction que nous avions voulu prendre.

2021-07-06 09:16 UTC, MelanieMEB commented
> Salut @jonathanperret, je serais intéressé par ta vision ou tes propositions si tu en as ? On peut aussi organiser une visio à plusieurs pour éviter les ping pongs et trouver un chemin intéressant ? On est dispos ce matin par exemple.

Jonathan peut en effet, comme tout dev, avoir une vision sur le sujet. Si vous faites une visio à plusieurs pour trouver un chemin, pensez à bien inclure la team xp-eval qui devra maintenir ces changements avec toutes les nouveautés à venir (et notamment la refonte totale de la progress bar (donc l'affichage du numéro de question) d'ici un mois).

2021-07-06 09:35 UTC, sroccaserra commented
Ok, dommage, ça fait un moment que je trouve que faire exister cette notion de question (différente de la notion d'épreuve) dans le code (sous la forme proposée par cette PR ou sous une autre forme) était intéressante pour Pix. Si je comprends bien tu proposes de régler le problem at hand par un autre moyen que vous avez déjà étudié et qui est plus adapté ?

2021-07-06 09:39 UTC, MelanieMEB commented
> Ok, dommage, ça fait un moment que je trouve que faire exister cette notion de question (différente de la notion d'épreuve) dans le code (sous la forme proposée par cette PR ou sous une autre forme) était intéressante pour Pix. Si je comprends bien tu proposes de régler le problem at hand par un autre moyen que vous avez déjà étudié et qui est plus adapté ?

Je ne parle pas de rejeter complètement l'idée, je dis seulement que d'autres idées avaient été abordé, et que merger cette solution demande soit de prendre celle-ci sans prendre le temps de considérer d'autres solutions, soit de tout retirer si on prend l'autre solution.
Dans tous les cas, c'est un gros sujet de choix d'archi coté XP-eval, qui n'a pas encore été creuser. Je propose juste du temps et de la réflexion, coté XP eval.

2021-07-06 13:58 UTC, celineung reviewed
@MelanieMEB si l'on suit ces modifs:
Dans le cas de la refonte de la barre de progression (ne plus afficher le numéro de question "X/5" mais un pourcentage), l'index que l'on mettrait dans l'url aurait plus de sens du coup (`assessments/{assessmentId}/challenges/{numéro de la question}`, ou même `assessments/{assessmentId}/questions/{numéro de la question}`).

2021-07-06 13:58 UTC, celineung commented on api/tests/integration/infrastructure/repositories/certification-challenge-repository_test.js
> +      const savedCertificationChallenges = await certificationChallengeRepository.saveWithOrder({ certificationCourseId, certificationChallenges: challengesToBeSaved });
**nitpick:** puisque le given when then est rendu explicite: ajouter un saut de ligne + le commentaire "//when"

2021-07-06 13:58 UTC, celineung commented on api/lib/infrastructure/repositories/certification-challenge-repository.js
> +    const dtos = certificationChallenges.map((certificationChallenge, index) => {
**question:** les `certificationChallenges` sont déjà triés ?

2021-07-06 13:58 UTC, celineung commented on api/lib/domain/services/certification-result-service.js
> +  // userService.getPlacementProfile() + filter level > 0 => avec allCompetence (bug)
**suggestion:** Il y a beaucoup de code en commun avec `_getScoreAndLevels`. Possible de factoriser ?

2021-07-06 13:58 UTC, celineung commented on api/lib/infrastructure/repositories/certification-challenge-repository.js
> +  async getNextNonAnsweredChallengeWithIndexByCourseId(assessmentId, courseId) {
```suggestion
  async getNextNonAnsweredQuestionWithIndexByCourseId(assessmentId, courseId) {
```

2021-07-22 14:31 UTC, sroccaserra commented
Proposition Team Eval :
> clore la PR et on se plonge dedans lorsqu’on doit attaquer le sujet de la refonte totale de la progress bar

2021-07-22 14:31 UTC, closed without merging