[FEAT] Ajouter l'onglet activité sur la page des campagnes d'évaluation (PIX-2664)
1024pix/pix pull request #3150
Opened 2021-07-01 12:18 UTC by xav-car

## :unicorn: Problème
La page activité n'est pas disponible autrement qu'en connaissant la route. Etant sur le point d'être fini nous souhaitons que tout le monde puisse y avoir accès 

## :robot: Solution
Rajouter un onglet sur le détail d'une campagne d'évaluation. A partir du moment ou nous avons des particpations, cet onglet devient disponible

## :rainbow: Remarques

## :100: Pour tester
Se connecter sur `pro.admin@example.net` 

Une campagne avec des participations ( vérifier la présence du lien et l'accès à la page)
Une campagne sans participations (ne pas afficher le lien)

2021-07-01 12:22 UTC, pix-service commented
I'm deploying this PR to these urls:

- App (.fr): https://app-pr3150.review.pix.fr
- App (.org): https://app-pr3150.review.pix.org
- Orga: https://orga-pr3150.review.pix.fr
- Certif: https://certif-pr3150.review.pix.fr
- Admin: https://admin-pr3150.review.pix.fr
- API: https://api-pr3150.review.pix.fr/api/

 Please check it out!

2021-07-12 07:37 UTC, bpetetot commented on orga/app/routes/authenticated/campaigns/campaign/assessment-results.js
> +>>>>>>> cd567f8ae (route orga)
Conflit non résolu ici

2021-07-12 07:39 UTC, bpetetot commented on orga/tests/acceptance/campaign-assessment-results_test.js
> +//Mirage est une souffrance
^^

2021-07-12 07:40 UTC, bpetetot commented on orga/tests/acceptance/campaign-assessment-results_test.js
> +      debugger
`debugger` à supprimer

2021-07-12 08:25 UTC, bpetetot commented
Ça serait bien de mettre le même margin autour du graphique que sur l'écran d'activité. (conserver le margin actuel entre les filtres et le tableau)

![Screenshot 2021-07-12 at 10 23 02](https://user-images.githubusercontent.com/516360/125255021-4fe4de80-e2fb-11eb-8470-16017bb6495f.png)

2021-07-13 12:50 UTC, xav-car commented on orga/app/components/routes/authenticated/campaign/report.hbs
> +        <LinkTo @route="authenticated.campaigns.campaign.assessment-results" @model={{@campaign}} class="navbar-item">
previous button ( back navigateur plutôt que activity ?)

2021-07-13 12:50 UTC, xav-car commented on orga/app/styles/components/campaign/analysis/competences.scss
> +}
eol

2021-07-13 12:50 UTC, xav-car commented on orga/app/templates/authenticated/campaigns/campaign/analysis.hbs
> +/>
eol

2021-07-13 12:50 UTC, xav-car commented on api/lib/domain/read-models/campaign-results/CampaignAssessmentParticipationResultMinimal.js
> +class CampaignAssessmentParticipationResultMinimal {
A voir pour un autre nom ? pas trop parlant ?

`CampaignAssessmentParticiaptionResult`, celui qui existe le renommer en `CampaignParticipationResultDetails` ?

2021-07-13 12:50 UTC, xav-car commented on api/lib/infrastructure/repositories/campaign-assessment-participation-result-list-repository.js
> +async function _buildCampaignAssessmentParticipationSummaries(results, targetedSkillsCount) {
changer le nom de la method ?

2021-07-13 12:50 UTC, xav-car commented on api/lib/application/campaign-participations/index.js
> +        tags: ['api', 'campaign-assessment-participation-summary'],
renommer le tag ?

2021-07-13 12:50 UTC, xav-car commented on api/lib/application/campaign-participations/index.js
> +          '- Récupération des campaign-assessment-participation-summaries par campagne',
là içi aussi

2021-07-15 15:02 UTC, KaramHaitham approved these changes

2021-07-16 08:49 UTC, ajoanny commented on api/lib/domain/read-models/campaign-results/CampaignAssessmentParticipationResultMinimal.js
> +class CampaignAssessmentParticipationResultMinimal {
J'avoue que je suis pas partant pour le `CampaignAssessmentParticiaptionResult` et le `CampaignParticipationResultDetails` je trouve qu'on apporte rien de spécial en plus par rapport au minimal.
Après j'ai pas mieux donc si vous préférez Details go Details.

2021-07-16 08:51 UTC, ajoanny commented on api/lib/domain/read-models/campaign-results/CampaignAssessmentParticipationResultMinimal.js
> +class CampaignAssessmentParticipationResultMinimal {
et avoir `CampaignAssessmentParticipation` et `CampaignAssessmentResult` ?
Je pense que c'est pas beaucoup plus parlant sur ce que c'est

2021-07-19 12:56 UTC, lisequesnel commented on high-level-tests/e2e/cypress/integration/pix-orga/campaign-management.feature
> +    Lorsque je clique sur "Activité"
**question** : c'est pas plutôt "Résultats" ?

2021-07-19 12:58 UTC, lisequesnel commented on orga/app/components/campaign/activity/participants-list.hbs
> +              </td>
**question** : cette partie est-elle accessible ? comme on est en train de corriger ça à d'autres endroits, ce serait dommage d'introduire des problèmes d'accessibilité pour les corriger plus tard

**question sous-jacente** : au final c'est quoi la bonne pratique d'accessibilité ?

2021-07-19 13:00 UTC, lisequesnel commented on orga/app/components/routes/authenticated/campaign/assessment/details.hbs
> +     @route="authenticated.campaigns.campaign.activity"
**question** : je croyais que c'était depuis la page de résultats qu'on pouvait accéder au détail et pas depuis la page d'activité. ça a changé ?

2021-07-19 13:03 UTC, lisequesnel commented on orga/app/router.js
> +        this.route('details');
**suggestion** : comme l'onglet s'appelle "Paramètres", je suggère d'écrire "/parametres" également (voire de changer le nom des fichiers aussi, si c'est plus propre, mais peut-être dans une autre PR, à voir)

2021-07-19 13:06 UTC, lisequesnel commented on orga/translations/en.json
> +        "collective-results": "Collective",
**suggestion** : c'est pas plutôt "Results" ?

2021-07-19 13:12 UTC, lisequesnel commented on orga/app/routes/authenticated/campaigns/campaign/assessment-results.js
> +  // ???????????????
un oubli ?

2021-07-19 13:22 UTC, lisequesnel commented on api/lib/infrastructure/repositories/campaign-assessment-participation-result-list-repository.js
> +function _getParticipantActivityResultList(campaignId, targetProfile, filters) {
**question** : c'est vraiment pour l'onglet "Activité" cette partie ? Ça me parait bizarre puisqu'on utilise `validatedSkillsCount`. Je dirais intuitivement que c'est plutôt pour l'onglet "Résultats".
NB : le nom du commit c'est pareil

2021-07-19 13:23 UTC, lisequesnel commented on api/lib/infrastructure/repositories/campaign-assessment-participation-result-list-repository.js
> +function _getParticipantActivityResultList(campaignId, targetProfile, filters) {
Je pense qu'avec un petit renommage ce serait plus clair (j'avoue que là, j'étais perdue 🤯)

2021-07-19 13:24 UTC, lisequesnel commented on api/lib/domain/read-models/campaign-results/CampaignAssessmentParticipationResultMinimal.js
> +class CampaignAssessmentParticipationResultMinimal {
J'ai pas compris à quoi servait ce model désolée ^^

2021-07-19 13:27 UTC, xav-car commented on orga/app/components/campaign/activity/participants-list.hbs
> +              </td>
On a vu avec Tanaguru . 

clique sur tout le `tr` ok, du moment qu'il y a un a href qui puisse t'amener sur la page aussi en navigation clavier.

2021-07-19 13:28 UTC, lisequesnel commented on api/lib/application/campaign-participations/index.js
> +      path: '/api/campaigns/{id}/shared-participations',
**question** : est-ce qu'on veut utiliser la même route pour les collectes de profils ? 
Si oui, en quoi `/api/campaigns/{id}/results` ou `/api/campaigns/{id}/participant(s)-result(s)` (je sais pas où mettre les S) est pas clair ?
Si non, est-ce qu'on va pas avoir des problèmes de nommage pour distinguer les 2 ?

2021-07-19 13:29 UTC, bpetetot commented on orga/app/components/campaign/activity/participants-list.hbs
> +              </td>
Oui c'est la pratique recommandée par l'auditeur d'a11y (j'ai plus son nom en tête ^^)
On leur a demander comment gérer l'accessibilité d'un tableau en ayant une ligne toute la ligne de cliquable. 
Leur réponse est de mettre le lien dans la première colonne ET d'avoir un évènement Javascript pour gérer le clique sur toute la ligne.

2021-07-19 13:31 UTC, xav-car commented on orga/translations/en.json
> +        "collective-results": "Collective",
ouaip ça a été corrigé dans un autre commit 😅

2021-07-19 13:33 UTC, xav-car commented on orga/app/routes/authenticated/campaigns/campaign/assessment-results.js
> +  // ???????????????
à la base on pensait que `loading `ne servait à rien. jusqu'à l'apparition des filtres et du clignotement de la page  :) ça a été supprimé dans un autre commit

2021-07-19 13:33 UTC, lisequesnel commented on api/lib/application/campaign-participations/index.js
> +          '- Récupération des campaign-assessment-participation-result-minimals par campagne',
**niptick** : je suis pas sûre qu'avoir ce détail comme doc soit très utile, par contre `Récupération des résultats partagés des participants à une campagne donnée`

2021-07-19 13:35 UTC, bpetetot commented on orga/app/components/routes/authenticated/campaign/assessment/details.hbs
> +     @route="authenticated.campaigns.campaign.activity"
Voilà ce qui a été vu avec Estelle :
"Activité" est la page par défaut.

Quand on créé une campagne, on est redirigé directement vers le "Détail" de la campagne.
Quand on va sur une campagne, on arrive *toujours* sur l'onglet "Activité" (qu'il y ait 0 ou X participations => c'est ce qui a changé)

Ensuite quand:
- Si on est sur l'onglet "Activité" et qu'on clique sur "Previous page", on revient à la liste des campagnes
- Si on est sur un des autres onglets de campagne et qu'on clique sur "Previous page", on revient sur l'onglet "Activité" (page par défaut d'une campagne)

2021-07-19 13:36 UTC, bpetetot commented on orga/app/router.js
> +        this.route('details');
Je suis d'accord et je renommerais également le nom en anglais "details" en "settings"

2021-07-19 13:37 UTC, bpetetot commented on orga/app/routes/authenticated/campaigns/campaign/assessment-results.js
> +  // ???????????????
Ahh je crois que ça a été supprimé dans un commit suivant :(

2021-07-19 13:37 UTC, lisequesnel commented on api/lib/domain/read-models/campaign-results/CampaignAssessmentParticipationResultMinimal.js
> +class CampaignAssessmentParticipationResultMinimal {
**question/suggestion** : on a vraiment besoin de ce nouveau modèle ? J'ai l'impression que l'ancien modèle `CampaignAssessmentParticipationSummary` qui était utilisé uniquement pour l'affichage de la liste des participants ne sera plus utilisé après cette PR, et donc je me dis qu'on pourrait simplement faire évoluer ce modèle

2021-07-19 13:38 UTC, lisequesnel commented on orga/app/routes/authenticated/campaigns/campaign/assessment-results.js
> +>>>>>>> cd567f8ae (route orga)
même si c'est résolu plus tard, ce serait mieux de pas faire apparaître ça dans l'historique

2021-07-19 13:39 UTC, lisequesnel commented on orga/tests/acceptance/campaign-assessment-results_test.js
> +//Mirage est une souffrance
**question** : certes, mais on veut vraiment laisser ce commentaire ici ? ^^

2021-07-19 13:40 UTC, bpetetot commented on api/lib/application/campaign-participations/index.js
> +      path: '/api/campaigns/{id}/shared-participations',
Non en effet, je pense qu'on aura 2 routes différentes, car les modèles / réponses ne seront pas les mêmes pour les campagnes d'évaluation et de collectes de profils.

On pourrait avoir : 
```
'/api/campaigns/{id}/shared-participations'
'/api/campaigns/{id}/shared-profiles'
```
ou
```
'/api/campaigns/{id}/assessment/results'
'/api/campaigns/{id}/profile/results'
```
ou autre...

2021-07-19 13:41 UTC, lisequesnel commented on orga/tests/acceptance/campaign-assessment-results_test.js
> +      debugger
**niptick** : ce serait mieux de modifier le commit pour supprimer ceci

2021-07-19 13:51 UTC, lisequesnel requested changes
Quelques remarques :
- Je pense qu'il faut rendre obsolète la route GET `api/campaigns/{id}/assessment-participations` ? (= la laisser fonctionner encore un temps mais la noter comme dépréciée, jusqu'à ce que les instances des fronts aient été updatées, puis supprimer cette route dans une PR ultérieure en monitorant son utilisation via datadog)
- La page d'un participant est accessible depuis 2 pages différentes, mais une seule option pour revenir en arrière est acceptée, je pense que ça pose problème. Ma solution : enlever le click sur la ligne dans l'onglet "Activité" (il n'y a aucune information supplémentaire)
- Le graphique de répartition des résultats par palier est toujours cliquable, mais c'est assez perturbant car rien ne se passe. Avant on changeait de page, mais ça n'est plus le cas. Peut-être dans un second temps, mais je pense qu'il faudrait réfléchir à comment le faire apparaître plus clairement. Ou peut-être que cette fonctionnalité devient inutile 🤷‍♀️ 
- BUG BLOQUANT : lorsqu'on va sur une campagne de collecte, c'est la page d'activité qui s'affiche

2021-07-19 13:53 UTC, bpetetot commented on api/lib/domain/read-models/campaign-results/CampaignAssessmentParticipationResultMinimal.js
> +class CampaignAssessmentParticipationResultMinimal {
@lisequesnel Ce modèle représente une ligne du tableau de résultat des participants (pour une campagne d'évaluation)
Tu as raison c'est le même quasiment le même `CampaignAssessmentParticipationSummary` (en plus simple).
Aujourd'hui on a conservé le endpoint actuel et le modèle lié pour le déprécié et enfin le supprimer à une MEP+1. C'est une des raisons pour lesquelles nous n'avons pas donner le même nom à ce modèle.

`CampaignAssessmentParticipationSummary` ne parlait également pas à beaucoup de monde sur l'intention du modèle, mais ça semble également le cas pour `CampaignAssessmentParticipationResultMinimal` ^^

Sinon je trouve ça bien comme nom `CampaignAssessmentParticipationResult`

2021-07-19 13:57 UTC, bpetetot commented
> Le graphique de répartition des résultats par palier est toujours cliquable, mais c'est assez perturbant car rien ne se passe. Avant on changeait de page, mais ça n'est plus le cas. Peut-être dans un second temps, mais je pense qu'il faudrait réfléchir à comment le faire apparaître plus clairement. Ou peut-être que cette fonctionnalité devient inutile 🤷‍♀️

Si tu cliques sur une ligne du graphique, il filtre le tableau du dessous en fonction du palier sélectionné

2021-07-19 14:03 UTC, lisequesnel commented on api/lib/application/campaign-participations/index.js
> +      path: '/api/campaigns/{id}/shared-participations',
`/api/campaigns/{id}/assessment-results` et `api/campaigns/{id}/profile-results` ?

2021-07-19 14:07 UTC, bpetetot commented on api/lib/application/campaign-participations/index.js
> +      path: '/api/campaigns/{id}/shared-participations',
Moi ça me va 👍

2021-07-19 14:08 UTC, lisequesnel commented
> > La page d'un participant est accessible depuis 2 pages différentes, mais une seule option pour revenir en arrière est acceptée, je pense que ça pose problème. Ma solution : enlever le click sur la ligne dans l'onglet "Activité" (il n'y a aucune information supplémentaire)
> 
> Je ne comprends pas bien ce que tu veux dire.

Lorsqu'on est sur l'onglet "Résultats" et qu'on clique sur un participant, puis qu'on clique sur la flèche de retour, on arrive sur l'onglet "Activité", je trouve ça perturbant, ça veut dire que potentiellement à chaque fois, la personne va se retaper le click sur le bon onglet + tous les filtres à remettre... Pas top.

> > Le graphique de répartition des résultats par palier est toujours cliquable, mais c'est assez perturbant car rien ne se passe. Avant on changeait de page, mais ça n'est plus le cas. Peut-être dans un second temps, mais je pense qu'il faudrait réfléchir à comment le faire apparaître plus clairement. Ou peut-être que cette fonctionnalité devient inutile 🤷‍♀️
> 
> Si tu cliques sur une ligne du graphique, il filtre le tableau du dessous en fonction du palier sélectionné

Ce que je veux dire c'est que ce n'est pas visible facilement ce filtre. Si tu le sait pas, ça se voit pas. Un idée serait de forcer le scroll vers le tableau, mais je sais pas si c'est tip top côté accessibilité

2021-07-19 14:16 UTC, bpetetot commented
> Lorsqu'on est sur l'onglet "Résultats" et qu'on clique sur un participant, puis qu'on clique sur la flèche de retour, on arrive sur l'onglet "Activité", je trouve ça perturbant, ça veut dire que potentiellement à chaque fois, la personne va se retaper le click sur le bon onglet + tous les filtres à remettre... Pas top.

Ah ok, en effet c'est pas top, une solution serait de faire simplement un "Back" navigateur (c'est possible en JS) et comme cette page ne peut pas être atteinte autre que par un clique dans un tableau faisable.

> Ce que je veux dire c'est que ce n'est pas visible facilement ce filtre. Si tu le sait pas, ça se voit pas. Un idée serait de forcer le scroll vers le tableau, mais je sais pas si c'est tip top côté accessibilité

À voir avec Estelle et/ou Quentin ce qu'ils en pensent. (Garder tel quel, supprimer le filtrage au click ou scroller)

2021-07-20 11:30 UTC, jonathanperret commented
> Effet, il y a un bug bizarre.. apparement j'arrive à le reproduire uniquement quand j'utilise sur le bouton back du navigateur et qu'ensuite je clique sur une campagne de collecte de profil

Depuis la liste des campagnes (https://orga-pr3150.review.pix.fr/campagnes) si on clique sur le nom de la campagne "Pro - Campagne de collecte de profils - envois multiple" on arrive sur https://orga-pr3150.review.pix.fr/campagnes/18 (page activité) mais si on clique ailleurs dans le `tr` pour cette même campagne on arrive sur https://orga-pr3150.review.pix.fr/campagnes/18/profils (page participants).

2021-07-20 11:44 UTC, jonathanperret commented
> > Lorsqu'on est sur l'onglet "Résultats" et qu'on clique sur un participant, puis qu'on clique sur la flèche de retour, on arrive sur l'onglet "Activité", je trouve ça perturbant, ça veut dire que potentiellement à chaque fois, la personne va se retaper le click sur le bon onglet + tous les filtres à remettre... Pas top.
> 
> Ah ok, en effet c'est pas top, une solution serait de faire simplement un "Back" navigateur (c'est possible en JS) et comme cette page ne peut pas être atteinte autre que par un clique dans un tableau, c'est faisable.

Si c'est de la page de détails d'un participant que tu parles, elle a une URL (ex. https://orga-pr3150.review.pix.fr/campagnes/18/profils/105508) et donc elle n'est pas accessible que par un clic.

Je suis sûr que quelqu'un a écrit quelque part qu'avoir un élément d'interface utilisateur dans la page qui invoque la fonctionnalité de retour en arrière du navigateur était une mauvaise idée. Non seulement parce qu'on ne peut pas contrôler d'où vient l'utilisateur mais surtout parce que ça casse le modèle de navigation et les attentes de l'utilisateur. Quand j'utilise une application bien faite (l'interface Datadog est un bon exemple !) je m'attends à ce que le bouton "back" me remette dans un état précédent. Si la page web elle-même manipule mon historique, cette attente ne sera plus satisfaite : par exemple si je clique pour revenir d'un participant à la campagne, je veux que le bouton "back" me ramène où j'étais juste avant, à savoir sur le participant. Et vice versa !

Attention à ne pas confondre l'action de "revenir à l'état précédent" avec celle de "remonter dans la hiérarchie". La flèche de navigation qui est présente sur la page de participant (et celle de campagne) n'a pas le sens "revenir en arrière" mais "remonter au parent", elle devrait donc être implémentée en conséquence. Le pictogramme conventionnel pour cette action est plutôt une flèche vers le haut que vers la gauche, d'ailleurs.

Dans le cas de la page participant, à mon sens elle devrait donc permettre d'accéder à la liste des participants qui est le parent le plus "logique" de cette page, indépendamment de la façon dont on y est arrivé. Si un utilisateur veut revenir à la page activité après avoir cliqué sur un participant, il peut simplement utiliser la fonctionnalité "revenir en arrière" de son navigateur puisque justement on aura pris soin de respecter son fonctionnement ! Dommage d'ailleurs que la position de scroll ne soit pas préservée dans ce cas (le retour à la page "Activité" force un scroll vers le haut), mais ça pourrait probablement se corriger.

Bien sûr en éliminant la possibilité de naviguer vers un participant depuis "Activité" on se simplifierait (un peu) le travail mais je trouve ça dommage pour l'utilisateur de le priver d'un lien aussi évident.

2021-07-22 08:40 UTC, bpetetot commented on orga/app/router.js
> +        this.route('details');
A faire dans une autre PR

2021-07-22 08:59 UTC, lisequesnel commented on api/lib/application/campaign-participations/index.js
> +        handler: campaignParticipationController.findSharedParticipations,
**question** : ici le naming devrait pas être raccord avec la route ?

2021-07-22 08:59 UTC, lisequesnel commented on api/lib/application/campaign-participations/index.js
> +        tags: ['api', 'campaign-assessment-participation-result-minimal'],
c'est toujours d'actualité le naming "...Minimal" ? Parce qu'il reste as mal d'occurence

2021-07-22 09:01 UTC, lisequesnel commented on api/lib/domain/read-models/campaign-results/CampaignAssessmentParticipationResultMinimal.js
> +class CampaignAssessmentParticipationResultMinimal {
`CampaignAssessmentParticipationResult` existe déjà de mémoire pour quand on est sur le détail d'un résultat : d'où ici dans la liste parler de "summary"

2021-07-22 10:07 UTC, bpetetot commented on api/lib/application/campaign-participations/index.js
> +        tags: ['api', 'campaign-assessment-participation-result-minimal'],
Oui toujours `Minimal` car personne n'a réussi à trancher, du coup, pour le moment ça reste comme ça.
Ici la conversation : https://github.com/1024pix/pix/pull/3150#discussion_r668709184

2021-07-22 10:13 UTC, bpetetot commented on api/lib/application/campaign-participations/index.js
> +        handler: campaignParticipationController.findSharedParticipations,
done

2021-07-22 12:47 UTC, lisequesnel approved these changes

2021-07-22 12:48 UTC, lisequesnel commented
validé fonctionnellement ✅

2021-07-22 13:08 UTC, merged