[FEATURE] Afficher un message générique quand aucun participant n'a rejoint la campagne (PIX-2671).
1024pix/pix pull request #3219
Opened 2021-07-20 15:06 UTC by ajoanny

## :unicorn: Problème
Lorsqu’un prescripteur souhaite voir les onglets Activité / Résultats / Analyse alors qu’aucun participant n’a encore participé, tous les blocs s’affichent mais sans informations.

## :robot: Solution
 Afficher un message avec un bouton permettant de copier / coller le lien de la campagne.

## :rainbow: Remarques
> _Des infos supplémentaires, trucs et astuces ?_

## :100: Pour tester
Aller sur PixOrga avec le compte pro.admin@example.net

Les onglets des campagnes sans participant doivent afficher un message avec un bouton permettant de copier / coller le lien de la campagne.

Les onglets : 
- Participants
- Résultat collectif
- Analyse
- Activité (`/campagnes/{id}/activite`)

2021-07-20 15:11 UTC, pix-service commented
I'm deploying this PR to these urls:

- App (.fr): https://app-pr3219.review.pix.fr
- App (.org): https://app-pr3219.review.pix.org
- Orga: https://orga-pr3219.review.pix.fr
- Certif: https://certif-pr3219.review.pix.fr
- Admin: https://admin-pr3219.review.pix.fr
- API: https://api-pr3219.review.pix.fr/api/

 Please check it out!

2021-07-21 08:48 UTC, yaelle6 commented on orga/app/components/campaign/copy-paste-button.hbs
> +{{/if}}
eol

2021-07-21 08:48 UTC, yaelle6 commented on orga/app/components/campaign/empty-state.hbs
> +</div>
eol

2021-07-21 08:48 UTC, yaelle6 commented on orga/app/styles/components/campaign/empty-state.scss
> +}
eol

2021-07-21 08:48 UTC, yaelle6 commented on orga/public/images/empty-state.svg
> +<svg width="178" height="245" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"><defs><filter x="-21.5%" y="-222.4%" width="143.1%" height="544.9%" filterUnits="objectBoun
eol

2021-07-21 08:48 UTC, yaelle6 commented on orga/tests/integration/components/campaign/copy-paste-button_test.js
> +  test('it displays the empty message', async function(assert) {
``` suggestion
  test('it displays the default message', async function(assert) {
```

2021-07-21 08:48 UTC, yaelle6 commented on orga/tests/integration/components/campaign/copy-paste-button_test.js
> +import { setupIntl, t } from 'ember-intl/test-support';
```suggestion
import { setupIntl } from 'ember-intl/test-support';
```

2021-07-21 08:48 UTC, yaelle6 commented on orga/app/components/routes/authenticated/campaign/assessment/list.hbs
> +{{/if}}
eol

2021-07-21 08:48 UTC, yaelle6 commented on orga/app/components/routes/authenticated/campaign/collective-results/tab.hbs
> +{{/if}}
eol

2021-07-21 08:48 UTC, yaelle6 commented on orga/app/components/routes/authenticated/campaign/profile/list.hbs
> +{{/if}}
eol

2021-07-21 08:48 UTC, yaelle6 commented on orga/app/templates/authenticated/campaigns/campaign/analysis.hbs
> +{{/if}}
eol

2021-07-21 08:57 UTC, yaelle6 approved these changes
testé fonctionnellement 👍

2021-07-21 09:50 UTC, xav-car commented on orga/config/icons.js
> +      'spider',
a retirer

2021-07-21 09:51 UTC, xav-car commented on orga/tests/integration/components/campaign/copy-paste-button_test.js
> +import { setupIntl, t } from 'ember-intl/test-support';
On utilise le `t` l27 .

2021-07-21 10:04 UTC, lisequesnel commented on orga/app/components/campaign/analysis/recommendations.hbs
> -    <div class="table__empty content-text">{{t 'pages.campaign-review.table.empty'}}</div>
**question** : il y a pas une traduction à enlever dans les fichiers de trad aussi ?

2021-07-21 10:05 UTC, lisequesnel commented on orga/app/styles/components/campaign/empty-state.scss
> +        display: flex;
problème d'indentation je pense :)

2021-07-21 10:08 UTC, lisequesnel commented on orga/app/routes/authenticated/campaigns/campaign/analysis.js
> +    return model;
**question** : ça change quelque chose ?

2021-07-21 10:10 UTC, lisequesnel commented on orga/app/components/routes/authenticated/campaign/profile/list.hbs
> -      <div class="table__empty content-text">{{t 'pages.profiles-list.table.empty'}}</div>
idem pour tous les empty state

2021-07-21 10:14 UTC, lisequesnel requested changes
Problème : Quand on filtre sur un tableau, et qu'aucun résultat ne ressort, la page affiche l'empty state, mais on ne peut plus rechanger le filtre. Je pense qu'il faut garder l'affichage du "aucun résultat", pour les cas où les filtres sont trop sélectifs (cf capture d'écran avec un filtre dans l'url)

![image](https://user-images.githubusercontent.com/23451175/126472926-c6145c59-b954-4c54-8fc2-e3c732d9b7f7.png)

2021-07-22 08:37 UTC, lisequesnel commented on orga/app/components/routes/authenticated/campaign/collective-results/tab.hbs
>    {{/unless}}
dans les résultats collectifs il n'y a pas de filtres, donc je pense qu'on peut enlever cette partie quand même

2021-07-22 08:38 UTC, lisequesnel commented
validé fonctionnellement ✅

2021-07-22 08:39 UTC, lisequesnel approved these changes
il reste quelques petits trucs à prendre en compte :
- CI qui passe pas ;
- historique git à revoir ;
- quelques commentaires à résoudre.

Mais sinon j'approuve

2021-07-22 13:39 UTC, bpetetot commented on orga/app/styles/components/campaign/empty-state.scss
> +    color:$grey-30;
[suggestion] manque un espace `color:  $grey-30;`

2021-07-22 13:42 UTC, bpetetot commented on orga/tests/integration/components/campaign/copy-paste-button_test.js
> +    assert.contains(t(defaultMessage));
[question]
Pourquoi on utilise la fonction `t` ici ? Car defaultMessage est `Ivre il clique sur le bouton et ....`, ce n'est pas une clé de traduction.

Normalement `assert.contains(defaultMessage);` devrait être suffisant.

2021-07-22 13:43 UTC, bpetetot commented on orga/tests/integration/components/campaign/copy-paste-button_test.js
> +  });
[suggestion] Le `beforeEach` n'est pas utile, tu as seulement un seul test

2021-07-22 13:44 UTC, bpetetot commented on orga/tests/integration/components/campaign/copy-paste-button_test.js
> +      @clipboardText={{'textToCopy'}}
[suggestion]
`@clipboardText="textToCopy"`

2021-07-22 13:45 UTC, bpetetot commented on orga/tests/integration/components/campaign/empty-state_test.js
> +    await render(hbs`<Campaign::EmptyState @textToCopy={{'ABDC123'}}/>`);
[suggestion]
`@textToCopy ="ABDC123"`

Et j'aurais renommé `@textToCopy` en `@campaignCode`

2021-07-22 13:48 UTC, bpetetot commented on orga/app/components/routes/authenticated/campaign/assessment/list.hbs
> +    @campaignCode={{@campaign.code}}/>
Voir mon commentaire précédent sur le test de ce composant.

Apparement, il a bien une propriété "campaignCode" et pas "textToCopy"

2021-07-22 13:49 UTC, bpetetot commented on orga/app/components/routes/authenticated/campaign/collective-results/tab.hbs
>    {{/unless}}
Et du coup le if ligne 28 est également à supprimer

2021-07-22 13:54 UTC, bpetetot commented on orga/app/components/routes/authenticated/campaign/assessment/list.hbs
> +{{#if (gt @campaign.participationsCount 0)}}
[question] Est-ce qu'on ajouterait pas dans le model de campaign un getter `hasParticipations` qui fait le greater than ? Pas obligatoire, c'est une proposition pour faciliter la lecture du composant.

2021-07-22 13:56 UTC, bpetetot commented on orga/tests/integration/components/routes/authenticated/campaign/profile/list_test.js
> -      assert.contains('En attente de profils');
Supprimer ce texte des fichiers i18n

2021-07-22 13:56 UTC, bpetetot commented on orga/tests/integration/components/routes/authenticated/campaign/collective-results/tab_test.js
> -    assert.contains('En attente de résultats');
Supprimer ce texte des fichiers i18n

2021-07-22 15:29 UTC, xav-car commented on orga/tests/integration/components/campaign/copy-paste-button_test.js
> +    assert.contains(t(defaultMessage));
dans les fait, on doit passer une clé de trad au composant. qui le décode avec un `t` dans son controller. du coup dans le test il s'attend a avoir un `t` de ce qu'on lui a passé en paramètre.

(je ne sais pas si je suis clair) . ou alors c'est notre texte de test qui est perturbant.

2021-07-22 15:45 UTC, xav-car commented on orga/app/routes/authenticated/campaigns/campaign/analysis.js
> +    return model;
Je crois que ça ne change rien en fait. 
ça a été revu dans la PR d'avant qui est arrivé sur dev.

2021-07-22 15:46 UTC, xav-car commented on orga/app/components/routes/authenticated/campaign/profile/list.hbs
> -      <div class="table__empty content-text">{{t 'pages.profiles-list.table.empty'}}</div>
du coup, on le garde, suite au request changes.

2021-07-22 15:47 UTC, xav-car commented on orga/app/components/routes/authenticated/campaign/collective-results/tab.hbs
>    {{/unless}}
fichier supprimer dans la PR sur l'ouverture de la page activité

2021-07-22 15:56 UTC, bpetetot commented on orga/tests/integration/components/campaign/copy-paste-button_test.js
> +    assert.contains(t(defaultMessage));
Oui peut être dans se cas mettre une clé, mais du coup c'est le composant `copy-paste-button` qui est bizarre. Car dans sa propriété `defaultMessage` il doit prendre une clé de message et pas un message. J'aurais enlevé l'utilisation de la fonction `t` dans le JS du composant, pour que cette propriété prenne en entrée un message déjà traduit.

2021-07-22 16:26 UTC, lisequesnel commented on orga/translations/en.json
> +      "empty-state": "No particiants yet! Share with them the following link to join this campaign.",
typo : "No participants yet!"

2021-07-22 16:27 UTC, lisequesnel commented on orga/translations/en.json
> +          "empty": "No results",
**question** : cette clé est encore utilisée ? il me semble pas

2021-07-22 16:28 UTC, lisequesnel commented on orga/translations/en.json
> +          "empty": "No results",
**question** : cette clé est encore utilisée ? il me semble pas

2021-07-23 09:40 UTC, merged