[FEATURE] Accepter une recherche approximative sur un utilisateur lors de la sortie SCO (PIX-2758).
1024pix/pix pull request #3230
Opened 2021-07-22 08:00 UTC by Anne-Gaelle-S

## :unicorn: Problème
> _Décrivez ici le besoin ou l'intention couvert par cette Pull Request._

## :robot: Solution
> _Ajoutez à cet endroit, si nécessaire, des détails concernant la solution technique retenue et mise en oeuvre, des difficultés ou problèmes rencontrés._

## :rainbow: Remarques
> _Des infos supplémentaires, trucs et astuces ?_

## :100: Pour tester
> _Les instructions pour reproduire le problème, les profils de test, le parcours spécifique à utiliser, etc._

2021-07-22 08:06 UTC, pix-service commented
I'm deploying this PR to these urls:

- App (.fr): https://app-pr3230.review.pix.fr
- App (.org): https://app-pr3230.review.pix.org
- Orga: https://orga-pr3230.review.pix.fr
- Certif: https://certif-pr3230.review.pix.fr
- Admin: https://admin-pr3230.review.pix.fr
- API: https://api-pr3230.review.pix.fr/api/

 Please check it out!

2021-07-23 14:53 UTC, octo-topi approved these changes
Mob prog

2021-07-26 07:39 UTC, AndreiaPena commented
**Question** : Pourquoi ce choix de laisser le nom de l'utilisateur avec "l'erreur de frappe
<img width="540" alt="Capture d’écran 2021-07-26 à 09 37 51" src="https://user-images.githubusercontent.com/58915422/126951168-697b7d3f-f086-44c7-bc32-4d84775b6da1.png">
" dans le scénario du double INE ?

2021-07-26 09:31 UTC, AndreiaPena requested changes

2021-07-26 09:31 UTC, AndreiaPena commented on api/lib/domain/services/check-sco-account-recovery-service.js
>    });
**Remarque bloquante :** Pourquoi avoir créé deux méthodes : `_getLastMatchingSchoolingRegistration` et `findByNationalStudentIdAndBirthdate` alors qu'il est possible de modifier la méthode existante `getSchoolingRegistrationInformation`, en enlevant les paramètres firstName et lastName et le select spécifiant les colonnes voulues ? 

Cette méthode n'est pas utilisé autre part et fait exactement vos checks de votre méthode `_getLastMatchingSchoolingRegistration` ( que le userId n'est pas null, et qu'on prend la schooling registration la plus récente.)

2021-07-26 09:31 UTC, AndreiaPena commented on api/lib/infrastructure/repositories/schooling-registration-repository.js
> +
A supprimer si remarque pris en compte, elle ne sera plus nécessaire

2021-07-26 09:35 UTC, AndreiaPena commented on api/tests/unit/domain/services/user-reconciliation-service_test.js
> +      // Can it be replaced by 'When at least one schoolingRegistration matched on names' ?
**Question :** Est-ce que cela va rester ? Ou vous vouliez avoir nos retours dessus ?

2021-07-26 09:37 UTC, yschoueri commented on api/lib/domain/services/check-sco-account-recovery-service.js
> +  };
**chipotage**
```suggestion
 const { id, userId, firstName, lastName, organizationId } = lastSchoolingRegistration;
 
  return { id, userId, firstName, lastName, username, organizationId, email };
```

2021-07-26 09:45 UTC, octo-topi commented on api/tests/unit/domain/services/user-reconciliation-service_test.js
> +      // Can it be replaced by 'When at least one schoolingRegistration matched on names' ?
On a documenté l'ambiguité du nom du test par rapport à ce qu'il fait.
Pas d'action prévue

2021-07-26 09:58 UTC, octo-topi commented on api/lib/domain/services/check-sco-account-recovery-service.js
>    });
C'est délibéré, on a voulu mettre les RG dans le service et pas dans le repository.

Par contre, suite au dernier rebase, la fonction `getSchoolingRegistrationInformation` n'est plus utilisée, je la supprime de suite.

2021-07-26 10:18 UTC, AndreiaPena commented on api/lib/domain/services/check-sco-account-recovery-service.js
>    });
Dans l'historique de cette feature, on avait tout ce check fait dans le usecase, puis un refacto a été réalisé pour mettre tout ça dans le repo, le usecase était bien plus lisible.

Mais là ce qu'on constate c'est un retour en arrière, on rebascule tout dans le service qui devient à mon sens plus complexe à lire (avec plusieurs méthodes privées) et faire tout ce filtre pour avoir le dernier schoolingR alors qu'un orderBy fait ça aussi bien, je comprend pas trop cette décision.

A en discuter au recap tech si nécessaire.

2021-07-26 12:17 UTC, aceol commented on api/lib/domain/services/check-sco-account-recovery-service.js
> +    .first();
Pour éviter une étape superflue:
```suggestion
  const lastSchoolingRegistration = _(schoolingRegistrationsMatchingIneAndBirthdate)
    .orderBy('updatedAt')
    .last();
```

2021-07-26 12:20 UTC, AndreiaPena commented on api/lib/domain/services/check-sco-account-recovery-service.js
>    });
Faire le choix de mettre les RG dans le usecase ou le repo, c'est à l'appréciation de chacun, on en a discuté ensemble mais aucune règle d'équipe n'a été mis en place.
Or ici on est sur une implem déjà existante et qui a fait l'objet d'un refacto validé.

2021-07-27 08:01 UTC, yahyayouness commented on api/lib/infrastructure/repositories/schooling-registration-repository.js
> +const _toDomain = (schoolingRegistrationDTO) => {
@octo-topi tu m'avais proposé _toDomainObject que j'avais déjà pris dans un repo !

2021-07-27 08:08 UTC, octo-topi commented on api/lib/domain/services/check-sco-account-recovery-service.js
>    });
Quelques éléments ici (hors ticket)
https://github.com/GradedJestRisk/pix-tools/blob/master/adr/store-business-rules.md

2021-07-27 09:13 UTC, octo-topi commented on api/lib/domain/services/check-sco-account-recovery-service.js
>    });
Vu avec @AndreiaPena @yahyayouness @yschoueri  => retour arrière à faire

2021-07-27 11:33 UTC, octo-topi commented
> **Question** : Pourquoi ce choix de laisser le nom de l'utilisateur avec "l'erreur de frappe" dans le scénario du double INE ?
> <img alt="Capture d’écran 2021-07-26 à 09 37 51" width="540" src="https://user-images.githubusercontent.com/58915422/126951168-697b7d3f-f086-44c7-bc32-4d84775b6da1.png">

Avant de demander à @manux-pix son avis, j'ai vérifié si c'était coûteux.
Et bien le code n'est pas du tout fait pour, il ne renvoie pas le champ qui a matché (6 possibilités).
J'en informe @manux-pix 

```
    'First names=>',
    sr."firstName",
    sr."middleName",
    sr."thirdName",
    'Last names=>',
    sr."lastName",
    sr."preferredLastName"
```

2021-07-27 11:39 UTC, octo-topi reviewed
@yahyayouness 

Pour cette PR, j'ai repris la PR modèle de @laura-bergoens et .. il y a `_toDomain`
https://github.com/1024pix/pix/pull/3109

Je retire donc ma remarque dans l'autre PR
https://github.com/1024pix/pix/blob/dev/api/lib/infrastructure/repositories/account-recovery-demand-repository.js#L8

Veux-tu que je corrige `account-recovery-demand-repository.js` ?

2021-07-27 11:41 UTC, octo-topi commented on api/lib/domain/services/check-sco-account-recovery-service.js
> +    .first();
Bien vu.. mais le code sera supprimé par https://github.com/1024pix/pix/pull/3230#discussion_r677268526

2021-07-27 11:45 UTC, octo-topi commented on api/lib/domain/services/check-sco-account-recovery-service.js
> +  };
Je ne suis pas fan à priori car oen voit plsu qui vient de quoi d'un coup d'oeil.
Mais je suis OK pour essayer => j'ai pris ta suggestion

2021-07-27 11:45 UTC, octo-topi commented on api/lib/infrastructure/repositories/schooling-registration-repository.js
> +
https://github.com/1024pix/pix/pull/3230#discussion_r677268526

2021-07-27 15:48 UTC, AndreiaPena approved these changes

2021-07-28 07:12 UTC, octo-topi commented on api/lib/domain/services/check-sco-account-recovery-service.js
>    });
Corrigé par @AndreiaPena

2021-07-28 07:17 UTC, merged