[FEATURE] Ne plus afficher l'infobulle si l'utilisateur l'a déjà vue (PIX-2878).
1024pix/pix pull request #3267
Opened 2021-07-30 14:58 UTC by celineung

## :unicorn: Problème
Sur une épreuve focus, une tooltip s'affiche pour indiquer à l'utilisateur ce qu'est une épreuve focus.
Cette tooltip s'affiche actuellement à chaque épreuve focus.
Or l'utilisateur n'a pas besoin de la voir à chaque fois.

## :robot: Solution
Afficher la tooltip seulement la première fois:
quand l'utilisateur clique sur "J'ai compris", on sauvegarde en DB que l'utilisateur a déjà vu la tooltip, elle ne sera donc pas réaffichée la prochaine fois.

## :rainbow: Remarques
> _Des infos supplémentaires, trucs et astuces ?_

## :100: Pour tester
Se rendre sur une épreuve focus (ex: rec2dRKsI4aBIsayz):
- une tooltip s'affiche
- les boutons actions et input sont déasactivés
- un overlay s'affiche derrière la tooltip
- cliquer sur "J'ai compris' de la tooltip
- vérifier que la tooltip et l'overlay ont disparu et les input et bouton sont cliquables
- en DB le champ `hasSeenFocusedChallengeTooltip` de l'utilisateur est passé à `true`
- après rafraichissement de la page, la tooltip et l'overlay ne sont plus visibles

2021-07-30 15:03 UTC, pix-service commented
I'm deploying this PR to these urls:

- App (.fr): https://app-pr3267.review.pix.fr
- App (.org): https://app-pr3267.review.pix.org
- Orga: https://orga-pr3267.review.pix.fr
- Certif: https://certif-pr3267.review.pix.fr
- Admin: https://admin-pr3267.review.pix.fr
- API: https://api-pr3267.review.pix.fr/api/

 Please check it out!

2021-08-02 08:02 UTC, francois2metz reviewed
Sur Firefox le bien aimé, rien ne s'affiche sur une épreuve focus (mais il y a bien un overlay: 
![Screenshot 2021-08-02 at 10-00-28 Épreuve 1 sur 1 Preview Pix](https://user-images.githubusercontent.com/86659/127825583-6a193d13-9f5e-4c3d-a252-986f51df6706.png)

2021-08-02 08:02 UTC, francois2metz commented on api/lib/application/users/index.js
> +          '- Sauvegarde le fait que l\'utilisateur ait vu le message sur le nouveau dashboard' +
Ce n'est pas le bon commentaire ;)

2021-08-02 08:12 UTC, VincentHardouin commented on mon-pix/tests/acceptance/challenge-item-qroc_test.js
> +          // debugger;
petit oubli

2021-08-02 08:22 UTC, MelanieMEB requested changes
Cette PR me fait poser pas mal de questions : 
- Après réflexion, je ne pense pas qu'il faille déjà mettre les autres colonnes non utilisées
- On risque d'avoir pas mal de colonne de config, on a déjà hasSeenAssessmentInstruction. Est-ce qu'on souhaite continuer dans ces colonnes true/false ou passer sur une colonne json qui renverrait une liste d'info déjà vu ? Si on reste sur du true/false, est-ce qu'on les veut toujours dans la table user ? 
- C'est peut être une question plus large que ce ticket, c'est pour cela que dans ce ticket, je propose de n'ajouter qu'une seule colonne.

2021-08-02 08:22 UTC, MelanieMEB commented on api/db/migrations/20210727092407_add-columns-has-seen-focused-and-other-challenge-tooltips.js
> +    table.boolean('hasSeenOtherChallengeTooltip').defaultTo(false);
Actuellement, je propose de laisser de coté le cas du hasSeenOtherChallengeTooltip, qui n'est pas utilisé et qui pourrait évoluer.

2021-08-02 08:22 UTC, MelanieMEB commented on mon-pix/app/controllers/assessments/challenge.js
> +  // @tracked hasUserSeenFocusedChallengeTooltip = this.currentUser.user.hasSeenFocusedChallengeTooltip;
Il reste un commentaire

2021-08-02 08:22 UTC, MelanieMEB commented on mon-pix/app/controllers/assessments/challenge.js
> +    // this.hasUserSeenFocusedChallengeTooltip = true;
Il reste un commentaire

2021-08-02 08:47 UTC, Thomasevano commented on api/lib/infrastructure/repositories/user-repository.js
> +    const user = await BookshelfUser.where({ id: userId }).fetch({ require: false });
**Question :**J'ai peut etre pas tout suivi mais on avait pas pour but d'enlever Bookshelf ?

2021-08-02 08:47 UTC, Thomasevano commented on mon-pix/app/controllers/assessments/challenge.js
> +    // this.hasUserSeenFocusedChallengeTooltip = true;
Oubli d'enlever les commentaire

2021-08-02 09:03 UTC, alexandrecoin commented on mon-pix/tests/acceptance/challenge-item-qroc_test.js
> +          // debugger;
Oupsie.

2021-08-02 09:48 UTC, alexandrecoin commented on api/lib/infrastructure/repositories/user-repository.js
> +    const user = await BookshelfUser.where({ id: userId }).fetch({ require: false });
Effectivement, nous nous sommes inspirés de la requête réalisée dans le cadre de `hasUserSeenDashboardInfo`, toujours rattachée à Knex, comme nombre de requêtes dans pix-app.
J'aurais toutefois tendance à opérer ces modifications dans des PR séparées, à la manière de ce qui a été fait dans #3197.

2021-08-02 10:00 UTC, alexandrecoin commented on api/db/migrations/20210727092407_add-columns-has-seen-focused-and-other-challenge-tooltips.js
> +    table.boolean('hasSeenOtherChallengeTooltip').defaultTo(false);
>     * Après réflexion, je ne pense pas qu'il faille déjà mettre les autres colonnes non utilisées

On est d'accord. Cette implémentation a eu lieu car les specs après avoir réalisé cette version.

>     * On risque d'avoir pas mal de colonne de config, on a déjà hasSeenAssessmentInstruction. Est-ce qu'on souhaite continuer dans ces colonnes true/false ou passer sur une colonne json qui renverrait une liste d'info déjà vu ? Si on reste sur du true/false, est-ce qu'on les veut toujours dans la table user ?

J'aurais tendance à rester sur cette version dans le cadre de cette PR avec la deadline qui arrive. Et réfléchir à une modification de l'enregistrement des données une fois les épreuves focus sorties.

>     * C'est peut être une question plus large que ce ticket, c'est pour cela que dans ce ticket, je propose de n'ajouter qu'une seule colonne.

100% d'accord avec ce point de vue.

2021-08-02 12:58 UTC, alexandrecoin commented
> Sur Firefox le bien aimé, rien ne s'affiche sur une épreuve focus (mais il y a bien un overlay)

Fixed. On avait oublié de set le feature toggle 🙇🏼‍♂️

2021-08-02 14:57 UTC, VincentHardouin commented on api/lib/application/users/index.js
> +          '- Le contenu de la requête n\'est pas pris en compte.',
Le schéma Joi n'est pas très utile du coup, je propose de l'enlever.

2021-08-03 08:01 UTC, VincentHardouin commented on api/lib/application/users/index.js
> +          '- Le contenu de la requête n\'est pas pris en compte.',
mb j'avais pas vu que c'était sur les params.

2021-08-03 08:02 UTC, VincentHardouin approved these changes

2021-08-03 08:27 UTC, Thomasevano approved these changes

2021-08-03 13:25 UTC, MelanieMEB requested changes
Ce type d'épreuve ne fonctionne pas si la personne n'est pas connecté (sur une démo ou preview par exemple)

2021-08-03 13:56 UTC, francois2metz commented on mon-pix/app/controllers/assessments/challenge.js
> +    if (ENV.APP.FT_FOCUS_CHALLENGE_ENABLED) {
J'ai l'impression que l'idée c'est maintenant d'utiliser un feature toggle coté API pour pouvoir le changer a chaud. Comme la PR est grosse, ca peut aussi être fait a part.

2021-08-03 14:00 UTC, francois2metz commented
On a un PATCH systématique au chargement de la page pour modifier `has-seen-focused-challenge-tooltip` alors que c'est déjà a true.

2021-08-05 15:03 UTC, alexandrecoin commented on mon-pix/app/controllers/assessments/challenge.js
> +    if (ENV.APP.FT_FOCUS_CHALLENGE_ENABLED) {
On passera effectivement ça sur une autre PR. :)

2021-08-05 15:04 UTC, alexandrecoin commented
> On a un PATCH systématique au chargement de la page pour modifier `has-seen-focused-challenge-tooltip` alors que c'est déjà a true.

Un check a été rajouté pour vérifier que le user n'avait pas la propriété `hasSeenFocusedChallengeTooltip` avant de le PATCH

2021-08-06 08:35 UTC, MelanieMEB approved these changes

2021-08-06 08:43 UTC, merged