[BUGFIX] Suppression d'un appel inutile et potentiellement long au back depuis Pix Orga.
1024pix/pix pull request #3271
Opened 2021-08-02 16:37 UTC by lisequesnel

## :unicorn: Problème
Un appel à `/api/campaigns/id/collective-results` est réalisé sur l'onglet résultats, alors que les informations récupérées ne sont pas du tout affichées. De plus, cette route agrège des résultats et donc peut mettre un certain temps. Cela n'est pas optimal pour l'expérience utilisateur.

## :robot: Solution
Supprimer cet appel.

## :rainbow: Remarques
Rien à signaler.

## :100: Pour tester
Aller sur l'onglet "Résultats" et vérifier dans l'onglet "Network" de la console que l'appel n'est pas lancé.

2021-08-02 16:41 UTC, pix-service commented
I'm deploying this PR to these urls:

- App (.fr): https://app-pr3271.review.pix.fr
- App (.org): https://app-pr3271.review.pix.org
- Orga: https://orga-pr3271.review.pix.fr
- Certif: https://certif-pr3271.review.pix.fr
- Admin: https://admin-pr3271.review.pix.fr
- API: https://api-pr3271.review.pix.fr/api/

 Please check it out!

2021-08-02 16:56 UTC, VincentHardouin approved these changes

2021-08-03 07:00 UTC, bpetetot requested changes
Cet appel est utilisé pour afficher la carte de résultat moyen (voir PR #3222), du coup pour le moment il est encore nécessaire. Mais il sera remplacé par un autre appel quand le stockage des résultats seront stockés sur les participations.

2021-08-03 08:01 UTC, lisequesnel commented
> Cet appel est utilisé pour afficher la carte de résultat moyen (voir PR #3222), du coup pour le moment il est encore nécessaire. Mais il sera remplacé par un autre appel quand le stockage des résultats seront stockés sur les participations.

Ah en effet, j'avais pas vu ça dans la PR en cours. Et en effet faudra changer ça, maybe le mettre dans la route `GET /campaigns/id` comme `participationsCount` et `sharedParticipationsCount` ?

2021-08-03 08:01 UTC, closed without merging