[FEATURE] Ajout de l'affichage/disparition de la tooltip des épreuves focus au hover (PIX-2909).
1024pix/pix pull request #3274
Opened 2021-08-03 15:58 UTC by alexandrecoin

## :unicorn: Problème
> _Décrivez ici le besoin ou l'intention couvert par cette Pull Request._

## :robot: Solution
> _Ajoutez à cet endroit, si nécessaire, des détails concernant la solution technique retenue et mise en oeuvre, des difficultés ou problèmes rencontrés._

## :rainbow: Remarques
> _Des infos supplémentaires, trucs et astuces ?_

## :100: Pour tester
> _Les instructions pour reproduire le problème, les profils de test, le parcours spécifique à utiliser, etc._

2021-08-03 16:03 UTC, pix-service commented
I'm deploying this PR to these urls:

- App (.fr): https://app-pr3274.review.pix.fr
- App (.org): https://app-pr3274.review.pix.org
- Orga: https://orga-pr3274.review.pix.fr
- Certif: https://certif-pr3274.review.pix.fr
- Admin: https://admin-pr3274.review.pix.fr
- API: https://api-pr3274.review.pix.fr/api/

 Please check it out!

2021-08-05 07:43 UTC, MelanieMEB requested changes
L'information n'est pas visible au clavier.
Possibilité : 
- Mettre un tabindex pour le rendre selectionnable et en faire un bouton pour afficher aussi le message

2021-08-10 08:55 UTC, francois2metz commented
Sous Firefox, la tooltip ne s'affiche que au survol du bouton quasi invisible:

![Screenshot 2021-08-10 at 10-54-06 Épreuve 1 sur 1 Preview Pix](https://user-images.githubusercontent.com/86659/128838251-c4cd45f7-c893-4cc1-b1e6-4a1ac2ffccb1.png)

2021-08-11 13:51 UTC, sbedeau requested changes

2021-08-11 13:51 UTC, sbedeau commented on mon-pix/app/components/challenge/challenge-statement/focused-tooltip.js
> +  }
**suggestion(si mineur):** J'ai beaucoup de difficulté à percevoir les différents cas utilisateurs décrits par les conditions. La compréhension des duplications est de fait difficile également.

Je propose d'expliciter les différents cas par des méthodes voire simplifier les différentes conditions

2021-08-11 13:51 UTC, sbedeau commented on mon-pix/app/templates/components/challenge-statement.hbs
> +        <Challenge::ChallengeStatement::FocusedTooltip @challenge={{@challenge}} @onTooltipClose={{@onTooltipClose}}/>
**question:** Pourquoi on a besoin de faire remonter `onTooltipClose` ?

2021-08-11 13:51 UTC, sbedeau commented on mon-pix/app/components/challenge/challenge-statement/focused-tooltip.js
> +  toggleTooltip(value) {
**chipotage:** Un toggle est une bascule de l'état booléen précédent ce qui n'est pas le cas ici
 
**suggestion:** Renommer en `displayTooltip`

2021-08-11 13:51 UTC, sbedeau commented on mon-pix/app/styles/components/_focused-tooltip.scss
> +.challenge-statement-instruction {
**chipotage(bloquant):** Toutes les classes de ce fichier doivent être préfixées par le nom du fichier `focused-tooltip` pour appliquer correctement BEM

2021-08-11 14:52 UTC, MelanieMEB approved these changes

2021-08-11 14:52 UTC, MelanieMEB commented on mon-pix/app/components/challenge/challenge-statement/focused-tooltip.hbs
> +          class="challenge-statement-tag__icon-button"
```suggestion
  <button type="button"
          tabindex="0"
          aria-describedby="challenge-statement__tag-information"
          class="challenge-statement-tag__icon-button"
          aria-label="Afficher l'indication sur l'épreuve"
```

2021-08-11 14:52 UTC, MelanieMEB commented on mon-pix/app/components/challenge/challenge-statement/focused-tooltip.js
> +    }
Est-ce que

```suggestion
      this.shouldDisplayTooltip = value;
```

ne suffit pas dans ce cas ?

2021-08-12 12:36 UTC, MelanieMEB commented on mon-pix/app/components/challenge/challenge-statement/focused-tooltip.js
> +    }
Vu en review : besoin de séparer les cas

2021-08-12 13:47 UTC, MelanieMEB approved these changes

2021-08-12 14:32 UTC, Thomasevano approved these changes

2021-08-13 07:48 UTC, sbedeau approved these changes

2021-08-13 08:08 UTC, merged