[FEATURE] Permettre de sortir dans un fichier csv les résultats d'algolix.
1024pix/pix pull request #3288
Opened 2021-08-05 09:32 UTC by VincentHardouin

## :unicorn: Problème
Actuellement Algolix sort les résultats de l'algo seulement en console et sans convention de format (json, csv, …). 

## :robot: Solution
Permettre à Algolix de sortir les résultats dans un fichier csv qui sera nommé par la date du jour. 
Quand Algolix est lancé plusieurs fois de suite les résultats sont ajoutés à la fin du fichier du jour.
Afin que les résultats de chaque lancé soient bien séparé il a été mis en place des uuid à la place d'id incrémentaux.  

## :rainbow: Remarques
> _Des infos supplémentaires, trucs et astuces ?_

## :100: Pour tester
> _Les instructions pour reproduire le problème, les profils de test, le parcours spécifique à utiliser, etc._

2021-08-05 09:39 UTC, pix-service commented
I'm deploying this PR to these urls:

- App (.fr): https://app-pr3288.review.pix.fr
- App (.org): https://app-pr3288.review.pix.org
- Orga: https://orga-pr3288.review.pix.fr
- Certif: https://certif-pr3288.review.pix.fr
- Admin: https://admin-pr3288.review.pix.fr
- API: https://api-pr3288.review.pix.fr/api/

 Please check it out!

2021-08-05 15:43 UTC, Thomasevano approved these changes

2021-08-06 08:33 UTC, alexandrecoin approved these changes

2021-08-06 08:38 UTC, MelanieMEB requested changes

2021-08-06 08:38 UTC, MelanieMEB commented on high-level-tests/test-algo/tests/utils/CsvFile.test.js
> +      const expectedPath = path.join(__dirname, '../../', '2021-08-05-results.csv');
Si on ne garde que le jour de la date, si on en crée plusieurs dans une journée, ça risque d'être compliqué de travailler.
Je propose : l'ajout de l'heure-minute-sec + ajout possiblement de la compétence/targetprofil testé + type de user

2021-08-06 12:02 UTC, MelanieMEB approved these changes

2021-08-06 12:14 UTC, merged