[TECH] Sortir TimedChallengeInstructions de tous les types de challenges.
1024pix/pix pull request #3305
Opened 2021-08-09 15:24 UTC by Thomasevano

## :unicorn: Problème
Cet écran est imbriqué dans les différents type de challenge.

## :robot: Solution
Sortir le composant au niveau supérieur afin que les autres challenges ne se préoccupent plus d'un composant qui n'a rien avoir avec eux.

## :rainbow: Remarques
> _Des infos supplémentaires, trucs et astuces ?_

## :100: Pour tester
- Se rendre sur une épreuve timé et vérifier que ça marche bien

2021-08-09 15:29 UTC, pix-service commented
I'm deploying this PR to these urls:

- App (.fr): https://app-pr3305.review.pix.fr
- App (.org): https://app-pr3305.review.pix.org
- Orga: https://orga-pr3305.review.pix.fr
- Certif: https://certif-pr3305.review.pix.fr
- Admin: https://admin-pr3305.review.pix.fr
- API: https://api-pr3305.review.pix.fr/api/

 Please check it out!

2021-08-11 08:47 UTC, alexandrecoin approved these changes

2021-08-11 09:23 UTC, MelanieMEB requested changes
Soucis fonctionel : 
- Passer la démo recVhpqHADC8KxyvG
Une fois que l'écran a été vu, il est considéré comme toujours vu et on ne le revoit pas entre les épreuves.

2021-08-11 09:34 UTC, MelanieMEB reviewed
Il faudrait, quand le user répondre à une question, remettre le hasUserConfirmedWarning à false, ça pourrait aider.

2021-08-11 14:22 UTC, ghost reviewed
Techniquement ok pour moi.
Fonctionnellement j'attend que les remarques de Mel soient prises en compte.
A noter que c'est probablement dur au recyclage du composant que l'information n'est pas rafraîchie, d'où la proposition de Mel

2021-08-11 15:41 UTC, MelanieMEB approved these changes

2021-08-12 07:12 UTC, VincentHardouin commented on mon-pix/app/components/challenge-item-generic.js
> +          this.args.userHasFinishedChallenge();
Je pense qu'on pouvait utiliser le `finishChallenge` pour faire ça.

2021-08-12 08:14 UTC, MelanieMEB approved these changes

2021-08-12 09:44 UTC, sbedeau approved these changes
Fonctionnellement, j'ai remarqué que : 
- si on valide le message en épreuve N, puis back en N-1, puis forward avec bouton en épreuve N alors on ne voit plus le message d'information (pas trop grave mais ça veut dire qu'on recycle toujours le composant, il faut le garder en tête si on a des cas bizarres prochainement)

2021-08-12 12:34 UTC, merged