[TECH] Prévenir l'absence de clef étrangère.
1024pix/pix pull request #3311
Opened 2021-08-10 10:35 UTC by octo-topi

## :unicorn: Problème
> _Décrivez ici le besoin ou l'intention couvert par cette Pull Request._

## :robot: Solution
> _Ajoutez à cet endroit, si nécessaire, des détails concernant la solution technique retenue et mise en oeuvre, des difficultés ou problèmes rencontrés._

## :rainbow: Remarques
> _Des infos supplémentaires, trucs et astuces ?_

## :100: Pour tester
> _Les instructions pour reproduire le problème, les profils de test, le parcours spécifique à utiliser, etc._

2021-08-10 10:39 UTC, pix-service commented
I'm deploying this PR to these urls:

- App (.fr): https://app-pr3311.review.pix.fr
- App (.org): https://app-pr3311.review.pix.org
- Orga: https://orga-pr3311.review.pix.fr
- Certif: https://certif-pr3311.review.pix.fr
- Admin: https://admin-pr3311.review.pix.fr
- API: https://api-pr3311.review.pix.fr/api/

 Please check it out!

2021-08-20 14:54 UTC, Thomasevano commented
J'ai bien enlevé l'entrée `finalized-sessions` mais les tests passent pour moi. J'ai surement loupé quelque chose.

2022-01-06 08:28 UTC, octo-topi commented
> J'ai bien enlevé l'entrée `finalized-sessions` mais les tests passent pour moi. J'ai surement loupé quelque chose.

Bien vu, j'ai revu l'implémentation, il y avait bien un bug !

2022-01-07 16:30 UTC, mickaelalibert requested changes
Un long silence vaut mieux que des grands mots 👀

2022-01-07 17:28 UTC, octo-topi commented
> Un long silence vaut mieux que des grands mots eyes

Note pour moi-même:
- remplacer `logger` par `console`
- tester le cas où la whitelist est vide

2022-01-10 08:07 UTC, closed without merging