[FEATURE] Retravailler le visuel de message de sortie de panneau d'épreuve focus (PIX-2871).
1024pix/pix pull request #3320
Opened 2021-08-12 04:35 UTC by alexandrecoin

## :unicorn: Problème
Le visuel de message de sortie du panneau d'épreuve focus n'est pas forcément très visible.

## :robot: Solution
Changement du visuel pour un message sticky en bas de page à la sortie du panneau de l'épreuve.

## :rainbow: Remarques

- Une nouvelle couleur a été ajoutée dans le cadre du redesign, besoin de créer une variable CSS ?
- L'accessibilité comporte encore trop d'inconnues à ce stade pour avoir été prise en compte dans l'élaboration de ce message sticky
- Nous ne disposons pas de maquettes concernant le design d'une version mobile, ce dernier a donc été créé à partir de la version desktop.

## :100: Pour tester
Se rendre sur l'épreuve `rec2dRKsI4aBIsayz` et sortir du panneau de l'épreuve.

2021-08-12 04:41 UTC, pix-service commented
I'm deploying this PR to these urls:

- App (.fr): https://app-pr3320.review.pix.fr
- App (.org): https://app-pr3320.review.pix.org
- Orga: https://orga-pr3320.review.pix.fr
- Certif: https://certif-pr3320.review.pix.fr
- Admin: https://admin-pr3320.review.pix.fr
- API: https://api-pr3320.review.pix.fr/api/

 Please check it out!

2021-08-12 09:37 UTC, sbedeau approved these changes

2021-08-12 13:41 UTC, MelanieMEB requested changes
En attente des traduction

2021-08-12 13:41 UTC, MelanieMEB commented on mon-pix/app/styles/components/_challenge-item.scss
> +    background-color: $blue-10;
```suggestion
    background-color: rgba(196, 230, 255, 0.5);
```

2021-08-12 13:41 UTC, MelanieMEB commented on mon-pix/app/templates/components/challenge-item-qroc.hbs
> +  {{#unless this.hasFocusedOutOfWindow}}
Proposition : On pourrait pas mettre les deux conditions dans une unique method : hasOnlyFocusedOutOfChallenge, ou dans l''idée ?

2021-08-13 08:43 UTC, alexandrecoin commented on mon-pix/app/styles/components/_challenge-item.scss
> +    background-color: $blue-10;
J'ai gardé la variable `$blue-10` correspondant à ces valeurs `196, 230, 255` et ait baissé l'opacité suggérée afin de ne pas altérer la visibilité.

2021-08-13 08:45 UTC, alexandrecoin commented on mon-pix/app/templates/components/challenge-item-qroc.hbs
> +  {{#unless this.hasFocusedOutOfWindow}}
J'ai essayé davantage d'exprimer le fait qu'il n'y avait que deux focus out possibles. A voir si cela te convient. 🙂

2021-08-13 08:59 UTC, VincentHardouin approved these changes

2021-08-13 09:02 UTC, Thomasevano approved these changes

2021-08-13 09:20 UTC, MelanieMEB approved these changes

2021-08-13 09:27 UTC, merged