[FEATURE] Embed + focus = :heavy_check_mark:
1024pix/pix pull request #3344
Opened 2021-08-17 13:39 UTC by francois2metz

## :unicorn: Problème
L'implémentation actuelle des épreuves focus ne permet pas l'utilisation des embeds.

## :robot: Solution
Utiliser la méthode `document.hasFocus()` qui renvoit true si une iframe contenu dans le document a le focus. 

## :rainbow: Remarques
Nous n'avons pas trouvé d'événements qui nous permettrait de ne pas interroger périodiquement le résultat de `document.hasFocus()`

## :100: Pour tester
1. Aller sur un challenge qroc + focus + embed: `rec1Y3cL4enp1lZ97`
2. Lancer le simulateur
3. Constater qu'il n'y a aucun message de sortie de la page
4. Sortir de la page
5. Constater qu'il y a un message de sortie de la page

2021-08-17 13:44 UTC, pix-service commented
I'm deploying this PR to these urls:

- App (.fr): https://app-pr3344.review.pix.fr
- App (.org): https://app-pr3344.review.pix.org
- Orga: https://orga-pr3344.review.pix.fr
- Certif: https://certif-pr3344.review.pix.fr
- Admin: https://admin-pr3344.review.pix.fr
- API: https://api-pr3344.review.pix.fr/api/

 Please check it out!

2021-08-17 13:55 UTC, Thomasevano approved these changes

2021-08-17 13:59 UTC, sbedeau requested changes, later dismissed
Fonctionnellement, on régresse sur les épreuves focus non embed

2021-08-17 14:15 UTC, VincentHardouin commented
> Fonctionnellement, on régresse sur les épreuves focus non embed

Je ne vois pas de problème, une fois le FT bien activé. Est-ce que tu peux être plus précis ?

2021-08-17 14:24 UTC, sbedeau commented
> > Fonctionnellement, on régresse sur les épreuves focus non embed
> 
> Je ne vois pas de problème, une fois le FT bien activé. Est-ce que tu peux être plus précis ?

Effectivement, le FT n'était probablement pas activé tout à l'heure. 

Sur le plan technique, est-ce que vous avez essayé ça l'approche suivante : 

Dans `launchSimulator` dans le fichier `challenge-embed-simulator` 

```js
iframe.onblur = () => {
  console.log('foo');
};

iframe.onfocus = () => {
  console.log('bar');
};
```

2021-08-17 14:29 UTC, VincentHardouin commented
> Sur le plan technique, est-ce que vous avez essayé ça l'approche suivante :
> 
> Dans `launchSimulator` dans le fichier `challenge-embed-simulator`
> 
> ```js
> iframe.onblur = () => {
>   console.log('foo');
> };
> 
> iframe.onfocus = () => {
>   console.log('bar');
> };
> ```

Tout à fait nous avons essayé, mais cela n'a pas le comportement que l'on souhaite

2021-08-17 14:37 UTC, alexandrecoin requested changes
Sur une épreuve `non-focus` ou si le FT n'est pas activé, le message de sortie d'épreuve apparaît en cas de sortie.

<img width="1022" alt="Capture d’écran 2021-08-17 à 16 36 14" src="https://user-images.githubusercontent.com/36371437/129746161-070563e0-c87b-45bb-84eb-00b141d3e3c2.png">

2021-08-17 15:00 UTC, celineung commented on mon-pix/app/components/challenge-item-generic.js
>    }
**suggestion:** remonter ces hooks au début pour améliorer leur visibilité

2021-08-17 15:01 UTC, sbedeau reviewed
**réflexion :** Je suis opposé à l'utilisation de timer et je pense qu'on doit privilégier la mécanique événementielle mais je ne peux pas argumenter plus que par notre expérience : 
- lisibilité difficile
- les histoires de performance associées
- la baisse de correspondance des tests avec la réalité (on doit stubber en acceptance) 

À défaut pouvoir proposer mieux et à moins de me plonger dedans, je reste au niveau commentaire non bloquant

2021-08-17 15:03 UTC, sbedeau commented
sans me plonger dedans -> abus de langage, désolé

2021-08-17 15:17 UTC, VincentHardouin commented
> Sur une épreuve `non-focus` ou si le FT n'est pas activé, le message de sortie d'épreuve apparaît en cas de sortie.
> 
> <img alt="Capture d’écran 2021-08-17 à 16 36 14" width="1022" src="https://user-images.githubusercontent.com/36371437/129746161-070563e0-c87b-45bb-84eb-00b141d3e3c2.png">

En effet ! Merci c'est corrigé

2021-08-17 15:24 UTC, celineung commented on mon-pix/app/services/focus.js
> +      this.timeout = setTimeout(()=> {
**question:** Est-ce qu'ici on ne créerait pas plusieurs `setTimeout` ?

2021-08-18 07:38 UTC, alexandrecoin approved these changes

2021-08-19 14:44 UTC, MelanieMEB requested changes
KO pour le moment, besoin à vérifier, surtout qu'on n'est pas satisfait de la solution.

2021-08-19 14:44 UTC, MelanieMEB commented on mon-pix/app/services/focus.js
> +      this.timeout = setTimeout(()=> {
Globalement,si ça se fait, je propose de limiter cette approche pour les épreuves avec embed, pour ne pas lancer de timer inutilement.

2021-08-19 14:44 UTC, MelanieMEB commented on mon-pix/app/services/focus.js
> +      }, 100);
Peut être passer à 1000 plutot, peu de risque de triche déjà à ce niveau.

2021-08-23 07:19 UTC, francois2metz commented on mon-pix/app/services/focus.js
> +      this.timeout = setTimeout(()=> {
Je ne suis pas forcément chaud pour avoir des logiques de détection différentes entre les épreuves. J'ai l'impression que cela va beaucoup complexifier les tests du focus.

2021-09-20 15:08 UTC, MelanieMEB commented on mon-pix/app/services/focus.js
> +      this.timeout = setTimeout(()=> {
Suite aux discussions : on met ça partout pour éviter de la complexité et de la gestion de différents cas.

2021-09-21 10:03 UTC, MelanieMEB requested changes

2021-09-21 10:03 UTC, MelanieMEB commented on mon-pix/app/components/challenge/item.js
> +    this.focus.start();
Le focus.start() devrait se faire dans le constructor qui était présent.
```suggestion
```

2021-09-21 10:03 UTC, MelanieMEB commented on mon-pix/app/components/challenge/item.js
> -    }
constructor() {
    super(...arguments);
    if (this.isFocusedChallenge) {
      this.focus.start();
    }

2021-09-21 10:03 UTC, MelanieMEB commented on mon-pix/app/components/challenge/item.js
> -  @tracked hasFocusedOutOfWindow = false || this.args.assessment.hasFocusedOutChallenge;
En passant par le service focus, on n'a plus la mise à zéro par rapport à la BDD de l'état du focus

2021-09-21 10:03 UTC, MelanieMEB commented on mon-pix/app/services/focus.js
> +    this.currentWindowHasFocus = document.hasFocus();
Il faudrait une action en plus quand on perd le focus, pour pouvoir appeler le back (voir l'action `setFocusedOutOfChallenge` du controller assessments)

2021-09-21 13:45 UTC, francois2metz commented on mon-pix/app/services/focus.js
> +    this.currentWindowHasFocus = document.hasFocus();
Je ne suis pas sur de comprendre ce qu'il faut faire. Je ne vois pas d'action spécique pour la window.

2021-11-16 12:58 UTC, closed without merging