[FEATURE] Création du type de campagne 'flash' (PIX-2778).
1024pix/pix pull request #3361
Opened 2021-08-19 13:00 UTC by alexandrecoin

## :unicorn: Problème

Pour tester le nouvel algorithme en cours de développement, certains de nos partenaires vont avoir accès à un nouveau type de campagne, les campagne Flash, qui utiliseront ce nouvel algo et la nouvelle notation.

## :robot: Solution

Rajout, côté back, d'un nouveau type de campagne sur le endpoint de création de campagne.

## :rainbow: Remarques
N/A

## :100: Pour tester

2021-08-19 13:05 UTC, pix-service commented
I'm deploying this PR to these urls:

- App (.fr): https://app-pr3361.review.pix.fr
- App (.org): https://app-pr3361.review.pix.org
- Orga: https://orga-pr3361.review.pix.fr
- Certif: https://certif-pr3361.review.pix.fr
- Admin: https://admin-pr3361.review.pix.fr
- API: https://api-pr3361.review.pix.fr/api/

 Please check it out!

2021-08-20 06:54 UTC, VincentHardouin approved these changes

2021-08-20 12:22 UTC, MelanieMEB requested changes

2021-08-20 12:22 UTC, MelanieMEB commented on api/lib/domain/models/Campaign.js
> +  FLASH: 'FLASH',
Proposition : déplacer cette info dans une colonne `evaluationMethod` avec deux valeurs : simple/flash ? 
`

2021-08-20 12:34 UTC, lisequesnel commented on api/lib/domain/models/Campaign.js
> +  FLASH: 'FLASH',
je dirais plutôt `assessmentMethod` (pour coller avec le type `ASSESSMENT` qui a un `assessmentId`).

2021-08-24 11:52 UTC, lisequesnel commented on api/lib/application/campaigns/campaign-controller.js
> +      assessmentMethod,
**question** : on avait pas dit que c'était un champ qu'on ne sauvegardait pas manuellement pour l'instant ? Si oui, normalement il n'a rien à faire ici, il sera mis par défaut à "simple" à l'insertion directement en base (un peu comme les booléen mis à false par défaut)

2021-08-24 11:55 UTC, lisequesnel commented on api/lib/infrastructure/repositories/campaign-repository.js
> +      'assessmentMethod',
**suggestion (blocking)** : pour moi ce n'est pas un champ qui est modifiable, on ne veut pas modifier en cours de campagne avec quelle modalité on veut évaluer les gens, ils seraient évalués de manière différence, ce qui seraient injuste pour les uns ou pour les autres.

2021-08-24 11:56 UTC, lisequesnel commented on api/lib/infrastructure/repositories/campaign-repository.js
> +      'assessmentMethod',
**suggestion (blocking)** : idem ici, ce n'est pas un champ que l'on gère pour l'instant à la création, si j'ai bien compris

2021-08-24 11:57 UTC, lisequesnel commented on api/lib/domain/read-models/CampaignReport.js
> +    assessmentMethod,
**suggestion (blocking)** : `CampaignReport` est le read model côté Pix Orga qui représente la vision prescripteur de la Campagne. Pour l'instant, nul besoin d'ajouter ce champ dans ce modèle pour moi.

2021-08-24 12:00 UTC, lisequesnel commented on api/lib/infrastructure/repositories/campaign-management-repository.js
> +      'assessmentMethod',
**suggestion (blocking)** : idem, ce champ n'est pas un champ éditable pour les mêmes raison qu'évoquées plus haut, même depuis Pix Admin (`CampaignManagement` est le read-model d'une campagne vue par un PIX_MASTER)

2021-08-24 12:03 UTC, lisequesnel requested changes
globalement, des choses à revoir, on peut refaire un point, peut-être qu'un mob avec des personnes connaissant le fonctionnel sur ce scope ne serait pas plus mal. La team est dispo (et moi de même :) )

Petites remarques supplémentaires (en plus de celles ci-dessus) :
- Mettre à jour le titre et le contenu du la PR ;
- Revoir les commits qui me semblent brouillons (les titres ne reflètent pas forcément leur contenu).

2021-08-27 09:16 UTC, MelanieMEB commented on api/db/migrations/20210823142553_add-column-assessment-method-to-campaigns-table.js
> +const DEFAULT_COLUMN_VALUE = 'SIMPLE';
OK pour le ticket, je me demande juste pour le simple si on trouverait pas un nom plus parlant.

2021-08-27 12:06 UTC, lisequesnel commented on api/db/migrations/20210823142553_add-column-assessment-method-to-campaigns-table.js
> +const DEFAULT_COLUMN_VALUE = 'SIMPLE';
`SMART_RANDOM`, le fameux

2021-08-27 12:08 UTC, lisequesnel commented on api/db/database-builder/factory/build-campaign.js
> +  assessmentMethod = 'SIMPLE',
**question** : Du coup on ne créé pas d'énumération ? `Campaign.assessmentMethods.SIMPLE` ou tout autre nom (cf autre commentaire)

2021-08-30 08:34 UTC, alexandrecoin commented on api/db/database-builder/factory/build-campaign.js
> +  assessmentMethod = 'SIMPLE',
Modifié avec le nom `SMART_RANDOM` qui est en effet plus approprié. :)

2021-08-30 11:56 UTC, lisequesnel commented on api/db/migrations/20210823142553_add-column-assessment-method-to-campaigns-table.js
> +const DEFAULT_COLUMN_VALUE = 'SMART_RANDOM';
**suggestion** : pour éviter tout problème, ce serait mieux de changer cette valeur dans le commit précédent je pense

2021-08-30 11:58 UTC, lisequesnel commented on api/db/database-builder/factory/build-campaign.js
> +  assessmentMethod = Campaign.assessmentMethods.SMART_RANDOM,
**suggestion** : Mettre cette valeur par défaut, uniquement dans le cas des campagnes d'évaluation (dans le if juste en dessous)

2021-08-30 11:58 UTC, lisequesnel approved these changes
validé, modulo les 2 petits retours

2021-08-30 12:19 UTC, MelanieMEB approved these changes
OK avec les commentaires de Lise

2021-08-31 12:15 UTC, merged