[CLEAN] Remplacement des boutons du challenge en PixButton.
1024pix/pix pull request #3369
Opened 2021-08-20 13:34 UTC by MelanieMEB

## :unicorn: Problème
Les boutons de la page Challenge n'était pas des PixButton

## :robot: Solution
Mettre les Pix Button

## :rainbow: Remarques
- Supprimer coté JS les variables pour afficher le loading
- Nettoyer le CSS

## :100: Pour tester
Passer des épreuves, des timés ou focus. 
Timée : 
Focus : 
Revenir en arrière
Vérifier en mobile

2021-08-20 13:41 UTC, pix-service commented
I'm deploying this PR to these urls:

- App (.fr): https://app-pr3369.review.pix.fr
- App (.org): https://app-pr3369.review.pix.org
- Orga: https://orga-pr3369.review.pix.fr
- Certif: https://certif-pr3369.review.pix.fr
- Admin: https://admin-pr3369.review.pix.fr
- API: https://api-pr3369.review.pix.fr/api/

 Please check it out!

2021-08-20 14:38 UTC, Anne-Gaelle-S commented on mon-pix/app/templates/components/challenge-actions.hbs
> +      @isBorderVisible={{true}}
**question**
Je crois que pour un PixButton de color green on a pas besoin du paramètre `isBorderVisible`... est-ce que ça change quelque chose ici ?

2021-08-20 14:40 UTC, Anne-Gaelle-S commented on mon-pix/app/templates/components/challenge-actions.hbs
> +      @isBorderVisible={{true}}
**question**
Idem ici, je suis pas sûre que le `isBorderVisible` ait un effet, dans [la doc Storybook](https://storybook.pix.fr/?path=/docs/basics-button--default) on a :
> Paramètre utilisé seulement quand le backgroundColor est transparent-light ou transparent-dark

2021-08-20 14:42 UTC, Anne-Gaelle-S commented on mon-pix/app/templates/components/challenge-actions.hbs
> +        @isBorderVisible={{true}}
**remarque**
Ici aussi `isBorderVisible` à enlever s'il n'a pas d'effet

2021-08-20 14:46 UTC, Anne-Gaelle-S approved these changes
Merci pour la PR ça nettoie déjà pas mal d'endroit 😍 !
Je compte continuer la suite du remplacement des PixButton dans PixApp dès mercredi prochain, pour voir le ticket c'est : https://1024pix.atlassian.net/browse/PIX-3012 
Sauf si il y a déjà un travail en cours dessus (je changerai de composant PixUI à remplacer ^^)

2021-08-20 15:52 UTC, Thomasevano approved these changes
Le nettoyage de 370 lignes 😍🥳

2021-08-20 16:15 UTC, sbedeau approved these changes
**réflexion :** On a pu voir par le passé (fin de parcours par ex.) que l'ajout d'éléments de PixUI sans encapsulation au sein d'une `div` de positionnement créé un couplage fort. On peut par exemple subir un alignement à gauche au lieu du centre

**suggestion:** faire des encapsulations des `PixButton`

2021-08-20 16:15 UTC, sbedeau commented on mon-pix/tests/integration/components/challenge-actions_test.js
> -});
**question:** Est-ce qu'on ne devrait pas garder ce test ?

2021-08-20 16:24 UTC, sbedeau requested changes
**Fonctionnellement :** 
- Les boutons ne sont plus côte à côte en mobile 
<img width="231" alt="Screenshot 2021-08-20 at 18 18 44" src="https://user-images.githubusercontent.com/46371288/130263598-2d6e07e4-960c-42b9-87b2-a817fca8e3b6.png">

- En timeout, le bouton est vert vs bleu avant (on remarque d'ailleurs qu'il est bleu au retour en arrière)
<img width="446" alt="Screenshot 2021-08-20 at 18 20 23" src="https://user-images.githubusercontent.com/46371288/130264071-6507893f-519e-4787-a0ec-3753b188b151.png">

- Pas eu le temps de tester focus (j'essaie lundi)

2021-08-23 12:39 UTC, MelanieMEB commented on mon-pix/tests/integration/components/challenge-actions_test.js
> -});
Oui, je le remet !

2021-08-24 15:29 UTC, sbedeau approved these changes
Merci pour la prise de retour. Je remarque encore un delta avec l'existant. 
A voir si on est ok avec.

Pour l'histoire de la div encapsulante pour découpler de Pix UI, je ne suis pas bloquant sur le sujet mais qu'en penses tu ?

2021-08-25 07:40 UTC, merged