[TECH] Remplacer les plugins de good, good-console, good-squeeze qui ont été dépréciées par hapi-pino (Pix-3051).
1024pix/pix pull request #3380
Opened 2021-08-23 14:24 UTC by yahyayouness

## :unicorn: Problème
Les plugins good, good-console, good-squeeze ont été déprécié depuis 20/12/2020.

## :robot: Solution
Remplacer les plugins par hapi-pino

## :rainbow: Remarques
Avec hapi-pino on peut customiser facilement l'objet request remontée dans les logs Datadog, ce qui va nous permettre d'avoir une entrée de logs enrichie avec tous les métriques nécessaires qu'on veut monitorer.

## :100: Pour tester
- Lancer l'API en locale.
- Vérifier la sortie des logs.
- Un test est en cours avec Datadog pour voir si on perd pas certaines informations

2021-08-23 14:29 UTC, pix-service commented
I'm deploying this PR to these urls:

- App (.fr): https://app-pr3380.review.pix.fr
- App (.org): https://app-pr3380.review.pix.org
- Orga: https://orga-pr3380.review.pix.fr
- Certif: https://certif-pr3380.review.pix.fr
- Admin: https://admin-pr3380.review.pix.fr
- API: https://api-pr3380.review.pix.fr/api/

 Please check it out!

2021-08-24 07:59 UTC, octo-topi requested changes
:heart: pour cette PR

Comme vu ensemble, il manque pour être iso-production la reprise des stats systèmes (CPU, mémoire,etc) émis par opsy et récupéré par good

Une implémentation possible ici
https://github.com/GradedJestRisk/js-training/blob/master/node/network/incoming/hapi-logging/code/server.js#L96

2021-08-24 10:13 UTC, yahyayouness commented
> ❤️ pour cette PR
> 
> Comme vu ensemble, il manque pour être iso-production la reprise des stats systèmes (CPU, mémoire,etc) émis par opsy et récupéré par good
> 
> Une implémentation possible ici
> https://github.com/GradedJestRisk/js-training/blob/master/node/network/incoming/hapi-logging/code/server.js#L96

Merci je suis dessus, oppsy étant aussu déprécié, je cherche une alternative.

2021-08-24 14:35 UTC, octo-topi commented
> > heart pour cette PR
> > Comme vu ensemble, il manque pour être iso-production la reprise des stats systèmes (CPU, mémoire,etc) émis par opsy et récupéré par good
> > Une implémentation possible ici
> > [https://github.com/GradedJestRisk/js-training/blob/master/node/network/incoming/hapi-logging/code/server.js#L96](https://github.com/GradedJestRisk/js-training/blob/master/node/network/incoming/hapi-logging/code/server.js?rgh-link-date=2021-08-24T10%3A13%3A16Z#L96)
> 
> Merci je suis dessus, oppsy étant aussi déprécié, je cherche une alternative pour y remédier.

J'ai testé ça mais n'ai pas réussi à reproduire les métriques simples existantes de oppsy
https://github.com/radenui/hapi-k8s-health#readme

Je me demande si faire ça depuis Hapi est une bonne idée et s'il ne faudarait pas le faire depuis le conteneur avec prometheus, mais ça devient trop OPS pour moi
https://github.com/GradedJestRisk/js-training/blob/master/node/os/metrics/index.js

2021-08-25 09:41 UTC, yahyayouness commented
> > > heart pour cette PR
> > > Comme vu ensemble, il manque pour être iso-production la reprise des stats systèmes (CPU, mémoire,etc) émis par opsy et récupéré par good
> > > Une implémentation possible ici
> > > [https://github.com/GradedJestRisk/js-training/blob/master/node/network/incoming/hapi-logging/code/server.js#L96](https://github.com/GradedJestRisk/js-training/blob/master/node/network/incoming/hapi-logging/code/server.js?rgh-link-date=2021-08-24T10%3A13%3A16Z#L96)
> > 
> > 
> > Merci je suis dessus, oppsy étant aussi déprécié, je cherche une alternative pour y remédier.
> 
> J'ai testé ça mais n'ai pas réussi à reproduire les métriques simples existantes de oppsy
> https://github.com/radenui/hapi-k8s-health#readme
> 
> Je me demande si faire ça depuis Hapi est une bonne idée et s'il ne faudarait pas le faire depuis le conteneur avec prometheus, mais ça devient trop OPS pour moi
> https://github.com/GradedJestRisk/js-training/blob/master/node/os/metrics/index.js
> 
> Bref, déjà merger cette PR en gardant oppsy ferait baisser le nombre de modules dépréciés, ce serait déjà ça

J'ai remis Oppsy en attendant qu'on trouve mieux. J'avais enlevé du code mort custom qui faisait du prometeus dans l'appli qu'on suspectait à l'origine de memory leak. Ca vaudrait  le coup de revenir dessous et d'avoir un log 

> https://github.com/GradedJestRisk/js-training/blob/master/node/os/metrics/index.js

Yes, j'ai remis oppsy en attendant de trouver mieux. J'avais déjà enlevé du code mort custom qui faisait du prom. On le suspectait à l'origine de mémory leak mais ca vaut le coup de revoir ce qu'on peut garder dans notre contexte.

2021-08-31 14:25 UTC, octo-topi commented
Proposition: documenter le contrat d'interface OPS avec des tests
Il est implémenté actuellement comme ça
https://github.com/hapijs/good/blob/84de11a53ec38795ffe90e20968acbd17fba1f26/lib/utils.js#L118

2021-08-31 15:35 UTC, octo-topi commented
Comparaison DEV/PROD existant (avant PR)
```
NODE_ENV=development npm start
210831/152724.556, (1630423644556:OCTO-TOPI:46069:kt084x99:10000) [response] http://OCTO-TOPI:3000: get / {} 404 (14ms)
``` + couleur

PROD 
```
NODE_ENV=production npm start
{"event":"response","timestamp":1630423776764,"id":"1630423776764:OCTO-TOPI:46259:kt087e5b:10002","instance":"http://OCTO-TOPI:3000","method":"get","path":"/","query":{},"responseTime":3,"statusCode":404,"pid":46259,"httpVersion":"1.1","route":"/{p*}","log":[],"source":{"remoteAddress":"127.0.0.1","userAgent":"curl/7.74.0"},"config":{}}

```

Avec PR
```
NODE_ENV=development npm start
[1630423875190] INFO (46605 on OCTO-TOPI): request completed
    req: {
      "id": "1630423875178:OCTO-TOPI:46605:kt08a00f:10000",
      "method": "get",
      "url": "/",
      "headers": {
        "host": "localhost:3000",
        "user-agent": "curl/7.74.0",
        "accept": "*/*"
      },
      "remoteAddress": "127.0.0.1",
      "remotePort": 35950,
      "request_id": "1630423875178:OCTO-TOPI:46605:kt08a00f:10000"
    }
    res: {
      "statusCode": 404,
      "headers": {
        "content-type": "application/json; charset=utf-8",
        "vary": "origin",
        "access-control-expose-headers": "WWW-Authenticate,Server-Authorization",
        "cache-control": "no-cache",
        "content-length": 60
      }
    }
    responseTime: 12
```

PROD 
```
NODE_ENV=production npm start
{"level":30,"time":1630423992730,"pid":46710,"hostname":"OCTO-TOPI","req":{"id":"1630423992712:OCTO-TOPI:46710:kt08cj2s:10000","method":"get","url":"/","headers":{"host":"localhost:3000","user-agent":"curl/7.74.0","accept":"*/*"},"remoteAddress":"127.0.0.1","remotePort":35952,"request_id":"1630423992712:OCTO-TOPI:46710:kt08cj2s:10000"},"req":{"id":"1630423992712:OCTO-TOPI:46710:kt08cj2s:10000","method":"get","url":"/","headers":{"host":"localhost:3000","user-agent":"curl/7.74.0","accept":"*/*"},"remoteAddress":"127.0.0.1","remotePort":35952,"request_id":"1630423992712:OCTO-TOPI:46710:kt08cj2s:10000"},"res":{"statusCode":404,"headers":{"content-type":"application/json; charset=utf-8","vary":"origin","access-control-expose-headers":"WWW-Authenticate,Server-Authorization","cache-control":"no-cache","content-length":60}},"responseTime":18,"msg":"request completed"}
```

2021-09-02 08:28 UTC, octo-topi approved these changes

2021-09-03 09:14 UTC, merged