[CLEANUP] Refonte UX de l'affichage des signalement dans Pix Admin (PIX-3002)
1024pix/pix pull request #3421
Opened 2021-08-31 08:32 UTC by Giroteti

## :unicorn: Problème
Dans un souci de rapidité, l'affichage des signalements dans Pix Admin avait été fait de façon assez brute. De plus, le message de résolution des signalements impactants n'était pas fait. 

## :robot: Solution
Refondre l'UX de cette section dans Pix Admin en incluant le message de résolution.

## :rainbow: Remarques
R.A.S

## :100: Pour tester
- Se rendre sur une session de certification comprenant des signalement.

ou :
- créer une session
- inscrire un candidat
- passer la certif (en répondant faux à différentes questions ayant des images, des applications, etc et en prenant soin de noter le numéro de ces questions) 
- finaliser la session en ajoutant des signalements (non impactants, impactants auto et non-impactants)
- se rendre dans Pix Admin et constater le bon affichage des signalement.

2021-08-31 08:37 UTC, pix-service commented
I'm deploying this PR to these urls:

- App (.fr): https://app-pr3421.review.pix.fr
- App (.org): https://app-pr3421.review.pix.org
- Orga: https://orga-pr3421.review.pix.fr
- Certif: https://certif-pr3421.review.pix.fr
- Admin: https://admin-pr3421.review.pix.fr
- API: https://api-pr3421.review.pix.fr/api/

 Please check it out!

2021-08-31 08:39 UTC, P-Jeremy commented on admin/app/components/certification/certification-issue-report.hbs
> +</li>
Il manque un saut de ligne :p

2021-08-31 08:42 UTC, P-Jeremy commented on admin/app/templates/authenticated/certifications/certification/informations.hbs
>            <h5 class="card-title">
A voir avec @iwazaru, notre spécialiste a11y, mais il me semble que les niveaux de titres ne doivent pas s'enchaîner avec des trous. Genre si pas de h1, h2, h3, h4 dans la page, passer à un h5 peut perturber les lecteurs d'écran

2021-08-31 08:48 UTC, Giroteti commented on admin/app/styles/authenticated/certifications/certification/informations.scss
> +        margin: 0;
ça c'est dupliqué mais si je le remonte d'un cran (dans `&__subtitle`) ça s'applique pas. Normal @iwazaru ?

2021-08-31 08:48 UTC, Giroteti commented on admin/app/styles/components/certification-issue-report.scss
> +      margin-bottom: 24px;
idem que https://github.com/1024pix/pix/pull/3421/files#r699117586

2021-08-31 08:50 UTC, Giroteti commented on admin/app/templates/authenticated/certifications/certification/informations.hbs
>            <h5 class="card-title">
Vu avec lui, il a recommandé de continuer à faire ce qui est fait sur la page (qui utilise des h5/h6 dans d'autres cards alors que h1/2/3/4 ne sont pas présent).

2021-08-31 08:50 UTC, Giroteti commented on admin/app/templates/authenticated/certifications/certification/informations.hbs
> +              <Certification::CertificationIssueReport @isImpactful={{true}} @issueReport={{issueReport}}/>
voir si l'info de `isImpactful` n'est pas déjà présent dans l'`issueReport`

2021-08-31 08:52 UTC, P-Jeremy commented on admin/app/styles/authenticated/certifications/certification/informations.scss
> +        margin: 0;
y'a pas un rapport avec le poids des selecteurs CSS ?

https://www.w3schools.com/css/css_specificity.asp

2021-08-31 08:52 UTC, Giroteti commented on admin/app/styles/authenticated/certifications/certification/informations.scss
> +        color: #A95800;
Si les couleurs n'existent pas dans le fichier `palette`, faut-il que je les ajoute ? Si oui avec quels noms ? @iwazaru

2021-08-31 08:53 UTC, Giroteti commented on admin/app/styles/authenticated/certifications/certification/informations.scss
> +        font-size: 1rem;
Est-ce qu'il a des const quelque part pour les tailles de texte ? @iwazaru

2021-08-31 08:54 UTC, Giroteti commented on admin/app/styles/authenticated/certifications/certification/informations.scss
> +        color: #505F79;
idem que https://github.com/1024pix/pix/pull/3421/files#r699121002

2021-08-31 09:05 UTC, aceol commented on admin/app/styles/authenticated/certifications/certification/informations.scss
> +        color: #A95800;
Elles sont définies par pix-ui [_colors.scss](https://github.com/1024pix/pix-ui/blob/38d761f27a338523957a63187138207126c34e44/addon/styles/_colors.scss)
$yellow-alert-light: #FFF1C5;
$yellow-alert-dark: #A95800;

2021-08-31 09:10 UTC, aceol commented on admin/app/styles/authenticated/certifications/certification/informations.scss
> +        color: #505F79;
Elles sont définies par pix-ui _colors.scss
```css
grey-60: #505F79;
$grey-10: #F4F5F7;
```

2021-08-31 09:20 UTC, sroccaserra approved these changes
Ok pour moi quand les tests front Pix Admin seront corrigés

2021-08-31 09:33 UTC, Giroteti commented on admin/app/styles/authenticated/certifications/certification/informations.scss
> +        margin: 0;
Je pense pas, je pense que c'est parce que le certification-informations__certification-issue-reports__subtitle--with-action-required

et

certification-informations__certification-issue-reports__subtitle--without-action-required

apparaissent bien dans des attributs class dans le template mais `certification-informations__certification-issue-reports__subtitle` (sans _modifier_) n'apparait pas en tant que tel. J'avais cru que ça faisait de l'héritage mais c'est simplement une facilité de notation.

Mais du coup peut-être faut qu'il que je leur colle plusieurs classes, l'une pour les attributs communs et l'autre QUE pour les _modifiers_... 🤔

@aceol @iwazaru ?

2021-08-31 09:47 UTC, iwazaru requested changes

2021-08-31 09:47 UTC, iwazaru commented on admin/app/components/certification/certification-issue-report.hbs
> +    <FaIcon class="certification-issue-report__resolution-status--unresolved" @icon="times-circle"/>
Ici il y a une information qui n'est transmise que par une icône, il faut ajouter un `aria-label` avec un texte pour l'expliciter pour les lecteurs d'écran. Attention je crois que FaIcon a un `aria-hidden=true` par défaut qu'il faudrait annuler du coup.

2021-08-31 09:47 UTC, iwazaru commented on admin/app/templates/authenticated/certifications/certification/informations.hbs
> +    </PixButton>
🤷🏻

2021-08-31 09:47 UTC, iwazaru commented on admin/app/templates/authenticated/certifications/certification/informations.hbs
>            <h5 class="card-title">
@P-Jeremy a raison, j'avais supposé qu'il y avait des h1/2/3/4 sur la page mais en leur absence, ce n'est pas valide.
CECI DIT, ce serait absurde de le faire juste à cet endroit alors qu'il y a d'autres h5 sur la page, donc je propose de garder ça pour quand on fera une passe a11y sur cette page.

2021-08-31 09:47 UTC, iwazaru commented on admin/app/styles/authenticated/certifications/certification/informations.scss
> +        margin: 0;
C'est exactement ça il faut `certification-informations__certification-issue-reports__subtitle` et `certification-informations__certification-issue-reports__subtitle--with-action-required`

2021-08-31 09:47 UTC, iwazaru commented on admin/app/styles/authenticated/certifications/certification/informations.scss
> +        color: #A95800;
Pour info il y a la référence des couleurs avec leur nom sur :
https://zeroheight.com/8dd127da7/p/839645-couleurs/b/21317a

2021-08-31 09:47 UTC, iwazaru commented on admin/app/templates/authenticated/certifications/certification/informations.hbs
> +                                                   @label="Terminée le :"/>
Pinaillage : il y a beaucoup de "bruits" dans le diff à cause de ce que j'imagine être le formatteur auto de l'IDE à cause de lignes trop longues. Je serais d'avoir de retirer ce qui n'a pas de rapport avec la PR ou de le faire au moins de façon cohérente (comme plus bar, un attribut/argument par ligne)

2021-08-31 09:51 UTC, iwazaru commented on admin/app/styles/authenticated/certifications/certification/informations.scss
> +        font-size: 1rem;
Pour info : `rem` agit comme une const car ça signifie "100 % de la taille par défaut de la page".

2021-09-01 08:18 UTC, laura-bergoens approved these changes
Wouah c'est beau !

2021-09-01 10:21 UTC, iwazaru approved these changes

2021-09-01 12:31 UTC, merged

2021-09-07 15:41 UTC, Anne-Gaelle-S commented on admin/tests/integration/components/routes/authenticated/certifications/certification/informations_test.js
> +          //await this.pauseTest();
👻

2021-09-07 15:47 UTC, Giroteti commented on admin/tests/integration/components/routes/authenticated/certifications/certification/informations_test.js
> +          //await this.pauseTest();
Ah, mea culpa...