[BUGFIX] Ajout la création de la base de donnée dans le script configure
1024pix/pix pull request #3436
Opened 2021-09-01 15:56 UTC by frinyvonnick

## :unicorn: Problème
Suite à la pull request #3255 l'éxécution du docker-compose ne créer plus la base de donnée. Le script `configure` ne fonctionne plus pour une première installation.

## :robot: Solution
Dans la fonction **setup_and_run_infrastructure** on remplace l'appel du script `db:migrate` par le script `db:prepare` qui inclut la migration ainsi que le création/re-création de la base de donnée.

## :rainbow: Remarques
> _Des infos supplémentaires, trucs et astuces ?_

## :100: Pour tester
Supprimez vos conteneurs et lancer le script `configure`.

2021-09-01 16:01 UTC, pix-service commented
I'm deploying this PR to these urls:

- App (.fr): https://app-pr3436.review.pix.fr
- App (.org): https://app-pr3436.review.pix.org
- Orga: https://orga-pr3436.review.pix.fr
- Certif: https://certif-pr3436.review.pix.fr
- Admin: https://admin-pr3436.review.pix.fr
- API: https://api-pr3436.review.pix.fr/api/

 Please check it out!

2021-09-01 16:38 UTC, octo-topi requested changes
J'ai supprimé les conteneurs et lancé le script.. et c'est KO :cry: 
`npm run configure`

```
> pix-api@3.93.0 db:migrate /home/topi/Documents/OCTO/Missions/Pix/code/repo/pix/api
> knex --knexfile db/knexfile.js migrate:latest

Working directory changed to ~/Documents/OCTO/Missions/Pix/code/repo/pix/api/db
Using environment: development
error: database "pix" does not exist
    at Function.get (/home/topi/Documents/OCTO/Missions/Pix/code/repo/pix/api/node_modules/knex/lib/knex-builder/make-knex.js:43:26)
    at getSchemaBuilder (/home/topi/Documents/OCTO/Missions/Pix/code/repo/pix/api/node_modules/knex/lib/migrations/migrate/table-creator.js:61:17)
    at ensureTable (/home/topi/Documents/OCTO/Missions/Pix/code/repo/pix/api/node_modules/knex/lib/migrations/migrate/table-creator.js:11:10)
    at listCompleted (/home/topi/Documents/OCTO/Missions/Pix/code/repo/pix/api/node_modules/knex/lib/migrations/migrate/migration-list-resolver.js:12:9)
    at Object.listAllAndCompleted (/home/topi/Documents/OCTO/Missions/Pix/code/repo/pix/api/node_modules/knex/lib/migrations/migrate/migration-list-resolver.js:28:5)
    at Migrator.latest (/home/topi/Documents/OCTO/Missions/Pix/code/repo/pix/api/node_modules/knex/lib/migrations/migrate/Migrator.js:64:57)
    at Command.<anonymous> (/home/topi/Documents/OCTO/Missions/Pix/code/repo/pix/api/node_modules/knex/bin/cli.js:232:55)
npm ERR! code ELIFECYCLE

```

2021-09-01 17:42 UTC, frinyvonnick commented
En refaisant un test, j'ai une autre erreur de ce type : 
![image](https://user-images.githubusercontent.com/13099512/131718449-2b077612-bb10-4075-bfb2-9380981f6299.png)

2021-09-02 07:33 UTC, Thomasevano commented
> Mon .env
> 
> ```
> DATABASE_URL=postgresql://postgres@localhost/pix
> TEST_DATABASE_URL=postgresql://postgres@localhost/pix_test
> ```
> 
> J'ai supprimé les conteneurs et lancé le script.. et c'est KO 😢
> `npm run configure`
> 
> ```
> > pix-api@3.93.0 db:migrate /home/topi/Documents/OCTO/Missions/Pix/code/repo/pix/api
> > knex --knexfile db/knexfile.js migrate:latest
> 
> Working directory changed to ~/Documents/OCTO/Missions/Pix/code/repo/pix/api/db
> Using environment: development
> error: database "pix" does not exist
>     at Function.get (/home/topi/Documents/OCTO/Missions/Pix/code/repo/pix/api/node_modules/knex/lib/knex-builder/make-knex.js:43:26)
>     at getSchemaBuilder (/home/topi/Documents/OCTO/Missions/Pix/code/repo/pix/api/node_modules/knex/lib/migrations/migrate/table-creator.js:61:17)
>     at ensureTable (/home/topi/Documents/OCTO/Missions/Pix/code/repo/pix/api/node_modules/knex/lib/migrations/migrate/table-creator.js:11:10)
>     at listCompleted (/home/topi/Documents/OCTO/Missions/Pix/code/repo/pix/api/node_modules/knex/lib/migrations/migrate/migration-list-resolver.js:12:9)
>     at Object.listAllAndCompleted (/home/topi/Documents/OCTO/Missions/Pix/code/repo/pix/api/node_modules/knex/lib/migrations/migrate/migration-list-resolver.js:28:5)
>     at Migrator.latest (/home/topi/Documents/OCTO/Missions/Pix/code/repo/pix/api/node_modules/knex/lib/migrations/migrate/Migrator.js:64:57)
>     at Command.<anonymous> (/home/topi/Documents/OCTO/Missions/Pix/code/repo/pix/api/node_modules/knex/bin/cli.js:232:55)
> npm ERR! code ELIFECYCLE
> ```

Le `db:prepare` fait un drop de la db avant d'en créer une nouvelle du coup lors du premier lancement du projet il ne trouve de db

2021-09-02 07:35 UTC, frinyvonnick commented
J'ai repassé en work in progress, parce qu'il semble que j'ai pas bien suivi ma procédure de test et en plus j'ai une autre erreur qui arrive chez moi cf https://github.com/1024pix/pix/pull/3436#issuecomment-910508995

2021-09-02 07:36 UTC, Thomasevano commented
Pour moi sur MAC tout a bien marcher. Peut etre qu'a la place d'un `db:prepare` on pourrait mettre les étapes un `db:create` et un `db:migrate` une par une a la suite.

2021-09-02 07:53 UTC, frinyvonnick commented
L'erreur que j'ai de mon côté est une erreur de connexion à la base de données qui arrive uniquement quand je drop le conteneur pg avant 🤔  J'investigue.

2021-09-02 13:14 UTC, frinyvonnick commented
Quelques changements ont été apportés : 

- Les conteneurs sont re-créer au moment du `up`
- Le script `db:reset` est utilisé à la place de `db:prepare`. Il inclut le chargement des seed donc la fonction `load_seed` a été supprimé.
- Un refacto a été réalisé pour corriger quelques soucis d'asynchronisme avec la class `PgClient`.

2021-09-02 17:24 UTC, Thomasevano approved these changes

2021-09-03 08:37 UTC, octo-topi commented on scripts/configure.sh
> +  timeout 20s bash -c "until docker exec pix_postgres_1 pg_isready ; do sleep 1 ; done"
Ah trop coop ! 
J'utilise ça sur mes project perso, mais ça suppose que le client pl soit installé en local, et ça ne gère pas le timeout
```bash
until pg_isready -h localhost -p 5432 -U postgres -d database
do
  echo "Database is not ready, next try in 10 s"
  sleep 10;
done
```

Reste à voir si perl est installé sur Windows. Qui a un Windows ici ?

2021-09-03 08:38 UTC, octo-topi reviewed
C'est bon pour moi :tada:  !
```
Working directory changed to ~/Documents/OCTO/Missions/Pix/code/repo/pix/api/db
Using environment: development
Batch 1 run: 308 migrations
✅ Database created

Loading seed data

> pix-api@3.93.0 db:seed /home/topi/Documents/OCTO/Missions/Pix/code/repo/pix/api
> knex --knexfile db/knexfile.js seed:run

```

2021-09-03 08:39 UTC, octo-topi approved these changes

2021-09-03 08:40 UTC, octo-topi commented
> Quelques changements ont été apportés :
> 
>     * Les conteneurs sont re-créer au moment du `up`
> 
>     * On attend explicitement que le container postgres soit prêt à recevoir des requêtes
> 
>     * Le script `db:reset` est utilisé à la place de `db:prepare`. Il inclut le chargement des seed donc la fonction `load_seed` a été supprimé.
> 
>     * Un refacto a été réalisé pour corriger quelques soucis d'asynchronisme avec la class `PgClient` (feat **team prescription** pray ).
> 
> 
> Pour tester il n'y a plus besoin de supprimer ses conteneurs. Il suffit de lancer `npm run configure`.

J'arive après la bataille, mais pour info y'a [moyen](https://www.postgresql.org/docs/current/sql-dropdatabase.html) de faire 
`DROP DATABASE IF EXISTS pix`

2021-09-03 08:42 UTC, frinyvonnick commented on scripts/configure.sh
> +  timeout 20s bash -c "until docker exec pix_postgres_1 pg_isready ; do sleep 1 ; done"
@xav-car est en train de tester 😄

2021-09-03 08:42 UTC, xav-car commented
Sous Windows

- sans container  👍
- avec container 👍

2021-09-03 08:43 UTC, xav-car approved these changes

2021-09-03 09:49 UTC, merged