[FEATURE] Ajout de l'infobulle sur les épreuves non-focus (PIX-2882).
1024pix/pix pull request #3476
Opened 2021-09-09 15:51 UTC by alexandrecoin

## :unicorn: Problème

A l'heure actuelle nous informons les utilisateurs des règles des épreuves via une infobulle uniquement pour les épreuves focus.
Nous souhaitons ajouter ce comportement pour les autres types d'épreuves.

## :robot: Solution

• Ajout d'un nouveau paramètre `other` dans la route associée.
• Nouvelles conditions de rendu pour les épreuves non-focus.

## :rainbow: Remarques

A l'heure actuelle, le caractère focus des épreuves sur Airtable est défini par un `boolean`. 
Nous pensons que nous allons rencontrer des difficultés avec l'implémentation actuelle si d'autres types d'épreuves venaient à être ajoutées.

## :100: Pour tester

• Se connecter sur mon-pix
• Réaliser du positionnement
• Vérifier sur les épreuves focus et non-focus : 
- Qu'une infobulle et un overlay apparaissent lors du premier passage sur l'épreuve
- Que ceux-ci disparaissent en cliquant sur `confirmer`
- Qu'il est possible de faire réapparaitre et disparaitre l'infobulle en survolant l'icône en haut à droite de l'épreuve
- Qu'il est possible de naviguer au clavier sur les épreuves

2021-09-09 15:57 UTC, pix-service commented
I'm deploying this PR to these urls:

- App (.fr): https://app-pr3476.review.pix.fr
- App (.org): https://app-pr3476.review.pix.org
- Orga: https://orga-pr3476.review.pix.fr
- Certif: https://certif-pr3476.review.pix.fr
- Admin: https://admin-pr3476.review.pix.fr
- API: https://api-pr3476.review.pix.fr/api/

 Please check it out!

2021-09-13 09:34 UTC, celineung requested changes

2021-09-13 09:34 UTC, celineung commented on api/tests/integration/application/users/index_test.js
> +    it('should return ', async function() {
```suggestion
    it('should return 200 when challengeType is valid', async function() {
```

2021-09-13 09:45 UTC, VincentHardouin commented on mon-pix/app/components/challenge/statement/tooltip.js
> +    }
```suggestion
    if (this.isFocusedChallenge && this._hasUserSeenFocusedChallengeTooltip()) {
      this.shouldDisplayTooltip = value;
    } else if (!this.isFocusedChallenge && this._hasUserSeenOtherChallengesTooltip()) {
      this.shouldDisplayTooltip = value;
    } else if (!this._isUserConnected()) {
      this.shouldDisplayTooltip = value; 
    }
```

2021-09-13 14:07 UTC, sbedeau approved these changes
Ok tech et fonc

2021-09-13 14:07 UTC, ghost commented on api/lib/application/users/index.js
> +            challengeType: Joi.string().valid('focused', 'other'),
**question:** Quels sont les scenarii dans lesquels on pourrait se retrouver avec d'autres types de challenges que `focused` et `other` ?

2021-09-13 14:07 UTC, ghost commented on mon-pix/app/components/challenge-item-generic.js
> +
**suggestion(non bloquante):** Pour faciliter la lecture  
```suggestion
  _hasUserNotSeenFocusedChallengeTooltip() {
    return this.args.isFocusedChallenge && this.currentUser.user && !this.currentUser.user.hasSeenFocusedChallengeTooltip;
  }

  _hasUserNotSeenOtherChallengesTooltip() {
    return !this.args.isFocusedChallenge && this.currentUser.user && !this.currentUser.user.hasSeenOtherChallengesTooltip;
  }

```

2021-09-14 09:01 UTC, alexandrecoin commented on api/lib/application/users/index.js
> +            challengeType: Joi.string().valid('focused', 'other'),
Normalement aucun mais nous avons préféré explicité et vérifié dès le point d'entrée les différentes valeurs admises. 🙂

2021-09-14 13:36 UTC, celineung approved these changes

2021-09-15 08:40 UTC, alexandrecoin commented
En attente de la traduction de l'infobulle.

2021-09-16 09:20 UTC, MelanieMEB requested changes
J'ai eu un ptit soucis fonc :
- J'ai recréé un compte et passer la compétence 1.1
- J'ai vu le j'ai compris pour les non focus, avec le grisé derrière.
- Puis j'ai eu le "J'ai compris" sur les focus, mais pas de grisé derrière

2021-09-16 15:08 UTC, MelanieMEB approved these changes
Soucis d'overlay remonté : il va être supprimé :)

2021-09-17 14:24 UTC, MelanieMEB commented on mon-pix/translations/en.json
> +          "other": "Essayez de répondre à cette question en recherchant sur internet ou avec l'aide d'une application externe."
```suggestion
          "other": "To answer this question, feel free to search the internet or use an external application."
```

2021-09-20 07:13 UTC, merged