[BUGFIX] Supprimer le double appel à getNextChallenge (PIX-2760).
1024pix/pix pull request #3491
Opened 2021-09-15 10:04 UTC by celineung

## :unicorn: Problème
Lorsque l'on arrive sur une nouvelle épreuve via les bouton je passe / je valide ou via la page de compétence, on remarque que deux appels à l'api sont faits pour récupérer la prochaine épreuve:
- un appel depuis `assessments.resume` pour savoir si une prochaine épreuve existe (pour pouvoir ensuite rediriger sur le checkpoint final si ce n'est pas le cas)
- un appel depuis `assessments.challenge` pour récupérer le contenu de l'épreuve

## :robot: Solution
1. Supprimer l'appel fait dans `assessments.resume` --> on arrive alors toujours sur une épreuve
2. Si l'épreuve est null, alors on redirige sur `assessments.resume` qui fait son routage vers le checkpoint final

## :rainbow: Remarques
Petit problème sur le transition.to: il ne faut pas lui mettre de `return` devant !
Cela ne posait pas de problème avant la PR car l'appel à getNextChallenge de `assessments.resume` prenait du temps et ça laissait le temps à transitionTo de finir.

## :100: Pour tester
Passer des épreuves et voir qu'un seul appel à /next est fait.

2021-09-15 10:09 UTC, pix-service commented
I'm deploying this PR to these urls:

- App (.fr): https://app-pr3491.review.pix.fr
- App (.org): https://app-pr3491.review.pix.org
- Orga: https://orga-pr3491.review.pix.fr
- Certif: https://certif-pr3491.review.pix.fr
- Admin: https://admin-pr3491.review.pix.fr
- API: https://api-pr3491.review.pix.fr/api/

 Please check it out!

2021-09-15 10:20 UTC, VincentHardouin approved these changes
Trop cool ! Pour rappel la route `/assessment/{id}/next`, c'est 31 M d'appels sur 15j représentant 20% des appels API, et là on va le réduire à 10% !

2021-09-16 09:00 UTC, alexandrecoin commented on mon-pix/app/routes/assessments/challenge.js
> +    if (challenge == null) {
```suggestion
    if (challenge === null) {
```

2021-09-16 09:02 UTC, alexandrecoin approved these changes

2021-09-16 14:20 UTC, MelanieMEB requested changes
OK fonctionnellement et sur l'approche.
Par contre KO fonctionnel sur les preview, les valider provoque une erreur.

2021-09-17 09:41 UTC, celineung commented on mon-pix/app/routes/assessments/challenge.js
> +    if (challenge == null) {
j'ai corrigé en:

```
if (!challenge) {
```

2021-09-20 08:25 UTC, MelanieMEB approved these changes

2021-09-20 08:40 UTC, merged