[FEATURE] Page de vérification de code pour un changement d'email (PIX-2892)
1024pix/pix pull request #3505
Opened 2021-09-17 09:40 UTC by Anne-Gaelle-S

## :unicorn: Problème
Dans le cadre de l'epix de vérification d'email nous envoyons par email un code de vérification.
Actuellement il est possible de demander un changement d'email et le code est envoyé par email.
Il faut ensuite pouvoir rentrer ce code de vérification sur l'app.

## :robot: Solution
Implémenter la page de code de vérification.

## :rainbow: Remarques
L'epix de vérification d'email est soumise à feature toggle

## :100: Pour tester
API : 
- `FT_VALIDATE_EMAIL=true npm start -- --watch` 
Pix APP : 
- Mon compte
- Méthodes de connexions
- Changer d'email
- Remplir le formulaire
- Constater qu'on arrive sur la page qui demande un code de vérification.

2021-09-17 09:45 UTC, pix-service commented
I'm deploying this PR to these urls:

- App (.fr): https://app-pr3505.review.pix.fr
- App (.org): https://app-pr3505.review.pix.org
- Orga: https://orga-pr3505.review.pix.fr
- Certif: https://certif-pr3505.review.pix.fr
- Admin: https://admin-pr3505.review.pix.fr
- API: https://api-pr3505.review.pix.fr/api/

 Please check it out!

2021-09-22 09:45 UTC, yschoueri approved these changes

2021-09-22 13:04 UTC, AndreiaPena commented on mon-pix/translations/en.json
> +      "description": "Saisissez le code de vérification reçu à l'adresse e-mail",
**chipotage**:
```suggestion
      "description": "Saisissez le code de vérification reçu à l'adresse e-mail :",
```

2021-09-22 15:01 UTC, yschoueri commented on mon-pix/translations/en.json
> +      "description": "Saisissez le code de vérification reçu à l'adresse e-mail",
done

2021-09-23 08:00 UTC, AndreiaPena commented on mon-pix/app/adapters/email-verification-code.js
> +    const userId = this.currentUser.user.get('id');
🎉

2021-09-23 08:49 UTC, AndreiaPena commented
**Remarques** : 

Comme il y a eu des changements sur la première page avec les champs adresse e-mail et mot de passe, je les partage ici. 
A voir si ça ne doit pas être fait sur une autre PR 🙂

Version desktop : D'après Abstract on a un espace de 24px entre les boutons et le bord en bas. Actuellement on a juste un padding de 14px.

<img width="686" alt="Capture d’écran 2021-09-23 à 10 43 29" src="https://user-images.githubusercontent.com/58915422/134478713-0449bb6a-3386-40a3-86d9-bf1a33bf1f90.png">

Version desktop : Comme le bouton en haut à droite a été supprimé, la bordure et le message sont plus proche du bord de droite sur Abstract. Il faut modifier ça. 

<img width="686" alt="Capture d’écran 2021-09-23 à 10 44 25" src="https://user-images.githubusercontent.com/58915422/134478869-d2ac562f-d2ca-4f94-be4e-e453d5347236.png">

[Abstract](https://app.abstract.com/projects/3e4937ef-48a8-408b-9edd-1f69dab81b39/branches/b9430a8a-50a7-4f5b-ae15-1c791e4c3ba5/collections/982a8957-6ce1-48ea-aa75-7d7399553b0e)

2021-09-23 09:11 UTC, AndreiaPena commented
Testé fonctionnellement ( en version anglaise aussi ) + accessibilité ✅

2021-09-23 09:28 UTC, AndreiaPena requested changes

2021-09-23 09:28 UTC, AndreiaPena commented on mon-pix/app/controllers/user-account/connection-methods.js
> +    this.model.email = newEmail.trim().toLowerCase();
**Remarque** : 
Je crois qu'on a un soucis avec ça. En passant la nouvelle adresse e-mail dans le model, si on annule après avoir passé cette étape on obtient ça : 

J'utilise le seed `sco.admin@example.net`, je met `andreia.pena+hello@pix.fr` et mon mot de passe, j'atteint la deuxième page avec le code et j'annule.

<img width="686" alt="Capture d’écran 2021-09-22 à 14 56 31" src="https://user-images.githubusercontent.com/58915422/134483799-41b4b1f7-1499-41b0-ae4b-6ee4e8b5c159.png">

Un rafraîchissement de ma page remet l'adresse actuelle, mais d'un point de vue ux, l'utilisateur ne va pas comprendre et surtout aura l'impression d'avoir fait le changement alors que non.

2021-09-23 09:28 UTC, thloesch commented
Au bout de 5 secondes, le message me proposant de renvoyer le code n'est pas cliquable.
C'est prévu dans une autre PR ?

<img width="291" alt="Capture d’écran 2021-09-23 à 11 27 48" src="https://user-images.githubusercontent.com/46494361/134484399-db0eb1ae-52df-45a6-8401-409a557db6e0.png">

2021-09-23 09:30 UTC, thloesch commented on mon-pix/app/controllers/user-account/connection-methods.js
> +    this.model.email = newEmail.trim().toLowerCase();
J'étais en train d'écrire exactement le même retour 👍

2021-09-23 09:36 UTC, yschoueri commented
> Au bout de 5 secondes, le message me proposant de renvoyer le code n'est pas cliquable.
> C'est prévu dans une autre PR ?
> 
> <img alt="Capture d’écran 2021-09-23 à 11 27 48" width="291" src="https://user-images.githubusercontent.com/46494361/134484399-db0eb1ae-52df-45a6-8401-409a557db6e0.png">

Yes on avait cree une story mais je ne la retrouve plus dans le jira lol

2021-09-23 09:40 UTC, AndreiaPena commented on mon-pix/app/components/user-account/email-verification-code.hbs
> +  <h1 class="user-account__validation-title">{{t 'pages.email-verification.title'}}</h1>
**Question** : Même chose pour la page précédente en fait... Mais je me pose la question que maintenant 😅
 Est-ce nécessaire que ce soit des `h1` ici alors que sur la page on a déjà le Mon Compte en `h1` ? 🧐
 
<img width="1038" alt="Capture d’écran 2021-09-23 à 11 39 53" src="https://user-images.githubusercontent.com/58915422/134485967-4b83cefa-7a7f-41b9-9f3b-8f3b5752cc14.png">

2021-09-23 09:51 UTC, AndreiaPena commented on mon-pix/translations/fr.json
> +    },
Remarque : Le pixIconButton n'étant plus utilisé, il faut supprimer la clé de traduction de son aria-label.

```
"cancel-button": {
          "aria-label": "Fermer"
        },
```

qui se trouve dans "account-update-email-with-validation"

2021-09-23 12:16 UTC, yschoueri commented on mon-pix/app/components/user-account/email-verification-code.hbs
> +  <h1 class="user-account__validation-title">{{t 'pages.email-verification.title'}}</h1>
good point!

2021-09-23 12:32 UTC, thloesch commented on mon-pix/config/environment.js
> +      WAIT_TIME_RESEND_CODE_MS: _getEnvironmentVariableAsNumber({ environmentVariableName: 'WAIT_TIME_RESEND_CODE_MS', defaultValue: 5000, minValue: 0 }),
*Suggestion* Pour une variable exposée à toutes les équipes, je trouve son nommage pas super clair, et on peut éviter les diminutifs.

Je propose `MILLISECONDS_BEFORE_MAIL_RESEND` pour suivre le standard des autres variables type `DAY_BEFORE_...`
Ou `MAIL_RESEND_DELAY_IN_MILLISECONDS` qui me va aussi.

2021-09-23 12:35 UTC, thloesch commented on mon-pix/tests/unit/controllers/user-account/connection-methods_test.js
> +    it('should update user email on sendVerificationCode', async function() {
*Remarque* Suite au commentaire d' @AndreiaPena , ce test ne semble pas approprié.

Il faudrait que le mail soit modifié après validation et non après envoi du code de validation

2021-09-23 14:08 UTC, yschoueri commented on mon-pix/app/controllers/user-account/connection-methods.js
> +    this.model.email = newEmail.trim().toLowerCase();
fixed

2021-09-23 14:09 UTC, yschoueri commented on mon-pix/config/environment.js
> +      WAIT_TIME_RESEND_CODE_MS: _getEnvironmentVariableAsNumber({ environmentVariableName: 'WAIT_TIME_RESEND_CODE_MS', defaultValue: 5000, minValue: 0 }),
done

2021-09-23 14:20 UTC, yschoueri commented on mon-pix/tests/unit/controllers/user-account/connection-methods_test.js
> +    it('should update user email on sendVerificationCode', async function() {
fixed

2021-09-24 07:59 UTC, AndreiaPena approved these changes

2021-09-24 09:49 UTC, thloesch approved these changes

2021-09-24 10:04 UTC, merged