[FEATURE] Mettre à jour les informations d'un centre de certifications depuis Pix Admin (PIX-3478)
1024pix/pix pull request #3509
Opened 2021-09-17 14:08 UTC by Libouk

## :unicorn: Problème
> _Décrivez ici le besoin ou l'intention couvert par cette Pull Request._

## :robot: Solution
> _Ajoutez à cet endroit, si nécessaire, des détails concernant la solution technique retenue et mise en oeuvre, des difficultés ou problèmes rencontrés._

## :rainbow: Remarques
> _Des infos supplémentaires, trucs et astuces ?_

## :100: Pour tester
> _Les instructions pour reproduire le problème, les profils de test, le parcours spécifique à utiliser, etc._

2021-09-17 14:13 UTC, pix-service commented
I'm deploying this PR to these urls:

- App (.fr): https://app-pr3509.review.pix.fr
- App (.org): https://app-pr3509.review.pix.org
- Orga: https://orga-pr3509.review.pix.fr
- Certif: https://certif-pr3509.review.pix.fr
- Admin: https://admin-pr3509.review.pix.fr
- API: https://api-pr3509.review.pix.fr/api/

 Please check it out!

2021-09-30 08:43 UTC, P-Jeremy commented on admin/tests/unit/controllers/authenticated/certification-centers/get_test.js
> +    //certificationCenter = { id: 1 };
commentaire à supprimer :)

2021-09-30 08:57 UTC, P-Jeremy commented on api/tests/unit/domain/models/GrantedAccreditation_test.js
> +    });*/
commentaires à supprimer

2021-09-30 09:03 UTC, P-Jeremy commented on api/tests/integration/infrastructure/repositories/granted-accreditation-repository_test.js
> +    it('should delete all granted accreditations for give certification center id', async function() {
'given'

2021-09-30 09:08 UTC, P-Jeremy commented on api/lib/domain/usecases/save-certification-center.js
> +      const grantedAccreditationModel = new GrantedAccreditation({
On préfère éviter les promise.all, on utilise plutôt blubird ;)

2021-09-30 09:10 UTC, P-Jeremy commented on api/tests/unit/domain/usecases/save-certification-center_test.js
> +        grantedAccreditation1.id = undefined;
Pourquoi on écrase la valeur de l'id ici ?

2021-09-30 09:12 UTC, P-Jeremy approved these changes

2021-09-30 09:12 UTC, P-Jeremy commented
Testé fonctionnellement :+1:

2021-10-01 15:29 UTC, aceol commented on api/lib/domain/usecases/save-certification-center.js
> +      const grantedAccreditationModel = new GrantedAccreditation({
Tout depends des metriques, ici on est sur 2-3 promesses, on peut donc tout a fait utiliser Promise.all. Je ne pense pas que ca évoluera bcp mais si c'etait le cas il faudrait effectivement evoluer vers mapSeries.

2021-10-01 15:31 UTC, aceol commented on api/tests/unit/domain/usecases/save-certification-center_test.js
> +        grantedAccreditation1.id = undefined;
Le builder cree un grantedAccreditation avec id, mais ici il n'est pas censé être deja passé par la BDD (donc pas d'id généré).
On avait d'ailleurs évoqué de créer un builder spécifique

2021-10-04 08:15 UTC, octo-topi commented
**question**
Si la modification est annulée, est-il normal que la valeur soit prise en compte (hors BDD, bien chargé au F5) ?

2021-10-04 08:18 UTC, octo-topi commented
**question**
Est-il normal qu'un centre de certif modifié à "Sans type" soit rejeté par l'API mais pas affiché dans l'IHM ?

![image](https://user-images.githubusercontent.com/56302715/135817095-f3877c73-d82c-4f67-a3d5-54c216762860.png)

2021-10-04 08:23 UTC, octo-topi commented
**question**
Est-il normal qu'un centre de certif modifié sans identifiant externe soit rejeté par l'API mais pas affiché dans l'IHM ?

![image](https://user-images.githubusercontent.com/56302715/135817894-e145a7f4-2c56-4eb3-86a9-67ee635fcf0c.png)

2021-10-04 08:25 UTC, octo-topi commented
**question**
Y a-t-il une raison UX pour mettre du gras sur Habilitation et pas le reste ?

![image](https://user-images.githubusercontent.com/56302715/135818187-573e8f12-4f3e-4f1c-9072-5dba8d7d2495.png)

2021-10-04 08:43 UTC, aceol commented on admin/app/controllers/authenticated/certification-centers/get.js
> +    else {
```suggestion
    } else {
```

2021-10-04 08:43 UTC, aceol commented on admin/app/templates/authenticated/certification-centers/get.hbs
> +            </div>
Sur l'annulation, on ne doit pas avoir les modifs qui impactent le model. 
On partira plutôt sur un model à part, et quand on valide, on met à jour le model de la session.
ℹ️ Sur l'annulation + re-edit, on peut choisir de garder les anciennes modifs mais ca n'est pas forcement pertinent

2021-10-04 08:48 UTC, octo-topi commented
**bloquant**
Cacher le bouton Editer si `FT_ACCREDITATION_ENABLED=false`  (actuellement: toujours affiché, peu importe la valeur, non renvoyé par le endpoint FT

![image](https://user-images.githubusercontent.com/56302715/135821383-ea4a2eb9-8360-4784-8661-d2d4f395ee7d.png)

2021-10-04 09:07 UTC, octo-topi commented
**bloquant**
Il n'y a aucun test front sur la modification Nom/Id externe/Type

2021-10-04 09:17 UTC, octo-topi commented
**suggestion**
Ajouter une notification "Sauvegarde effectuée" ou "Erreur"

2021-10-04 09:17 UTC, MathieuGilet commented
Il faudrait garantir l'ordre des accréditations car lorsque j'ajoute et retire une accréditation à un centre de certification puis que je refresh la page, l'ordre des accréditations change.

2021-10-04 09:18 UTC, octo-topi commented
**suggestion**
Ajouter une liste déroulante avec les types de CC autorisés
```
Check constraints:
    "certification-centers_type_check" CHECK (type = ANY (ARRAY['SCO'::text, 'SUP'::text, 'PRO'::text]))
```

2021-10-04 09:32 UTC, octo-topi commented on api/tests/unit/domain/models/GrantedAccreditation_test.js
> +  });
**suggestion**
Remplacer par un seul test avec l'assertion `deepEqualInstance`

2021-10-04 09:38 UTC, octo-topi commented on api/lib/domain/models/GrantedAccreditation.js
> +class GrantedAccreditation {
**question**
Pourquoi ne pas l'ajouter comme propriété à Certification Center ?

2021-10-04 09:40 UTC, octo-topi commented on api/lib/infrastructure/repositories/granted-accreditation-repository.js
> +const { knex } = require('../bookshelf');
```suggestion
const { knex } = require('../../../db/knex-database-connection');
```

2021-10-04 10:08 UTC, octo-topi commented on api/lib/domain/usecases/index.js
> +  grantedAccreditationRepository: require('../../infrastructure/repositories/granted-accreditation-repository'),
**chipotage**
le déplacer du commit "repo" au commit "usecase"

2021-10-04 10:10 UTC, octo-topi commented on api/lib/domain/usecases/save-certification-center.js
> +module.exports = async function saveCertificationCenter({ certificationCenter, accreditations, certificationCenterRepository, grantedAccreditationRepository }) {
**chipotage**
```suggestion
module.exports = async function updateCertificationCenter({ certificationCenter, accreditations, certificationCenterRepository, grantedAccreditationRepository }) {
```

2021-10-04 10:13 UTC, octo-topi commented on api/lib/domain/usecases/save-certification-center.js
>  const certificationCenterCreationValidator = require('../validators/certification-center-creation-validator');
**question**
Dans la team :rocket: , vous sortez systématiquement la validation hoirs du routeur pour la mettre dans un validator ?

2021-10-04 10:16 UTC, octo-topi commented on admin/app/adapters/certification-center.js
> +import ApplicationAdapter from './application';
**chipotage**
Code front introduit dans sun commit taggé API

2021-10-04 10:18 UTC, octo-topi commented on api/lib/application/certification-centers/certification-center-controller.js
> +    const savedCertificationCenter = await usecases.saveCertificationCenter({ certificationCenter, accreditations });
**question**
Il n'y a aucun test associté au commit de modif du controller, est-ce normal ?

2021-10-04 10:19 UTC, octo-topi commented on api/lib/application/certification-centers/index.js
> +          '- Création d‘un nouveau centre de certification\n' +
```suggestion
          '- Modification d'un centre de certification\n' +
```

2021-10-04 10:21 UTC, octo-topi commented on api/lib/infrastructure/serializers/jsonapi/accreditation-serializer.js
> +  },
**question**
OK pour se passer de TU sur le serializer, mais il faut au moins un test au niveau controller/routeur ?

2021-10-04 10:23 UTC, octo-topi requested changes
Le FT doit être pris en compte dans le Front, ainsi que le contrôle de la saisie (champ obligatoire/optionnel + liste de valeurs + affichage du retour API si KO) et la gestiion de l'annulation (rappeler l'APi en lecture)

2021-10-04 12:10 UTC, aceol commented
> Il faudrait garantir l'ordre des accréditations car lorsque j'ajoute et retire une accréditation à un centre de certification puis que je refresh la page, l'ordre des accréditations change.

Cela à un impact, pour l'instant, on ne 

> Le FT doit être pris en compte dans le Front, ainsi que le contrôle de la saisie (champ obligatoire/optionnel + liste de valeurs + affichage du retour API si KO) et la gestiion de l'annulation (rappeler l'APi en lecture)

On pourra faire la verification du formulaire dans une PR à part

2021-10-04 12:37 UTC, aceol commented on api/tests/integration/infrastructure/repositories/granted-accreditation-repository_test.js
> +    it('should delete all granted accreditations for give certification center id', async function() {
Pour eclaircir ce commentaire: 
```suggestion
    it('should delete all granted accreditations for given certification center id', async function() {
```
😀

2021-10-06 09:16 UTC, octo-topi approved these changes
Ok suite au changement de scope
https://1024pix.atlassian.net/browse/PIX-3577

2021-10-06 09:31 UTC, merged