[FEATURE] Afficher la classe des élèves sur la feuille d'émargement (PIX-3492)
1024pix/pix pull request #3560
Opened 2021-10-05 12:40 UTC by P-Jeremy

## :unicorn: Problème
> _Décrivez ici le besoin ou l'intention couvert par cette Pull Request._

## :robot: Solution
> _Ajoutez à cet endroit, si nécessaire, des détails concernant la solution technique retenue et mise en oeuvre, des difficultés ou problèmes rencontrés._

## :rainbow: Remarques
> _Des infos supplémentaires, trucs et astuces ?_

## :100: Pour tester
> _Les instructions pour reproduire le problème, les profils de test, le parcours spécifique à utiliser, etc._

2021-10-05 12:46 UTC, pix-service commented
I'm deploying this PR to these urls:

- App (.fr): https://app-pr3560.review.pix.fr
- App (.org): https://app-pr3560.review.pix.org
- Orga: https://orga-pr3560.review.pix.fr
- Certif: https://certif-pr3560.review.pix.fr
- Admin: https://admin-pr3560.review.pix.fr
- API: https://api-pr3560.review.pix.fr/api/

 Please check it out!

2021-10-07 07:03 UTC, octo-topi requested changes
Test fonctionnel SCO is_managing_student = false KO en RA (voir description de PR)
Le champ `classe` apparait au lieu de `identifiant externe`
![image](https://user-images.githubusercontent.com/56302715/136335261-93fe89a6-a22f-4cce-a1f9-1cc616c5f2b3.png)

Les autres tests fonctionnels sont OK :+1:

2021-10-07 07:28 UTC, octo-topi commented on api/tests/integration/infrastructure/repositories/session-for-attendance-sheet-repository_test.js
> +    context('when there are no schoolingResgistrations', function() {
**chipotage**
Typo + un espace 
```suggestion
    context('when there are no schooling registrations', function() {
```

2021-10-07 07:31 UTC, clemlatz approved these changes

2021-10-07 07:31 UTC, clemlatz commented on api/lib/infrastructure/repositories/session-for-attendance-sheet-repository.js
> +        'certificationCenter as certificationCenterName',
Est-ce qu'on pourrait pas utiliser ici plutôt `certificationCenter.name` vu qu'on a une jointure sur la table `certification-centers` ? En prévision dun éventuel dégageage de ce champ ?

2021-10-07 07:31 UTC, clemlatz commented on api/tests/unit/domain/usecases/get-attendance-sheet_test.js
> +function _buildSessionWithCandidate(certificationCenterType) {
Pourquoi ne pas utiliser un domainBuilder ici ?

2021-10-07 07:32 UTC, octo-topi commented on api/tests/integration/infrastructure/repositories/session-for-attendance-sheet-repository_test.js
> +      it('should return session informations in a session Object', async function() {
***chipotage**
Le fait que l'on renvoie un objet du domaine est normal, je propose de mettre en avant la RG qui a été ajoutée (division) et le tri qui est implicite
```suggestion
      it('should return session with ordered candidates and no division', async function() {
```

2021-10-07 07:32 UTC, octo-topi commented on api/tests/integration/infrastructure/repositories/session-for-attendance-sheet-repository_test.js
> +      it('should return session informations in a session Object', async function() {
**chipotage**
Le fait que l'on renvoie un objet du domaine est normal, je propose de mettre en avant la RG qui a été ajoutée
```suggestion
      it('should return session with division', async function() {
```

2021-10-07 07:35 UTC, octo-topi commented on api/lib/infrastructure/repositories/session-for-attendance-sheet-repository.js
> +      throw new NotFoundError('La session n\'existe pas ou son accès est restreint');
**question**
Je ne vois pas de contrôle d'accès ici qui justifierait "accès restreint"
```suggestion
      throw new NotFoundError('La session n\'existe pas');
```

2021-10-07 07:46 UTC, octo-topi commented on api/tests/unit/domain/usecases/get-attendance-sheet_test.js
> +      it('should return an error when user does not have access', function() {
**chipotage**
Information déjà fournie dans le contexte
```suggestion
      it('should return an error', function() {
```

2021-10-07 07:52 UTC, octo-topi commented on api/lib/domain/usecases/get-attendance-sheet.js
> +function _getAttendanceTemplatePath(certificationCenterType) {
**chipotage**
Pour être cohérent avec le reste
```suggestion
function _getAttendanceSheetTemplatePath(certificationCenterType) {
```

2021-10-07 07:57 UTC, octo-topi commented on api/lib/domain/usecases/get-attendance-sheet.js
> +  return _updateXmlWithCertificationCandidates(updatedStringifiedXml, session);
**question**
Ce `update` me fait penser qu'il y a de la mutation de données, mais en regardant un peu l'implémentation, l'objet retourné est bien créé. Comme on retourne le résultat de l'appel de fonction, je propose un renommage. En fait, ça dépend si le nom de la fonction décrit ce qu'elle fait ou ce qu'elle renvoie :thinking: 
```suggestion
  return _attendanceSheetWithCertificationCandidates(updatedStringifiedXml, session);
```

2021-10-07 08:00 UTC, aceol commented on api/lib/infrastructure/repositories/session-repository.js
> +    const session = await knex('sessions')
En une requete, ca donne: 

```suggestion
        const results = await knex.select('sessions.*').select({
      certificationCandidates: knex.raw(`
        json_agg("certification-candidates".* order by lower("lastName"), lower("firstName"))
        `,
      ),
    }).from('sessions')
      .join('certification-candidates', 'certification-candidates.sessionId', 'sessions.id')
      .groupBy('sessions.id')
      .where({ 'sessions.id': idSession })
      .first();

    if (!results) {
      throw new NotFoundError('La session n\'existe pas ou son accès est restreint');
    }

    return _toDomain(results);
```

 avec pour le _toDomains

```javascript
function _toDomain(results) {
  const toDomainCertificationCandidates = results.certificationCandidates.map((candidate) => {
    return new CertificationCandidate({ ...candidate });
  });

  return new Session({
    ...results,
    certificationCandidates: toDomainCertificationCandidates,
  });
```

2021-10-07 08:35 UTC, P-Jeremy commented on api/lib/infrastructure/repositories/session-repository.js
> +    const session = await knex('sessions')
@aceol ça fait péter les test d'acceptance :cry:

2021-10-07 09:38 UTC, octo-topi commented on api/tests/integration/domain/usecases/get-attendance-sheet/get-attendance-sheet_test.js
> +      const expectResult = await readOdsUtils.getContentXml({ odsFilePath: expectedOdsFilePath });
**chipotage**
```suggestion
      const expectedResult = await readOdsUtils.getContentXml({ odsFilePath: expectedOdsFilePath });
```

2021-10-07 12:59 UTC, octo-topi commented on api/translations/fr.json
> +	"Votre code Pix est {{ code }}": "Votre code Pix est {{ code }}",
**question**
Je en vois pas d'endroit où cette traduction est demandée... 
Ce fichier a-t-il été embarqué par erreur dans le commit ?

2021-10-07 12:59 UTC, octo-topi approved these changes
Tests fonctionnels et revue de code OK

2021-10-07 13:15 UTC, P-Jeremy commented on api/translations/fr.json
> +	"Votre code Pix est {{ code }}": "Votre code Pix est {{ code }}",
Ah oui, c'est une erreur...

2021-10-07 14:28 UTC, P-Jeremy commented on api/tests/unit/domain/usecases/get-attendance-sheet_test.js
> +function _buildSessionWithCandidate(certificationCenterType) {
J'essaie d'en mettre un mais ça fait péter mes tests et je ne comprends pas pourquoi...

2021-10-08 08:53 UTC, aceol commented on api/tests/unit/domain/usecases/get-attendance-sheet_test.js
> +function _buildSessionWithCandidate(certificationCenterType) {
Ca semble être résolu!?

2021-10-08 09:12 UTC, aceol commented on api/lib/infrastructure/repositories/session-repository.js
> +    const session = await knex('sessions')
effectivement, il faut mettre un leftJoin au lieu d'un join (innerJoin)

2021-10-08 09:24 UTC, P-Jeremy commented on api/tests/unit/domain/usecases/get-attendance-sheet_test.js
> +function _buildSessionWithCandidate(certificationCenterType) {
non, on peut regarder ensemble cet aprem si tu veux @aceol ?

2021-10-08 14:15 UTC, P-Jeremy commented on api/tests/unit/domain/usecases/get-attendance-sheet_test.js
> +function _buildSessionWithCandidate(certificationCenterType) {
On a regardé avec @MathieuGilet, on se casse les dents avec les domainBuilder, la faute au transform dans le useCase

2021-10-08 14:46 UTC, aceol commented on api/tests/unit/domain/usecases/get-attendance-sheet_test.js
> +function _buildSessionWithCandidate(certificationCenterType) {
On peut laisser comme ca. Les transform créés de nouveaux objet qui ne correspondent pas aux classes des domainBuilder

2021-10-08 14:49 UTC, aceol commented on api/tests/unit/domain/usecases/get-attendance-sheet_test.js
> +          });
En utilisant des `stub.calledWith(...).resolves(...) `on évite les `expect.to.have.been.calledWithExactly`
=> Si on ne passe pas les bons paramètres, le resolve ne fonctionnera pas et ainsi la valeur de retour de la methode testé ne sera pas corrects.  
`expect(result).to.deep.equal(odsBuffer);` renverra `false`

2021-10-11 09:31 UTC, merged