[bugfix] Ne pas autoriser de publier une session avec une certif "aborted" (pix-3573)
1024pix/pix pull request #3567
Opened 2021-10-06 13:04 UTC by aceol

## :unicorn: Problème
Lors de la finalisation de session il est possible d'utiliser la case à cocher sur toute la colonne pour la "case de fin de test". Hors cela s'applique sur toutes les certif dont celles qui sont "abort"

## :robot: Solution
Coté front: on applique la "case de fin de tests" que sur les certif completed.
Coté back: on ne peux publier une session si une des sessions n'est pas complétée + raison d'annulation (abortReason)

## :rainbow: Remarques

## :100: Pour tester
- Créer une session avec 2 candidats
- Demarrer une certif sans la terminer
- Demarrer une autre certif et la terminer
- Dans admin "finaliser la session" puis selectionner la case de fin de test sur TOUTE la colonne (pas sur la ligne terminée uniquement)
- Verifier sur pix admin que la session est dans les sessions à traiter et non dans les sessions à publier

2021-10-06 13:06 UTC, aceol commented
Ne pas merger avant d'avoir pix-2988-display-auto-scored-or-auto-cancel-started-certification mergé sur dev

2021-10-06 13:09 UTC, pix-service commented
I'm deploying this PR to these urls:

- App (.fr): https://app-pr3567.review.pix.fr
- App (.org): https://app-pr3567.review.pix.org
- Orga: https://orga-pr3567.review.pix.fr
- Certif: https://certif-pr3567.review.pix.fr
- Admin: https://admin-pr3567.review.pix.fr
- API: https://api-pr3567.review.pix.fr/api/

 Please check it out!

2021-10-07 12:14 UTC, P-Jeremy approved these changes

2021-10-07 12:19 UTC, Libouk commented on api/lib/domain/models/FinalizedSession.js
> +        && _hasNoFlaggedAsAborted(juryCertificationSummaries)
Est-ce qu'utiliser _isNotFlaggedAsAborted ne serait pas mieux ?

2021-10-07 12:46 UTC, Libouk commented on api/tests/unit/domain/models/FinalizedSession_test.js
> +
ligne en trop

2021-10-07 12:50 UTC, Libouk approved these changes

2021-10-07 13:17 UTC, octo-topi commented on api/translations/fr.json
> +}
Ce fichier fait-il partie de ceux à commiter ou est-ce une erreur ?

2021-10-07 13:19 UTC, P-Jeremy commented on api/translations/fr.json
> +}
C'est encore une erreur... Je ne comprends pas d'où sort ce fichier

2021-10-07 13:47 UTC, octo-topi commented
Session finalisée
![image](https://user-images.githubusercontent.com/56302715/136396683-dcbf56e3-3f62-4d84-842e-76a12024d2ca.png)

Se retrouve dans session à traiter => OK
![image](https://user-images.githubusercontent.com/56302715/136397198-6e3eb2be-6693-4c38-b6ab-4452383f3dba.png)

2021-10-07 13:48 UTC, octo-topi requested changes
Tests fonctionels OK, par contre les traductions sont modifiées par erreur

2021-10-07 14:01 UTC, octo-topi approved these changes

2021-10-07 14:08 UTC, merged