[FEATURE] Inviter un membre à une organisation PRO avec un rôle défini dans le fichier de création des organisations PRO (PIX-3493).
1024pix/pix pull request #3582
Opened 2021-10-08 14:34 UTC by yahyayouness

## :unicorn: Problème
Aujourd'hui, le script de création des organisations PRO permet de créer des organisations et de leur rattacher un membre avec le role ADMIN. Or, pour certaines organisations disposant de tags spécifiques,  on veut leur attribuer le role MEMBER uniquement. 

## :robot: Solution
Rajouter une colonne dans le fichier CSV [organizationInvitationRole] qui va contenir le rôle à attribuer. [ ADMIN ou MEMBER ]

## :100: Pour tester
Lancer le script avec le fichier csv ci-dessous:

`node scripts/create-pro-organizations-with-tags.js /path/ORGA.csv`

externalId;name;provinceCode;canCollectProfiles;credit;email;organizationInvitationRole;locale;tags;createdBy
111111;orgatest;31;TRUE;0;votreemail@pix.fr;MEMBER;fr-fr;mednum;1

Vérifier qu'une invitation a été créé avec le rôle mentionné dans le fichier dans la table organizationInvitation.

2021-10-08 14:40 UTC, pix-service commented
I'm deploying this PR to these urls:

- App (.fr): https://app-pr3582.review.pix.fr
- App (.org): https://app-pr3582.review.pix.org
- Orga: https://orga-pr3582.review.pix.fr
- Certif: https://certif-pr3582.review.pix.fr
- Admin: https://admin-pr3582.review.pix.fr
- API: https://api-pr3582.review.pix.fr/api/

 Please check it out!

2021-10-12 08:57 UTC, yschoueri approved these changes

2021-10-12 14:12 UTC, Anne-Gaelle-S reviewed
Je n'arrive pas tester, le scénario me semble pas complet ... 
J'ai essayé de faire `node scripts/create-pro-organizations-with-tags.js file.csv` avec le jeu de donné écrit dans la PR et ça m'a retourné `Done.
10000000,orgatest`.
Jusqu'à là ok. Mais de ce que je comprend de la description lorsque je lance le script il va : 
- me créé l'orga `orgatest` => ça ok je la retrouve bien dans ma BDD ✅ 
<img width="876" alt="image" src="https://user-images.githubusercontent.com/38167520/136972593-64eb0080-4cd4-456f-a713-68e6809d5c4b.png">

- me rattacher l'orgatest avec l'utilisateur d'id 1 (puisque le createdBy=1 dans le csv) => là ça ne passe pas. Je n'ai aucune ligne dans la table "memberships" qui relie l'user 1 et l'orga créée 🚫 
<img width="931" alt="image" src="https://user-images.githubusercontent.com/38167520/136972667-3aa7271f-69de-4147-bb64-83938f3b410a.png">

Est-ce que je fais fausse route quelque part ? Qu'est-ce que je n'ai pas compris ?

2021-10-12 15:55 UTC, ebarbier commented
Peux-tu me dire ce qu'il se passe si la colonne 'organizationInvitationRole' est vide?
Ca casse le lancement du script ou est-ce que ça prend la valeur par défaut 'ADMIN' (cette 2eme solution serait l'idéal)?
Thanks!

2021-10-12 15:58 UTC, ebarbier commented
Au lieu de 'Rattacher un membre' dans le titre et la description, peux-tu mettre 'Inviter un membre'. Thanks!

2021-10-12 16:14 UTC, yahyayouness commented
> Je n'arrive pas tester, le scénario me semble pas complet ... J'ai essayé de faire `node scripts/create-pro-organizations-with-tags.js file.csv` avec le jeu de donné écrit dans la PR et ça m'a retourné `Done. 10000000,orgatest`. Jusqu'à là ok. Mais de ce que je comprend de la description lorsque je lance le script il va :
> 
> * me créé l'orga `orgatest` => ça ok je la retrouve bien dans ma BDD ✅
> 
> <img alt="image" width="876" src="https://user-images.githubusercontent.com/38167520/136972593-64eb0080-4cd4-456f-a713-68e6809d5c4b.png">
> 
> * me rattacher l'orgatest avec l'utilisateur d'id 1 (puisque le createdBy=1 dans le csv) => là ça ne passe pas. Je n'ai aucune ligne dans la table "memberships" qui relie l'user 1 et l'orga créée 🚫
> 
> <img alt="image" width="931" src="https://user-images.githubusercontent.com/38167520/136972667-3aa7271f-69de-4147-bb64-83938f3b410a.png">
> 
> Est-ce que je fais fausse route quelque part ? Qu'est-ce que je n'ai pas compris ?

Non, c'est moi qui a oublié de mettre l'assertion dans la partie test sorry. Je l'ai mise à jour, il faut juste vérifier qu'une invitation a été insérée dans la table organizationInvitation avec le rôle dans le fichier.

> Peux-tu me dire ce qu'il se passe si la colonne 'organizationInvitationRole' est vide? Ca casse le lancement du script ou est-ce que ça prend la valeur par défaut 'ADMIN' (cette 2eme solution serait l'idéal)? Thanks!

Ca ne casse pas le script et n'enregistre pas de rôle au niveau de la table organizationInvitation. Comme il existe une règle de gestion coté API qui invite le premier membre de l'orga avec le rôle ADMIN, il sera administrateur.

2021-10-14 08:22 UTC, Anne-Gaelle-S approved these changes

2021-10-14 09:59 UTC, thloesch commented on api/tests/integration/domain/usecases/create-pro-organization-with-tags_test.js
> +      if (organization.email) {
**Remarque** : Je trouvais déjà ce test compliqué avant, mais en rajoutant un autre `expect` dans un `if` dans une boucle `for` d'un seul test, là je commence vraiment à être perdu.

Est-ce qu'on pourrait sortir ce `if` dans un test à part ?

2021-10-14 10:01 UTC, thloesch requested changes
Je bloque juste pour avoir un échange sur le test avant de merger

2021-10-18 08:01 UTC, yahyayouness commented on api/tests/integration/domain/usecases/create-pro-organization-with-tags_test.js
> +      if (organization.email) {
Yes, on peut le sortir dans un test dédié

2021-10-18 09:40 UTC, thloesch commented on api/tests/integration/domain/usecases/create-pro-organization-with-tags_test.js
> +        organizationInvitationRole: Membership.roles.ADMIN,
**Remarque non-bloquante** : On aurait même pas besoin de préciser les rôles ici, le script marcherait quand même

2021-10-18 09:42 UTC, thloesch commented on api/tests/integration/domain/usecases/create-pro-organization-with-tags_test.js
> +  it('should create organization invitation with role when email is specified', async function () {
Merci pour le test en plus ! 

Juste une petite correction sur le nom 
```suggestion
  it('should create organization invitation with role when role is specified', async function () {
```

2021-10-18 14:51 UTC, thloesch approved these changes

2021-10-18 15:31 UTC, merged