:jack_o_lantern:  (PIX-3642)
1024pix/pix pull request #3600
Opened 2021-10-13 15:00 UTC by francois2metz

:onion:

2021-10-13 15:05 UTC, pix-service commented
I'm deploying this PR to these urls:

- App (.fr): https://app-pr3600.review.pix.fr
- App (.org): https://app-pr3600.review.pix.org
- Orga: https://orga-pr3600.review.pix.fr
- Certif: https://certif-pr3600.review.pix.fr
- Admin: https://admin-pr3600.review.pix.fr
- API: https://api-pr3600.review.pix.fr/api/

 Please check it out!

2021-10-13 16:53 UTC, octo-topi approved these changes
![image](https://user-images.githubusercontent.com/56302715/137178477-3e97ac64-06f3-48ac-b1b2-eda7a4fb3203.png)

2021-10-13 16:54 UTC, octo-topi commented on .circleci/config.yml
> +          command: npm run lint
**question**
Pourquoi avoir interverti test et lint ?

2021-10-13 16:56 UTC, octo-topi commented on api/lib/config.js
> +      isHalloweenEnabled: isFeatureEnabled(process.env.FT_HALLOWEEN_ENABLED),
**suggestion**
Je préfère un verbe après `FT`
```suggestion
      isHalloweenEnabled: isFeatureEnabled(process.env.FT_DISPLAY_HALLOWEEN_THEME),
```

2021-10-13 17:31 UTC, HEYGUL commented on .circleci/config.yml
> +          command: npm run lint
La réponse semble être dans le [message de commit](https://github.com/1024pix/pix/pull/3600/commits/7ce5c90b20ea78557b9768c5bc51162b28523b64)

2021-10-14 07:20 UTC, octo-topi commented on .circleci/config.yml
> +          command: npm run lint
Ca me donne à penser.. J'aime beaucoup l'idée en tout cas !

2021-10-14 07:23 UTC, ghost commented on api/lib/config.js
> +      isHalloweenEnabled: isFeatureEnabled(process.env.FT_HALLOWEEN_ENABLED),
**réflexion/suggestion** Est-ce que la fonctionnalité serait pas d'avoir une feature `isSeasonalThemeEnabled` avec un ensemble de thèmes associés que l'on fait grandir avec le temps ? (Noël, Saint-Patrick, journée de la cybersécurité, etc.)

2021-10-14 07:50 UTC, ghost requested changes

2021-10-14 07:50 UTC, ghost commented on .circleci/config.yml
> +          command: npm run lint
**réflexion (au sujet de l'intention du commit) :** 
Est-ce qu'en faisant ça, on ne transforme pas les tests (par extension TDD pour celles et ceux qui pratiquent) en une pratique de CI au lieu d'une méthodologie de développement en local ? 
D'une certaine manière, ça me laisse penser que l'on change de paradigme : plutôt que de vérifier que les tests passent en local (red -> green), on va en CI pour vérifier que les tests ne cassent pas (green -> red?). Les tests doivent exceptionnellement casser en CI pour la raison qu'ils s'ont probablement dépendants de l'environnement ; ça ne doit pas être normal d'aller en CI pour s'assurer que les tests passent (d'ailleurs, ça coûte de l'argent si ma mémoire sur la facturation de CircleCI est bonne) 🤔 

**réflexion (sur le principe de linter après les tests) :** 
A priori les tests ne sont pas censés passer si le lint ne passe pas. Le lint joue aussi (et surtout) le rôle de chasseur de bugs issus de mauvaises pratiques. On peut se retrouver à se demander pourquoi un test casse alors que la syntaxe n'est simplement pas la bonne, ou que sais-je. Le feedback le plus rapide pour obtenir cette information est alors d'exécuter le lint avant les tests. 
>Lint programming is a type of automated check. It should happen early in development, before code reviews and testing. That’s because automated code checks make the code review and test processes more efficient. And they free your developers to focus on the right things. — [What Is Lint Code? And Why Is Linting Important?](https://www.perforce.com/blog/qac/what-lint-code-and-why-linting-important)

**problème (bloquant) :** Je trouve que ce commit mérite une PR à part pour faciliter la communication sur ce standard (qui doit changer ou non) et l'inscrire explicitement dans l'historique git.

2021-10-14 08:22 UTC, ghost commented on mon-pix/app/styles/components/_hexagon-score.scss
> +.pumpkin-mode {
**problème :** Ce nommage ne respecte pas le standard [BEM-like](https://1024pix.atlassian.net/wiki/spaces/DEV/pages/1448378369/Le+nommage+des+classes+CSS) que l'on utilise même si je comprend l'intention qui semble s'y rattacher "pouvoir supprimer facilement".
 
**suggestion :** Cette classe peut convenir à nos standards, sans avoir à ajouter des `modifiers` partout. À ajouter au sein de la classe `.hexagon-score`
```suggestion
&--pumpkin-mode {
```

2021-10-14 09:33 UTC, sroccaserra commented on .circleci/config.yml
> +          command: npm run lint
Thought : c'est vrai que c'est pas trop en rapport avec la PR.

2021-10-14 11:49 UTC, francois2metz commented on .circleci/config.yml
> +          command: npm run lint
Ce commit va être supprimé. Il est juste la pour essayer d'avoir un feedback utile de l'intégration continue pendant le développement de cette belle fonctionnalité.

2021-10-14 14:35 UTC, Libouk commented on mon-pix/app/styles/components/_hexagon-score.scss
> +.pumpkin-mode {
Merci Stéphane, j'avais un doute et en effet : "la convention Block__Element--Modifier BEM."

2021-10-14 14:40 UTC, Libouk commented
Suite aux soucis qu'on a rencontrés avec le feature-toggle, ci-joint une PR où on supprime un feature toggle et en comparant je pense qu'on a fait quelques oublis : https://github.com/1024pix/pix/pull/3605

2021-10-15 07:33 UTC, sroccaserra commented on .circleci/config.yml
> +          command: npm run lint
Ah ok. J'ai pas participé, donc je ne comprends peut-être pas tout, mais pour moi le feedback de l'IC est tellement lent qu'il m'est de peu d'utilité, que le lint soit avant ou après les tests autos.

Si l'intention c'est "I prefer TDD to Lint Driven development", je ne comprends pas comment l'IC peut aider à faire du TDD. Un `--watch` en local est bien plus utile ?

(Je rappelle au passage que j'appartiens à la team "premier degré", désolé si je passe à côté d'un truc rigolo 🤭)

2021-10-15 07:45 UTC, sroccaserra commented on .circleci/config.yml
> +          command: npm run lint
> Est-ce qu'en faisant ça, on ne transforme pas les tests (par extension TDD pour celles et ceux qui pratiquent) en une pratique de CI au lieu d'une méthodologie de développement en local ?

Je serai étonné que ce soit ça, j'ai l'impression que c'est en plus des tests en local non ? Une façon de privilégier la remontée CI des fails de tests auto par rapport à la remontée CI du lint ? @francois2metz ?

Because à aucun moment je n'imagine que faire du TDD par CI interposée soit une option :
- j'écris un test qui échoue,
- je commit push,
- je vais boire un café ou lire un bouquin,
- je vois que ça a échoué dans la CI
- j'écris l'implémentation bête qui fait passer le test
- je commit push
- je vais au cinéma
- je vois que le test est passé au vert dans la CI
- je réfactore
- ...

À ce rythme c'est mes petits enfants qui termineront la feature (si j'ai des petits enfants un jour) 🤷

2021-10-18 15:01 UTC, francois2metz commented
:broken_heart:

2021-10-18 15:01 UTC, closed without merging