[TECH] Renommer badge-partner-competence en skillset (PIX-2708).
1024pix/pix pull request #3613
Opened 2021-10-15 08:40 UTC by celineung

## :jack_o_lantern: Problème
Suite à la PR #3112, on parle désormais de `SkillSet` pour les lots d'acquis.
Historiquement appelé `BadgePartnerCompetence`, cette PR renomme `BadgePartnerCompetence`en `SkillSet`.

## :bat: Solution
Renommer `BadgePartnerCompetence`en `SkillSet`.

## :spider_web: Remarques
On a parfois des `BadgePartnerCompetence` et parfois des `PartnerCompetence`.
Or il s'agit de la même chose. Ces deux éléments ont été renommés en `SkillSet`.

Puisque le front met plus de temps à se déployer que l'api, le dernier commit de cette PR permet d'envoyer à la fois `badgePartnerCompetence` et `skillSet`. **Ce dernier commit sera à revert une fois la PR déployée en prod**

## :ghost: Pour tester
Se rendre sur la RA.
Gagner des badges sur les campagnes.

Constater qu'en fin de campagne:
- sur la campagne AZERTY123: les noms des compétences Pix sont affichées
- sur la campagne CLEA123: les noms des compétences SkillSet sont affichées

(J'ai créé la campagne CLEA123 pour les tests de cette RA. Actuellement c'est la campagne QWERTY789 qui fait gagner le badge `PIX_EMPLOI_CLEA_V2`, mais il faut se connecter via pôle emploi pour la passer)

2021-10-15 08:44 UTC, pix-service commented
I'm deploying this PR to these urls:

- App (.fr): https://app-pr3613.review.pix.fr
- App (.org): https://app-pr3613.review.pix.org
- Orga: https://orga-pr3613.review.pix.fr
- Certif: https://certif-pr3613.review.pix.fr
- Admin: https://admin-pr3613.review.pix.fr
- API: https://api-pr3613.review.pix.fr/api/

 Please check it out!

2021-10-18 13:32 UTC, yannbertrand commented
API 🆗 pour moi ✅

2021-10-19 13:06 UTC, alexandrecoin commented
Ok pour la partie API ✌️

2021-10-20 10:00 UTC, VincentHardouin commented
⚠️ il faut laisser une période de transition où l'on peut appeler l'API avec les anciens noms, car l'API et le front ne se déploie pas en même temps. Cela a pour conséquence de laisser un état où l'API n'accepte plus l'ancien nom car elle se déploie plus vite mais le front lui appel toujours avec l'ancien nom.

2021-10-21 10:14 UTC, MelanieMEB commented on api/lib/infrastructure/serializers/jsonapi/badge-with-learning-content-serializer.js
> +        attributes: ['threshold', 'scope', 'skillSets', 'partnerCompetences'],
```suggestion
        attributes: ['threshold', 'scope', 'skillSets'],
```
On en a plus besoin normalement

2021-10-21 10:14 UTC, MelanieMEB commented on api/lib/infrastructure/serializers/jsonapi/badge-with-learning-content-serializer.js
>        },
```suggestion
```

2021-10-21 10:14 UTC, MelanieMEB commented on api/lib/infrastructure/serializers/jsonapi/badge-with-learning-content-serializer.js
> +        badge.badgePartnerCompetences = badge.skillSets;
Question : Pourquoi on en a encore besoin sur cette route ?

2021-10-21 15:47 UTC, MelanieMEB requested changes
Test fonctionnel : ca a l'air ok.

2021-10-26 12:18 UTC, VincentHardouin commented
J'ai testé en faisant un revert des commits des fronts c'est OK.

2021-10-26 12:23 UTC, celineung commented on api/lib/infrastructure/serializers/jsonapi/badge-with-learning-content-serializer.js
> +        attributes: ['threshold', 'scope', 'skillSets', 'partnerCompetences'],
@MelanieMEB on garde `partnerCompetences` pour s'assurer que la version du front qui utilise encore `partnerCompetences` fonctionne (le front met plus de temps à se déployer que l'api)

2021-10-26 15:36 UTC, ghost approved these changes

2021-10-27 09:01 UTC, MelanieMEB approved these changes
Ok pour moi !

2021-10-27 10:15 UTC, merged