[FEATURE] Ajout d'un script de comparaison du nombre de pix avec la dernière release (PIX-3547).
1024pix/pix pull request #3628
Opened 2021-10-19 13:37 UTC by thetinyspark

## :jack_o_lantern: Problème
Nous avons besoin de savoir quel serait le nombre de pix obtenus par un utilisateur aujourd'hui s'il validait des questions de niveau équivalent à celles qu'il a déjà validé. 

## :bat: Solution
Ajouter un script de recalcul du nombre de pix aujourd'hui en se basant sur le référentiel

## :spider_web: Remarques

## :ghost: Pour tester
Se rendre dans le dossier api/scripts et lancer la commande suivante: 
```bash
node scripts/compare-pix-with-latest-release.js <pix-user-id>
```

2021-10-19 13:43 UTC, pix-service commented
I'm deploying this PR to these urls:

- App (.fr): https://app-pr3628.review.pix.fr
- App (.org): https://app-pr3628.review.pix.org
- Orga: https://orga-pr3628.review.pix.fr
- Certif: https://certif-pr3628.review.pix.fr
- Admin: https://admin-pr3628.review.pix.fr
- API: https://api-pr3628.review.pix.fr/api/

 Please check it out!

2021-10-20 08:32 UTC, VincentHardouin commented on api/scripts/compare-pix-with-latest-release.js
> +  return validated;
```suggestion
  return foundKnowledgeElements.filter((ke) => {
    return ke.isValidated;
  });
```

2021-10-20 08:32 UTC, VincentHardouin commented on api/scripts/compare-pix-with-latest-release.js
> +  return result;
```suggestion
  return Promise.all(ids.map(async (tubeId) => tubeRepository.get(tubeId); }));
```

2021-10-21 15:14 UTC, thetinyspark commented on api/scripts/compare-pix-with-latest-release.js
> +  return validated;
> 

Corrigé

2021-10-21 15:14 UTC, thetinyspark commented on api/scripts/compare-pix-with-latest-release.js
> +  return result;
> 

Corrigé

2021-10-22 08:12 UTC, Jeremiejade requested changes
<3 LGTM <3

2021-10-22 08:12 UTC, Jeremiejade approved these changes

2021-10-22 08:57 UTC, Thomasevano approved these changes

2021-10-25 08:13 UTC, merged