[TECH] Renommer les tables et modèles liés aux habilitations (PIX-3673).
1024pix/pix pull request #3657
Opened 2021-10-27 07:44 UTC by MathieuGilet

## :jack_o_lantern: Problème
Lors de la mise en place des tables et modèles permettant de gérer les habilitations des centres de certification, des noms ont été choisis (`accreditations`, `granted-accreditations` et `accredited-bagdes`. Ces noms faisaient sens dans le cadre de cet Epix. Néanmoins, un nouveau besoin apparaît: pouvoir lier une "habilitation" (table `accreditations`) à un candidat et les noms choisis apparaissent comme trop spécifique par rapport à ce qu'ils représentent vraiement.

## :bat: Solution
- Renommer la table (et les modèles) `accreditations` en `complementary-certifications`
- Renommer la table (et les modèles) `granted-accreditations` en `complementary-certification-habilitations`
- Renommer la table (et les modèles) `accredited-badges` en `complementary-certification-badges`

## :spider_web: Remarques
- Dans cette PR, j'ai fait le choix de recréer des nouvelles tables plutôt que de faire des renommages. La raison principale étant que les contraintes créées par knex, reprennent le nom de la table et il aurait fallu les renommer aussi pour "faire propre".
- Je ne supprime pas les anciennes tables pour le moment, cela sera fait dans une future PR.
- Je me suis contenté d'effectuer le renommage uniquement côté API car la PR est déjà conséquente.
- Un découpage par commit a été effectué mais je pense qu'il serait mieux de faire une review globale directement car certains fichiers sont modifiés dans plusieurs commits.

## :ghost: Pour tester

### Migration données
Se positionner avant la migration `git checkout 809bec3544d5fb7651cb8ad7e6528877bd3b6467`

Créer la BDD et les seeds `npm run db:reset`

Vérifier les données
``` sql
SELECT
    'certification-center=>'
    ,crt_cnt.id
    ,crt_cnt.name
    ,'complementary certification=>'
    ,crt_cmp.id
    ,crt_cmp.name
    ,'habilitation=>'
    ,crt_cmp_hbl."createdAt"
FROM
     "certification-centers" crt_cnt
         INNER JOIN "granted-accreditations" crt_cmp_hbl ON crt_cmp_hbl."certificationCenterId" = crt_cnt.id
         INNER JOIN "accreditations" crt_cmp ON crt_cmp.id = crt_cmp_hbl."accreditationId"
```

Démarrer pix-admin et modifier les accréditations, vérifier que des données sont créées
`select * from "granted-accreditations" order by "createdAt" desc`

Se positionner sur le dernier commit `git checkout pix-3673-rename-accreditation-models`

Exécuter la migration `npm run db:migrate`
Modifier ces centres de certification

Vérifier les données, notamment les ID
``` sql
           createdAt           |    id    
-------------------------------+----------
 2021-10-29 09:51:57.003171+00 | 10000006
 2021-10-29 09:51:57.002656+00 | 10000005
 2021-10-29 09:49:18.196+00    | 10000004
 2021-10-29 09:48:30.135+00    | 10000001
 2021-10-29 09:48:30.134+00    | 10000000
 2020-01-01 00:00:00+00        |   100657
 2020-01-01 00:00:00+00        |   100659
 2020-01-01 00:00:00+00        |   100658
```

Annuler la migration
`npx knex --knexfile db/knexfile.js migrate:down` (3 fois)

Vérifier que les nouvelles tables n'existent plus

### Application
- Se connecter [à Pix Admin](https://admin-pr3657.review.pix.fr/certification-centers/10000000)
- Créer un centre de certification avec des habilitations
- Modifier ensuite ce centre en lui modifiant ces habilitations
- Vérifier que tout fonctionne
- Vérifier en base de données que les habilitations sont bien enregistrées dans les bonnes tables.
- 
```sql
SELECT
    'certification-center=>'
    ,crt_cnt.id
    ,crt_cnt.name
    ,'complementary certification=>'
    ,crt_cmp.id
    ,crt_cmp.name
    ,'habilitation=>'
    ,crt_cmp_hbl."createdAt"
FROM
     "certification-centers" crt_cnt
         INNER JOIN "complementary-certification-habilitations" crt_cmp_hbl ON crt_cmp_hbl."certificationCenterId" = crt_cnt.id
         INNER JOIN "complementary-certifications" crt_cmp ON crt_cmp.id = crt_cmp_hbl."complementaryCertificationId"
```

2021-10-27 07:50 UTC, pix-service commented
I'm deploying this PR to these urls:

- App (.fr): https://app-pr3657.review.pix.fr
- App (.org): https://app-pr3657.review.pix.org
- Orga: https://orga-pr3657.review.pix.fr
- Certif: https://certif-pr3657.review.pix.fr
- Admin: https://admin-pr3657.review.pix.fr
- API: https://api-pr3657.review.pix.fr/api/

 Please check it out!

2021-10-27 09:14 UTC, octo-topi commented
Test fonctionnel OK

## Application
Création avec Cléa
![image](https://user-images.githubusercontent.com/56302715/139036722-9b329426-02c6-4ff6-be1b-ae3b0caebad2.png)

Modification en enlevant Cléa et en ajoutant Pix+Droit
![image](https://user-images.githubusercontent.com/56302715/139036876-369c28e1-5392-41d0-9e9e-0272b3dc5535.png)

## Migration

Avant
![image](https://user-images.githubusercontent.com/56302715/139221568-59e296c1-cffa-4c28-af4a-2c17900c1a7a.png)

Après
![image](https://user-images.githubusercontent.com/56302715/139222456-ef7e4fac-4ffb-44bc-82cf-ff3334639ef7.png)

2021-10-27 13:06 UTC, aceol commented on api/tests/unit/domain/usecases/retrieve-last-or-create-certification-course_test.js
> -              certificationCenterRepository.getBySessionId.resolves(session);
🧐

2021-10-27 13:07 UTC, aceol approved these changes

2021-10-27 13:07 UTC, aceol commented on api/lib/infrastructure/serializers/jsonapi/certification-center-serializer.js
> +      },
Est-ce que c'est à garder?

2021-10-27 15:45 UTC, MathieuGilet commented on api/tests/unit/domain/usecases/retrieve-last-or-create-certification-course_test.js
> -              certificationCenterRepository.getBySessionId.resolves(session);
Ce test avait été refactoré (dans la douleur) à cause de la présence de nombreuses exclusions de lint et apparemment une erreur s'était glissée dans un test lors de ce refacto.

2021-10-27 15:46 UTC, MathieuGilet commented on api/lib/infrastructure/serializers/jsonapi/certification-center-serializer.js
> +      },
Oui c'est à garder. Ca permet de ne pas avoir d'impact sur le front et de toujours renvoyer des "accreditations" pour les habilitations des centres de certification.

2021-10-28 08:56 UTC, octo-topi commented on api/db/migrations/20211025132405_create-table-complementary-certifications.js
> +exports.up = async function(knex) {
**question**
Pourquoi 1 fichier migration par table plutôt qu'un fichier pour toute la PR ?

2021-10-28 09:22 UTC, octo-topi commented on api/db/migrations/20211025155811_create-table-complementary-certification-habilitations.js
> +  return knex.batchInsert('complementary-certification-habilitations', complementaryCertificationHabilitations);
**suggestion**

[Batch Insert](https://knexjs.org/#Utility-BatchInsert)
> The batchInsert utility will insert a batch of rows wrapped inside a transaction (which is automatically created unless explicitly given a transaction using transacting), at a given chunkSize. It's primarily designed to be used when you have thousands of rows to insert into a table.

Les conditions ne sont pas réunies.
``` sql
select count(1) from "granted-accreditations";
 86
```

Je propose
```js
knew.raw('
INSERT INTO "complementary-certification-habilitations" (
      id,
      "complementaryCertificationId",
      "certificationCenterId",
      "createdAt"  )
SELECT id,
      "accreditationId",
      "certificationCenterId",
      "createdAt"
FROM "granted-accreditations"');
```

2021-10-28 09:39 UTC, octo-topi commented on api/db/migrations/20211025155811_create-table-complementary-certification-habilitations.js
> +    t.increments().primary();
**proposition bloquant**
La création de la table entraîne la recréation de la séquence.. à l'id 1 :fearful: 
On ne le voit pas en RA car les seeds sont créées après la migration.
Ca donne, par exemple sur une autre table, si je modifie les habilitations 

![image](https://user-images.githubusercontent.com/56302715/139229606-a04edc5b-341a-456c-8ebf-c38d34cf1d0d.png)

Solution: aligner la séquence après recopie
```js
const maxId = await knex.raw('SELECT MAX(id) FROM "complementary-certification-habilitations"');

const idForNextInsertion = maxId + 1;

await knex.raw(`ALTER SEQUENCE "complementary-certifications_id_seq" RESTART WITH ${idForNextInsertion})`;

```

2021-10-28 09:40 UTC, octo-topi requested changes
La migration des données aboutit à des séquences à 1, ce qui entrainera des blocages à l'INSERT, genre "PK violated"
Voir https://github.com/1024pix/pix/pull/3657/files#r738218498

2021-10-28 09:40 UTC, sroccaserra commented on api/tests/unit/domain/usecases/retrieve-last-or-create-certification-course_test.js
> -              certificationCenterRepository.getBySessionId.resolves(session);
Effectivement, bien vu :)

2021-10-28 09:55 UTC, sroccaserra commented on api/db/migrations/20211025155811_create-table-complementary-certification-habilitations.js
> +  return knex.batchInsert('complementary-certification-habilitations', complementaryCertificationHabilitations);
On pourrait aussi remplacer le knex.batchInsert par un knex.insert, ça évite le knex.raw.

Cependant on peut aussi se demander ce qui se passerait si un granted accreditation est inséré entre le select et le insert, et ce même dans la version knex.raw (je jette un oeil à la doc PG de insert).

2021-10-28 10:11 UTC, sroccaserra commented on api/db/migrations/20211025155811_create-table-complementary-certification-habilitations.js
> +  return knex.batchInsert('complementary-certification-habilitations', complementaryCertificationHabilitations);
Question complémentaire : est-ce que tous les noeuds API utiliseront déjà la nouvelle version du code au moment de la migration ? Je ne pense pas, ce qui fait qu'il est possible qu'il y ait des insertions dans granted accreditations pendant que la migration est en train de s'effectuer ?

2021-10-28 14:22 UTC, MathieuGilet commented on api/db/migrations/20211025155811_create-table-complementary-certification-habilitations.js
> +    t.increments().primary();
J'ai rajouté le réalignement des index dans les scripts.

2021-10-28 14:22 UTC, MathieuGilet commented on api/db/migrations/20211025155811_create-table-complementary-certification-habilitations.js
> +  return knex.batchInsert('complementary-certification-habilitations', complementaryCertificationHabilitations);
J'ai laissé du pure knex mais j'ai utilisé un insert au lieu d'un batch insert.

2021-10-28 15:51 UTC, MathieuGilet commented on api/db/migrations/20211025132405_create-table-complementary-certifications.js
> +exports.up = async function(knex) {
C'était juste pour mieux découper et faciliter la review.

2021-10-29 08:29 UTC, octo-topi commented on api/db/migrations/20211025132405_create-table-complementary-certifications.js
> +exports.up = async function(knex) {
En fait, ce qui me fait dire ça, c'est qu'il y a une dépendance temporelle subtile pour que les FK soient respectées.
- en premier: 20211025132405_create-table-complementary-certifications.js
- en deuxième: 20211025155811_create-table-complementary-certification-habilitations.js

Et pour savoir qui passe premier, [est-ce le timestamp dans le nom de fichier](https://stackoverflow.com/questions/50152098/knex-order-of-schmas-migrated), y a-t-il des ID internes, y a-t-il un tri dans les autres PR ? 

[La doc n'est pas très claire]([url](https://knexjs.org/#Migrations))
Bref, un seul fichier, ça répond à la question facilement.

2021-10-29 08:32 UTC, octo-topi commented on api/db/migrations/20211025155811_create-table-complementary-certification-habilitations.js
> +  return knex.batchInsert('complementary-certification-habilitations', complementaryCertificationHabilitations);
@sroccaserra on a prévu de demander aux utilisateur de PixAdmin de ne pas y toucher pendant la MEP, voir [thread Slack](https://1024pix.slack.com/archives/CHGPQ7W9W/p1635411420004200?thread_ts=1635326524.006700&cid=CHGPQ7W9W). Il aurait été possible de gérer le cas dont tu parles, mais ça fait de la complexité pour peu de valeur métier.

2021-10-29 08:51 UTC, octo-topi commented on api/db/migrations/20211025155811_create-table-complementary-certification-habilitations.js
> +    t.increments().primary();
J'ai retesté, il y avait une `)` de trop. Je pousse la correction
```
migration file "20211025155811_create-table-complementary-certification-habilitations.js" failed
migration failed with error: ALTER SEQUENCE "complementary-certification-habilitations_id_seq" RESTART WITH 100655) - syntax error at or near ")"
error: ALTER SEQUENCE "complementary-certification-habilitations_id_seq" RESTART WITH 100655) - syntax error at or near ")"

```

2021-10-29 09:32 UTC, aceol commented on api/db/migrations/20211025132405_create-table-complementary-certifications.js
> +exports.up = async function(knex) {
C'est les timestamps effectivement

2021-10-29 10:00 UTC, octo-topi commented on api/db/migrations/20211025155811_create-table-complementary-certification-habilitations.js
> +    t.increments().primary();
J'ai retesté, il y avait une typo sur 
```
-- old
const maxIdResult = await knex('complementary-certifications').max('id').first();
-- new
const maxIdResult = await knex('complementary-certification-habilitations').max('id').first();
```
J'ai poussé la correction, c'est :heavy_check_mark:

2021-10-29 10:01 UTC, octo-topi approved these changes
Testé OK après correction https://github.com/1024pix/pix/pull/3657#discussion_r739101754

2021-10-29 13:01 UTC, merged