[FEATURE] Annulation d'une invitation envoyée par l'admin d'une organisation (PIX-399)
1024pix/pix pull request #3731
Opened 2021-11-15 11:03 UTC by annemarie35

## :christmas_tree: Problème
> _Décrivez ici le besoin ou l'intention couvert par cette Pull Request._

## :gift: Solution
> _Ajoutez à cet endroit, si nécessaire, des détails concernant la solution technique retenue et mise en oeuvre, des difficultés ou problèmes rencontrés._

## :star2: Remarques
> _Des infos supplémentaires, trucs et astuces ?_

## :santa: Pour tester
> _Les instructions pour reproduire le problème, les profils de test, le parcours spécifique à utiliser, etc._

2021-11-15 11:08 UTC, pix-service commented
I'm deploying this PR to these urls:

- App (.fr): https://app-pr3731.review.pix.fr
- App (.org): https://app-pr3731.review.pix.org
- Orga: https://orga-pr3731.review.pix.fr
- Certif: https://certif-pr3731.review.pix.fr
- Admin: https://admin-pr3731.review.pix.fr
- API: https://api-pr3731.review.pix.fr/api/

 Please check it out!

2021-11-23 13:38 UTC, AndreiaPena commented
**Remarque:**
En passant la souris sur le bouton pour supprimer l'invit, je constate qu'il y a un conflit entre le changement de couleur du bouton (qui passe en gris foncé ) et le hover de toute la ligne qui passe lui aussi en gris foncé.
Peut-être demander un avis/retour de Quentin sur ce que l'on attend dans ce cas de figure ? 

<img width="271" alt="Capture d’écran 2021-11-23 à 14 36 02" src="https://user-images.githubusercontent.com/58915422/143034173-bae301d3-0c4e-4278-a617-2af1caf9c93b.png">

2021-11-23 14:14 UTC, yschoueri requested changes

2021-11-23 14:14 UTC, yschoueri commented on api/lib/application/organizations/index.js
> +      method: 'PUT',
Pourquoi un PUT et pas un DELETE ? et sinon je verrai plutot un PATCH si pas un DELETE

2021-11-23 14:14 UTC, yschoueri commented on orga/app/components/team/invitations-list.hbs
> +        {{#if invitation.isPending}}
Perso je pense que ce serait mieux que l'API ne retourne que les invitations qui sont pending

2021-11-23 14:14 UTC, yschoueri commented on api/lib/application/organizations/organization-controller.js
> +    });
La repetition est redondante
```suggestion
    const cancelledOrganizationInvitation = await usecases.cancelOrganizationInvitation({ organizationInvitationId });
```

2021-11-23 14:14 UTC, yschoueri commented on orga/tests/integration/components/team/invitations-list_test.js
> +  test('it should show success notification when cancel an invitation succeed', async function (assert) {
```suggestion
  test('it should show success notification when cancelling an invitation succeeds', async function (assert) {
```

2021-11-23 14:14 UTC, yschoueri commented on orga/tests/integration/components/team/invitations-list_test.js
> +  test('it should show error notification when cancel an invitation failed', async function (assert) {
```suggestion
  test('it should show error notification when cancelling an invitation fails', async function (assert) {
```

2021-11-23 14:43 UTC, Anne-Gaelle-S commented on api/lib/application/organizations/index.js
> +      method: 'PUT',
PUT parce que c'était idempotent, mais je me demande aussi si le DELETE serait pas mieux ... 🤔

2021-11-23 14:44 UTC, Anne-Gaelle-S commented on orga/app/components/team/invitations-list.hbs
> +        {{#if invitation.isPending}}
c'est déjà le cas, le if est là pour enlever visuellement l'invitation dès qu'on la cancel :/

2021-11-23 14:44 UTC, Anne-Gaelle-S commented on orga/app/components/team/invitations-list.hbs
> +        {{#if invitation.isPending}}
mais du coup si on fait un DELETE on pourrait surement enlever ce if

2021-11-23 15:11 UTC, Anne-Gaelle-S commented on api/lib/application/organizations/index.js
> +      method: 'PUT',
J'ai rajouté un commit qui change en DELETE (en plus ça corrige le soucis qu'a soulevé Andreia)

2021-11-23 15:40 UTC, yschoueri commented on api/lib/application/organizations/index.js
> +      method: 'PUT',
ok ca marche

2021-11-23 15:43 UTC, yschoueri commented on orga/app/models/organization.js
> +  get pendingOrganizationInvitationsCount() {
A voir si ca c'est toujours necessaire ?

2021-11-23 15:43 UTC, AndreiaPena commented on api/lib/application/organizations/index.js
> +            "- Elle permet à l'administrateur de l'organisation d'annuler une invitation envoyée mais non acceptée encore.",
```suggestion
          "- **Cette route est restreinte aux utilisateurs authentifiés en tant qu'administrateur d'une organisation**\n" +
            "- Elle permet à l'administrateur de l'organisation d'annuler une invitation en attente.",
```

2021-11-23 15:43 UTC, AndreiaPena commented on api/lib/application/organizations/index.js
> +            invitationId: identifiersType.organizationInvitationId,
```suggestion
            organizationInvitationId: identifiersType.organizationInvitationId,
```

autant garder le même nommage partout et surtout on est plus explicite avec l'ajout du organization

2021-11-23 15:46 UTC, yschoueri approved these changes

2021-11-23 15:46 UTC, Anne-Gaelle-S commented on orga/app/models/organization.js
> +  get pendingOrganizationInvitationsCount() {
non :D

2021-11-23 15:47 UTC, AndreiaPena commented on api/tests/unit/domain/usecases/cancel-organization-invitation_test.js
> +  context('when invitation exist ', function () {
```suggestion
  context('when invitation exist', function () {
```

2021-11-23 16:08 UTC, Anne-Gaelle-S commented on api/lib/application/organizations/index.js
> +            invitationId: identifiersType.organizationInvitationId,
done :D

2021-11-24 09:34 UTC, annemarie35 commented on api/lib/application/organizations/index.js
> +      method: 'PUT',
Pareil, pour l'idempotence et le fait ça aurait été cool un DELETE mais comme on supprime pas du tout la donnée je trouve que ça crée de la confusion... La route PUT avec le cancel a le mérite d'être très explicite sur ce qu'elle fait. 
Je me sers de cet article https://blog.octo.com/should-i-put-or-should-i-patch/

2021-11-24 09:34 UTC, annemarie35 commented on orga/app/components/team/invitations-list.hbs
> +        {{#if invitation.isPending}}
C'est l'appel GET http://localhost:4202/api/admin/organizations/1/invitations qui récupère la list des invitations non ?
Je me perds un peu encore avec la magie d'ember

2021-11-24 09:35 UTC, annemarie35 commented on api/lib/application/organizations/index.js
>        path: '/api/organizations/{id}/invitations/{invitationId}/cancel',
@Anne-Gaelle-S si on met un DELETE, il n'y a plus besoin du /cancel en fin de route

2021-11-24 13:24 UTC, AndreiaPena commented
A11Y : On a eu un retour de Tanaguru sur les toasters, les notifications du succès ou d'echec qui apparaissent suite à une action. Ils doivent être restitués par les lecteurs d'écran, ce qui n'est pas le cas actuellement.
Coté Pix Orga, on utilise `ember-cli-notifications` pour les notifications. J'ai pas vraiment creusé dans le cas, mais il faudrait pouvoir surcharger des notifications avec un `role=alert` pour les messages d'erreurs et un `role=status` pour les messages de succès (sur cette PR on a ce deuxième cas) 
<img width="775" alt="Capture d’écran 2021-11-24 à 14 20 02" src="https://user-images.githubusercontent.com/58915422/143246108-5d543d9b-d336-455c-a368-f8325d6d6fbb.png">

2021-11-24 13:32 UTC, AndreiaPena commented on api/tests/acceptance/application/organizations/cancel-organization-invitation-put_test.js
> +  describe('DELETE /api/organizations/{id}/invitations/{invitationId}', function () {
**Remarque :** Remplacer le `put` du nom du fichier de test par `delete`

2021-11-25 09:04 UTC, AndreiaPena approved these changes

2021-11-25 10:07 UTC, merged