[FEATURE] Badge: Ajouter un critère sur un ensemble d'acquis (frontend)
1024pix/pix pull request #3761
Opened 2021-11-23 09:27 UTC by nlepage

## :christmas_tree: Problème
Sur Pix Admin, sur la création d'un badge, je dois pouvoir créer un nouvel ensemble d'acquis :

 - Pouvoir ajouter une ligne dans la table Skills-set avec une liste d'acquis.
 - Ne pas avoir à saisir les {} à la main…

## :gift: Solution
Adapter l'écran pour permettre l'ajout d'un criteria de type SkillSets avec un seul SkillSet pour le moment.
https://share.goabstract.com/c6eaea93-f791-403e-b407-ff4a5d7cac0e?collectionLayerId=dd8aac4c-9078-43aa-a950-6aeafdcacd0f&mode=design

## :star2: Remarques
Non

## :santa: Pour tester
Se rendre dans pix admin et créer un badge avec un critère sur un ensemble d'acquis.
Vérifier que tout est OK en BdD.

2021-11-23 09:32 UTC, pix-service commented
I'm deploying this PR to these urls:

- App (.fr): https://app-pr3761.review.pix.fr
- App (.org): https://app-pr3761.review.pix.org
- Orga: https://orga-pr3761.review.pix.fr
- Certif: https://certif-pr3761.review.pix.fr
- Admin: https://admin-pr3761.review.pix.fr
- API: https://api-pr3761.review.pix.fr/api/

 Please check it out!

2021-12-06 14:44 UTC, yannbertrand approved these changes

2021-12-08 08:26 UTC, MelanieMEB requested changes
J'ai un soucis à la func review :
Je crée bien le critère, mais coté Pix Admin, on ne voit pas la liste des acquis.
Coté BDD, le critère est bien présent, mais le `SkillSetIds` est vide, malgré que le `skill-set` a bien été créé. Soucis coté api peut-être.

2021-12-08 08:26 UTC, MelanieMEB commented on api/lib/domain/usecases/create-skill-set.js
> +  return await skillSetRepository.save({
```suggestion
  return skillSetRepository.save({
```

2021-12-08 14:33 UTC, nlepage commented
> J'ai un soucis à la func review : Je crée bien le critère, mais coté Pix Admin, on ne voit pas la liste des acquis. Coté BDD, le critère est bien présent, mais le `SkillSetIds` est vide, malgré que le `skill-set` a bien été créé. Soucis coté api peut-être.

Il y avait un souci avec le serializer du criterion.

2021-12-09 09:34 UTC, MelanieMEB approved these changes
Globalement OK, proposition d'une petite modification pour éviter des bugs futurs

2021-12-09 09:34 UTC, MelanieMEB commented on admin/app/components/target-profiles/badge-form.js
> +      const skillIds = this.skillSet.skills.split(',');
```suggestion
      const skillIds = this.skillSet.skills.replace(/ /g,'').split(',');
```
J'ai testé en c/c des id, j'ai laissé des espaces, et ca a un peu cassés ma listes. Je propose donc cette petite modification

2021-12-09 10:28 UTC, merged