[TECH] Améliorer l'accessibilité de la navigation sur Pix Orga (PIX-3894).
1024pix/pix pull request #3781
Opened 2021-11-26 15:25 UTC by AndreiaPena

## :christmas_tree: Problème
De nombreuses pages sur Pix Orga ne répondent pas aux critères d'accessibilité.
Une audit accessibilité sur cette application nous permet désormais de corriger ces manques.

Actuellement nous ne remplissons pas le critère suivant : **Dans chaque page web, le contenu visible porteur d’information reste-t-il présent lorsque les feuilles de styles sont désactivées ?**

Lorsque les styles sont désactivés, les "boutons" du menu déroulant ne sont plus cliquables.

## :gift: Solution
Ajouter des boutons dans le menu déroulant pour rendre les éléments cliquables.

## :star2: Remarques
L'utilisation de `role="button"` sur un `<li>` lui fait perdre sa nature d'élément de liste en plus de rendre le bouton inutilisable en mode CSS désactivé. Il faut donc intégrer un `<button>` dans un `<li>` pour éviter ce problème.

## :santa: Pour tester
- Se connecter sur Pix Orga (ex : sco.admin@example.net )
- Utiliser Wave pour retirer les feuilles de style de l'application
<img width="380" alt="Capture d’écran 2021-11-26 à 16 22 25" src="https://user-images.githubusercontent.com/58915422/143602358-0a145cba-1095-4a96-bfd5-49c2e9ac7729.png">
- Constater que la liste (les orgas et la partie "Se déconnecter) sont des boutons et sont cliquables

2021-11-26 15:30 UTC, pix-service commented
I'm deploying this PR to these urls:

- App (.fr): https://app-pr3781.review.pix.fr
- App (.org): https://app-pr3781.review.pix.org
- Orga: https://orga-pr3781.review.pix.fr
- Certif: https://certif-pr3781.review.pix.fr
- Admin: https://admin-pr3781.review.pix.fr
- API: https://api-pr3781.review.pix.fr/api/

 Please check it out!

2021-11-26 15:44 UTC, yschoueri requested changes

2021-11-26 15:44 UTC, yschoueri commented on orga/app/components/dropdown/item.hbs
> +<li class="dropdown__item dropdown__item--link" {{on "click" @onClick}} {{on "keyup" this.handleKeyUp}} ...attributes>
le click devrait se mettre sur le button alors et non pas sur le li

2021-11-26 16:09 UTC, yschoueri approved these changes

2021-11-29 10:09 UTC, Anne-Gaelle-S approved these changes
🥰

2021-11-29 10:34 UTC, merged