[FEATURE] Ajour d'un script pour supprimer les mots de passe des users anonimisés (PIX-3459)
1024pix/pix pull request #3826
Opened 2021-12-10 17:04 UTC by Anne-Gaelle-S

## :christmas_tree: Problème
Avant la feature d'anonymisation de tous les types d'utilisateurs, pour anonymiser certains utilisateurs, il était nécessaire de faire des requêtes directement sur la base de production.
Sauf que les méthodes de connexions n'étaient pas supprimées. Et un utilisateur correctement "anonimisés" ne devrait plus avoir son mot de passe dans la BDD pix.
Aujourd'hui il y a +2000 users anonymisés qui ont encore un mot de passe.

## :gift: Solution
Créer un script permettant de "nettoyer" (aka supprimer les authentication methods) les mots de passes des utilisateurs anonymisés

## :star2: Remarques
RAS

## :santa: Pour tester
- Créer un fichier `liste.csv` avec dedans une liste d'id de users : 
```
ID
199
99
100
```
- Vérifier en BDD que ces users on bien une `authentication-methods` avec un password
- Lancez `node ./scripts/clean-anonymized-users-passwords.js liste.csv`
- Constatez que le script s'exécute bien.
- Allez en base et vérifier que les authentication-methods des id précédemment utilisés ont été supprimées.

2021-12-10 17:09 UTC, pix-service commented
I'm deploying this PR to these urls:

- App (.fr): https://app-pr3826.review.pix.fr
- App (.org): https://app-pr3826.review.pix.org
- Orga: https://orga-pr3826.review.pix.fr
- Certif: https://certif-pr3826.review.pix.fr
- Admin: https://admin-pr3826.review.pix.fr
- API: https://api-pr3826.review.pix.fr/api/

 Please check it out!

2021-12-13 10:58 UTC, AndreiaPena submitted a review, later dismissed
Ne doit-on pas supprimer toutes les `authentication-methods` de l'utilisateur dans ce script ? 
Et pas uniquement les authentication-methods avec mot de passe.

2021-12-13 11:36 UTC, AndreiaPena requested changes
Vu avec Emmy et Thierry, bien que les autres `authentication-methods` (PE,GAR) aient été supprimé à la main, on s'assure de tous supprimer dans ce script (PE,GAR,PIX) pour s'éviter des loupés.

2021-12-14 15:16 UTC, AndreiaPena commented on api/scripts/clean-anonymized-users-passwords.js
> +    });
```suggestion
    const numberOfRowDeleted = await authenticationMethodRepository.removeAllAuthenticationMethodsByUserId({
      userId,
    });
```

2021-12-14 15:17 UTC, AndreiaPena commented on api/scripts/clean-anonymized-users-passwords.js
> +async function cleanAnonymizedUsersPasswords({ arrayOfAnonymizedUsersIds }) {
```suggestion
async function cleanAnonymizedAuthenticationMethods({ arrayOfAnonymizedUsersIds }) {
```

2021-12-14 15:19 UTC, AndreiaPena commented on api/scripts/clean-anonymized-users-passwords.js
> +  console.log('Starting cleaning anonymized users with passwords');
```suggestion
  console.log('Starting deleting anonymized users authentication methods');
```

Je sais pas si c'est correct mais c'est plus l'idée.

2021-12-14 15:21 UTC, AndreiaPena commented on api/scripts/clean-anonymized-users-passwords.js
> +  const anonymizedUserIdsWithPasswordDeleted = [];
```suggestion
  const anonymizedUserIdsWithAuthenticationMethodsDeleted = [];
```

2021-12-14 15:24 UTC, AndreiaPena commented
Globalement, tout dans le code qui rapport à la suppression d'un mot de passe devrait être modifié en suppression de méthodes de connexion

2021-12-14 16:17 UTC, AndreiaPena approved these changes

2021-12-14 16:22 UTC, AndreiaPena commented
Testé avec un user possédant une seule authentication-method et un autre user possédant 2 authentication-method.

ℹ️ Par contre si je relance le script avec les mêmes userId, le script se déroule sans problème, bien qu'il n'ai rien supprimé.
Est-ce qu'on devrait bloquer ou laisser tel quel ? Il n'y a je pense aucun risque à laisser faire même s'il ne trouve pas le userId en question, si ?

2021-12-15 11:21 UTC, annemarie35 approved these changes

2021-12-15 13:41 UTC, yschoueri commented on api/scripts/clean-anonymized-users-authentication-methods.js
> +      .value();
pourquoi pas le faire en pure js?
```suggestion
    const arrayOfAnonymizedUsersIds = anonymizedUsersIds
      .filter((user) => !_.isNil(user.ID));
      .map((user) => user.ID)
```

2021-12-15 13:42 UTC, yschoueri approved these changes

2021-12-16 09:51 UTC, Anne-Gaelle-S commented on api/scripts/clean-anonymized-users-authentication-methods.js
> +      .value();
y'a un petit avantage je crois, c'est que le filter de lodash ne throw pas sur les valeurs `undefined` , lodash apporte une petite surcouche de magie qui protège des cas un peu tordu du js natif

2021-12-16 10:06 UTC, merged