[FEATURE] Supprimer la case de fin de test pour les sessions dont le centre est autorisé (PIX-4141)
1024pix/pix pull request #3945
Opened 2022-01-14 15:48 UTC by aceol

## :unicorn: Problème
2 feature sont sous FT de case de fin de test mais sans prendre en compte le centre de certification:
- ecran de fin de test du passage de certification
- lien dans le menu (gauche) de certif

## :robot: Solution
Faire dépendre ces 2 features des centres de certification autorisés par la whitelist

## :rainbow: Remarques
On a choisi de ne pas modifié le model et de rajouter des infos directement dans le serializer

## :100: Pour tester
Verifier le lien vers l'espace surveillant dans certif et s'assurer qu'il s'affiche en fonction du centre de certification en cours (en haut à droit)
<img width="1430" alt="Screenshot 2022-01-12 at 15 08 48" src="https://user-images.githubusercontent.com/3769147/149732720-58c1115d-1103-40aa-a3e4-853effd0bc13.png">

Passer la certification sur une session dans un centre NON autorisé, voir que la case de fin de test s'affiche comme avant. 

Passer la certification sur une session dans un centre autorisé, voir que la case de fin de test ne s'affiche plus et qu'on a bien le nouvel ecran.

2022-01-14 15:53 UTC, pix-service commented
I'm deploying this PR to these urls:

- App (.fr): https://app-pr3945.review.pix.fr
- App (.org): https://app-pr3945.review.pix.org
- Orga: https://orga-pr3945.review.pix.fr
- Certif: https://certif-pr3945.review.pix.fr
- Admin: https://admin-pr3945.review.pix.fr
- API: https://api-pr3945.review.pix.fr/api/

 Please check it out!

2022-01-17 08:45 UTC, iwazaru approved these changes

2022-01-17 08:45 UTC, iwazaru commented on mon-pix/tests/acceptance/certification-course_test.js
> +          //server.create('feature-toggle', { id: 0, isEndTestScreenRemovalEnabled: true });
**nitpick**
À supprimer
```suggestion

```

2022-01-17 08:45 UTC, iwazaru commented on mon-pix/tests/acceptance/certification-course_test.js
> +          // server.create('feature-toggle', { id: 0, isEndTestScreenRemovalEnabled: true });
**nitpick**
À supprimer
```suggestion

```

2022-01-17 09:29 UTC, P-Jeremy commented
Test ok pour la majorité des cas, mais lors de la finalisation d'une session dont le centre fait parti de la whitelist, on voit ce message avant confirmation de la finalisation

![image](https://user-images.githubusercontent.com/37305474/149743490-143c9c59-05ff-49e5-afe2-60e67087a7aa.png)

2022-01-17 09:42 UTC, MathieuGilet approved these changes

2022-01-17 10:04 UTC, octo-topi requested changes, later dismissed
https://github.com/1024pix/pix/pull/3945#issuecomment-1014313387

2022-01-17 11:50 UTC, P-Jeremy commented
Test ok pour la case de fin de test lors de la finalisation

![image](https://user-images.githubusercontent.com/37305474/149764697-18926e2f-a100-466e-a40f-ebea8647ee51.png)

2022-01-17 14:21 UTC, P-Jeremy approved these changes

2022-01-17 15:10 UTC, merged