[ORGA] Améliorer l'affichage des colonnes de la liste des campagnes
1024pix/pix pull request #3954
Opened 2022-01-18 17:16 UTC by yschoueri

## :unicorn: Problème
Quand la page n'est pas assez large, le texte dans les colonnes est tronqué parfois au milieu du mot.

## :robot: Solution
Ne pas permettre le troncage en milieu de mot et limiter la largeur des colonnes. 

## :100: Pour tester
Accéder à (Pix-Orga)[https://orga-pr3921.review.pix.fr]
Vérifier le texte dans les colonnes en changeant la largeur de la page.

2022-01-18 17:21 UTC, pix-service commented
I'm deploying this PR to these urls:

- App (.fr): https://app-pr3954.review.pix.fr
- App (.org): https://app-pr3954.review.pix.org
- Orga: https://orga-pr3954.review.pix.fr
- Certif: https://certif-pr3954.review.pix.fr
- Admin: https://admin-pr3954.review.pix.fr
- API: https://api-pr3954.review.pix.fr/api/

 Please check it out!

2022-01-18 17:37 UTC, AndreiaPena commented
**Suggestion**
Si on suit les conventions, je propose en titre: `[FEATURE] Améliorer l'affichage des colonnes de la liste des campagnes sur Pix Orga (PIX-4149).`

2022-01-19 09:36 UTC, AndreiaPena commented on orga/app/components/campaign/list.hbs
> +      </colgroup>
**Question**
Visiblement il y avait déjà une gestion des tailles de colonnes dans les `<Table::Header @size="wide">` juste en bas, est-ce que ça ne pouvait pas s'ajouter à cette endroit là ? 
Si ça ne pouvait pas se faire, est-ce qu'il vaut mieux aussi supprimer ces sizes pour tout rassembler à un même endroit.
Le fait d'avoir ça a deux endroits différents me perd un peu.

2022-01-19 14:18 UTC, yschoueri commented on orga/app/components/campaign/list.hbs
> +      </colgroup>
j'ai bouge le width sur col parce que min-width et max-width ne fonctionne pas sur les th et td

2022-01-19 14:43 UTC, yschoueri commented
> **Suggestion** Si on suit les conventions, je propose en titre: `[FEATURE] Améliorer l'affichage des colonnes de la liste des campagnes sur Pix Orga(PIX-4149).`

Vu que ce n'est plus que la liste des campagnes, je l'ai enleve du titre

2022-01-19 16:51 UTC, AndreiaPena commented
Est-ce que tu peut compléter la partie test pour notifier quels sont les tableaux impactés par tes modifications ? Merci 🙏

2022-01-19 17:23 UTC, AndreiaPena commented
Visuellement, j'observe un soucis sur la table des participations à une campagne. ( Quand on clique sur une campagne, le tableau qui montre les élèves ayant finalisé le parcours ou en cours ) en version mobile.
Il existait déjà sur dev, mais il est accentué ici.

Sur dev : 
<img width="363" alt="Capture d’écran 2022-01-19 à 18 07 49" src="https://user-images.githubusercontent.com/58915422/150181567-add98c4f-3681-46a8-832a-3610d06a53cc.png">

Sur la branche : 
<img width="363" alt="Capture d’écran 2022-01-19 à 18 08 01" src="https://user-images.githubusercontent.com/58915422/150181651-1665e556-f1ba-4450-8e8d-988299fa4511.png">

Ça se "corrige" quand je décoche ça mais je ne sais pas si c'est la solution :) 
<img width="748" alt="Capture d’écran 2022-01-19 à 18 17 35" src="https://user-images.githubusercontent.com/58915422/150182043-3865ed83-fe78-44fd-962b-9711f8e0e8d3.png">

2022-01-19 17:23 UTC, AndreiaPena commented on orga/app/components/campaign/list.hbs
> +      </colgroup>
Ok !

2022-01-19 17:48 UTC, AndreiaPena requested changes
Visuellement, j'observe des soucis en version mobile sur les tables : 
- Equipe
- Campagnes
-  Participations à une campagne. 
- ( pas check sur les autres encore)

Tableau Participations à une campagne : 
<img width="363" alt="Capture d’écran 2022-01-19 à 18 08 01" src="https://user-images.githubusercontent.com/58915422/150181651-1665e556-f1ba-4450-8e8d-988299fa4511.png">

Ça se "corrige" quand je décoche ça mais je ne sais pas si c'est la solution :) 
<img width="448" alt="Capture d’écran 2022-01-19 à 18 17 35" src="https://user-images.githubusercontent.com/58915422/150182043-3865ed83-fe78-44fd-962b-9711f8e0e8d3.png">
 

Tableau Campagnes :
Le `td` ne prend plus toute la ligne et reste écrasé dans la partie gauche, ça pose problème car l'utilisateur ne pourra plus tapoter sur toute la ligne pour accéder aux détails d'une campagne.

<img width="522" alt="Capture d’écran 2022-01-19 à 18 38 35" src="https://user-images.githubusercontent.com/58915422/150184724-2566137b-fe8f-445b-ab2e-6704b7dbb822.png">

en dev : 
<img width="522" alt="Capture d’écran 2022-01-19 à 18 38 26" src="https://user-images.githubusercontent.com/58915422/150185133-a6389799-f59c-4cff-9162-0585f7466d2f.png">


Tableau Equipe : 
<img width="370" alt="Capture d’écran 2022-01-19 à 18 36 26" src="https://user-images.githubusercontent.com/58915422/150185193-8b70c6d7-c259-42ce-92e7-65f941532336.png">

2022-01-21 10:20 UTC, AndreiaPena approved these changes

2022-01-24 16:28 UTC, AndreiaPena commented on orga/app/components/student/sco/list.hbs
> +            <td class="ellipsis" title={{student.firstName}}>{{student.firstName}}</td>
tu as besoin du title pour réduire les nom et prénom en ... ?

2022-01-24 16:51 UTC, yschoueri commented on orga/app/components/student/sco/list.hbs
> +            <td class="ellipsis" title={{student.firstName}}>{{student.firstName}}</td>
le title c'est comme il risque d'etre tronque, le user peut survoler dessus et avoir le nom au complet

2022-01-25 08:57 UTC, annemarie35 approved these changes

2022-01-25 09:36 UTC, merged