[FEATURE] Renommer les labels "Créée par" en "Propriétaire" sur Pix Orga (PIX-4148).
1024pix/pix pull request #3975
Opened 2022-01-26 10:16 UTC by AndreiaPena

## :unicorn: Problème
Dans le cadre de la gestion des accès sur Pix Orga, on affiche désormais le nom des propriétaires des campagnes. Mais les labels sont resté inchangés le temps d'implémenter la gestion.

## :robot: Solution
Renommer les labels "Créée par" en "Propriétaire" sur les pages suivantes : 
- Onglet Toutes les campagnes > Dans le tableau, deuxième colonne
- Dans la page de détails d'une campagne en haut à droite.

## :rainbow: Remarques
Le label "Campagnes" à également été renommé en "Nom de la campagne"

## :100: Pour tester
Se connecter sur Pix Orga, se mettre en domaine `org` pour pouvoir changer facilement de langue.
- Onglet `Mes campagnes`  > la colonne "Campagnes" devient "Nom de la campagne" (en anglais “Name of the campaign”)
- Onglet `Mes campagnes` > "Créé le" devient "Créée le"

- Onglet `Toutes les campagnes` > la colonne "Campagnes" devient "Nom de la campagne" (en anglais “Name of the campaign”)
- Onglet `Toutes les campagnes` > "Créé le" devient "Créée le"
- Onglet `Toutes les campagnes` > "Créé par" devient "Propriétaire" (en anglais “Owner”)

- Sur la page de détails d'une campagne > "Créé par" devient "Propriétaire" (en anglais “Owner”)

2022-01-26 10:23 UTC, pix-service commented
I'm deploying this PR to these urls:

- App (.fr): https://app-pr3975.review.pix.fr
- App (.org): https://app-pr3975.review.pix.org
- Orga: https://orga-pr3975.review.pix.fr
- Certif: https://certif-pr3975.review.pix.fr
- Admin: https://admin-pr3975.review.pix.fr
- API: https://api-pr3975.review.pix.fr/api/

 Please check it out!

2022-01-26 10:39 UTC, ebarbier requested changes
J'ai oublié. Tu peux renommer le placeholder des filtres aussi?
"Rechercher un créateur" => "Rechercher un propriétaire"
"Search for a creator" => "Search for an owner"

2022-01-26 15:19 UTC, AndreiaPena commented
> J'ai oublié. Tu peux renommer le placeholder des filtres aussi? "Rechercher un créateur" => "Rechercher un propriétaire" "Search for a creator" => "Search for an owner"

Done :)

2022-01-27 11:32 UTC, Anne-Gaelle-S approved these changes

2022-01-27 13:50 UTC, ebarbier approved these changes

2022-01-31 14:00 UTC, yschoueri approved these changes

2022-01-31 14:23 UTC, annemarie35 approved these changes

2022-01-31 14:23 UTC, annemarie35 commented on orga/tests/integration/components/campaign/filter/filters_test.js
>      assert.contains('Filtres');
Doit-on remplacer également les assert.contains en utilisant ember-testing-library ? Il me semblait que oui car la fonction contains est un helper orga/tests/helpers/contains.js

2022-01-31 14:23 UTC, annemarie35 commented on orga/tests/integration/components/campaign/list_test.js
> +      assert.dom('[placeholder="Rechercher un propriétaire"]').exists();
l'assertion n'était pas possible avec ember-testing-library ?

2022-01-31 16:04 UTC, Anne-Gaelle-S commented on orga/tests/integration/components/campaign/filter/filters_test.js
>      assert.contains('Filtres');
done :)

2022-01-31 16:06 UTC, Anne-Gaelle-S commented on orga/tests/integration/components/campaign/list_test.js
> +      assert.dom('[placeholder="Rechercher un propriétaire"]').exists();
je regarde 👀

2022-01-31 16:10 UTC, Anne-Gaelle-S commented on orga/tests/integration/components/campaign/list_test.js
> +      assert.dom('[placeholder="Rechercher un propriétaire"]').exists();
apparament si on peut faire avec getByPlaceholderText https://testing-library.com/docs/queries/byplaceholdertext/ :D

2022-02-01 15:28 UTC, merged