[TECH] Améliorer la cohérence des fichiers YAML.
1024pix/pix pull request #3983
Opened 2022-01-27 12:09 UTC by octo-topi

## :unicorn: Problème
Les fichiers YAML ont deux extensions possibles, ce qui n'est pas intuitif:
- yaml
- yml

Les fichiers YAML de la racine présentent des différences avec deux des applications (quote, espacement)

## :robot: Solution
Utiliser uniquement l'extension `.yml`
Linter tous les fichiers à la racine

## :rainbow: Remarques
Le fichier  `docker-compose.yml` ne peut pas être linté.

```
/repo/pix/high-level-tests/e2e/docker-compose.yml
  13:21  error  Parsing error: Unexpected token .7
```

Il est ignoré grâce à un argument (inopérant dans le fichier `.eslintignore` ou dans la section `ignores` .

## :100: Pour tester
Vérifier que la CI est OK
Introduire une violation (ex: espace) et vérifier qu'elle sort en erreur

2022-01-27 12:15 UTC, pix-service commented
I'm deploying this PR to these urls:

- App (.fr): https://app-pr3983.review.pix.fr
- App (.org): https://app-pr3983.review.pix.org
- Orga: https://orga-pr3983.review.pix.fr
- Certif: https://certif-pr3983.review.pix.fr
- Admin: https://admin-pr3983.review.pix.fr
- API: https://api-pr3983.review.pix.fr/api/

 Please check it out!

2022-01-27 15:12 UTC, mickaelalibert commented
Je ne sais pas encore quelle est la compatibilité des différentes solutions utilisées avec ça, mais la recommandation officielle de YAML est d'utiliser l'extension `.yaml` dès que possible (cf. https://yaml.org/faq.html)

2022-01-28 08:04 UTC, octo-topi commented
> Je ne sais pas encore quelle est la compatibilité des différentes solutions utilisées avec ça, mais la recommandation officielle de YAML est d'utiliser l'extension `.yaml` dès que possible (cf. [yaml.org/faq.html](https://yaml.org/faq.html))

J'ai choisi `.yml` suite aux souvenirs de debug laborieux avant de comprendre que `.yaml` n'est pas reconnu par CircleCI
https://circleci.com/docs/2.0/writing-yaml/#overview

Pour Github au moins les deux sont possibles
https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#about-yaml-syntax-for-workflows

2022-02-03 11:12 UTC, mickaelalibert approved these changes
LGTM 😍 
Edit : C'est bien aussi de faire un triple check des fois ....

2022-02-03 11:15 UTC, mickaelalibert requested changes, later dismissed

2022-02-03 11:15 UTC, mickaelalibert commented on high-level-tests/e2e/docker-compose.yaml
> -  postgres:
ça va poser soucis si l'on ne change pas la configuration du reste des conteneurs pour qu'ils se connectent à `database` au lieu de `Postgres` dans le env-api

2022-02-03 11:30 UTC, octo-topi commented on high-level-tests/e2e/docker-compose.yaml
> -  postgres:
Corrigé

2022-02-03 12:58 UTC, mickaelalibert approved these changes

2022-02-03 17:19 UTC, merged