[FEATURE] Suppression d'un RT non assigné dans Pix-Admin (PIX-4288).
1024pix/pix pull request #4061
Opened 2022-02-09 15:28 UTC by alexandrecoin

## :unicorn: Problème

En cas d'erreur de saisie lors de la création d'un RT ou si celui-ci venait à ne plus être valable, il n'est pas possible de le supprimer dans le cas où il n'a pas encore été assigné au minimum à un utilisateur. 

## :robot: Solution

Création d'une route dédiée dans l'api à la suppression d'un RT non assigné.
Ajout d'un bouton de suppression dans pix-admin dans le tableau des RT

## :rainbow: Remarques
N/A

## :100: Pour tester

Pour vérifier qu'il est possible de supprimer un RT non assigné: 
- Créer un RT dans pix-admin et le supprimer par la suite

Pour vérifier qu'il n'est PAS possible de supprimer un RT assigné à un utilisateur:
- Réaliser la campagne `XXXXXX` et tenter de supprimer le RT une fois la campagne terminée.

2022-02-09 15:35 UTC, pix-service commented
I'm deploying this PR to these urls:

- App (.fr): https://app-pr4061.review.pix.fr
- App (.org): https://app-pr4061.review.pix.org
- Orga: https://orga-pr4061.review.pix.fr
- Certif: https://certif-pr4061.review.pix.fr
- Admin: https://admin-pr4061.review.pix.fr
- API: https://api-pr4061.review.pix.fr/api/

 Please check it out!

2022-02-10 14:15 UTC, matthiasferraina approved these changes

2022-02-11 09:46 UTC, nlepage requested changes
cf. mon dernier commentaire.

2022-02-11 09:46 UTC, nlepage commented on admin/app/components/target-profiles/badges.hbs
> +                @message="Etes-vous sûr de vouloir supprimer ce résultat thématique ? (Uniquement si le RT n'a pas encore été assigné)"
```suggestion
                @message="Êtes-vous sûr de vouloir supprimer ce résultat thématique ? (Uniquement si le RT n'a pas encore été assigné)"
```

2022-02-11 09:46 UTC, nlepage commented on admin/app/components/target-profiles/badges.hbs
> +                @show={{this.displayConfirm}}
On ne va pas pouvoir utiliser le même booléen pour toute la liste.

Actuellement ça empile autant de popups de confirmations qu'il y a de badges dans la liste, avec la popup du dernier de la liste en avant plan.

On supprime donc toujours le dernier badge de la liste !

2022-02-15 09:06 UTC, nlepage requested changes
**bug:**
 - essayer de supprimer un RT déjà assigné, on obtient bien le message d'erreur
 - essayer d'accéder au détail du même RT, ember plante...

2022-02-15 09:06 UTC, nlepage commented on api/lib/domain/usecases/delete-unassociated-badge.js
> +module.exports = async function deleteUnassociatedBadge({ badgeId, badgeRepository }) {
**suggestion:** idéalement il faudrait que la transaction soit créée à ce niveau et passée aux 3 appels de repository.

2022-02-15 13:26 UTC, nlepage approved these changes

2022-02-15 13:38 UTC, merged