[TECH ]Use a upstream with some parameters
1024pix/pix pull request #4097
Opened 2022-02-15 15:23 UTC by francois2metz

Co-authored-by: Mickaël Alibert <mickael.alibert@pix.fr>

## :unicorn: Problème
> _Décrivez ici le besoin ou l'intention couvert par cette Pull Request._

## :robot: Solution
> _Ajoutez à cet endroit, si nécessaire, des détails concernant la solution technique retenue et mise en oeuvre, des difficultés ou problèmes rencontrés._

## :rainbow: Remarques
> _Des infos supplémentaires, trucs et astuces ?_

## :100: Pour tester
> _Les instructions pour reproduire le problème, les profils de test, le parcours spécifique à utiliser, etc._

2022-02-15 15:28 UTC, pix-service commented
I'm deploying this PR to these urls:

- App (.fr): https://app-pr4097.review.pix.fr
- App (.org): https://app-pr4097.review.pix.org
- Orga: https://orga-pr4097.review.pix.fr
- Certif: https://certif-pr4097.review.pix.fr
- Admin: https://admin-pr4097.review.pix.fr
- API: https://api-pr4097.review.pix.fr/api/

 Please check it out!

2022-02-21 13:15 UTC, yahyayouness approved these changes
Ca aurait été bien d'avoir le résultat des tests en locale dans la description de la PR avec les libs utilisées pour valider les résultats souhaités.
Les liens des applications ne marchent plus, il manque la config pour les faire marcher !

2022-02-22 09:53 UTC, yahyayouness requested changes
Je remet en request change pour les liens de la PR qui ne sont pas accessible. https://app-pr4097.review.pix.fr/

2022-02-22 10:11 UTC, yahyayouness approved these changes
Vu ensemble, je remets ma coche car seul mon-pix est déployé dans cette RA en se basant sur la variable d'env project-dir. Le test est concluant avec l'url https://pix-front-review-pr4097.osc-fr1.scalingo.io.

2022-02-22 14:23 UTC, mickaelalibert commented
Pour en arriver à ce correctif, le chemin suivi a été le suivant :

Création d'un docker-compose pour reproduire le fonctionnement du trafic de Pix (nginx front-> nginx back):

```yaml
version: "3.9" 
services:
  front:
    image: nginx
    ports:
      - "8000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./server.conf:/etc/nginx/nginx.conf:ro
  api:
    image: nginx
    deploy:
      replicas: 3
```

La configuration du conteneur `front` est modifiée pour coller à celle de nos conteneurs Front sur pix,
et le proxy est configuré pour renvoyer vers nos trois conteneurs : 

```
server{
    location / {
        proxy_connect_timeout 15s;
        proxy_pass http://api/api;
        proxy_redirect default;
    }
}
```

En démarrant ces conteneurs, on obtient une infra similaire à la production, il ne reste donc plus qu'à simuler une erreur réseau. Pour cela, il faudrait couper le network entre le conteneur front et un conteneur spécifique des réplicas `api`. Après quelques tests d'outils et de manipulation, nous avons finalement décidé de nous rapprocher encore plus de la production en utilisant comme backend l'api de recette, qui a elle aussi deux IPs de loadbalancer: 

```
Non-authoritative answer:
pix-api-recette.osc-fr1.scalingo.io     canonical name = sc-lb-pool-01.osc-fr1.scalingo-network.com.
Name:   sc-lb-pool-01.osc-fr1.scalingo-network.com
Address: 5.104.101.30
Name:   sc-lb-pool-01.osc-fr1.scalingo-network.com
Address: 109.232.236.90
```

L'utilisation d'IP publiques nous permet d'utiliser simplement l'outil [pumba](https://github.com/alexei-led/pumba) qui offre notamment la possibilité de couper du trafic réseau depuis des conteneurs vers des IP spécifiques, via l'utilisation de la commande `tc`(paquet `iproute2`).

En déployant uniquement le front, qui tape désormais sur l'api de recette, nous pouvons desormais couper l'accès réseau, lancer des requêtes en boucle (avec l'outil [hey](https://github.com/rakyll/hey)), et reproduire une erreur similaire : 

```bash
# lancement des requêtes dans une console 
hey -q 1 -c 2 -z 1m http://localhost:8000 

# lancement de la coupure de connexion
docker exec -ti nginx_front_1 apt update
docker exec -ti nginx_front_1 apt install -y iproute2
docker run -it --rm -v /var/run/docker.sock:/var/run/docker.sock gaiaadm/pumba netem  --target=109.232.236.90  --target=5.104.101.30 -d 32s loss -p 100 nginx_front_1
```

On obtient alors les logs suivants : 

```
2022/02/22 13:46:52 [warn] 24#24: *10 upstream server temporarily disabled while connecting to upstream, client: 172.24.0.1, server: , request: "GET / HTTP/1.1", upstream: "https://109.232.236.90:443/api", host: "localhost:8000"
front_1           | 2022/02/22 13:46:52 [error] 24#24: *10 upstream timed out (110: Connection timed out) while connecting to upstream, client: 172.24.0.1, server: , request: "GET / HTTP/1.1", upstream: "https://109.232.236.90:443/api", host: "localhost:8000"
front_1           | 2022/02/22 13:46:52 [warn] 24#24: *9 upstream server temporarily disabled while connecting to upstream, client: 172.24.0.1, server: , request: "GET / HTTP/1.1", upstream: "https://5.104.101.30:443/api", host: "localhost:8000"
front_1           | 2022/02/22 13:46:52 [error] 24#24: *9 upstream timed out (110: Connection timed out) while connecting to upstream, client: 172.24.0.1, server: , request: "GET / HTTP/1.1", upstream: "https://5.104.101.30:443/api", host: "localhost:8000"
front_1           | 2022/02/22 13:46:52 [error] 24#24: *9 no live upstreams while connecting to upstream, client: 172.24.0.1, server: , request: "GET / HTTP/1.1", upstream: "https://pix-api-recette.osc-fr1.scalingo.io/api", host: "localhost:8000"
front_1           | 172.24.0.1 - - [22/Feb/2022:13:46:52 +0000] "GET / HTTP/1.1" 502 157 "-" "hey/0.0.1" "-"
front_1           | 2022/02/22 13:46:52 [error] 24#24: *9 no live upstreams while connecting to upstream, client: 172.24.0.1, server: , request: "GET / HTTP/1.1", upstream: "https://pix-api-recette.osc-fr1.scalingo.io/api", host: "localhost:8000"
```

On remarque que dès que le réseau est coupé, chaque ip de backend est marquée par Nginx comme `temporarily disabled`, puis que chaque connexion suivante sur ce serveur tombe en `no live upstreams`. On reproduit donc bien un comportement similaire. On remarque au passage les mots clés `upstream`, alors que nous utilisons des directives de proxy uniquement. 

> Selon la [documentation Nginx de `proxy_pass`](https://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_pass), un DNS qui retourne plusieurs adresse est traité comme un upstream :  `If a domain name resolves to several addresses, all of them will be used in a round-robin fashion. In addition, an address can be specified as a server group.`

En explicitant ce comportement via les directives `upstream` de Nginx, nous pourrions alors parametrer les réactions de Nginx en cas d'erreur. 

La configuration ainsi adaptée est la suivante :

```
upstream api {
    server pix-api-recette.osc-fr1.scalingo.io:443;
}
server{
    location / {
        proxy_connect_timeout 15s;
        proxy_pass https://api;
        proxy_redirect default;
    }
}
```

Le passage à un upstream perturbe le fonctionnement du backend, nous atterissons desormais sur une page Scalingo qui nous dit que l'application est introuvable. En analysant les requêtes effectuées via un tcpdump, on constate que le header `Host` envoyé à scalingo est le host spécifié dans le `proxy_pass`, et non celui du `server` d'upstream.

> Selon la [documentation de `proxy_set_header`](https://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_set_header), par défaut deux headers sont modifiés, dont le `Host`. Pour régler le problème d'accès, il suffit donc de réécrire ce header à la bonne valeur :
> `proxy_set_header Host pix-api-recette.osc-fr1.scalingo.io;`

Le comportement avec la directive upstream étant maintenant le même, nous pouvons faire les paramétrages de désactivation des serveurs d'upstream par Nginx. Pour cela, nous pouvons utiliser les deux paramètres suivants : 

- `max_fails` : Nombre de requêtes au backend en erreurs avant que Nginx ne le désactive (log: `upstream server temporarily disabled while connecting to upstream`), par défaut 1 (si passé à 0, plus aucun backend ne sera désactivé)
- `fail_timeout` : Temps de désactivation d'un backend (log: `no live upstreams while connecting to upstream`), par défaut 10s

Nous ne voulons pas désactiver complètement le méchanisme de sonde de backend, au risque de faire patienter trop longtemps nos utilisateurs en cas d'erreurs, mais nous pouvons réduire le nombre de déclenchement en augmentant le paramètre `max_fails`.

Nous voulons réduire l'impact d'une erreur isolée sur les utilisateurs, et donc réduire le temps de désactivation d'un backend, il faut donc définir un temps plus court pour `fail_timeout`

2022-02-23 13:47 UTC, aceol approved these changes
LGTM...

2022-02-23 16:34 UTC, VincentHardouin approved these changes

2022-02-28 09:24 UTC, merged