[ADR] Add an ADR on string validation
1024pix/pix pull request #4103
Opened 2022-02-16 15:37 UTC by frinyvonnick

Suite à la Mise en jambes sur la "Validation des chaînes de caractères", le besoin a été ressenti d'ouvrir un ADR sur le sujet afin d'ouvrir la discussion.  J'ai retranscrit le contenu de la MEJ dans la partie contexte et la solution que nous proposions avec @ajoanny. Je vous laisse proposer des solutions alternatives au problème dans cette pull request.

2022-02-16 15:42 UTC, pix-service commented
I'm deploying this PR to these urls:

- App (.fr): https://app-pr4103.review.pix.fr
- App (.org): https://app-pr4103.review.pix.org
- Orga: https://orga-pr4103.review.pix.fr
- Certif: https://certif-pr4103.review.pix.fr
- Admin: https://admin-pr4103.review.pix.fr
- API: https://api-pr4103.review.pix.fr/api/

 Please check it out!

2022-02-17 11:38 UTC, aceol approved these changes
👍

2022-02-17 16:21 UTC, alexandrecoin approved these changes

2022-02-21 08:13 UTC, VincentHardouin commented on docs/adr/0031-uniformiser-la-validation-des-chaines-de-caracteres.md
> +On s'est rendu compte qu'il n'est pas trivial de vider un champ de base données.
```suggestion
On s'est rendu compte qu'il n'est pas trivial de vider un champ de base de données.
```

2022-02-21 08:13 UTC, VincentHardouin commented on docs/adr/0031-uniformiser-la-validation-des-chaines-de-caracteres.md
> +Il existe actuellement plusieurs manière de le faire côté front :
```suggestion
Il existe actuellement plusieurs manières de le faire côté front :
```

2022-02-21 08:13 UTC, VincentHardouin commented on docs/adr/0031-uniformiser-la-validation-des-chaines-de-caracteres.md
> +Côté API, il existe aussi plusieurs manière de valider les chaînes de caractères reçues :
```suggestion
Côté API, il existe aussi plusieurs manières de valider les chaînes de caractères reçues :
```

2022-02-21 08:13 UTC, VincentHardouin commented on docs/adr/0031-uniformiser-la-validation-des-chaines-de-caracteres.md
> +On constate que dans le deux premiers cas il peut y avoir un doute.
```suggestion
On constate que dans les deux premiers cas il peut y avoir un doute.
```

2022-02-21 08:13 UTC, VincentHardouin commented on docs/adr/0031-uniformiser-la-validation-des-chaines-de-caracteres.md
> +Il est important aussi de préciser que par le passé on a eu des bugs lié à l'utilisation d'adminer. Il est arrivé qu'avec adminer on stocke des chaînes vides au lieu de null ce qui avait une incidenc
```suggestion
Il est important aussi de préciser que par le passé on a eu des bugs lié à l'utilisation d'adminer. Il est arrivé qu'avec adminer on stocke des chaînes vides au lieu de null ce qui avait une incidence sur la manière dont la donnée était interpretée par l'API.
```

2022-02-21 08:13 UTC, VincentHardouin commented on docs/adr/0031-uniformiser-la-validation-des-chaines-de-caracteres.md
> +On pourrait donc une fois par application définir comment sont sérialisé les chaînes de caractères. Cela permet de ne faire la ternaire qu'une seule fois.
```suggestion
On pourrait donc une fois par application définir comment sont sérialisées les chaînes de caractères. Cela permet de ne faire la ternaire qu'une seule fois.
```

2022-02-21 08:22 UTC, octo-topi requested changes
Merci de cette PR :heart: 
J'ai des réserves conséquentes sur la forme pour qu'elle soit utile dans le futur, je les liste ci-dessous. Je pensais que c'était explicite dans le [template](https://github.com/1024pix/pix/blob/dev/docs/adr/0001-enregistrer-les-decisions-concernant-l-architecture.md), mais il semble que non :grinning: Comment pourrait-on le modifier pour que ce le soit ?

Mes réserves:
- objectif flou: "il n'est pas trivial de vider un champ de base données" ne me parle pas du tout (je ne suis pas venu à la MEJ, mais ce sera le cas de beaucoup de futurs dev); en lisant en travers 5 minutes je me rends compte qu'il s'agit du front, or cela n'apparait pas dans le nom du fichier
- avantages/inconvénientsde chaque solution implicites: le but de l'ADR, c'est de l'expliciter, et aussi d'expliciter la décision , ex: la solution A a tel avantage, et c'est le plus important parce que X, donc on prend A. Si X n'est plus d'actualité, alors les futurs dev pourront changer de solution.

Je suis dispo pour vous aider si besoin

2022-02-21 08:32 UTC, frinyvonnick commented
Merci @octo-topi pour ton retour. Le sujet n'est pas front, il est fullstack. C'est pour ça qu'il y a une partie "côté front" et "côté API". Je vais essayer de retravailler le contenu en reprenant le template que tu as mis en lien.

2022-02-21 08:58 UTC, Anne-Gaelle-S approved these changes

2022-02-21 08:58 UTC, Anne-Gaelle-S commented on docs/adr/0031-uniformiser-la-validation-des-chaines-de-caracteres.md
> +4. `Joi.string().allow(null).optional()` - La propriété n'est pas obligatoire mais on accepte null
```suggestion
3. `Joi.string().empty('').allow(null).optional()` - La propriété n'est pas obligatoire, on accepte null et une chaîne vide est considéré comme `undefined`
4. `Joi.string().allow(null).optional()` - La propriété n'est pas obligatoire et on accepte null
```

2022-02-21 08:58 UTC, Anne-Gaelle-S commented on docs/adr/0031-uniformiser-la-validation-des-chaines-de-caracteres.md
> +Il est important aussi de préciser que par le passé on a eu des bugs lié à l'utilisation d'adminer. Il est arrivé qu'avec adminer on stocke des chaînes vides au lieu de null ce qui avait une incidenc
```suggestion
Il est important aussi de préciser que par le passé on a eu des bugs lié à l'utilisation d'Adminer. Il est arrivé qu'avec Adminer on stocke des chaînes vides au lieu de null, ce qui avait une incidence sur la manière dont la donnée était interpretée par l'API.
```

2022-02-21 09:44 UTC, octo-topi commented
> Merci @octo-topi pour ton retour. Le sujet n'est pas front, il est fullstack. C'est pour ça qu'il y a une partie "côté front" et "côté API". Je vais essayer de retravailler le contenu en reprenant le template que tu as mis en lien.

Ce n'est pas forcément un question de format, mais une question de but de l'ADR. Ce n'est pas facile de prendre le recul quand on est le sujet, je peux jouer ce rôle de "mec-qui-comprend-pas" pour aider à rendre les choses explicites si vous voulez.

2022-02-22 07:58 UTC, yannbertrand commented on docs/adr/0031-uniformiser-la-validation-des-chaines-de-caracteres.md
> +Lors de la réalisation de la pull request https://github.com/1024pix/pix/pull/3953.
```suggestion
Lors de la réalisation de [cette pull request](https://github.com/1024pix/pix/pull/3953).
```
(Lien cassé à cause du `.`)

2022-02-22 12:57 UTC, octo-topi commented on docs/adr/0031-uniformiser-la-validation-des-chaines-de-caracteres.md
> +On s'est rendu compte qu'il n'est pas trivial de vider un champ de base de données.
```suggestion
Nous avons besoin de supprimer un texte sur un enregistrement en base de données.
```

2022-02-22 13:01 UTC, octo-topi commented on docs/adr/0031-uniformiser-la-validation-des-chaines-de-caracteres.md
> +# 31. Uniformiser la validation des chaînes de caractères
Il y a deux questions, il me semble:
- comemnt valider la donnée reçue par l'API (routeur ou domaine)
- comment valider la suppression d'un texte

2022-02-22 13:33 UTC, octo-topi commented on docs/adr/0031-uniformiser-la-validation-des-chaines-de-caracteres.md
> +Il est important aussi de préciser que par le passé on a eu des bugs lié à l'utilisation d'adminer. Il est arrivé qu'avec adminer on stocke des chaînes vides au lieu de null ce qui avait une incidenc
```suggestion
Il est important aussi de préciser que par le passé, suite à des mises à jours de données manuelles, il y a des chaînes vides au lieu de `NULL` (SQL),  ce qui avait une incidence sur la manière dont la donnée était interpretée par l'API.
```

2022-02-22 13:34 UTC, octo-topi commented on docs/adr/0031-uniformiser-la-validation-des-chaines-de-caracteres.md
> +2. On veut mettre à jour le champ
```suggestion
1. supprimer la propriété
2. mettre à jour la propriété
```

2022-02-22 13:35 UTC, octo-topi commented on docs/adr/0031-uniformiser-la-validation-des-chaines-de-caracteres.md
> +### Solution : Réduire le nombre de valeurs acceptées par le backend
Cela a sa place dans le paragraphe "Décision", actuellement vide IMHO

2022-02-22 13:37 UTC, octo-topi commented on docs/adr/0031-uniformiser-la-validation-des-chaines-de-caracteres.md
> +4. La propriété est une chaîne de caractère non vide
S'il n'y a pas de mapping entre "On peut déduire" et "Chaque état", je propose une bullet list
```suggestion
On peut déduire de cette validation un certains nombre de cas:
- La propriété n'est pas présente dans le payload
- La propriété vaut chaîne vide
- La propriété vaut null
- La propriété est une chaîne de caractère non vide
```

2022-02-22 13:40 UTC, octo-topi commented on docs/adr/0031-uniformiser-la-validation-des-chaines-de-caracteres.md
> +La deuxième solution se traduit généralement par une ternaire qui vérifie si la chaîne est vide avant de l'envoyer à l'API :
Le `trim()` obscurcit un peu message de "chaîne vide". 

Est-ce qu'on est dans le cas :
- l'utilisateur a supprimé le contenu du champ
- l'utilisateur n'a pas alimenté un champ vide (ex: saisie optionelle)
- l'utilisateur a entré du texte, mais que des espaces

2022-02-23 09:30 UTC, frinyvonnick commented on docs/adr/0031-uniformiser-la-validation-des-chaines-de-caracteres.md
> +Il est important aussi de préciser que par le passé on a eu des bugs lié à l'utilisation d'adminer. Il est arrivé qu'avec adminer on stocke des chaînes vides au lieu de null ce qui avait une incidenc
La phrase a été changée :)

2022-02-23 11:22 UTC, frinyvonnick commented
Suite à une discussion avec @octo-topi hier. J'ai push une nouvelle version de l'ADR en ajoutant des solutions avec avantages et inconvénients. J'ai aussi rempli la partie décision et conséquences avec celle qui semble la plus avantageuse.

2022-02-23 11:45 UTC, octo-topi approved these changes

2022-02-23 11:48 UTC, octo-topi commented on docs/adr/0031-uniformiser-la-validation-des-chaines-de-caracteres.md
> +```
Comme le code cité fait des trucs chelou (s'il est undefined, on met null, sinon on met la valeur sans espaces extérieurs), je propose de ne pas le mentionner.
```suggestion
Dans la deuxième possibilité, c'est au front de vérifier si le texte est vide avant de l'envoyer à l'API 
```

2022-02-23 13:25 UTC, frinyvonnick commented
Est ce que je peux passer le statut à "accepté" ?

2022-02-23 13:26 UTC, frinyvonnick commented on docs/adr/0031-uniformiser-la-validation-des-chaines-de-caracteres.md
> +```
Done ✅

2022-02-23 15:14 UTC, VincentHardouin commented on docs/adr/0031-uniformiser-la-validation-des-chaines-de-caracteres.md
> +- On a une solution adapté à notre cas particulier qui justifie l'usage d'une chaîne vide plutôt que `null`
```suggestion
- On a une solution adaptée à notre cas particulier qui justifie l'usage d'une chaîne vide plutôt que `null` 
```

2022-02-23 15:14 UTC, VincentHardouin commented on docs/adr/0031-uniformiser-la-validation-des-chaines-de-caracteres.md
> +On n'autorise des valeurs multiples côté validation qui peuvent réfleter un ensemble d'intentions diverses (`""`, `" "`, une chaîne différente de `""` ou `" "`, `undefined` ou encore `null`).
```suggestion
On n'autorise des valeurs multiples côté validation qui peuvent réfléter un ensemble d'intentions diverses (`""`, `" "`, une chaîne différente de `""` ou `" "`, `undefined` ou encore `null`).
```

2022-02-23 15:14 UTC, VincentHardouin commented on docs/adr/0031-uniformiser-la-validation-des-chaines-de-caracteres.md
> +- Les intentions ne sont pas clairement définis entre (`""`, `null` ou `undefined`). Elle peuvent varier d'un usage à un autre.
```suggestion
- Les intentions ne sont pas clairement définies entre (`""`, `null` ou `undefined`). Elles peuvent varier d'un usage à un autre.
```

2022-02-23 15:14 UTC, VincentHardouin commented on docs/adr/0031-uniformiser-la-validation-des-chaines-de-caracteres.md
> +On utilise la validation Joi (dans le routeur ou le domaine) suivante pour les propriété de type texte :
```suggestion
On utilise la validation Joi (dans le routeur ou le domaine) suivante pour les propriétés de type texte : 
```

2022-02-23 15:14 UTC, VincentHardouin commented on docs/adr/0031-uniformiser-la-validation-des-chaines-de-caracteres.md
> +On ajoute le transform suivante dans les application Ember pour éviter l'utilisation de ternaire :
```suggestion
On ajoute le transform suivante dans les applications Ember pour éviter l'utilisation de ternaire :
```

2022-02-23 15:14 UTC, VincentHardouin commented on docs/adr/0031-uniformiser-la-validation-des-chaines-de-caracteres.md
> +On va définir la validation des propriété de type texte en fonction de usages pour avoir la solution la plus adaptée possible.
```suggestion
On va définir la validation des propriétés de type texte en fonction des usages pour avoir la solution la plus adaptée possible.
```

2022-02-23 15:14 UTC, VincentHardouin commented on docs/adr/0031-uniformiser-la-validation-des-chaines-de-caracteres.md
> +- Dans la majorité des usages en terme de validation on utilise `null` à l'heure actuelle
```suggestion
- Dans la majorité des usages en termes de validation on utilise `null` à l'heure actuelle
```

2022-02-24 07:39 UTC, VincentHardouin approved these changes

2022-02-24 08:06 UTC, frinyvonnick commented
![image](https://user-images.githubusercontent.com/13099512/155483524-3bda1055-544f-43bd-b350-60201f2ffeba.png)

J'ai passé le statut à accepté au vu du nombre d'approves ici et des réactions sur Slack. Je vais merger dés que la ci passe.

2022-02-24 08:21 UTC, merged