[TECH] Migrer la colonne Answer.id de INTEGER en BIG INTEGER (Partie 1)
1024pix/pix pull request #4108
Opened 2022-02-17 11:26 UTC by yahyayouness

## :unicorn: Problème

L'identifiant de la table Answer est de type Integer. Avec 707264980 enregistrements actuellement, nous risquons de taper la limite des enregistrements possibles.

Ci-dessous le nombre d'insertion de ces deux dernières semaines:

<img width="1234" alt="Capture d’écran 2022-02-17 à 11 00 44" src="https://user-images.githubusercontent.com/10045497/154452260-288221dd-fede-4a6c-adb5-c214f929fedc.png">

Dans la continuité du chantier de migration de nos identifiants techniques de Integer à Bigint. Nous allons changer le type de de l’ID (clé primaire) de la table Answers.

Au vu de la quantité de données, les risques sont :

- nécessiter une (très importante) indispo de la plateforme
- corrompre ou perdre des données
- fracasser toutes les données / la plateforme

## :robot: Solution
Après avoir mener plusieurs tests dans un environnement proche de la production:
-  Application Scalingo [pix-int-to-bigint-test](https://dashboard.scalingo.com/apps/osc-secnum-fr1/pix-int-to-bigint-test/) Plan postgres 64g.
- Test de charge simulé par Artillery [pix-runner-performance-test](https://dashboard.scalingo.com/apps/osc-secnum-fr1/pix-runner-performance-test/)
- Collecte des statistiques avec l'application [pix-db-stats-int-to-bigint-test](https://dashboard.scalingo.com/apps/osc-secnum-fr1/pix-db-stats-int-to-bigint-test/)

L'objectif étant de minimiser l'indisponibilité de la plateforme en essayant de limiter les ressources ( mémoire, workers ...) lors de la création des indexes. Résultat du benchmark regroupé dans ce [fichier](https://docs.google.com/spreadsheets/d/1jhflHP4UOupr-SE53yHJlyp22A44SyEQSK9KMsp0R-E/edit#gid=0): 

<img width="1496" alt="Capture d’écran 2022-02-17 à 11 09 45" src="https://user-images.githubusercontent.com/10045497/154453967-e4d336eb-cb12-41a9-9b48-a487e002fbe8.png">

Nous somme venue à la conclusion que le temps de création d'un index était de 30min. En optimisant le tuning des workers et mémoire, on arrive à gagner 3 minutes mais pas plus à cause d'une autre ressource limitante I/O. Notre fournisseur Scalingo n'offre pas de moyen pour optimiser cette ressource, on se retrouve donc à faire avec cette contrainte.

Le choix s'est porté donc vers une solution avec downtime qui sera joué pendant la nuit et controlée afin de limiter le temps d'indisponibilité.

La démarche décidée avec @octo-topi, @jonathanperret et les captains est la suivante :

Partie 1: Une première migration knex qui migre directement le type de la colonne si l'environnement contient peu de données ( ex locale, recette ). Dans le cas inverse (ex production), opter pour une stratégie progressive avec des tables temporaires Answer et KE avec des identifiants de type Bigint. Ces deux tables temporaires n'auront pas de contraintes afin d'accélérer la copie de donnée. 

Autres parties: En cours de rédaction

## :rainbow: Remarques
Cette PR contient des commits qui permettent de restaurer la base de donnée de cette [PR](https://github.com/1024pix/pix/pull/3813)
Un spécial merci à @octo-topi pour sa pédagogie, sa documentation et pour le suivi du chantier.

## :100: Pour tester

Migration des données si faible volumétrie: ( Localhost ou RA )

1/ Exécuter les migrations (depuis /api/) :

`npm run db:reset`

2/ Vérifier que la colonne a été migrée en se connectant à la base en local.

`psql postgresql://postgres@localhost/pix_test
`
` \d answer` => vérifier que le type de la table answer est de type Bigint.

Migration des données si forte volumétrie ( Localhost )

`MAX_ROW_COUNT_FOR_SYNCHRONOUS_MIGRATION = 3000;
`
Migration des données si forte volumétrie ( pix-int-to-bigint-test )

1/ Supprimer la migration de la table knex_migrations
`delete from "knex_migrations"  where name like '%add-bigintId-to-answers-id-pk-and-ke-answer-id-fk.js' ;`

2/ Lancer un déploiement manuelle de l'application pix-int-to-bigint-test pour lancer la migration

3/ Vérifier la présence des deux tables temporaires answers_bigint et knowledge-elements_bigint ainsi que la table bigint-migration-settings.

2022-02-17 11:31 UTC, pix-service commented
I'm deploying this PR to these urls:

- App (.fr): https://app-pr4108.review.pix.fr
- App (.org): https://app-pr4108.review.pix.org
- Orga: https://orga-pr4108.review.pix.fr
- Certif: https://certif-pr4108.review.pix.fr
- Admin: https://admin-pr4108.review.pix.fr
- API: https://api-pr4108.review.pix.fr/api/

 Please check it out!

2022-02-17 16:02 UTC, jonathanperret commented on api/db/migrations/20220127164959_add-bigintId-to-answers-id-pk-and-ke-answer-id-fk.js
> +    logger.info('Too much rows to use alter column int to bigint, it will take a long time');
```suggestion
    logger.info('Too many rows to use alter column int to bigint, it will take a long time');
```

2022-02-17 16:08 UTC, jonathanperret commented on api/scripts/database/restore-dump/download-and-restore-backup.sh
> +LOG_FOR_HUMANS=true
L'avertissement de variable inutilisée (`SC2034`) me paraît correct ici, pourquoi le désactiver ?

2022-02-21 08:42 UTC, octo-topi submitted a review, later dismissed
Il y a 700 lignes :exploding_head: et il y a deux sujets traités
Je propose deux PR

edit: :heavy_check_mark: c'est fait, merci @yahyayouness

2022-02-21 10:29 UTC, octo-topi commented on api/db/migrations/20220127164959_add-bigintId-to-answers-id-pk-and-ke-answer-id-fk.js
> +  await knex.raw('LOCK TABLE "answers" IN ACCESS EXCLUSIVE MODE');
A priori pas utile. Quel est le scénario qui poserait problème ?

2022-02-21 10:45 UTC, octo-topi commented on api/db/migrations/20220127164959_add-bigintId-to-answers-id-pk-and-ke-answer-id-fk.js
> +  await knex.raw('LOCK TABLE "answers" IN ACCESS EXCLUSIVE MODE');
Tests à faire:
- branche 1 code: en RA, test de charge pendant la migration, vérifier que pas de perte de données
- branche 2 du code: sur app de test avec données de prod, vérifier que pas échec

2022-02-21 10:53 UTC, octo-topi commented on api/scripts/bigint/answer/add-constraints-and-indexes-to-answers-ke-temporary-tables-with-bigint.js
> +const MAX_ROW_COUNT_FOR_SYNCHRONOUS_MIGRATION = 10000000;
Pourquoi ?

2022-02-21 10:54 UTC, octo-topi commented on api/scripts/bigint/answer/add-constraints-and-indexes-to-answers-ke-temporary-tables-with-bigint.js
> +const addConstraintsAndIndexesToAnswersKeBigintTemporaryTables = async () => {
Ajouter un test

2022-02-22 10:33 UTC, yahyayouness commented on api/scripts/database/restore-dump/download-and-restore-backup.sh
> +LOG_FOR_HUMANS=true
Le commit en question a été cherry pick d'une autre PR et a été enlevé. On prend la remarque dans la PR d'origine

2022-02-22 10:34 UTC, yahyayouness commented
> Il y a 700 lignes 🤯 et il y a deux sujets traités Je propose deux PR

Done. J'ai laissé juste le commit de la partie 1. Le reste sera dans des PRs dédiées.

2022-02-22 10:36 UTC, yahyayouness commented on api/scripts/bigint/answer/add-constraints-and-indexes-to-answers-ke-temporary-tables-with-bigint.js
> +const addConstraintsAndIndexesToAnswersKeBigintTemporaryTables = async () => {
Déplacé dans une autre PR.

2022-02-22 10:36 UTC, yahyayouness commented on api/scripts/bigint/answer/add-constraints-and-indexes-to-answers-ke-temporary-tables-with-bigint.js
> +const MAX_ROW_COUNT_FOR_SYNCHRONOUS_MIGRATION = 10000000;
Déplacé dans une autre PR.

2022-02-22 15:56 UTC, yahyayouness commented on api/db/migrations/20220127164959_add-bigintId-to-answers-id-pk-and-ke-answer-id-fk.js
> +  await knex.raw('LOCK TABLE "answers" IN ACCESS EXCLUSIVE MODE');
LOCK enlevé

2022-02-28 11:18 UTC, octo-topi commented on api/db/migrations/20220127164959_add-bigintId-to-answers-id-pk-and-ke-answer-id-fk.js
> +    table.integer('answerId').unsigned();
**suggestion**
Pour cette raison, et pour d'autres, il est temps de créer un test sur ce script de migration 
```
    table.bigInteger('answerId');
```
Pour être honnête, j'ai découvert le bug en écrivant le test :sweat_smile:

2022-02-28 11:20 UTC, octo-topi commented on api/db/migrations/20220127164959_add-bigintId-to-answers-id-pk-and-ke-answer-id-fk.js
> +}
Comme discuté ensemble, je pense que cette opération doit être faite en partie 6.
J'ai poussé un commit qui le fait, si OK pour toi tu peux le fixup.
Cela évitera des contorsions comme la création de `createTableForBigintMigrationSetting(knex);` qui ne sert à rien.

2022-02-28 11:20 UTC, octo-topi commented on api/db/migrations/20220127164959_add-bigintId-to-answers-id-pk-and-ke-answer-id-fk.js
> +    table.integer('answerId').unsigned();
**suggestion**
Pour cette raison, et pour d'autres, il est temps de créer un test sur ce script de migration 
```
    table.bigInteger('answerId');
```
Pour être honnête, j'ai découvert le bug en écrivant le test :sweat_smile:

2022-02-28 11:22 UTC, octo-topi commented on api/tests/acceptance/database/migration/20220127164959_add-bigintId-to-answers-id-pk-and-ke-answer-id-fk_test.js
> +      `SELECT COUNT(1) FROM information_schema.tables t WHERE t.table_type = 'BASE TABLE' AND t.table_name = 'answers_bigint'`
Y'a moyen de faire plus lisible avec cette extension, mais bon c'est une dépendance de plus pour un cas particulier
https://github.com/knex/knex-schema-inspector#readme

2022-02-28 11:24 UTC, octo-topi commented on api/tests/acceptance/database/migration/20220127164959_add-bigintId-to-answers-id-pk-and-ke-answer-id-fk_test.js
> +    await knex.raw('DROP TABLE IF EXISTS "answers_bigint"');
Y'a moyen de faire plus lisible, mais il faut la nouvelle version de knex :cry: 
https://knexjs.org/#Schema-dropTableIfExists

2022-02-28 11:25 UTC, octo-topi commented on api/db/migrations/20220127164959_add-bigintId-to-answers-id-pk-and-ke-answer-id-fk.js
> +const MAX_ROW_COUNT_FOR_SYNCHRONOUS_MIGRATION = 10000000;
```suggestion
const MIN_ROW_COUNT_FOR_MIGRATION_WITH_TEMPORARY_TABLES = 10000000;
```

2022-02-28 11:27 UTC, octo-topi commented on api/db/migrations/20220127164959_add-bigintId-to-answers-id-pk-and-ke-answer-id-fk.js
> +    logger.debug('Setup environment for answers.id migration to BIGINT using temporary tables..');
J'ai changé le niveau de log sinon c'est affiché à chaque exécution en local, sur chaque branche, WDYT ?
`LOG_LEVEL=trace npm run db:reset  `

On peut avoir un max de log en production avec cette modif du package.json
 "postdeploy": "LOG_LEVEL=debug npm run db:migrate",

2022-02-28 11:28 UTC, octo-topi requested changes
Il y a un bug, voir https://github.com/1024pix/pix/pull/4108#discussion_r815797124

2022-02-28 16:33 UTC, yahyayouness commented on api/db/migrations/20220127164959_add-bigintId-to-answers-id-pk-and-ke-answer-id-fk.js
> +    table.integer('answerId').unsigned();
Bien vu 👍 C'est corrigé

2022-02-28 17:36 UTC, yahyayouness commented on api/db/migrations/20220127164959_add-bigintId-to-answers-id-pk-and-ke-answer-id-fk.js
> +}
Done, j'ai fixup le commit

2022-02-28 17:36 UTC, yahyayouness commented
> Il y a un bug, voir [#4108 (comment)](https://github.com/1024pix/pix/pull/4108#discussion_r815797124)

Merci pour tes retours, c'est pris en compte

2022-03-01 08:36 UTC, octo-topi approved these changes, later dismissed

2022-03-02 12:12 UTC, yahyayouness commented on api/db/migrations/20220127164959_add-bigintId-to-answers-id-pk-and-ke-answer-id-fk.js
> +    logger.debug('Setup environment for answers.id migration to BIGINT using temporary tables..');
Bonne idée, j'ai mis le niveau de log debug, comme on a opté pour ce niveau dans les logs.
`LOG_LEVEL=debug npm run db:migrate` en locale à exécuter pour avoir les logs.

2022-03-07 10:24 UTC, VincentHardouin commented on api/package.json
> +    "postdeploy": "LOG_LEVEL=debug npm run db:migrate",
On est sûr de vouloir le laisser ?

2022-03-16 14:38 UTC, octo-topi commented on api/package.json
> +    "postdeploy": "LOG_LEVEL=debug npm run db:migrate",
Ouaip, voir la partie 1

2022-03-16 14:47 UTC, octo-topi commented
Comme vu ensemble, je transforme la migration en script
Il faudra reporter la migration native dans la partie 6
Le sha du commit d'origine est 2596b3070d859aeeef9a33d511be826b26c3681e

2022-03-16 15:11 UTC, octo-topi reviewed
Testé en local et en RA :heavy_check_mark:

2022-03-16 15:12 UTC, octo-topi commented on api/package.json
> +    "postdeploy": "LOG_LEVEL=debug npm run db:migrate",
On n'en a plus besoin après le passage de la migration en script, effectivement

2022-03-16 15:42 UTC, octo-topi approved these changes

2022-03-23 08:59 UTC, yahyayouness commented on api/package.json
> +    "postdeploy": "LOG_LEVEL=debug npm run db:migrate",
Le commit en question a été supprimé

2022-03-28 08:45 UTC, merged