[FEATURE] Mettre à jour le composant pour choisir un propriétaire de campagne (PIX-4410)
1024pix/pix pull request #4121
Opened 2022-02-21 13:58 UTC by Anne-Gaelle-S

## :unicorn: Problème
> _Décrivez ici le besoin ou l'intention couvert par cette Pull Request._

## :robot: Solution
> _Ajoutez à cet endroit, si nécessaire, des détails concernant la solution technique retenue et mise en oeuvre, des difficultés ou problèmes rencontrés._

## :rainbow: Remarques
> _Des infos supplémentaires, trucs et astuces ?_

## :100: Pour tester
> _Les instructions pour reproduire le problème, les profils de test, le parcours spécifique à utiliser, etc._

2022-02-21 14:18 UTC, pix-service commented
I'm deploying this PR to these urls:

- App (.fr): https://app-pr4121.review.pix.fr
- App (.org): https://app-pr4121.review.pix.org
- Orga: https://orga-pr4121.review.pix.fr
- Certif: https://certif-pr4121.review.pix.fr
- Admin: https://admin-pr4121.review.pix.fr
- API: https://api-pr4121.review.pix.fr/api/

 Please check it out!

2022-02-22 09:33 UTC, yschoueri commented
si je ne me trompe pas, je pense qu'il y a du css que tu peux nettoyer ou on forçait la taille a 100% mais mnt ca fait partie du composant

2022-02-22 10:20 UTC, AndreiaPena requested changes
Il y a un problème concernant la modification d'une campagne. 

Scénario : 
- Je suis connecté avec sco.admin@example.net
- J'ai crée une campagne que j'ai attribué à Lance Low, le propriétaire est pris en compte ✅ 
- Je suis sur la page de modif de cette même campagne
- Je choisis Daenerys comme nouveau propriétaire, je sélectionne son nom dans la liste
- Je valide mais le propriétaire est toujours Lance Low ❌

<img width="1329" alt="Capture d’écran 2022-02-22 à 11 18 30" src="https://user-images.githubusercontent.com/58915422/155112178-cb4b1242-3dfa-4565-b074-1b95d0de7651.png">
<img width="556" alt="Capture d’écran 2022-02-22 à 11 18 55" src="https://user-images.githubusercontent.com/58915422/155112092-4e04be04-87dd-455a-bec4-e0de5e3faf46.png">
<img width="1334" alt="Capture d’écran 2022-02-22 à 11 19 04" src="https://user-images.githubusercontent.com/58915422/155112102-6dc097df-65c9-4e23-a86c-f797615a4fa3.png">

2022-02-22 10:31 UTC, AndreiaPena commented
**Question :** J'avais un doute, du coup je suis allé voir comment c'était avant. On avait fait le choix de faire apparaître le nom de l'actuel propriétaire dans la page de modification de campagne, ce qui n'est plus le cas maintenant. 
Pourquoi ce choix ? 

Avant : 
<img width="568" alt="Capture d’écran 2022-02-22 à 11 27 55" src="https://user-images.githubusercontent.com/58915422/155113863-2fa81b42-ee19-48c6-b972-35c706e27b65.png">

D'un point de vue utilisateur, est-ce que c'est plus pertinent de laisser vide étant donné qu'on est sur de la modification ? Ou est-ce que c'est mieux de laisser voir appraître le nom de l'actuel propriétaire pour ne pas les perturber en laissant à penser que le champ est maintenant vide ?

2022-02-22 10:37 UTC, Anne-Gaelle-S commented
C'était un bug, j'ai corrigé tes deux retours :) 
Le nom du propriétaire actuel devrait toujours apparaitre par défaut dans la page de modification

2022-02-22 10:38 UTC, AndreiaPena commented
Rien à voir avec ton ticket, mais la couleur du placeholder du composant n'est pas la bonne. On est passé à coté. A changer sur Pix UI :) 

 <img width="1191" alt="Capture d’écran 2022-02-22 à 11 36 03" src="https://user-images.githubusercontent.com/58915422/155115170-348b7273-15d9-4731-8d36-c7143ec5ee13.png">

2022-02-22 13:24 UTC, AndreiaPena commented
Fonctionnel ok ✅

2022-02-22 13:33 UTC, yschoueri commented on orga/app/styles/pages/authenticated/campaigns/create-form.scss
> -.create-campaign {
❤️

2022-02-22 13:34 UTC, yschoueri commented on orga/app/styles/pages/authenticated/campaigns/create-form.scss
> -    width: 100%;
❤️

2022-02-22 13:36 UTC, yschoueri commented on orga/translations/en.json
> +        "collapse-label": "TODO",
En attendant les bonnes traductions, en voici 😊 
```suggestion
        "search-placeholder": "Search an owner",
        "clear-label": "Clear owner selection",
        "expand-label": "Expand dropdown",
        "collapse-label": "Collapse dropdown",
```

2022-02-22 13:38 UTC, yschoueri commented
> Rien à voir avec ton ticket, mais la couleur du placeholder du composant n'est pas la bonne. On est passé à coté. A changer sur Pix UI :)
> 
> <img alt="Capture d’écran 2022-02-22 à 11 36 03" width="1191" src="https://user-images.githubusercontent.com/58915422/155115170-348b7273-15d9-4731-8d36-c7143ec5ee13.png">

C'est etonnant parce que sur pix ui elle est bonne, donc c'est un truc sur pix orga qui doit l'override

2022-02-22 13:42 UTC, AndreiaPena commented
> C'est etonnant parce que sur pix ui elle est bonne, donc c'est un truc sur pix orga qui doit l'override

Ah ! J'ai pas été vérifier mais ça me rassure, on avait bien regardé tout ça normalement

2022-02-22 14:10 UTC, AndreiaPena commented on orga/tests/acceptance/campaign-creation_test.js
> -    test('it should be possible to change default campaign owner', async function (assert) {
**Question :** Pourquoi est-il supprimé ?

2022-02-22 14:12 UTC, AndreiaPena commented on orga/app/styles/pages/authenticated/campaigns/create-form.scss
> +// enleve la flèche par défaut de la datalist sur chrome
```suggestion
// enlève la flèche par défaut de la datalist sur chrome
```

2022-02-22 14:12 UTC, AndreiaPena approved these changes

2022-02-22 14:15 UTC, Anne-Gaelle-S commented on orga/tests/acceptance/campaign-creation_test.js
> -    test('it should be possible to change default campaign owner', async function (assert) {
ça revient à tester le composant Pix-UI

2022-02-22 14:52 UTC, yschoueri approved these changes

2022-02-22 15:28 UTC, yschoueri commented on orga/translations/en.json
> +        "collapse-label": "Close the drop down list",
c'est un seul mot
```suggestion
        "expand-label": "Open the dropdown list",
        "collapse-label": "Close the dropdown list",
```

2022-02-23 09:13 UTC, merged