[TECH] Migrer la colonne Answer.id de INTEGER en BIG INTEGER (Partie 2)
1024pix/pix pull request #4127
Opened 2022-02-22 15:54 UTC by yahyayouness

## :unicorn: Problème
Voir [3357](Voir https://github.com/1024pix/pix/pull/3357)

## :robot: Solution
Copier les données de la table answer et knowledge-element vers les deux tables intermédiaires answer_bigint, knowledge-element.

## :rainbow: Remarques
Selon les temps de réponses, la copie avec l'instruction "insert into" sera remplacé par un restore de la table via un dump plus rapide. 
En cas de problème lors de l'exécution du script, le rollback effectué par knex assure un retour à la normale car la copie est dans une transaction isolée.
Pas de reprise de donnée prévue pour le moment.

Résultat sur une environnement iso prod: **4h pour la copie de donnée**
```
2022-02-17 22:58:46.982230808 +0100 CET [one-off-9205] {"level":30,"time":1645135126981,"pid":24,"hostname":"pix-int-to-bigint-test-one-off-9205","msg":"Start copy answers and knowledge-elements data"}
2022-02-18 03:05:27.857993973 +0100 CET [one-off-9205] {"level":30,"time":1645149927857,"pid":24,"hostname":"pix-int-to-bigint-test-one-off-9205","msg":"Call to copyAnswerKeDataToTemporaryTables took 14800875.221370697 milliseconds"}
2022-02-18 03:05:27.858004976 +0100 CET [one-off-9205] {"level":30,"time":1645149927857,"pid":24,"hostname":"pix-int-to-bigint-test-one-off-9205","msg":"Finish copy"}
2022-02-18 03:05:27.858006164 +0100 CET [one-off-9205] {"level":30,"time":1645149927857,"pid":24,"hostname":"pix-int-to-bigint-test-one-off-9205","msg":"End script: copy done successfully."}
2022-02-18 03:05:28.382207472 +0100 CET [manager] container [one-off-9205] (620ec508cc40e1029534b56c) has stopped
```

## :100: Pour tester

En local:

1/ Lance le script avec l'instruction:

2/ vérifier que toutes les données des tables answer et KE ont été copiés.

En RA:

1/ Lance le script avec l'instruction:

2/ vérifier que toutes les données ont été copiés.

Env iso production / Application pix-int-to-bigint:

1/ vérifier que toutes les données ont été copiés.

2022-02-22 16:02 UTC, pix-service commented
I'm deploying this PR to these urls:

- App (.fr): https://app-pr4127.review.pix.fr
- App (.org): https://app-pr4127.review.pix.org
- Orga: https://orga-pr4127.review.pix.fr
- Certif: https://certif-pr4127.review.pix.fr
- Admin: https://admin-pr4127.review.pix.fr
- API: https://api-pr4127.review.pix.fr/api/

 Please check it out!

2022-03-01 09:13 UTC, octo-topi commented on api/scripts/bigint/answer/copy-answers-ke-data-to-temporary-tables-with-bigint.js
> +const copyAnswerKeDataToTemporaryTables = async () => {
Je propose d'ajouter un test automatisé

2022-03-01 09:15 UTC, octo-topi commented on api/scripts/bigint/answer/copy-answers-ke-data-to-temporary-tables-with-bigint.js
> +  const trx = await knex.transaction();
Je propose d'expliciter la portée de la transaction la syntaxe fonction de knex
https://knexjs.org/#Transactions
```
try {
  await knex.transaction(async trx => {

    const books = [
      {title: 'Canterbury Tales'},
      {title: 'Moby Dick'},
      {title: 'Hamlet'}
    ];

    const ids = await knex('catalogues')
      .insert({
        name: 'Old Books'
      }, 'id')
      .transacting(trx)

    books.forEach(book => book.catalogue_id = ids[0])
    await knex('books')
      .insert(books)
      .transacting(trx)

    console.log(inserts.length + ' new books saved.')
  })
} catch (error) {
  console.error(error);
}
```

2022-03-01 14:47 UTC, octo-topi commented on api/scripts/bigint/answer/copy-answers-ke-data-to-temporary-tables-with-bigint.js
> +  const trx = await knex.transaction();
Fait dans un commit séparé

2022-03-01 14:49 UTC, octo-topi requested changes
Pourrais-tu vérifier les tests auto que j'ai rajouté ? 
Bon pour moi sinon :rocket:

2022-03-01 14:49 UTC, octo-topi commented on api/scripts/bigint/answer/copy-answers-ke-data-to-temporary-tables-with-bigint.js
> +const copyAnswerKeDataToTemporaryTables = async () => {
Fait dans un commit séparé

2022-03-01 14:49 UTC, octo-topi commented on api/scripts/bigint/answer/copy-answers-ke-data-to-temporary-tables-with-bigint.js
> +  await trx.raw(`INSERT INTO "bigint-migration-settings"("tableName") VALUES ('knowledge-elements')`);
On n'utilise pas cette table jusque l'étape 4, donc autant la déplacer là.
Leur alimentation ici est mystérieuse

Je l'ai fait dans un commit séparé

2022-03-02 08:51 UTC, yahyayouness commented
> Pourrais-tu vérifier les tests auto que j'ai rajouté ? Bon pour moi sinon 🚀

Il y a un test qui fail, je le check. Fixed avec un after each qui purge les JDD crées.

2022-03-02 11:35 UTC, yahyayouness commented on api/scripts/bigint/answer/copy-answers-ke-data-to-temporary-tables-with-bigint.js
> +const copyAnswerKeDataToTemporaryTables = async () => {
Test fixed avec un after each pour purger les données créés

2022-03-02 11:39 UTC, yahyayouness commented on api/scripts/bigint/answer/copy-answers-ke-data-to-temporary-tables-with-bigint.js
> +  const trx = await knex.transaction();
Le commit a été fixup

2022-03-02 11:41 UTC, yahyayouness commented on api/scripts/bigint/answer/copy-answers-ke-data-to-temporary-tables-with-bigint.js
> +  await trx.raw(`INSERT INTO "bigint-migration-settings"("tableName") VALUES ('knowledge-elements')`);
Ca me va, le commit a été fixup

2022-03-02 15:22 UTC, octo-topi approved these changes, later dismissed
Bon pour moi ! Mergeable dès que le test avec des données iso-production est rééexécuté et ne montre pas de régressions.

2022-03-16 15:52 UTC, octo-topi approved these changes
Test Ok en local et en RA

`[15:51][osc-fr1] Scalingo:pix-api-review-pr4127 ~ $ node scripts/bigint/answer/copy-answers-ke-data-to-temporary-tables-with-bigint.js
{"level":50,"time":1647445887917,"pid":59,"hostname":"pix-api-review-pr4127-one-off-3684","msg":"ERROR logs enabled"}
{"level":40,"time":1647445887918,"pid":59,"hostname":"pix-api-review-pr4127-one-off-3684","msg":"WARN logs enabled"}
{"level":30,"time":1647445887918,"pid":59,"hostname":"pix-api-review-pr4127-one-off-3684","msg":"INFO logs enabled"}
{"level":20,"time":1647445887918,"pid":59,"hostname":"pix-api-review-pr4127-one-off-3684","msg":"DEBUG logs enabled"}
{"level":10,"time":1647445887918,"pid":59,"hostname":"pix-api-review-pr4127-one-off-3684","msg":"TRACE logs enabled"}
{"level":20,"time":1647445888029,"pid":59,"hostname":"pix-api-review-pr4127-one-off-3684","msg":"Start script... "}
{"level":20,"time":1647445888029,"pid":59,"hostname":"pix-api-review-pr4127-one-off-3684","msg":"Start copy answers and knowledge-elements data"}
{"level":20,"time":1647445888066,"pid":59,"hostname":"pix-api-review-pr4127-one-off-3684","msg":"Call to copyAnswerKeDataToTemporaryTables took 36.62114700675011 milliseconds"}
{"level":20,"time":1647445888066,"pid":59,"hostname":"pix-api-review-pr4127-one-off-3684","msg":"Finish copy"}
{"level":20,"time":1647445888066,"pid":59,"hostname":"pix-api-review-pr4127-one-off-3684","msg":"End script: copy done successfully."}
`

2022-03-28 14:53 UTC, merged