[FEATURE] Tutos v2 enregistrés vide (PIX-4297)
1024pix/pix pull request #4129
Opened 2022-02-22 16:45 UTC by nlepage

## :unicorn: Problème

Quand on a aucun tuto enregistré, rien ne s'affiche sur l'écran des tutors enregistrés.

## :robot: Solution

Afficher un message pour indiquer à l'utilisateur comment enregistrer des tutos.

## :rainbow: Remarques

N/A

## :100: Pour tester

Visiter l'écran sans avoir enregistré aucun tuto.

2022-02-22 16:49 UTC, pix-service commented
I'm deploying this PR to these urls:

- App (.fr): https://app-pr4129.review.pix.fr
- App (.org): https://app-pr4129.review.pix.org
- Orga: https://orga-pr4129.review.pix.fr
- Certif: https://certif-pr4129.review.pix.fr
- Admin: https://admin-pr4129.review.pix.fr
- API: https://api-pr4129.review.pix.fr/api/

 Please check it out!

2022-02-23 09:01 UTC, alexandrecoin requested changes
Fonctionnel: Tout ne rentre pas en format mobile. (ici `360px` de largeur)
![Capture d’écran 2022-02-23 à 09 59 57](https://user-images.githubusercontent.com/36371437/155288289-e1919dff-c207-453b-89ce-168672f85173.png)

2022-02-23 09:04 UTC, VincentHardouin commented on mon-pix/app/components/tutorials/saved-empty.hbs
> +  <div>
Est-ce que cette div ne devrait pas avoir un padding pour prévenir les tailles d'écran intermédiaire  ? Exemple 1024pix si cela existe.

2022-02-23 09:29 UTC, alexandrecoin commented
J'ai l'impression que le format des cartes a également été modifié �

![Capture d’écran 2022-02-23 à 10 28 08](https://user-images.githubusercontent.com/36371437/155292277-9b1b734e-2624-46fa-b91e-3c5034c3fd42.png)
�

2022-02-23 10:06 UTC, nlepage commented
> J'ai l'impression que le format des cartes a également été modifié thinking

On va regarder ça

2022-02-23 10:16 UTC, nlepage commented
@alexandrecoin ça devrait être bon sur mobile.

2022-02-23 10:16 UTC, nlepage commented on mon-pix/app/components/tutorials/saved-empty.hbs
> +  <div>
Pour éviter que le texte se colle trop au bord de l'écran ?

2022-02-23 10:20 UTC, nlepage commented on mon-pix/app/components/tutorials/saved-empty.hbs
> +  <div>
J'ai mis un padding sur la div parente, comme ça ni le texte ni l'illustration ne se collent au bord de la fenêtre

2022-02-23 10:33 UTC, nlepage commented on mon-pix/app/components/tutorials/saved-empty.hbs
> +  <div>
> > J'ai l'impression que le format des cartes a également été modifié thinking
> 
> On va regarder ça

Ça devrait être bon avec le dernoier push.

2022-02-23 13:36 UTC, VincentHardouin approved these changes

2022-02-23 13:43 UTC, alexandrecoin approved these changes

2022-02-23 14:22 UTC, yannbertrand approved these changes

2022-02-23 16:38 UTC, merged