[TECH] Renommer la table schooling-registrations par organization-learners (PIX-4137).
1024pix/pix pull request #4152
Opened 2022-02-28 17:00 UTC by ajoanny

## :unicorn: Problème
La table schooling-registrations va contenir les données des prescrits sco, sup et pro. Le nom schooling-registrations n'est plus adapté.

## :robot: Solution
Renommer la table organization-learners.

## :rainbow: Remarques
La migration est rapide donc elle faite en une fois.

## :100: Pour tester
Non régression sur : 
- Commencer un campagne.
- Dissociation
- Affichage des informations du prescrit pour les campagnes d'évaluation et de collecte.
- Affichage de l'activité d'un campagne (Évaluation et Collecte).
- Export des résultats (Évaluation et Collecte).

2022-02-28 17:05 UTC, pix-service commented
I'm deploying this PR to these urls:

- App (.fr): https://app-pr4152.review.pix.fr
- App (.org): https://app-pr4152.review.pix.org
- Orga: https://orga-pr4152.review.pix.fr
- Certif: https://certif-pr4152.review.pix.fr
- Admin: https://admin-pr4152.review.pix.fr
- API: https://api-pr4152.review.pix.fr/api/

 Please check it out!

2022-03-01 12:23 UTC, VincentHardouin commented on api/db/migrations/20220228154928_rename-table-schooling-registrations-by-organization-learners.js
> +  await knex.raw(`ALTER TABLE "${OLD_TABLE_NAME}" RENAME TO "${NEW_TABLE_NAME}";`);
Je pense qu'on peut utiliser la méthode knex dédiée
```suggestion
  await knex.schema.renameTable(OLD_TABLE_NAME, NEW_TABLE_NAME);
```

**suggestion** : Renommer aussi les contraintes

2022-03-02 09:16 UTC, xav-car commented on api/db/migrations/20220228154928_rename-table-schooling-registrations-by-organization-learners.js
> +  await knex.raw(`ALTER TABLE "${OLD_TABLE_NAME}" RENAME TO "${NEW_TABLE_NAME}";`);
c'est prévu de les faire dans un second temps afin de réduire le temps pris par la migration.

2022-03-02 11:10 UTC, lisequesnel commented on api/lib/infrastructure/repositories/campaign-assessment-participation-repository.js
> +        .join('organization-learners', 'organization-learners.id', 'campaign-participations.schoolingRegistrationId')
**question** : on renomme pas la colonne `schoolingRegistrationId` ?

2022-03-04 10:56 UTC, lisequesnel commented on api/db/migrations/20220303102116_rename-schooling-registration-id-to-organization-learner-id.js
> +  return knex.schema.table(CAMPAIGN_PARTICIPATIONS, (table) => table.renameColumn(OLD_COLUMN_NAME, NEW_COLUMN_NAME));
**suggestion** : en vrai, on a besoin d'un index sur `organizationLearnerId` dans `campaign-participations`. Ne pourrait-on pas le rajouter ici ?

2022-03-04 10:57 UTC, lisequesnel commented on api/db/migrations/20220303102116_rename-schooling-registration-id-to-organization-learner-id.js
> +    table.renameColumn(OLD_COLUMN_NAME, NEW_COLUMN_NAME);
**suggestion** : c'est pas l'inverse ? `table.renameColumn(NEW_COLUMN_NAME, OLD_COLUMN_NAME);`

2022-03-04 10:57 UTC, lisequesnel commented on api/db/migrations/20220303102116_rename-schooling-registration-id-to-organization-learner-id.js
> +  return knex.schema.table(CAMPAIGN_PARTICIPATIONS, (table) => table.renameColumn(NEW_COLUMN_NAME, OLD_COLUMN_NAME));
idem ici ^^

2022-03-04 11:00 UTC, lisequesnel commented on api/db/database-builder/factory/build-campaign-participation.js
> +    schoolingRegistrationId: schoolingRegistrationId,
**suggestion** : simplifier en `schoolingRegistrationId,`

2022-03-04 11:12 UTC, lisequesnel commented on api/lib/infrastructure/repositories/certification-candidate-repository.js
> +    id: certificationCandidateToSave.id,
**question** : si j'en crois où c'est utilisé, c'est uniquement pour la création, et les ids sont générés en base, du coup je trouve bizarre de l'avoir ici

2022-03-04 11:12 UTC, lisequesnel commented on api/lib/infrastructure/repositories/certification-candidate-repository.js
> +    sessionId: certificationCandidateToSave.sessionId,
**suggestion** : si j'en crois le seul endroit où c'est utilisé, le sessionId est overridé derrière donc inutile de l'inclure ici je dirais

2022-03-04 11:14 UTC, lisequesnel commented on api/scripts/prod/compute-organization-learners.js
> +          { id: campaignParticipation.id, schoolingRegistrationId },
**question** : je suis pas sûre de comprendre pourquoi ici on remet `schoolingRegistrationId`

2022-03-04 11:18 UTC, lisequesnel commented on api/tests/integration/scripts/prod/compute-organization-learners_test.js
> +    const { id: schoolingRegistrationId } = databaseBuilder.factory.buildSchoolingRegistration();
**suggestion** : fixup ces modifications avec le commit qui a fait ces changements, puisqu'au final on revient en arrière

2022-03-04 14:51 UTC, ajoanny commented on api/scripts/prod/compute-organization-learners.js
> +          { id: campaignParticipation.id, schoolingRegistrationId },
En gros on change pas le nom dans le model, parce que sinon on doit changer dans tous les endroits où on utilise CampaignParticipation.
Le nom de la colonne en bdd c'est OrganizationLearnerId, par contre pour le model et les paramètres passé au repo on appelle ça schoolingRegistrationId le temps de faire les modifications partout .

2022-03-10 10:10 UTC, ajoanny commented
En attente du script de correction des prescrits

2022-03-11 13:42 UTC, aceol commented on api/db/database-builder/factory/build-account-recovery-demand.js
> +    schoolingRegistrationId: actualSchoolingRegistrationId,
C'est ok ca?

2022-03-11 13:47 UTC, aceol commented on api/lib/infrastructure/repositories/certification-candidate-repository.js
> +  };
```suggestion
  return {
  _.pick(certificationCandidateToSave, [ 'authorizedToStart', 'billingMode',
    'birthCity',
    'birthCountry',
    'birthINSEECode',
    'birthPostalCode',
    'birthProvinceCode',
    'birthdate',
    'email',
    'externalId',
    'extraTimePercentage',
    'firstName',
    'lastName',
    'prepaymentCode',
    'resultRecipientEmail',
    'organizationLearnerId',
    'sex']
  };
```

2022-03-11 14:01 UTC, aceol approved these changes
Que fait-on de toutes les occurences de `schoolingRegistration` dans le code? Est-ce que c'est pour une prochaine PR ou bien on laisse comme ca pour toute la partie SCO?

2022-03-11 16:51 UTC, aceol requested changes

2022-03-11 16:51 UTC, aceol commented on api/lib/infrastructure/repositories/certification-candidate-repository.js
dans ce fichier on a 

```
async findBySessionIdAndPersonalInfo({ sessionId, firstName, lastName, birthdate }) {
    const results = await CertificationCandidateBookshelf.where({ sessionId, birthdate }).fetchAll();
    const certificationCandidates = bookshelfToDomainConverter.buildDomainObjects(
      CertificationCandidateBookshelf,
      results
    );

```

Bookshelf cherche le schoolingRegistrationId via le domainModel  mais en bdd c'est organizationLearnerId ce qui fait que le champs reste vide. As t'on une solution pour ca?

2022-03-14 09:19 UTC, xav-car commented on api/lib/infrastructure/repositories/certification-candidate-repository.js
🤔 , il me semblait qu'on l'avait modifié partout. (c'est un truc magic bookshelf ?

2022-03-14 09:23 UTC, xav-car commented on api/lib/infrastructure/repositories/certification-candidate-repository.js
on peut virer Bookshelf  👼 ?

2022-03-14 10:59 UTC, lisequesnel commented on api/lib/infrastructure/repositories/certification-candidate-repository.js
> +  };
ça marche pas pour `organizationLearnerId: certificationCandidateToSave.schoolingRegistrationId`

2022-03-14 11:04 UTC, lisequesnel commented
> * C'est **blocked** mais tout de meme pret pour etre review?

C'est blocked pour l'instant parce qu'on veux lancer un script en prod avant de merger cette PR. Mais les reviews sont ouvertes.

> * Que fait-on de toutes les occurences de `schoolingRegistration` dans le code? Est-ce que c'est pour une prochaine PR ou bien on laisse comme ca pour toute la partie SCO?

Cette PR fait juste les changements en base. Pour tout le renommage des méthodes, constantes, variables, etc, ce sera fait dans une autre PR.

2022-03-14 11:20 UTC, lisequesnel commented on api/lib/infrastructure/repositories/certification-candidate-repository.js
Yes c'est auto-magique avec bookshelf.
Solution 1 : virer bookshelf par knex ici et à tout les endroits où on a besoin du mapping
Solution 2 : voir dans `infrastructure/orm-models` pour spécifier le mapping dans la méthode `Bookshelf.model()`, peut-être que ça peut marcher

2022-03-14 16:29 UTC, ajoanny commented on api/lib/infrastructure/repositories/certification-candidate-repository.js
C'est rigolo les tests passent même après avoir renommer la colonne.

2022-03-15 09:55 UTC, xav-car commented on api/lib/infrastructure/repositories/certification-candidate-repository.js
j'ai modifié un test pour qu'il casse avec la demande de schoolingRegistrationId . et on a tenté une petite adaptation pour le model. le temps de virer ça en Knex de votre côté. (perso, je ne me sens pas confiant à l'idée de le changer sans connaître  certaines règles.)

2022-03-17 15:36 UTC, aceol approved these changes

2022-03-18 09:02 UTC, xav-car approved these changes

2022-03-21 10:40 UTC, merged