[FEATURE] Voir un écran intermédiaire avant de débuter une épreuve focus (PIX-4402)
1024pix/pix pull request #4199
Opened 2022-03-15 11:09 UTC by P-Jeremy

## :unicorn: Problème
> _Décrivez ici le besoin ou l'intention couvert par cette Pull Request._

## :robot: Solution
> _Ajoutez à cet endroit, si nécessaire, des détails concernant la solution technique retenue et mise en oeuvre, des difficultés ou problèmes rencontrés._

## :rainbow: Remarques
> _Des infos supplémentaires, trucs et astuces ?_

## :100: Pour tester
> _Les instructions pour reproduire le problème, les profils de test, le parcours spécifique à utiliser, etc._

2022-03-15 11:15 UTC, pix-service commented
I'm deploying this PR to these urls:

- App (.fr): https://app-pr4199.review.pix.fr
- App (.org): https://app-pr4199.review.pix.org
- Orga: https://orga-pr4199.review.pix.fr
- Certif: https://certif-pr4199.review.pix.fr
- Admin: https://admin-pr4199.review.pix.fr
- API: https://api-pr4199.review.pix.fr/api/

 Please check it out!

2022-03-17 16:03 UTC, octo-topi commented
Mob func review OK:
- page d'avertissement affichée (initiale + F5)
- si sortie dev tools / onglet/navigateur: bien affiché
- plusieurs focus d'affilée: plusierus avertissement
- cas passant OK

2022-03-17 16:23 UTC, aceol commented on mon-pix/app/services/focused-certification-challenges-manager.js
> +    this._focusedCertificationsChallenges = JSON.parse(this._localStorage.getItem(LOCAL_STORAGE_KEY)) || A([]);
A vider en demarrant la certif pour eviter les conflits sur differentes certifs (poste partagé en centre de certif)

2022-03-17 16:26 UTC, octo-topi requested changes, later dismissed
Review func KO: vider le local storage en début de certification

2022-03-17 16:29 UTC, aceol commented on mon-pix/tests/unit/services/focused-certification-challenges-manager_test.js
> +    it('should return false when challengeId does not exist', function () {
Ajouter un test pour le has avec un localStorage vide

2022-03-17 16:35 UTC, aceol commented on mon-pix/app/controllers/assessments/challenge.js
> +  _setOnBlurEventToWindow() {
```suggestion
_subscribeOnBlurEvent
```

2022-03-17 16:47 UTC, aceol approved these changes

2022-03-17 16:47 UTC, aceol commented on mon-pix/app/controllers/assessments/challenge.js
> +  _clearOnBlurMethod() {
```suggestion
  _unsubscribeOnBlurEvent() 
```

2022-03-17 16:47 UTC, aceol commented on mon-pix/app/styles/components/_focused-certification-challenge-instructions.scss
> +  padding: 20px;
inutile?

2022-03-17 16:47 UTC, aceol commented on mon-pix/app/styles/components/_certification-banner.scss
> +  filter: blur(30px);
nitpick: mettre dans une variable css mon-pix

2022-03-17 16:47 UTC, aceol commented on mon-pix/app/templates/assessments/challenge.hbs
> +    {{/if}}
```suggestion
    {{#if shouldDisplayTruc}}
        <FocusedCertificationChallengeInstructions
          @hasUserConfirmedWarning={{this.setUserFocusCertificationChallengeConfirmation}}
        />
    {{/if}}
```

2022-03-18 11:01 UTC, MathieuGilet approved these changes

2022-03-18 13:24 UTC, merged