[TECH] Stocker le clientId du parcours Pôle Emploi uniquement dans l'API (PIX-4682).
1024pix/pix pull request #4267
Opened 2022-03-31 14:38 UTC by AndreiaPena

## :unicorn: Problème
Actuellement le paramètre `clientId` que l'on utilise pour communiquer avec Pôle Emploi est stocké coté front et coté API. 
L'appel `api/pole-emploi/token` fait par le front, fournit à l'API le clientId qu'il possède pourtant déjà dans son propre environnement. 
Ce paramètre n'est jamais modifié, c'est systématiquement le même. Il n'y a donc pas de raison qu'il soit à deux endroits à la fois.

## :robot: Solution
Supprimer le clientId de l'environnement front.

## :rainbow: Remarques
Renommage de la méthode `generatePoleEmploiTokens` pour `exchangePoleEmploiCodeForTokens`

## :100: Pour tester
Tester qu'il n'y a pas de régression dans le parcours Pôle Emploi : 
(tester en local) 
- Aller sur Pix App et cliquer sur le bouton Se connecter à Pôle Emploi (préciser le domaine fr pour voir le bouton)
- Entrer l'identifiant et le mot de passe ( seeds disponible ici : https://1024pix.atlassian.net/wiki/spaces/DEV/pages/1961295916/Environnements+P+le+emploi )
- Si première connexion avec cet utilisateur : 
  - valider les cgu et accepter
- Sinon on accède directement à la page d'accueil Pix 
- Se déconnecter

Autre parcours possible : 
- aller sur `/campagnes` 
- Entrer le code campagne PIXEMPLOI
- Entrer les informations de l'utilisateur sur le portail PE
- On accède au début du parcours
- Quitter le parcours, et se déconnecter.

2022-03-31 14:46 UTC, pix-service commented
I'm deploying this PR to these urls:

- App (.fr): https://app-pr4267.review.pix.fr
- App (.org): https://app-pr4267.review.pix.org
- Orga: https://orga-pr4267.review.pix.fr
- Certif: https://certif-pr4267.review.pix.fr
- Admin: https://admin-pr4267.review.pix.fr
- API: https://api-pr4267.review.pix.fr/api/

 Please check it out!

2022-04-07 08:26 UTC, annemarie35 commented on mon-pix/tests/acceptance/login-pe_test.js
> +    route.location = { replace: sinon.stub() };
attention doublon

2022-04-07 09:32 UTC, annemarie35 reviewed
Bon à savoir, j'ai du ajouter la var d'env POLE_EMPLOI_AUTHENTICATION_URL dans le .env de l'api
- Test fonctionnel avec login via page de login ok
- Test fonctionnel avec accès par code campagne ok  en passant par http://localhost.fr:4200/campagnes 
- Test fonctionnel avec accès par code campagne ko avec erreur `redirect_uri_mismatch The redirection URI provided does not match a pre-registered value` si on ne met pas le .fr dans l'url

On a deux url de redirection possible :
- quand on se logge via le code campagne c'est `redirect_uri=http%3A%2F%2Flocalhost%3A4200%2Fconnexion-pole-emploi`
- quand c'est via la page de login, il y a le .fr `redirect_uri%3Dhttp%253A%252F%252Flocalhost.fr%253A4200%252Fconnexion-pole-emploi`

Il faudrait ajouter les deux possibilités via le portail développeur de PE ou peut-être regarder dans le code si ça révèle quelque chose (je ne me suis pas penchée en détail encore sur cette dernière question) ?

Ps 1 : je suis allée voir sur le portail développeur, on a mis `http://localhost.fr:4200/connexion-pole-emploi`

2022-04-07 09:44 UTC, yschoueri approved these changes

2022-04-07 09:44 UTC, yschoueri commented on api/lib/config.js
> +      authUrl: process.env.POLE_EMPLOI_AUTHENTICATION_URL, // TODO
```suggestion
      authUrl: process.env.POLE_EMPLOI_AUTHENTICATION_URL,
```

2022-04-07 09:49 UTC, annemarie35 commented on api/lib/config.js
> +      authUrl: process.env.POLE_EMPLOI_AUTHENTICATION_URL, // TODO
J'ai eu des erreurs car cette variable manquait, je propose de mettre à jour le sample.env avec POLE_EMPLOI_AUTHENTICATION_URL

2022-04-07 10:20 UTC, annemarie35 requested changes
On a deux url de redirection possible :
- quand on se logge via le code campagne c'est `redirect_uri=http%3A%2F%2Flocalhost%3A4200%2Fconnexion-pole-emploi`
- quand c'est via la page de login, il y a le .fr `redirect_uri%3Dhttp%253A%252F%252Flocalhost.fr%253A4200%252Fconnexion-pole-emploi`

Il faudrait ajouter les deux possibilités via le portail développeur de PE ou peut-être regarder dans le code si ça révèle quelque chose (je ne me suis pas penchée en détail encore sur cette dernière question).

Ps 1 : je suis allée voir sur le portail développeur, on a mis `http://localhost.fr:4200/connexion-pole-emploi`
Ps 2 : en passant par http://localhost.fr:4200/campagnes , ça fonctionne

2022-04-08 10:07 UTC, annemarie35 commented
Suite à ma remarque sur le fait qu'on se connecte en .fr ou pas en local, je pense qu'on peut juste ajouter l'url `http://localhost:4200/connexion-pole-emploi` dans le portail dev de pole emploi car l'url de redirection est générée dynamiquement actuellement (on revient de là où on arrive en somme)
```
 get redirectUri() {
    const { protocol, host } = location;
    const path = this.router.urlFor(this.routeName);
    return `${protocol}//${host}${path}`;
  }
 ```

2022-04-11 07:21 UTC, annemarie35 approved these changes

2022-04-11 07:30 UTC, merged

2022-04-11 14:09 UTC, jonathanperret commented on mon-pix/mirage/config.js
> +  this.get('/pole-emploi/auth-url', (schema, request) => {
@AndreiaPena attention cette déclaration est probablement superflue maintenant que cette réponse a été aussi mise dans le test (`login-pe_test.js`).