[TECH] Enlever le "s" de "pole-emplois"
1024pix/pix pull request #4282
Opened 2022-04-04 15:29 UTC by Anne-Gaelle-S

## :unicorn: Problème
Pole Emploi s'écrit sans "s" , or on a écrit à plusieurs reprise "pole-emplois" dans notre code.

## :robot: Solution
Corriger la typo. 

## :rainbow: Remarques
RAS

## :100: Pour tester
Lancer les tests.

2022-04-04 15:33 UTC, VincentHardouin requested changes
Attention, il faut laisser la possibilité d'appeler sur les 2 routes pendant au moins 1 version pour que tout le monde ait le nouveau front. La PR n'est pas mergeable en l'état.

2022-04-04 15:37 UTC, pix-service commented
I'm deploying this PR to these urls:

- App (.fr): https://app-pr4282.review.pix.fr
- App (.org): https://app-pr4282.review.pix.org
- Orga: https://orga-pr4282.review.pix.fr
- Certif: https://certif-pr4282.review.pix.fr
- Admin: https://admin-pr4282.review.pix.fr
- API: https://api-pr4282.review.pix.fr/api/

 Please check it out!

2022-04-05 09:55 UTC, AndreiaPena commented
**Suggestion :** Changer le tag CLEAN pour un des trois proposés dans [CONTRIBUTING](https://github.com/1024pix/pix/blob/dev/docs/CONTRIBUTING.md) :)

<img width="1005" alt="Capture d’écran 2022-04-05 à 11 54 06" src="https://user-images.githubusercontent.com/58915422/161728876-7f108790-d1b2-4e2f-9f2b-f6fecca987cc.png">

2022-04-05 12:11 UTC, VincentHardouin approved these changes

2022-04-05 12:24 UTC, AndreiaPena approved these changes
Scénario de création de compte PE testé ✅

2022-04-05 15:37 UTC, VincentHardouin approved these changes

2022-04-06 04:45 UTC, laura-bergoens commented
> Scénario de création de compte PE testé white_check_mark

Je trouve qu'il est un peu fourre-tout ce TECH là

2022-04-06 04:46 UTC, laura-bergoens approved these changes
Excellente suggestion du stagiaire

2022-04-06 08:36 UTC, merged