[BUGFIX] Ne pas afficher le message d'alerte de sortie de focus lorsque l'user reprend un nouvel assessment (PIX-4787).
1024pix/pix pull request #4330
Opened 2022-04-14 07:25 UTC by VincentHardouin

## :unicorn: Problème
Actuellement, sur Pix App, lorsqu'un utilisateur sort d'une épreuve focus, puis quitte l'épreuve et commence/reprend un autre assessment alors il aura encore le message qui lui indique qu'il est sorti de l'épreuve, alors même que l'épreuve peut ne pas être focus.

## :robot: Solution
Les controllers d'Ember sont des singletons, c'est-à-dire que lorsqu'on accède à plusieurs assessment on utilise en réalité la même instance du controller auquel on passe juste des paramètres différents. 
Cependant, nous ne lui indiquons pas que certains champs doivent être remis à 0. Pour faire cela, il existe la méthode `resetController` qui est déclenchée lorsque la route est quittée ou change (cf : [doc resetController](https://api.emberjs.com/ember/3.28/classes/Route/methods/resetController?anchor=resetController)).  Nous utilisons alors cette méthode pour gérer ce cas. 

## :rainbow: Remarques
> _Des infos supplémentaires, trucs et astuces ?_

## :100: Pour tester
- Se connecter à Pix APP
- Passer une compétence jusqu'à avoir une épreuve focus
- Sortir de la fenêtre de l'épreuve pour perdre le focus
- Quitter l'épreuve à l'aide du bouton en haut à droite
- Reprendre une autre compétence et constater qu'il n'y a pas le message de sortie d'épreuve.

2022-04-14 07:32 UTC, pix-service commented
I'm deploying this PR to these urls:

- App (.fr): https://app-pr4330.review.pix.fr
- App (.org): https://app-pr4330.review.pix.org
- Orga: https://orga-pr4330.review.pix.fr
- Certif: https://certif-pr4330.review.pix.fr
- Admin: https://admin-pr4330.review.pix.fr
- API: https://api-pr4330.review.pix.fr/api/

 Please check it out!

2022-04-14 07:35 UTC, alexandrecoin approved these changes

2022-04-14 14:44 UTC, matthiasferraina approved these changes

2022-04-14 15:54 UTC, alexandrecoin requested changes, later dismissed
Nous avons décelé une régression.
Pour reproduire : 
- Aller sur une épreuve focus
- Changer d'onglet et revenir
- Constater le message de sortie d'épreuve
- Quitter le challenge et revenir sur le même assessment
- Le message de sortie d'épreuve n'est plus visible

2022-04-15 15:15 UTC, yannbertrand approved these changes
LGTM

2022-04-19 07:51 UTC, merged