[TECH] Nettoyage de toutes les variables, constantes, méthodes, routes du terme `schooling-registrations` (PIX-4741).
1024pix/pix pull request #4348
Opened 2022-04-20 08:46 UTC by KaramHaitham

## :unicorn: Problème
> _Décrivez ici le besoin ou l'intention couvert par cette Pull Request._

## :robot: Solution
> _Ajoutez à cet endroit, si nécessaire, des détails concernant la solution technique retenue et mise en oeuvre, des difficultés ou problèmes rencontrés._

## :rainbow: Remarques
> _Des infos supplémentaires, trucs et astuces ?_

## :100: Pour tester
> _Les instructions pour reproduire le problème, les profils de test, le parcours spécifique à utiliser, etc._

2022-04-20 08:51 UTC, pix-service commented
I'm deploying this PR to these urls:

- App (.fr): https://app-pr4348.review.pix.fr
- App (.org): https://app-pr4348.review.pix.org
- Orga: https://orga-pr4348.review.pix.fr
- Certif: https://certif-pr4348.review.pix.fr
- Admin: https://admin-pr4348.review.pix.fr
- API: https://api-pr4348.review.pix.fr/api/

 Please check it out!

2022-05-04 15:59 UTC, lisequesnel commented on api/tests/unit/infrastructure/serializers/jsonapi/user-with-organization-learner-serializer_test.js
>  describe('Unit | Serializer | JSONAPI | UserWithSchoolingRegistration-serializer', function () {
UserWithOrganizationLearnerSerializer

2022-05-04 16:01 UTC, lisequesnel commented on api/lib/application/organizations/index.js
> +      path: '/api/organizations/{id}/organization-learners/import-siecle',
**suggestion** : je suis pas pour changer la route maintenant, car ça va avoir un impact sur les requêtes, il faut tout d'abord déprécier l'usage d'une route avant de la supprimer, sinon on va avoir des requêtes qui terminent en 404 not found

2022-05-04 16:03 UTC, lisequesnel commented on api/tests/acceptance/application/organizations/organization-controller-import-schooling-registrations_test.js
> +describe('Acceptance | Application | organization-controller-import-organization-learners', function () {
**question** : changer le nom du fichier aussi ?

2022-05-04 16:05 UTC, lisequesnel commented on api/lib/application/organizations/index.js
> +      path: '/api/organizations/{id}/organization-learners/import-csv',
**suggestion** : idem ici, c'est mieux de déprécier la route, d'en créer une nouvelle mais de pas supprimer directement celle-ci dans un premier temps.

Une fois que l'ancienne route n'est plus utilisée (on vérifie ça avec datadog) alors on peut la supprimer.

2022-05-04 16:06 UTC, lisequesnel commented on api/lib/application/organizations/index.js
> +        handler: organizationController.importHigherOrganizationLearners,
**question** : on avait pas dit `importSupOrganizationLearners` ?

2022-05-04 16:07 UTC, lisequesnel commented on api/lib/infrastructure/serializers/csv/csv-learner-parser.js
> +class CsvLearnerParser {
**suggestion** : `CsvOrganizationLearnerParser` ?

2022-05-04 16:08 UTC, lisequesnel commented on api/translations/fr.json
> +	"account-recovery-email": {
**question** : pourquoi tout ces changements ? je suis pas sûre que ce soit voulu

2022-05-04 16:15 UTC, lisequesnel commented on api/lib/domain/usecases/import-higher-schooling-registrations.js
> -module.exports = async function importHigherSchoolingRegistration({
**question** : je comprends pas, il y a plusieurs fichiers qui sont supprimés et ne sont pas rajoutés avec le nouveau naming

2022-05-05 15:26 UTC, MaHeRots requested changes, later dismissed

2022-05-05 15:26 UTC, MaHeRots commented on api/tests/integration/domain/usecases/import-higher-organization-learners_test.js
>  const higherSchoolingRegistrationRepository = require('../../../../lib/infrastructure/repositories/higher-schooling-registration-repository');
**suggestion** : `higherOrganizationLearnerRepository` ?
sauf si c'est pour plus tard, je comprendrais 100% 😅

2022-05-05 15:26 UTC, MaHeRots commented on api/tests/unit/domain/models/HigherOrganizationLearnerSet_test.js
> +    context('when set has no lerner', function () {
**suggestion** : `learner` (pour les lignes en dessus et en dessous de ce commentaire)
(merci beaucoup d'avoir pensé à moi en ajoutant une typo 🙏 , ça aide à rester concentrée 😉 )

2022-05-05 15:26 UTC, MaHeRots commented on api/lib/infrastructure/repositories/account-recovery-demand-repository.js
> +    organizationLearnerId: accountRecoveryDemandDTO.organizationLearnerId,
**suggestion** : supprimer cette ligne et retirer le spread au dessus 😄

2022-05-05 15:30 UTC, machestla commented
Aaaah c'est quoi ce retour rouge ! Je ne voulais pas ça ! Pas du tout, désolée !!! 
Comment je change ça ?
Je voulais juste commenter moi !

2022-05-06 08:31 UTC, lisequesnel commented on api/lib/domain/models/HigherOrganizationLearner.js
> +class HigherOrganizationLearner {
**suggestion** : `SupOrganizationLearner`

2022-05-06 08:32 UTC, lisequesnel commented on api/lib/domain/models/HigherOrganizationLearner.js
> +const { checkValidation } = require('../validators/higher-organization-learner-validator');
**question** : du coup ce commit ne devrait-il pas être avec le précédent ?

2022-05-06 08:33 UTC, lisequesnel commented on api/lib/domain/usecases/replace-higher-schooling-registrations.js
>  module.exports = async function replaceHigherSchoolingRegistrations({
**question** : idem pour ce commit. D'ailleurs ils ont le même nom

2022-05-06 08:35 UTC, lisequesnel commented on api/tests/integration/domain/usecases/import-higher-organization-learners_test.js
>  const higherSchoolingRegistrationRepository = require('../../../../lib/infrastructure/repositories/higher-schooling-registration-repository');
oui, je me dis que dans une PR ultérieure c'est ok

2022-05-09 13:14 UTC, ajoanny approved these changes

2022-05-09 13:14 UTC, ajoanny commented on api/lib/infrastructure/repositories/account-recovery-demand-repository.js
> +    organizationLearnerId: accountRecoveryDemandDTO.organizationLearnerId,
```js
 return new AccountRecoveryDemand(accountRecoveryDemandDTO);
```

2022-05-09 13:14 UTC, ajoanny commented on api/lib/application/organizations/index.js
> +        handler: organizationController.importHigherOrganizationLearners,
Le terme sup c'est pas correct en anglais je crois, on a déjà eu le discussion dans un vieux thread slack.
Si c'est pour coller à l'enseignement supérieur en tout cas c'est pas correct.
Higher c'est pas parfait mais ça me parait être plus correct. On peut toujours faire le renommage plus tard je pense

2022-05-09 13:14 UTC, ajoanny commented on api/tests/unit/domain/usecases/import-organization-learners-from-siecle_test.js
> +      const extractedorganizationLearnersInformations = [{ nationalStudentId: 'INE1' }];
**nitpick :** extractedOrganizationLearnersInformations

2022-05-09 13:14 UTC, ajoanny commented on api/tests/acceptance/application/organizations/organization-controller-import-higher-schooling-registration_test.js
>  const { expect, knex, databaseBuilder, generateValidRequestAuthorizationHeader } = require('../../../test-helper');
**suggestion :** le nom du fichier est pas bon

2022-05-09 13:14 UTC, ajoanny commented on api/tests/unit/domain/models/HigherOrganizationLearner_test.js
> +    const buildRegistration = (attributes) => new HigherOrganizationLearner(attributes);
buildLearner

2022-05-09 13:14 UTC, ajoanny commented on api/lib/infrastructure/serializers/csv/higher-organization-learner-parser.js
> +    const LearnerSet = new HigherOrganizationLearnerSet(i18n);
learnerSet

2022-05-10 07:44 UTC, KaramHaitham commented on api/lib/infrastructure/repositories/account-recovery-demand-repository.js
> +    organizationLearnerId: accountRecoveryDemandDTO.organizationLearnerId,
done

2022-05-10 20:41 UTC, KaramHaitham commented on api/lib/application/organizations/index.js
> +      path: '/api/organizations/{id}/organization-learners/import-siecle',
rolled back

2022-05-16 09:37 UTC, yaelle6 commented on api/lib/application/organization-learner-dependent-users/index.js
> +exports.name = 'organization-learner-dependentusers-api';
⚠️ organization-learner-dependent-users

2022-05-16 13:19 UTC, yaelle6 commented on api/lib/domain/usecases/create-user-and-reconcile-to-organization-learner-from-external-user.js
> +      const schoolingRegistration = await organizationLearnerRepository.reconcileUserToOrganizationLearner({
rien de grave mais cette variable n'a pas été renommée

2022-05-16 13:20 UTC, yaelle6 commented on api/lib/domain/usecases/dissociate-user-from-organization-learner.js
> +  const schoolingRegistrationForAdmin = await organizationLearnerRepository.getOrganizationLearnerForAdmin(
renommer cette variable

2022-05-16 13:21 UTC, yaelle6 commented on api/lib/domain/usecases/generate-username.js
> +  const schoolingRegistrations = await organizationLearnerRepository.findByOrganizationIdAndBirthdate({
renommer la variable

2022-05-16 13:22 UTC, yaelle6 commented on api/lib/domain/usecases/generate-username.js
>        'There were no schoolingRegistrations matching with organization and birthdate'
changer le msg d'erreur

2022-05-16 13:22 UTC, yaelle6 commented on api/lib/domain/usecases/generate-username.js
> +    throw new OrganizationLearnerNotFound('There were no schoolingRegistrations matching with names');
changer le msg d'erreur

2022-05-16 13:27 UTC, KaramHaitham commented on api/lib/application/organization-learner-dependent-users/index.js
> +exports.name = 'organization-learner-dependentusers-api';
bien vu !

2022-05-16 13:46 UTC, lisequesnel commented on api/lib/domain/services/user-reconciliation-service.js
> +  const schoolingRegistrations = await organizationLearnerRepository.findByOrganizationIdAndBirthdate({
```suggestion
  const organizationLearners = await organizationLearnerRepository.findByOrganizationIdAndBirthdate({
```

2022-05-16 13:46 UTC, lisequesnel commented on api/lib/domain/services/user-reconciliation-service.js
> +  const schoolingRegistration = await supOrganizationLearnerRepository.findOneByStudentNumberAndBirthdate({
```suggestion
  const organizationLearner = await supOrganizationLearnerRepository.findOneByStudentNumberAndBirthdate({
```

2022-05-16 13:47 UTC, yaelle6 commented on api/tests/unit/domain/models/SupOrganizationLearnerSet_test.js
> +    context('when set has no lerner', function () {
miss a "a"

2022-05-16 13:48 UTC, lisequesnel commented on api/translations/fr.json
> +	"account-recovery-email": {
le fichier de trad FR est mal indenté, à voir mais potentiellement un soucis de config sur l'IDE

2022-05-16 13:50 UTC, lisequesnel commented on api/lib/infrastructure/repositories/organization-learner-repository.js
> +      const alreadyReconciledOrganizationLearner = _.find(schoolingRegistrationsToImport, {
```suggestion
      const alreadyReconciledOrganizationLearner = _.find(organizationLearnersToImport, {
```

2022-05-16 13:50 UTC, lisequesnel commented on api/lib/infrastructure/repositories/organization-learner-repository.js
>          const schoolingRegistration = _.find(schoolingRegistrationsToImport, {
```suggestion
        const organizationLearner = _.find(schoolingRegistrationsToImport, {
```

2022-05-16 13:51 UTC, lisequesnel commented on api/lib/infrastructure/repositories/organization-learner-repository.js
>      const schoolingRegistration = await knex
```suggestion
    const organizationLearner = await knex
```

2022-05-16 13:52 UTC, lisequesnel commented on api/lib/infrastructure/repositories/organization-learner-repository.js
>      return new OrganizationLearnerForAdmin(organizationLearner);
ligne 269 : Schooling registration -> OrganizationLearner. Ya plusieurs messages d'erreurs où le changement n'a pas été fait (dans différents fichiers)

2022-05-16 13:59 UTC, lisequesnel reviewed
en tirant la branche, j'ai trouvé encore plein de référence à schoolingRegistrations : 
<img width="765" alt="image" src="https://user-images.githubusercontent.com/23451175/168609960-bc8231de-c0c6-4bab-b262-caa3d6fbc557.png">

2022-05-16 16:01 UTC, ajoanny commented on api/lib/domain/usecases/find-organization-organization-learners.js
> +module.exports = async function findOrganizationOrganizationLearners({
c'est du code mort je crois

2022-05-16 16:03 UTC, ajoanny reviewed
On a fait les tests fonctionnels pour la partie orga / mon pix (import, reconciliation, dissociation, reset password, ajout d'identifiant, téléchargement de template,  etc)
Il manque les tests lié à la certif !

2022-05-23 08:03 UTC, KaramHaitham commented on api/lib/domain/usecases/find-organization-organization-learners.js
> +module.exports = async function findOrganizationOrganizationLearners({
Merci !

2022-05-23 12:41 UTC, KaramHaitham commented on api/lib/domain/usecases/find-organization-organization-learners.js
> +module.exports = async function findOrganizationOrganizationLearners({
usecase effacé

2022-05-23 13:09 UTC, KaramHaitham commented
> en tirant la branche, j'ai trouvé encore plein de référence à schoolingRegistrations : <img alt="image" width="765" src="https://user-images.githubusercontent.com/23451175/168609960-bc8231de-c0c6-4bab-b262-caa3d6fbc557.png">

Nous avons décidés de renommer le reste dans une PR apart.

2022-05-24 12:41 UTC, yaelle6 commented on api/lib/application/organization-learner-dependent-users/index.js
> +const schoolingRegistrationDependentUserController = require('./organization-learner-dependent-user-controller');
changer le nom de la constante pour l'import

2022-05-24 12:42 UTC, yaelle6 commented on api/lib/application/organization-learner-dependent-users/organization-learner-dependent-user-controller.js
> +const schoolingRegistrationDependentUser = require('../../infrastructure/serializers/jsonapi/organization-learner-dependent-user-serializer');
changer le nom de la constante pour l'import

2022-05-24 12:42 UTC, yaelle6 commented on api/lib/application/organization-learner-user-associations/index.js
> +const schoolingRegistrationUserAssociationController = require('./organization-learner-user-association-controller');
changer le nom de la constante pour l'import

2022-05-24 12:43 UTC, yaelle6 commented on api/lib/application/organization-learner-user-associations/organization-learner-user-association-controller.js
> +const schoolingRegistrationSerializer = require('../../infrastructure/serializers/jsonapi/organization-learner-user-association-serializer');
changer le nom de la constante pour l'import

2022-05-24 12:48 UTC, yaelle6 commented on api/tests/integration/application/organization-learner-dependent-users/index_test.js
> +const schoolingRegistrationDependentUserController = require('../../../../lib/application/organization-learner-dependent-users/organization-learner-dependent-user-controller');
changer le nom de la constante pour l'import

2022-05-24 12:49 UTC, yaelle6 commented on api/tests/integration/application/organization-learner-user-associations/index_test.js
> +const schoolingRegistrationUserAssociationController = require('../../../../lib/application/organization-learner-user-associations/organization-learner-user-association-controller');
changer le nom de la constante pour l'import

2022-05-24 12:51 UTC, yaelle6 commented on api/tests/integration/application/organization-learner-user-associations/index_test.js
>  describe('Integration | Application | Route | schooling-registration-user-associations', function () {
changer le nom dans le titre du test

2022-05-24 13:01 UTC, yaelle6 commented on api/tests/unit/domain/usecases/import-organization-learners-from-siecle_test.js
> +      const extractedorganizationLearnersInformations = [{ nationalStudentId: 'INE1' }];
il manque le O

2022-05-24 13:06 UTC, yaelle6 commented on api/tests/integration/domain/services/organization-learners-xml-service_test.js
> +      const expectedorganizationLearners = [
il manque un O

2022-05-24 13:08 UTC, yaelle6 commented on api/lib/domain/validators/sup-organization-learner-validator.js
> +  checkValidation(scoOrganizationLearner) {
supOrganizationLearner

2022-05-24 13:09 UTC, yaelle6 commented on api/lib/domain/validators/sup-organization-learner-validator.js
> +    const { error } = validationSchema.validate(scoOrganizationLearner, validationConfiguration);
supOrganizationLearner

2022-05-24 13:18 UTC, yaelle6 commented on api/tests/integration/infrastructure/repositories/sup-organization-learner-repository_test.js
>      context('when there is no schooling registrations for the given organizationId and student number', function () {
organization-learner dans le titre du test

2022-05-24 13:18 UTC, yaelle6 commented on api/tests/integration/infrastructure/repositories/sup-organization-learner-repository_test.js
>        context('when there is schooling registrations for the given organizationId and student number', function () {
organization-learner dans le titre du test

2022-05-25 07:47 UTC, laura-bergoens commented
Func review OK côté certif

2022-05-25 07:47 UTC, laura-bergoens approved these changes

2022-05-25 09:57 UTC, yaelle6 approved these changes

2022-05-25 09:58 UTC, KaramHaitham commented
testé fun/tech en MOB.

2022-05-30 09:18 UTC, merged