[FEATURE] Passer les sessions ayant des certifications non terminées scorées automatiquement en publiable lors de la finalisation (PIX-4848)
1024pix/pix pull request #4371
Opened 2022-04-27 09:01 UTC by laura-bergoens

## :unicorn: Problème
Il y a plusieurs semaines a été mis en place une nouvelle fonctionnalité : dans le cas de certifications non terminées, le surveillant indique une raison pour laquelle cela s'est produit lors de la finalisation de la session. Quelle que soit la raison, un scoring automatique est réalisé.
Afin de faire le suivi de la fonctionnalité et de son efficacité, l'équipe Certif nous a demandé de continuer à marquer les sessions ayant des certifications dans le cas décrit comme étant non publiables.
Depuis, la fonctionnalité a bien été validée et son fonctionnement est satisfaisant. L'équipe Certif estime désormais qu'il ne leur est plus nécessaire de faire une vérification manuelle sur ces sessions.

## :robot: Solution
Modifier les règles de publiabilité (😸 ) lors de la finalisation de la session.

## :rainbow: Remarques
Je me bats avec l'anglais pour faire des noms de méthodes potables, mais je suis pas super satisfaite.

## :100: Pour tester
Créer une session, inscrire un candidat, commencer un test de certification. Ne pas le terminer.
Finaliser la session, indiquer une raison d'abandon.
Puis aller sur PixAdmin (avec superadmin@example.net pour rappel) et constater que la session n'apparaît plus dans les sessions à problème mais bien dans les sessions à publier

2022-04-27 09:07 UTC, pix-service commented
I'm deploying this PR to these urls:

- App (.fr): https://app-pr4371.review.pix.fr
- App (.org): https://app-pr4371.review.pix.org
- Orga: https://orga-pr4371.review.pix.fr
- Certif: https://certif-pr4371.review.pix.fr
- Admin: https://admin-pr4371.review.pix.fr
- API: https://api-pr4371.review.pix.fr/api/

 Please check it out!

2022-04-28 12:33 UTC, MathieuGilet reviewed
En faisant le test fonctionnel je me suis rendu que ça ne fonctionnait pas. Je pense que c'est à cause de la condition _hasExaminerSeenAllEndScreens() qui sera faux pour une certification non terminée.

2022-05-03 06:05 UTC, laura-bergoens commented
> En faisant le test fonctionnel je me suis rendu que ça ne fonctionnait pas. Je pense que c'est à cause de la condition _hasExaminerSeenAllEndScreens() qui sera faux pour une certification non terminée.

Ah oui je vois, merci bien vu. J'avais testé avec un environnement superviseur

2022-05-05 12:31 UTC, P-Jeremy commented on api/tests/unit/domain/models/FinalizedSession_test.js
> +      // given / when
'is publishable when has no unfinished certification without abort reason'

2022-05-05 13:40 UTC, P-Jeremy commented
Test fonctionnel KO (sans esppace surveillant)

![image](https://user-images.githubusercontent.com/37305474/166935731-9bbb7054-d782-497b-8e25-0fe60f4947b7.png)

2022-05-11 18:35 UTC, aceol approved these changes

2022-05-11 18:35 UTC, aceol commented on api/lib/domain/models/FinalizedSession.js
> +  return !_.some(juryCertificationSummaries, (summary) => summary.isActionRequired());
Pourquoi?

2022-05-11 18:35 UTC, aceol commented on api/lib/domain/models/FinalizedSession.js
> +    .every((summary) => summary.hasSeenEndTestScreen);
filter & every sont natifs sur les collections une raison de passer par lodash?

2022-05-13 14:23 UTC, octo-topi requested changes
Tes fonctionel KO:
Sans espace surveillant, la session apparaît dans `session à traiter` et pas dans `à publier`
![image](https://user-images.githubusercontent.com/56302715/168304530-2e41bac5-2385-42f3-8701-ed315fdafc13.png)


![image](https://user-images.githubusercontent.com/56302715/168304268-8ff04ed5-163b-493f-bc0b-bab1a7794cef.png)

2022-05-13 14:30 UTC, octo-topi commented on api/lib/domain/read-models/JuryCertificationSummary.js
> +  isUnfinishedWithoutAbortReason() {
**nitpick**
Si tu as du mal à trouver un nom sans double-négation, je suggère de changer d'approche

```suggestion
  abortedForNoReason() {
```

2022-05-13 14:32 UTC, octo-topi commented on api/lib/domain/read-models/JuryCertificationSummary.js
> +    return !this.abortReason && !this.completedAt;
**question**
Les read-model, de ce que j'ai compris, c'est quand il n'y a pas de RG métier et qu'on ne fait que lire.
Ici, `isUnfinishedWithoutAbortReason` et `getCleaCertificationStatus` ne contiennent-elles pas du code métier ?

2022-05-13 14:37 UTC, octo-topi commented on api/tests/integration/infrastructure/repositories/jury-certification-summary-repository_test.js
> +        const expectedJuryCertificationSummary = domainBuilder.buildJuryCertificationSummary({
**nitpick**
Il s'agit ici d'un refacto, je propose de déplacer le commit au début de la PR

2022-05-13 14:40 UTC, octo-topi commented on api/lib/domain/models/FinalizedSession.js
> +  return !_.some(juryCertificationSummaries, (summary) => summary.isUnfinishedWithoutAbortReason());
**nitpick**
```suggestion
function _sessionCanBePublished(juryCertificationSummaries) {
  return !_.some(juryCertificationSummaries, (summary) => summary.isUnfinishedWithoutAbortReason());
```

2022-05-24 15:25 UTC, mariannebost commented on api/lib/domain/read-models/JuryCertificationSummary.js
> +  isUnfinishedWithoutAbortReason() {
Vu en mob, il faut garder le nom isUnfinishedWithoutAbortReason

2022-05-24 15:27 UTC, mariannebost commented on api/lib/domain/models/FinalizedSession.js
> +  return !_.some(juryCertificationSummaries, (summary) => summary.isUnfinishedWithoutAbortReason());
Vu en mob: ce n'est pas l'unique raison qui rend une session publiable

2022-05-27 11:50 UTC, laura-bergoens commented on api/lib/domain/read-models/JuryCertificationSummary.js
> +    return !this.abortReason && !this.completedAt;
Ce n'est pas ma compréhension d'un read-model. Pour moi il s'agit d'un modèle de données dont les attributs ou la logique répond à une query particulière. On l'appelle read-model car ce n'est pas un modèle qu'on va venir modifier et persister. Donc ici, JuryCertificationSummary est un read-model car il constitue une représentation d'une certification pour l'usage admin de jury.
Du coup, je vois pas d'objection à ce qu'il y ait de la logique métier

2022-05-27 11:50 UTC, laura-bergoens commented on api/lib/domain/models/FinalizedSession.js
> +    .every((summary) => summary.hasSeenEndTestScreen);
J'ai rebasculé l'existant sur ce fichier avec le natif JS

2022-05-31 08:49 UTC, closed without merging