[BUGFIX] Corriger le script de rattachement de profils cibles (PIX-4866)
1024pix/pix pull request #4381
Opened 2022-04-29 16:55 UTC by ajoanny

## :unicorn: Problème
Parfois lors de l'utilisation du script certaines organisations ne sont pas rattachées aux profils cibles.

## :robot: Solution
Ne pas passer les ids externes des organisations en UpperCase.

## :rainbow: Remarques
Le code n'est pas correctement testé et n'est pas testable (console log qui traîne un peu partout)

## :100: Pour tester
Lancer le script en utilisant des organisations qui ont des ids externes avec des minuscules.

2022-04-29 17:00 UTC, pix-service commented
I'm deploying this PR to these urls:

- App (.fr): https://app-pr4381.review.pix.fr
- App (.org): https://app-pr4381.review.pix.org
- Orga: https://orga-pr4381.review.pix.fr
- Certif: https://certif-pr4381.review.pix.fr
- Admin: https://admin-pr4381.review.pix.fr
- API: https://api-pr4381.review.pix.fr/api/

 Please check it out!

2022-05-02 09:18 UTC, xav-car commented on api/scripts/prod/add-target-profile-shares-to-organizations.js
> -      const externalId = externalIdLowerCase.toUpperCase();
[questions] 
Il y a t-il eu une raison pour mettre en uppercase ? souci de synchro avec BDD et fichier ? 
Ne serait-il pas mieux de récupérer l'UAI en uppercase constamment ? 
Faire une sauvegarde de l'UAI en uppercase tout le temps ? 

Je ne sais pas si ce sont des questions pertinentes. mais j'ai l'impression que le uppercase a voulu solutionner un problème pour en créer un autre derrière.

2022-05-02 16:01 UTC, ajoanny commented on api/scripts/prod/add-target-profile-shares-to-organizations.js
> -      const externalId = externalIdLowerCase.toUpperCase();
Je me suis posé les mêmes questions et j'ai pas de réponse mais pour le coût stocker en upper case ça réglerait le problème.

2022-05-03 09:26 UTC, AndreiaPena commented on api/scripts/prod/add-target-profile-shares-to-organizations.js
> -      const externalId = externalIdLowerCase.toUpperCase();
L'ajout de cette ligne est historique à la création de ce [script ](https://github.com/1024pix/pix/pull/805/files) qui pour le coup est pas très explicite sur ses choix et intentions 😅

2022-05-03 10:27 UTC, AndreiaPena commented
Tu as cette ligne dans le script : `const organizationsByExternalId = organizeOrganizationsByExternalId(organizations);`
Cette méthode est appelé d'un autre fichier helper et passe les externalIds également en majuscules 🤔

Tu dis très justement que le script n'est pas correctement testé, effectivement on aurait pu trouver dans les tests la raison pour laquelle on passe l'externalId en majuscule.

**Question :** Pourquoi ne pas rajouter ces tests manquants dans cette PR ? :)

2022-05-03 12:55 UTC, AndreiaPena requested changes
Sauf si loupé de ma part, je lance un script avec des uai et une liste de target profile ids.

L'UAI renseigné dans mon CSV à des chiffres et une lettre en **miniscule**. (ex: 1234c)
En base de données, la lettre de cet UAI est en majuscule. (1234C)

**Résultat : le rattachement n'a pas été fait.** 

Le script est assez silencieux sur ce qu'il s'est concrètement passé. En fouillant le code, il ne retourne pas spécialement d'erreur et ce à toutes les étapes du script.
<img width="541" alt="Capture d’écran 2022-05-03 à 14 49 45" src="https://user-images.githubusercontent.com/58915422/166456130-74154e1d-f3c4-4f7d-bc8e-75a8a975391e.png">

Là j'ai l'impression que le rattachement s'est bien passé. Alors que non, il ne s'est pas fait.

Quand il rattache bien, ça donne ça d'ailleurs : 
<img width="441" alt="Capture d’écran 2022-05-03 à 14 52 19" src="https://user-images.githubusercontent.com/58915422/166456280-fd12c903-c08e-4666-934e-605d1c48464c.png">

De mon point de vue, ce script devrait être moins permissif. S'arrêter dès qu'il rencontre le moindre problème pour ne pas qu'on pense que tout s'est bien passé alors que non.

2022-05-03 15:10 UTC, ajoanny commented
> Tu as cette ligne dans le script : `const organizationsByExternalId = organizeOrganizationsByExternalId(organizations);` Cette méthode est appelé d'un autre fichier helper et passe les externalIds également en majuscules thinking
> 
> Tu dis très justement que le script n'est pas correctement testé, effectivement on aurait pu trouver dans les tests la raison pour laquelle on passe l'externalId en majuscule.
> 
> **Question :** Pourquoi ne pas rajouter ces tests manquants dans cette PR ? :)

Bah la PR semblait urgente vendredi donc j'ai faut au plus vite pour débloquer le truc, mais du coup comme c'est pas mergé c'est pas urgent.

2022-05-03 16:13 UTC, ajoanny commented
L'objectif de la PR c'est de faire en sorte que le script marche quand on lui passe des id d'orga correct.
Ex:
Si je lui passe 1234aC et qu'en BDD j'ai une orga 1234aC ça marche.
Si je lui passe 1234aC et qu'en BDD j'ai une orga 1234AC ça marche pas mais ça casse pas.
Pas de changement important dans le comportement : On fait en sorte que le comportement du script soit le comportement attendu/

Les changements que tu proposes sont pertinents par contre c'est plus un bug fix et ça prend plus de temps.
Perso je pense que si c'est script qui est utilisé régulièrement (et si j'ai bien compris c'est le cas) il faut le remplacer par une feature sur pix-admin.
Faut essayer de rendre autonome les pôles métier et jouer ce script régulièrement c'est pas les rendre autonomes.

2022-05-04 08:27 UTC, AndreiaPena commented
> Perso je pense que si c'est script qui est utilisé régulièrement (et si j'ai bien compris c'est le cas) il faut le remplacer par une feature sur pix-admin.
> Faut essayer de rendre autonome les pôles métier et jouer ce script régulièrement c'est pas les rendre autonomes.

Bien d'accord avec ta remarque, on l'a déjà remonté à Emmy d'ailleurs. Le script de création d'orgas en masse et celui-ci sont joué bien trop souvent et devrait devenir une feature Admin. Mais c'est pas la priorité visiblement.

Je comprends ton choix de faire un quick fix parce qu'il y avait "urgence" à corriger le tir.
Un autre ticket serait donc le bienvenue pour renforcer ce script en tests et dans sa gestion des erreurs.

2022-05-04 13:42 UTC, annemarie35 approved these changes

2022-05-04 14:20 UTC, ajoanny commented on api/scripts/prod/add-target-profile-shares-to-organizations.js
> -      const externalId = externalIdLowerCase.toUpperCase();
😆 c'est claire c'est succinct

2022-05-04 15:54 UTC, AndreiaPena approved these changes

2022-05-06 09:01 UTC, lisequesnel commented
J'ai pas l'impression que c'est fonctionnel : la première ligne ne fonctionne pas : <img width="448" alt="image" src="https://user-images.githubusercontent.com/23451175/167101122-d5a47fd5-517f-45a0-b0d4-a9e16c7b3644.png">

2022-05-09 12:59 UTC, ajoanny commented
> J'ai pas l'impression que c'est fonctionnel : la première ligne ne fonctionne pas : <img alt="image" width="448" src="https://user-images.githubusercontent.com/23451175/167101122-d5a47fd5-517f-45a0-b0d4-a9e16c7b3644.png">

C'est le comportementt du. script par défaut mais j'ai fait une modif

2022-05-09 13:16 UTC, lisequesnel commented
> > J'ai pas l'impression que c'est fonctionnel : la première ligne ne fonctionne pas : <img alt="image" width="448" src="https://user-images.githubusercontent.com/23451175/167101122-d5a47fd5-517f-45a0-b0d4-a9e16c7b3644.png">
> 
> C'est le comportementt du. script par défaut mais j'ai fait une modif

ce que je voulais dire, c'est que si ça fonctionne, pour le "1/4" ça écrit aussi "Adding targetProfiles...". J'ai regardé en base, et en effet la 1ere ligne n'a pas été effectuée

2022-05-09 14:53 UTC, ajoanny commented
> > > J'ai pas l'impression que c'est fonctionnel : la première ligne ne fonctionne pas : <img alt="image" width="448" src="https://user-images.githubusercontent.com/23451175/167101122-d5a47fd5-517f-45a0-b0d4-a9e16c7b3644.png">
> > 
> > 
> > C'est le comportementt du. script par défaut mais j'ai fait une modif
> 
> ce que je voulais dire, c'est que si ça fonctionne, pour le "1/4" ça écrit aussi "Adding targetProfiles...". J'ai regardé en base, et en effet la 1ere ligne n'a pas été effectuée

Oui du coup quand ça marche pas j'ai mis un message (ce que conseillait Andréa), parce on sait juste pas ce qui se passe

2022-05-09 16:31 UTC, lisequesnel commented
> > > > J'ai pas l'impression que c'est fonctionnel : la première ligne ne fonctionne pas : <img alt="image" width="448" src="https://user-images.githubusercontent.com/23451175/167101122-d5a47fd5-517f-45a0-b0d4-a9e16c7b3644.png">
> > > 
> > > 
> > > C'est le comportementt du. script par défaut mais j'ai fait une modif
> > 
> > 
> > ce que je voulais dire, c'est que si ça fonctionne, pour le "1/4" ça écrit aussi "Adding targetProfiles...". J'ai regardé en base, et en effet la 1ere ligne n'a pas été effectuée
> 
> Oui du coup quand ça marche pas j'ai mis un message (ce que conseillait Andréa), parce on sait juste pas ce qui se passe

j'ai l'impression qu'on se comprends pas 🤣 . Le script est pas fonctionnel : la ligne 1 devrait marcher et ça marche pas.

2022-05-10 12:20 UTC, ajoanny commented
Je vais re regarder ça

2022-05-10 14:51 UTC, ajoanny commented
Quelqu'un peut refaire les tests fonctionnels ? J'ai laissé une orga qui n'existe pas dans le fichier des profils cibles normalement on devrait à voir un message qui dit ça n'a pas marché pour tel orga.

2022-05-10 14:59 UTC, lisequesnel approved these changes
testé fonctionnellement ✅

2022-05-10 15:29 UTC, merged