[TECH] Supprimer le code en relation avec les tutoriels v1 (PIX-4845).
1024pix/pix pull request #4385
Opened 2022-05-02 15:58 UTC by VincentHardouin

## :unicorn: Problème
Actuellement, ce sont les tutoriels "v2" qui sont en production. Nous avons donc pleins de code associé au tutoriel v1 encore présent dans le code mais celui-ci ne peut plus être joué : il est donc plus accessible.

## :robot: Solution
Nous pouvons supprimer inutilisé. Tout d'abord nous vérifions sur Datadog que la route n'est plus utilisée : 
- La route GET `/users/tutorials`

## :rainbow: Remarques
> _Des infos supplémentaires, trucs et astuces ?_

## :100: Pour tester
> _Les instructions pour reproduire le problème, les profils de test, le parcours spécifique à utiliser, etc._

2022-05-02 16:03 UTC, pix-service commented
I'm deploying this PR to these urls:

- App (.fr): https://app-pr4385.review.pix.fr
- App (.org): https://app-pr4385.review.pix.org
- Orga: https://orga-pr4385.review.pix.fr
- Certif: https://certif-pr4385.review.pix.fr
- Admin: https://admin-pr4385.review.pix.fr
- API: https://api-pr4385.review.pix.fr/api/

 Please check it out!

2022-05-03 09:35 UTC, yannbertrand approved these changes
LGTM

2022-05-03 09:36 UTC, matthiasferraina approved these changes

2022-05-03 09:37 UTC, yannbertrand requested changes
En fait non l'écran mes tutos est cassé

2022-05-03 09:37 UTC, matthiasferraina commented
c'est ce que je viens de voir aussi 😬

2022-05-03 09:38 UTC, matthiasferraina requested changes
il manque le header sur la page des tutos

2022-05-03 13:43 UTC, yannbertrand approved these changes

2022-05-03 15:11 UTC, matthiasferraina approved these changes

2022-05-03 15:42 UTC, alexandrecoin approved these changes

2022-05-03 15:51 UTC, merged