[FEATURE] Préciser le texte de la sous-catégorie de signalement E3 dans la page de finalisation de session (PIX-4907)
1024pix/pix pull request #4404
Opened 2022-05-05 19:58 UTC by laura-bergoens

## :unicorn: Problème
Contexte : Epix de suppression des champs libres lors de la finalisation d'une session de certification.
Cette épix contient des changements visuels et fonctionnels importants, de fait on souhaite présenter à l'utilisateur toutes les modifications en même temps (et simultanément diffuser une doc à jour). 

## :robot: Solution
Introduction du feature toggle suivant : `FT_CERTIFICATION_FREE_FIELDS_DELETION`

Modification du texte du signalement E3 soumis à la toggle  `Le fichier à télécharger ne se télécharge pas ou ne s'ouvre pas.`

## :rainbow: Remarques
> _Des infos supplémentaires, trucs et astuces ?_

## :100: Pour tester

### PixCertif

[Accéder à la finalisation d'une session](https://certif-pr4404.review.pix.fr/sessions/20001/finalisation)
Sous la catégorie E1/E10, ajouter un signalement E3

Avec le toggle ON, avoir le texte : `Le fichier à télécharger ne se télécharge pas ou ne s'ouvre pas.`
Avec le toggle OFF, avoir le texte: `Le fichier à télécharger ne s'ouvre pas.`

Ajoutez ce signalement et finalisez la session.

### PixAdmin
Allez dans la liste des signalements de la certif.

Constater le texte `Le fichier à télécharger ne se télécharge pas ou ne s'ouvre pas. `  : (quel que soit l'état du toggle)

2022-05-05 20:04 UTC, pix-service commented
I'm deploying this PR to these urls:

- App (.fr): https://app-pr4404.review.pix.fr
- App (.org): https://app-pr4404.review.pix.org
- Orga: https://orga-pr4404.review.pix.fr
- Certif: https://certif-pr4404.review.pix.fr
- Admin: https://admin-pr4404.review.pix.fr
- API: https://api-pr4404.review.pix.fr/api/

 Please check it out!

2022-05-09 09:01 UTC, MathieuGilet commented on certif/tests/integration/components/issue-report-modal/in-challenge-certification-issue-report-fields_test.js
> +
Pourquoi ne pas laisser le test avec le toggle on comme avant et juste faire le cas du test du toggle off à part ? Je me dis que ce sera plus simple à refacto quand on enlèvera le feature toggle et que le nouveau message deviendra la norme.

2022-05-09 09:02 UTC, MathieuGilet commented on certif/tests/unit/models/certification-issue-report_test.js
> +    // expectedAssertNumber back to 12 when removing FT isCertificationFreeFieldsDeletionEnabled
Même principe que le commentaire précédent ici.

2022-05-09 09:08 UTC, MathieuGilet commented
![Selection_062](https://user-images.githubusercontent.com/1216570/167377919-386f1bf9-1f5e-46ef-aeed-03ebc359520d.png)
Pas de soucis côté Pix Certif mais l'affichage côté Pix Admin contient encore l'ancien message.

2022-05-12 08:44 UTC, octo-topi commented on api/lib/config.js
> +      isCertificationFreeFieldsDeletionEnabled: isFeatureEnabled(process.env.FT_CERTIFICATION_FREE_FIELDS_DELETION),
**nitpick**
Le rajouter au sample.env ou au moins dan api/lib/infrastructure/validate-environement-variables.js

2022-05-12 09:23 UTC, octo-topi commented
# Func review
KO

## Certif 

### OFF
OK
![image](https://user-images.githubusercontent.com/56302715/168037517-196f14cf-b30f-45fa-96d6-297c0404d2b0.png)

### ON
OK
![image](https://user-images.githubusercontent.com/56302715/168037273-3c59f2f1-f9d9-4400-8733-2ac812efd2fe.png)


## Admin 
KO
![image](https://user-images.githubusercontent.com/56302715/168037920-deef55bd-6131-4e78-a807-e89ec6c2e106.png)

2022-05-12 09:23 UTC, octo-topi requested changes
Test func KO, voir PixAdmin
https://github.com/1024pix/pix/pull/4404#issuecomment-1124738989

2022-05-12 09:36 UTC, octo-topi commented on admin/app/models/certification-issue-report.js
> +  [certificationIssueReportSubcategories.FILE_NOT_OPENING]:
**suggestion**
Rajouter un test

2022-05-12 09:58 UTC, octo-topi approved these changes

2022-05-17 09:52 UTC, octo-topi commented on certif/tests/integration/components/issue-report-modal/in-challenge-certification-issue-report-fields_test.js
> +
Corrigé

2022-05-17 09:55 UTC, Libouk approved these changes

2022-05-17 14:58 UTC, MathieuGilet approved these changes

2022-05-17 15:07 UTC, merged