[FEATURE] Empêcher les membres d'admin ayant le rôle métier d'accéder aux pages certifications (PIW-5062)
1024pix/pix pull request #4512
Opened 2022-06-10 12:22 UTC by Anne-Gaelle-S

## :unicorn: Problème
> _Décrivez ici le besoin ou l'intention couvert par cette Pull Request._

## :robot: Solution
> _Ajoutez à cet endroit, si nécessaire, des détails concernant la solution technique retenue et mise en oeuvre, des difficultés ou problèmes rencontrés._

## :rainbow: Remarques
> _Des infos supplémentaires, trucs et astuces ?_

## :100: Pour tester
> _Les instructions pour reproduire le problème, les profils de test, le parcours spécifique à utiliser, etc._

2022-06-10 12:29 UTC, pix-service commented
I'm deploying this PR to these urls:

- App (.fr): https://app-pr4512.review.pix.fr
- App (.org): https://app-pr4512.review.pix.org
- Orga: https://orga-pr4512.review.pix.fr
- Certif: https://certif-pr4512.review.pix.fr
- Admin: https://admin-pr4512.review.pix.fr
- API: https://api-pr4512.review.pix.fr/api/

 Please check it out!

2022-06-13 08:59 UTC, AndreiaPena requested changes
Je me connecte avec pixmetier@example.net
Je ne vois pas le menu certifications ✅ 
J'entre dans l'url /certifications
J'accède à la page 🚫 
<img width="1700" alt="Capture d’écran 2022-06-13 à 10 55 01" src="https://user-images.githubusercontent.com/58915422/173317908-f0a2453d-cbd9-48a3-975c-0a51b460f32f.png">

Or je ne devrais pas pouvoir y accéder en tant que métier

l'url `/certifications/id` nous redirige bien vers organizations mais pas `/certifications`

2022-06-13 09:21 UTC, yschoueri commented on admin/app/components/menu-bar.hbs
> +    {{#if this.accessControl.hasAccessToCertificationActionsScope}}
Je renommerai la methode a `hasAccessToCertificationScope` puisque ce n'est plus juste les actions

2022-06-13 09:47 UTC, yschoueri commented
> Je me connecte avec [pixmetier@example.net](mailto:pixmetier@example.net) Je ne vois pas le menu certifications ✅ J'entre dans l'url /certifications J'accède à la page 🚫 <img alt="Capture d’écran 2022-06-13 à 10 55 01" width="1700" src="https://user-images.githubusercontent.com/58915422/173317908-f0a2453d-cbd9-48a3-975c-0a51b460f32f.png">
> 
> Or je ne devrais pas pouvoir y accéder en tant que métier
> 
> l'url `/certifications/id` nous redirige bien vers organizations mais pas `/certifications`

je m'en occupe

2022-06-14 09:05 UTC, igorissen approved these changes

2022-06-14 09:36 UTC, AndreiaPena approved these changes

2022-06-14 09:39 UTC, AndreiaPena commented
Testé func ✅ 

- Le rôle METIER n'a plus accès à la page certifications et aux pages enfants.
- BUG : Le rôle CERTIF peut modifier le "niveau volet jury", comme les rôles SUPPORT et SUPER ADMIN

2022-06-14 11:06 UTC, merged