[FEATURE] Afficher plus d'informations sur les utilisateurs dans Pix Admin (PIX-1389)
1024pix/pix pull request #4515
Opened 2022-06-10 16:40 UTC by Anne-Gaelle-S

## :unicorn: Problème
> _Décrivez ici le besoin ou l'intention couvert par cette Pull Request._

## :robot: Solution
> _Ajoutez à cet endroit, si nécessaire, des détails concernant la solution technique retenue et mise en oeuvre, des difficultés ou problèmes rencontrés._

## :rainbow: Remarques
> _Des infos supplémentaires, trucs et astuces ?_

## :100: Pour tester
> _Les instructions pour reproduire le problème, les profils de test, le parcours spécifique à utiliser, etc._

2022-06-10 16:46 UTC, pix-service commented
I'm deploying this PR to these urls:

- App (.fr): https://app-pr4515.review.pix.fr
- App (.org): https://app-pr4515.review.pix.org
- Orga: https://orga-pr4515.review.pix.fr
- Certif: https://certif-pr4515.review.pix.fr
- Admin: https://admin-pr4515.review.pix.fr
- API: https://api-pr4515.review.pix.fr/api/

 Please check it out!

2022-06-13 08:40 UTC, ebarbier requested changes
Juste afficher les dates sur les 6 nouveaux champs.
Cacher l'heure pour l'instant. On verra ça dans un 2ème temps.

2022-06-13 13:56 UTC, yschoueri approved these changes

2022-06-13 13:56 UTC, yschoueri commented on admin/app/components/users/user-detail-personal-information/user-overview.hbs
> +            <span>{{@user.langage}}</span>
```suggestion
            <span>{{@user.language}}</span>
```

2022-06-13 13:56 UTC, yschoueri commented on admin/app/models/user.js
> +  get langage() {
```suggestion
  get language() {
```

2022-06-13 14:06 UTC, yschoueri commented on admin/app/components/users/user-detail-personal-information/authentication-method.hbs
> +    <dd>{{dayjs-format @user.lastLoggedAt "DD/MM/YYYY"}}</dd>
A discuter mais peut etre mieux de rester sur une lib pour formatter les dates et le faire dans le controller

2022-06-13 14:21 UTC, yschoueri approved these changes

2022-06-13 14:23 UTC, iwazaru approved these changes

2022-06-13 14:29 UTC, iwazaru commented on admin/app/components/users/user-detail-personal-information/authentication-method.hbs
> +    <dd>{{dayjs-format @user.lastLoggedAt "DD/MM/YYYY"}}</dd>
En fait en y réfléchissant, je me dis que c’est deux sujets différents.

Là l’idée c’est de remplacer moment par dayjs, donc on ajoute pas de librairie mais on en remplace deux obsolètes par deux autres. On va juste brièvement avoir les quatre, mais à mon avis on peut se débarrasser facilement des deux anciennes en un aprèm tech vu que l’API est la même.

Dans un second temps on peut remplacer tous les formatages dans le template par des méthodes de controller et se débarasser de ember-dayjs si on pense que c’est une bonne idée, mais là c’est à mon avis un refactor plus important, donc ce serait dommage de retarder le remplacement de moment.

2022-06-13 14:44 UTC, ebarbier reviewed
Si le champ "adresse e-mail confirmée le" est vide, alors je vois "invalid date". On peut laisser vide please?
![image](https://user-images.githubusercontent.com/6672938/173380083-bf514b30-2459-47a9-86ad-f77a9c357213.png)

2022-06-14 14:19 UTC, ebarbier approved these changes

2022-06-14 15:01 UTC, yschoueri commented on admin/app/components/users/user-detail-personal-information/authentication-method.hbs
> +  {{#if @user.emailConfirmedAt }}
```suggestion
  {{#if @user.emailConfirmedAt}}
```

2022-06-14 16:26 UTC, merged