[FEATURE] Ne pas mentionner la valeur professionnalisante de la certification Pix par France Compétences dans les attestations téléchargées depuis le domaine .org (PIX-5162).
1024pix/pix pull request #4545
Opened 2022-06-20 13:25 UTC by MathieuGilet

## :unicorn: Problème
Actuellement, la phrase "Le certificat Pix est reconnu comme professionnalisant par France compétences à compter d’un score minimal de 120 pix” apparaît sur les attestations téléchargées depuis le domaine .org. Cependant, cette mention ne doit concerner que les attestations téléchargées depuis le domain .fr.

## :robot: Solution
- Ne pas afficher la phrase dans les attestations téléchargées depuis le domaine .org

## :100: Pour tester
- Se connecter à Pix Certif avec le compte `certifsco@example.net`.
- Créer une session et y ajouter un élève.
- Passer la certification, finaliser et publier la session.
- Aller sur Pix App en .fr et vérifier que l'attestation comporte bien la phrase.
- Aller sur Pix App en .org et vérifier que l'attestation ne comporte pas la phrase.
- Aller sur Pix Orga en .fr et vérifier que les attestations de la classe comporte bien la phrase.
- Aller sur Pix App en .org et vérifier que les attestations de la classe ne comporte pas la phrase.

2022-06-20 13:31 UTC, pix-service commented
I'm deploying this PR to these urls:

- App (.fr): https://app-pr4545.review.pix.fr
- App (.org): https://app-pr4545.review.pix.org
- Orga: https://orga-pr4545.review.pix.fr
- Certif: https://certif-pr4545.review.pix.fr
- Admin: https://admin-pr4545.review.pix.fr
- API: https://api-pr4545.review.pix.fr/api/

 Please check it out!

2022-06-20 13:38 UTC, alexandrecoin commented on mon-pix/tests/integration/components/user-certifications-detail-header_test.js
> +    it('should call file saver with isFrenchDomainExtension to true in url', async function () {
```suggestion
    it('should call file saver with isFrenchDomainExtension set to true in url', async function () {
```

2022-06-20 13:39 UTC, P-Jeremy commented on mon-pix/app/components/user-certifications-detail-header.js
> +    const url = `/api/attestation/${certifId}?isFrenchDomainExtension=${this.url.isFrenchDomainExtension}`;
```suggestion
    const url = `/api/attestation/${certifId}?shouldDisplayProfessionalizingWarning=${this.args.shouldDisplayProfessionalizingWarning}`;
```

Il y'a un getter dans le modèle de certification qui retourne true ou false selon le domaine de l'url et la date. ça serait peut être interessant de s'en servir ici

2022-06-20 13:40 UTC, alexandrecoin commented on mon-pix/tests/integration/components/user-certifications-detail-header_test.js
> +    it('should call file saver with isFrenchDomainExtension to false in url', async function () {
```suggestion
    it('should call file saver with isFrenchDomainExtension set to false in url', async function () {
```

2022-06-20 13:40 UTC, P-Jeremy commented on mon-pix/app/components/user-certifications-detail-header.js
> +  @service url;
Du coup peut être pas necessaire ici, voir commentaire ci plus bas

2022-06-20 13:41 UTC, P-Jeremy approved these changes

2022-06-21 06:51 UTC, octo-topi commented on api/lib/application/organizations/index.js
> +            isFrenchDomainExtension: Joi.boolean(),
`nitpick`
Stricto sensu, dans l'URL, `fr` est contenu dans le `hostname`, lui-même composé de domaines dont `fr` est le niveau le plus haut  (`topLevelDomain`)
https://en.wikipedia.org/wiki/Uniform_Resource_Identifier
https://en.wikipedia.org/wiki/Country_code_top-level_domain

Ce que tu nommes extension fait partie du domaine, donc `domainExtension` est ambigu.
Comme le le terme 'domaine de plus haut niveau (TLD)` est technique, je propose de l'utiliser.

Je suggère donc
```suggestion
            isTopLevelDomainFrench: Joi.boolean(),
```

2022-06-21 06:57 UTC, octo-topi commented on api/lib/application/organizations/index.js
> +            isFrenchDomainExtension: Joi.boolean(),
Si possible, toujours renseigner la valeur envoyée par le front 
"Better explicit than implicit"
```suggestion
            isFrenchDomainExtension: Joi.boolean().required(),
```

2022-06-21 07:02 UTC, octo-topi commented on mon-pix/app/components/user-certifications-detail-header.js
> +    const url = `/api/attestation/${certifId}?isFrenchDomainExtension=${this.url.isFrenchDomainExtension}`;
Pourquoi est-ce le front qui doit se signaler comme étant de tel ou tel domaine ?
Est-ce qu'inspecter le `Referer` reçu par l'API serait envisageable et plus fiable ?
```suggestion
```

2022-06-21 07:09 UTC, octo-topi requested changes
Ok sur le principe, mais clarifier la raison du choix de la détermination du TLD dans le front et pas dans l'API, par exemple dans la description de PR, section "Solution"
https://github.com/1024pix/pix/pull/4545/files#r902231119

2022-06-21 07:10 UTC, octo-topi commented on api/lib/infrastructure/utils/pdf/AttestationViewModel.js
> +    if (!this._isFrenchDomainExtension) return false;
**nitpick**
je suggère d'ordonner du plus général au plus spécifique, mais c'est question de goût
```suggestion
    if (!this._isFrenchDomainExtension) return false;
    if (!this._deliveredAt) return false;
```

2022-06-21 07:12 UTC, octo-topi commented on api/lib/infrastructure/utils/pdf/certification-attestation-pdf.js
> +  isFrenchDomainExtension = false,
``nitpick``
> Better explicit than implicit
```suggestion
  isFrenchDomainExtension,
```

2022-06-21 07:12 UTC, octo-topi commented on api/tests/unit/application/certifications/certification-controller_test.js
> -
:pray:

2022-06-21 07:13 UTC, octo-topi commented on api/tests/unit/application/certifications/certification-controller_test.js
>      it('should return binary attestation', async function () {
```suggestion
    it('should return attestation in PDF binary format', async function () {
```

2022-06-21 07:14 UTC, octo-topi commented on api/tests/unit/application/certifications/certification-controller_test.js
> -      });
:pray:

2022-06-21 08:08 UTC, aceol commented on mon-pix/app/components/user-certifications-detail-header.js
> +    const url = `/api/attestation/${certifId}?isFrenchDomainExtension=${this.url.isFrenchDomainExtension}`;
Ce n'est pas au front de prendre cette decision

2022-06-21 08:23 UTC, MathieuGilet commented on mon-pix/tests/integration/components/user-certifications-detail-header_test.js
> +    it('should call file saver with isFrenchDomainExtension to true in url', async function () {
Done

2022-06-21 08:24 UTC, MathieuGilet commented on mon-pix/tests/integration/components/user-certifications-detail-header_test.js
> +    it('should call file saver with isFrenchDomainExtension to false in url', async function () {
Done

2022-06-21 08:37 UTC, MathieuGilet commented on api/lib/application/organizations/index.js
> +            isFrenchDomainExtension: Joi.boolean(),
En faisant un test en local (localhost.fr:4200), le hostname ne contient que localhost et pas localhost.fr donc on ne pourrait pas tester la présence de la phrase france compétences en local.

2022-06-21 08:46 UTC, octo-topi commented on api/lib/application/organizations/index.js
> +            isFrenchDomainExtension: Joi.boolean(),
Voir https://github.com/1024pix/pix/pull/4545#discussion_r902231119, il est possible de passer un `hostname` custom dans les tests

2022-06-21 08:51 UTC, MathieuGilet commented on api/lib/application/organizations/index.js
> +            isFrenchDomainExtension: Joi.boolean(),
Done

2022-06-21 09:01 UTC, MathieuGilet commented on api/lib/infrastructure/utils/pdf/certification-attestation-pdf.js
> +  isFrenchDomainExtension = false,
Done

2022-06-21 09:12 UTC, octo-topi commented on mon-pix/app/components/user-certifications-detail-header.js
> +    const url = `/api/attestation/${certifId}?isFrenchDomainExtension=${this.url.isFrenchDomainExtension}`;
Alors, ce n'est pas testable manuellement en local malgré la conf nginx :cry: 
Je retire donc ma proposition

2022-06-21 09:13 UTC, octo-topi approved these changes
Remarque bloquant résolue, voir https://github.com/1024pix/pix/pull/4545#discussion_r902367519

2022-06-21 09:21 UTC, MathieuGilet commented on api/tests/unit/application/certifications/certification-controller_test.js
>      it('should return binary attestation', async function () {
DOne

2022-06-21 09:22 UTC, MathieuGilet commented on api/lib/infrastructure/utils/pdf/AttestationViewModel.js
> +    if (!this._isFrenchDomainExtension) return false;
Done

2022-06-21 12:31 UTC, merged