[TECH] Le script des seeds ne peut pas être lancé dans une console PG sur scalingo (PIX-5216).
1024pix/pix pull request #4568
Opened 2022-06-23 15:49 UTC by ajoanny

## :unicorn: Problème
Le script des seeds utilise trop de connection à la BDD et ne marche pas dans une console scalingo.

## :robot: Solution
Limiter le nombre de connexion pour le calcul des résultats de campagne.

## :rainbow: Remarques
> _Des infos supplémentaires, trucs et astuces ?_

## :100: Pour tester
Dans une console PG lancer
npm run db:empty
npm run db:seed

2022-06-23 15:57 UTC, pix-service commented
I'm deploying this PR to these urls:

- App (.fr): https://app-pr4568.review.pix.fr
- App (.org): https://app-pr4568.review.pix.org
- Orga: https://orga-pr4568.review.pix.fr
- Certif: https://certif-pr4568.review.pix.fr
- Admin: https://admin-pr4568.review.pix.fr
- API: https://api-pr4568.review.pix.fr/api/

 Please check it out!

2022-06-24 07:38 UTC, octo-topi requested changes
Sauf erreur de ma part, knex alloue un pool de connexion en fonction de la variable d'environnement `DATABASE_CONNECTION_POOL_MAX_SIZE` qui est :
- par défaut à 8 sur la RA;
- par défaut à 4 en local `api/db/knexfile.js`.

Si ton analyse est correcte (`computeParticipationsResults` est en cause), il ne peut pas utilier plus de 4 connexions car il passe par knex et on devrait reproduire en local, ce qui n'est pas le cas.

```js
 "db:seed": "knex --knexfile db/knexfile.js seed:run",
```

Je pense que la cause n'est pas celle-là. :thinking: 
As-tu pu reproduire en RA ?

2022-06-24 07:44 UTC, laura-bergoens commented
@octo-topi "peut-être" qu'en local ca va plus vite donc les connexions sont libérées très rapidement ? Je fais un peu l'avocat du diable là

2022-06-24 07:49 UTC, ajoanny commented
> Si ton analyse est correcte (`computeParticipationsResults` est en cause), il ne peut pas utilier plus de 4 connexions car il passe par knex et on devrait reproduire en local, ce qui n'est pas le cas.

Ouais reproduit en RA !

2022-06-24 08:03 UTC, ajoanny commented
La variable DATABASE_CONNECTION_POOL_MAX_SIZE à pas de valeur par défaut dans le sample.env du coup la valeur utilisé c'est 10 c'est pour ça que ça passe.
J'ai utilisé la variable d'env

2022-06-24 08:10 UTC, octo-topi commented
> La variable DATABASE_CONNECTION_POOL_MAX_SIZE à pas de valeur par défaut dans le sample.env du coup la valeur utilisé c'est 10 c'est pour ça que ça passe. J'ai utilisé la variable d'env


Je n'en démord pas : 

>Sauf erreur de ma part, knex alloue un pool de connexion en fonction de la variable d'environnement DATABASE_CONNECTION_POOL_MAX_SIZE qui est :
>-    par défaut à 8 sur la RA;
>-    par défaut à 4 en local api/db/knexfile.js.

La variable d'environnement en RA est prise dans le template d'application [`pix-api-review`](https://dashboard.scalingo.com/apps/osc-fr1/pix-api-review/environment)
Où elle vaut 8
> DATABASE_CONNECTION_POOL_MAX_SIZE=8

La valeur de 4 est par défaut utilisée sur Scalingo si pas de var d'env
Je mets le bout de code-qui-va-bien `api/db/knexfile.js`
```js
max: parseInt(process.env.DATABASE_CONNECTION_POOL_MAX_SIZE, 10) || 4,
```

2022-06-24 13:58 UTC, ajoanny commented
Ah oui je me suis planté :
> max: parseInt(process.env.DATABASE_CONNECTION_POOL_MAX_SIZE, 10) || 4,
10 => c'est la base 10

Je sais pas en tout cas en local ça marche et pas sur la RA 🤷🏽‍♂️
je vais creuser un peu plus

2022-06-24 14:23 UTC, ajoanny commented
Hum, intéressant en mettant une seule connexion dans en local ça passe.
Et je reproduit plus en RA.
La diff c'est qu'hier j'avais pgboss. je vais mettre une seul connexion en RA pour voir

2022-06-24 14:41 UTC, ajoanny commented
Bon après en local avec pgboss qui tourne ça passe 🤷🏽‍♂️

2022-06-24 15:07 UTC, closed without merging