[FEATURE] Ajout de la notion de resolution automatique sur les certification issue reports (PIX-5258)
1024pix/pix pull request #4650
Opened 2022-07-12 16:02 UTC by P-Jeremy

## :unicorn: Problème
> _Décrivez ici le besoin ou l'intention couvert par cette Pull Request._

## :robot: Solution
> _Ajoutez à cet endroit, si nécessaire, des détails concernant la solution technique retenue et mise en oeuvre, des difficultés ou problèmes rencontrés._

## :rainbow: Remarques
> _Des infos supplémentaires, trucs et astuces ?_

## :100: Pour tester
> _Les instructions pour reproduire le problème, les profils de test, le parcours spécifique à utiliser, etc._

2022-07-12 16:07 UTC, pix-service commented
I'm deploying this PR to these urls:

- App (.fr): https://app-pr4650.review.pix.fr
- App (.org): https://app-pr4650.review.pix.org
- Orga: https://orga-pr4650.review.pix.fr
- Certif: https://certif-pr4650.review.pix.fr
- Admin: https://admin-pr4650.review.pix.fr
- API: https://api-pr4650.review.pix.fr/api/

 Please check it out!

2022-07-13 08:12 UTC, aceol commented
Test func ✅
<img width="1251" alt="image" src="https://user-images.githubusercontent.com/3769147/178684465-abfc322f-3dc8-40ab-b30b-e2b8b6b87deb.png">

2022-07-13 09:06 UTC, octo-topi commented on api/lib/infrastructure/repositories/certification-issue-report-repository.js
> +      .merge()
**bloquant question**
Si je supprimer ces deux lignes, les tests d'intégration du repo passent toujours..

2022-07-13 09:10 UTC, octo-topi commented on api/db/migrations/20220712125907_add-hasBeenAutomaticallyResolved-column-to-certification-issue-reports.js
> +    .orWhere('resolution', 'LIKE', autoResolveSentenceLike)
**remarque**
Effectivement, le LIKE sans wildcard `%` fonctionne

2022-07-13 09:12 UTC, octo-topi commented on api/db/migrations/20220712125907_add-hasBeenAutomaticallyResolved-column-to-certification-issue-reports.js
> +const autoResolveSentenceLike = 'Aucune question ne correspond au numéro %';
**nitpick**
```suggestion
const autoResolveSentencePattern = 'Aucune question ne correspond au numéro %';
```

2022-07-13 09:12 UTC, alexandrecoin commented on api/tests/integration/infrastructure/repositories/certification-issue-report-repository_test.js
> -    it('should throw a notFound error', async function () {
**Question :** Pourquoi ne vérifie-t-on plus que le signalement n'existe pas ?

2022-07-13 09:15 UTC, octo-topi requested changes, later dismissed
OK sauf https://github.com/1024pix/pix/pull/4650/commits/d0895b7a04e139665ee574edcd8e5796a675e7ff#r919836716

2022-07-13 09:24 UTC, P-Jeremy commented on api/lib/infrastructure/repositories/certification-issue-report-repository.js
> +      .merge()
C'est un fix de dernière minute hier soir, les tests d'acceptance étaient au rouge sans le onConflict. J'ai envoyé un message ce matin à Antoine pour dire qu'il manquait sûrement un test d'intégration de ce côté 🙂

2022-07-13 11:18 UTC, aceol commented on api/tests/integration/infrastructure/repositories/certification-issue-report-repository_test.js
> -    it('should throw a notFound error', async function () {
Avec bookshelf, on faisait par défaut cette verification. On estime pour autant que demander la suppression d'un element qui n'existe pas n'est pas un comportement attendu.
Si on souhaite le supprimer: Il n'existe pas donc tout va bien
Si on souhaite le récuperer: erreur 500, de toute facon, il n'y a pas de raison de le demander

2022-07-15 14:54 UTC, asrodride approved these changes

2022-07-15 14:54 UTC, asrodride commented
Fonctionnel OK!

2022-07-18 08:03 UTC, octo-topi approved these changes

2022-07-18 08:11 UTC, merged