[FEATURE] Ajout d'un id sur le message d'erreur sur la page de connexion de Pix App (PIX-5357)
1024pix/pix pull request #4657
Opened 2022-07-18 09:59 UTC by clarissedmn

## :unicorn: Problème
Le message d'erreur n'est pas à proximité du champ du formulaire, ce qui rend plus difficile l'accès à l'information.

## :robot: Solution
Ajouter un `id `sur les messages d'erreurs correspondant au `aria-describedby` des champs du formulaire afin de les associer directement.

## :100: Pour tester
Vérifier qu'un `aria-describedby` existe bien sur les champs du formulaires et qu'un attribut `id` est présent sur le message d'erreur.

2022-07-18 10:06 UTC, pix-service commented
I'm deploying this PR to these urls:

- App (.fr): https://app-pr4657.review.pix.fr
- App (.org): https://app-pr4657.review.pix.org
- Orga: https://orga-pr4657.review.pix.fr
- Certif: https://certif-pr4657.review.pix.fr
- Admin: https://admin-pr4657.review.pix.fr
- API: https://api-pr4657.review.pix.fr/api/

 Please check it out!

2022-07-18 13:34 UTC, Jeyffrey approved these changes

2022-07-18 13:57 UTC, yannbertrand commented on mon-pix/app/components/form-textfield.hbs
> +      aria-describedby="error-message"
```suggestion
      aria-describedby="sign-form-error-message"
```

2022-07-18 13:57 UTC, yannbertrand approved these changes
LGTM

2022-07-21 09:14 UTC, yannbertrand requested changes
Rediscuté ensemble, on peut faire mieux !

2022-07-21 13:33 UTC, matthiasferraina commented on mon-pix/app/components/account-recovery/backup-email-confirmation-form.hbs
> +    <div id="backup-email-confirmation-already-associate-error-message">
**NitPick**
```suggestion
    <div id="backup-email-confirmation-already-associated-error-message">
```

2022-07-21 13:33 UTC, matthiasferraina commented on mon-pix/app/components/form-textfield.hbs
> +      aria-describedby="{{@aria-describedby}} validationMessage-{{@textfieldName}}"
**Question** : Je vois qu'on a rajouté l'attribut `@aria-describedby` qui peut être récupéré en input du composant `FormTextField`. Mais dans les formulaire on utilise pas le `@aria-describedby` on ajoute juste `aria-describedby ` sur le composant ember directement. Est ce que on veut vraiment passer le aria-describedby en input du coup `(aria-describedby="{{@aria-describedby}}) `? ou bien le mettre directement sur le composant ember:

```
<FormTextfield
          @label="{{t "pages.password-reset-demand.fields.email.label"}}"
          @textfieldName="email"
          @validationStatus="default"
          @inputBindingValue={{this.email}}
          @require={{true}}
          aria-describedby="password-reset-demand-error-message password-reset-demand-failed-message"/>
```


🤔 ?

2022-07-21 13:37 UTC, clarissedmn commented on mon-pix/app/components/form-textfield.hbs
> +      aria-describedby="{{@aria-describedby}} validationMessage-{{@textfieldName}}"
Bien vu, c'est une erreur de ma part :) Il faut qu'on ajoute le @aria-describedby sur le composant FormTextField pour qu'il soit tranmis à l'input

2022-07-21 14:20 UTC, matthiasferraina approved these changes
LGTM

2022-07-21 16:10 UTC, yannbertrand approved these changes
LGTM good job 🚀 

**suggestion**: communiquer sur ce changement pour que les autres équipes pensent à ne pas oublier cet attribut dans les futures utilisations des composants FormTextField

2022-07-25 08:36 UTC, merged