[FEATURE] Restreindre l'accès aux campagnes de l'organisation CNAV sur Pix App(PIX-5114).
1024pix/pix pull request #4663
Opened 2022-07-18 14:19 UTC by Anne-Gaelle-S

## :unicorn: Problème
Nous ne gérons toujours pas l'accès restreint aux campagnes pour la CNAV sur Pix App.

## :robot: Solution
Restreindre l'accès aux campagnes appartenant à la CNAV. 

## :rainbow: Remarques
Mutualisation du code (back et front) pour nos deux partenaires openId: Pôle Emploi et CNAV.

PR qui supprime l'usage du Tag Pôle Emploi dans la restriction des accès aux campagnes : https://github.com/1024pix/pix/pull/4551/files#diff-2db20c130bafca6e6ba6a5746b898f5a763a86563360859da600de5e5e482eee

## :100: Pour tester
Comme ce ticket touche à du code Pôle Emploi, tester la non régression des scénarios PE : 

`Scénario première connexion`

- Aller sur Pix App
- Cliquer sur le bouton 'Se connecter avec Pole Emploi' ou taper dans l'url /connexion-pole-emploi
- Entrer les seeds Pôle Emploi (vous les trouverez dans le wiki)
- Valider les cgu
- Constater que l'on est connecté
- Se déconnecter

`Scénario deuxième connexion`

Se reconnecter et ne pas passer par les cgu

`Scénario campagne PE`

- Sur Pix App, taper /campagnes
- Entrer le code suivant : PIXEMPLOI
- Cliquer sur commencer
- Entrer les seeds Pôle Emploi (vous les trouverez dans le wiki)
- Constater que l'on revient sur Pix et sur la suite de la campagne

---

Tester le scénario CNAV classique aussi (/connexion-cnav)

Enfin, tester le scénario de la restriction d'accès à la campagne CNAV : 
- Sur Pix App, taper /campagnes
- Entrer le code suivant : PIXCNAV01
- Cliquer sur commencer
- Constater que l'on passe bien dans l'auth CNAV
- Remplir les infos (l'identifiant et mot de passe se trouvent dans le keepass Pix)
- Constater que l'on revient sur Pix et sur la suite de la campagne

2022-07-18 14:25 UTC, pix-service commented
I'm deploying this PR to these urls:

- App (.fr): https://app-pr4663.review.pix.fr
- App (.org): https://app-pr4663.review.pix.org
- Orga: https://orga-pr4663.review.pix.fr
- Certif: https://certif-pr4663.review.pix.fr
- Admin: https://admin-pr4663.review.pix.fr
- API: https://api-pr4663.review.pix.fr/api/

 Please check it out!

2022-07-18 16:22 UTC, yschoueri commented on api/lib/domain/usecases/index.js
> +  poleEmploiOidcAuthenticationService: require('../services/authentication/pole-emploi-oidc-authentication-service'),
J'ai l'impression que cette injection n'est plus necessaire

2022-07-18 16:26 UTC, yschoueri commented on mon-pix/app/routes/campaigns/access.js
> +      get(this.session, 'data.authenticated.identity_provider') === identityProvider;
a verifier qu'apres le login avec la cnav, on set bien authenticated.identity_provider

2022-07-19 08:32 UTC, AndreiaPena commented on api/db/seeds/data/campaigns-pro-builder.js
> +    targetProfileId: TARGET_PROFILE_PIX_EMPLOI_CLEA_ID,
Changer pour un targetProfile non POLE EMPLOI 
```suggestion
    targetProfileId: TARGET_PROFILE_PIX_CNAV_CLEA_ID,
```

2022-07-19 08:33 UTC, AndreiaPena commented on api/lib/application/authentication/authentication-controller.js
> +      AuthenticationMethod.identityProviders.CNAV
Todo dans une autre PR : Ne plus passer par le modèle AuthenticationMethod mais par la constante

2022-07-19 09:00 UTC, igorissen commented on api/lib/domain/services/authentication/oidc-authentication-service.js
> +module.exports = OidcAuthenticationService;
J'arrive après la bataille, soit le nom de la classe ne convient pas soit c'est la méthode createAccessToken qui n'est pas au bon endroit. La méthode `createAccessToken` est plus lié à PIX qu'à l'interconnexion avec un IDP. 🤔

2022-07-19 09:00 UTC, igorissen commented on api/lib/domain/services/authentication/authentication-service-registry.js
> +        oidcAuthenticationService: poleEmploiOidcAuthenticationService,
Quelle est la différence entre ces 2 services ?

2022-07-19 09:00 UTC, igorissen commented on api/lib/domain/services/authentication/pole-emploi-authentication-service.js
> -}
Pourquoi le choix de retirer uniquement createAccessToken ?

2022-07-19 09:02 UTC, AndreiaPena commented on api/lib/domain/services/authentication/pole-emploi-authentication-service.js
> -}
Parce qu'on cherche ici à mutualiser ce qui touche à la restriction des accès aux campagnes.
Dans la PR précédente on a touché à cette fonction coté PE en ajoutant l'identityProvider dans le token. Paramètre qui n'existait dans cette même fonction mais coté CNAV. 

L'objectif à long terme sera de ne plus avoir de service propre aux deux partenaires, mais ici on s'en tient juste à cette fonction pour ne pas déborder du but initial de la PR

2022-07-19 09:03 UTC, Anne-Gaelle-S commented on api/lib/application/authentication/authentication-controller.js
> +      AuthenticationMethod.identityProviders.CNAV
à long terme peut être que ce sera plutôt le front qui fournira cette information là non ?

2022-07-19 09:05 UTC, Anne-Gaelle-S commented on api/lib/application/pole-emploi/pole-emploi-controller.js
> +const authenticationService = require('../../../lib/domain/services/authentication/pole-emploi-authentication-service');
**remarque**
En vrai je trouve que ce renommage est un peu confusant et ne sert pas à grand chose 🤔 
Si je cherche spécifiquement `poleEmploi` pour trouver le code lié à pole emploi je ne tomberai pas dessus alors que c'est totalement en lien avec

2022-07-19 09:06 UTC, AndreiaPena commented on api/lib/domain/services/authentication/authentication-service-registry.js
> +        oidcAuthenticationService: poleEmploiOidcAuthenticationService,
Il faut voir cette PR comme une première étape à la mutualisation des services de nos partenaires. Du coup c'est pas jolie en l'état mais on se retrouve avec le service de base `authenticationService: poleEmploiAuthenticationService` qui contient encore toute les autres fonctions que l'on a pas mutualisé et le nouveau service `oidcAuthenticationService: poleEmploiOidcAuthenticationService` qui contient le createAccessToken.

A terme on aura qu'un seul service

2022-07-19 09:07 UTC, AndreiaPena commented on api/lib/application/pole-emploi/pole-emploi-controller.js
> +const authenticationService = require('../../../lib/domain/services/authentication/pole-emploi-authentication-service');
+1 ici ce n'est pas nécessaire de le renommer

2022-07-19 09:08 UTC, Anne-Gaelle-S commented on api/lib/domain/services/authentication/authentication-service-registry.js
> +        oidcAuthenticationService: poleEmploiOidcAuthenticationService,
`poleEmploiAuthenticationService` est notre ancien fichier de service de pole-emploi
`poleEmploiOidcAuthenticationService` est le fichier de configuration cible qui étend le service générique `OidcAuthenticationService` . 
En gros , quand on a finit la brique générique il n'y plus de terme pole emploi dans le code sauf dans `poleEmploiOidcAuthenticationService`

2022-07-19 09:09 UTC, Anne-Gaelle-S commented on api/lib/domain/services/authentication/oidc-authentication-service.js
> +module.exports = OidcAuthenticationService;
Alors le hic c'est qu'on crée un access token spécifique en fonction de chaque idp avec qui on se connecte. Du coup ça reste spécifique aux idp et non pas juste lié à Pix ...

2022-07-19 09:10 UTC, Anne-Gaelle-S commented on api/lib/domain/services/authentication/pole-emploi-authentication-service.js
> -}
On voulait se restreindre à l'accès aux campagnes CNAV (et sinon la PR ferait 15km de long 😅 ).
CreateAccessToken est utilisé pour accéder à une campagne quand la personne n'était pas encore loguée

2022-07-19 09:12 UTC, AndreiaPena commented on api/lib/domain/services/authentication/oidc-authentication-service.js
> +module.exports = OidcAuthenticationService;
Je suis d'accord mais il s'agit bien de la création d'un access token pour nos partenaires. Elle n'est pas utilisé pour autre chose. 
A mon sens pour que les choses soient clairs et à leur place, mieux vaut garder cette fonction dans ce service oidc plutôt que de le déplacer dans d'autres services qui ont eux aussi leur propre fonction createAccessToken mais pour d'autres besoins fonctionnels

2022-07-19 09:12 UTC, Anne-Gaelle-S commented on mon-pix/tests/unit/routes/campaigns/access_test.js
> +        campaign.isRestrictedByIdentityProvider.withArgs(CNAV).returns(true);
**remarque**
Je vois vraiment pas l'intérêt de déclarer `CNAV` dans une constante au dessus 🤔 ça apporte une ligne de plus mais pas d'info supplémentaire non ?

2022-07-19 09:20 UTC, AndreiaPena requested changes, later dismissed
Lorsque je teste avec le code campagne PIXCNAV01:

- j'accède à la CNAV pour me connecter
- Je suis redirigé vers PIX
- J’atteris sur le dashboard 🔴 au lieu de commencer la campagne

Quelqu'un d'autre à le même scénario ?

2022-07-19 10:25 UTC, iwazaru commented on mon-pix/app/routes/application.js
> +      this._isFromIdentityProviderLoginPage(nextURL, 'POLE_EMPLOI')
**question**
Est-ce qu'on a besoin de vérifier que l'idp est cnav ou pole emploi ? Est-ce qu'il ne faut pas rediriger dès lors qu'on a une nextURL dans la session ?

2022-07-19 13:03 UTC, AndreiaPena commented on mon-pix/app/routes/application.js
> +      this._isFromIdentityProviderLoginPage(nextURL, 'POLE_EMPLOI')
je crains des scénarios que je ne connait pas, disposant de nextURL mais qu'il veulent juste stocker et ne pas faire de replace avec. Les tests sont inexistants sur ce fichier, ça m'aide encore moins 😅

2022-07-19 13:05 UTC, yschoueri commented on api/lib/application/pole-emploi/pole-emploi-controller.js
> +const authenticationService = require('../../../lib/domain/services/authentication/pole-emploi-authentication-service');
le service a ete remplace par le registry dans des commits d'apres

2022-07-19 13:33 UTC, AndreiaPena approved these changes

2022-07-19 13:34 UTC, merged