[TECH] Mise à jour d'add-ons ember-cli sur Pix-Certif
1024pix/pix pull request #4691
Opened 2022-07-22 13:34 UTC by alexandrecoin

## :unicorn: Problème

Lorsque nous démarrons Pix-Certif, nous pouvons remarquer l'avertissement ci-dessous en console.
Cet avertissement est lié à la dépréciation du package `ember-cli-mirage`

<img width="404" alt="Capture d’écran 2022-07-22 à 15 33 18" src="https://user-images.githubusercontent.com/36371437/180450013-9cecbf7e-9799-4011-9c10-aa6b197f2946.png">

## :robot: Solution

Mise à jour de `ember-cli-mirage`

## :rainbow: Remarques

La MAJ du package entraîne l'apparition d'un  nouvel avertissement lié à `ember-cli-google-fonts` qui est déprécié et non utilisé dans l'application. Le package est par conséquent supprimé

## :100: Pour tester

Lancer Pix-Certif et vérifier que l'avertissement ci-dessus n'est plus présent en console.
Vérifier également qu'il n'y ait pas de régression dans l'application.

2022-07-22 13:39 UTC, pix-service commented
I'm deploying this PR to these urls:

- App (.fr): https://app-pr4691.review.pix.fr
- App (.org): https://app-pr4691.review.pix.org
- Orga: https://orga-pr4691.review.pix.fr
- Certif: https://certif-pr4691.review.pix.fr
- Admin: https://admin-pr4691.review.pix.fr
- API: https://api-pr4691.review.pix.fr/api/

 Please check it out!

2022-07-22 13:48 UTC, octo-topi requested changes
Est-ce souhaité de passer de la version 2 à 1 pour le lockfile (downgrade) dans le premier commit, puis l'inverse ensuite ? 
Cela entraîne la réécriture de tout le fichier et rend la diff illisible. Sinon pour le reste c'est tout bon :heart:

2022-07-22 13:57 UTC, alexandrecoin commented
> Est-ce souhaité de passer de la version 2 à 1 pour le lockfile (downgrade) dans le premier commit, puis l'inverse ensuite ? Cela entraîne la réécriture de tout le fichier et rend la diff illisible. Sinon pour le reste c'est tout bon ❤️

Bien vu. Ca a en effet pas lieu d'être.

2022-07-22 15:37 UTC, octo-topi approved these changes

2022-07-22 16:00 UTC, yannbertrand commented
Je suis vraiment curieux de comprendre pourquoi les `app.import` qu'on retrouve [sur Pix App](https://github.com/1024pix/pix/pull/4571/files) ne sont pas nécessaires ici. Mais sinon ça m'a l'air tout bon !

Petite suggestion de complément pour encore améliorer l'UX : https://github.com/1024pix/pix/pull/4618.

2022-07-22 16:00 UTC, yannbertrand approved these changes

2022-07-27 14:46 UTC, aceol approved these changes

2022-07-27 15:29 UTC, Thomasevano approved these changes

2022-08-03 08:01 UTC, francois2metz approved these changes
:purple_heart: :yellow_heart: :green_heart: :blue_heart: LGTM  :blue_heart: :green_heart: :yellow_heart: :purple_heart:

2022-08-03 12:27 UTC, merged