[FEATURE] Améliorations pages de maintenance Pix App
1024pix/pix pull request #4697
Opened 2022-07-24 04:30 UTC by yannbertrand

## :rainbow: Améliorations
- Ne plus récupérer le reset css de Cloudflare.
- Amélioration du `title` de la page de maintenance planifiée.
- Centrage vertical fluide pour éviter le margin top en dur.
- Utilisation du `word-break: break-word` pour passer à la ligne quand c'est nécessaire et éviter la scrollbar horizontale.
- Taille du logo adaptative pour éviter la scrollbar horizontale.
- Suppression du hack IE9.
- Fait tourné Prettier.

## :100: Pour tester
Regarder le résultat sur la RA sur `/maintenance_scheduled.html` et `/maintenance_page.html`.

2022-07-24 04:37 UTC, pix-service commented
I'm deploying this PR to these urls:

- App (.fr): https://app-pr4697.review.pix.fr
- App (.org): https://app-pr4697.review.pix.org
- Orga: https://orga-pr4697.review.pix.fr
- Certif: https://certif-pr4697.review.pix.fr
- Admin: https://admin-pr4697.review.pix.fr
- API: https://api-pr4697.review.pix.fr/api/

 Please check it out!

2022-07-24 05:06 UTC, MelanieMEB requested changes

2022-07-24 05:06 UTC, MelanieMEB commented on mon-pix/maintenance_page.html
> +        background: url('data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAABaAAAAQACAMAAAAgFQ6gAAADAFBMVEVIb+9FcO9javVmafVWbPI+ce1gavRCcO47cuxMbvBYbPKMg/FSbfFQbfGPgvKEhO9qaPZObvBaa/Nca/NvZ/dKb/BUbfJea/Rx
Est-ce qu'on ajoute un h1 ?

2022-07-24 05:06 UTC, MelanieMEB commented on mon-pix/maintenance_page.html
> +        background: url('data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAABaAAAAQACAMAAAAgFQ6gAAADAFBMVEVIb+9FcO9javVmafVWbPI+ce1gavRCcO47cuxMbvBYbPKMg/FSbfFQbfGPgvKEhO9qaPZObvBaa/Nca/NvZ/dKb/BUbfJea/Rx
Passer plutot par un margin-top negatif sur le .maintenace-page ?

2022-07-24 05:06 UTC, MelanieMEB commented on mon-pix/maintenance_page.html
> +        background: url('data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAABaAAAAQACAMAAAAgFQ6gAAADAFBMVEVIb+9FcO9javVmafVWbPI+ce1gavRCcO47cuxMbvBYbPKMg/FSbfFQbfGPgvKEhO9qaPZObvBaa/Nca/NvZ/dKb/BUbfJea/Rx
```suggestion
        <svg width="204" height="154" viewBox="0 0 204 154" xmlns="http://www.w3.org/2000/svg" aria-labelledby="title">
```

2022-07-24 06:05 UTC, MelanieMEB commented on mon-pix/maintenance_page.html
> +        background: url('data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAABaAAAAQACAMAAAAgFQ6gAAADAFBMVEVIb+9FcO9javVmafVWbPI+ce1gavRCcO47cuxMbvBYbPKMg/FSbfFQbfGPgvKEhO9qaPZObvBaa/Nca/NvZ/dKb/BUbfJea/Rx
Ajouter `aria-labelledby="title"` à `<svg>`

2022-07-24 06:51 UTC, yannbertrand commented on mon-pix/maintenance_page.html
> +        background: url('data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAABaAAAAQACAMAAAAgFQ6gAAADAFBMVEVIb+9FcO9javVmafVWbPI+ce1gavRCcO47cuxMbvBYbPKMg/FSbfFQbfGPgvKEhO9qaPZObvBaa/Nca/NvZ/dKb/BUbfJea/Rx
Done

2022-07-24 06:53 UTC, yannbertrand commented on mon-pix/maintenance_page.html
> +        background: url('data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAABaAAAAQACAMAAAAgFQ6gAAADAFBMVEVIb+9FcO9javVmafVWbPI+ce1gavRCcO47cuxMbvBYbPKMg/FSbfFQbfGPgvKEhO9qaPZObvBaa/Nca/NvZ/dKb/BUbfJea/Rx
Je sais pas quelle est la meilleure pratique. J'ai peur que si la page est trop petite pour accueillir tout le texte, on remonte en dehors du viewport 🤔

2022-07-24 10:58 UTC, MelanieMEB approved these changes

2022-07-29 07:09 UTC, alexandrecoin approved these changes

2022-07-29 07:25 UTC, VincentHardouin approved these changes

2022-07-29 08:06 UTC, yannbertrand commented
Je porte ça sur les autres applis avant de merger ;)

2022-08-22 08:34 UTC, merged