Pix 5578 remove c3 subcategory from issue modal
1024pix/pix pull request #4852
Opened 2022-09-01 13:04 UTC by alexandrecoin

## :unicorn: Problème
> _Décrivez ici le besoin ou l'intention couvert par cette Pull Request._

## :robot: Solution
> _Ajoutez à cet endroit, si nécessaire, des détails concernant la solution technique retenue et mise en oeuvre, des difficultés ou problèmes rencontrés._

## :rainbow: Remarques
> _Des infos supplémentaires, trucs et astuces ?_

## :100: Pour tester
> _Les instructions pour reproduire le problème, les profils de test, le parcours spécifique à utiliser, etc._

2022-09-01 13:09 UTC, pix-service commented
I'm deploying this PR to these urls:

- App (.fr): https://app-pr4852.review.pix.fr
- App (.org): https://app-pr4852.review.pix.org
- Orga: https://orga-pr4852.review.pix.fr
- Certif: https://certif-pr4852.review.pix.fr
- Admin: https://admin-pr4852.review.pix.fr
- API: https://api-pr4852.review.pix.fr/api/

 Please check it out!

2022-09-05 07:34 UTC, aceol commented on api/tests/unit/domain/models/CertificationIssueReport_test.js
> -      [...Object.values(CertificationIssueReportSubcategories)].forEach((subcategory) => {
Question: Pourquoi supprimer ce test?

2022-09-05 07:37 UTC, aceol requested changes, later dismissed
Il semble manquer le fichier de migration

2022-09-05 08:07 UTC, aceol approved these changes

2022-09-05 08:41 UTC, alexandrecoin commented on api/tests/unit/domain/models/CertificationIssueReport_test.js
> -      [...Object.values(CertificationIssueReportSubcategories)].forEach((subcategory) => {
Les deux sous-catégories testées n'existent plus.

2022-09-06 08:27 UTC, Libouk approved these changes

2022-09-06 08:57 UTC, P-Jeremy approved these changes

2022-09-06 10:07 UTC, merged