[FEATURE] Remplacer la transition de tickets Jira des GitHub Action à une App côté Jira
1024pix/pix pull request #4870
Opened 2022-09-05 12:55 UTC by yannbertrand

## :unicorn: Problème
L'intégration Jira/GitHub n'est pas très uniforme et demande de la maintenance pour des actions relativement basiques.

## :robot: Solution
Remplacer les GitHub Actions par une App GitHub côté Jira, en l’occurrence : [GitHub for Jira](https://marketplace.atlassian.com/apps/1219592/github-for-jira?hosting=cloud&tab=overview) (solution officielle Atlassian).

Voilà les premiers branchements utilisés : 
![image](https://user-images.githubusercontent.com/5855339/188452949-1959ed48-5e11-4c26-a314-2b11b03ec0bd.png)

## :rainbow: Remarques
Le remplacement n'est pas tout à fait ISO. Je l'ai configuré afin de ressembler autant que possible à notre workflow.

Avantages :
- Le ticket est détecté avec plus de liberté sur les usages : nom de la branche, nom du commit, nom de PR...
- Le ticket passe en "doing" dès qu'on commit ou ouvre une branche si on met le numéro de ticket dans un de ces 2 éléments (avant l'ouverture de PR donc).
- Plus de maintenance dev tant que l'App est maintenue par Jira.

Inconvénients : 
- Plus de lien avec le label ":eyes: Tech Review Needed"
- Pas de gestion des PR draft

Next steps :
- Mettre le numéro de version dans Jira automatiquement au passage en recette.
- Créer un ticket Jira qui reprend les infos d'une PR GitHub non reliée lors de son ouverture.
- Commentaire auto avec les liens vers RA + PR dans Jira (pour supprimer un script supplémentaire)

## :100: Pour tester
> _Les instructions pour reproduire le problème, les profils de test, le parcours spécifique à utiliser, etc._

2022-09-05 13:05 UTC, pix-service commented
I'm deploying this PR to these urls:

- App (.fr): https://app-pr4870.review.pix.fr
- App (.org): https://app-pr4870.review.pix.org
- Orga: https://orga-pr4870.review.pix.fr
- Certif: https://certif-pr4870.review.pix.fr
- Admin: https://admin-pr4870.review.pix.fr
- API: https://api-pr4870.review.pix.fr/api/

 Please check it out!

2022-09-05 14:47 UTC, francois2metz approved these changes
:grapes: :melon: :tangerine: :pineapple: :apple: :kiwi_fruit: LGTM :kiwi_fruit: :apple:  :pineapple:  :tangerine:  :melon: :grapes:

2022-09-06 07:47 UTC, octo-topi requested changes
J'aime l'idée, mais comment on teste ?
Pourrais-tu remplir la section "Comment tester" de la PR ?
Si pas possible sans merger, alors go

2022-09-06 08:08 UTC, yannbertrand commented
> J'aime l'idée, mais comment on teste ? Pourrais-tu remplir la section "Comment tester" de la PR ? Si pas possible sans merger, alors go

Vu que l'App Jira est déjà branchée, tu peux regarder l'historique des derniers tickets Jira qui ont transitionné, ça rentre en conflit avec les GitHub Action qui sont exécutées plus tard dans le workflow du ticket donc le résultat final n'est pas forcément cohérent mais ça donne une bonne idée ^^.

Je rempli la section "Pour tester" ;)

2022-09-06 08:34 UTC, octo-topi approved these changes

2022-09-06 16:22 UTC, pix-service commented
I'm deploying this PR to these urls:

- App (.fr): https://app-pr4870.review.pix.fr
- App (.org): https://app-pr4870.review.pix.org
- Orga: https://orga-pr4870.review.pix.fr
- Certif: https://certif-pr4870.review.pix.fr
- Admin: https://admin-pr4870.review.pix.fr
- API: https://api-pr4870.review.pix.fr/api/

 Please check it out!

2022-09-06 16:26 UTC, merged