[FEATURE] Améliorer la fonction de recherche d'un candidat dans l'espace surveillant (PIX-5728)
1024pix/pix pull request #4963
Opened 2022-09-22 14:16 UTC by Libouk

## :unicorn: Problème
La liste des candidats inscrits à une session de certification est affichée dans l’Espace Surveillant avec des actions liées, notamment la possibilité d’autoriser le lancement du test des candidats. Une fonction recherche permet au surveillant de session de rechercher un candidat dans l’Espace Surveillant.

- La fonction recherche ne retourne pas de résultats si le nom ET le prénom sont saisis dans la barre de recherche.

- La fonction recherche ne retourne aucun résultat si les caractères spéciaux ne sont pas recopiés dans la barre de recherche (ç, accent, tiret entre prénoms/noms composés etc).

## :robot: Solution
Ignorer les accents, prendre en compte les noms complets.

## :100: Pour tester
- Créer une session de certification avec des candidats dont les noms comprennent des accents ou des noms composés.
- Se connecter à l'espace surveillant de la session créée.
- Tester de rechercher le nom complet d'un candidat, prénom ou nom en premier.
- Tester de rechercher un candidat dont le nom ou prénom contient des accents.
- Tester de rechercher un candidat dont le nom ou prénom contient un tiret.

2022-09-22 14:22 UTC, pix-service commented
I'm deploying this PR to these urls:

- App (.fr): https://app-pr4963.review.pix.fr
- App (.org): https://app-pr4963.review.pix.org
- Orga: https://orga-pr4963.review.pix.fr
- Certif: https://certif-pr4963.review.pix.fr
- Admin: https://admin-pr4963.review.pix.fr
- API: https://api-pr4963.review.pix.fr/api/

 Please check it out!

2022-09-23 08:02 UTC, aceol approved these changes

2022-09-23 08:02 UTC, aceol commented on certif/app/components/session-supervising/candidate-list.js
> +      const collator = new Intl.Collator('fr', { sensitivity: 'base' });
Si on retire les '-' des noms, il faut aussi les retirer du filtre, 
 pour autant, l'option de Collator: `ignorePunctuation: true` le fait automatiquement, on peut donc retirer les `replace`
 

>  ignorePunctuation
> Whether punctuation should be ignored. Possible values are true and false; the default is false.

2022-09-23 08:02 UTC, aceol commented on certif/tests/integration/components/session-supervising/candidate-list_test.js
> +              id: 123,
L'id n'est pas utilisé, on peut le retirer
```suggestion
```

2022-09-23 09:35 UTC, alexandrecoin requested changes
Il y a un souci fonctionnel avec le prénoms composés. (présence d'un tiret)
<img width="613" alt="Capture d’écran 2022-09-23 à 11 34 26" src="https://user-images.githubusercontent.com/36371437/191932795-a1b19a9f-9ad1-41b3-8864-4832c7c7d4c8.png">
<img width="659" alt="Capture d’écran 2022-09-23 à 11 34 31" src="https://user-images.githubusercontent.com/36371437/191932806-ae87479a-31fc-4100-992b-171937988265.png">

2022-09-23 09:38 UTC, alexandrecoin commented
De plus je n'ai pas compris si le nom (ou le prénom) doit être intégralement cherché ou pas.
S'il est possible de n'entrer qu'une partie du nom (ex: sans la particule) afin de trouver l'utilisateur, il y a également un souci.
<img width="627" alt="Capture d’écran 2022-09-23 à 11 36 19" src="https://user-images.githubusercontent.com/36371437/191933363-16b7b193-c2db-4f5d-8562-7ed6ec06d3c5.png">
<img width="630" alt="Capture d’écran 2022-09-23 à 11 36 11" src="https://user-images.githubusercontent.com/36371437/191933375-6364ad08-1c75-4ce2-b829-ec32d612d154.png">

2022-09-23 09:53 UTC, Libouk commented
> De plus je n'ai pas compris si le nom (ou le prénom) doit être intégralement cherché ou pas. S'il est possible de n'entrer qu'une partie du nom (ex: sans la particule) afin de trouver l'utilisateur, il y a également un souci. <img alt="Capture d’écran 2022-09-23 à 11 36 19" width="627" src="https://user-images.githubusercontent.com/36371437/191933363-16b7b193-c2db-4f5d-8562-7ed6ec06d3c5.png"> <img alt="Capture d’écran 2022-09-23 à 11 36 11" width="630" src="https://user-images.githubusercontent.com/36371437/191933375-6364ad08-1c75-4ce2-b829-ec32d612d154.png">

Ca ne faisait pas partie de l'objectif de chercher une partie du nom.

2022-09-23 13:25 UTC, alexandrecoin approved these changes

2022-09-26 13:09 UTC, merged