[TECH] Utiliser les nouveaux attributs de compatibilité machine ajoutés aux Tubes dans la release LCMS (PIX-????)
1024pix/pix pull request #5139
Opened 2022-10-26 19:00 UTC by laura-bergoens

## :jack_o_lantern: Problème
Côté LCMS le schéma de la release a évolué : les tubes contiennent maintenant l'info sur leur compatibilité tablette/smartphone.
Plus besoin donc, côté Pix, de calculer ces champs en passant par les épreuves (complexe)

## :bat: Proposition
Utiliser les nouveaux attributs

## :spider_web: Remarques
BLOQUé : en attente de merge côté LCMS de la nouveauté.

## :ghost: Pour tester
Tester la non-rég sur l'affichage des infos de compatibilité dans les affichages suivants :
- Dans PixAdmin, sur un "nouveau" profil-cible, dans l'accordéon à côté des sujets
- Dans PixOrga, dans la page de sélection de sujets, dans l'accordéon également

2022-11-19 13:59 UTC, pix-service commented
I'm deploying this PR to these urls:

- App (.fr): https://app-pr5139.review.pix.fr
- App (.org): https://app-pr5139.review.pix.org
- Orga: https://orga-pr5139.review.pix.fr
- Certif: https://certif-pr5139.review.pix.fr
- Admin: https://admin-pr5139.review.pix.fr
- API: https://api-pr5139.review.pix.fr/api/

 Please check it out!

2022-11-30 15:33 UTC, nlepage requested changes
C'est top, ça simplifie énormément.

Cependant modifier les propriétés présentes sur les objets du modèle au niveau du usecase me semble être une mauvaise idée.

On pourrait plutôt essayer d'adapter le serializer ?

2022-11-30 15:33 UTC, nlepage commented on api/lib/domain/usecases/get-framework-areas.js
> +  }
**issue:** `tubeRepository` renvoie des objets du modèle, ça paraît dangereux de modifier les propriétés présentes sur ces objets non ?

2022-12-01 08:37 UTC, laura-bergoens commented on api/lib/domain/usecases/get-framework-areas.js
> +  }
Moui. L'ajout de propriétés était un truc qui existait déjà avant sur ce usecase, après le delete n'est pas indispensable. Mais si vraiment tout ça te gratte (je te rassure ça me gratte bcp aussi la modification de modèle comme ça) je peux tenter un petit commit de refacto

2022-12-01 09:20 UTC, nlepage approved these changes

2022-12-01 09:30 UTC, Thomasevano approved these changes

2022-12-01 10:18 UTC, merged