[TECH] Supprime le code specifique de certification complementaire (PIX-6199)
1024pix/pix pull request #5151
Opened 2022-11-02 09:12 UTC by aceol

## :jack_o_lantern: Problème
Suite au refacto de sessions complementaire, il n'est plus nécessaire d'avoir du code specifique

## :bat: Proposition
Supprimer le code encore existant

## :spider_web: Remarques
Des codes specifique aux badges sont necessaires pour les migrations. Ils sont deplaces dans api/db

## :ghost: Pour tester
Pas de regression sur le passage de certification complementaire. Verifier les badges sur les certificats

2022-11-02 09:18 UTC, pix-service commented
I'm deploying this PR to these urls:

- App (.fr): https://app-pr5151.review.pix.fr
- App (.org): https://app-pr5151.review.pix.org
- Orga: https://orga-pr5151.review.pix.fr
- Certif: https://certif-pr5151.review.pix.fr
- Admin: https://admin-pr5151.review.pix.fr
- API: https://api-pr5151.review.pix.fr/api/

 Please check it out!

2022-11-02 16:40 UTC, aceol commented on api/lib/domain/models/ComplementaryCertificationCourseResult.js
> +    this.complementaryCertificationId = complementaryCertificationId;
Pourquoi?

2022-11-02 16:45 UTC, aceol commented on api/db/seeds/data/badges-builder.js
> -const Badge = require('../../../lib/domain/models/Badge');
Pas dans le bon commit

2022-11-03 07:56 UTC, alexandrecoin approved these changes
LGTM 🧹

2022-11-03 08:38 UTC, aceol commented on api/lib/domain/models/ComplementaryCertificationCourseResult.js
> +    this.complementaryCertificationId = complementaryCertificationId;
supprimé!

2022-11-03 13:34 UTC, alexandrecoin requested changes
La session de certification créée à l'aide du CLI ne renvoie pas de session de certif dans Pix-certif (alors qu'il est possible de passer la certification en question sur pix-app)
Testé sur une autre RA pour comparer (feat @mcampourcy )

2022-11-03 17:03 UTC, mariannebost approved these changes

2022-11-04 15:42 UTC, aceol commented
> La session de certification créée à l'aide du CLI ne renvoie pas de session de certif dans Pix-certif (alors qu'il est possible de passer la certification en question sur pix-app) Testé sur une autre RA pour comparer (feat @mcampourcy )

Ce n'etait pas lié à cette PR, mais j'ai quand meme rajouté le fix: on n'avait pas d'ordre sur le centre de certif sur lequel ajouter la sessions

2022-11-06 06:02 UTC, alexandrecoin approved these changes

2022-11-07 13:43 UTC, merged