[FEATURE] Migration de reprise des données des utilisateurs déjà anonymisés (PIX-6630)
1024pix/pix pull request #5436
Opened 2023-01-03 10:30 UTC by igorissen

## :christmas_tree: Problème

Actuellement, suite à l'ajout de nouvelles colonnes **hasBeenAnonymised** et **hasBeenAnonymisedBy** sur la table **Users**, les utilisateurs anonymes ont toujours les valeurs par défaut pour ces colonnes **FALSE** et **NULL**.

## :gift: Proposition

Créer un script de migration de base de données pour mettre à jour la valeur de la colonne `hasBeenAnonymised` pour tous les utilisateurs anonymes (FALSE -> TRUE).

## :star2: Remarques

- Test à faire en local uniquement
- Si un rollback doit être fait de cette migration, la valeur dans la colonne `hasBeenAnonymisedBy` sera retirée

## :santa: Pour tester

- Se mettre sur la branche `dev` et récupérer la dernière version du code
- Exécutez la commande, dans le dossier de l'api, `npm run db:reset` pour avoir une base de données propre
- Lancez l'api et l'application admin
- Anonymisez des utilisateurs
- Vérifiez en base de données que ces utilisateurs ont bien été anonymisé
- Pour chacun des ces utilisateurs anonymisés, supprimer les valeurs des colonnes `hasBeenAnonymised (FALSE)` et `hasBeenAnonymisedBy (NULL)` pour obtenir l'état actuel des utilisateurs anonymisés en production
- Stoppez l'api et l'application admin
- Se mettre sur la branche de cette PR
- Exécutez la commande, dans le dossier de l'api, `npm run db:migrate`
- Constatez en base de données que les utilisateurs anonymisés ont la valeur `TRUE` pour la colonne `hasBeenAnonymised`
- Exécutez la commande, dans le dossier de l'api, `npm run db:rollback:latest`
- Constatez en base de données que les utilisateurs anonymisés ont la valeur `FALSE` pour la colonne `hasBeenAnonymised`

2023-01-03 15:59 UTC, annemarie35 commented on api/db/migrations/20230103093529_set-date-for-hasBeenAnonymised-column-on-users-table.js
> +/**
Suggestion : supprimer ces commentaires s'ils ne servent à rien

2023-01-04 09:03 UTC, annemarie35 approved these changes

2023-01-04 13:48 UTC, AndreiaPena commented
**Question** : N'a-t-on pas possiblement des utilisateurs actifs ayant en adresse e-mail des @example.net ? 
Comme on accepte les adresses bidons 😅

2023-01-04 13:54 UTC, AndreiaPena requested changes
Question : N'a-t-on pas possiblement des utilisateurs actifs ayant en adresse e-mail des @example.net ?
Comme on accepte les adresses bidons 😅

Update : j'en ai trouvé une dizaine avec des exemple.net et des infos non anonymisé sur Metabase

Je met ça en request changes en attendant ta réponse :)

2023-01-04 14:23 UTC, AndreiaPena approved these changes

2023-01-05 10:21 UTC, merged