[BUGFIX] Supprimer la div dans le bouton reset d'une compétence (PIX-6777).
1024pix/pix pull request #5504
Opened 2023-01-16 10:52 UTC by squirrel4k

## :christmas_tree: Problème
Suite à d'accessibilité, il est conseillé de ne pas avoir de div dans un <bouton>

## :gift: Proposition
Remplacer la div avec sr-only par un aria-label sur le bouton

## :star2: Remarques
/

## :santa: Pour tester
> _Les instructions pour reproduire le problème, les profils de test, le parcours spécifique à utiliser, etc._

2023-01-16 10:53 UTC, pix-service commented
Une fois les applications déployées, elles seront accessibles via les liens suivants :
  * [App (.fr)](https://app-pr5504.review.pix.fr)
  * [App (.org)](https://app-pr5504.review.pix.org)
  * [Orga](https://orga-pr5504.review.pix.fr)
  * [Certif](https://certif-pr5504.review.pix.fr)
  * [Admin](https://admin-pr5504.review.pix.fr)
  * [API](https://api-pr5504.review.pix.fr/api/)

Les variables d'environnement seront accessibles via les liens suivants :
  * [scalingo front](https://dashboard.scalingo.com/apps/osc-fr1/pix-front-review-pr5504/environment)
  * [scalingo api](https://dashboard.scalingo.com/apps/osc-fr1/pix-api-review-pr5504/environment)

2023-01-17 10:05 UTC, clarissedmn approved these changes

2023-01-17 10:34 UTC, VincentHardouin commented
C'est lu dans quel sens : Contenu du bouton puis aria-label,  l'inverse ou juste l'aria-label ? 
Je trouve pas ça très fluide comme nommage non ?

2023-01-17 10:42 UTC, clarissedmn commented
@VincentHardouin la aria-label override le contenu du bouton. Donc le contenu du bouton ne sera pas restitué avec le lecteur d'écran

2023-01-17 10:45 UTC, VincentHardouin commented
> @VincentHardouin la aria-label override le contenu du bouton. Donc le contenu du bouton ne sera pas restitué avec le lecteur d'écran

ça marche merci, du coup le aria-label ne dit pas ce que fait le bouton :/

2023-01-17 16:34 UTC, Jeyffrey requested changes

2023-01-17 16:34 UTC, Jeyffrey commented on mon-pix/app/components/scorecard-details.hbs
> +            aria-label="{{t 'pages.competence-details.for-competence' competence=@scorecard.name}}"
Cette traduction ne peut pas fonctionner seule dans un aria-label car le texte qu'elle apporte vient en complément du reste du label du bouton : `"for-competence": "la compétence {competence}",`.

Pour corriger ce problème d'accessibilité, il est possible de transformer la `div` en un `span`

2023-01-19 09:24 UTC, clarissedmn approved these changes

2023-01-19 09:33 UTC, VincentHardouin approved these changes

2023-01-19 09:42 UTC, matthiasferraina approved these changes

2023-01-19 09:44 UTC, Jeyffrey approved these changes

2023-01-19 10:22 UTC, merged