[ADR] Stockage du token d'accès de l'utilisateur côté client
1024pix/pix pull request #5558
Opened 2023-01-26 15:42 UTC by igorissen

## :egg: Problème

Actuellement, le token d'accès des utilisateurs se trouvent dans le localStorage du navigateur et donc disponible. Il faudrait utiliser un stockage plus sécurisé comme le cookieStorage.

## :bowl_with_spoon: Proposition
> _Ajoutez à cet endroit, si nécessaire, des détails concernant la solution technique retenue et mise en oeuvre, des difficultés ou problèmes rencontrés._

## :milk_glass: Remarques
> _Des infos supplémentaires, trucs et astuces ?_

## :butter: Pour tester
> _Les instructions pour reproduire le problème, les profils de test, le parcours spécifique à utiliser, etc._

2023-01-27 11:04 UTC, AndreiaPena commented on docs/adr/0041-stockage-de-l-access-token-cote-client.md
> +- Incompatibilité entre l'utilisation des cookies et du flow OAuth2 par le fonctionnement d'EmberSimpleAuth. Ce qui nous pousserait à ne plus utiliser le flow OAuth2 (voir https://github.com/mainmatt
l'incompatibilité provient du fait que notre 0Auth2 est custom ?

2023-02-01 14:45 UTC, igorissen commented on docs/adr/0041-stockage-de-l-access-token-cote-client.md
> +- Incompatibilité entre l'utilisation des cookies et du flow OAuth2 par le fonctionnement d'EmberSimpleAuth. Ce qui nous pousserait à ne plus utiliser le flow OAuth2 (voir https://github.com/mainmatt
Je pense que j'ai choisi un mot qui ne convient pas. Je vais voir pour en trouver un autre.

En faite un authenticator utilise un store. Dans notre cas, notre authenticator OAuth2, qui ne faite que rajouter notre logique par dessus celle de ESA, utilise l'[AdaptiveStore](https://ember-simple-auth.com/api/classes/AdaptiveStore.html) pour stocker le retourne de l'api après authentification et rafraichir le token d'accès.

Si on passe sur le CookieStore, toutes les informations du cookie vont se retrouver sur chacune des requêtes HTTP. Ce n'est pas le but de notre initiative.  Notre but étant de protéger le token d'accès (et celui de rafraichissement) avec un cookie sécurisé (secure + httpOnly). Si on sécurise le cookie, ESA ne pourra pas vérifier si l'utilisateur est connecté, il ne pourra pas gérer le rafraichissement du token d'accès. Un cookie sécurisé ne peut pas être lu par du JavaScript. Seul le backend pourra le faire.

2023-02-02 18:29 UTC, lego-technix commented on docs/adr/0041-stockage-de-l-access-token-cote-client.md
> +Nous utilisons le flow OAuth2 (custom) pour l'authentification des utilisateurs.
Je n'arrive plus à expliquer pourquoi le flow OAuth2 est _custom_. Il serait bon de l'expliciter :pray:

2023-02-02 18:35 UTC, lego-technix requested changes

2023-02-02 18:35 UTC, lego-technix commented on docs/adr/0041-stockage-de-l-access-token-cote-client.md
> +Nous gardons la solution actuelle, c'est-à-dire l'utilisation du localStorage.
```suggestion
Aucune solution n'a été trouvée qui éviterait le changement du flow d'authentification actuellement utilisé (OAuth2 custom) tout en gardant EmberSimpleAuth qui automatise pour nous toute la gestion des refresh tokens.
Aussi nous gardons pour l'instant la solution actuelle, c'est-à-dire l'utilisation du localStorage.
Une potentielle solution à plus long terme serait de faire une contribution à EmberSimpleAuth faisant l'utilisation de cookie pour le stockage de l'access token, mais il faudrait déjà réaliser ce développement puis qu'il soit accepté ce qui n'a rien de certain.
```

2023-02-03 09:45 UTC, igorissen commented on docs/adr/0041-stockage-de-l-access-token-cote-client.md
> +Nous utilisons le flow OAuth2 (custom) pour l'authentification des utilisateurs.
Sur toutes les applications, c'est pour définir l'endpoint pour authentification et le rafraichissement du token.
Par contre PixApp à une subtilité en plus, c'est la gestion de la connexion via le GAR.

2023-02-03 11:04 UTC, lego-technix approved these changes

2023-02-03 15:43 UTC, igorissen commented on docs/adr/0041-stockage-de-l-access-token-cote-client.md
> +Nous utilisons le flow OAuth2 (custom) pour l'authentification des utilisateurs. Ce flow nous permet de définir des endpoints différents de ceux par défaut fourni par ESA (Ember Simple Auth). La subt
```suggestion
Nous utilisons le flow OAuth2 (custom) pour l'authentification des utilisateurs. Ce flow nous permet de définir des endpoints différents de ceux par défaut fournis par ESA (Ember Simple Auth). La subtilité sur PixApp, c'est que nous devons également gérer les connexions via le GAR. 
```

2023-02-03 15:45 UTC, lego-technix approved these changes

2023-02-07 14:55 UTC, clemlatz approved these changes
Merci pour cette ADR !

Je propose juste d'ajouter une phrase à la fin du type :
"Nous avons choisi d'entériner cette non décision par une ADR pour sauvegarder le fruit de nos réflexions au cas où, à l'avenir, d'autres développeurs considérait la possibilité d'utiliser un cookie plutôt que le localStorage pour stocker le token d'accès."

2023-02-07 17:29 UTC, merged