[BUGFIX][MON-PIX] Rediriger l'utilisateur vers la page de connexion si un identity provider n'est pas configuré (PIX-6997)
1024pix/pix pull request #5610
Opened 2023-02-03 16:19 UTC by igorissen

## :egg: Problème

Si un utilisateur accède aujourd’hui à https://app.pix.org/connexion/fwb, cela déclenche une erreur 500.

C’est (probablement) dû au fait que les variables ne sont pas encore renseignés (à confirmer).

## :bowl_with_spoon: Proposition

Lorsqu’on appelle l’url de connexion oidc avec un identity provider qui n’est pas configuré, réagir comme si l’idp n’existait pas en redirigant l’utilisateur vers la page de connexion standard.

## :milk_glass: Remarques

RAS

## :butter: Pour tester

- En local retirer les configurations d'un identity provider (Pole Emploi, CNAV ou FWB)
- Démarrer l'api ainsi que l'application mon-pix
- Tenter une connexion via l'url associée à l'identity provider que vous avez retiré
- Constater que vous arrivez sur la page de connexion de Pix

2023-02-06 10:03 UTC, annemarie35 commented on api/tests/unit/domain/usecases/get-identity-providers.js
> +      sinon.stub(config, 'fwb').value({});
Suggestion : dans le before each ça renvoie déjà un objet vide. Cette ligne peut être supprimée

2023-02-06 10:08 UTC, annemarie35 commented on api/tests/unit/domain/usecases/get-identity-providers.js
> +      clientId: 'client id pole emploi',
Idem ici, vu qu'il faut juste que l'objet soit pas vide, on peut enlever les propriétés (ou alors c'était important et c'est pas couvert par le test)

2023-02-06 10:24 UTC, annemarie35 commented on api/lib/application/authentication/oidc/oidc-controller.js
>  module.exports = {
Il manque le test pour ce provider dans 
`api/tests/acceptance/application/authentication/oidc/authentication-url-route-get_test.js`

2023-02-06 10:24 UTC, annemarie35 commented on api/lib/application/authentication/oidc/oidc-controller.js
> +    return h.response(serializer.serialize(identityProviders)).code(200);
Il manque le test pour ce provider dans
api/tests/acceptance/application/authentication/oidc/authentication-url-route-get_test.js

2023-02-06 10:25 UTC, annemarie35 requested changes
Revue fonctionnelle ok pour moi.
ça serait bien de rajouter un test dans
api/tests/acceptance/application/authentication/oidc/authentication-url-route-get_test.js

2023-02-06 10:28 UTC, clemlatz reviewed
✅  Test fonctionnel OK

2023-02-06 10:28 UTC, clemlatz commented on api/lib/domain/services/authentication/oidc-authentication-service.js
> +const { v4: uuidv4 } = require('uuid');
**suggestion** : Tant qu'à faire, je propose de séparer par une ligne vide les imports de packages npm de nos modules internes.

2023-02-06 10:28 UTC, clemlatz commented on api/lib/domain/usecases/get-identity-providers.js
> +const IDENTITY_PROVIDERS = [
**question** : plutôt que de redéfinir les idp ici, est-ce qu'on ne pourrait faire évoluer et réutiliser ce qu'il y a dans `api/lib/domain/constants/oidc-identity-providers.js` ? C'est dommage parce qu'en l'état ça ajoute un endroit à modifier quand on ajoute un nouvel identity provider.

(D'ailleurs, si on garde cette façon de faire, il faudra mettre à jour : https://1024pix.atlassian.net/wiki/spaces/DEV/pages/3471474691/Ajout+d+un+nouveau+Identity+Provider+IDP+en+OpenID+Connect+OIDC+sur+Pix+App)

2023-02-06 14:08 UTC, igorissen commented on api/lib/application/authentication/oidc/oidc-controller.js
> +    return h.response(serializer.serialize(identityProviders)).code(200);
Pourrais-tu me donner plus de détails ?
Actuellement ce test dont tu fais références teste un fichier que je n'ai pas modifié. La route qui est impactée par ma modification est celle-ci `/api/oidc/identity-providers`.
Pour la modification que j'ai apporté, j'ai l'impression qu'un test unitaire au niveau du usecase est amplement suffisant.

2023-02-06 14:12 UTC, igorissen commented on api/tests/unit/domain/usecases/get-identity-providers.js
> +      clientId: 'client id pole emploi',
L'objet doit absolument contenir les propriétés requises pour le bon fonctionne d'un service de type OIDC. Si tu retires l'une des propriétés requises le test va être en erreur.

2023-02-06 14:53 UTC, annemarie35 commented on api/tests/unit/domain/usecases/get-identity-providers.js
> +      clientId: 'client id pole emploi',
Bizarre, j'ai commenté en laissant juste clientId: 'client id pole emploi', et joué les tests du usecases, ils sont resté verts...

2023-02-06 15:12 UTC, igorissen commented on api/lib/domain/usecases/get-identity-providers.js
> +const IDENTITY_PROVIDERS = [
Je viens de faire la modification. J'ai créé un commit en plus pour régler les problèmes qu'apporte ce changement.

2023-02-06 15:16 UTC, igorissen commented on api/tests/unit/domain/usecases/get-identity-providers.js
> +      clientId: 'client id pole emploi',
> Bizarre, j'ai commenté en laissant juste clientId: 'client id pole emploi', et joué les tests du usecases, ils sont resté verts...

Il y avait bien un problème au niveau du usecase que j'ai réglé (une mauvaise comparaison). Mais les propriétés sont requises pour le bon fonctionne de chaque service de type OIDC.

2023-02-06 16:07 UTC, annemarie35 commented on api/lib/application/authentication/oidc/oidc-controller.js
> +    return h.response(serializer.serialize(identityProviders)).code(200);
C'est la 500 qui est dans le ticket non ?
Je suis allée sur la branche dev, ai essayé d'aller sur http://localhost:4200/connexion/fwb (on voit que ça passe par http://localhost:4200/connexion/undefined) 

![Capture d’écran 2023-02-06 à 17 06 34](https://user-images.githubusercontent.com/7688741/217023102-6b27aba9-d97e-463a-8496-43fb4867e084.png)

2023-02-06 16:11 UTC, annemarie35 commented on api/tests/unit/domain/usecases/get-identity-providers.js
> +describe('Unit | UseCase | get-identity-providers', function () {
il faut ajouter _test à la fin du fichier

2023-02-06 16:30 UTC, igorissen commented on api/lib/application/authentication/oidc/oidc-controller.js
> +    return h.response(serializer.serialize(identityProviders)).code(200);
Oui c'est bien ça.

Cette 500 vient du faites que la requête `GET /identity-providers` que tu vois en 2e ligne retourne la FWB en plus de Pole Emploi et CNAV. Comme nous n'avons pas défini de valeur pour la FWB en prod (et ici dans ton cas en local) le service FWB est instancié sans valeur d'où le undefined.

2023-02-06 16:40 UTC, igorissen commented on api/lib/application/authentication/oidc/oidc-controller.js
> +    return h.response(serializer.serialize(identityProviders)).code(200);
https://github.com/1024pix/pix/blob/9320a20b1d5445114b640964c58b245749a4b791/mon-pix/app/routes/authentication/login-oidc.js#L30-L31

Voici le code sur `PixApp` qui décide si le front doit faire la requête pour obtenir l'authenticationUrl ou rediriger vers la page de connexion.
Sur dev on aura PE, CNAV et FWB mais FWB n'est pas configuré. Avec cette PR, on aura uniquement PE et CNAV parce que FWB n'est pas configuré correctement (pas de variables d'environnement)

2023-02-06 17:03 UTC, annemarie35 commented on api/lib/application/authentication/oidc/oidc-controller.js
> +    return h.response(serializer.serialize(identityProviders)).code(200);
@igorissen, j'ai lu le ticket jira, je sais que le pb vient du fait qu'il manque des var d'env :) J'ai fait tout plein de tests et de lecture de code pour comprendre... J'ai pas les vars d'env CNAV en local et j'ai des 500 comme pour la fwb.

Le sens de ma remarque :  il y a une route qui renvoie une 500 quand il manque des vars d'env, on peut s'assurer du comportement en mode scout rule en ajoutant un test. On parle pas de la même chose.

2023-02-06 17:03 UTC, annemarie35 approved these changes

2023-02-06 17:05 UTC, annemarie35 reviewed
Je referais une passe demain.

2023-02-07 08:09 UTC, annemarie35 commented on api/lib/domain/usecases/get-identity-providers.js
> +const IDENTITY_PROVIDERS = [
@igorissen @clemlatz Remarque : hier avec @reibecca on a eu du mal à comprendre simplement le code de cette PR et pour moi c'est un bad smell. Je m'explique. On a un fichier de constantes et je m'attends à ce que ça renvoie un objet avec de la configuration issue des var d'env. Or, le code m'a l'air bien complexe.
Après réflexion, je me demande si on aurait pas, inversé les dépendances.
On a api/lib/domain/constants/oidc-identity-providers.js qui dépend d'un service, par exemple PoleEmploiOidcAuthenticationService qui en plus étend la classe  OidcAuthenticationService ([voir ici](https://github.com/1024pix/pix/blob/dev/api/lib/domain/services/authentication/pole-emploi-oidc-authentication-service.js#L9)). 
On est donc obligé d'instancier des classes qui gèrent plus que juste générer un object avec de la config. Et comme ce fichier est utilisé un peu partout, dans les repo aussi, ça les fait dépendre les repo de OidcAuthenticationService.

Est-ce qu'on aurait pas mieux faire de différencier les deux ?

Après si on rajoute un nouvel IDP, je crois qu'on va devoir faire **NouvelIdpOidcAuthenticationService** sauf si on se lance dans un nouveau refacto

2023-02-07 08:56 UTC, igorissen commented on api/lib/application/authentication/oidc/oidc-controller.js
> +    return h.response(serializer.serialize(identityProviders)).code(200);
Je comprends l'idée du test (enfin je pense), mais cela ajouterai un test inutile pour moi.

La route dont tu souhaites ajouter un test, a une validation Joi sur les identity providers. Actuellement, en prod, la route va attendre les identity providers suivant : pole-emploi, cnav et undefined. Sur cette PR ce sera également le cas parce que le fichier de constantes liste tous les identity provider même ceux qui n'ont pas de configuration d'où le undefined.

En l'état ajouter le test n'aura aucune utilité. Il faut changer le fonctionne du fichier de constante pour n'exporter que les identity providers qui ont leurs variables d'environnements.

2023-02-09 14:48 UTC, clemlatz commented on api/lib/domain/usecases/get-identity-providers.js
> +const IDENTITY_PROVIDERS = [
Personnellement ça me va de laisser ça comme ça dans la mesure où : 
1. le problème n'a pas été introduit dans cette PR
2. c'est un bug fix

Mais je suis d'accord qu'en l'état ce n'est pas très satisfaisant, je propose d'ajouter un ticket dette technique pour remettre sur l'établi les imports de config des IDP.

2023-02-09 14:54 UTC, clemlatz commented on api/lib/application/authentication/oidc/oidc-controller.js
> +    return h.response(serializer.serialize(identityProviders)).code(200);
Je ne suis pas sûr d'avoir compris le débat (donc je m'excuse par avance si je dis une bêtise) s'il y a encore une route qui renvoie 500 sous certaines conditions, pour moi ce n'est pas un test qui manque mais un bug (à corriger peut-être dans un autre ticket pour ne pas bloquer celui-là).

2023-02-09 14:54 UTC, clemlatz approved these changes

2023-02-10 09:07 UTC, annemarie35 commented on api/lib/application/authentication/oidc/oidc-controller.js
> +    return h.response(serializer.serialize(identityProviders)).code(200);
@clemlatz l'alerte envoyée par les captains est la 500 qu'on voit dans la copie d'écran.
La correction apporté par Isma fait que cette route n'est plus appelée avec les paramètres FWB, donc plus d'appel, plus de 500.

2023-02-14 14:42 UTC, merged