[TECH] Monter la version de Node.js de CircleCI
1024pix/pix pull request #5615
Opened 2023-02-06 13:53 UTC by yannbertrand

## :christmas_tree: Problème
La version de Node.js que nous utilisons sur les tests E2E CircleCI n'est pas celle que l'on utilise en production.

## :gift: Solution
Monter cette version en v16.19.0 (elle est dispo depuis 29/12/2022).

## :star2: Remarques
RAS

## :santa: Pour tester
Vérifier que la CI passe toujours.

2023-02-06 14:45 UTC, alexandrecoin approved these changes

2023-02-06 14:51 UTC, nlepage approved these changes

2023-02-06 14:54 UTC, P-Jeremy approved these changes

2023-02-06 14:59 UTC, VincentHardouin approved these changes

2023-02-07 08:39 UTC, octo-topi approved these changes

2023-02-07 08:41 UTC, octo-topi requested changes, later dismissed
Les tests ne passent pas :cry: 

**nitpick**
Ajouter la raison du décalage d'image dans la description de PR
https://github.com/1024pix/pix/blob/dev/docs/adr/0018-specifier-version-nodejs.md#d%C3%A9cision

2023-02-07 09:48 UTC, octo-topi approved these changes

2023-02-07 09:49 UTC, merged