[FEATURE] Permettre de rattacher une liste de profils cible à un contenu formatif dans Pix Admin (PIX-7072)
1024pix/pix pull request #5644
Opened 2023-02-10 11:14 UTC by matthiasferraina

## :unicorn: Problème
Actuellement, les contenus formatifs peuvent être créés via Pix Admin. Notre souhait est de permettre de les suggérer en fin de parcours. Pour cela, nous devons pouvoir les rattacher à des profils cible existants.

## :robot: Proposition
Nous allons permettre ce rattachement dans Pix Admin. Pour cela, nous avons conservé la même logique que celle du rattachement d'un profil cible à une organisation.

## :rainbow: Remarques
Les premiers commits font partie de cette[PR](https://github.com/1024pix/pix/pull/5632). Il faudra rebase une fois qu'elle aura été mergée.

## :100: Pour tester
- Se connecter  à Pix Admin.
- Aller sur la page des contenus formatifs.
- Selectionner un contenu formatif dans la liste.
- Au niveau de la page de détail, cliquer sur l'onglet "Profils cible".
- Ajouter un profil cible qui n'est pas dans la liste, en saisissant son `id`

2023-02-13 15:47 UTC, VincentHardouin commented on api/lib/infrastructure/repositories/target-profile-trainings-repository.js
> +      .merge()
**suggestion** : Peut-être mettre à jour l'`updatedAt` non ?

2023-02-13 15:47 UTC, VincentHardouin commented on api/lib/infrastructure/repositories/target-profile-trainings-repository.js
> +const { knex } = require('../../../db/knex-database-connection');
Les noms de repo sont majoritairement au singulier

2023-02-13 15:47 UTC, VincentHardouin commented on api/tests/integration/infrastructure/repositories/target-profile-trainings_test.js
> +const { expect, databaseBuilder } = require('../../../test-helper');
Est-ce qu'on peut renommer le fichier : `target-profile-trainings-repository_test.js` ? Ca permettre le bon fonctionnement de la superbe fonctionnalité de Webstorm pour switcher entre les tests et l'implémentation ❤️

2023-02-13 15:47 UTC, VincentHardouin commented on api/tests/unit/domain/usecases/attach-target-profiles-to-training_test.js
> +    it('should throw a NotFound error', async function () {
Il manque peut-être la notion d'appeler la méthode `findByIds` avec les ids sans doublons

2023-02-13 15:47 UTC, VincentHardouin commented on api/lib/application/trainings/index.js
> +                securityPreHandlers.checkAdminMemberHasRoleSupport,
Le support ne devrait pas avoir le droit de créer 

**suggestion** : retirer le check

2023-02-13 15:56 UTC, VincentHardouin approved these changes

2023-02-13 16:11 UTC, Jeyffrey requested changes

2023-02-13 16:11 UTC, Jeyffrey commented on admin/app/templates/authenticated/trainings/training/target-profiles.hbs
> +      <h2 class="page-section__title">Rattacher un ou plusieurs profil(s) cible(s)</h2>
Problème de style, dans son bloc, ce texte est plutôt un label de l'input, et il est centré.
Là, ça fait bizarre d'avoir l'input esseulé.

https://www.figma.com/file/YOD6plwy3EfJLmC2Let0zV/Pix-admin-V2?node-id=1035%3A15902&t=v9vdpoK1wtMpv98X-4

2023-02-13 16:11 UTC, Jeyffrey commented on admin/app/templates/authenticated/trainings/training/target-profiles.hbs
> +        }}</h2>
Ce titre n'est pas présent dans le design mais je trouve pas plus mal qu'il y soit.

Par contre, dans le design il s'appelle "Profils cibles **associés**"

2023-02-13 16:11 UTC, Jeyffrey commented on admin/app/templates/authenticated/trainings/training/target-profiles.hbs
> +        {{/unless}}
Je me demande si ce serait pas mieux de mettre le `if` au niveau de la `<table />`.
Je trouve que ça n'a pas trop d'intérêt d'avoir le header de la table, alors qu'elle est vide.

2023-02-13 16:11 UTC, Jeyffrey commented on admin/app/controllers/authenticated/trainings/training/target-profiles.js
> +    if (this.isDisabled) return;
```suggestion
    if (this.noTargetProfilesToAttach) return;
```

Plus explicite ?

2023-02-13 16:11 UTC, Jeyffrey commented on admin/app/controllers/authenticated/trainings/training/target-profiles.js
> +          `Le(s) profil(s) cible(s) suivant(s) étai(en)t déjà rattaché(s) à cette organisation : ${duplicatedIds.join(
```suggestion
          `Le(s) profil(s) cible(s) suivant(s) étai(en)t déjà rattaché(s) à ce contenu formatif : ${duplicatedIds.join(
```

2023-02-13 16:11 UTC, Jeyffrey commented on admin/app/styles/components/trainings/training-target-profiles-tab.scss
> +    margin-left: 8px;
```suggestion
    margin-left: $spacing-xs;
```

2023-02-13 16:11 UTC, Jeyffrey commented on admin/app/styles/components/trainings/training-target-profiles-tab.scss
> +    min-width: 300px;
```suggestion
    min-width: 18.75rem;
```

2023-02-14 09:32 UTC, Jeyffrey approved these changes

2023-02-14 10:03 UTC, merged