[TECH] Afficher une erreur 422 au lieu d'une erreur 403 quand Pôle Emploi ne renvoie correctement les infos d'un utilisateur (PIX-6982)
1024pix/pix pull request #5667
Opened 2023-02-15 16:21 UTC by annemarie35

## :unicorn: Problème
> _Décrivez ici le besoin ou l'intention couvert par cette Pull Request._

## :robot: Proposition
> _Ajoutez à cet endroit, si nécessaire, des détails concernant la solution technique retenue et mise en oeuvre, des difficultés ou problèmes rencontrés._

## :rainbow: Remarques
> _Des infos supplémentaires, trucs et astuces ?_

## :100: Pour tester
> _Les instructions pour reproduire le problème, les profils de test, le parcours spécifique à utiliser, etc._

2023-02-17 16:09 UTC, igorissen requested changes

2023-02-17 16:09 UTC, igorissen commented on api/lib/domain/constants.js
> +  },
```suggestion
OIDC_ERRORS: {
      USER_INFO: {
        serviceUnreachable: { shortCode: 'OIDC01', code: 'USER_INFO_SERVICE_UNREACHABLE' },
        missingFields: { shortCode: 'OIDC02', code: 'USER_INFO_MANDATORY_MISSING_FIELD' },
        reponseBadFormatted: { shortCode: 'OIDC03', code: 'USER_INFO_SERVICE_RESPONSE_BAD_FORMATTED' },
      },
  },
```

2023-02-17 16:09 UTC, igorissen commented on api/lib/domain/errors.js
> +  constructor(message = "Des informations obligatoires concernant l'utilisateur sont manquantes.", code, meta) {
```suggestion
  constructor(message = "Mandatory information about the user is missing.", code, meta) {
```

2023-02-17 16:09 UTC, igorissen commented on api/lib/domain/services/authentication/oidc-authentication-service.js
> +      throw new OidcMissingFields(message, error.code, meta);
Retourner une 503 avec une erreur ServiceUnavailableError

2023-02-17 16:09 UTC, igorissen commented on api/lib/domain/services/authentication/oidc-authentication-service.js
> +      throw new OidcMissingFields(message, error.code, meta);
Retourner une 500 avec comme erreur OidcUserInfoFormatError

2023-02-17 16:09 UTC, igorissen commented on api/tests/unit/domain/services/authentication/oidc-authentication-service_test.js
> +        expect(errorResponse).to.be.instanceOf(OidcMissingFields);
ServiceUnavailableError

2023-02-17 16:09 UTC, igorissen commented on api/tests/unit/domain/services/authentication/oidc-authentication-service_test.js
> +        expect(error).to.be.instanceOf(OidcMissingFields);
OidcUserInfoFormatError

2023-02-17 16:09 UTC, igorissen commented on mon-pix/app/routes/authentication/login-oidc.js
> +      const error = new ApiError(apiError.detail, apiError);
Utiliser une factory createJSONApiError pour générer une erreur bien formaté

2023-02-17 16:09 UTC, igorissen commented on mon-pix/app/errors/api-error.js
> +export default class ApiError extends Error {
JSONApiError

2023-02-17 16:09 UTC, igorissen commented on mon-pix/tests/unit/routes/authentication/login-oidc_test.js
> +      // eslint-disable-next-line qunit/require-expect
Rajouter les 2 tests manquants : userinfobadformat et missing fields

2023-02-17 16:09 UTC, igorissen commented on mon-pix/app/routes/error.js
> +        controller.errorStatus += ` (${error.shortCode})`;
Utiliser code au lieu de shortCode

2023-02-17 16:09 UTC, igorissen commented on api/lib/domain/services/authentication/oidc-authentication-service.js
> -      monitoringTools.logErrorWithCorrelationIds({ message: dataToLog });
A garder

2023-02-17 16:09 UTC, igorissen commented on api/lib/domain/services/authentication/oidc-authentication-service.js
> -      monitoringTools.logErrorWithCorrelationIds({ message: dataToLog });
A garder

2023-02-17 16:09 UTC, igorissen commented on api/lib/domain/services/authentication/oidc-authentication-service.js
> -        missingFields: userInfoMissingFields,
Ajouter userInfoContent (autorisation dpo > https://github.com/1024pix/pix/pull/5062)

2023-02-17 17:10 UTC, annemarie35 commented on api/lib/domain/services/authentication/oidc-authentication-service.js
> +      throw new OidcMissingFields(message, error.code, meta);
Les capitaines ne veulent plus de 500  pourquoi retourner une 503 ?

2023-02-17 17:10 UTC, annemarie35 commented on api/lib/domain/services/authentication/oidc-authentication-service.js
> +      throw new OidcMissingFields(message, error.code, meta);
Les capitaines ne veulent plus de 500  pourquoi retourner une 500 ?

2023-02-17 17:10 UTC, annemarie35 commented on api/tests/unit/domain/services/authentication/oidc-authentication-service_test.js
> +        expect(errorResponse).to.be.instanceOf(OidcMissingFields);
Les capitaines ne veulent plus de 500  pourquoi retourner une 5XX ?

2023-02-20 08:25 UTC, igorissen commented on api/lib/domain/services/authentication/oidc-authentication-service.js
> +      throw new OidcMissingFields(message, error.code, meta);
Cette condition ne devrait, en théorie, pas arriver car soit le container n'a plus accès à l'extérieur et donc un problème chez Pix et son hébergement, soit c'est PE qui a un souci avec leur hébergement et donc aucune communication possible.

Dans le premier cas, je pense que les capitaines doivent en être informé. Dans le deuxième cas, je dirais que c'est nous qui pouvons nous en occuper. Par contre, impossible de dissocier les 2 événements, donc autant que les capitaines soient informés.

2023-02-20 08:26 UTC, annemarie35 commented on api/tests/unit/domain/services/authentication/oidc-authentication-service_test.js
> +        expect(error).to.be.instanceOf(OidcMissingFields);
Plutôt rester dans l'idée des missings fields non > je propose `OidcMissingFieldsError` ? 
Le problème de base, qui génère l'appel à cette route userinfo est le fait qu'il manque ces champs oblogatoire
https://github.com/1024pix/pix/commit/3e7bebade1df8520ccf1138213f16f5cd4cebed9

2023-02-20 08:41 UTC, annemarie35 commented on api/lib/domain/services/authentication/oidc-authentication-service.js
> +      throw new OidcMissingFields(message, error.code, meta);
Il y avait des pbs de time out côté pole emploi à un moment et ça ne répondait pas il me semble.
Le ticket est une demande des capitaines, je propose de leur redemander leur besoin.

2023-02-20 08:45 UTC, annemarie35 commented on mon-pix/tests/unit/routes/authentication/login-oidc_test.js
> +      // eslint-disable-next-line qunit/require-expect
Pas utile à mon avis si on change juste errors dans les tests

2023-02-20 11:10 UTC, annemarie35 commented on mon-pix/tests/unit/routes/authentication/login-oidc_test.js
> +        const authenticateStub = sinon.stub().rejects({
idem mais avec l'erreur 400 et une erreur 503 ?

2023-02-20 11:11 UTC, igorissen commented on mon-pix/app/routes/authentication/login-oidc.js
> +      const error = new ApiError(apiError.detail, apiError);
A faire sur un autre ticket tech pour la création de la factory.

2023-02-20 13:57 UTC, igorissen commented on api/lib/domain/services/authentication/oidc-authentication-service.js
> +      throw new OidcMissingFields(message, error.code, meta);
Avec l'accord des capitaines, nous gardons la 503.

2023-02-20 13:58 UTC, igorissen commented on api/lib/domain/services/authentication/oidc-authentication-service.js
> +      throw new OidcMissingFields(message, error.code, meta);
Nous utilisons une 422 pour la gestion de cette erreur avec du monitoring datadog.

2023-02-20 14:24 UTC, igorissen commented on mon-pix/app/routes/error.js
> +        controller.errorStatus += ` (${error.shortCode})`;
On part sur l'utilisation du shortCode comme pour le GAR

2023-02-20 15:43 UTC, igorissen approved these changes

2023-02-22 08:38 UTC, lego-technix reviewed
Je viens de finir une première passe de relecture du code.

2023-02-22 08:38 UTC, lego-technix commented on api/lib/domain/constants.js
> +      missingFields: { shortCode: 'OIDC01', code: 'USER_INFO_MANDATORY_MISSING_FIELDS' },
Il serait préférable que la propriété `USER_INFO.missingFields` et la constante `USER_INFO_MISSING_FIELDS` soient cohérentes et si une erreur est renvoyée, c'est que c'était « mandatory » 😉 :

```suggestion
      missingFields: { shortCode: 'OIDC01', code: 'USER_INFO_MISSING_FIELDS' },
```

2023-02-22 08:38 UTC, lego-technix commented on api/lib/domain/errors.js
> +  constructor(message = 'Mandatory information about the user is missing.', code, meta) {
Il serait préférable que le message porte aussi le fait qu'il s'agit d'une erreur dans le contexte OIDC :
```suggestion
  constructor(message = 'Mandatory information returned by the identify provider about the user is missing.', code, meta) {
```

2023-02-22 12:32 UTC, annemarie35 commented on api/lib/domain/constants.js
> +      missingFields: { shortCode: 'OIDC01', code: 'USER_INFO_MANDATORY_MISSING_FIELDS' },
Done

2023-02-22 12:35 UTC, annemarie35 commented on api/lib/domain/errors.js
> +  constructor(message = 'Mandatory information about the user is missing.', code, meta) {
Done

2023-02-22 12:45 UTC, annemarie35 reviewed
Revue fonctionnelle OK pour moi, je suis repassé par les 3 cas d'erreurs

2023-02-22 13:29 UTC, lego-technix requested changes
J'ai encore mis 2 tout petits commentaires par rapport au code.

Enfin j'ai testé fonctionnellement et il y a cette dernière chose : nous avions dit lors de la relecture en mob ainsi qu'avec les captains que le cas `if (!userInfoContent || typeof userInfoContent !== 'object')` impliquait que le service OIDC du fournisseur d'accès était manifestement en erreur et que cela touchait tous les utilisateurs et non pas uniquement un utilisateur et donc que tout le monde voulait en être averti et qu'il fallait donc que ce cas renvoie une `5XX`. Or dans l'état actuel de la PR le code renvoyé pour ce cas est `422`, ce qui ne correspond donc pas à nos dernières discussions. Ou bien ai-je manqué quelque chose ?

2023-02-22 13:29 UTC, lego-technix commented on api/lib/domain/services/authentication/oidc-authentication-service.js
>      const userInfoMissingFields = this.userInfoMissingFields({ userInfoContent });
Même si ce n'est pas cette PR qui est à l'origine du nom de la méthode, on gagnerait en lisibilité du code à renommer dans cette PR le nom de la méthode `userInfoMissingFields` en `getUserInfoMissingFields` qui commence par un verbe :
```suggestion
    const userInfoMissingFields = this.getUserInfoMissingFields({ userInfoContent });
```

2023-02-22 13:29 UTC, lego-technix commented on api/lib/domain/services/authentication/oidc-authentication-service.js
>        const message = 'Une erreur est survenue en récupérant les informations des utilisateurs.';
Ici ne sont récupéré que les informations pour 1 utilisateur et pour être cohérent avec les autres messages on gagnerait à modifier le message d'erreur :

```suggestion
      const message = 'Une erreur est survenue en récupérant les informations utilisateur.';
```

2023-02-22 14:36 UTC, annemarie35 commented on api/lib/domain/services/authentication/oidc-authentication-service.js
>      const userInfoMissingFields = this.userInfoMissingFields({ userInfoContent });
> le service OIDC du fournisseur d'accès était manifestement en erreur et que cela touchait tous les utilisateurs

Non pas tous les utilisateurs, seulement ceux qui quand on décode le token renvoyé par pole emploi, n'ont pas les élements requis (family name, etc.)
Vu que l'appel à userInfo n'est fait par défaut mais seulement dans ce cas précis (qui ne touche que pole emploi il me semble).
J'ai pas d'avis sur la question.

2023-02-22 14:38 UTC, annemarie35 commented on api/lib/domain/services/authentication/oidc-authentication-service.js
>        const message = 'Une erreur est survenue en récupérant les informations des utilisateurs.';
Je fais la modif

2023-02-22 14:58 UTC, ebarbier commented
Merci de rajouter une variable pour afficher le nom du fournisseur d'identité dans les messages d'erreur.
Exemple: “Un ou des champs obligatoires (${userInfoMissingFields}) n’ont pas été renvoyés par votre fournisseur d’identité ${nom du fournisseur d’identité}. Merci!

2023-02-22 16:18 UTC, lego-technix approved these changes

2023-02-22 16:36 UTC, merged