[CHORE] Aligner les en-tête et le contenu sur le tableau de la page des prescrits (PIX-7247)
1024pix/pix pull request #5728
Opened 2023-02-23 14:46 UTC by Alexandre-Monney

## :unicorn: Problème
Sur la page participants/étudiants/élèves, il y a actuellement plusieurs types de comportement dans les colonnes du tableau : justifié à gauche, à droite, ou centré.

## :robot: Proposition
Dans le tableau de la liste des prescrits (étudiants/élèves/participants) d’une orga, justifier le contenu de toutes les colonnes à gauche (c’est bien le cas pour les tableaux des autres pages, liste des campagnes ou activité/résultats d’une campagne par exemple)

## :rainbow: Remarques
> _Des infos supplémentaires, trucs et astuces ?_

## :100: Pour tester

- Aller sur Pix Orga : (Pour les 3 types d'orga).
- Aller sur la page élèves/étudiants/participants.
- Vérifier que l'alignement sur les en-tête et le contenu du tableau des prescrits soit à gauche

2023-02-27 14:08 UTC, xav-car approved these changes

2023-02-28 16:21 UTC, yaelle6 commented
je trouve que ca fait bizarre d'avoir la date de naissance justifiée à gauche et la date de dernière participation justifiée au centre. On pourrait homogénéiser. (j'ai une prèf quand c'est justifié à gauche )

2023-03-01 09:35 UTC, yaelle6 approved these changes
ok 👍

2023-03-01 10:57 UTC, aurelie-crouillebois requested changes, later dismissed
Le titre de la colonne "Certificabilité" doit être centré comme son contenu.
Faire en sorte que Header et HeaderSort réagissent comme attendu sur la propriété align.

2023-03-01 10:57 UTC, aurelie-crouillebois commented on orga/app/styles/pages/authenticated/organization-participants.scss
> +    text-align: center;
L'alignement ne doit pas être géré via CSS à ce niveau là, mais utilisant l'attribut "align" dans le HeaderSort associé (ParticipationCount).
Vérifier le padding-left à 0.
Renommer la classe si elle doit continuer à exister -> participationCount

2023-03-01 12:49 UTC, Alexandre-Monney commented on orga/app/styles/pages/authenticated/organization-participants.scss
> +    text-align: center;
Ajout du @align dans le HeaderSort. Et Suppression de cette class dans le hbs & scss.

2023-03-01 13:14 UTC, frinyvonnick commented on orga/app/styles/pages/authenticated/sup-organization-participants/list.scss
> +    justify-content: center;
Il faudrait passer le "display: flex;" en "display: inline-flex;" pour que le @align sur Table::Header fonctionne correctement.

2023-03-01 13:14 UTC, frinyvonnick approved these changes

2023-03-01 13:23 UTC, Alexandre-Monney commented on orga/app/styles/pages/authenticated/sup-organization-participants/list.scss
> +    justify-content: center;
👍

2023-03-01 14:45 UTC, merged