[FEATURE] Ajout d'un feature togglepour l'envoie des données à PoleEmploi (PIX-7016).
1024pix/pix pull request #5732
Opened 2023-02-24 11:36 UTC by ajoanny

## :unicorn: Problème
L'envoie des données à Pole emploi à la volé est source de beaucoup d'erreur à cause de la gestion du token.

## :robot: Proposition
Ne plus faire les envoie des résultats de campagne à Pole emploi à la volé mais faire en sorte que Pole emploi puisse les récupérer via des requêtes API.
La fonctionnalité est en phase de développement et on veut pouvoir activer/désactiver la fonctionnalité pendant l'execution.
Pour pouvoir faire ça on pas sur un feature toggle.

## :rainbow: Remarques
> _Des infos supplémentaires, trucs et astuces ?_

## :100: Pour tester
Mettre la variable d'env PUSH_DATA_TO_POLE_EMPLOI_ENABLED à true ou false pour activier ou désactivé l"envoie.
Vérifier que le données ont été envoyées à PE en cas d'activation de la feature et qu'elles sont juste en registrées en BDD en cas de désactivation.

2023-03-01 10:36 UTC, aurelie-crouillebois requested changes
Vérifier le linter et corriger le config.js

2023-03-01 10:36 UTC, aurelie-crouillebois commented on api/lib/config.js
> +    config.poleEmploi.pushEnabled = 'true';
true sans quotes

2023-03-01 10:36 UTC, aurelie-crouillebois commented on api/sample.env
> +# Authorize to push campaign results to pole emploi
```suggestion
# Enable to push campaign results to pole emploi
```

2023-03-01 10:36 UTC, aurelie-crouillebois commented on api/tests/integration/domain/usecases/send-shared-participation-results-to-pole-emploi_test.js
> +const poleEmploiNotifier = require('../../../../lib/infrastructure/externals/pole-emploi/pole-emploi-notifier.js');
WTF linter/prettier conf

2023-03-02 10:01 UTC, frinyvonnick commented on api/lib/domain/events/index.js
> +  }
```suggestion
const disabledPoleEmploiNotifier = require('../../infrastructure/externals/pole-emploi/disabled-pole-emploi-notifier.js');

function requirePoleEmploiNotifier() {
  if (settings.poleEmploi.pushEnabled) {
    return poleEmploiNotifier;
  } else {
    return disabledPoleEmploiNotifier;
  }
```

2023-03-02 10:01 UTC, frinyvonnick commented on api/lib/domain/usecases/index.js
> +    return disablePoleEmploiNotifier;
```suggestion
const poleEmploiNotifier = require('../../infrastructure/externals/pole-emploi/pole-emploi-notifier.js');
const disabledPoleEmploiNotifier = require('../../infrastructure/externals/pole-emploi/disabled-pole-emploi-notifier.js');

function requirePoleEmploiNotifier() {
  if (settings.poleEmploi.pushEnabled) {
    return poleEmploiNotifier;
  } else {
    return disabledPoleEmploiNotifier;
```

2023-03-02 10:02 UTC, frinyvonnick commented on api/tests/integration/domain/usecases/send-shared-participation-results-to-pole-emploi_test.js
> +const poleEmploiNotifier = require('../../../../lib/infrastructure/externals/pole-emploi/pole-emploi-notifier.js');
Pourquoi on a encore le changement du .js ici ?

2023-03-02 11:02 UTC, frinyvonnick approved these changes

2023-03-02 11:04 UTC, aurelie-crouillebois approved these changes

2023-03-02 12:19 UTC, merged