[BUGFIX][ADMIN] Augmenter la taille maximale pour le logo d'une organisation à 2,5Mo (PIX-7326)
1024pix/pix pull request #5774
Opened 2023-03-06 16:01 UTC by igorissen

## :unicorn: Problème
> _Décrivez ici le besoin ou l'intention couvert par cette Pull Request._

## :robot: Proposition
> _Ajoutez à cet endroit, si nécessaire, des détails concernant la solution technique retenue et mise en oeuvre, des difficultés ou problèmes rencontrés._

## :rainbow: Remarques
> _Des infos supplémentaires, trucs et astuces ?_

## :100: Pour tester
> _Les instructions pour reproduire le problème, les profils de test, le parcours spécifique à utiliser, etc._

2023-03-07 14:32 UTC, reibecca commented
Tests fonctionnels ok en locale mais pas sur la RA. L'upload de l'image dépassant les 2,5 Mo fonctionne 🤔

2023-03-07 14:51 UTC, reibecca commented on admin/app/controllers/authenticated/organizations/get.js
> +      this.notifications.error(ERROR_MESSAGES[status || 'default'], { autoClear: false });
question : à quoi correspond le `autoClear: false`?

2023-03-07 14:56 UTC, reibecca commented on admin/tests/unit/controllers/authenticated/organizations/get_test.js
> +  module('#updateOrganizationInformation', function () {
suggestion : on pourrait aussi tester le cas de succès et vérifier que le bon message s'affiche

2023-03-07 15:50 UTC, igorissen commented on admin/app/controllers/authenticated/organizations/get.js
> +      this.notifications.error(ERROR_MESSAGES[status || 'default'], { autoClear: false });
C'est pour désactiver le timer qui fermera la notification automatiquement après x secondes.

2023-03-07 15:50 UTC, igorissen commented on admin/tests/unit/controllers/authenticated/organizations/get_test.js
> +  module('#updateOrganizationInformation', function () {
Oui on peut.

2023-03-07 17:03 UTC, reibecca commented on admin/app/controllers/authenticated/organizations/get.js
> +      this.notifications.error(ERROR_MESSAGES[status || 'default'], { autoClear: false });
Oh ok merci !

2023-03-08 09:32 UTC, igorissen commented
> Tests fonctionnels ok en locale mais pas sur la RA. L'upload de l'image dépassant les 2,5 Mo fonctionne 🤔

@reibecca je viens de faire le test sur la RA, et j'ai bien reçu la notification.
Par contre, le front affiche l'image mais la retire une fois que la requête s'est terminée en erreur (donc affichage de la notification)

2023-03-09 17:31 UTC, reibecca approved these changes

2023-03-09 18:34 UTC, lego-technix requested changes

2023-03-09 18:34 UTC, lego-technix commented on admin/app/controllers/authenticated/organizations/get.js
> +};
Étant donné que la `PayloadTooLargeError` envoie bien l'info `maxSize` il serait vraiment plus propre de l'exploiter dans le message d'erreur affiché à l'utilisateur plutôt que de mettre ça en dur.

2023-03-09 18:34 UTC, lego-technix commented on api/lib/application/organizations/index.js
> +                maxSize: '2.5',
`maxSize_in_megabytes` plutôt pour faciliter la génération du message à l'utilisateur.

2023-03-09 18:34 UTC, lego-technix commented on admin/app/controllers/authenticated/organizations/get.js
> +};
Utiliser le mécanisme d'i18n pour la valeur du message. Ce n'est pas un travail plus difficile car il suffit d'écrire le message uniquement dans `fr.json`, pas besoin de mettre les traductions dans les autres langues.

2023-03-09 18:35 UTC, lego-technix commented on api/lib/application/organizations/index.js
> +                maxSize: '2.5',
:heart:

2023-03-10 11:35 UTC, lego-technix approved these changes

2023-03-10 12:41 UTC, merged