fix(mon-pix): improve feedpack-panel style
1024pix/pix pull request #5840
Opened 2023-03-21 14:49 UTC by Jeyffrey

## :unicorn: Problème
> _Décrivez ici le besoin ou l'intention couvert par cette Pull Request._

## :robot: Proposition
> _Ajoutez à cet endroit, si nécessaire, des détails concernant la solution technique retenue et mise en oeuvre, des difficultés ou problèmes rencontrés._

## :rainbow: Remarques
> _Des infos supplémentaires, trucs et astuces ?_

## :100: Pour tester
> _Les instructions pour reproduire le problème, les profils de test, le parcours spécifique à utiliser, etc._

2023-03-23 12:17 UTC, VincentHardouin approved these changes

2023-03-23 14:29 UTC, clarissedmn commented
Je viens de remarquer que quand on a déjà signalé un problème et qu'on ferme puis réouvre le bouton, le formulaire est reset.

2023-03-23 14:31 UTC, Jeyffrey commented
Oui c'est reset à chaque ouverture / fermeture.
Ça te semble bizarre si on a déjà fait une soumission ?

2023-03-23 14:33 UTC, clarissedmn commented
Oui je trouve ça un peu bizarre mais c'est un comportement qu'on avait déjà ! Je sais pas si c'est voulu :)

2023-03-23 14:38 UTC, Jeyffrey commented
Je pense que si on veut palier à ça, ça irait avec un petit changement d'UX.
En ajoutant un bouton "Faire une nouvelle demande", ou un truc du genre.

2023-03-23 17:09 UTC, yannbertrand requested changes

2023-03-23 17:09 UTC, yannbertrand commented on mon-pix/app/styles/components/_feedback-panel.scss
>  }
Y'a des chances que ça corrige une erreur de l'audit :)

2023-03-23 17:09 UTC, yannbertrand commented on mon-pix/tests/acceptance/compare-answer-solution-qroc_test.js
> +      assert.dom('.pix-modal__overlay--hidden .comparison-window').exists();
Pourquoi le test change ?

2023-03-23 17:09 UTC, yannbertrand commented on mon-pix/app/styles/components/_feedback-panel.scss
> -  margin-top: 16px;
Est utile dans le contexte où le composant est affiché dans une épreuve

![image](https://user-images.githubusercontent.com/5855339/227280968-9f18b658-6729-4962-a1fa-4a7f45ddec20.png)

2023-03-23 17:09 UTC, yannbertrand commented on mon-pix/app/components/comparison-window.hbs
> +    {{#if @showModal}}
Top pour reset le form 👍

2023-03-24 08:34 UTC, Jeyffrey commented on mon-pix/tests/acceptance/compare-answer-solution-qroc_test.js
> +      assert.dom('.pix-modal__overlay--hidden .comparison-window').exists();
En fait il était plus valable.
La classe ".comparison-window" n'était plus dans le DOM, mais je l'ai ajoutée https://github.com/1024pix/pix/pull/5840/files#diff-29c8bd3ab154eff7ad06296086bbdbdfc003b7d03bdfa7f806c10af5a5382dae.

2023-03-24 08:35 UTC, Jeyffrey commented on mon-pix/app/styles/components/_feedback-panel.scss
> -  margin-top: 16px;
Ah yes, je vais faire un style spécifique pour cet écran alors !
Bien vu 🧐

2023-03-24 08:43 UTC, yannbertrand commented on mon-pix/app/styles/components/_feedback-panel.scss
> -  margin-top: 16px;
Ça semble être les deux seuls usages du composant donc on doit être safe après ça ;) 

![image](https://user-images.githubusercontent.com/5855339/227468844-98581f1f-6f11-4422-ace0-3acd5510b873.png)

2023-03-24 08:47 UTC, Jeyffrey commented on mon-pix/app/styles/components/_feedback-panel.scss
> -  margin-top: 16px;
J'ai ajouté du style dans `_challenge.scss`

2023-03-24 09:48 UTC, yannbertrand approved these changes
C'est beau

2023-03-24 10:43 UTC, merged