:recycle: Remove domain transaction from usecase
1024pix/pix pull request #5867
Opened 2023-03-24 15:44 UTC by mcampourcy

## :unicorn: Problème
> _Décrivez ici le besoin ou l'intention couvert par cette Pull Request._

## :robot: Proposition
> _Ajoutez à cet endroit, si nécessaire, des détails concernant la solution technique retenue et mise en oeuvre, des difficultés ou problèmes rencontrés._

## :rainbow: Remarques
> _Des infos supplémentaires, trucs et astuces ?_

## :100: Pour tester
> _Les instructions pour reproduire le problème, les profils de test, le parcours spécifique à utiliser, etc._

2023-03-24 15:49 UTC, frinyvonnick commented
Reste à faire : 
- Modifier les 5 autres usecases qui utilise assessmentRepository.save, certificationCourseRepository.save et certificationCourseRepository.findOneCertificationCourseByUserIdAndSessionId
- Créer un autre DomainTransaction avec notre implémentation pour pas impacter les autres usages

2023-03-31 13:07 UTC, frinyvonnick commented
Actuel : 
<img width="644" alt="image" src="https://user-images.githubusercontent.com/13099512/229128144-2f00afc9-c3a2-4639-98d7-70cc6a0d7535.png">
Etape transitoire pour la migration : 
<img width="713" alt="image" src="https://user-images.githubusercontent.com/13099512/229128225-4b6856be-2ee0-4b1c-98a6-8555bff5706c.png">
Cible : 
<img width="714" alt="image" src="https://user-images.githubusercontent.com/13099512/229128263-8fe287d2-b7ba-4c98-b800-c28bcd9234b9.png">

2023-06-20 07:36 UTC, octo-topi requested changes, later dismissed
Mais... la transaction est une notion métier, non ?
C'est ce que cet ADR laisse penser en tout cas
https://github.com/1024pix/pix/blob/dev/docs/adr/0009-transaction-metier.md

Pourquoi pas changer de stratégie, mais dans ce cas pour ne pas perdre la connaissance, une mise à jour des raisons dans l'ADR est incontournable IMHO

2023-06-20 11:06 UTC, frinyvonnick commented
> Mais... la transaction est une notion métier, non ? C'est ce que cet ADR laisse penser en tout cas https://github.com/1024pix/pix/blob/dev/docs/adr/0009-transaction-metier.md
> 
> Pourquoi pas changer de stratégie, mais dans ce cas pour ne pas perdre la connaissance, une mise à jour des raisons dans l'ADR est incontournable IMHO

La notion de transaction est purement SQL et lié à l'implémentation de notre repositories qui utilise une base données relationnel. Par exemple si on changeait demain pour une base de données SQL cette notion n'aurait plus aucune raison d'exister. Ce qui montre bien que c'est une problématique technique et non métier. 

Le [red book(Implementing Domain Driven Design)](https://www.eyrolles.com/Informatique/Livre/implementing-domain-driven-design-9780321834577/) en parle beaucoup mieux que moi dans son chapitre "Repositories" dans la sous partie "Managing transaction" :

"The domain model and its encompassing Domain Layer is never the correct place to manage transactions. The operations associated with a model are usually too fine grained to themselves manage transactions and shouldn’t be aware that transactions play a part in their life cycle. If you are to avoid plac- ing transactional concerns in the model, just where do they belong?
A common architectural approach to facilitating transactions on behalf of persistence aspects of the domain model is to manage them in the Application Layer (14). Generally, we create one Facade [Gamma et al.] there for each major use case grouping addressed by the application/system. The Facade is designed with coarse-grained business methods, usually one for each use case flow (which may be limited to one for a given use case). Each such business method coordinates a task as required by the use case. When a Facade’s busi- ness method is invoked by the User Interface Layer (14), whether on behalf of a human or another system, the business method begins a transaction and then acts as a client to the domain model. After all necessary interaction with the domain model is successfully completed, the Facade’s business method commits the transaction it started. If an error/exception occurs that prevents completion of the use case task, the transaction is rolled back by the same managing business method.
The transaction may be managed declaratively or explicitly by developer code. Whether or not your transactions are declarative or user managed, what I have described here logically works as follows:"
```java
public class SomeApplicationServiceFacade {
    ...
    public void doSomeUseCaseTask()  {
        Transaction transaction = null;
        try {
            transaction = this.session().beginTransaction();
            // use the domain model ...
            transaction.commit();
        } catch (Exception e) {
            if (transaction != null) {
              transaction.rollback();
            }
        }
    }
}
```

Ce qu'on voit c'est que la Facade dont ils parlent correspond à nos controllers actuellement.

@ajoanny avait aussi commencé des travaux dans l'idée de ne plus avoir à passer les transactions au niveau de la couche domaine ici https://github.com/1024pix/pix/pull/3231

Dans cette PR avec @mcampourcy, on essaye de faire un POC qu'on pourra présenter en MEJ quand il sera fonctionnel et qu'on sera satisfait de la Developper Experience. Idéalement, on aura aussi réfléchi à la transition 😄 

Est ce que ça répond à tes interrogations @octo-topi ?

2023-07-26 06:49 UTC, HEYGUL commented
> Mais... la transaction est une notion métier, non ? C'est ce que cet ADR laisse penser en tout cas [`dev`/docs/adr/0009-transaction-metier.md](https://github.com/1024pix/pix/blob/dev/docs/adr/0009-transaction-metier.md?rgh-link-date=2023-06-20T07%3A36%3A31Z)
> 
> Pourquoi pas changer de stratégie, mais dans ce cas pour ne pas perdre la connaissance, une mise à jour des raisons dans l'ADR est incontournable IMHO

Je plussois.
Lors de l'introduction de la `DomainTransaction`, l'idée était de regrouper au sein d'une transaction unique les actions métiers.
Le nommage peut porter à confusion avec la transaction SQL sous-jacente.
Plutôt que de supprimer la notion de `DomainTransaction`, je suis partisan de la renommer.

2023-09-27 12:05 UTC, frinyvonnick commented
> > Mais... la transaction est une notion métier, non ? C'est ce que cet ADR laisse penser en tout cas [`dev`/docs/adr/0009-transaction-metier.md](https://github.com/1024pix/pix/blob/dev/docs/adr/0009-transaction-metier.md?rgh-link-date=2023-06-20T07%3A36%3A31Z)
> > Pourquoi pas changer de stratégie, mais dans ce cas pour ne pas perdre la connaissance, une mise à jour des raisons dans l'ADR est incontournable IMHO
> 
> Je plussois. Lors de l'introduction de la `DomainTransaction`, l'idée était de regrouper au sein d'une transaction unique les actions métiers. Le nommage peut porter à confusion avec la transaction SQL sous-jacente. Plutôt que de supprimer la notion de `DomainTransaction`, je suis partisan de la renommer.

J'avais oublié de répondre ici suite à notre conversation. En résumé : 
- La notion continue d'exister
- On n'a plus à passer la référence de la transaction en cours dans la couche domain

2023-12-18 08:38 UTC, yaf commented
Et du coup cette PR qui semblait être un POC a besoin d'être finaliser pour être mergé ou bien on la supprime ? :shrug: 

Je partage l'envie d'avoir à minima une nouvelle ADR avec les agruments qui ont été avancé ici (voir un lien depuis une ADR vers cette PR) :pencil2: 

Mais peut-être faut-il aussi faire une première implémentation ?

Je débarque un peu dans la conversation, mais un truc m'échappe en regardant le code : pourquoi démarrer la transaction dans la couche application ? Comme tu le dis @aceol, c'est un truc de DB, donc de repository il me semble. :thinking:

2023-12-18 10:29 UTC, frinyvonnick commented
Oui je voudrais finir l'implémentation. Le code a changé depuis que j'ai fait ça et je n'ai pas trouvé le temps de le corriger. 

> Je débarque un peu dans la conversation, mais un truc m'échappe en regardant le code : pourquoi démarrer la transaction dans la couche application ? Comme tu le dis @aceol, c'est un truc de DB, donc de repository il me semble. 🤔

Pourquoi on ne démarre pas la transaction dans le repository, c'est parce que il n'y a pas de 1 pour 1 entre usecase et repository. Souvent, on a plusieurs repository. On a aussi des cas où la couche application appelle deux usecases à la suite avec la nécessité qu'ils soient éxecuté dans le cadre d'une même transaction. 

> Je partage l'envie d'avoir à minima une nouvelle ADR avec les agruments qui ont été avancé ici (voir un lien depuis une ADR vers cette PR) ✏️

Oui, c'est prévu. Comme expliqué dans un message plus haut, je souhaiterais d'abord faire une MEJ + réfléchir à la phase de migration 😄

2024-02-13 16:42 UTC, frinyvonnick commented
J'ai enlevé le tag cross-team parce que pour le moment je rebascule le sujet côté Prescription (j'ai déplacé le code dans notre bounded context) en attendant de faire de la documentation (un ADR ?) et une MEJ 😄

2024-02-14 10:55 UTC, xav-car commented on api/src/prescription/shared/infrastructure/ApplicationTransaction.js
> +  static async execute(func) {
**thought** : ajouter un paramètre pour personnaliser la transaction

2024-02-14 11:08 UTC, xav-car commented on api/src/prescription/campaign-participation/infrastructure/repositories/campaign-participation-repository.js
> +  const knexConn = ApplicationTransaction.getConnection(domainTransaction);
**suggestion** Vérifier que le update et le get sont utilisé avec des domainTransaction

2024-02-14 11:11 UTC, xav-car approved these changes

2024-02-14 13:32 UTC, frinyvonnick commented on api/src/prescription/campaign-participation/infrastructure/repositories/campaign-participation-repository.js
> +  const knexConn = ApplicationTransaction.getConnection(domainTransaction);
Le get est utilisé dans les usecases : 
- startCampaignParticipation
- beginCampaignParticipationImprovement

2024-02-14 13:32 UTC, frinyvonnick commented on api/src/prescription/campaign-participation/infrastructure/repositories/campaign-participation-repository.js
> +  const knexConn = ApplicationTransaction.getConnection(domainTransaction);
le update est utilisé dans : 
- beginCampaignParticipationImprovement

2024-02-14 13:40 UTC, merged