[FEATURE] Afficher les domaines de compétences sur la page de fin de campagne sur Pix-App (PIX-7012)
1024pix/pix pull request #5923
Opened 2023-04-03 16:17 UTC by clarissedmn

## :unicorn: Problème
Les domaines des compétences n'étaient pas affichés sur la page de fin de campagne.

## :robot: Proposition
Afficher les domaines avec leur couleur associé.

## :rainbow: Remarques
Le titre a été changé en "Détails des résultats".
Le caption a été modifié pour apporté davantage d'informations.

## :100: Pour tester
- Aller sur la RA
- Passer une campagne avec pallier `PROBADGE1`
- Vérifier que domaines sont bien affichés sur les résultats par compétences.

2023-04-04 14:57 UTC, VincentHardouin commented on mon-pix/app/components/routes/campaigns/assessment/skill-review.js
> +    }
Je propose d'utiliser `reduce` et de simplifier un peu le code. Je n'ai pas essayé mais l'idée serait qelque chose comme ça : 
```javascript
const competenceResultsGroupedByAreas = competenceResults.reduce((acc, competenceResult) => {
  const currentArea = competenceResult.areaName;
  const competence = {
    name: competenceResult.name,
    reachedStage: competenceResult.reachedStage,
    masteryRate: competenceResult.masteryRate,
  };
  if (acc[currentArea]) {
    acc[currentArea].competences.push(competence);
  } else {
    acc[currentArea] = {
      areaName: currentArea,
      areaColor: competenceResult.areaColor,
      competences: [competence],
    };
  }
  return acc;
}, {});
```

2023-04-05 08:32 UTC, clarissedmn commented on mon-pix/app/components/routes/campaigns/assessment/skill-review.js
> +    }
Top ça marche ! C'est plus propre 👍

2023-04-05 09:43 UTC, yannbertrand commented on mon-pix/app/styles/pages/_skill-review.scss
> +      @extend %pix-body-l;
👍

2023-04-05 09:44 UTC, yannbertrand commented on mon-pix/app/styles/pages/_skill-review.scss
> +      font-weight: $font-medium;
Je suggère

```suggestion
      @extend %pix-weight-medium;
```

Mais peut être que c'est moins bien ?

2023-04-05 09:45 UTC, yannbertrand commented on mon-pix/app/styles/pages/_skill-review.scss
> +    h3 {
Pas possible d'utiliser une classe plutôt ?

2023-04-05 09:45 UTC, yannbertrand commented on mon-pix/app/styles/pages/_skill-review.scss
>    &__table {
Les lignes du tableau `tr` sont trop hautes 58px sans zoom textuel, contre 48px sur les maquettes.

2023-04-05 09:49 UTC, yannbertrand commented on mon-pix/app/styles/pages/_skill-review.scss
>    &__table {
Peut être que ça sera corrigé avec la v30.0.0 de Pix UI ?

https://github.com/1024pix/pix-ui/pull/376

2023-04-05 09:56 UTC, yannbertrand commented
Je ne pense pas que ce soit bloquant (et je me rappelle plus ce qu'on s'était dit par rapport à ça) mais on n'a plus tout à fait le même design sur les puces devant les domaines. À voir quand est-ce qu'on le traite

2023-04-05 11:58 UTC, VincentHardouin commented on mon-pix/app/components/routes/campaigns/assessment/skill-review.js
> +    }
Globalement c'est dommage que cette logique soit dans le front

2023-04-05 12:13 UTC, yannbertrand commented on mon-pix/app/components/routes/campaigns/assessment/skill-review.js
> +  }
On peut pas faire ça côté API ?

2023-04-05 12:15 UTC, yannbertrand commented on mon-pix/app/styles/pages/_skill-review.scss
> +    font-family: $font-open-sans;
```suggestion
```

Pas besoin, c'est déjà dans `%pix-title-s`.

2023-04-05 12:20 UTC, clarissedmn commented on mon-pix/app/components/routes/campaigns/assessment/skill-review.js
> +  }
Ce serait plus propre mais ça mérite une plus grosse refacto pour modifier notre gestion des CompetenceResult dans toutes les sortes de campagne !

2023-04-05 12:21 UTC, yannbertrand commented
Visiblement, on ne récupère pas les traductions des domaines.

![image](https://user-images.githubusercontent.com/5855339/230078799-2eff113a-1bc3-47f7-8aa2-637b4eef3eaa.png)

2023-04-05 12:35 UTC, Jeyffrey commented on mon-pix/app/styles/pages/_skill-review.scss
> +      font-weight: $font-medium;
Le premier est plus explicite je trouve

2023-04-05 12:41 UTC, clarissedmn commented on mon-pix/app/styles/pages/_skill-review.scss
>    &__table {
Je vois bien 48px (3rem) de mon côté 🤔 
```
 tr {
      height: 3rem;
      background-color: $pix-neutral-5;

      & + tr {
        border-top: $pix-spacing-xs solid $pix-neutral-0;
      }
    }
```

2023-04-05 12:51 UTC, clarissedmn commented on mon-pix/app/styles/pages/_skill-review.scss
> +      font-weight: $font-medium;
Apparement, c'est plutôt %pix-body-weight-medium ! Je ne sais pas si la doc de storybook n'est pas à jour

2023-04-05 13:00 UTC, Jeyffrey requested changes

2023-04-05 13:00 UTC, Jeyffrey commented on mon-pix/app/styles/pages/_skill-review.scss
> +  }
La bordure est plus épaisse et haute dans le [design Figma](https://www.figma.com/file/y6p1FS5HKhJkMLrJN4i90P/Pix-App?node-id=3907-74984&t=86ySdTc5DsSwcTGy-4)

2023-04-05 13:00 UTC, Jeyffrey commented on mon-pix/app/components/routes/campaigns/assessment/skill-review.hbs
> +                <h3>{{area}}</h3>
On a plus le numéro dans ce titre dans le design Figma. 
Mais ça vient du référentiel il me semble...

2023-04-05 13:00 UTC, Jeyffrey commented on mon-pix/app/styles/pages/_skill-review.scss
> +      font-weight: $font-medium;
🙏 ne pas utiliser de placeholder / mixin si c'est juste pour remplacer une variable.

Avec un placeholder, quelqu'un qui découvre le code sera obligé d'aller voir ce qui se cache derrière.
Ça vaut le coup uniquement pour éviter d'écrire plusieurs lignes qui vont ensemble (font-size, weight, line-height, ...)

2023-04-05 13:00 UTC, Jeyffrey commented on mon-pix/app/styles/pages/_skill-review.scss
>    &__table {
Yes mais pour l'instant on a 58px 
![image](https://user-images.githubusercontent.com/7335131/230086844-a406ca24-77f1-4575-b2c1-2862223e727b.png)

2023-04-05 13:00 UTC, Jeyffrey commented on mon-pix/app/components/routes/campaigns/assessment/skill-review.hbs
> +            <div class="skill-review-competence-stages-result__content">
Ne devrait-on pas avoir des `ul/ol + li` à ce niveau là vu qu'on est dans une liste ?

2023-04-05 13:02 UTC, clarissedmn commented on mon-pix/app/styles/pages/_skill-review.scss
>    &__table {
Ah yes !! Je viens de regarder c'est à caude des étoiles :)

2023-04-05 13:10 UTC, clarissedmn commented on mon-pix/app/components/routes/campaigns/assessment/skill-review.hbs
> +                <h3>{{area}}</h3>
Yes c'est ça !

2023-04-05 13:12 UTC, clarissedmn commented on mon-pix/app/components/routes/campaigns/assessment/skill-review.hbs
> +            <div class="skill-review-competence-stages-result__content">
Pourquoi pas ! Après ça me parait bizarre car il faudrait mettre tous les domaines titres et les tableaux dans un `li`

2023-04-05 13:18 UTC, clarissedmn commented on mon-pix/app/components/routes/campaigns/assessment/skill-review.hbs
> +            <div class="skill-review-competence-stages-result__content">
Je suis d'avis de plutôt rester comme tel

2023-04-05 13:20 UTC, Jeyffrey commented on mon-pix/app/components/routes/campaigns/assessment/skill-review.hbs
> +            <div class="skill-review-competence-stages-result__content">
C'est toi qui vois !

2023-04-05 14:31 UTC, yannbertrand commented on mon-pix/app/components/routes/campaigns/assessment/skill-review.js
> +  }
Ouais ok. Je propose de refaire du clean là dessus quand tous les PC auront des paliers, ça sera des RG plus simples.

2023-04-05 14:32 UTC, yannbertrand commented on mon-pix/app/styles/pages/_skill-review.scss
> +      font-weight: $font-medium;
Du coup autant virer ces placeholders de weight non ?

2023-04-05 16:20 UTC, yannbertrand approved these changes
OK pour moi ⭐

2023-04-06 13:02 UTC, Jeyffrey approved these changes

2023-04-06 13:41 UTC, merged