[FEATURE] Pour un user qui se connecte à Pix Orga via invitation, si le cookie de la locale est dispo, alors enregistrer cette locale (PIX-7407)
1024pix/pix pull request #5944
Opened 2023-04-06 16:33 UTC by reibecca

## :unicorn: Problème
> _Décrivez ici le besoin ou l'intention couvert par cette Pull Request._

## :robot: Proposition
> _Ajoutez à cet endroit, si nécessaire, des détails concernant la solution technique retenue et mise en oeuvre, des difficultés ou problèmes rencontrés._

## :rainbow: Remarques
> _Des infos supplémentaires, trucs et astuces ?_

## :100: Pour tester
> _Les instructions pour reproduire le problème, les profils de test, le parcours spécifique à utiliser, etc._

2023-04-11 08:48 UTC, lego-technix commented on api/lib/domain/usecases/accept-organization-invitation.js
> +    if (user.mustBePersisted) {
La propriété `mustBePersisted` a été introduite dans #5914, mais avec du recul elle gagnerait à être renommée de manière plus descriptive qu'impérative en `hasBeenModified` :

```suggestion
    if (user.hasBeenModified) {
```

2023-04-13 07:33 UTC, igorissen commented on api/tests/unit/domain/models/User_test.js
> +describe.only('Unit | Domain | Models | User', function () {
```suggestion
describe('Unit | Domain | Models | User', function () {
```

C'est bizarre que tu arrives à push le code avec un `.only`. Tu devrais activer husky 🐶

2023-04-13 07:58 UTC, reibecca commented on api/tests/unit/domain/models/User_test.js
> +describe.only('Unit | Domain | Models | User', function () {
Oups 🙈

2023-04-13 09:21 UTC, lego-technix requested changes

2023-04-13 09:21 UTC, lego-technix commented on orga/app/services/locale.js
> +  @service cookies;
Cette ligne fait appel à un addon Ember qu'il faut donc ajouter le paquet NPM [ember-cookies](https://www.npmjs.com/package/ember-cookies) dans le `package.json`.

2023-04-13 09:49 UTC, lego-technix commented
✅ Testé fonctionnellement avec succès avec Firefox

2023-04-13 12:20 UTC, lego-technix approved these changes

2023-04-13 12:27 UTC, igorissen approved these changes

2023-04-13 16:00 UTC, merged