[TECH] Ajoute un ADR sur la suppression des prescrits avec une vue SQL (PIX-7645)
1024pix/pix pull request #5967
Opened 2023-04-12 09:39 UTC by frinyvonnick

## :unicorn: Problème

Lors de l'écriture de l'ADR 42 un besoin n'avait pas été exprimé et donc pas pris en compte. Ce nouveau besoin remet en question la solution choisie lors du précédent ADR. Ce nouvel ADR vient documenter une décision d'architecture temporaire prise conjointement avec l'équipe Data, le CTriO et le CPO. 

## :robot: Proposition
> _Ajoutez à cet endroit, si nécessaire, des détails concernant la solution technique retenue et mise en oeuvre, des difficultés ou problèmes rencontrés._

## :rainbow: Remarques
> _Des infos supplémentaires, trucs et astuces ?_

## :100: Pour tester
> _Les instructions pour reproduire le problème, les profils de test, le parcours spécifique à utiliser, etc._

2023-04-12 09:55 UTC, machestla commented on docs/adr/0045-suppression-logique-des-données-avec-historisation
> +# 42. Suppression logique de données avec historisation.
**Question ;** Il faut garder le même numéro d'ADR que celui obsolète ?

2023-04-12 09:55 UTC, machestla commented on docs/adr/0045-suppression-logique-des-données-avec-historisation
> +Pix est utilisé en plus des applications présentes dans le monorepo par Metabase. Dans Metabase il y a
**Suggestion :** utilisé**e**

2023-04-12 09:55 UTC, machestla commented on docs/adr/0045-suppression-logique-des-données-avec-historisation
> +L'équipe Data n'est pas en mesure pour le moment de mettre à disposition des dépôts de données historisé
Suggestion : historisé**s**

2023-04-12 09:55 UTC, machestla commented on docs/adr/0045-suppression-logique-des-données-avec-historisation
> +les requêtes en lecture. Les requêtes en ecriture restent inchangés. Il sera facile de retirer la vue et changer le code de l'API le
**Suggestion :** Les requêtes en **é**criture restent inchangé**e**s

2023-04-12 09:55 UTC, machestla commented on docs/adr/0045-suppression-logique-des-données-avec-historisation
> +
**Question :** On ne parle pas de la solution des flags ?

2023-04-12 13:06 UTC, frinyvonnick commented on docs/adr/0045-suppression-logique-des-données-avec-historisation
> +# 42. Suppression logique de données avec historisation.
C'est un oubli, merci 🙏

2023-04-12 13:08 UTC, frinyvonnick commented on docs/adr/0045-suppression-logique-des-données-avec-historisation
> +
Pour moi la solution avec juste les flags a été présenté dans l'ADR précédent du coup pas besoin de revenir dessus ici 😄

2023-04-13 08:19 UTC, xav-car approved these changes

2023-04-13 13:37 UTC, Alexandre-Monney commented on docs/adr/0045-suppression-logique-des-données-avec-historisation
> +La différence avec l'ADR précédent est que le données placées dans la table de prescrits supprimés doivent continuer à être utilisable
```suggestion
La différence avec l'ADR précédent est que les données placées dans la table de prescrits supprimés doivent continuer à être utilisable
```

2023-04-13 13:39 UTC, Alexandre-Monney commented on docs/adr/0045-suppression-logique-des-données-avec-historisation
> +Les travaux de POC et Benchmark sur la solution 2 de la team Prescription sont disponible ici : https://1024pix.atlassian.net/wiki/spaces/DEV/pages/3727720453/Suppression+d+un+prescrit
```suggestion
Les travaux de POC et Benchmark sur la solution 2 de la team Prescription sont disponibles ici : 
```

2023-04-13 13:45 UTC, Alexandre-Monney commented on docs/adr/0045-suppression-logique-des-données-avec-historisation
> +Rajouter sur la table organization-learners les colonnes deletedAt et deletedBy. Créer une vue active-organization-learners qui requête
**suggestion**: on ne l'appelle pas "view-active-organization-learners" ?

2023-04-13 13:46 UTC, Alexandre-Monney commented on docs/adr/0045-suppression-logique-des-données-avec-historisation
> +la table organization-learners avec la condition WHERE deletedAt IS NULL. Cela consiste à mettre à jour les requêtes en lecture sur la
**suggestion**: Est ce que la condition ne serait pas sur les deux colonnes deletedAt AND deletedBy ?

2023-04-13 13:48 UTC, Alexandre-Monney commented on docs/adr/0045-suppression-logique-des-données-avec-historisation
> +L'ensemble des partis pris à cette décision ont conscience que la solution choisie n'est pas idéale et qu'elle est de nature temporaire.
```suggestion
L'ensemble des partis pris à cette décision a conscience que la solution choisie n'est pas idéale et qu'elle est de nature temporaire.
```

2023-04-13 13:51 UTC, Alexandre-Monney commented on docs/adr/0045-suppression-logique-des-données-avec-historisation
> +des tableaux de bords à destination de nos partenaires et des tableaux de bords pour nos utilisateurs internes.
```suggestion
des tableaux de bord à destination de nos partenaires et des tableaux de bord pour nos utilisateurs internes.
```

2023-04-13 13:52 UTC, Alexandre-Monney commented on docs/adr/0045-suppression-logique-des-données-avec-historisation
> +des ces dépôts de données, on a choisi conjointement avec le CTriO, CPO et la team Data de mettre en place une solution
```suggestion
de ces dépôts de données, on a choisi conjointement avec le CTriO, CPO et la team Data de mettre en place une solution
```

2023-04-14 12:41 UTC, frinyvonnick commented on docs/adr/0045-suppression-logique-des-données-avec-historisation
> +Rajouter sur la table organization-learners les colonnes deletedAt et deletedBy. Créer une vue active-organization-learners qui requête
On peut l'appeler comme ça pour rendre explicite que c'est une vue 👍

2023-04-14 12:42 UTC, frinyvonnick commented on docs/adr/0045-suppression-logique-des-données-avec-historisation
> +la table organization-learners avec la condition WHERE deletedAt IS NULL. Cela consiste à mettre à jour les requêtes en lecture sur la
On a pas besoin de faire sur les deux, une seule suffit normalement peu importe laquelle 😄

2023-04-18 13:57 UTC, alicepeltier requested changes

2023-04-18 13:57 UTC, alicepeltier commented on docs/adr/0045-suppression-logique-des-données-avec-historisation.md
> +Cette décision représente un choix volontaire d'ajout de dette technique qu'il faudra résorber lorsque cela sera rendu possible par les travaux de l'équipe Data.
à quoi est-ce que tu fais allusion comme travaux prévu par l'équipe data sur le sujet ?

2023-04-19 08:02 UTC, xav-car commented on docs/adr/0045-suppression-logique-des-données-avec-historisation.md
> +Cette décision représente un choix volontaire d'ajout de dette technique qu'il faudra résorber lorsque cela sera rendu possible par les travaux de l'équipe Data.
Si je ne dis pas de bêtise, c'est le stockage du nombre de `orgnization-learners` total sans devoir recompter les lignes à chaque demande .

2023-04-19 08:39 UTC, savoisn commented on docs/adr/0042-suppression-logique-de-données.md
> +Obsolète
est ce qu'on peut ajouter : 
remplacé par 0045-suppression-logique-des-données-avec-historisation.md

2023-04-21 13:33 UTC, alicepeltier approved these changes
LGTM

2023-04-21 14:47 UTC, merged