[BUGFIX] Ne plus appeler le provider de mail lors de l'exécution des tests (PIX-7783)
1024pix/pix pull request #6003
Opened 2023-04-18 09:18 UTC by igorissen

## :unicorn: Problème

En mode non-connecté au réseau, certains tests sortent à tord en erreur car l'on tente toujours de faire des appels vers l'extérieur.

## :robot: Proposition

Faire la vérification DNS uniquement lorsque l'envoie d'e-mail est activé.

## :rainbow: Remarques

RAS

## :100: Pour tester

#### Les tests

- Se mettre hors ligne.
- Exécuter les tests.
- Vérifier qu'ils passent.

#### Les applications

- Activer l'envoi d'e-mail (en local ou sur la RA)
- Se créer un compte sur Pix App
- Vérifier que vous recevez bien l'e-mail d'inscription

En bonus

- Se connecter sur Pix Orga et/ou Pix Certif
- Envoyer une invitation à rejoindre PixOrga et/ou Pix Certif
- Vérifier que vous recevez bien l'e-mail d'invitation à rejoindre Pix Orga et/ou Pix Certif

2023-04-18 12:30 UTC, octo-topi commented on api/tests/test-helper.js
> +  nock.disableNetConnect();
Il y a déjà `nock.disableNetConnect();` ligne 22, pourrais-tu expliquer quel cas couvre ton ajout ?

2023-04-18 12:40 UTC, octo-topi commented on api/lib/infrastructure/mail-check.js
> +    if (!mailing.enabled) {
Je propose de reporter tout le code de ce fichier dans le mailer:
- parce qu'il y a peu de code
- parce que cela permettra de commencer par vérifier `mailing.enabled` dans `sendEmail` et de faire un early-exit pour simplifier le code

2023-04-18 12:59 UTC, igorissen commented on api/tests/test-helper.js
> +  nock.disableNetConnect();
Honnêtement, je n'ai repris que le code qu'il y avait sur la [PR](https://github.com/1024pix/pix/pull/5927/files) qui avait cassé l'envoi l'e-mail.

Mais en regardant la doc de Nock, je ne suis pas certain que cela aurait fonctionné (je me trompes peut être). Le test du DNS qui doit être fait ne passe pas par un appel HTTP (enfin je crois), donc nock n'aurait pas pu désactiver la vérification DNS.

2023-04-18 13:02 UTC, igorissen commented on api/lib/infrastructure/mail-check.js
> +    if (!mailing.enabled) {
Yes, je vais faire le changement.

2023-04-19 07:46 UTC, octo-topi commented on api/tests/test-helper.js
> +  nock.disableNetConnect();
Dans ce cas, autant ne pas rajouter de code sans savoir pourquoi, ça ne peut causer IMHO que de la confusion

2023-04-19 07:48 UTC, octo-topi commented on api/lib/infrastructure/mail-check.js
> +    if (!mailing.enabled) {
Cool
Je "unresolve" jusqu'à ce que ça soit fait, comme ça je vérifie après

2023-04-19 10:52 UTC, francois2metz approved these changes
:rose: :hibiscus: :white_flower: :wilted_flower:  :tulip: :sunflower: :cherry_blossom:  LGTM :cherry_blossom: :sunflower:  :tulip: :wilted_flower: :white_flower: :hibiscus: :rose:

2023-04-25 08:27 UTC, lego-technix requested changes
J'ai quelques petites remarques : ça arrive. Ne pas merger SVP.

2023-04-25 08:38 UTC, lego-technix requested changes

2023-04-25 08:38 UTC, lego-technix commented on api/lib/infrastructure/mailers/mailer.js
>      debugEmail(options);
Laisser actif le debug pour l'envoi d'email, même si `MAILING_ENABLED=false`, introduit avec #5577 : 

```suggestion
    debugEmail(options);

    if (!mailing.enabled) {
      return EmailingAttempt.success(options.to);
    }
```

2023-04-25 08:38 UTC, lego-technix commented on api/lib/infrastructure/mail-check.js
> +    return resolver.resolveMx(domain).then(() => true);
En profiter pour être plus explicite sur le nom de l'argument de cette fonction, `address` n'est pas le nom d'argument auquel on s'attend le plus :

```suggestion
  checkDomainIsValid(emailAddress) {
    const domain = emailAddress.replace(/.*@/g, '');
    return resolver.resolveMx(domain).then(() => true);
```

2023-04-25 09:20 UTC, lego-technix commented
Testé : 

* ✅ `npm t` **avec** réseau et **avec** `MAILING_ENABLED=false`
* ✅ `npm t` **sans** réseau et **avec** `MAILING_ENABLED=false`
* ✅ Envois d'invitations avec les applications (Pix App, Pix Admin, Pix Orga) **avec** réseau et **avec** `MAILING_ENABLED=true`
* ✅ Envois d'invitations avec les applications (Pix App, Pix Admin, Pix Orga) **sans** réseau et **avec** `MAILING_ENABLED=false`

Il n'y a que l'exécution de tests (`npm t`) avec réseau et avec `MAILING_ENABLED=true` que je n'essaye pas pour éviter le risque d'envois multiples intempestifs même si a priori les tests utilisent des mocks.

2023-04-25 10:05 UTC, lego-technix approved these changes

2023-04-25 13:19 UTC, merged