:sparkles: api: changes in session certification results' template (PIX-8239).
1024pix/pix pull request #6442
Opened 2023-06-22 08:42 UTC by Steph0

## :unicorn: Problème
Changement du template de mail pour les résultat de session de certification, comprenant du changement de texte + l'ajout du paramètre permettant de télécharger en anglais ou en français (selon la section du mail) le fichier de résultat.

## :robot: Proposition

* Remplacer “_En savoir plus sur_ [pix.fr](https://pix.fr/) “ par “_En savoir plus sur_ [pix.fr](https://pix.fr/) (France) ou [pix.org](http://pix.org/) _(International)_” à la fin de la partie **française** du mail.

* En fin d'email
  * Pour la partie FR : Ceci est un e-mail automatique, merci de ne pas y répondre.
  * Pour la partie EN : This is an automated email message, please do not reply.

* Modification lien de l’email : Ajouter le paramètre &lang= après le token

## :rainbow: Remarques

⚠️  La prise en charge du paramètre `lang` si vous téléchargez le fichier dépend de la PR https://github.com/1024pix/pix/pull/6354 ; ici cette PR ne prend en charge que l'ajout du query parameter `lang` .

## :100: Pour tester

* Sur Pix certif, url `/sessions/5/candidats`, avec utilisateur certifsco, ajouter un candidat en vous mettant avec votre adresse de réception des résultats
* Faire en sorte de faire le parcours de certif
* Aller sur Pix Admin, url `/sessions/5/certifications` , avec utilisateur superadmin, publier dépublier la session
* Vérifier l'email reçu

2023-06-22 13:40 UTC, AndreiaPena commented
Attention, le titre c'est le nom du commit, il faut penser à le changer :)

2023-06-22 14:00 UTC, AndreiaPena reviewed
j'ai testé avec l'ancien ID (oublié de le changer) et j'ai forcément eu le lien qui ne s'est pas afficher correctement (normal) du coup faudra pas se louper avec le changement de l'ID du template oui.

--- 

Testé avec le nouvel ID et le mail est bon ✅ 

 
<img width="417" alt="Capture d’écran 2023-06-22 à 16 07 43" src="https://github.com/1024pix/pix/assets/58915422/eced05c6-400a-4969-8d7d-40b047967f14">


Par contre si je fais un curl avec le &lang=fr

<img width="634" alt="Capture d’écran 2023-06-22 à 16 41 30" src="https://github.com/1024pix/pix/assets/58915422/a60bed02-a474-43ab-9b3b-0769a2d9021c">

il est donc primordiale que les 2 PR passent ensemble

2023-06-22 14:08 UTC, AndreiaPena approved these changes

2023-06-23 12:53 UTC, aceol commented
Ou sont utilisées les traductions ajoutés/modifiés?

2023-06-26 14:30 UTC, AndreiaPena requested changes
Si on garde le `&` alors le paramètre lang va être absorbé par le paramètre token

2023-06-26 14:30 UTC, AndreiaPena commented on api/lib/domain/services/mail-service.js
> +      link: `${link}&lang=en`,
```suggestion
      link: `${link}?lang=fr`,
    },
    en: {
      ...enTranslations['certification-result-email'].params,
      homeName: PIX_HOME_NAME_INTERNATIONAL,
      homeUrl: PIX_HOME_URL_ENGLISH_SPOKEN,
      title: translate({ phrase: 'certification-result-email.title', locale: 'en' }, { sessionId }),
      link: `${link}?lang=en`,
```

2023-06-27 08:11 UTC, AndreiaPena approved these changes

2023-06-30 13:51 UTC, mariannebost approved these changes

2023-07-03 08:40 UTC, Steph0 commented
> Ou sont utilisées les traductions ajoutés/modifiés?

@aceol Toutes ces traductions sont utilisées dans le template MAIL. Elles sont passées en paramètres à Brevo qui derrière fait son interpolation au format `{{params.fr.download}}`

2023-07-03 08:41 UTC, Steph0 commented on api/lib/domain/services/mail-service.js
> +      link: `${link}&lang=en`,
Merci à toi !

2023-07-03 15:18 UTC, merged