trigger secret detection on pre-commit
1024pix/pix pull request #6718
Opened 2023-07-26 07:28 UTC by annemarie35

## :unicorn: Problème
Des secrets peuvent être commités et diffusés publiquement.

## :robot: Solution
Contrôler la présence de secrets dans un hook de pré-commit.

## :100: Pour tester
- récupérer le référentiel
  - essayer de le commiter et observer qu'une alerte est levée et qu'il n'est pas possible de le commiter (bon, un --no-verify vous fera passer outre) 
- ajouter des fichiers test, dans plusieurs répertoires, par exemple :
  - api/tests/unit/tooling/empty-json-file.json
  - docs/adr/fake-adr-with-secret.md
  - pix-editor/empty-file-test.md
  - pix-editor/referential-in-pix-editor-directory.json
  - referential.json
  - test espace.md _(un fichier contenant un espace dans le nom)_
  - api/chars-file-\*\$§.md (nom avec des caractères spéciaux qui va générer une erreur sur le script)

2023-07-26 07:56 UTC, HEYGUL commented
L'usage des hooks de precommit n'étant pas obligatoire, il faudrait a minima exécuter le script sur la CI pour détecter la fuite de secrets de manière systématique (même si c'est déjà trop tard dans ce cas-là, au moins on sait qu'une fuite a eu lieue).
A voir comment refuser un commit qui introduirait une fuite de secrets.

2023-07-26 07:59 UTC, HEYGUL commented on .husky/detect-secret
> +SECRET=postgres://postgres:J9FUMSBhei8oU@db.dbhostprovider.com:5434/thedb
je ne comprend pas cette valeur, à quoi correspond elle ?

2023-07-26 08:00 UTC, octo-topi requested changes
Test KO, le commit n'est pas bloqué

```
❯ curl -H  "Authorization: Bearer xxxxxxxxx" https://lcms.minimal.pix.fr/api/releases/latest > ./referential.json
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 28721  100 28721    0     0   228k      0 --:--:-- --:--:-- --:--:--  228k
❯ git add ./referential.json
❯ git commit -m "test"
[pix-8665-prevent-secret-leaking 8eb65bb98c] test
 2 files changed, 1 insertion(+)
 create mode 100644 api/foo
 create mode 100644 api/referential.json
```

2023-07-26 08:01 UTC, octo-topi commented on .husky/detect-secret
> +SECRET=postgres://postgres:J9FUMSBhei8oU@db.dbhostprovider.com:5434/thedb
A un marqueur qui signale l'existence de contenu sensible. La MEJ t'en dira plus.

2023-07-26 08:01 UTC, octo-topi commented
> L'usage des hooks de precommit n'étant pas obligatoire, il faudrait a minima exécuter le script sur la CI pour détecter la fuite de secrets de manière systématique (même si c'est déjà trop tard dans ce cas-là, au moins on sait qu'une fuite a eu lieue). A voir comment refuser un commit qui introduirait une fuite de secrets.

C'est déjà fait par GitGuardian. Je le rajoute dans la description de PR.

2023-07-26 13:01 UTC, octo-topi approved these changes
Test Ok sur Linux
```
❯ git add ./referential.json
❯ git commit -m "test"
→ No staged files match any configured task.
Inspecting file :  api/referential.json 
Oops, we found the secret  postgres://postgres:J9FUMSBhei8oU@db.dbhostprovider.com:5434/thedb  in file api/referential.json ! 
husky - pre-commit hook exited with code 255 (error)

```

2023-07-31 11:34 UTC, francois2metz approved these changes
:rose: :hibiscus: :white_flower: :wilted_flower:  :tulip: :sunflower: :cherry_blossom:  LGTM :cherry_blossom: :sunflower:  :tulip: :wilted_flower: :white_flower: :hibiscus: :rose:

2023-08-02 07:03 UTC, merged