[TECH] Utilisation de npm workspaces.
1024pix/pix pull request #6791
Opened 2023-07-31 20:00 UTC by HEYGUL

## :unicorn: Problème

Les targets `npm` à rallonge, les `npm run ci:all`, etc .... On n'en (p|v)eut plus !

## :robot: Proposition

Utiliser `npm workspaces` pour tirer parti du monorepo.

## :rainbow: Remarques

Une ADR à écrire ?

## :100: Pour tester

Une CI verte, what else ?

2023-08-21 09:08 UTC, HEYGUL commented on package.json
> +    "prebuild": "mkdir -p ../dist",
```suggestion
   "prebuild": "mkdir -p ./dist",
```

2023-08-21 09:13 UTC, HEYGUL commented on 1d/package.json
> +    "scalingo-prebuild": "mv ../package-lock.json package-lock.json; rm ../package.json",
A supprimer

2023-08-21 12:22 UTC, annemarie35 commented on admin/package.json
> +    "scalingo-prebuild": "rm ../node_modules/mon-pix; cp -rL ../node_modules ./node_modules; rm ../package.json",
ça devrait pas être `"rm ../node_modules/admin ` ?

2023-08-22 12:23 UTC, octo-topi requested changes, later dismissed
Je ne sais pas où mettre ça en review, donc je le mets là !

Deux points me frappent:
- on ne sait pas pourquoi on le fait (quels avantages ? quels inconvénients ?) : je m'attends à un ADR car c'est structurant (ex: on a déjà mis le choix des versions de Node dans un ADR)
- on ne voit pas d'impact dans la doc d'installation, est-ce normal ? Rien ne change ? Vraiment ? On fait toujours `npm ci` dans chaque app ?

2023-08-22 13:50 UTC, annemarie35 commented
@octo-topi on est en train de mettre tout ça dans les slides de présentation, l'adr est une bonne idée ^^

2023-08-22 15:00 UTC, francois2metz commented
Avec le fonctionnement de npm et de la résolution de dépendance, le fait de devoir synchroniser les versions des packages entre les applis front me parait bloquant.

2023-08-22 15:58 UTC, HEYGUL commented
> Avec le fonctionnement de npm et de la résolution de dépendance, le fait de devoir synchroniser les versions des packages entre les applis front me parait bloquant.

Pas si sûr : est-ce que renovate saurait mettre à jour les dépendances de manière synchrone sur les applis front.
On pourrait ainsi bénéficier de ce premier travail avant de passer à une autre solution (genre `pnpm`).

2023-08-23 07:50 UTC, yannbertrand commented
Quelques petites découverte pour moi.

Je ne connais pas bien les workspaces, j'ai regardé un peu [la doc](https://docs.npmjs.com/cli/v7/using-npm/workspaces) puis j'ai fait quelques tests depuis la racine :
- `npm ci`
- `npm run test:api:unit --workspace api` - pratique, pas besoin de me déplacer dans le dossier `api` !
- `npm run start --workspace api mon-pix` ne lance que l'API, c'est normal d'après la doc
- `npm run start --workspace api --workspace mon-pix` ne lance que l'API. Quand je `ctrl+c`, l'API se coupe et mon-pix se lance donc les 2 ne tournent pas en même temps 😅 peut être que j'ai mal compris le fonctionnement.

Du coup pour lancer mon env de dev pour Pix App, j'ai toujours besoin de 2 terminaux mais je peux les lancer depuis la racine `npm run start -w api` et `npm run start -w mon-pix` dans un autre terminal.

`npm run lint --workspaces` semble paralléliser correctement.

`npm run start -ws` lance en série 🤔, il faut interrompre toutes les apps les unes après les autres pour le couper 😅

2023-08-23 07:58 UTC, igorissen commented
> * `npm run start --workspace api mon-pix` ne lance que l'API, c'est normal d'après la doc
> * `npm run start --workspace api --workspace mon-pix` ne lance que l'API. Quand je `ctrl+c`, l'API se coupe et mon-pix se lance donc les 2 ne tournent pas en même temps 😅 peut être que j'ai mal compris le fonctionnement.

Oui on avait fait ces tests aussi

> `npm run lint --workspaces` semble paralléliser correctement.

Derrière ce run script NPM il y a cette commande `run-p --print-label lint:*`

2023-08-23 08:02 UTC, yannbertrand commented
> > `npm run lint --workspaces` semble paralléliser correctement.
> 
> Derrière ce run script NPM il y a cette commande `run-p --print-label lint:*`

Ah j'ai été un peu vite, en fait non ça tourne en série ! Le fait de préciser `-ws` fait bien en sorte de ne pas exécuter le script à la racine.

2023-08-23 09:26 UTC, yannbertrand commented
> > Avec le fonctionnement de npm et de la résolution de dépendance, le fait de devoir synchroniser les versions des packages entre les applis front me parait bloquant.
> 
> Pas si sûr : est-ce que renovate saurait mettre à jour les dépendances de manière synchrone sur les applis front. On pourrait ainsi bénéficier de ce premier travail avant de passer à une autre solution (genre `pnpm`).

On peut configurer Renovate pour grouper tout ça, mais Renovate ne fait que proposer les nouvelles versions. Parfois il faut faire du travail manuel derrière et des fois c'est déjà assez difficile unitairement sur une appli. Ça a été plutôt un avantage jusqu'à présent de dissocier les versions des applis pour y aller incrémentalement. Donc je partage la crainte : le risque est de freiner les montées de versions.

Ceci dit je comprend la limitation, si vous pensez que la solution `pnpm` est viable et trouvez un moyen d'y aller (quite à trouver plus de temps pour avec une impact team ?), je suis plutôt OK pour apporter ce changement même si il n'est que temporaire.

Par contre je suis d'accord qu'il manque de précision sur la problématique que cette proposition essaye de résoudre pour le moment ! Ça serait intéressant d'avoir plus d'éléments dans le descriptif de la PR :)

2023-08-23 09:51 UTC, Thomasevano commented on 0052-utilisation-de-workspaces.md
> +Mais nous afrrivons aux limites :
```suggestion
Mais nous arrivons aux limites :
```

2023-08-23 12:24 UTC, annemarie35 commented on package.json
> +    "build:api": "npm run build --workspace=api",
build:api à supprimer

2023-08-23 12:52 UTC, HEYGUL commented on INSTALLATION.md
>  - Admin : `npm run start:admin`
npm run start --workspace=admin

2023-08-23 12:52 UTC, HEYGUL commented on INSTALLATION.md
>  - Api : `npm run start:api`
npm run start --workspace=api

2023-08-23 12:53 UTC, HEYGUL commented on package.json
> +    "ci:workspaces": "npm ci",
pourquoi les remettre ? perso je préfère que chaque s'approprie l'usage de npm

2023-08-24 07:25 UTC, octo-topi commented on 0052-utilisation-de-workspaces.md
> +- Temps d’installation des dépendances assez long
Cette phrase est problématique car:
- elle est arbitraire/subjective (`important`, `long`, je ne trouve pas sur une connexion fibre et un PC récent);
- elle mélange la cause et les conséquences.

Je propose cette reformulation.
```suggestion
Chaque application déclare ses propres dépendances avec `npm` , sans les mettre en commun avec les autres applications. En conséquence, ces dépendances sont installées isolément. Chaque application est autoportante.  

Si les dépendances sont mises en commun (avec les ` workspaces`), elles ne seront téléchargées et installées qu'une seule fois. Cela peut réduire le temps d'installation et la taille prise sur le disque. Cette solution n'est valide qu'en local, pas en production où les applications sont déployées séparément.
```

2023-08-24 07:27 UTC, octo-topi commented on 0052-utilisation-de-workspaces.md
> +- Un dossier node_modules à la racine regroupant les dépendances communes des workspaces
Ce n'est pas un avantage, c'est un détail d'implémentation.
```suggestion
```

2023-08-24 07:32 UTC, octo-topi commented on 0052-utilisation-de-workspaces.md
> +- Le temps d'installation est divisé par deux
Je n'ai pas la référence en tête, mais il y a un piège ici.
Si la taille est de 2Mo sur un PC récent (pas un système emabarqué), passer à 1Mo n'est pas un avantage comparé à la complexité des workspace. Idem si on passe de 2 secondes à 1 seconde.
```suggestion
Sur un PC 8CPU 2Ghz avec débit descendant de 3Mb/s
- la taille est divisée par 2, passant de 2Gb à 1 Gb
- le temps d'installation est divisé par deux, passant de 10 minutes à 5 minutes
```

2023-08-24 07:43 UTC, octo-topi commented on 0052-utilisation-de-workspaces.md
> +Mais ceci est mitigé par l'utilisation de Renovate (lien vers [commit](https://github.com/1024pix/pix/pull/6791/commits/7956548245f6bbfaff21efc4f6ec94672b51aad0)).
Je propose de ne garder que cet inconvénient, et de déplacer les remarques sur pix1d dans la partie conséquences en fin de fichier.

Je propose aussi d'expliciter le travail initial de réalignement des dépendances, pas seulement les montées de version suivantes.
```suggestion
Pour que le gain soit effectif, il faut que les applications aient un nombre suffisant de dépendances en commun. On peut s'attendre à ce que les 4 front-end EmberJs aient des librairies en commun, mais beaucoup moins avec le back-end HapiJs.

Même si c'est le casn, pour que la dépendance puisse être utilisée par plusieurs applications, toutes ces applications devront utiliser la même version de cette librairie. Il y aura donc un travail initial d'alignement de toutes les dépendances partagées entre les applications, sinon il n'y aura pas de bénéfice.

Les montées de versions affecteront toutes les applications. Si uen montée de version embarque un changement bloquant, le code de toutes les applications devra être être modifié avant de merger la PR, ce qui augmentera le temps de développement, de revue, et donc le délai de mise à disposition.

Une partie du travail de montées de version est pris en charge par Renovate (lien vers [commit](https://github.com/1024pix/pix/pull/6791/commits/7956548245f6bbfaff21efc4f6ec94672b51aad0)).

En résumé, l'inconvénient est le couplage entre applications.
```

2023-08-24 07:46 UTC, octo-topi commented on 0052-utilisation-de-workspaces.md
> +### Solution :
Il manque la solution 2 (existante), à savoir utiliser la version native (sans workspace).
C'est important pour que le développeur ne doive pas inverser les inconvénients de la solution 1 dans sa tête pour avoir la solution 2.

```suggestion
### Solution 1 : utiliser les workspace npm
```

2023-08-24 07:49 UTC, octo-topi commented on 0052-utilisation-de-workspaces.md
> +Nous avons choisi d'utiliser les npm workspaces.
L'intérêt d'un ADR est de dire pourquoi on choisi. Souvent, le contexte rend une décision évidente, mais ce contexte change et on se demande après coup pourquoi la décision.

Je propose de suivre le template (ADR1) et d'expliciter ce qui vous a fait décider en faveur de la solution 1
```
Nous avons choisi la solution n°1, à savoir les ADR, car le temps passé à créer un ADR est minimal par rapport au risque encouru si la connaissance est perdue.
```
Ce qui donnerait ici
```suggestion
Nous avons choisi d'utiliser les npm workspaces parce que l'avantage XXXX est plus important que les inconvénients
```

2023-08-24 07:50 UTC, octo-topi commented on 0052-utilisation-de-workspaces.md
> +- Impact minime sur le workflow.
Cette phrase est mystérieuse.. Quel workflow ? Celui de CI ? Les actions du développeur ?
```suggestion
- Impact minime sur le workflow.
```

2023-08-24 07:51 UTC, octo-topi commented on 0052-utilisation-de-workspaces.md
> +- Moins de run script npm
J'aimerai une réponse détaillée, le fichier INSTALLATION.md me donne des pistes
```
cd admin && npm start
npm start --workspace=admin
```

2023-08-28 07:50 UTC, octo-topi commented on docs/adr/0052-utilisation-de-workspaces.md
> +- Moins de run script npm. Avec l'option `--workspace` nous pouvons spécifier le workspace sur lequel exécuter la commande
:fire:

2023-08-28 07:52 UTC, octo-topi commented on docs/adr/0052-utilisation-de-workspaces.md
> +### Solution 2 : rester dans l'état actuel
Une ADR peut changer la codebase, bien sûr, mais l'essentiel est qu'on sache quelle solution choisir, je propose donc
```suggestion
### Solution 2 : utiliser npm sans les workspace
```

2023-08-28 07:53 UTC, octo-topi commented on docs/adr/0052-utilisation-de-workspaces.md
> +Les mêmes versions des dépendances sont dupliquées.
```suggestion
Les dépendances utilisées par plusieurs applications, avec la même version, sont dupliquées.
```

2023-08-28 07:55 UTC, octo-topi commented on docs/adr/0052-utilisation-de-workspaces.md
> +Nous avons choisi d'utiliser les npm workspaces parce que l'avantage d'avoir _chaque version des dépendances installée une seule fois_ est plus important que les inconvénients.
Mouais, nan ! Je propose plus direct
```suggestion
Nous avons choisi d'utiliser les npm workspaces parce que, même si cela amène de la complexité et du couplage entre les applications, l'expérience de développement en local (délai installation, taille disque) est plus importante que la production.
```

2023-08-28 07:56 UTC, octo-topi commented on INSTALLATION.md
> +- Orga : `npm start --workspace=orga`
```suggestion

Chaque application front-end a besoin de l'API pour fonctionner.

Pour démarrer:
- Admin : `npm start --workspace=admin`
- Api : `npm start --workspace=api`
- App : `npm start --workspace=mon-pix`
- Certif : `npm start --workspace=certif`
- Orga : `npm start --workspace=orga`
```

2023-08-28 08:26 UTC, yannbertrand commented on docs/adr/0052-utilisation-de-workspaces.md
> +Si les dépendances sont mises en commun (avec les ` workspaces`), elles ne seront téléchargées et installées qu'une seule fois. Cela peut réduire le temps d'installation et la taille prise sur le dis
```suggestion
Si les dépendances sont mises en commun (avec les `workspaces`), elles ne seront téléchargées et installées qu'une seule fois. Cela peut réduire le temps d'installation et la taille prise sur le disque. Cette solution n'est valide qu'en local, pas en production où les applications sont déployées séparément.
```

2023-08-28 09:02 UTC, yannbertrand commented on docs/adr/0052-utilisation-de-workspaces.md
> +Les mêmes versions des dépendances sont dupliquées.
```suggestion
Les dépendances utilisées par plusieurs applications, y compris si elles dépendant de la même version, sont dupliquées.
```

2023-08-28 09:04 UTC, yannbertrand commented
Top l'ADR 👍

2023-09-13 05:28 UTC, HEYGUL commented
PR fermée car l'inconvénient d'avoir une seule et même version d'une dépendance au sein de **tout** le monorepo est trop important.
Décision consignée dans #7067.

2023-09-13 05:28 UTC, closed without merging