[FEATURE] Pouvoir choisir de rechercher sur les orgas archivés ou non dans Pix Admin (PIX-6109).
1024pix/pix pull request #6812
Opened 2023-08-02 14:49 UTC by Thomasevano

## :unicorn: Problème
On ne peut pas cacher les organisations archivés 

## :robot: Proposition
Ajouter un bouton toggle afin de cacher les organisations archivés

## :rainbow: Remarques
> _Des infos supplémentaires, trucs et astuces ?_

## :100: Pour tester
> _Les instructions pour reproduire le problème, les profils de test, le parcours spécifique à utiliser, etc._

2023-08-04 12:58 UTC, igorissen reviewed
Il faudrait plus détailler la partie `Pour tester` de la description de la PR

2023-08-04 13:02 UTC, igorissen reviewed
Impossible de tester fonctionnellement sur la RA car il n'y a pas de seed d'organisation archivée. 2 options sont possibles :
1. Ajouter des seeds
2. Archiver une organisation présente pour valider fonctionnellement par la suite

2023-08-04 13:03 UTC, igorissen approved these changes
Tests fonctionnels ✅  sur Chrome

2023-08-04 13:10 UTC, reibecca commented on admin/tests/acceptance/authenticated/organizations/list_test.js
> +      test('it display non archived organizations', async function (assert) {
```suggestion
      test('it displays non archived organizations', async function (assert) {
```

2023-08-04 13:12 UTC, reibecca commented on admin/tests/acceptance/authenticated/organizations/list_test.js
> +        assert.dom(screen.getByLabelText('Organisation Tic')).exists();
**Suggestion** : Ajouter un assert pour vérifier que l'orga archivée n'est pas affichée

```suggestion
     assert.dom(screen.getByLabelText('Organisation Tic')).exists();
     assert.dom(screen.getByLabelText('Organisation Tac')).doesNotExist();
```

2023-08-04 13:13 UTC, reibecca commented on admin/tests/acceptance/authenticated/organizations/list_test.js
> +        const expectedTableHeaderFiltersAndBodyLength = 3;
**Question :** j'ai pas compris à quoi correspond `expectedTableHeaderFiltersAndBodyLength`

2023-08-04 13:16 UTC, reibecca commented on admin/tests/unit/routes/authenticated/organizations/list_test.js
> +          hideArchived: undefined,
**Question** : sa valeur par défaut n'est pas `false` ?

2023-08-04 13:19 UTC, reibecca commented on api/lib/infrastructure/repositories/organization-repository.js
Il faudrait ajouter un test à ce repository

2023-08-04 13:29 UTC, Thomasevano commented on admin/tests/acceptance/authenticated/organizations/list_test.js
> +        const expectedTableHeaderFiltersAndBodyLength = 3;
C'était car on avait les headers aussi en `row` retourner dans le dom
Mais le test va changer il test un affichage alors qu'il devrait test s'il a bien la bonne URL au clique sur le toggle

2023-08-04 13:30 UTC, Thomasevano commented on admin/tests/acceptance/authenticated/organizations/list_test.js
> +        assert.dom(screen.getByLabelText('Organisation Tic')).exists();
C'était mon intention premiere mais il l'a trouve pas avec get, il faudra utiliser un findAll il me semble

2023-08-04 13:31 UTC, Thomasevano commented on admin/tests/unit/routes/authenticated/organizations/list_test.js
> +          hideArchived: undefined,
Il me semblait aussi aussi, mais le test échoue et me dit qu'il reçoit, `undefined` j'ai pas vraiment compris pourquoi j'avoue

2023-08-04 13:32 UTC, reibecca commented
✅ Tests fonctionnels en local sur Chrome

2023-08-04 13:35 UTC, reibecca commented on admin/tests/acceptance/authenticated/organizations/list_test.js
> +        assert.dom(screen.getByLabelText('Organisation Tic')).exists();
Mince, essaye avec un `queryByLabelText` ou `queryByText`

2023-08-04 13:37 UTC, reibecca commented on admin/tests/acceptance/authenticated/organizations/list_test.js
> +        const expectedTableHeaderFiltersAndBodyLength = 3;
Ah d'accords, je comprenais pas pourquoi il s'attendait à recevoir 3, je me disais si il y qu'une orga archivée sur les deux, il devrait en attendre qu'une

2023-08-04 13:37 UTC, reibecca commented on admin/tests/unit/routes/authenticated/organizations/list_test.js
> +          hideArchived: undefined,
Oh c'est bizarre 🤔 je vais regarder

2023-08-04 13:41 UTC, igorissen commented on admin/tests/acceptance/authenticated/organizations/list_test.js
> +        const expectedTableHeaderFiltersAndBodyLength = 3;
@reibecca c'est parce que les éléments d'un tableau sont des `row` en terme de `role` pour l'accessibilité.
1. header : contient les noms de chacune des colonnes
2. filters : contient pour chacune des colonnes un input pour faire un filtre
3. la liste des organisations

2023-08-04 13:44 UTC, clemlatz requested changes

2023-08-04 13:44 UTC, clemlatz commented on api/lib/infrastructure/repositories/organization-repository.js
> +    qb.whereNull('archivedAt');
**issue(blocking):** si je commente cette ligne, ça ne casse aucun test 🥲 

Comme dit @reibecca, c'est le signe qu'il manque un test.

2023-08-04 13:44 UTC, clemlatz commented on admin/app/styles/components/organizations/list-items.scss
> +  &__self-toggle {
**suggestion:**

```suggestion
  &__archived-organizations-toggle {
```

Je suppose que le "self" avait du sens pour "Afficher mes sessions" mais ici pas trop.

2023-08-04 13:44 UTC, clemlatz commented on admin/app/templates/authenticated/organizations/list.hbs
> +      <XToggle @size="small" @theme="light" @value={{this.hideArchived}} @onToggle={{fn (mut this.hideArchived)}} />
**suggestion:** utiliser un composant Pix UI comme PixCheckbox ou PixToggle ?

2023-08-04 13:44 UTC, clemlatz commented on admin/tests/acceptance/authenticated/organizations/list_test.js
> +        assert.dom(screen.getByLabelText('Organisation Tic')).exists();
Oui il faut utiliser `findByLabelText` qui va retourner `null` s'il ne trouve pas l'élément, contrairement à `getByLabelText` qui va jeter une erreur et faire échouer le test si l'élément n'existe pas (alors que c'est ce qu'on veut 🙂)

2023-08-04 13:58 UTC, reibecca commented on admin/tests/acceptance/authenticated/organizations/list_test.js
> +        const expectedTableHeaderFiltersAndBodyLength = 3;
@igorissen pour l'accessibilité c'est pas `cell` le rôle des éléments d'un tableau ?

Mais je comprends mieux pourquoi 3 maintenant 🙂 merci

2023-08-04 14:00 UTC, reibecca commented on admin/app/styles/components/organizations/list-items.scss
> +    padding-bottom: 10px;
**Suggestion :** Utiliser un design token de pix pour le spacing

2023-08-04 14:11 UTC, Thomasevano commented on admin/app/templates/authenticated/organizations/list.hbs
> +      <XToggle @size="small" @theme="light" @value={{this.hideArchived}} @onToggle={{fn (mut this.hideArchived)}} />
Je me suis demander aussi, mais comme ils ont pas le design, et qu'il ne "fonctionne pas" lorsque je les ai essayés sur ui.pix.fr. Dans le code j'en ai trouvé qu'une utilisation qui indiquait "Deprecated"

2023-08-04 14:29 UTC, clemlatz commented
✅ Test fonctionnel OK sur Firefox (mais je me suis fait la réflexion que ça aurait été plus logique de masquer par défaut les organisations archivées et de les afficher à la demande)

2023-08-07 09:23 UTC, reibecca commented on admin/tests/unit/routes/authenticated/organizations/list_test.js
> +          hideArchived: undefined,
C'est étrange, j'ai réessayé et le test passe que je lui passe `false`, `true`, `undefined` ou même une string vide

2023-08-07 09:24 UTC, reibecca commented
✅ Testé fonctionnellement avec les nouveaux seeds

2023-08-07 09:24 UTC, reibecca approved these changes

2023-08-07 12:10 UTC, clemlatz approved these changes

2023-08-07 13:47 UTC, merged