[FEATURE] Remettre à zéro la participation à une campagne - API (PIX-8669).
1024pix/pix pull request #6815
Opened 2023-08-02 15:34 UTC by HEYGUL

## :unicorn: Problème
Il n'est pas possible de remettre à zéro les compétences Pix+.

## :robot: Proposition
Ces compétences étant évaluées lors d'une campagne, on ajoute une fonctionnalité de remise à zéro d'une participation à une campagne.
Cette PR couvre la route d'API permettant cette remise à zéro.

## :rainbow: Remarques
-

## :100: Pour tester
La CI est verte et c'est déjà pas mal.

2023-08-03 14:16 UTC, yannbertrand commented
Pourquoi est-ce qu'on ne valide pas notre payload avec Joi ?

2023-08-03 14:25 UTC, yannbertrand approved these changes
Pas d'impact à prévoir en prod car `campaignRepository.areKnowledgeElementsResettable` renvoie toujours `false` avec nos données actuelles. Donc OK pour moi de merger.

2023-08-03 14:33 UTC, yannbertrand commented on api/lib/domain/usecases/start-campaign-participation.js
> +  await assessmentRepository.setAssessmentsAsStarted({ assessmentIds, domainTransaction });
Finalement pas besoin de repasser les `competenceEvaluation` à `started` pour les `scorecard` ? Ça fonctionne aussi si on modifie le statut d'`assessment` ?

2023-08-03 14:35 UTC, yannbertrand commented on api/tests/integration/infrastructure/repositories/assessment-repository_test.js
> +      expect(statesInDb).to.deep.equal(['started', 'started']);
```suggestion
      expect(statesInDb).to.deep.equal([Assessment.states.STARTED, Assessment.states.STARTED]);
```

2023-08-03 14:43 UTC, VincentHardouin commented on api/lib/domain/usecases/start-campaign-participation.js
> +  await assessmentRepository.setAssessmentsAsStarted({ assessmentIds, domainTransaction });
Les competencesEvaluation n'ont pas de status `ENDED` : https://github.com/1024pix/pix/blob/757496150ea9c2535ad2a10ae50637a5c1cb0c6d/api/lib/domain/models/CompetenceEvaluation.js#L1-L4
La Scorecard se base sur l'assessment pour le cas où la compétence est terminée : 
https://github.com/1024pix/pix/blob/f147e3d6f99c29845faf31fb3f5d7991ae3862bc/api/lib/domain/models/Scorecard.js#L169-L171

2023-08-03 14:46 UTC, yannbertrand commented on api/lib/domain/usecases/start-campaign-participation.js
> +  await assessmentRepository.setAssessmentsAsStarted({ assessmentIds, domainTransaction });
OK farpait

2023-08-03 14:56 UTC, yannbertrand commented
Ah par contre je n'arrive pas `db:reset` sur cette branche

```
Erreur dans databaseBuilder.commit() : error: /* path:  */ insert into "features" ("description", "id", "key") values ($1, $2, $3) - duplicate key value violates unique constraint "features_key_unique"
Error while executing "pix/api/db/seeds/seed.js" seed: /* path:  */ insert into "features" ("description", "id", "key") values ($1, $2, $3) - duplicate key value violates unique constraint "features_key_unique"
Error: Error while executing "pix/api/db/seeds/seed.js" seed: /* path:  */ insert into "features" ("description", "id", "key") values ($1, $2, $3) - duplicate key value violates unique constraint "features_key_unique"
    at Seeder._waterfallBatch (pix/api/node_modules/knex/lib/migrations/seed/Seeder.js:118:23)
error: /* path:  */ insert into "features" ("description", "id", "key") values ($1, $2, $3) - duplicate key value violates unique constraint "features_key_unique"
    at Object.queryBuilder (pix/api/node_modules/knex/lib/knex-builder/make-knex.js:112:26)
    at createQueryBuilder (pix/api/node_modules/knex/lib/knex-builder/make-knex.js:320:26)
    at knex (pix/api/node_modules/knex/lib/knex-builder/make-knex.js:101:12)
    at DatabaseBuilder.commit (pix/api/db/database-builder/database-builder.js:23:15)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async createTargetProfile (pix/api/db/seeds/data/common/tooling/target-profile-tooling.js:85:3)
    at async commonBuilder (pix/api/db/seeds/data/common/common-builder.js:91:3)
    at async Module.seed (pix/api/db/seeds/seed.js:15:3)
```

2023-08-03 15:13 UTC, yannbertrand requested changes
Le `npm run db:reset` bloque à cause de cette ligne. Même résultat chez @mirawlin je bloque le temps d'en discuter.

2023-08-03 15:14 UTC, yannbertrand commented on api/db/database-builder/database-builder.js
> +      'features',
Cette ligne

2023-08-03 15:27 UTC, mirawlin commented on api/db/database-builder/database-builder.js
> +      'features',
J'ai testé sur local apres avoir suprimmer cette ligne et ca marche bien. Mais j'aimerais comme meme qu'on discute pour mieux comprendre cette partie

2023-08-03 15:31 UTC, yannbertrand commented on api/db/database-builder/database-builder.js
> +      'features',
Oui ce n'est probablement pas ici la root cause, cette ligne est certainement légitime !

2023-08-03 15:40 UTC, yannbertrand approved these changes
C'est bien fixé ✅

2023-08-04 09:07 UTC, VincentHardouin commented on api/lib/domain/models/KnowledgeElement.js
> +      earnedPix: 0,
**suggestion :** repasser l'id à `undefined` pour signifier qu'il s'agit bien d'un nouveau KE

2023-08-04 09:07 UTC, VincentHardouin commented on api/tests/integration/infrastructure/repositories/campaign-repository_test.js
> +    it('should return true if campaign allows knowledgeElements to be reset', async function () {
Il y a en réalité 4 cas à tester : 

| multipleSendings    | areKnowledgeElementsResettable | expected |
| :-----------: | :-----------: | :-----------: |
| true | true | true |
| true | false | false |
| false | true | false |
| false | false | false |


On peut envisager un test paramétré 
```
{ multipleSendings: true, areKnowledgeElementsResettable: true, expected: true }
{ multipleSendings: true, areKnowledgeElementsResettable: false, expected: false }
{ multipleSendings: false, areKnowledgeElementsResettable: true, expected: false }
{ multipleSendings: false, areKnowledgeElementsResettable: false, expected: false }
```

2023-08-04 09:07 UTC, VincentHardouin commented on api/lib/infrastructure/repositories/campaign-participant-repository.js
> +async function getKnowledgeElementsFromCampaignParticipation(campaignParticipation, domainTransaction) {
Cette méthode ne sert pas le commit peut être supprimé, nous récupérons finalement tous les KEs de l'user, puis nous filtrons ceux qui nous intéresse grâce au champ `skillId`

2023-08-04 09:07 UTC, VincentHardouin commented on api/lib/infrastructure/serializers/jsonapi/campaign-participation-serializer.js
> +    .then((deserializedCampaignParticipation) => {
**suggestion :** Passer en async/await

2023-08-04 12:15 UTC, xav-car commented on api/lib/domain/models/KnowledgeElement.js
> +      earnedPix: 0,
+ test ajouter pour valider le fait que ce soit undefined

2023-08-04 12:22 UTC, xav-car approved these changes

2023-08-04 12:22 UTC, mirawlin approved these changes

2023-08-04 12:36 UTC, VincentHardouin approved these changes

2023-08-04 12:39 UTC, merged