[TECH] Supprime le code de l'auto answer
1024pix/pix pull request #6835
Opened 2023-08-08 08:02 UTC by yannbertrand

## :unicorn: Problème
Suite à #5345, on a pas fait le nettoyage de l'auto answer.

## :robot: Proposition
Supprimer le code correspondant à l'auto answer.

## :rainbow: Remarques
Penser à activer `FT_ALWAYS_OK_VALIDATE_NEXT_CHALLENGE_ENDPOINT` en local.

## :100: Pour tester

### Vérification du feature toggle

L'efficacité du feature toggle protégeant la route peut se tester facilement en ligne de commande :

1. Vérifier que la commande suivante renvoie un `404` :
   ```shell
   curl -X POST http://app.dev.pix.fr/api/admin/assessments/55555/always-ok-validate-next-challenge
   ```
2. Ajouter la ligne `FT_ALWAYS_OK_VALIDATE_NEXT_CHALLENGE_ENDPOINT=true` au fichier `.env`
3. Vérifier que la commande suivante renvoie un `401` :
   ```shell
   curl -X POST http://app.dev.pix.fr/api/admin/assessments/55555/always-ok-validate-next-challenge
   ```

### Vérification du fonctionnement

Cette nouvelle route se teste avec la nouvelle version d'auto-answer. Pour cette partie de test, se rapprocher d'un dev qui pourra vous expliquer comment utiliser cette fonctionnalité si vous ne la connaissez pas encore.

2023-08-08 12:36 UTC, francois2metz approved these changes
:grapes: :melon: :tangerine: :pineapple: :apple: :kiwi_fruit: LGTM :kiwi_fruit: :apple:  :pineapple:  :tangerine:  :melon: :grapes:

2023-08-09 07:57 UTC, VincentHardouin approved these changes

2023-08-10 07:39 UTC, mirawlin approved these changes

2023-08-21 14:25 UTC, Steph0 commented on api/lib/config.js
> +    config.featureToggles.isAlwaysOkValidateNextChallengeEndpointEnabled = true;
Le FT peut être supprimé non ?
J'ai l'impression qu'il servait uniquement dans `Acceptance | API | assessment-controller-auto-validate-next-challenge` qui est désormais supprimé

2023-08-21 15:02 UTC, francois2metz commented on api/lib/config.js
> +    config.featureToggles.isAlwaysOkValidateNextChallengeEndpointEnabled = true;
Non il n'est pas supprimé. C'est le endpoint qui remplace celui qu'on supprime ici.

2023-08-23 07:50 UTC, francois2metz commented on api/sample.env
> +FT_ALWAYS_OK_VALIDATE_NEXT_CHALLENGE_ENDPOINT=true
On veut le passer a true par défaut ?

2023-08-23 07:52 UTC, yannbertrand commented on api/sample.env
> +FT_ALWAYS_OK_VALIDATE_NEXT_CHALLENGE_ENDPOINT=true
Elle a déjà cette valeur sur les RA, l'intégration et la recette. Je suis plutôt pour qu'on puisse l'utiliser en dev :) (reste une manip à faire pour les devs déjà chez Pix)

2023-09-01 13:33 UTC, lego-technix commented on api/sample.env
> +FT_ALWAYS_OK_VALIDATE_NEXT_CHALLENGE_ENDPOINT=true
Personnellement je suis plutôt opposé à un passage à `true` de cette valeur. En effet cela ferait penser qu'il serait normal voire nécessaire dans une utilisation classique de pix `FT_ALWAYS_OK_VALIDATE_NEXT_CHALLENGE_ENDPOINT` soit activé. Or ce FT n'est ni normal ni nécessaire dans le cadre d'une utilisation classique de pix. C'est un FT pour « ouvrir une brèche » dans pix. Et on veut vraiment que l'activation de cette possibilité ne soit pas faite sans qu'il s'agisse d'une action consciente et volontaire.

Que `FT_ALWAYS_OK_VALIDATE_NEXT_CHALLENGE_ENDPOINT` soit activé sur les RA est utile et non risqué, mais cela ne veut pas dire que cela en fait le cas qu'on souhaite par défaut.

2023-09-01 13:34 UTC, lego-technix requested changes

2023-09-01 13:34 UTC, lego-technix commented on api/sample.env
> +FT_ALWAYS_OK_VALIDATE_NEXT_CHALLENGE_ENDPOINT=true
Personnellement je suis plutôt opposé à un passage à `true` de cette valeur. En effet cela ferait penser qu'il serait normal voire nécessaire dans une utilisation classique de pix `FT_ALWAYS_OK_VALIDATE_NEXT_CHALLENGE_ENDPOINT` soit activé. Or ce FT n'est ni normal ni nécessaire dans le cadre d'une utilisation classique de pix. C'est un FT pour « ouvrir une brèche » dans pix. Et on veut vraiment que l'activation de cette possibilité ne soit pas faite sans qu'il s'agisse d'une action consciente et volontaire.

Que `FT_ALWAYS_OK_VALIDATE_NEXT_CHALLENGE_ENDPOINT` soit activé sur les RA est utile et non risqué, mais cela ne veut pas dire que cela en fait le cas qu'on souhaite par défaut.

2023-09-01 13:37 UTC, lego-technix requested changes

2023-09-01 13:37 UTC, lego-technix commented on api/lib/config.js
> +    config.featureToggles.isAlwaysOkValidateNextChallengeEndpointEnabled = true;
Personnellement je suis plutôt opposé à un passage à true de cette valeur. Ce FT « ouvre une brèche » dans pix. Et on veut vraiment que l'activation de cette possibilité ne soit pas faite sans qu'il s'agisse d'une action consciente et volontaire.

Que FT_ALWAYS_OK_VALIDATE_NEXT_CHALLENGE_ENDPOINT soit activé sur les RA est utile et non risqué, mais cela ne veut pas dire que cela en fait le cas qu'on souhaite par défaut.

2023-09-11 07:33 UTC, francois2metz commented on api/sample.env
> +FT_ALWAYS_OK_VALIDATE_NEXT_CHALLENGE_ENDPOINT=true
Je propose de changer la valeur de FT dans une autre PR. Cela n'a pas de rapport avec la suppression du code susmentionné.

2023-09-11 12:34 UTC, yannbertrand commented on api/sample.env
> +FT_ALWAYS_OK_VALIDATE_NEXT_CHALLENGE_ENDPOINT=true
Done :)

En lien avec https://github.com/1024pix/pix/pull/6835#discussion_r1313037095 également

2023-09-11 12:43 UTC, lego-technix approved these changes
Merci beaucoup pour les modifications.

2023-09-11 12:46 UTC, francois2metz commented on api/lib/config.js
> +    config.featureToggles.isAlwaysOkValidateNextChallengeEndpointEnabled = false;
Il reste ce changement a supprimer

2023-09-11 12:47 UTC, lego-technix commented on api/lib/config.js
> +    config.featureToggles.isAlwaysOkValidateNextChallengeEndpointEnabled = false;
Ce changement est nécessaire pour que les tests passent quand on a activé le FT dans son `.env` local.

2023-09-11 12:53 UTC, lego-technix commented on api/lib/config.js
> +    config.featureToggles.isAlwaysOkValidateNextChallengeEndpointEnabled = false;
Le test `Acceptance | Controller | feature-toggle-controller` est cassé sans cela.

2023-09-11 14:35 UTC, merged