[FEATURE] Refus d'un signalement en direct par le surveillant (PIX-8798).
1024pix/pix pull request #6956
Opened 2023-08-29 05:38 UTC by alexandrecoin

## :unicorn: Problème
> _Décrivez ici le besoin ou l'intention couvert par cette Pull Request._

## :robot: Proposition
> _Ajoutez à cet endroit, si nécessaire, des détails concernant la solution technique retenue et mise en oeuvre, des difficultés ou problèmes rencontrés._

## :rainbow: Remarques
> _Des infos supplémentaires, trucs et astuces ?_

## :100: Pour tester
> _Les instructions pour reproduire le problème, les profils de test, le parcours spécifique à utiliser, etc._

2023-09-08 09:54 UTC, AndreiaPena commented on certif/app/components/session-supervising/candidate-in-list.js
> +    return this.args.candidate.liveAlertStatus !== 'ongoing';
**remarque :** 

Avec ce nom de méthode je m'attend à un === et non pas à un !==

2023-09-08 09:55 UTC, AndreiaPena commented on certif/app/components/session-supervising/candidate-in-list.js
> +    return this.args.candidate.liveAlertStatus !== 'ongoing';
du coup le if devient `if (!this._hasCertificationOngoingLiveAlert)`

2023-09-08 12:40 UTC, AndreiaPena commented on api/lib/application/sessions/index.js
> +          "Elle retourne toutes les infos des candidats d'une session ayant obtenu la certification Clea, sous format CSV",
**Remarque :** il ne s'agit pas de ce que fait la route, c'est un oubli lors d'une duplication visiblement. A modifier :)

2023-09-08 12:41 UTC, AndreiaPena commented on api/lib/domain/usecases/dismiss-live-alert.js
> +export const dismissLiveAlert = async ({ certificationChallengeLiveAlertRepository, sessionId, userId }) => {
**Suggestion/chipotage :** mettre le repo après les autres paramètres
```suggestion
export const dismissLiveAlert = async ({sessionId, userId, certificationChallengeLiveAlertRepository }) => {
```

2023-09-08 12:47 UTC, AndreiaPena commented on api/lib/application/sessions/session-controller.js
> +  const userId = request?.payload?.data?.attributes?.['user-id'];
**Suggestion :** On pourrait faire ça plutôt ? 
```suggestion
  const userId = request.deserializedPayload;
```

2023-09-08 12:49 UTC, AndreiaPena commented on api/lib/domain/usecases/dismiss-live-alert.js
> +  }
**Remarque :** cette gestion devrait être faite dans la méthode de repo et pas dans usecase

2023-09-08 15:06 UTC, P-Jeremy commented on certif/tests/acceptance/session-supervising_test.js
> +        assert.notContains('Aucun signalement en cours pour ce candidat');
```suggestion
      assert.dom(firstVisit.queryByText('Aucun signalement en cours pour ce candidat')).doesNotExist();

2023-09-08 15:11 UTC, AndreiaPena commented on api/lib/infrastructure/repositories/certification-challenge-live-alert-repository.js
> +  return certificationChallengeLiveAlertDtos ? _toDomain(certificationChallengeLiveAlertDtos) : null;
Suite du commentaire sur la gestion de l'erreur dans le repo et non dans le usecase .

Pour moi un `get` devrait trouver un résultat sinon tomber en erreur, un `find` lui peut retourner un tableau vide. 

du coup :
```suggestion
if(!certificationChallengeLiveAlertDtos) {
throw Error();
}
  return _toDomain(certificationChallengeLiveAlertDtos);
```

2023-09-08 15:12 UTC, AndreiaPena commented on api/lib/infrastructure/repositories/sessions/session-for-supervising-repository.js
> +        this.select('*').from('certification-challenge-live-alerts').where({ status: 'ongoing' });
```suggestion
        this.select('*').from('certification-challenge-live-alerts').where({ status: CertificationChallengeLiveAlertStatus.ONGOING });
```

2023-09-08 15:14 UTC, AndreiaPena commented on certif/translations/en.json
> +            "description": "Indiquez au candidat de rafraîchir sa page."
Pas de traduction ? 🧐

2023-09-08 15:14 UTC, AndreiaPena commented on certif/tests/unit/adapters/session_test.js
> +      adapter.ajax = sinon.stub();
```suggestion
// given
      adapter.ajax = sinon.stub();
```

2023-09-08 15:16 UTC, AndreiaPena commented on api/tests/acceptance/application/session/session-controller-dismiss-live-alert_test.js
> +      expect(response.statusCode).to.equal(204);
**Chipotage :** 
un petit //given //when //then dans le test ? 😎

2023-09-08 15:17 UTC, AndreiaPena commented on api/tests/acceptance/application/session/session-controller-dismiss-live-alert_test.js
> +      expect(liveAlert.status).to.equal('dismissed');
```suggestion
      expect(liveAlert.status).to.equal(CertificationChallengeLiveAlertStatus.DISMISSED);
```

2023-09-08 15:24 UTC, P-Jeremy commented on api/tests/acceptance/application/session/session-controller-dismiss-live-alert_test.js
> +      const certificationCenter = databaseBuilder.factory.buildCertificationCenter();
```suggestion
      // given
      const certificationCenter = databaseBuilder.factory.buildCertificationCenter();

2023-09-08 15:25 UTC, P-Jeremy commented on api/tests/acceptance/application/session/session-controller-dismiss-live-alert_test.js
> +      const response = await server.inject(options);
```suggestion
      // when
      const response = await server.inject(options);

2023-09-08 15:25 UTC, P-Jeremy commented on api/tests/acceptance/application/session/session-controller-dismiss-live-alert_test.js
> +      expect(response.statusCode).to.equal(204);
```suggestion
      // then
      expect(response.statusCode).to.equal(204);

2023-09-08 15:28 UTC, P-Jeremy commented on api/tests/integration/infrastructure/repositories/certification-challenge-live-alert-repository_test.js
> +      it('should return null', async function () {
Il manque les les given / when / then ici aussi ;)

2023-09-08 15:29 UTC, P-Jeremy commented on certif/app/components/session-supervising/candidate-in-list.js
> +      this.notifications.error('Une erreur a eu lieue. Merci de réessayer ultérieurement.');
```
      this.notifications.error('Une erreur a eu lieu. Merci de réessayer ultérieurement.');

2023-09-08 15:31 UTC, AndreiaPena commented on api/lib/infrastructure/repositories/certification-challenge-live-alert-repository.js
>  }) {
**Remarque:** 
J'ai parcouru le code mais je n'ai pas trouvé d'usage du domainTransaction lors de cet appel. On peut l'enlever.

```suggestion
const save = async function (certificationChallengeLiveAlert) {
```

2023-09-11 08:14 UTC, AndreiaPena commented
Ping nous quand les retours seront pris pour qu'on fasse un ultime test func :)

2023-09-11 09:47 UTC, cberthou commented on certif/translations/en.json
> +            "description": "Indiquez au candidat de rafraîchir sa page."
Pas encore. On est en attente.

2023-09-11 09:50 UTC, aceol commented on api/lib/domain/usecases/get-assessment.js
> +      liveAlerts.filter((liveAlert) => liveAlert.status === CertificationChallengeLiveAlertStatus.ONGOING).length > 0;
On cherche à savoir s'il y en a au moins 1, un some suffirait
```suggestion
      !liveAlerts.some((liveAlert) => liveAlert.status === CertificationChallengeLiveAlertStatus.ONGOING);
```

2023-09-11 09:50 UTC, aceol commented on api/lib/infrastructure/repositories/sessions/session-for-supervising-repository.js
> +        this.select('*').from('certification-challenge-live-alerts').where({ status: 'ongoing' });
⚠️ Le onExists prends en compte TOUTES les lignes, pas uniquement celle de l'assessment en cours, il faut filtrer pour verifier qu'il existe des ongoing pour cet assessement
(si on a un ongoing sur une autre session, les dismissed ou accepted apparaitront)

2023-09-11 09:50 UTC, aceol commented on certif/app/components/session-supervising/candidate-in-list.js
> +    return this.args.candidate.liveAlertStatus !== 'ongoing';
Je crois qu'on voudrait plutot renommer en 
`get _hasNoCertificationOngoingLiveAlert()`

2023-09-11 09:50 UTC, aceol commented on certif/app/components/session-supervising/candidate-in-list.js
> +  get candidateFullName() {
Note pour plus tard: rajouter un get fullName dans le model CertificationCandidate

2023-09-11 09:50 UTC, aceol commented on api/lib/application/sessions/session-controller.js
> +  const userId = request?.payload?.data?.attributes?.['user-id'];
On fait un `const userId = request?.payload` mais juste au dessus `request.params`, on est pas consistant sur notre confiance!

2023-09-11 09:50 UTC, aceol commented on api/lib/infrastructure/repositories/certification-challenge-live-alert-repository.js
> +const certificationChallengeLiveAlertsTable = 'certification-challenge-live-alerts';
```suggestion
const CERTIFICATION_CHALLENGE_LIVE_ALERTS_TABLE = 'certification-challenge-live-alerts';
```

2023-09-11 09:50 UTC, aceol commented on api/lib/infrastructure/repositories/certification-challenge-live-alert-repository.js
> +  return certificationChallengeLiveAlertDtos ? _toDomain(certificationChallengeLiveAlertDtos) : null;
Si on a un first, on devrait renommer `certificationChallengeLiveAlertDtos` en `certificationChallengeLiveAlertDto`

2023-09-11 09:50 UTC, aceol commented on api/lib/infrastructure/repositories/certification-challenge-live-alert-repository.js
> +};
Pourquoi destructurer?

2023-09-11 09:50 UTC, aceol commented on certif/app/adapters/session.js
> +    const payload = { data: { data: { attributes: { 'user-id': +candidateId } } } };
Le `+` a un interet?
```suggestion
    const payload = { data: { data: { attributes: { 'user-id': candidateId } } } };
```

2023-09-11 09:50 UTC, aceol commented on certif/mirage/config.js
> +    }
C'est un cas tres specifique, pourquoi ne pas le faire pour le test uniquement?
```javascript
this.patch('/sessions/:id/dismiss-live-alert', () => new Response(400)
```

2023-09-11 09:50 UTC, aceol commented on api/lib/infrastructure/repositories/sessions/session-for-supervising-repository.js
> +        this.select('*').from('certification-challenge-live-alerts').where({ status: 'ongoing' });
```suggestion
        this.select('*').from({'certification-challenge-live-alerts': ccla})
         .where({ status: 'ongoing' })
         .whereRaw('ccla.id' = 'certification-challenge-live-alerts.id')
```

2023-09-11 09:50 UTC, aceol commented on api/lib/infrastructure/repositories/sessions/session-for-supervising-repository.js
> +        this.select('*').from('certification-challenge-live-alerts').where({ status: 'ongoing' });
Sinon faire un with() qui recupere uniquement les ongoing

2023-09-11 09:58 UTC, P-Jeremy commented on api/lib/domain/usecases/dismiss-live-alert.js
> +  }
C'est une erreur métier qui vient du domaine, elle doit donc être gérée côté usecase.

2023-09-11 10:06 UTC, P-Jeremy commented on api/lib/infrastructure/repositories/certification-challenge-live-alert-repository.js
> +  return certificationChallengeLiveAlertDtos ? _toDomain(certificationChallengeLiveAlertDtos) : null;
Le fait de ne pas trouver de ongoing live alert n'est pas quelque chose d'incompatible avec le métier, il est préférable d'envoyer null plutôt qu'une erreur

2023-09-11 15:31 UTC, Steph0 commented on api/lib/application/sessions/index.js
> +                'user-id': identifiersType.userId,
Ce paramètre pourrait être dans l'url et la route en serait un peu plus RESTful

path: '/api/sessions/{id}/candidates/{idCandidate}/dismiss-live-alert'

Que l'on peut lire "Je rejette l'alerte du candidat X dans la liste des candidats de la session Y dans la liste des sessions"

2023-09-11 15:31 UTC, Steph0 commented on api/lib/application/sessions/index.js
> +        validate: {
L'API manque un peu de documentation

```suggestion
      config: {
        plugins: {
          'hapi-swagger': {
            produces: ['application/json'],
            consumes: ['application/json'],
          },
        },
        response: {
          failAction: 'log',
          status: {
            204: Joi.string().empty(''),
            401: responseObjectErrorDoc,
            403: responseObjectErrorDoc,
          },
        },
        validate: {
```

J'ai d'ailleurs dû fouiller dans le controller pour trouver que la réponse nominale était une 204.

2023-09-11 15:31 UTC, Steph0 commented on api/lib/application/sessions/index.js
> +      method: 'PATCH',
Y-a-t-il une chose qui empêcherait de créer tout ce nouveau code dans `/src` suite à la clotûre des Tech Days ?

2023-09-11 15:31 UTC, Steph0 commented on api/lib/application/sessions/index.js
> +          'Elle permet de rejeter une alerte relevée par le candidat',
Pinaillage : préciser que c'est dans le cadre de la certif nextGen, ou alors le mettre dans les `tags` ? Tant que nous sommes dans le switch cela pourrait être confus pour les gens

2023-09-11 15:31 UTC, Steph0 commented on api/lib/application/sessions/session-controller.js
> +  const { id: sessionId } = request.params;
Proposition : renommer dans la route le param en `sessionId` et pouvoir faire ici

```suggestion
  const { sessionId } = request.params;
```

2023-09-11 15:31 UTC, Steph0 commented on api/lib/domain/models/CertificationCandidateForSupervising.js
> +    liveAlertStatus = null,
Je me demande si c'est judicieux d'ajouter des param purement nextGen sans aucun usage 'boomers' (ce qui est la PROD actuelle).

Ca m'ennuie ici que l'on modifier le model qui impact la version boomers de Certif pour un truc uniquement NextGen. Cela introduit des risques et impacts sur un contexte fonctionnel qui est pas de l'ordre de la supervision V2.

A noter que je ne dis pas qu'il faut toujours séparer nextGen de certif, mais juste d'être capable de séparer quand on entre dans une fonctionnalité qui est vraiment purement nextGen.

Pour moi la réponse serait de créer une sous-contexte fonctionnel (dossier `src` qui serait de l'ordre de la supervision V3) + un modèle `CertificationCandidtaeForSupervising` qui soit est autonome (et duplique l'actuel) ; soit est un `extend` de la classe pour la V3 (héritage).

Ce ne sont que des propositions bien sûr de solutions, d'autres stratégies sont possibles.

Mon point ici est que j'ai peur que si on commence à mixer des usages qui n'ont aucun apport à la boomers, que l'on commence vraiment à faire du gloubiboulgua et que la version 'boomers' se retrouve dans de la maintenance de trucs V3 dans son périmètre actuel.

2023-09-11 15:31 UTC, Steph0 commented on api/lib/domain/models/CertificationChallengeLiveAlert.js
> +};
```suggestion
const CertificationChallengeLiveAlertStatus = Object.freeze({
  ONGOING: 'ongoing',
  DISMISSED: 'dismissed',
  ACCEPTED: 'accepted',
});
```

2023-09-11 15:31 UTC, Steph0 commented on api/lib/domain/usecases/dismiss-live-alert.js
> +    throw new NotFoundError();
Je propose de mettre un message, ça sera cool d'avoir un truc explicite dans les logs si jamais ça se produit.

```suggestion
    throw new NotFoundError("The challenge is not currently in alert");
```

2023-09-11 15:31 UTC, Steph0 commented on .circleci/config.yml
> +      - run: npm ci --loglevel silly
Pourquoi mettre le log level aussi haut ?

2023-09-11 15:31 UTC, Steph0 commented on api/lib/domain/usecases/get-assessment.js
> +    );
Si j'ai bien compris mes dernières discussions avec @Sims07 ceci peut décaler dans l'entité `Assessment`

2023-09-11 15:31 UTC, Steph0 commented on api/lib/infrastructure/repositories/certification-challenge-live-alert-repository.js
> +    .onConflict(['id'])
Cela me semble dangereux de faire un onConflict sur l'id d'un save. Ca risque pas de remplacer une alerte qui a rien a voir mais qui avait pris cet id ? 
Quel est le contexte qui nécessite le positionnement du onConflict ?

2023-09-11 15:31 UTC, Steph0 commented on api/lib/infrastructure/repositories/certification-challenge-live-alert-repository.js
> +const CERTIFICATION_CHALLENGE_LIVE_ALERTS_TABLE = 'certification-challenge-live-alerts';
Je trouve que mettre ce nom de table en const complexifie la lecture inutilement de ce fichier

```suggestion

```

2023-09-11 15:31 UTC, Steph0 commented on api/lib/infrastructure/repositories/certification-challenge-live-alert-repository.js
> +  return certificationChallengeLiveAlertDto ? _toDomain(certificationChallengeLiveAlertDto) : null;
Je propose de déplacer le renvoie à `null` dans le _toDomain

2023-09-11 15:31 UTC, Steph0 commented on api/lib/infrastructure/repositories/sessions/session-for-supervising-repository.js
> +      qb.select('*')
Pinaillage par habitude de pas mettre d'abbréviation même pour les trucs évidents

```suggestion
    .with('ongoing-live-alerts', (queryBuilder) => {
      queryBuilder.select('*')
```

2023-09-11 15:31 UTC, Steph0 commented on api/tests/acceptance/application/session/session-controller-dismiss-live-alert_test.js
> +describe('Acceptance | Controller | sessions-controller', function () {
J'ai l'impression qu'il manque un test quelque part pour couvrir la vérification du prehandler sur le rejet d'un non supervisor

2023-09-11 15:31 UTC, Steph0 commented on certif/tests/unit/adapters/session_test.js
> +        adapter.ajax.calledWith(`http://localhost:3000/api/sessions/${sessionId}/dismiss-live-alert`, 'PATCH', payload),
Proposition : éviter de rendre fix la notion de localhost et encore plus de port dans un test

```suggestion
        adapter.ajax.calledWith(`${ENV.APP.API_HOST}/api/sessions/${sessionId}/dismiss-live-alert`, 'PATCH', payload),
```

2023-09-11 15:31 UTC, Steph0 commented on certif/translations/en.json
> +        },
🎌 Pour du FR ici ?

2023-09-11 15:31 UTC, Steph0 commented on certif/app/components/session-supervising/handle-live-alert-modal.hbs
> +<PixModal
Au  vu de la structure, je suis d'avis de séparer en deux composants distinct la modale "ask" et "rejected".
Dans ce composent "tout en un" quasi toute l'intelligence est conditionnée ce qui rend la + complexe, et n'est commun aux deux modales que du très basique

2023-09-11 15:31 UTC, Steph0 commented on api/lib/application/sessions/session-controller.js
> +  const { userId } = request.deserializedPayload;
🎌 Comme c'est pour de la traçabilité je pense que l'on ne peut pas faire confiance au payload, je propose d'utiliser ce qui est fait dans les autres API

```suggestion
  const { userId } = request.auth.credentials;
```

2023-09-12 08:02 UTC, Steph0 commented on api/lib/application/sessions/index.js
> +                'user-id': identifiersType.userId,
EN fait en lisant le reste de la PR, le payload et le path param peut complètement disparaitre (et devrait) en faveur de tirer le userId depuis le token d'auth

2023-09-12 08:15 UTC, AndreiaPena commented on api/lib/application/sessions/session-controller.js
> +  const { userId } = request.deserializedPayload;
si tu fait le `auth.credentials`, tu récupères le userId du surveillant. Or on souhaite le userId du candidat, qu'on récupère dans le payload ici

2023-09-13 08:15 UTC, cberthou commented on certif/translations/en.json
> +        },
Les traductions arriveront plus tard. En attendant, on laisse le français en placeholder.

2023-09-13 08:27 UTC, cberthou commented on api/lib/domain/usecases/get-assessment.js
> +    );
C'est envisageable. Dans ce cas, il faut ajouter une méthode `.attachLiveAlerts` à l'Assessment.

2023-09-13 14:53 UTC, cberthou commented on api/lib/application/sessions/index.js
> +      method: 'PATCH',
Rien n'empêche, mais la PR a été ouverte avant, donc c'est pas mal de boulot de tout déplacer maintenant.

2023-09-13 14:57 UTC, cberthou commented on api/lib/application/sessions/index.js
> +                'user-id': identifiersType.userId,
L'id candidat est différent du userId (qui est l'ID du surveillant). Mais le premier changement sur l'URL est top.

2023-09-13 15:16 UTC, cberthou commented on api/lib/infrastructure/repositories/certification-challenge-live-alert-repository.js
> +    .onConflict(['id'])
L'idée est de faire un upsert.

Les certificationChallengeLiveAlerts ne sont jamais supprimées, donc elles conservent leur id indéfiniment.

2023-09-18 09:37 UTC, AndreiaPena commented
A11Y : le contraste n'est pas assez élevé pour l'élément 

<img width="624" alt="Capture d’écran 2023-09-18 à 11 34 27" src="https://github.com/1024pix/pix/assets/58915422/e6b3e80d-5b77-4fb3-9b28-944394689d57">

2023-09-18 09:39 UTC, AndreiaPena commented
**Question :** Est-ce qu'on veut garder "Signaler un problème avec la question" quand un signalement est en cours ?
Parce qu'on peut cliquer dessus mais ça ne donne rien. C'est assez confusant.

<img width="533" alt="Capture d’écran 2023-09-18 à 11 35 10" src="https://github.com/1024pix/pix/assets/58915422/7da16d30-6575-4d0c-b456-80abd0ec6443">

2023-09-18 09:52 UTC, AndreiaPena requested changes
**Question :** cette nouvelle gestion de signalement n'apparaît pas pour une certification V2 coté Pix App ✅ car c'est propre à la V3 mais ce n'est pas géré dans l'espace surveillant.

On voit l'option "Gérer un signalement" alors qu'ils n'y auront jamais accès.
Il faut le conditionner pour ne pas que les utilisateurs voient cette option tant qu'on est pas passé en V3 en prod.

<img width="619" alt="Capture d’écran 2023-09-18 à 11 50 03" src="https://github.com/1024pix/pix/assets/58915422/c3f8a5fc-c182-45f1-b243-026fe366c8ce">

2023-09-19 14:12 UTC, Steph0 approved these changes

2023-09-21 08:14 UTC, AndreiaPena commented
Testé dans un cas de V2, on ne voit pas la ligne "Gérer le signalement" ✅ 
<img width="809" alt="Capture d’écran 2023-09-21 à 10 06 36" src="https://github.com/1024pix/pix/assets/58915422/0d600edb-5471-4c21-b84d-eeeba678d631">

On ne voit plus le bouton ✅ 
<img width="572" alt="Capture d’écran 2023-09-21 à 10 09 27" src="https://github.com/1024pix/pix/assets/58915422/e296b825-2f54-4b19-95ff-f8e335bf5744">


Dans une certif V3, Jean Jean n'a pas la ligne car pas concerné ✅ 
En revanche je peut signaler sur Don Don ✅ 
<img width="643" alt="Capture d’écran 2023-09-21 à 10 09 52" src="https://github.com/1024pix/pix/assets/58915422/76f09857-a6ce-41f6-9e48-acc9f91bc814">
<img width="643" alt="Capture d’écran 2023-09-21 à 10 09 56" src="https://github.com/1024pix/pix/assets/58915422/3afd0004-7c43-4556-84d3-ef599a7c4d62">

2023-09-21 08:15 UTC, AndreiaPena approved these changes

2023-09-21 08:30 UTC, aceol approved these changes

2023-09-21 08:32 UTC, AndreiaPena commented
**Tout dernier retour (vu avec Anne So qui a confirmé) :** 

L'encadré indiquant que tout s'est bien déroulé devrait être vert plutôt que rouge.

<img width="643" alt="Capture d’écran 2023-09-21 à 10 10 07" src="https://github.com/1024pix/pix/assets/58915422/65fa98f1-480e-4e13-b4c1-043b9c3898f3">

2023-09-22 08:29 UTC, merged