[TECH] Supprimer la colonne "lastLoggedAt" de la table "Users" (PIX-9032)
1024pix/pix pull request #6983
Opened 2023-09-04 06:55 UTC by igorissen

## :unicorn: Problème

Cette PR est la dernière étape de la tâche demandant de déplacer la colonne lastLoggedAt depuis la table users vers la table user-logins.

1. Ajout de la colonne lastLoggedAt dans la table user-logins et alimentation de cette nouvelle colonne #6952 
2. Ajout d'un script à faire tourner en production pour synchroniser l'ancienne colonne (users.lastLoggedAt) vers la nouvelle (user-logins.lastLoggedAt) uniquement si aucune valeur existe sur cette dernière #6958 
3. Ne plus mettre à jour la colonne lastLoggedAt de la table users #6977 
4. Ajout d'un script de migration de base de données (cette PR)

## :robot: Proposition

Supprimer la colonne **lastLoggedAt** de la table **users**.

## :rainbow: Remarques

RAS

## :100: Pour tester

Test à faire sur votre machine

- Exécuter la commande de migration `npm run db:migrate`
- Constater en base de données que le schema de la table users a bien été modifié (colonne lastLoggedAt supprimée)
- Exécuter la commande de rollback `npm run db:rollback:latest`
- Constater en base de données que le schema de la table users a bien été modifié (colonne lastLoggedAt ajoutée)

2023-09-04 08:57 UTC, lego-technix approved these changes
✅ Testé fonctionnellement avec succès

2023-09-04 11:56 UTC, lego-technix commented
À noter que le script `npm run db:reset` ne fonctionne actuellement pas car ce script appelle les fonctions « buildUser » du common-builder qui utilisent encore la propriété `lastLoggedAt`, fonctionnement qui est modifié avec la PR #6977.

Donc cette PR sera complètement fonctionnelle lorsque la PR #6977 aura été mergée sur `dev` et que cette PR-ci aura été rebasée sur `dev`.

2023-09-04 16:24 UTC, EmmanuelleBonnemay approved these changes
Commandes migrate et rollback s'exécutent correctement. Commande reset ne fonctionne pas comme documenté @lego-technix

2023-09-14 09:39 UTC, lego-technix requested changes
Regénérer cette migration avec une nouvelle date plus récente pour que cette migration apparaisse après les autres migrations liées à `lastLoggedAt`.

2023-09-14 09:44 UTC, lego-technix approved these changes
✅ Bonne date pour la migration

2023-09-18 08:02 UTC, merged