[FEATURE][ADMIN] Permettre la modification du rôle d'un membre d'un centre de certification (PIX-4996)
1024pix/pix pull request #7055
Opened 2023-09-12 12:03 UTC by igorissen

## :unicorn: Problème

Actuellement, il n'est pas possible pour un agent Pix de modifier le rôle d'un membre d'un centre de certification.

## :robot: Proposition

Permettre la modification du rôle d'un membre d'un centre de certification.

## :rainbow: Remarques

Nous nous sommes basés sur ce qui a été fait sur la liste des membres d'une organisation avec quelques modifications.

## :100: Pour tester

- Se connecter à Pix Admin (par exemple la RA https://admin-pr7055.review.pix.fr/) avec le compte suivant
```superadmin@example.net```
- Ouvrir la page `Centres de certification`
- Ouvrir la page de détail du centre `Accèssorium`
- Constater l'affichage d'un tableau en bas de page contenant la liste des membres du centre (2 membres)
- Choisir un membre et modifier son rôle
- Valider votre choix
- Constater l'affichage d'une notification de succès
- Constater la mise à jour du rôle du membre que vous avez sélectionné

2023-09-14 14:57 UTC, clemlatz commented on api/tests/integration/infrastructure/repositories/certification-center-membership-repository_test.js
> +      const certificationCenterMembershipToUpdate = databaseBuilder.factory.buildCertificationCenterMembership();
**suggestion**: préciser le rôle, même si c'est le rôle par défaut, pour qu'on voit clairement que le rôle a changé juste en lisant le test

```suggestion
      const certificationCenterMembershipToUpdate = databaseBuilder.factory.buildCertificationCenterMembership({ role: 'MEMBER' });
```

2023-09-14 14:57 UTC, clemlatz commented on api/lib/infrastructure/repositories/certification-center-membership-repository.js
> +    throw new NotFoundError(`Cet ID ${certificationCenterMembershipId} est invalide`);
**suggestion**: lever une erreur avec un message en anglais

```suggestion
    throw new NotFoundError(`Cannot find a certification center membership for id ${certificationCenterMembershipId}`);
```

2023-09-14 14:57 UTC, clemlatz commented on api/tests/integration/infrastructure/repositories/certification-center-membership-repository_test.js
> +        expect(error).to.be.instanceof(NotFoundError);
**suggestion**: tester le message d'erreur

```suggestion
        expect(error).to.be.instanceof(NotFoundError);
        expect(error.message).to.equal(`Cannot find a certification center membership for id ${certificationCenterMembership.id}`);
```

2023-09-14 14:57 UTC, clemlatz commented on api/tests/integration/infrastructure/repositories/certification-center-membership-repository_test.js
> +      clock = sinon.useFakeTimers(now);
**question**: est-ce qu'on a besoin de clock ici ? J'ai pas l'impression qu'on utilise `Date` dans la méthode du repo.

2023-09-14 14:57 UTC, clemlatz commented on api/tests/unit/infrastructure/serializers/jsonapi/certification-center-membership-serializer_test.js
> +      expect(certificationCenterMembership).to.deep.equal(expectedCertificationCenterMembership);
```suggestion
      expect(certificationCenterMembership).to.deepEqualInstance(expectedCertificationCenterMembership);
```

2023-09-14 14:57 UTC, clemlatz commented on api/lib/application/certification-center-memberships/certification-center-membership-controller.js
> +  }
**question**: je me demande si c'est utile d'envoyer deux ids dans la requête et de les comparer. On pourrait juste se baser sur l'un des deux et ignorer l'autre ?

2023-09-14 14:58 UTC, clemlatz commented
✅ Tests fonctionnels OK sous Chrome (mais pas eu le temps encore de faire la revue du front)

2023-09-14 15:20 UTC, lego-technix requested changes

2023-09-14 15:20 UTC, lego-technix commented on admin/app/components/certification-centers/membership-item-actions.hbs
> +    </PixButton>
Très léger dysfonctionnement au niveau de l'UI : si on appuie sur le bouton « Modifier le rôle », qu'on change le rôle et qu'on fait « Annuler », le bouton porte la valeur modifiée du rôle alors qu'on a annulé. C'est juste un problème d'affichage.

2023-09-14 15:45 UTC, igorissen commented on api/lib/application/certification-center-memberships/certification-center-membership-controller.js
> +  }
Vu que l'on fait un PATCH sur un élément l'ID sera toujours dans l'URL. De plus EmberData utilise JSON API comme spec, ce qui entraine la duplication d'information.

2023-09-14 15:47 UTC, igorissen commented on admin/app/components/certification-centers/membership-item-actions.hbs
> +    </PixButton>
Oui, j'ai oublié d'ajouter le `rollbackAttributes()` lorsque l'on annule la modification. Et il faudra que je le fasse uniquement si le model à été modifié.

2023-09-15 13:19 UTC, lego-technix commented on admin/app/components/certification-centers/membership-item-actions.hbs
> +    </PixButton>
✅ Testé fonctionnellement avec succès avec Firefox

2023-09-15 13:21 UTC, lego-technix approved these changes
✅ Testé fonctionnellement avec succès avec Firefox

2023-09-15 13:49 UTC, lego-technix commented on api/tests/acceptance/application/certification-center-memberships/certification-center-membership-controller_test.js
> +          'when provider certification center membership ID is different from the one in the payload',
```suggestion
          'when given certification center membership ID is different from the one in the payload',
```

2023-09-19 07:26 UTC, clemlatz commented on api/lib/application/certification-center-memberships/certification-center-membership-controller.js
> +  }
Oui Ember envoie les deux et je ne pense pas qu'on puisse faire autrement. Mais on pourrait en ignorer un des deux côté API.

2023-09-19 08:05 UTC, igorissen commented on api/lib/application/certification-center-memberships/certification-center-membership-controller.js
> +  }
Comme je disais au daily, Ember fourni les 2 mais lorsqu'une personne tente de faire l'appel sans passer par l'application, je pense que c'est quand même une bonne idée de vérifier si l'ID du payload est le même que celui de l'URL. Cela permet de vérifier que l'on modifiera la bonne ressource.

2023-09-19 08:43 UTC, lego-technix commented on api/lib/application/certification-center-memberships/certification-center-membership-controller.js
> +  }
Même si un seul de ces ID est nécessaire, à partir du moment où on a pas le choix d'avoir ces 2 ID, je suis aussi pour qu'on s'assure de la cohérence de ces 2 valeurs.

2023-09-20 09:54 UTC, er-lim commented on api/tests/unit/domain/models/CertificationCenterMembership_test.js
> +    it('update certification center membership "role" and "updatedByUserId" attributes', async function () {
```suggestion
    it('updates certification center membership "role" and "updatedByUserId" attributes', async function () {
```

2023-09-20 09:54 UTC, er-lim commented on admin/app/components/certification-centers/membership-item-role.hbs
> +    @label="Sélectionner un rôle"
Suggestion : 
Mettre le texte dans le fichier de traduction `fr.json`

2023-09-20 09:54 UTC, er-lim commented on admin/app/components/certification-centers/membership-item-actions.hbs
> +      Enregistrer
Suggestion: 
Mettre le texte dans le fichier de traduction (pareil pour les textes en dur en bas).

2023-09-20 09:54 UTC, er-lim commented on admin/app/controllers/authenticated/certification-centers/get/team.js
> +      this.notifications.success('Le rôle du membre a été modifié.');
mettre les textes en dur dans la fonction dans le fichier de traduction `fr` et `en.json`

2023-09-20 09:56 UTC, er-lim commented on api/lib/infrastructure/repositories/certification-center-membership-repository.js
> +  return _toDomain(updatedCertificationCenterMembership);
Remarque : 
Je n'ai pas l'impression qu'on va exploiter l'objet du domaine CertificationCenterMembership retourné vu qu'il manque la partie `user`, `certification-center`.

Est-ce qu'il ne faudrait pas faire un findById ici pour avoir un objet valide et donc l'exploiter dans le usecase ?

2023-09-20 10:35 UTC, igorissen commented on api/lib/infrastructure/repositories/certification-center-membership-repository.js
> +  return _toDomain(updatedCertificationCenterMembership);
Je vais retirer le retour parce que je ne l'utilise pas par la suite. J'utilise l'appel à findById dans le usecase pour récupérer le model modifié.

2023-09-21 11:56 UTC, er-lim approved these changes

2023-09-21 11:56 UTC, er-lim commented
Tests fonctionnels sur Chrome & Firefox ✅

2023-09-21 12:06 UTC, merged