[FEATURE] Ajouter le SSO Pays de la Loire (PIX-9309).
1024pix/pix pull request #7146
Opened 2023-09-25 13:34 UTC by Thomasevano

## :unicorn: Problème
Nous voulons ajouter Pays de la Loire comme SSO

## :robot: Proposition
Créer un nouveau service OIDC et ajouter les variables d'environnements

## :rainbow: Remarques
Penser a ajouter les variables d'environnements en recette

## :100: Pour tester
Il n'est pas possible de tester le SSO via les RA

2023-09-25 14:04 UTC, lego-technix requested changes, later dismissed

2023-09-25 14:04 UTC, lego-technix commented on api/lib/domain/services/authentication/pays-de-la-loire-oidc-authentication-service.js
> +}
Ne pas mettre les fonctions getRedirectLogoutUrl et saveIdToken car le logout de PDL est un logout standard (RP-Initiated Logout) et non un logout custom. Et le logout standard (RP-Initiated Logout) sera implémenté plus tard dans la brique générique.

2023-09-25 14:08 UTC, lego-technix commented
Globalement je pense qu'il faudrait traiter tous les noms de SSO comme des chaînes de caractères de type token, sans sens, et donc écrire `paysdelaloire` au lieu `paysDeLaLoire` et `PAYSDELALOIRE` au lieu de `PAYS_DE_LA_LOIRE`, etc. En effet du point de vue de Pix ces chaînes de caractères n'ont aucun sens et ne doivent pas en avoir et par contre il est important qu'il y ait un `_` devant le mot `ENABLED` de variables d'environnement comme `PAYSDELALOIRE_ENABLED`.

Cela n'a pas été fait comme ça avec `POLE_EMPLOI`, mais ce n'est pas parce que (possiblement) nous nous sommes trompés une fois qu'il faut recommencé. À discuter en équipe.

2023-09-26 09:28 UTC, er-lim commented on api/lib/domain/services/authentication/pays-de-la-loire-oidc-authentication-service.js
> +class paysDeLaLoireOidcAuthenticationService extends OidcAuthenticationService {
```suggestion
class PaysDeLaLoireOidcAuthenticationService extends OidcAuthenticationService {
```

2023-09-29 12:45 UTC, lego-technix requested changes

2023-09-29 12:45 UTC, lego-technix commented on api/lib/config.js
> +    },
Dans tous les fichiers modifiés, traiter tous les noms de SSO comme des chaînes de caractères de type token, sans sens, en tant que « boîte noire » et donc écrire `paysdelaloire` au lieu `paysDeLaLoire` et `PAYSDELALOIRE` au lieu de `PAYS_DE_LA_LOIRE`, etc.

2023-09-29 16:50 UTC, lego-technix requested changes
Il manque encore 2 dernières occurrences de chaînes de caractères `pays-de-la-loire` qui devraient être `paysdelaloire`. Désolé, je n'avais pas listé cette modification explicitement, j'avais juste mis « etc. ». Donc encore ces 2 dernières et cela devrait être bon.

2023-09-29 16:50 UTC, lego-technix commented on api/lib/domain/services/authentication/authentication-service-registry.js
> +import { PaysdelaloireOidcAuthenticationService } from './pays-de-la-loire-oidc-authentication-service.js';
```suggestion
import { PaysdelaloireOidcAuthenticationService } from './paysdelaloire-oidc-authentication-service.js';
```

2023-09-29 16:50 UTC, lego-technix commented on api/lib/domain/services/authentication/pays-de-la-loire-oidc-authentication-service.js
> +      slug: 'pays-de-la-loire',
```suggestion
      slug: 'paysdelaloire',
```

2023-10-02 06:49 UTC, lego-technix commented
> Il manque encore 2 dernières occurrences de chaînes de caractères `pays-de-la-loire` qui devraient être `paysdelaloire`. Désolé, je n'avais pas listé cette modification explicitement, j'avais juste mis « etc. ». Donc encore ces 2 dernières et cela devrait être bon.

Je viens de faire un commit fixup pour modifier cela.

2023-10-02 06:49 UTC, lego-technix approved these changes

2023-10-02 06:56 UTC, igorissen commented on api/lib/domain/services/authentication/pays-de-la-loire-oidc-authentication-service.js
> +      slug: 'pays-de-la-loire',
J'arrive après la bataille mais cette modification devrait dans ce cas entrainer une modification de la propriété `slug`. Le slug, normalement pour Pays de la Loire aurait du être `pays-de-la-loire`. Comme exemple on peut prendre le titre d'un article d'un blog, l'URL contient le `slug` du titre de l'article.

2023-10-02 07:00 UTC, lego-technix commented on api/lib/domain/services/authentication/pays-de-la-loire-oidc-authentication-service.js
> +      slug: 'pays-de-la-loire',
Dans une optique systématique et d'industrialisation, l'idée est que toutes les valeurs concernant l'identity provider soient des « boîtes noires » sans sens, sauf pour l'`organizationName`. Donc le slug devant être une boîte noire aussi, il doit être `paysdelaloire`.

2023-10-02 07:14 UTC, igorissen commented on api/lib/domain/services/authentication/pays-de-la-loire-oidc-authentication-service.js
> +      slug: 'pays-de-la-loire',
Si cela doit être une `boîte noire`, je me trompes peut être, alors le slug devrait être une valeur aléatoire n'ayant aucun sens pour les utilisateurs.

2023-10-02 07:19 UTC, lego-technix commented
> 
> Je viens de faire un commit fixup pour modifier cela.

Pour info, j'ai dû mettre à jour avec la nouvelle arborescence `src/shared` et les commits fixup ont tous été squashés et pourtant je n'ai pas fait `git rebase -i --autosquash origin/dev`, j'ai uniquement fait `git rebase -i origin/dev`.

2023-10-06 10:08 UTC, igorissen commented
Comme exemple de l'utilisation du slug, voici une capture de la documentation de l'api du service Trakt.tv.
Pour récupérer les détails d'un film, on peut utiliser l'id technique de Trakt, le slug (parle au humain), l'id technique de TMDB (TheMovieDatabase) ou l'id technique de IMDB (InternetMovieDatabase).

![Screenshot 2023-10-06 at 11 57 44](https://github.com/1024pix/pix/assets/6919604/ecde7023-1af8-457e-9dd2-a0f2135e00f6)


> https://app.domain.net/connexion/pays-de-la-loire

claire, lisible et compréhensible pour l'humain

> https://app.domain.net/connexion/suTy7_gA23

incompréhensible pour l'humain et assez douteux, potentiellement plus compliqué pour les devs à faire le lien entre cet identifiant et un fournisseur d'identité

2023-10-06 14:21 UTC, igorissen approved these changes

2023-10-06 14:58 UTC, merged