[DOCS] Mise à jour du Contributing.MD.
1024pix/pix pull request #7164
Opened 2023-09-27 13:14 UTC by MelanieMEB

## :unicorn: Problème
Le contributing.md n'était pas à jour.
De plus, la question du nombre d'approvals nécessaire à un merge est souvent remontée.

## :robot: Proposition
Rendre le contributing.md plus cohérent avec nos approches actuelles
Proposer des règles pour le nombre d'approvals pour un merge.

## :rainbow: Remarques
Pas de remques

## :100: Pour tester
Document : pas de test précis.

2023-09-27 13:19 UTC, mickaelalibert reviewed
Nitpick d'ortographe 👼

2023-09-27 13:19 UTC, mickaelalibert commented on CONTRIBUTING.md
> +On suit la convention que la description doit marcher comme une fin de phraseà `Une fois mergée, cette _pull request_ permettra de …`.
```suggestion
On suit la convention que la description doit marcher comme une fin de phrase à `Une fois mergée, cette _pull request_ permettra de …`.
```

2023-09-27 13:19 UTC, mickaelalibert commented on CONTRIBUTING.md
> +- tous les checks de la CI soit verts : les applications se sont déployées, les tests sont passés ;
```suggestion

- tous les checks de la CI soient verts : les applications se sont déployées, les tests sont passés ;
```

2023-09-27 13:19 UTC, mickaelalibert commented on CONTRIBUTING.md
> +Le nombre d'approve peut légèrement changer selon les cas :
```suggestion
Le nombre de validations attendu peut légèrement changer selon les cas :

```

2023-09-27 15:32 UTC, aceol approved these changes

2023-09-27 15:32 UTC, aceol commented on CONTRIBUTING.md
> +Le format à respecter est le suivant : `[<TAG>] <DESCRIPTION> (<US_ID>).`, ex : "[FEATURE] Création de compte (PIX-987)."
Comment gerer cette notion de US_ID pour l'exterieur? (pas d'acces à JIRA)

2023-09-27 15:32 UTC, aceol commented on CONTRIBUTING.md
> +L'utilisation des spécifications `Conventional Commits` est accepté actuellement, mais encore utilisé dans tous les commits.
```suggestion
L'utilisation des spécifications `Conventional Commits` est accepté actuellement, mais pas encore utilisé dans tous les commits.
```

2023-09-27 15:32 UTC, aceol commented on CONTRIBUTING.md
> +- Si la PR a été réalisé à plusieurs, il faut au moins 1 *approval* en plus des personnes ayant participé. Si l'équipe n'est pas assez grande : les 2 *approvals* peuvent être donnés par les personnes
❤️

2023-09-28 09:44 UTC, cberthou requested changes
Super mise à jour, c'était nécessaire. Un petit point à creuser pour moi.

2023-09-28 09:44 UTC, cberthou commented on CONTRIBUTING.md
> +Pour qu'une pull-request soit acccepté et puisse être mergé, il faut que :
```suggestion
Pour qu'une pull-request soit accceptée et puisse être mergée, il faut que : 
```

2023-09-28 09:44 UTC, cberthou commented on CONTRIBUTING.md
> +L'utilisation des spécifications `Conventional Commits` est accepté actuellement, mais encore utilisé dans tous les commits.
Un peu flou. On ne dit pas si on a pour objectif de le généraliser, même si il n'est pas encore tout le temps utilisé, ou si c'est une recommandation simple, mais que ça n'a pas vraiment d'importance.

2023-09-28 12:52 UTC, yannbertrand commented on CONTRIBUTING.md
> +Pour qu'une pull-request soit acccepté et puisse être mergé, il faut que :
```
Pour qu'une pull-request soit acceptée et puisse être mergée, il faut que : 
```
On va s'en sortir :p

2023-09-28 13:04 UTC, yannbertrand commented on CONTRIBUTING.md
> +BUMP | PR relative à des montées de versions
Merci pour l'ajout 👍

2023-10-12 13:54 UTC, thloesch commented on CONTRIBUTING.md
> +L'organisation GitHub [1024pix](https://github.com/1024pix) héberge le code utilisé dans le projet [Pix](https://pix.fr). Les dépôts GitHub de l'organisation sont en évolution rapide et développés pa
```suggestion
L'organisation GitHub [1024pix](https://github.com/1024pix) héberge le code utilisé dans le projet [Pix](https://pix.fr). Les dépôts GitHub de l'organisation sont en évolution rapide et développés par plusieurs équipes dédiées chez Pix. Le dépôt GitHub [1024pix/pix](https://github.com/1024pix/pix) est la source canonique de nos équipes. Les développements que nous réalisons sont exclusivement dédiés à l'amélioration de la plateforme [Pix](https://pix.fr) et nous ne travaillons pas à l'heure actuelle à une version générique utilisable par toutes et tous pour d'autres usages.
```

2023-10-12 13:57 UTC, thloesch commented on CONTRIBUTING.md
> +L'utilisation des spécifications `Conventional Commits` est recommandé actuellement, mais n'est pas encore généralisé dans tous les commits.
```suggestion
L'utilisation des spécifications `Conventional Commits` est recommandée actuellement, mais n'est pas encore généralisée dans tous les commits.
```

2023-10-12 13:59 UTC, thloesch commented on CONTRIBUTING.md
> +- Si la PR a été réalisé à plusieurs, il faut au moins 1 *approval* en plus des personnes ayant participé. Si l'équipe n'est pas assez grande : les 2 *approvals* peuvent être donnés par les personnes
```suggestion
- Si la PR a été réalisée à plusieurs, il faut au moins 1 *approval* en plus des personnes ayant participé. Si l'équipe n'est pas assez grande : les 2 *approvals* peuvent être donnés par les personnes ayant participé : nous conseillons fortement de ne pas merger directement après le développement et de faire la review de sa propre PR à tête reposée.
```

2023-10-12 14:01 UTC, thloesch approved these changes

2023-10-12 14:08 UTC, merged