[FEATURE] [Certif] Afficher le bouton et la page pour envoyer une invitation (PIX-134)
1024pix/pix pull request #7173
Opened 2023-09-28 11:52 UTC by lego-technix

## :unicorn: Problème
> _Décrivez ici le besoin ou l'intention couvert par cette Pull Request._

## :robot: Proposition
> _Ajoutez à cet endroit, si nécessaire, des détails concernant la solution technique retenue et mise en oeuvre, des difficultés ou problèmes rencontrés._

## :rainbow: Remarques
> _Des infos supplémentaires, trucs et astuces ?_

## :100: Pour tester
> _Les instructions pour reproduire le problème, les profils de test, le parcours spécifique à utiliser, etc._

2023-09-28 12:34 UTC, lego-technix commented
À FAIRE : 
* Reprendre le layout des 2 boutons pour que les 2 boutons soient alignés à droite
* Corriger une régression qui a fait disparaître la 3ème colonne « Référent »
* Voir si on peut transformer le test d'acceptance 'it displays an invite a member button' en test d'intégration

2023-09-29 09:14 UTC, lego-technix commented on certif/app/router.js
> +      this.route('invite', { path: '/inviter' });
TODO : Actuellement cette route n'a pas son accès protégé pour que seuls les admins y accèdent. C'est à corriger.

2023-09-29 12:55 UTC, reibecca commented on certif/app/templates/authenticated/team/invite.hbs
> +  </p>
**chipotage :** changer la font du texte présent au dessus du formulaire d'invitation en 14px au lieu de 16px (possibilité d'utiliser le placeholder  `@extend %pix-body-s`

2023-09-29 12:56 UTC, reibecca commented on certif/translations/fr.json
> +      "invite-button": "Inviter un membre",
**chipotage :** modifier le wording du bouton pour envoyer une invitation en écrivant simplement "inviter" comme sur pix orga, comme on aura la possibilité d'inviter un ou plusieurs membres

2023-09-29 12:59 UTC, reibecca approved these changes
✅ Testé fonctionnellement sur Chrome et Safari

2023-09-29 13:14 UTC, Thomasevano commented on certif/tests/acceptance/team_test.js
> +    module('when visiting "/equipe/invitations" unauthorized URL', function () {
```suggestion
    module('when visiting "/equipe/invitations" as an unauthorized user', function () {
```

2023-09-29 13:14 UTC, Thomasevano commented on certif/tests/acceptance/team_test.js
> +    module('when visiting "/equipe/inviter" unauthorized URL', function () {
```suggestion
    module('when visiting "/equipe/inviter" as an unauthorized user', function () {
```

2023-09-29 14:39 UTC, Steph0 commented
# Test func

Se connecter dans [Pix Certif](https://certif-pr7173.review.pix.fr/) avec un compte ayant le rôle d'Admin dans une organisation (par exemple james-paledroits@example.net) ✅ 

Constater que dans cette équipe un nouveau bouton Inviter un membre est affiché à droite✅ 

Cliquer sur ce bouton et constater qu'on est redirigé vers une nouvelle page Inviter un membre✅ 
![image](https://github.com/1024pix/pix/assets/170271/49f2e0ae-39f0-4c38-8b6f-d0f742821671)

Se déconnecter ✅

Se connecter dans [Pix Certif](https://certif-pr7173.review.pix.fr/) avec un compte ayant le rôle de Membre dans une organisation (par exemple marc-alex-terrieur@example.net)✅
Constater que dans cette équipe le nouveau bouton Inviter un membre n'est affiché✅

Faire cette manipulation à la fois sur une organisation « CLEA » et sur une organisation non-« CLEA ». La colonne Référent doit s'afficher pour les organisations « CLEA ».

CLEA ✅ 
![image](https://github.com/1024pix/pix/assets/170271/fd1eb5c5-df01-4ad5-98f3-7ca867b794f6)
![image](https://github.com/1024pix/pix/assets/170271/fccf8e79-88fa-4d0f-a492-c9d1e37f4235)

PAS CLEA ❌ 

![image](https://github.com/1024pix/pix/assets/170271/947a198b-0476-4203-a57c-f2fc0d0705ee)
![image](https://github.com/1024pix/pix/assets/170271/2127dd4c-3bb0-48c1-b967-c9b8005c026f)
![image](https://github.com/1024pix/pix/assets/170271/dbec2316-5eea-4762-a0c8-b9d7a9b8a486)


J'ai peut-être loupé quelque chose dans ma compréhension mais le PAS CLEA devrait donc pas avoir le bouton ?

-----------------------------
Plusieurs orga, differents droits ❌ *

Aussi j'ai retiré les droits Admin sur l'orga 7001 (la SCO managing student) et d'un coup le bouton a disparu partout, par exemple sur Accessorium, alors que sur orga il est bien Admin

![image](https://github.com/1024pix/pix/assets/170271/7145bd9f-90a2-41c2-a38d-b95efc7c449c)
![image](https://github.com/1024pix/pix/assets/170271/bc332c0a-ad40-4d7b-b888-63ce4ad569eb)
![image](https://github.com/1024pix/pix/assets/170271/2aef04e1-c710-4c62-ab2b-36aba8389598)

2023-09-29 15:05 UTC, Steph0 requested changes
Sur les tests funcs si je me suis plantés sur les KO cela m'intéresse d'avoir une explication personnalisée ! :)

Je mets Request changes à cause de ces tests car si ce sont de vrais KO je me dis que la PR ne peut pas passer en l'état

2023-09-29 15:05 UTC, Steph0 commented on certif/app/components/team/invite-form.hbs
> +{{! template-lint-disable require-input-label }}
Pourquoi ne pas mettre les label (cela remonte aussi dans WAVE niveau accessibilité) ?

2023-09-29 15:05 UTC, Steph0 commented on certif/app/templates/authenticated/team/invite.hbs
> +<div class="team-invite-page">
Alors sous-couvert de ma bonne compréhension de la petite formation faite avec @frinyvonnick ; je crois qu'en BEM il faut pas rappeler le nom du fichier parent (ici `/team` par rapport à `/invite`).
Pinaillage : je trouve aussi que `page` est pas forcement utile

```suggestion
<div class="invite">
```

PLus d'infos ici : https://1024pix.atlassian.net/wiki/spaces/DC/pages/3845292101/BEM+Review

2023-09-29 15:05 UTC, Steph0 commented on certif/app/templates/authenticated/team/invite.hbs
> +  <h1 class="page__title page-title">
Retour BEM, le nom du bloc (`team-invite-page`) doit être nommé entièrement. N'y aurait-il pas aussi un truc redondant d'avoir à la fois (`page__title` et `page-title`) ?

```suggestion
  <h1 class="team-invite-page__title">
```

2023-09-29 15:05 UTC, Steph0 commented on certif/app/templates/authenticated/team/list.hbs
> +{{#if this.shouldDisplayNavbarSection}}
Il n'y a en théorie pas de cas possible où on aurait les deux simultanement. Applicable aussi à `{{#if this.shouldDisplayInviteMemberButton}}`

```suggestion
{{else if this.shouldDisplayNavbarSection}}
```

2023-09-29 15:05 UTC, Steph0 commented on certif/app/components/team/invite-form.hbs
> +<form {{on "submit" @onSubmit}} class="form" ...attributes>
Il n'y a pas de fichier de test sur ce composant

2023-09-29 15:26 UTC, reibecca commented
> J'ai peut-être loupé quelque chose dans ma compréhension mais le PAS CLEA devrait donc pas avoir le bouton ?

@Steph0 si PAS CLEA, alors le bouton concernant le réferent ne doit pas s'afficher. 
On veut le bouton pour inviter un nouveau membre quelque soit le type de l'organisation, donc c'est normal qu'il soit toujours présent, c'est ce qu'on veut 🙂

2023-09-29 15:32 UTC, reibecca commented on certif/app/templates/authenticated/team/invite.hbs
> +<div class="team-invite-page">
je ne suis pas très d'accord, avoir la classe principale avec le mot 'page' dedans est très répandu dans le code de Pix sur les templates, ça permet une meilleure compréhension je trouve

2023-09-29 15:33 UTC, reibecca commented on certif/app/templates/authenticated/team/invite.hbs
> +<div class="team-invite-page">
je ne suis pas très d'accord, avoir la classe principale avec le mot 'page' dedans est très répandu dans le code de Pix sur les templates, ça permet une meilleure compréhension je trouve

2023-09-29 15:41 UTC, reibecca commented
> Plusieurs orga, differents droits ❌

> Aussi j'ai retiré les droits Admin sur l'orga 7001 (la SCO managing student) et d'un coup le bouton a disparu partout, par exemple sur Accessorium, alors que sur orga il est bien Admin

@Steph0  La règle sur Pix Certif est que seul un admin peut inviter d'autres membres dans un centre de certification. Du coup si plus d'admin, plus de possibilité d'effectuer cette action.

Par contre, il me semble que sur Pix Orga, il y a une règle qui fait qu'on ne peut pas avoir d'Orga sans admin (à vérifier je suis pas sur à 100%), ça expliquerait pourquoi l'admin a toujours son rôle coté Orga

2023-10-02 07:09 UTC, igorissen commented
> > Plusieurs orga, differents droits ❌
> 
> > Aussi j'ai retiré les droits Admin sur l'orga 7001 (la SCO managing student) et d'un coup le bouton a disparu partout, par exemple sur Accessorium, alors que sur orga il est bien Admin
> 
> @Steph0 La règle sur Pix Certif est que seul un admin peut inviter d'autres membres dans un centre de certification. Du coup si plus d'admin, plus de possibilité d'effectuer cette action.
> 
> Par contre, il me semble que sur Pix Orga, il y a une règle qui fait qu'on ne peut pas avoir d'Orga sans admin (à vérifier je suis pas sur à 100%), ça expliquerait pourquoi l'admin a toujours son rôle coté Orga

@Steph0 le rôle sur Pix Certif n'est pas lié au rôle sur Pix Orga, c'est 2 tables distinctes. Donc si tu as retirés que celui de Pix Certif alors c'est normal que sur Pix Orga l'utilisateur a toujours son rôle admin (j'espère avoir bien compris la conversion 😅).

- table `memberships` pour la partie Pix Orga. Et comme @reibecca l'a signalé sur Pix Orga il doit y avoir toujours un admin. Cette condition n'est pas encore disponible sur Pix Certif.
- table `certification-center-memberships` pour la partie Pix Certif

2023-10-02 07:10 UTC, aceol commented on certif/app/templates/authenticated/team/list.hbs
> +{{#if this.shouldDisplayNavbarSection}}
Pourquoi pas les 2 simultanéments? Il ne semble pas s'opposer

2023-10-02 07:14 UTC, aceol commented on certif/app/templates/authenticated/team/invite.hbs
> +  <h1 class="page__title page-title">
Les deux sont contradictoires non? Pourquoi la 1ere?
> je crois qu'en BEM il faut pas rappeler le nom du parent.

> Retour BEM, le parent doit être nommé entièrement

2023-10-02 07:28 UTC, igorissen commented on certif/app/routes/authenticated/team.js
Ce code aurait du rester ici.
- Il permet de récupérer la liste des membres et de le récupérer via this.modelFor(...) depuis la route enfant
- Idem pour la liste des invitations qui n'est pas censé être au niveau de la route `/equipe/members`

2023-10-02 07:34 UTC, igorissen commented on certif/app/routes/authenticated/team.js
Je viens de voir qu'il a été déplacé dans `team.list` parent de `team.list.members` et `team.list.invitations`

2023-10-02 08:08 UTC, aceol commented
⚠️ il y a tout pleins de commit de fixup

2023-10-02 09:19 UTC, igorissen reviewed
Comme signaler, il manque un test d'intégration sur le composant `components/team/invite-form`.

2023-10-02 09:19 UTC, igorissen commented on certif/tests/unit/controllers/authenticated/team/invite_test.js
> +    controller = this.owner.lookup('controller:authenticated/sessions/new');
```suggestion
    controller = this.owner.lookup('controller:authenticated/team/invite');
```

2023-10-02 09:19 UTC, igorissen commented on certif/tests/unit/controllers/authenticated/team/invite_test.js
> +    assert.ok(controller.router.transitionTo.calledWith('authenticated.sessions.list'));
```suggestion
    assert.ok(controller.router.transitionTo.calledWith('authenticated.team.invite'));
```

2023-10-02 09:19 UTC, igorissen commented on certif/tests/acceptance/team_test.js
> +      test('redirects to "/equipe" URL', async function (assert) {
```suggestion
      test('redirects to "/equipe/membres" URL', async function (assert) {
```

2023-10-02 09:19 UTC, igorissen commented on certif/tests/acceptance/team_test.js
> +      test('redirects to "/equipe" URL', async function (assert) {
```suggestion
      test('redirects to "/equipe/membres" URL', async function (assert) {
```

2023-10-02 09:42 UTC, igorissen commented
> ⚠️ il y a tout pleins de commit de fixup

Oui, c'est normal. On a décider avec l'équipe de laisser les fixup pour ceux qui font les reviews pour voir ce qui a été modifié après le commentaire. Une fois que tout est résolu, on fait le fixup sur les commits associés puis on lance le processus de merge.

2023-10-02 13:02 UTC, aceol commented
> > ⚠️ il y a tout pleins de commit de fixup
> 
> Oui, c'est normal. On a décider avec l'équipe de laisser les fixup pour ceux qui font les reviews pour voir ce qui a été modifié après le commentaire. Une fois que tout est résolu, on fait le fixup sur les commits associés puis on lance le processus de merge.
OK ca marche!
(du coup, c'est pas evident quand on fait une nouvelle review commit par commit)

2023-10-02 13:02 UTC, Steph0 commented on certif/app/templates/authenticated/team/invite.hbs
> +<div class="team-invite-page">
@reibecca je n'avais pas forcèment regardé, mais effectivement sur le `-page` je trouve 218 occurences dans les hbs 😄

2023-10-02 13:06 UTC, Steph0 commented on certif/app/templates/authenticated/team/invite.hbs
> +  <h1 class="page__title page-title">
Vu ensemble, j'ai modifié les textes de mes commentaires pour que ça soit + compréhensible ^^'

2023-10-02 13:09 UTC, Steph0 commented on certif/app/templates/authenticated/team/list.hbs
> +{{#if this.shouldDisplayNavbarSection}}
Punaise j'ai pas spotté le bon endroit du fichier..... 

Ce commentaire est pour `{{#if this.shouldDisplayNoRefererSection}}` et `{{#if this.shouldDisplayUpdateRefererButton}}`  pas sur la navbarsection ({{#else if shouldDisplayUpdateRefererButton}}

Pas de NoRefererSection et DisplayUpdateRefererButton simultanément

2023-10-02 14:36 UTC, lego-technix commented
> Sur les tests funcs si je me suis plantés sur les KO cela m'intéresse d'avoir une explication personnalisée ! :)
> 
> Je mets Request changes à cause de ces tests car si ce sont de vrais KO je me dis que la PR ne peut pas passer en l'état

@Steph0 bien vu pour les tests fonctionnels ! Le problème que tu as remonté a été corrigé avec un commit fixup (merci @er-lim).

Et il y a maintenant dans les seeds `team-acces` un nouveau centre de certification `Accèssovolt` pour l'utilisateur `james-paledroits@example.net`. Cet utilisateur est maintenant _Admin_ dans  le centre de certification `Accèsorium` et _Membre_ dans le centre de certification `Accèssovolt`. Cela devrait éviter à l'avenir que l'on passe à côté de ce genre de problème.

Enfin, j'ai modifié la procédure _Pour tester_ de manière à y inclure le point que tu as testé et qui était absent.

2023-10-02 14:45 UTC, yoandl commented
Tests sur Firefox  ✅  : 
tous les tests semblent ok, le bouton "inviter les membres" est bien présent pour un utilisateur admin (clea /non-clea et la colonne Référent apparait bien pour les centres CLEA .

2023-10-02 14:46 UTC, yoandl approved these changes
func review ok sur firefox

2023-10-02 15:06 UTC, lego-technix commented on certif/tests/unit/controllers/authenticated/team/invite_test.js
> +    assert.ok(controller.router.transitionTo.calledWith('authenticated.sessions.list'));
Cette ligne avait bien besoin d'être corrigée, merci. Mais la redirection dans le controller est faite vers `authenticated.team` et voila donc pourquoi je viens de modifier l'assert pour qu'il soit comme suit : 

```javascript
assert.ok(controller.router.transitionTo.calledWith('authenticated.team'));
```

2023-10-02 15:19 UTC, lego-technix commented on certif/app/templates/authenticated/team/invite.hbs
> +  <h1 class="page__title page-title">
@Steph0 bien vu cette classe `page__title` problématique ! En fait il n'y a pas de style associé dans Pix Certif. C'est une classe qui vient de Pix Orga, et qui existe dans Pix Orga, mais qui n'existe pas dans Pix Certif. Cette classe s'est propagée dans Pix Certif par copier-coller. Je l'ai enlevée en poussant un commit fixup.

2023-10-02 15:49 UTC, lego-technix commented on certif/app/templates/authenticated/team/list.hbs
> +{{#if this.shouldDisplayNavbarSection}}
Je ne suis pas certain de bien comprendre car `{{#if this.shouldDisplayUpdateRefererButton}}` et `{{#if this.shouldDisplayNoRefererSection}}` ne sont pas au même niveau dans l'arborescence DOM de ce fragment HTML et donc je ne pense pas qu'on puisse les liés avec un `else`.

2023-10-02 15:51 UTC, lego-technix commented on certif/app/components/team/invite-form.hbs
> +{{! template-lint-disable require-input-label }}
Ce `{{! template-lint-disable require-input-label }}` a été retiré, il s'agissait d'une propagation involontaire par copier-coller.

2023-10-02 15:51 UTC, lego-technix commented on certif/app/components/team/invite-form.hbs
> +<form {{on "submit" @onSubmit}} class="form" ...attributes>
@Steph0 bien vu ! Le fichier de test `certif/tests/integration/components/team/invite-form_test.js` correspondant a été ajouté.

2023-10-02 15:54 UTC, lego-technix commented
Toutes vos remarques ont été traitées. Vous êtes invités à marquer comme « Resolved » toutes les conversations qui le sont et à prévenir si un point avait été corrigé de manière non satisfaisante ou oublié.

2023-10-03 12:39 UTC, Steph0 commented on certif/app/templates/authenticated/team/list.hbs
> +{{#if this.shouldDisplayNavbarSection}}
J'ai relu tout cela attentivement, on dirait bien que c'est moi qui me suis mélangé les pinceaux 😬

2023-10-03 13:08 UTC, Steph0 approved these changes
Après revue, tout me semble OK désormais !

2023-10-03 16:53 UTC, merged