[FEATURE] Appliquer le design sur la plage de fin de mission (Pix-9367)
1024pix/pix pull request #7194
Opened 2023-10-02 15:57 UTC by yaelle6

## :unicorn: Problème
> _Décrivez ici le besoin ou l'intention couvert par cette Pull Request._

## :robot: Proposition
> _Ajoutez à cet endroit, si nécessaire, des détails concernant la solution technique retenue et mise en oeuvre, des difficultés ou problèmes rencontrés._

## :rainbow: Remarques
> _Des infos supplémentaires, trucs et astuces ?_

## :100: Pour tester
> _Les instructions pour reproduire le problème, les profils de test, le parcours spécifique à utiliser, etc._

2023-10-06 17:02 UTC, aurelie-crouillebois commented
J'ai résolu les conflits sur le rebase sur dev, et j'ai fixé le pbm de taille du svg.
Il y a un pbm global à revoir, c'est la position du robot vis à vis des bulles. Il doit descendre en fonction du volume de texte.
Il me reste la revue du reste du code à faire.

2023-10-09 09:14 UTC, aurelie-crouillebois requested changes

2023-10-09 09:14 UTC, aurelie-crouillebois commented on 1d/app/pods/assessment/results/template.hbs
> +    <MissionCard @title="Recherche sur internet" @colorClass="red" @imageName="internet-search" />
Changer le nom et la couleur en fonction de la mission

2023-10-09 09:14 UTC, aurelie-crouillebois commented on 1d/app/pods/assessment/results/template.hbs
> +      <PixButtonLink @route="home" @shape="rounded" class="back-to-mission">
Changer la route pour aller sur les missions au lieu de home (+ test)

2023-10-09 09:14 UTC, aurelie-crouillebois commented on 1d/app/styles/components/mission.scss
> +      // p::before {
Supprimer les commentaires

2023-10-09 09:14 UTC, aurelie-crouillebois commented on 1d/translations/fr.json
> +      "list": "Choisi ta mission parmi celles qui te sont proposées ci-dessous !",
ajouter une entrée pour avoir une liste de traductions par page.

2023-10-09 09:27 UTC, yaf approved these changes

2023-10-09 09:56 UTC, aurelie-crouillebois approved these changes

2023-10-09 12:37 UTC, merged