[DOCS] Mise à jour de la photo de l'application dans le README.md
1024pix/pix pull request #7349
Opened 2023-10-27 23:16 UTC by takos22

## :unicorn: Problème
> La photo dans le [README.md actuel](https://github.com/1024pix/pix/blob/dev/README.md) ne reflète pas la version de Pix la plus récente, les certifications ne sont qu'au niveau 6 maximum alors que le [niveau 7 existe depuis septembre](https://pix.fr/actualites/decouvrez-le-niveau-7-des-maintenant-sur-pix).

## :robot: Proposition
> J'ai pris une capture d'écran dans le même format et j'ai remplacé le fichier de l'ancienne capture d'écran par la mienne à `./docs/assets/pix-app-screenshot.png`, qui comporte des certifications jusqu'au niveau 7.

## :rainbow: Remarques
> Aucune.

## :100: Pour tester
> Ouvrir le nouveau [README.md](https://github.com/takos22/pix/blob/dev/README.md).

2023-11-06 09:59 UTC, yaf commented
merci :)

2023-11-06 10:34 UTC, lego-technix requested changes
Bonne idée, par contre :

1. La copie d'écran fournie est moins belle que celle qui est actuellement présente dans le dépôt (fontes moins belles, notamment sur les cartes).
2. Le fichier est trop gros, il faut le compresser

2023-11-06 10:49 UTC, yaf commented
@takos22 est-ce que tu pourrais modifier l'image de cette PR en suivant les indications de @lego-technix ?

2023-11-08 21:55 UTC, takos22 commented
Je le ferais dans le week-end ou la semaine prochaine.

2023-12-06 08:24 UTC, francois2metz commented
Je ferme. A réouvrir si il y a du nouveau.

2023-12-06 08:24 UTC, closed without merging