[TECH] Auto rebuild libxmljs2 on ARM64 macs
1024pix/pix pull request #7610
Opened 2023-12-05 17:52 UTC by cberthou

## :christmas_tree: Problème
Actuellement, le binaire installé par libxmljs2 pour node20 n'est pas compatible avec node20 sur les mac ARM64.

## :gift: Proposition
Si la version de la lib ne peut être chargée, nous la rebuildons en post-install.

## :santa: Pour tester

Sur mac M1/M2
```
npm ci
// le rebuild doit se produire

npm i
// le rebuild ne se produit pas
```

2023-12-05 18:25 UTC, lego-technix commented on api/package.json
> -    "preinstall": "npx check-engine",
Est-ce voulu d'avoir supprimé le script `preinstall` ? Si oui il faudrait a minima expliquer pourquoi et si c'est un sujet différent que celui de cette PR peut-être plutôt privilégier une PR dédiée.

2023-12-06 08:50 UTC, Steph0 commented
Ca vaudrait pas plutôt le coup de travailler sur le fait d'enlever l'usage de cette lib (qui est utilisée très peu) plutôt que ce workaround ?
https://1024pix.atlassian.net/browse/PIX-10260

2023-12-06 09:07 UTC, cberthou commented on api/package.json
> -    "preinstall": "npx check-engine",
Non, c'est pas voulu, j'ai fait du caca.

2023-12-06 15:14 UTC, Steph0 requested changes
@cberthou Avant de merger si on peut se synchro. Finalement ça concerne l'équipe certif et on est en train de statuer dessus (et du fait ta PR serait pas forcèment utile).

2023-12-12 11:55 UTC, closed without merging

2023-12-12 12:07 UTC, aceol commented
On peut clore suite au revert de l'upgrade pour eviter un postinstall lourd (mais qui aurait pu etre nécessaire!)
 https://github.com/1024pix/pix/pull/7628