[TECH] LOG_ENABLED disabled by default for a new environment (PIX-10289).
1024pix/pix pull request #7641
Opened 2023-12-07 16:32 UTC by Steph0

## :christmas_tree: Problème

Les règles de logging, et la documentation autour de la documentation de la configuration de logging, sont confuses.

## :gift: Proposition

* Corriger la documentation
* Avoir une seule source dé vérité pour la configuration
  * Simplifier les règles de gestion autour de l'environnement de développement, et de fait par défaut suivre `sample.env` pour tous les environnements y compris dev
  * Garder la suggestion de la PR 1024pix/pix#7589 qui propose que par défaut les logs sont désactivés (aspects de sécurité)
  
## :socks: Remarques

Cette PR fait suite à 
* Pull Request 1024pix/pix#7589
* Github issue 1024pix #4033

## :santa: Pour tester

* Dans votre fichier `.env` mettre LOGGING_ENABLED=false
  * Lancer `NODE_ENV='development' npm start` les logs de l'API ne doivent pas s'afficher
* Dans votre fichiver `.env` mettre LOGGING_ENABLED=true
  * Lancer `NODE_ENV='development' npm start` les logs de l'API doivent s'afficher
* Supprimer volontairement la variable d'environnement, avec `unset LOGGING_ENABLED` en ligne de commande par exemple
  * Lancer `NODE_ENV='development' npm start` les logs de l'API ne doivent pas s'afficher (absence de configuration = false par défaut)
* Refaire ces mêmes tests, mais avec `NODE_ENV='production', et vérifier que les comportements de toutes les étapes précèdentes sont les mêmes

2023-12-12 19:40 UTC, aceol approved these changes

2023-12-12 19:40 UTC, aceol commented on api/sample.env
>  # default: `false`
Ne devrait on pas la mettre à `true` par defaut? Ca semble etre le comportement attendu

2023-12-13 06:50 UTC, HEYGUL requested changes
Comme discuté de vive voix, je préconise de garder le fonctionnement actuel, et d'expliciter le comportement dans le fichier `sample.env` et toute autre page de documentation adéquate.

2023-12-13 11:22 UTC, Steph0 commented on api/sample.env
>  # default: `false`
J'avais hésité à le faire et tu as tout à fait raison !

2023-12-13 11:26 UTC, Steph0 commented
@HEYGUL comme j'évoquais de vive voix, je proposais en revanche de justement ne pas grader le fonctionnement actuel ; car cela n'a pas forcèment de sens d'avoir une logique de surcharge **uniquement** pour `developpement`.

Par contre je n'avais pas détailler ma proposition ci-dessus, notamment sur les aspects de sécurité (en + de conserver le bénéfice de votre PR #7589 tout en simplifiant le code proposé à l'époque).

2023-12-13 12:25 UTC, lionelB commented
@HEYGUL n'ayant pas participé à la conversation, quelles sont les raisons à garder le comportement actuel ?

2023-12-13 16:21 UTC, VincentHardouin commented
Pour info le titre de la PR doit être en français cf: https://github.com/1024pix/pix/blob/dev/CONTRIBUTING.md

2023-12-13 16:26 UTC, aceol approved these changes

2023-12-14 06:33 UTC, HEYGUL commented
> @HEYGUL n'ayant pas participé à la conversation, quelles sont les raisons à garder le comportement actuel ?

La PR a changé depuis mon commentaire.
Pour info, elle proposait de désactiver les logs par défaut, ce qui est le comportement inverse du comportement actuel.

J'étais contre, car dans une PR précédente, nous avions corrigé la prise en compte de `LOG_ENABLED` en `dev` pour permettre cette désactivation uniquement si spécifié.
En se mettant à jour, @Steph0 et @P-Jeremy, dont les fichiers `.env` contenait `LOG_ENABLED=false`, ont cru que l'api ne fonctionnait plus car ils n'avaient (à juste titre) plus de logs.
Si on désactive les logs par défaut, il y a des chances que les logs soient désactivés sur la majeur partie des environnements locaux de nos collègues (et j'aime pas embêter mes collègues).

En l'état actuel des choses, je suis moins tranché, même si activer les logs sur un environnement de production devrait être une opération explicite IMO.

2023-12-14 06:35 UTC, HEYGUL reviewed
En l'état actuel, je suis neutre sur l'acceptation ou non de cette PR.

2023-12-14 06:35 UTC, HEYGUL approved these changes

2023-12-15 09:48 UTC, Steph0 commented
> même si activer les logs sur un environnement de production devrait être une opération explicite IMO.

C'est en challengeant justement ce point précis, où je défendais IMO l'inverse (log actifs par défaut), que je suis tombé sur les recommandations OWASP et CWE qui donnent de fait un avis moins subjectif à l'intérêt d'activer par défaut.

En plus de suivre des précos de sécurité, ça simplifie le code pour env de dev (ce que je proposais initialement), et cette fois sans aucun risque d'embêter les collègues 😊

2023-12-19 10:25 UTC, xav-car approved these changes

2024-01-03 08:30 UTC, yaf commented on api/sample.env
> +# default: `true`
C'est bizarre de dire `default: true` alors que l'on précise en dessosu que c'est `true`. Est-ce que ça signifie que nous pourrions enlever la ligne en dessous ? (c'est ce que je pense quand il y a un commentaire `default: true`. Peut-être faut-il supprimer le commentaire simplement ?

2024-01-03 09:06 UTC, Steph0 commented on api/sample.env
> +# default: `true`
Je vois ce que tu veux dire, c'est vrai que au vu du code de toute manière c'est ENABLED si absent, vu que j'ai remis le `isFeatureNotDisabled` que j'avais précèdemment enlevé (dur de trouver le meilleur rapport qualité / remplissage de l'objectif de la PR).

2024-01-03 09:14 UTC, yaf approved these changes

2024-01-03 09:14 UTC, yaf commented on api/sample.env
> +# default: `true`
Merci !

2024-01-03 09:25 UTC, merged