[FEATURE] Retourner un erreur 404 lors de l'enregistrement d'un signalement si la catégorie liée n'existe pas en base de données (PIX-10210))
1024pix/pix pull request #7692
Opened 2023-12-14 18:55 UTC by matthieu-octo

## :christmas_tree: Problème
La méthode `get` du repository `issue-report-categories` qui récupère la catégorie liée au signalement ne retourne pas d’erreur si elle ne retrouve rien.

## :gift: Proposition
Retourner une erreur `404 NOT FOUND` au consommateur de l'API si la catégorie liée au signalement n'existe pas en base de données.

## :socks: Remarques
RAS

## :santa: Pour tester
WIP ...

2023-12-15 09:31 UTC, P-Jeremy approved these changes

2023-12-19 09:21 UTC, Steph0 requested changes
Je suis pas super fan sur des données textes en entrée de renvoyer le retour au front, ça peut générer des [Reflected XSS Attacks](https://owasp.org/www-community/attacks/xss/).

> Reflected attacks are those where the injected script is reflected off the web server, such as in an error message, search result, or any other response that includes some or all of the input sent to the server as part of the request.

Je propose de modifier le détail par `"The issue report category name does not exist"`.

REQUEST
```
curl --location 'https://api-pr7692.review.pix.fr/api/certification-reports/99999/certification-issue-reports' \
--header 'Accept: */*' \
--header 'Content-Type: application/json' \
--header 'Authorization: Bearer eyJhb.....Gj8' \
--data '{
    "data": {
        "attributes": {
            "category": "<script>alert('\''toto'\'');</script>",
            "subcategory": null,
            "description": null,
            "question-number": null
        },
        "relationships": {
            "certification-report": {
                "data": {
                    "type": "certification-reports",
                    "id": "CertificationReport-9999"
                }
            }
        },
        "type": "certification-issue-reports"
    }
}'
```

RESPONSE
```
{
  "errors": [
    {
      "status": "404",
      "title": "Not Found",
      "detail": "The issue report category name <script>alert('toto');</script> does not exist"
    }
  ]
}
```

2023-12-19 09:23 UTC, Steph0 commented
@matthieu-octo tu peux détailler le cas de test de non-régression, c'est à dire le cas nominal (or 404) pour le refaire côté appli front ? 🙏🏻

2023-12-19 09:31 UTC, Steph0 requested changes, later dismissed

2023-12-19 09:31 UTC, Steph0 commented on api/lib/domain/read-models/CertificationIssueReportcategory.js
> +  constructor({ id }) {
```suggestion
/**
* @typedef {Object} CertificationIssueReportCategory
* @property {number} id
*/

export class CertificationIssueReportCategory {
  constructor({ id }) {
```

2023-12-19 09:31 UTC, Steph0 commented on api/lib/domain/read-models/CertificationIssueReportcategory.js
> +export { CertificationIssueReportCategory };
Peut-être supprimé si tu mets l'export devant class ci-dessus

2023-12-19 09:31 UTC, Steph0 commented on api/src/certification/shared/infrastructure/repositories/issue-report-category-repository.js
> +import { NotFoundError } from '../../../../../lib/domain/errors.js';
Prendre le `NotFoundError` de `src/shared` car tu es déjà dans `src`

2023-12-19 09:31 UTC, Steph0 commented on api/lib/domain/read-models/CertificationIssueReportcategory.js
> +class CertificationIssueReportCategory {
⚠️ Le mettre dans `src`, il faut éviter autant que possible de créer des choses dans `lib`

2023-12-19 10:36 UTC, aceol commented on api/src/certification/shared/infrastructure/repositories/issue-report-category-repository.js
> +    throw new NotFoundError(`The issue report category name ${name} does not exist`);
```suggestion
    throw new NotFoundError(`The issue report category "${name}" does not exist`);
```

2023-12-19 10:39 UTC, aceol commented on api/tests/certification/shared/integration/infrastructure/repositories/issue-report-categories-repository_test.js
> +    describe('when the issue report category name exists in the database', function () {
Pas forcé de specifier 'database'
```suggestion
    describe('when the issue report category name exists', function () {
```

2023-12-19 10:40 UTC, aceol approved these changes
Approve mais il faut effectivement ne pas creer/utiliser depuis lib

2023-12-19 14:57 UTC, matthieu-octo commented on api/src/certification/shared/infrastructure/repositories/issue-report-category-repository.js
> +    throw new NotFoundError(`The issue report category name ${name} does not exist`);
J'ai pris en compte le commentaire à ce sujet : https://github.com/1024pix/pix/pull/7692#pullrequestreview-1788438596

2023-12-19 15:26 UTC, Osirisxxl commented on api/tests/unit/domain/usecases/save-certification-issue-report_test.js
> +        it('should return a Not Found domain error', async function () {
```suggestion
        it('should throw a Not Found domain error', async function () {
```

2023-12-19 15:34 UTC, Osirisxxl commented on api/tests/unit/domain/usecases/save-certification-issue-report_test.js
> +import { expect, sinon, domainBuilder, catchErr } from '../../../test-helper.js';
Je suis pas rentré dans le détail, mais au doigt mouillé, j'ai l'impression qu'on teste plusieurs fois la même chose. Peut-être qu'on peut simplement garder un cas passant et un cas où on throw 🤔

2023-12-19 15:34 UTC, Osirisxxl approved these changes

2023-12-19 16:15 UTC, matthieu-octo commented on api/tests/unit/domain/usecases/save-certification-issue-report_test.js
> +import { expect, sinon, domainBuilder, catchErr } from '../../../test-helper.js';
Ton doigt mouillé voit juste 😄 
Dans les tests du usecase, il y a deux `describes`, faisant référence à la recherche de la `issueReportCategory` en DB avec une `category` ou bien une `subcategory` en lien avec la ligne suivante dans le use case: 
```
const issueReportCategoryName = certificationIssueReportDTO.subcategory ?? certificationIssueReportDTO.category;
```

Pour ne pas amener de confusion, j'ai dupliqué mon test dans chacun des `describe`. Une deuxième raison était que le nom de la catégorie ou de la sous-catégorie était présent dans le message d'erreur, ce qui n'est plus le cas.

J'allège et je supprime un cas ?

2023-12-19 16:26 UTC, Osirisxxl commented on api/tests/unit/domain/usecases/save-certification-issue-report_test.js
> +import { expect, sinon, domainBuilder, catchErr } from '../../../test-helper.js';
ça me va si on allège 👍

2023-12-22 09:03 UTC, merged