[FEATURE] Ne pas afficher l'icone de réponse si un candidat passe une question dans la page de détails (PIX-10682).
1024pix/pix pull request #7832
Opened 2024-01-09 16:58 UTC by alexandrecoin

## :christmas_tree: Problème

Une nouvelle page de détails spécifique aux certifs v3 a été implémentée dans Pix Admin. Parmi les informations disponibles sur cette page, on trouve la réponse apportée à la question par un candidat. Cette information est accessible en cliquant sur une icône dans la colonne “Actions”.

L’icône permettant de voir la réponse apportée à la question est disponible pour une question au statut “Abandonnée” ce qui n’est pas pertinent car par défaut, question abandonnée = pas de réponse apportée par le candidat.

## :gift: Proposition

Dans Pix Admin > page de détails d’une certification v3 : ne pas afficher l’icône réponse pour une question au statut “Abandonnée”

## :socks: Remarques
> _Des infos supplémentaires, trucs et astuces ?_

## :santa: Pour tester

• trouver une certif v3 avec au moins une question qui a été passée (= abandonnée) 
OU
• créer une session dans un CDC taggué isV3Pilot > inscrire un candidat à cette session > rejoindre la session avec le candidat > cliquer sur le bouton “Je passe” pour au moins 1 question du test (et bien ou mal répondre à quelques questions)
• dans Pix Admin > Certifications > ouvrir la page de détails de la certif avec au moins 1 question passée/abandonnée
• résultat : l’icône “Réponse” n’est pas affichée pour la/les question(s) au statut “Abandonnée”
• l’icône “Réponse” reste visible pour les questions au statut “OK” ou “KO”

2024-01-10 09:22 UTC, Osirisxxl commented on admin/app/components/certifications/certification/details-v3.js
> +    return certificationChallenge.answerValue && certificationChallenge.answerValue !== '#ABAND#';
```suggestion
    return certificationChallenge?.answerValue !== '#ABAND#';
```

2024-01-10 09:24 UTC, Osirisxxl commented on admin/tests/integration/components/certifications/certification/details-v3_test.js
> +      module('when the candidate passes the question', function () {
```suggestion
      module('when the candidate skips the question', function () {
```
to pass = réussir  
un faux ami sympa

2024-01-10 09:43 UTC, Osirisxxl commented
Test func ok
🎁  url d'une certif sur admin avec des questions passées: https://admin-pr7832.review.pix.fr/certifications/145038/details

2024-01-10 09:44 UTC, Osirisxxl commented on admin/tests/integration/components/certifications/certification/details-v3_test.js
> +          assert.dom(screen.queryByRole('button', { name: 'Afficher la réponse du candidat' })).doesNotExist();
Ça ça ne passe pas sur la CI 🤔 
Est-ce que l'état du test précédent avec une question répondue est conservé ?

2024-01-10 10:15 UTC, alexandrecoin commented on admin/tests/integration/components/certifications/certification/details-v3_test.js
> +          assert.dom(screen.queryByRole('button', { name: 'Afficher la réponse du candidat' })).doesNotExist();
problème de condition d'affichage, c'est fixé.

2024-01-10 10:36 UTC, Osirisxxl approved these changes

2024-01-10 15:21 UTC, cberthou requested changes

2024-01-10 15:21 UTC, cberthou commented on admin/app/components/certifications/certification/details-v3.js
> +    return certificationChallenge?.answerValue !== '#ABAND#' && !certificationChallenge.validatedLiveAlert;
utiliser plutôt le answerStatus

2024-01-10 15:29 UTC, cberthou approved these changes

2024-01-11 09:05 UTC, mcampourcy commented
Test func OK

<img width="1583" alt="Capture d’écran 2024-01-11 à 10 04 49" src="https://github.com/1024pix/pix/assets/11388201/27f73905-4ce5-4f46-862a-a77403212e1e">

2024-01-11 09:05 UTC, mcampourcy approved these changes

2024-01-12 15:34 UTC, merged