[FEATURE] Gérer le niveau -1 pour les certifications complémentaire (PIX-10319)
1024pix/pix pull request #7836
Opened 2024-01-10 13:35 UTC by P-Jeremy

## :christmas_tree: Problème
> _Décrivez ici le besoin ou l'intention couvert par cette Pull Request._

## :gift: Proposition
> _Ajoutez à cet endroit, si nécessaire, des détails concernant la solution technique retenue et mise en oeuvre, des difficultés ou problèmes rencontrés._

## :socks: Remarques
> _Des infos supplémentaires, trucs et astuces ?_

## :santa: Pour tester
> _Les instructions pour reproduire le problème, les profils de test, le parcours spécifique à utiliser, etc._

2024-01-17 09:52 UTC, aceol commented on api/tests/unit/domain/events/handle-complementary-certifications-scoring_test.js
> +              it('should  not save a not "acquired" complementary certification with current level badge', async function () {
```suggestion
              it('should save a not "acquired" complementary certification with current level badge', async function () {
```

2024-01-26 11:40 UTC, matthieu-octo commented on api/lib/domain/events/handle-complementary-certifications-scoring.js
> +  // FIXME: this loop is irrelevant, there can only be one complementary certification taken on one certificationCourse
Que fait-on de ce commentaire ? On le traite en équipe pour en savoir plus sur l'historique ?

2024-01-26 16:16 UTC, matthieu-octo commented on api/lib/domain/events/handle-complementary-certifications-scoring.js
> +      // FIXME Need to match with non outdated target_profiles and check that badges are still attached to the target profile ?
Réflexion autour de ce commentaire. A-t-on tranché avec le métier ?

La question qu'on se posait était de savoir si c'est pertinent de filtrer les `target profiles` `outdated` alors qu'il est possible que celui-ci le devienne après que la certification complémentaire ait été passée par le candidat (et obtenue) et si le scoring était recalculé après coup, le filtre pouvait manquer de pertinence.

2024-01-26 16:32 UTC, matthieu-octo commented on api/lib/domain/events/handle-complementary-certifications-scoring.js
> +function _isBelowMinimumCurrentLevelScore({ pixScore, minimumEarnedPixForCurrentLevel }) {
À la lecture, l'intention ne m'a pas parue évidente :

```suggestion
function _isBelowMinimumCurrentLevelRequiredPixScore({ pixScore, minimumEarnedPixForCurrentLevel }) {
```

2024-01-26 16:35 UTC, matthieu-octo commented on api/lib/domain/events/handle-complementary-certifications-scoring.js
> +function _isAboveMinimumLowerLevelScore({ pixScore, minimumEarnedPixForLowerLevel }) {
À la lecture, l'intention ne m'a pas parue évidente : 

```suggestion
function _isAboveMinimumLowerLevelRequiredPixScore({ pixScore, minimumEarnedPixForLowerLevel }) {

```

2024-01-26 16:41 UTC, matthieu-octo commented on api/lib/domain/events/handle-complementary-certifications-scoring.js
> +function _isBelowMinimumReproducibilityRate(complementaryCertificationScoring) {
Au risque d'être trop verbeux, j'aurais apporté une précision supplémentaire comme dans la fonction de dessous.

```suggestion
function _isBelowMinimumCurrentLevelRequiredReproducibilityRate(complementaryCertificationScoring) {

```

2024-01-26 16:43 UTC, matthieu-octo commented on api/lib/domain/events/handle-complementary-certifications-scoring.js
> +function _isAboveMinimumLowerReproducibilityRate(
Au risque d'être trop verbeux, j'aurais apporté une précision supplémentaire.

```suggestion
_isAboveMinimumLowerLevelRequiredReproducibilityRate
```

2024-01-29 09:09 UTC, P-Jeremy commented on api/lib/domain/events/handle-complementary-certifications-scoring.js
> +      // FIXME Need to match with non outdated target_profiles and check that badges are still attached to the target profile ?
Vu avec Ann-so, on ne veut pas filtrer les target profile outdated. On peut supprimer ce commentaire

2024-01-29 09:39 UTC, P-Jeremy commented on api/lib/domain/events/handle-complementary-certifications-scoring.js
> +  // FIXME: this loop is irrelevant, there can only be one complementary certification taken on one certificationCourse
La PR est déjà grosse, on va le taiter dans une PR à part

2024-01-29 11:10 UTC, Osirisxxl commented on api/lib/domain/events/handle-complementary-certifications-scoring.js
> +    ) {
```suggestion
    const hasAcquiredLowerLevel = nextLowerLevelBadge && _hasAcquiredLowerLevel({
        pixScore: assessmentResult.pixScore,
        reproducibilityRate: assessmentResult.reproducibilityRate,
        minimumEarnedPixForCurrentLevel: minimumEarnedPix,
        minimumEarnedPixForLowerLevel: nextLowerLevelBadge.minimumEarnedPix,
        complementaryCertificationScoring,
        minimumReproducibilityRateLowerLevel,
      })
    if (_hasAcquiredPixCertification(assessmentResult) && hasAcquiredLowerLevel) {
```

2024-01-29 13:45 UTC, P-Jeremy commented on api/lib/domain/events/handle-complementary-certifications-scoring.js
> +  // FIXME: this loop is irrelevant, there can only be one complementary certification taken on one certificationCourse
Pris en compte dans le refacto

2024-01-30 15:45 UTC, P-Jeremy commented on api/lib/domain/events/handle-complementary-certifications-scoring.js
> +    ) {
Plus d'actualité suite au refacto

2024-01-31 11:27 UTC, matthieu-octo commented on api/src/certification/complementary-certification/infrastructure/repositories/complementary-certification-badge-repository.js
> +    `),
Proposition pour retirer le commentaire eslint, en concordance avec [la documentation knex](https://knexjs.org/guide/raw.html#raw-parameter-binding) : 

```suggestion
    knex.raw(
        `
      (SELECT "target-profiles".id
      FROM "complementary-certification-badges"
      JOIN "badges" on "badges".id = "complementary-certification-badges"."badgeId"
      JOIN "target-profiles" on "target-profiles"."id" = "badges"."targetProfileId"
      WHERE "complementary-certification-badges".id = ?
      )
    `,
        [`${complementaryCertificationBadgeId}`],
      ),
```

2024-01-31 11:54 UTC, Steph0 requested changes, later dismissed

2024-01-31 11:54 UTC, Steph0 commented on api/lib/domain/models/ComplementaryCertificationBadge.js
> +class ComplementaryCertificationBadge {
Je propose de mettre ce model côté `src`, il est notament utilisé par le repo de ce contexte

2024-01-31 11:54 UTC, Steph0 commented on api/lib/domain/models/ComplementaryCertificationBadge.js
> +  }
Des factory ont pour moins une utilité quand elles ont soit un peu de logique (formatage, etc), ou si elles représentent au moins une translation abstraite d'un type d'objet à un autre quand elles font du passe-plat, c'est porté alors par le nom de méthode (par exemple si elle s'était appellé `fromBadgeToAttach`). Dans l'idéal elle cumule les deux conditions.

Mais dans le cas de ce commit je trouve qu'elle ne remplie aucun de ces deux conditions et peut donc être supprimée.

2024-01-31 11:54 UTC, Steph0 commented on api/src/certification/complementary-certification/infrastructure/repositories/complementary-certification-badge-repository.js
> +const getAllWithSameTargetProfile = async function (complementaryCertificationBadgeId) {
En vrai est-ce que l'on arrive pas au point où il serait plus simple de créer une clé étrangère c-c-badges <--> targetProfile ?

Niveau métier, c'est impossible qu'un ensemble de ccbadges sont la même 'key' appartiennent à différents profils cibles (pas permis par l'attachement).

Par conséquent cela devrait être porté par la couche métier.
Même en terme de code, on commence à être de moins en moins DRY en écrivant toujours les mêmes jointures avec de subtiles différences.

**J'imagine que ça fait un trop gros refacto d'introduire la clé étrangère, alors du coup je propose plutôt de passer ici par une approche + programmatique** 

* usecase fait d'abord un ~ "getTargetProfileFromCCBadges" from complementaryCertificationBadgeId
* on ré-utilise / transforme un peu getAllIdsByTargetProfileId`` en une sorte de getAllByTargetProfileId, qui renvoie des domain models ComplementaryCertificationBadge` créé plus haut (et non pas juste les ids)
* et du coup le usecase peu utiliser ce getAllByTargetProfileId

On sera ainsi un peu + DRY et ce sera nos couches business de notre archi qui portera cette liaison "N ccbdges .. 1 profil cible". Actuellement on compense et on le déduit de notre couche infrastructure par les jointures, il me semble important de commencer à faire remonter cette règle métier.

Ma peur et que ce repository finisse de + en + à contenir N méthodes qui font la même jointure sans cesse pour appliquer au final ce qui est une règle métier.

2024-01-31 11:54 UTC, Steph0 commented on api/src/certification/complementary-certification/infrastructure/repositories/complementary-certification-badge-repository.js
> +      // eslint-disable-next-line knex/avoid-injections
⚠️ Pour moi ça c'est bloquant ici. 😬 On peut utiliser les requêtes préparées de knex, et en fait y'a surement moyen de pas du tout utiliser du raw``.
Note que selon ce qu'on veut faire avec mon commentaire ci-dessous cela pourrait disparaitre.

2024-01-31 11:54 UTC, Steph0 commented on api/src/certification/complementary-certification/infrastructure/repositories/complementary-certification-badge-repository.js
> +};
⚠️ Bloquant car ne respecte pas les principes de Clean Archi. Il doit y avoir une couche Adapter, qui est chez Pix le `toDomain`, pour représenter la décorrélation entre la couche Framework/Driver et Usecases.

2024-01-31 11:55 UTC, Steph0 commented on api/src/certification/complementary-certification/infrastructure/repositories/complementary-certification-badge-repository.js
> +      // eslint-disable-next-line knex/avoid-injections
Voir commentaire de @matthieu-octo (merci d'avoir pris le temps de faire la suggestion :) ! )

2024-01-31 11:59 UTC, Steph0 commented on api/src/certification/complementary-certification/infrastructure/repositories/complementary-certification-badge-repository.js
> +};
A noter que vu que c'est un `getXXX` il manque le retour d'une NotFoundError si pas de résultats. Ou Alors transformer en find et traiter cela niveau usecase.

2024-01-31 12:00 UTC, Steph0 commented on api/src/certification/complementary-certification/infrastructure/repositories/complementary-certification-badge-repository.js
> +    .select('complementary-certification-badges.*')
Nitpick : je propose de limiter les colonnes qui transitent par le réseau (on a besoin que de 3 champs).

2024-01-31 12:06 UTC, Steph0 reviewed
@P-Jeremy désolé pour le blocked pendant un temps mais ça m'est arrivé que une PR soit mergée pendant ma review et je voulais pas que ça arrive à cause du repository (comme on a validé le test func en MOB) 

je voulais attirer l'attention sur le fait que sur le repository je souhaiterais des changements qui me semblent important (surtout ce truc de requêtes préparées en fait) 😅

2024-01-31 13:10 UTC, AndreiaPena commented on api/db/database-builder/factory/build-complementary-certification.js
> +  minimumReproducibilityRateLowerLevel = 60.0,
**Question** : Pourquoi on précise `60.0` ?

2024-01-31 13:15 UTC, P-Jeremy commented on api/db/database-builder/factory/build-complementary-certification.js
> +  minimumReproducibilityRateLowerLevel = 60.0,
C'est pour être raccord avec les données de prod

2024-01-31 13:16 UTC, AndreiaPena commented on api/tests/unit/domain/models/ComplementaryCertificationScoringWithComplementaryReferential_test.js
> +    it('returns false when pixScore is under minimumEarnedPix rat even if Pix+ certification is acquired', function () {
```
context('when pixScore is under minimumEarnedPix rat even if Pix+ certification is acquired', function () {
    it('returns false', function () {
```

2024-01-31 13:36 UTC, AndreiaPena commented on api/db/database-builder/factory/build-complementary-certification.js
> +  minimumReproducibilityRateLowerLevel = 60.0,
en prod on est à 60.0 ? :o

2024-01-31 13:41 UTC, AndreiaPena commented on api/lib/domain/events/handle-complementary-certifications-scoring.js
> +    _hasAcquiredPixCertification(assessmentResult)
on pourrait pas faire un assessmentResult.hasAcquired() et avoir dans le modèle AssessmentResult ?

```
hasAcquired() {
    return this.status.VALIDATED;
  }
```

2024-01-31 13:42 UTC, Steph0 commented on api/tests/tooling/domain-builder/factory/build-complementary-certification-badge.js
> +function buildComplementaryCertificationBadge({ id = 123, level = 1, minimumEarnedPix = 50 } = {}) {
Si déplacement dans src, pensez aussi à contextualiser le domain-builder dans le index.js (ligne 177) ; cela ressemble à ça 

```
const certification = {
  session: {
    buildCenter,
    buildCertificationSessionCandidate: buildCertificationSessionCandidate,
    buildCertificationSessionEnrolledCandidate: buildCertificationSessionEnrolledCandidate,
    buildCertificationSessionComplementaryCertification: buildCertificationSessionComplementaryCertification,
  },
};
```

2024-01-31 13:42 UTC, Steph0 commented on api/lib/domain/models/ComplementaryCertificationScoringCriteria.js
> +    complementaryCertificationId,
Ce champ m'embête ; on possède déjà `complementaryCertificationBadgeId`, qui du coup permet de récupérer le `complementaryCertificationId`. Et je n'ai pas vu son usage niveau usecases ou events. 

A quoi vous sert-il ?

2024-01-31 13:42 UTC, Steph0 commented on api/lib/domain/models/ComplementaryCertificationScoringWithComplementaryReferential.js
> +    pixScore,
L'ajout de ces champs dans ce commit fait que du coup il n'y a plus aucune difference (a priori) entre ComplementaryCertificationScoringWithoutComplementaryReferential` et `ComplementaryCertificationScoringWithComplementaryReferential` (en faisant un diff entre les fichiers, les fonctions _isAboveMinimumScore` sont juste pas nommes dans l'autre fichier)

Pouvons nous du coup n'avoir qu'une seule entité en lieu et place de ces ajouts de champs ?

Eventuellement déplacer aussi vers src 😊

2024-01-31 13:42 UTC, Steph0 commented on api/lib/domain/events/handle-complementary-certifications-scoring.js
> +        return await _saveLowerLevel({ complementaryCertificationScoring, badgeNextLowerLevel });
'tention au  `return await`, le return suffit

2024-01-31 13:42 UTC, Steph0 commented on api/lib/domain/events/handle-complementary-certifications-scoring.js
> +function _hasAcquiredLowerLevel({
Bon je le mets ici mon commentaire, mais je me demande si ça devrait pas être autre part (genre quand on récupère les badges) :xD

Est-ce que on devrait pas bloquer / gérer le fait qu'un badge est `detached` ?

Je vais essayer de détailler ma pensée.

Pour moi une justification de faire la jointure dans le premier commit, est que on veut potentiellement autoriser le fetch de badges detachés ; dès fois que l'on voudrait rescorer des certifs dans un état détaché.

Sauf qu'en vrai on devrait jeter une erreur si on essaye de re-scorer une complémentaire qui est plus sur un profil détaché.

Et du coup dans le repository du premier commit plutôt que de faire la jointure on pouvait juste chercher les autres badges avec la même 'key' et detached = NULL (et au revoir la jointure 😄 yes !!)

Même en oubliant le repository je me dis que ça devrait être pris en compte de checker qu'on cherche pas à re-scorer des certifs "cloturées" non ?

2024-01-31 14:02 UTC, Osirisxxl commented on api/lib/domain/events/handle-complementary-certifications-scoring.js
> +  pixScore,
On peut le récupérer de l'assessmentResult

2024-01-31 14:22 UTC, P-Jeremy commented on api/tests/tooling/domain-builder/factory/build-complementary-certification-badge.js
> +function buildComplementaryCertificationBadge({ id = 123, level = 1, minimumEarnedPix = 50 } = {}) {
Alors vu la taille de la PR, il n'y aura pas de déplacement dans SRC :sweat_smile:

2024-01-31 14:25 UTC, P-Jeremy commented on api/lib/domain/events/handle-complementary-certifications-scoring.js
> +function _hasAcquiredLowerLevel({
Vu avec @asrodride, on ne veut pas filtrer sur les profils cibles détachés. on veut scorer / rescorer une certif selon le profil cible utilisé lors de la certif. On score dans les conditions de la certification

2024-01-31 14:44 UTC, Osirisxxl commented on api/src/certification/complementary-certification/infrastructure/repositories/complementary-certification-badge-repository.js
> +    `),
Ouep, très bien ça sera échappé comme ça.
En l'absence de la connaissance sur comment, on avait accepté le comment en étant sûr que ce n'était pas un input utilisateur.

2024-01-31 14:55 UTC, Osirisxxl commented on api/tests/unit/domain/models/ComplementaryCertificationScoringWithComplementaryReferential_test.js
> +    it('returns false when pixScore is under minimumEarnedPix rat even if Pix+ certification is acquired', function () {
```suggestion
    context('when pixScore is under minimumEarnedPix rate even if Pix core certification is acquired', function () { it('returns false', function () {
```

2024-01-31 14:55 UTC, Osirisxxl commented on api/tests/unit/domain/models/ComplementaryCertificationScoringWithComplementaryReferential_test.js
> +    it('returns false when pixScore is under minimumEarnedPix rat even if Pix+ certification is acquired', function () {
Le nom du test précédent est aussi à changer pour les même raisons 💡 (je soupçonne un copier coller 😉 )

2024-01-31 14:58 UTC, Osirisxxl commented on api/src/certification/complementary-certification/infrastructure/repositories/complementary-certification-badge-repository.js
> +    .select('complementary-certification-badges.*')
Est-ce qu'on peut trouver un p'tit nom pour la classe dans ce cas là ?
Qu'on ait pas l'impression de manipuler des badges alors qu'on a qu'une petite partie de l'objet :)

2024-01-31 15:01 UTC, Osirisxxl commented on api/src/certification/complementary-certification/infrastructure/repositories/complementary-certification-badge-repository.js
> +const getAllWithSameTargetProfile = async function (complementaryCertificationBadgeId) {
Je veux bien en parler de vive voix si tu es chaud Stephen :) 

Au doigt mouillé je dirais de laisser passer la PR telle quelle et de faire le refacto approprié dans une autre PR, sans attendre :)

2024-01-31 15:08 UTC, Osirisxxl commented on api/lib/domain/models/ComplementaryCertificationScoringWithComplementaryReferential.js
> +    pixScore,
Je pense que ça vaut le coup de reprendre 5 minutes pour regarder les différences entre 
`ComplementaryCertificationScoringWithComplementaryReferential` et `ComplementaryCertificationScoringWithoutComplementaryReferential` pour voir si on peut n'avoir qu'un seul objet ou mieux mutualiser déjà.

2024-01-31 15:11 UTC, Osirisxxl commented on api/tests/unit/domain/events/handle-complementary-certifications-scoring_test.js
> +        /* eslint-disable mocha/no-setup-in-describe */
maintenant qu'on est dans un beforeEach, je pense qu'on peut enlever la désactivation de règle 🤔

2024-01-31 15:12 UTC, Osirisxxl approved these changes

2024-01-31 15:23 UTC, P-Jeremy commented on api/src/certification/complementary-certification/infrastructure/repositories/complementary-certification-badge-repository.js
> +const getAllWithSameTargetProfile = async function (complementaryCertificationBadgeId) {
J'avoue que je suis pour le refacto dans une seconde PR

2024-01-31 15:37 UTC, P-Jeremy commented on api/src/certification/complementary-certification/infrastructure/repositories/complementary-certification-badge-repository.js
> +    .select('complementary-certification-badges.*')
Effectivement, soit on fait un modèle générique et on instancie toutes les propriétés, soit on n'en prend que quelques unes et on crée une classe spécifique.

ComplementaryCertificationBadgeForScoring ?

2024-01-31 15:40 UTC, aceol commented on api/src/certification/complementary-certification/infrastructure/repositories/complementary-certification-badge-repository.js
> +    `),
Mais on peut à priori ne pas avoir de `raw` du tout

2024-01-31 15:42 UTC, aceol commented on api/src/certification/complementary-certification/infrastructure/repositories/complementary-certification-badge-repository.js
> +};
C'est pas franchement appliqué chez Pix, mais c'est pas bcp de travail, allons y!

2024-01-31 15:43 UTC, aceol commented on api/db/database-builder/factory/build-complementary-certification.js
> +  minimumReproducibilityRateLowerLevel = 60.0,
Ca devait etre en dur mais on a challengé pour mettre ca en parametrable

2024-01-31 15:51 UTC, aceol commented on api/lib/domain/models/ComplementaryCertificationScoringWithComplementaryReferential.js
> +    pixScore,
Ca peut faire l'objet d'une PR a part?

2024-01-31 15:53 UTC, aceol commented on api/lib/domain/models/ComplementaryCertificationScoringWithComplementaryReferential.js
> +    pixScore,
Migration + suppression du fichier en doublon (si doublon)

2024-01-31 15:54 UTC, aceol commented on api/lib/domain/events/handle-complementary-certifications-scoring.js
> +function _hasAcquiredLowerLevel({
Effectivement, on prends le badge pour lequel on s'est positionné lors de la certif. C'est lors du passage de la certif que la question se pose

2024-01-31 15:55 UTC, aceol commented on api/lib/domain/models/ComplementaryCertificationScoringWithComplementaryReferential.js
> +    pixScore,
Il semble que oui!
https://github.com/1024pix/pix/pull/7836#discussion_r1472814770

2024-01-31 15:57 UTC, aceol commented on api/tests/unit/domain/events/handle-complementary-certifications-scoring_test.js
> +        /* eslint-disable mocha/no-setup-in-describe */
On est pas dans le beforeEach, on est dans un describe ici

2024-02-01 08:55 UTC, matthieu-octo commented on api/tests/tooling/domain-builder/factory/build-complementary-certification-badge.js
> +function buildComplementaryCertificationBadge({ id = 123, level = 1, minimumEarnedPix = 50 } = {}) {
Ha ! j'avais pas vu ton commentaire @P-Jeremy du coup j'ai déjà traité le retour pour éviter de créer de la dette liée à la migration 😅

2024-02-01 09:41 UTC, Osirisxxl commented on api/tests/unit/domain/events/handle-complementary-certifications-scoring_test.js
> +        /* eslint-disable mocha/no-setup-in-describe */
bah oui 👓  😞

2024-02-01 09:49 UTC, matthieu-octo commented on api/src/certification/complementary-certification/infrastructure/repositories/complementary-certification-badge-repository.js
> +    .select('complementary-certification-badges.*')
retour traité

2024-02-01 11:11 UTC, matthieu-octo commented on api/tests/unit/domain/models/ComplementaryCertificationScoringWithComplementaryReferential_test.js
> +    it('returns false when pixScore is under minimumEarnedPix rat even if Pix+ certification is acquired', function () {
Retour traité. Par contre @Osirisxxl je n'ai pas appliqué la correction `"Pix core"` car ça ne correspondait pas au contenu du texte, j'ai laissé l'existant :)

2024-02-01 11:13 UTC, matthieu-octo commented on api/lib/domain/events/handle-complementary-certifications-scoring.js
> +        return await _saveLowerLevel({ complementaryCertificationScoring, badgeNextLowerLevel });
retour traité lors du refacto

2024-02-01 11:14 UTC, matthieu-octo commented on api/lib/domain/events/handle-complementary-certifications-scoring.js
> +function _hasAcquiredLowerLevel({
@Steph0 la réponse te convient-elle ?
Si oui, je clos le commentaire :)

2024-02-01 13:30 UTC, matthieu-octo commented on api/lib/domain/models/ComplementaryCertificationScoringWithComplementaryReferential.js
> +    pixScore,
Je suis également aligné sur le fait de traité cette tâche ultérieurement dans un ticket tech à part.
Je clos le commentaire.

2024-02-01 13:45 UTC, matthieu-octo commented on api/lib/domain/events/handle-complementary-certifications-scoring.js
> +    _hasAcquiredPixCertification(assessmentResult)
La méthode `isValidated` dans la classe `AssessmentResult` existe déjà et vérifie exactement la même chose.
J'utilise celle-ci et supprime la fonction `hasAcquired ` présente dans le fichier de scoring.

2024-02-01 13:57 UTC, matthieu-octo commented on api/lib/domain/events/handle-complementary-certifications-scoring.js
> +  pixScore,
retour traité

2024-02-01 13:58 UTC, matthieu-octo commented on api/lib/domain/models/ComplementaryCertificationScoringWithComplementaryReferential.js
> +    pixScore,
Si pas d'objections, ce sera à traiter dans un ticket ultérieur comme proposé précédemment.

2024-02-01 14:10 UTC, matthieu-octo commented on api/lib/domain/models/ComplementaryCertificationScoringCriteria.js
> +    complementaryCertificationId,
Je ne trouve pas non plus d'utilisation de ce champ, je supprime le commit qui de ma perception n'a pas d'utilité.

2024-02-01 14:54 UTC, Steph0 commented on api/lib/domain/models/ComplementaryCertificationScoringWithComplementaryReferential.js
> +    pixScore,
Ca peut être une PR à part, mais ça serait dommage que ça tombe aux oubliettes.

2024-02-01 15:05 UTC, aceol commented on api/lib/domain/events/handle-complementary-certifications-scoring.js
> +function _hasAcquiredLowerLevel({
Un peu en marge du ticket, mais ca vaudrait le coup de changer de version un profil cible, rescorer (sur un badge détaché donc) et voir ce qu'il se passe

2024-02-01 16:09 UTC, Steph0 commented on api/src/certification/complementary-certification/domain/models/ComplementaryCertificationBadgeForScoring.js
> +class ComplementaryCertificationBadgeForScoring {
Ce n'était pas le cas avant, pourquoi venir ajouter le `forScoring` dans cette nouvelle version du code ? 

On souhaite aller vers des entités qui représentent le métie (approche qui tends à aller vers du DDD). Il n'existe pas de notion métier de "badge pour le score".

`ComplementaryCertificationBadge`convenait, il représentait un badge de complémentaire (c'est à dire un RT certifiant dans le voc métier en langue FR) dans ce sous-contexte avec les informations qui lui allaient bien.

Si on veut absolument une entité "dédiée scoring", alors il faut le mettre dans un dossier read-model.

2024-02-01 16:09 UTC, Steph0 commented on api/tests/certification/complementary-certification/integration/infrastucture/repositories/complementary-certification-badge-repository_test.js
> +      function () {
```
context('when no complementary certification badge does not exist'
```

Le contenu du test est bon mais pas se description, tu auras toujours au moins length = 1 si le badge en entrée n'a pas de copains en base

2024-02-01 16:09 UTC, Steph0 commented on api/lib/domain/events/handle-complementary-certifications-scoring.js
> +      acquired,
Nitpick : je trouve que ce `...complementaryCertificationScoring` rend la lecture inutilement compliqué pour gagner une ligne ; ça oblige à aller voir l'implémentation pour comprendre les propriétés tirées

```js
      complementaryCertificationCourseId: complementaryCertificationScoring.complementaryCertificationCourseId,
      label: complementaryCertificationScoring.label,
      complementaryCertificationBadgeId,
      source: ComplementaryCertificationCourseResult.sources.PIX,
      acquired,
```

2024-02-01 16:09 UTC, Steph0 commented on api/lib/domain/events/handle-complementary-certifications-scoring.js
> +    });
* Supprimer la ligne let complementaryCertificationScoring;`
* Mettre `return _buildComplementaryCertificationScoringWithReferential({` ligne 164)
* Supprimer le `else` et mettre `return new ComplementaryCertificationScoringWithoutComplementaryReferential({`

En gros le else n'a pas d'utilité vu que un seul ìf`, on peut gagner en lisibilité en supprimer une variable modifibale (let) et passer en early return avec un gain de quelques lignes de code au passage

2024-02-01 16:09 UTC, Steph0 commented on api/lib/domain/events/handle-complementary-certifications-scoring.js
> +  });
N'y aurait-il pas ici des propriétés qui sont redonnées alors qu'elles sont fournies par les autres propriétés.
Par exemple, pas besoin de passer le `complementaryCertificationBadgeId` puisque fourni par le paramètre `complementaryCertificationScoring.complementaryCertificationBadgeId`

Meme chose pour le `minimumEarnedPix` je crois. A checker les autres

2024-02-01 16:36 UTC, aceol approved these changes

2024-02-01 16:36 UTC, aceol commented
Revue(s) func ok

2024-02-02 08:35 UTC, P-Jeremy commented on api/tests/certification/complementary-certification/integration/infrastucture/repositories/complementary-certification-badge-repository_test.js
> +      function () {
Pas si l'id passé en paramètre n'est pas bon. Après je vois ce que tu veux dire mais du coup inutile de mettre un notFound ici si on est sûr d'en avoir toujours au moins un

2024-02-02 08:39 UTC, P-Jeremy commented on api/src/certification/complementary-certification/domain/models/ComplementaryCertificationBadgeForScoring.js
> +class ComplementaryCertificationBadgeForScoring {
ça ne représentait pas un 'ComplementaryCertificationBadge' à mon sens. Juste quelques infos liés à ce badge. 

Moi si je vois 'ComplementaryCertificationBadge' je m'attends à une représenation complète. Là c'est une partie d'un 'ComplementaryCertificationBadge' uniquement utilisable lors du scoring.

En l'état ce modèle n'est pas utilisable lors d'un autre cas métier

2024-02-02 08:43 UTC, Osirisxxl commented on api/lib/domain/events/handle-complementary-certifications-scoring.js
> +      acquired,
#intellisense

2024-02-02 09:22 UTC, P-Jeremy commented on api/src/certification/complementary-certification/domain/models/ComplementaryCertificationBadgeForScoring.js
> +class ComplementaryCertificationBadgeForScoring {
:warning: Vu en équipe en DSM: 
- Pour un modèle partiel, utiliser des readModels spécifique
- Dans ce cas, on va plutôt, utiliser un model mais instancié complètement

2024-02-02 09:23 UTC, P-Jeremy commented on api/tests/certification/complementary-certification/integration/infrastucture/repositories/complementary-certification-badge-repository_test.js
> +      function () {
⚠️ Vu en équipe en DSM:
- Le notFound a du sens, changer l'intitulé du test

2024-02-02 13:13 UTC, Steph0 commented on api/src/certification/complementary-certification/domain/models/ComplementaryCertificationBadge.js
> +class ComplementaryCertificationBadge {
⭐ 🤩 ⭐

2024-02-02 13:14 UTC, Steph0 commented on api/src/certification/complementary-certification/domain/models/ComplementaryCertificationBadge.js
> +    this.complementaryCertificationI = complementaryCertificationId;
⚠️ 
```
this.complementaryCertificationId = complementaryCertificationId;
```

2024-02-02 13:14 UTC, Steph0 commented on api/src/certification/complementary-certification/domain/models/ComplementaryCertificationBadge.js
> +    this.certificateMessag = certificateMessage;
⚠️ 
```
this.temporaryCertificateMessage = temporaryCertificateMessage;
```

Je pense qu'il manque un fichier de test sur ce model 😬

2024-02-02 13:45 UTC, Steph0 approved these changes
Sacré boulot ! 💪🏻

2024-02-06 09:53 UTC, merged