[FEAT] Ajouter un message d'erreur spécifique lors de la création de parcours autonome non-autorisée (PIX-10994).
1024pix/pix pull request #7959
Opened 2024-02-02 09:32 UTC by Libouk

## :unicorn: Problème
Lorsqu’un utilisateur Pix Admin n’a pas été ajouté en tant que membre de l’organisation des parcours autonomes et qu’il cherche à créer un parcours autonome, il reçoit un message d’erreur “Une erreur est survenue” qui ne lui apporte pas de solution ni de piste pour débloquer la situation.

## :robot: Proposition
On propose de rajouter un message spécifique à ce cas pour informer l’utilisateur qu’il n’est pas membre de l’orga et qu’il doit s’y ajouter s’il souhaite créer un parcours autonome.

## :100: Pour tester
- Se connecter à Pix Admin avec un profil pas ajouté en tant que membre de l'organisation des parcours autonomes.
- Cliquer sur l'onglet Parcours Autonomes 
- Cliquer sur Nouveau parcours autonome
- Remplir les champs et cliquer sur Créer le parcours autonome
- Constater qu'un message d'erreur "" apparait.

2024-02-07 09:27 UTC, La-toile-cosmique requested changes

2024-02-07 09:27 UTC, La-toile-cosmique commented on admin/app/controllers/authenticated/autonomous-courses/new.js
> +      return this.notifications.error(this.intl.t('pages.autonomous-courses.notifications.failure.error-occurred'));
Mouais je doute de la pertinence de catcher, comparer et traduire les messages. Je pense qu'on peut se permettre de balancer le detail dans la notif et c'est tout.

2024-02-07 09:43 UTC, Libouk commented on admin/app/controllers/authenticated/autonomous-courses/new.js
> +      return this.notifications.error(this.intl.t('pages.autonomous-courses.notifications.failure.error-occurred'));
J'ai respecté ce qui est recommandé dans l'[ADR d'affichage des messages d'erreur](https://github.com/1024pix/pix/blob/dev/docs/adr/0044-gestion-erreurs-i18n-reference.md).
La comparaison sur le message d'erreur est un peu sketchy, il aurait mieux valu remonter un code d'erreur depuis le back mais on n'a pas la main.

2024-02-07 12:47 UTC, La-toile-cosmique commented on admin/translations/fr.json
> +          "error-occurred": "Une erreur est survenue.",
ce message est très générique, je suis pas sûr qu'il ait sa place dans cette arborescence

2024-02-07 12:47 UTC, La-toile-cosmique commented on admin/app/controllers/authenticated/autonomous-courses/new.js
> +      return this.notifications.error(this.intl.t('pages.autonomous-courses.notifications.failure.error-occurred'));
Et si c'était une autre app que l'admin, j'aurais été d'accord. Mais là les utilisateurs internes veulent juste un message à peu près compréhensible.
La ça donne un truc un peu boiteux qui tente de respecter un standard mais s'en donner les moyens.
Si tu veux vraiment faire cet effort alors il faut renvoyer un code depuis l'API et se baser sur ce code.
Et même si tu le fais je pense qu'on peut quand même afficher le "detail" de l'erreur dans la notif si l'erreur n'est pas attendue ( n'est pas interceptée et traduite ).

2024-02-07 13:50 UTC, Libouk commented on admin/app/controllers/authenticated/autonomous-courses/new.js
> +      return this.notifications.error(this.intl.t('pages.autonomous-courses.notifications.failure.error-occurred'));
Donc selon toi je ferais mieux de faire sauter le catch existant sur le bad request error et ne pas rajouter ma gestion d'erreur, enlever également le message générique et uniquement remonter le détail de l'erreur car on est sur Pix Admin ?

2024-02-07 14:16 UTC, La-toile-cosmique commented on admin/app/controllers/authenticated/autonomous-courses/new.js
> +      return this.notifications.error(this.intl.t('pages.autonomous-courses.notifications.failure.error-occurred'));
yup, ou alors si vraiment tu veux garder l'i18n, retourner un code d'erreur et utiliser ce code comme clé pour aller au bout de la démarche. Personnellement je trouve que c'est beaucoup d'efforts pour l'admin mais les deux solutions sont acceptables pour moi.

2024-02-07 14:18 UTC, Libouk commented on admin/app/controllers/authenticated/autonomous-courses/new.js
> +      return this.notifications.error(this.intl.t('pages.autonomous-courses.notifications.failure.error-occurred'));
Je n'ai pas fait cette solution car ça touche à la création de campagne qui se trouve dans le scope Prescription. Je pars sur l'option d'afficher le error detail quand il existe

2024-02-07 14:53 UTC, La-toile-cosmique approved these changes

2024-02-08 11:29 UTC, Jeyffrey approved these changes

2024-02-09 09:07 UTC, merged