[FEATURE] Ajout de commentaire jury automatique en cas d'annulation de certification pour trop de challenges neutralisés (PIX-10532)
1024pix/pix pull request #8233
Opened 2024-02-29 17:26 UTC by Osirisxxl

## :unicorn: Problème
Pour les certifications v2 et v3, si plus de 33% des questions posées au candidat sont neutralisées, alors la certification est annulée.

Un message automatique doit être adressé dans ce cas au candidat et à l’organisation pour les en informer.

## :robot: Proposition
Insertion des clés de traduction dans la colonne commentByAutoJury pour le cas où la certification est annulée suite à la neutralisation de plus de 33% des questions posées au candidat.

## :rainbow: Remarques
- La quasi-totalité du boulot est déjà fait 💪 
- Il n'y a que des tests unitaires sur le scoring... Vu l'ampleur de la PR, je n'en rajoute pas à cette occasion

## :100: Pour tester
Pending

2024-02-29 18:31 UTC, Osirisxxl commented on api/src/certification/shared/domain/models/JuryComment.js
> +   * @param {AutoJuryCommentKey} [props.commentByAutoJury]
Rend le paramètre optionnel 💡

2024-02-29 18:35 UTC, Osirisxxl commented on api/src/certification/shared/domain/models/JuryComment.js
>  const JuryCommentContexts = Object.freeze({
Permet de définir le type `JuryCommentContext` et d'avoir une validation cohérente de la propriété context lors d'une instanciation de JuryComment.
https://github.com/1024pix/pix/pull/8233/files#diff-c816efe6b03ea4b9d4580ab3d8ea6c6a00b55828542984cfe4aa14620a381c5aR29

2024-03-01 10:22 UTC, Steph0 requested changes, later dismissed
Il manque la partie V3 à passer sur la clé automatique (actuellement c'est du automatoque mais en dur)

![image](https://github.com/1024pix/pix/assets/170271/f74bd686-938d-4594-8da1-b1ee9853a311)


https://github.com/1024pix/pix/blob/05a6a774715f96136c773962ee5eb0d3167e2831/api/lib/domain/events/handle-certification-rescoring.js#L143

2024-03-01 14:20 UTC, Steph0 commented
⚠️ Pour la V3 c'est le même message, mais pas les mêmes "raisons" techniques, du coup c'est ptet pas le bon nom qui a été donné à la clé.
Dans le cas V2, c'est sur un pourcentage lié à un contexte de neutralisation ; dans la V3 la raison technique c'est le nombre minimal de réponse nécessaires à une V3 (fixé en base).

Au final les deux par contre c'est bien du CANCELLED. Mais faudrait une clé + générique du genre CANCELLED_INSUFFICIENT_ANSWERS

2024-03-01 15:52 UTC, AndreiaPena commented
Testé func pix admin 
<img width="1707" alt="Capture d’écran 2024-03-01 à 15 33 24" src="https://github.com/1024pix/pix/assets/58915422/0e206f75-ddc8-4424-aa37-6491f16b937a">
<img width="1707" alt="Capture d’écran 2024-03-01 à 16 50 10" src="https://github.com/1024pix/pix/assets/58915422/36f82813-876b-40ff-b771-3e9de44de6ed">

2024-03-01 16:04 UTC, AndreiaPena approved these changes

2024-03-01 16:07 UTC, aceol approved these changes

2024-03-01 16:42 UTC, merged