[TECH] Migrer l'injection de certification/shared vers certification/course (PIX-1473)
1024pix/pix pull request #8446
Opened 2024-03-18 20:35 UTC by aceol

## :unicorn: Problème

## :robot: Proposition

## :rainbow: Remarques

## :100: Pour tester

2024-03-25 13:02 UTC, aceol commented
- [ ] find-certification-attestations-for-division.js
- [ ] get-certification-attestation.js
- [ ] get-certification-attestations-for-session.js
- [ ] get-next-challenge-for-certification.js
- [ ] get-session-certification-reports.js
- [ ] get-v3-certification-course-details-for-administration.js
- [ ] reject-certification-course.js
- [ ] unreject-certification-course.js

2024-03-26 13:19 UTC, Osirisxxl approved these changes
Review tech 👌

2024-03-26 15:51 UTC, alexandrecoin commented
Je pense pas que ça soit lié à cette PR mais j'ai eu ça sur la page de détails d'une certif v3.
<img width="1712" alt="Capture d’écran 2024-03-26 à 16 50 28" src="https://github.com/1024pix/pix/assets/36371437/4c8ae4ae-38a2-4555-b034-75c468991ead">

2024-03-27 16:03 UTC, matthieu-octo commented
review tech OK

review fonc en cours ...

2024-03-27 16:38 UTC, aceol commented
> Je sais pas si c'est à lié à cette PR mais j'ai eu ça sur la page de détails d'une certif v3. <img alt="Capture d’écran 2024-03-26 à 16 50 28" width="1712" src="https://private-user-images.githubusercontent.com/36371437/316940041-4c8ae4ae-38a2-4555-b034-75c468991ead.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE1NTc2NzIsIm5iZiI6MTcxMTU1NzM3MiwicGF0aCI6Ii8zNjM3MTQzNy8zMTY5NDAwNDEtNGM4YWU0YWUtMzhhMi00NTU1LWIwMzQtNzVjNDY4OTkxZWFkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI3VDE2MzYxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcwNjY5MmMwZDA1MDYyM2RiNDg0MGI1MGNjMGQ5MTgxZDQ2MTBlNDUzYmQ2MDg1NjJiNjE2NTgxNzdmOGUzZDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.E2qqgXMHrpkvHxXlNQisSMcbVEh7YXG0n__2XNCY2Bw">

Ca pourrait etre lié à cettte route, c'est sur quelle url?
get-v3-certification-course-details-for-administration.js

2024-03-27 17:07 UTC, matthieu-octo approved these changes

2024-03-28 13:09 UTC, alexandrecoin requested changes
Je bloque pour éviter le merge le temps de voir ce qu'il s'est passé avec la certif v3.

2024-03-29 14:54 UTC, alexandrecoin approved these changes

2024-03-29 15:55 UTC, merged