[FEATURE] Modifs mineures de contenu des modules en production
1024pix/pix pull request #8516
Opened 2024-03-26 16:02 UTC by mgout

## :unicorn: Problème
Les modules comportent des erreurs mineures de contenu (bonnes réponses non comptabilisées comme telles, absence d'alternative textuelle)

## :robot: Proposition
Rédaction des contenus manquants.

## :rainbow: Remarques
RAS

## :100: Pour tester
Accéder aux modules dans un navigateur.

2024-03-29 12:59 UTC, dlahaye requested changes

2024-03-29 12:59 UTC, dlahaye commented on api/src/devcomp/infrastructure/datasources/learning-content/modules/bien-ecrire-son-adresse-mail.json
> +              "solutions": ["naomizao457@yahoo.com", "naomizao457@yahoo.fr", "naomizao457@Yahoo.com", "naomizao457@Yahoo.fr"]
@mgout si tu mets à jour ta branche avec la dev, tu verras que Romain a déjà corrigé ce cas. Tu n'auras donc pas à modifier ces deux lignes.
Tu peux voir la modif en question sur le fichier de la branche de dev : 
https://github.com/1024pix/pix/blob/dev/api/src/devcomp/infrastructure/datasources/learning-content/modules/bien-ecrire-son-adresse-mail.json#L365

La bonne pratique est donc en local:
- mettre à jour la branche dev
- retourner sur ta branche de travail
- rebase dev sur ta branche
- régler le conflit
- commit + push force

2024-04-08 12:55 UTC, yannbertrand commented
@mgout j'ai l'impression que des `alt` (Texte alternatif) sont manquants sur des images informatives (voir https://1024pix.atlassian.net/wiki/spaces/CONT/pages/3255140365/In+pursuit+of+A11Y+aka+accessibilit#%E2%84%B9-Les-images-informatives)

2024-04-09 09:44 UTC, yannbertrand approved these changes

2024-04-09 09:45 UTC, dlahaye approved these changes

2024-04-09 12:24 UTC, jeromechezpix commented
Voici mes retours sur les alternatives textuelles proposées.

Dans le module sur l'adresse IP, l'illustration étant complexe, l'alternative textuelle devrait être un minimum structurée. Pour l'attribut `alt`, je propose : "capture d’écran d’une page de résultats d’une recherche en ligne décrite dans l’alternative textuelle". Le texte alternatif actuel ("Image décrite (…)") est trop vague. Pour l'alternative textuelle, je vois deux options. La première consiste à faire une simple liste : 
- Champ de recherche : « recettes de cuisine végétariennes »
- Liste de résultats de recherche
  - Lien vers SOSCuisine
  - Lien vers CuisinePop.com
- Bouton « Plus de résultats »
- Pied da page : « France. Toulouse. D’après votre adresse IP. Mettre à jour ma position. »

Une seconde option consisterait à reproduire plus fidèlement la structure au moyen de balises de titre. Mais j'ai l'impression que la première est pédagogiquement suffisante.

RAS dans le module pour distinguer le vrai du faux. 

Pour la clé USB, j'ai l'impression que mettre ou ne pas mettre de texte alternatif a le même effet (illustration décorative). Mais ça ne coûte rien de le mettre.

Pour le module sur Wikipédia, on peut ajouter la source et la licence après la liste.

2024-04-09 13:14 UTC, jeromechezpix commented
Suite de mes retours après avoir déroulé les modules (ce que j'avais omis de faire en première lecture).

Pour le module sur l'adresse mail, j'ai l'impression qu'on peut se dispenser de parler de "blocs" et se contenter de parler de "parties". Je propose donc de simplifier le texte alternatif en "schéma de la syntaxe d’une adresse mail décrit dans l’alternative textuelle" et l'alternative textuelle en : 
- Partie 1 : identifiant, exemple : mickael.aubert123
- Séparateur : arobase
- Partie 2 : fournisseur d'adresse mail, exemple : laposte.net

Il me semble que @ est vocalisé "arobase" par les lecteurs d'écran, donc on pourrait mettre simplement le symbole.

Dans le module pour distinguer le vrai du faux, la description des tweets peut être améliorée. D'abord au niveau du texte alternatif, mettre pour le premier : "publication de FanDuRealMadrid (@FanRealBoss) sur X (Twitter) détaillée dans l'alternative textuelle" (ne pas mettre "Image décrite dans l'alternative textuelle"). Puis, dans l'alternative textuelle, ajouter les métadonnées : 
> Publication de FanDuRealMadrid (@FanRealBoss) sur X (Twitter) à 8 h 32 le 17 octobre 2023 : « ENFIN ! Kylian Mbappé va quitter le PSG pour rejoindre le Real Madrid. Tu es un vrai 10 !! https://www.goal.com/fr/news/le-psg-tente-un-dernier-coup-avec-kylian-mbappe/bltcba9cc42978c4f80 ».

Pour les deux suivants, ajouter les nombres de retweets/republications, citations et likes après la publication entre guillemets.
Note : on ne devrait plus parler de Twitter et de (re)tweets, mais de X (Twitter) et de (re)publications.
Pour Alain Bacri, je propose de séparer la publication et les indices : 
> Publication de Alain Bacri (@AlainBacri) sur X (Twitter) à 9 h 22 le 6 août 2022 : « Arrêtez TOUS le DOLIPRANE !!!
(2 émojis tête de mort) Le paracétamol TUE les gens !!!! mais personne en parle ! (2 emojis tête de mort) Il y a plusieurs PREUVES SCIENTIFIQUE qui le PROUVE, comme cet étude américaine : https://pubmed.ncbi.nlm.nih.gov/37436926/ PARTAGER à un MAXIMUM de personnes. Il faut que ça se sache !!! »
> - Indice 1 : Les majuscules et les émojis angoissants sont utilisés pour interpeller, créer un ton alarmiste et un sentiment d'urgence.
> - Indice 2 : […]

Pour l'attribut `alt` : "publication de Alain Bacri (@AlainBacri) sur X (Twitter) avec trois indices détaillés dans l’alternative textuelle".
Pour Stéphane le jardinier, je pense qu'il n'est pas utile de mentionner les visuels ni le concept de story. Texte alternatif proposé : "informations sur la pousse des plantes vertes détaillées dans l'alternative textuelle". Alternative textuelle : 
> Vos plantes vertes ne poussent pas ? Voici 2 super astuces dont vous ne pourrez plus vous passer !
> Astuce 1 : Privilégier la lumière directe pendant 72 h. Un grand bain de soleil pendant 72 h, ça fait toujours du bien ! Votre plante va adorer.
> Astuce 2 : Ajoutez de la spiruline à la terre. Vous trouverez d’ailleurs un lien en description avec le code promo JARDINIER3000.
Ça ne me semble pas utile non plus de refléter la structure en trois blocs.

Dans le module sur les sources d'informations, l'introduction des tweets est simplement à harmoniser avec celle du module sur le vrai du faux.

2024-04-09 14:57 UTC, jeromechezpix commented
Enfin, pour le module sur les ports de connexion, je suis réservé, car tout repose sur de la reconnaissance visuelle. On ne peut répondre à aucune question si on est non-voyant, même avec une description des images. Les textes alternatifs me semblent pédagogiquement inopérants. Je ne sais pas trop quoi recommandé ici.

2024-04-10 12:52 UTC, mgout commented
Modifications faites dans le dernier commit pour les 6 modules concernés, un grand merci pour ta relecture experte Jérôme ! 
Concernant le module ports de connexion, je te rejoins sur le commentaire, je ne change pas les alternatives, un effort supplémentaire ne me paraît pas justifié pour l'instant.

2024-04-10 13:33 UTC, merged