[FEATURE] Sauvegarde de la langue du candidat au début d'une certif V3 (PIX-11279).
1024pix/pix pull request #8563
Opened 2024-04-02 09:47 UTC by alexandrecoin

## :unicorn: Problème

Dans le cadre de la nouvelle certification Pix, et pour assurer la continuité avec la certification actuelle, nous allons permettre aux candidats de passer la certif en anglais.

Pour permettre de passer la certification dans une langue donnée, nous allons nous baser sur la langue du compte au lancement du test de certification par le candidat. 

La langue du compte au moment où le test est lancé par le candidat n’est pas une information que l’on stock aujourd’hui.

## :robot: Proposition

Sauvegarde la langue de l'utilisateur récupérée au lancement de la certif V3

## :rainbow: Remarques

## :100: Pour tester

• Créer une session de certification V3 (`certifv3@example.net`)
• Commencer le test (`certifiable-contenu-user@example.net`)
• Vérifier que la langue du candidat a été enregistrée en BDD (table `certification-courses`)

Pour aller plus loin : 

Refaire la même chose en changeant la langue du candidat avant et pendant le test (sur `.org`) et vérifier que la langue enregistrée correspond à celle utilisée avant le début du test.

2024-04-02 13:01 UTC, AndreiaPena commented
Testé func 

enregistrement en BDD de la lang lors de la création du `certification-courses` ✅ 
<img width="307" alt="Capture d’écran 2024-04-02 à 14 56 54" src="https://github.com/1024pix/pix/assets/58915422/c3bb2036-b747-46d8-9855-2005ad83a8fd">

J'ai ensuite quitté la certif, je me suis enregistré en lang EN sur pix app et je suis retournée sur la certification.
Je me retrouve avec un affichage en anglais et le contenu des épreuves en français 

<img width="1144" alt="Capture d’écran 2024-04-02 à 14 58 57" src="https://github.com/1024pix/pix/assets/58915422/b7215207-73b6-486c-a849-921d7fe0b304">

2024-04-02 13:23 UTC, AndreiaPena requested changes, later dismissed
J'ai pu entrer en certif V3 en néerlandais et il me semble qu'il ne fait pas partie des langues dispo pour la certif

<img width="293" alt="Capture d’écran 2024-04-02 à 15 20 56" src="https://github.com/1024pix/pix/assets/58915422/27db946c-076d-4b8e-9b63-5dedee9ed06a">
<img width="1124" alt="Capture d’écran 2024-04-02 à 15 21 05" src="https://github.com/1024pix/pix/assets/58915422/26cc7aea-ace1-4b86-be3e-8f756464f35c">

2024-04-03 09:55 UTC, AndreiaPena commented
On empêche bien l'accès à la certification si nl est enregistré mais on reçoit une 500. Il faut qu'on soit en mesure d'indiquer à l'utilisateur qu'il ne peut entrer en session avec cette langue.

<img width="1297" alt="Capture d’écran 2024-04-03 à 11 48 06" src="https://github.com/1024pix/pix/assets/58915422/26c24d78-2cc6-4218-af15-83b424a2262f">

Le message d'erreur : `{"type":"Error","message":"Cant create a certification course in nl","stack":"Error: Cant create a certification course in nl\n at retrieveLastOrCreateCertificationCourse (file:///app/lib/domain/usecases/retrieve-last-or-create-certification-course.js:78:13)\`

2024-04-03 12:06 UTC, AndreiaPena approved these changes

2024-04-03 12:06 UTC, AndreiaPena commented
> On empêche bien l'accès à la certification si nl est enregistré mais on reçoit une 500. Il faut qu'on soit en mesure d'indiquer à l'utilisateur qu'il ne peut entrer en session avec cette langue.
> 
> <img alt="Capture d’écran 2024-04-03 à 11 48 06" width="1297" src="https://private-user-images.githubusercontent.com/58915422/319134449-26c24d78-2cc6-4218-af15-83b424a2262f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIxNDYyNzAsIm5iZiI6MTcxMjE0NTk3MCwicGF0aCI6Ii81ODkxNTQyMi8zMTkxMzQ0NDktMjZjMjRkNzgtMmNjNi00MjE4LWFmMTUtODNiNDI0YTIyNjJmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDAzVDEyMDYxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQyYjIwZmNjZjEwYmI4OTZhZDI3ZGJlOGQ5Mjk0M2UzYWVhYWI2YmUyYjU5Mzg1NGU1ODBhYmM3ZjU2ZTMzMWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.CcIKRnGFok0RyFFFOZfa0ZfCRp76iNso6PmeDlmzCmg">
> Le message d'erreur : `{"type":"Error","message":"Cant create a certification course in nl","stack":"Error: Cant create a certification course in nl\n at retrieveLastOrCreateCertificationCourse (file:///app/lib/domain/usecases/retrieve-last-or-create-certification-course.js:78:13)\`

vu ensemble, un ticket est prévue pour cette gestion d'erreur

2024-04-03 15:47 UTC, aceol commented on api/lib/domain/usecases/retrieve-last-or-create-certification-course.js
> +      throw new Error(`Cant create a certification course in ${user.lang}`);
```suggestion
      throw new Error(`Can't create a certification course in ${user.lang}`);
```

2024-04-03 15:54 UTC, aceol approved these changes

2024-04-03 15:54 UTC, aceol commented on api/lib/domain/usecases/retrieve-last-or-create-certification-course.js
> +      throw new Error(`Cant create a certification course in ${user.lang}`);
On pourrait renvoyer un code d'erreur, pour avoir la traduction coté front par exemple en neerlandais

2024-04-03 15:54 UTC, aceol commented on api/lib/domain/usecases/retrieve-last-or-create-certification-course.js
> +  return user.isLanguageAvailableForV3Certification();
Remarque: Je trouve assez êtonnant d'avoir mis coté user, ca ne semble pas etre de sa responsabilité de connaitre cela

2024-04-03 15:54 UTC, aceol commented on api/tests/unit/domain/usecases/retrieve-last-or-create-certification-course_test.js
> +                  });
On pourrait aussi faire:
```suggestion
          const {created, certificationCourse} = await retrieveLastOrCreateCertificationCourse({
                      domainTransaction,
                      sessionId: 1,
                      accessCode: 'accessCode',
                      userId,
                      locale: 'fr',
                      ...injectables,
                    });

                    // then
                    expect(created).to.be.true;
                    expect(certificationCourse)to.deep.equalInstanceOf(new CertificationCourse({
                        ...savedCertificationCourse.toDTO(),
                        assessment: savedAssessment,
                        challenges: [],
                        version: 3,
                        lang: user.lang,
                      }),
                  });
```

2024-04-03 18:18 UTC, alexandrecoin commented on api/lib/domain/usecases/retrieve-last-or-create-certification-course.js
> +      throw new Error(`Cant create a certification course in ${user.lang}`);
Comme vu avec Andreia, tout ce qui concerne la gestion des erreurs (front & back) se trouve dans le prochain ticket.

2024-04-04 07:01 UTC, alexandrecoin commented on api/lib/domain/usecases/retrieve-last-or-create-certification-course.js
> +  return user.isLanguageAvailableForV3Certification();
La langue est pourtant une des propriétés de l'utilisateur. Ca me parait pas déconnant.

2024-04-04 12:33 UTC, merged