[TECH] Protège de commit sur la branche dev via Husky
1024pix/pix pull request #8620
Opened 2024-04-09 13:36 UTC by aceol

## :unicorn: Problème
"Tout le monde" peut commiter sur la branch dev alors que cela ne devrait être fait que via un merge.
Proteger directement la branche via github n'est pour le moment pas possible à cause de la CI

## :robot: Proposition
Utiliser husky pour prevenir tout commit sur dev

## :rainbow: Remarques
La partie lint ne bloquait pas le commit, elle affichait l'erreur mais c'est tout

## :100: Pour tester
En local:
`npm run local:add-optional-checks`
Remplacer dans `.husky/protect-branch` 
`protected_branch=dev` par le nom de la branche à tester, par exemple `protected_branch=protect-dev-commit-husky`

Tenter de faire un commit et s'assurer que ca ne fonctionne pas. 

Remettre `dev`
ajouter une erreur de lint
Tenter de commiter et s'assurer que cela ne fonctionne pas

2024-04-10 08:31 UTC, P-Jeremy submitted a review, later dismissed

2024-04-10 08:44 UTC, P-Jeremy commented
Test func ko

![image](https://github.com/1024pix/pix/assets/37305474/793b134a-c465-4118-b71c-cd4d79a7374b)
![image](https://github.com/1024pix/pix/assets/37305474/d34ed4de-8766-4f94-8878-c86804c4ba5d)
![image](https://github.com/1024pix/pix/assets/37305474/ba558980-db2d-4e66-9786-3dd1b64ef6f5)

2024-04-10 13:09 UTC, Steph0 requested changes
En l'état la PR ne peut pas passer ainsi (toto + la valeur de protected_branch) + test func KO (voir ci-dessous)

![image](https://github.com/1024pix/pix/assets/170271/372992cc-a4bc-4ae5-a744-2cc243745cc6)

![image](https://github.com/1024pix/pix/assets/170271/493206d9-d543-49f4-9731-3add93874d91)

![image](https://github.com/1024pix/pix/assets/170271/92e88fc8-ca6d-46cc-b271-c65cdb7a9b84)

2024-04-10 13:09 UTC, Steph0 commented on api/lib/domain/models/CertificationResult.js
> +
Oubli de retirer cela ?

2024-04-10 13:09 UTC, Steph0 commented on .husky/protect-branch
> +current_branch=$(git symbolic-ref HEAD | sed -e 's,.*/\(.*\),\1,')
Applicable au fichier de pre-commit, il faudrait mettre un shebang, cela réduira les effets de bord et d'interprétation propre à une configuration locale.
C'est le cas dans les autres scripts d'ailleurs.

En particulier dans le cas ici où on utilise des notations (les double `[[`) qui je crois de souvenir est propre à bash.

2024-04-10 13:09 UTC, Steph0 commented on .husky/protect-branch
> +current_branch=$(git symbolic-ref HEAD | sed -e 's,.*/\(.*\),\1,')
```suggestion
#!/usr/bin/env bash
current_branch=$(git symbolic-ref HEAD | sed -e 's,.*/\(.*\),\1,')
```

2024-04-10 13:09 UTC, Steph0 commented on .husky/protect-branch
> +exit 0
J'avais proposé sur le chan un script qui avait été testé et vérifié, qui est écrit avec moins de features non POSIX et sans des outils comme sed. Eventuellement je proposerai bien de le ré-utiliser :)

Je le remets ci-dessous

```sh
#!/bin/sh
locked_branch='dev'
push_branch=$(git rev-parse --abbrev-ref HEAD)

if [ "$locked_branch" = "$push_branch" ]
then
    echo "Do not push this branch! (git hooks)"
    exit 1
fi
exit 0
```

2024-04-10 13:09 UTC, Steph0 commented on .husky/protect-branch
> +protected_branch=protect-dev-commit-husky
```suggestion
protected_branch=dev
```

2024-04-10 14:10 UTC, P-Jeremy commented on api/lib/domain/models/CertificationResult.js
> +
non c'était pour montrer à @aceol que ça n'avait pas fonctionné :sweat_smile:

2024-04-10 14:18 UTC, P-Jeremy commented on .husky/protect-branch
> +protected_branch=protect-dev-commit-husky
@Steph0 C'était une modif temporaire de mon commit déstiné à disparaître

2024-04-10 16:09 UTC, aceol commented
> Test func ko 😢
> 
> ![image](https://private-user-images.githubusercontent.com/37305474/321166736-793b134a-c465-4118-b71c-cd4d79a7374b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI3NjUxNDEsIm5iZiI6MTcxMjc2NDg0MSwicGF0aCI6Ii8zNzMwNTQ3NC8zMjExNjY3MzYtNzkzYjEzNGEtYzQ2NS00MTE4LWI3MWMtY2Q0ZDc5YTczNzRiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDEwVDE2MDA0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdlYTY2OTI4YTM4N2UxNmM4MTY5NTg2MTU4NGY1YzkwMzhjZTIyZjAyODQ4N2RjZjI0M2Y0NWIyMGEwNGY1MzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.XdcIQWGTekkc0IlwGIpPKz19RdP0M-ysZ0eQGeebAHY) ![image](https://private-user-images.githubusercontent.com/37305474/321166192-d34ed4de-8766-4f94-8878-c86804c4ba5d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI3NjUxNDEsIm5iZiI6MTcxMjc2NDg0MSwicGF0aCI6Ii8zNzMwNTQ3NC8zMjExNjYxOTItZDM0ZWQ0ZGUtODc2Ni00Zjk0LTg4NzgtYzg2ODA0YzRiYTVkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDEwVDE2MDA0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk0N2IxYzlkZTcwMzEwODUxMWMyODgwZDdiODVmZjdkODYyYTBjYzVkNGVlYThhM2NjNjUyY2ViMGY0MTNiOWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.gs2Ph3FHXMl66oYSkpbRxn7_3_JOpE8PuJ--HhgnvQo) ![image](https://private-user-images.githubusercontent.com/37305474/321166344-ba558980-db2d-4e66-9786-3dd1b64ef6f5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI3NjUxNDEsIm5iZiI6MTcxMjc2NDg0MSwicGF0aCI6Ii8zNzMwNTQ3NC8zMjExNjYzNDQtYmE1NTg5ODAtZGIyZC00ZTY2LTk3ODYtM2RkMWI2NGVmNmY1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDEwVDE2MDA0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFiNTQ1ZjJjMGRhNjhhOGVhN2Y5ZDhmY2EwMWJjNWUwNTZjNzZhNWJkYmRmZGY3MTE0NjY4NjRjODlmZDg4ZWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.JWBbPwClXM5YMGvmccm0vOWZGrjkZ0g2xF_d4Vob_8M)

Bizarre que ca soit passé, peut etre à cause de l'environnement...

2024-05-03 13:44 UTC, Steph0 approved these changes
Tous les scripts testés ensemble sur Linux (Xubuntu, sur deux shells différents : bash et zsh) et Mac OS (shell zsh) ✔️

2024-05-03 13:44 UTC, Steph0 commented on .husky/protect-branch
> +current_branch=$(git symbolic-ref HEAD | sed -e 's,.*/\(.*\),\1,')
Done

2024-05-03 13:45 UTC, Steph0 commented on .husky/protect-branch
> +exit 0
Done

2024-05-03 13:45 UTC, Steph0 commented on .husky/protect-branch
> +protected_branch=protect-dev-commit-husky
Removed

2024-05-03 13:45 UTC, Steph0 commented on api/lib/domain/models/CertificationResult.js
> +
Removed

2024-05-03 13:46 UTC, Steph0 commented on .husky/detect-referential
>  SECRET=postgres://postgres:J9FUMSBhei8oU@db.dbhostprovider.com:5434/thedb
Note pour les lecteurs, faudrait pas que cette valeur bouge dans le fichier distant du referentiel 😬

2024-05-03 13:47 UTC, Steph0 approved these changes

2024-05-06 05:26 UTC, HEYGUL commented
> Renome le detect-secret en detect-referentiel
Par soucis de cohérence, je propose de le renommer `detect-learning-content`.

2024-05-07 13:52 UTC, P-Jeremy approved these changes

2024-05-07 13:53 UTC, P-Jeremy commented
It works on my machine !

![image](https://github.com/1024pix/pix/assets/37305474/07726e1e-d214-458e-bfbd-1294952d87cf)

2024-05-07 14:33 UTC, merged