[TECH] Ajouter une valeur par défaut pour LOG_ENABLED
1024pix/pix pull request #8845
Opened 2024-05-06 12:36 UTC by dlahaye

## :unicorn: Problème
Lors de [cette PR](https://github.com/1024pix/pix/pull/8675), une régression a été introduite côté API dans la configuration des variables d'environnements. Ainsi, en local, nous n'avions plus de logs pour l'API, car la variable par défaut LOG_ENABLED était commentée dans le sample.env (et donc dans les .env locaux).

## :robot: Proposition
Ajouter dans le fichier de config api/src/shared/config.js une valeur 'true' par défaut (comme documentée dans le sample.dev).

## :rainbow: Remarques
Le fichier config.js n'est pas testé et on constate qu'il peut y avoir des régressions.
Peut-être faudrait-il tester au cas par cas lorsqu'on trouve une régression (par exemple en commençant par le cas présent) ?
Cela peut être un sujet d'aprèm tech.

## :100: Pour tester

1. Récupérer la branche
2. Commenter la variable LOG_ENABLED dans le .env
3. Lancer l'api en local
4. S'assurer que les logs apparaissent par défaut

2024-05-06 12:39 UTC, yannbertrand approved these changes

2024-05-06 12:54 UTC, aurelie-crouillebois approved these changes

2024-05-06 12:58 UTC, Steph0 commented
Tech func, un KO

LOG_ENABLED = false
![image](https://github.com/1024pix/pix/assets/170271/a0adc071-3f54-49e8-92f7-5f44f2c50ed6)


LOG_ENABLED = true
![image](https://github.com/1024pix/pix/assets/170271/ceb6e9c0-5ad6-41b1-8281-d357c631c431)


Suppression env LOG_ENABLED 🎌 
![image](https://github.com/1024pix/pix/assets/170271/e42212d9-b711-44fe-8b13-1bf6ecf4edbd)

2024-05-06 13:01 UTC, Steph0 requested changes
Je propose le changement suite au KO test func (voir commentaires)

2024-05-06 13:01 UTC, Steph0 commented on api/src/shared/config.js
> +      enabled: toBoolean(process.env.LOG_ENABLED || 'true'),
Il faudrait mettre à jour aussi le `api/lib/infrastructure/validate-environment-variables.js`



```
LOG_ENABLED: Joi.string().allow(null, '').optional().valid('true', 'false'),
```

ou en vrai : et mettre à jour le sample.env en décommentant la ligne 

```
LOG_ENABLED: Joi.string().required()
```

2024-05-06 13:09 UTC, dlahaye commented on api/src/shared/config.js
> +      enabled: toBoolean(process.env.LOG_ENABLED || 'true'),
Alors déjà merci pour la découverte de ce fichier 🎉 
Mais, je ne comprends pas que `Joi` avec une validation `optional` pète malgré tout :/

2024-05-07 07:40 UTC, Steph0 commented on api/src/shared/config.js
> +      enabled: toBoolean(process.env.LOG_ENABLED || 'true'),
Alors je ne saurais plus faire l'historique des conflits entre valid / optional et string. Mais de ce que j'en comprends de la doc c'est que l'instruction actuelle demande un type 'string' avec `string()` où la valeur `null` n'est pas acceptée avec `optionnal` et qui n'a que deux valeurs possibles avec `valid` ce qui viendrait empêcher la valeur `undefined`.

Du coup peut-être que optional est ici superflu (il ne semble pas faire sens au regard de `valid`), mais j'en suis pas certain à 100%.

2024-05-07 09:29 UTC, dlahaye commented on api/src/shared/config.js
> +      enabled: toBoolean(process.env.LOG_ENABLED || 'true'),
Dans ce cas je serai assez partant pour la première proposition, qui conserve le `optional` comme les autres cas
(après, est-ce que mettre du `optional` partout est pertinent, c'est un autre sujet).
Peut-être en rajoutant `undefined` dans le `allow` ?
Tu en penses quoi ?

2024-05-07 09:59 UTC, Steph0 commented on api/src/shared/config.js
> +      enabled: toBoolean(process.env.LOG_ENABLED || 'true'),
Attention, souvent nos `.env` sont sourcés par l'IDE ou notre shell (par exemple sous oh my zsh j'ai loadé automatiquement). Et notre code va chercher les data via `process.env`.

Du coup tu as encore probablement en fait la variable de set au lancement (process.env), essayes par exemple de faire `echo ${LOG_ENABLED}` pour le vérifier (que ton shell est iso ton `.env`).

Bien vérifier de faire cela dans un shell "vierge", ou alors de bien faire un `unset LOG_ENABLED` (ou moi j'avais fait un export dans mon test func, voir ci-dessus).

Il y a tout un sujet sur la façon dont on gère nos var d'envs, [j'avais essayé de l'adresser en tech times ici](https://github.com/1024pix/pix/pull/7405) (avec Simon et Aurélie notamment), mais j'ai pas continué le sujet et c'est un énorme travail.

On fait un pair ensemble pour regarder cela ? :)

2024-05-07 10:00 UTC, yannbertrand commented on api/src/shared/config.js
> +      enabled: toBoolean(process.env.LOG_ENABLED || 'true'),
(J'ai pas d'avis sur votre discussion mais je viens de tomber sur https://joi.dev/tester/ pour expérimenter 😄)

2024-05-07 10:17 UTC, dlahaye commented on api/src/shared/config.js
> +      enabled: toBoolean(process.env.LOG_ENABLED || 'true'),
Vu en pair :)

2024-05-07 11:23 UTC, yannbertrand commented on api/src/shared/config.js
> +      enabled: toBoolean(process.env.LOG_ENABLED || 'true'),
Du coup le `|| 'true'` doit pouvoir être supprimé ici non ?

2024-05-07 11:24 UTC, yannbertrand commented on api/lib/infrastructure/validate-environment-variables.js
> +  LOG_ENABLED: Joi.string().required().valid('true', 'false'),
Il faudra bien communiquer ce changement pour éviter des incompréhensions ! (surtout en cette forte période d'absence ne pas hésitez à en reparler)

2024-05-07 13:28 UTC, yannbertrand approved these changes

2024-05-07 14:05 UTC, Steph0 commented on docker/sample.env
> +LOG_ENABLED=true
Alignement de la propriété faite, mais on a un gros doute sur le fait que ce fichier soit utilisé par quoi / qui que ce soit (en tout cas pas par les tests e2e)

2024-05-07 14:07 UTC, Steph0 approved these changes

2024-05-07 14:07 UTC, Steph0 commented on api/sample.env
>  # presence: optional
Neatpick : 
```suggestion
# presence: required
```

2024-05-14 07:20 UTC, yannbertrand commented
Il manque quelque chose pour merger ?

2024-05-14 07:21 UTC, dlahaye commented
> Il manque quelque chose pour merger ?

Non je ne pense pas. @Steph0 ?

2024-05-14 09:29 UTC, dlahaye commented
@yannbertrand vu avec @Steph0 LGTM 🚀

2024-05-14 10:29 UTC, merged