[FEATURE] Permettre la vocalisation des consignes des épreuves (PIX-11050).
1024pix/pix pull request #9081
Opened 2024-05-28 14:29 UTC by Libouk

## :unicorn: Problème
On souhaite ajouter sur l'écran des épreuves un bouton permettant de lire à haute voix la consigne de l'épreuve. Ce bouton doit pouvoir être affiché et caché depuis un autre bouton présent dans la bannière en haut de page. Ces boutons ne doivent pas s'afficher si les épreuves font partie d'une évaluation de certification. Enfin, ce bouton sera soumis à un feature toggle.

## :robot: Proposition
Ajouter un bouton selon la maquette prévue avec le design. https://www.figma.com/design/f5vigJiL19X7IYiWZuRH9y/XP-d'Eval---Vocalisation?node-id=265-4259&m=dev

## :rainbow: Remarques
Le feature toggle concerné se nomme FT_ENABLE_TEXT_TO_SPEECH_BUTTON

## :100: Pour tester
- Lancer Pix App
- Démarrer un parcours ou une compétence
- Constater que le bouton d'apparition/disparition du bouton de lecture est présent dans la bannière. Activer/désactiver ce bouton affichera ou cachera le bouton de lecture. Constater que l'image et le tooltip de ce bouton changent avec son état.
- Constater la présence du bouton de lecture à haute voix s'il est activé. Appuyer sur ce bouton lancera la lecture de la consigne dans la langue de l'épreuve. Cela entrainera également le changement d'état de l'image du bouton et du tooltip qui y est lié.

2024-05-29 09:04 UTC, AlexNaudyy commented
Autre retour, ne pas faire apparaitre la vocalisation sur les ecrans intermédiaires
<img width="1230" alt="image" src="https://github.com/1024pix/pix/assets/137420545/5f779ff7-ae7f-4389-bb86-39f658e7ddf7">

2024-05-29 10:37 UTC, Libouk commented
> Ne pas faire apparaitre la vocalisation sur les ecrans intermédiaires 

C'est résolu

2024-05-30 12:27 UTC, Jeyffrey commented on mon-pix/app/styles/components/_challenge-statement.scss
> +}
```suggestion
.challenge-statement__instruction-text-to-speech {
  width: 1.5rem;
  height: 1.5rem;
  margin-bottom: 4px;
  font-size: 1rem;
}
```

**suggestion:** je trouve qu'en ajoutant un peu de style (en forçant la taille du bouton en 24x24px (c'est comme ça sur le maquette aussi), on obtient quelque chose d'un peu plus "clean".

2024-05-30 12:27 UTC, Jeyffrey commented on mon-pix/app/components/challenge-statement.hbs
> +                class="challenge-statement__instruction-text-to-speech"
```suggestion
                class="challenge-statement__text-to-speech-trigger"
```
**suggestion:** rendre la classe CSS plus explicite

2024-05-30 12:27 UTC, Jeyffrey commented on mon-pix/app/components/challenge-statement.hbs
> +        <MarkdownToHtmlUnsafe @class="challenge-statement-instruction__text" @markdown={{this.challengeInstruction}} />
```suggestion
        <MarkdownToHtmlUnsafe @class="challenge-statement__text-to-speech-content" @markdown={{this.challengeInstruction}} />
```

2024-05-30 12:27 UTC, Jeyffrey commented on mon-pix/app/components/challenge-statement.hbs
> +      <div class="challenge-statement__instructions-and-text-to-speech">
```suggestion
      <div class="challenge-statement__text-to-speech-container">
```

2024-05-30 12:27 UTC, Jeyffrey commented on mon-pix/app/components/challenge-statement.hbs
>          <div class="sr-only">{{t "pages.challenge.statement.sr-only.alternative-instruction"}}</div>
**suggestion:** je pense que dans le cas où cette instruction alternative existe, c'est plus pertinent que ce soit elle qui soit lue. Parce que de ce que j'en sais, elle décrit des éléments "graphiques" de façon textuelle.

2024-05-30 12:27 UTC, Jeyffrey commented on mon-pix/app/models/feature-toggle.js
> +  @attr('boolean') isTextToSpeechButtonEnabled;
C'est la première fois que je vois cette façon de faire pour un feature-toggle.
Ça ne suffit pas de passer par la config de l'app crée précédemment ?

2024-05-30 12:27 UTC, Jeyffrey commented on mon-pix/translations/fr.json
> +          "stop": "Arrêter la lecture"
```suggestion
          "play": "Écouter l'épreuve",
          "stop": "Arrêter l'écoute de l'épreuve"
```

**suggestion:** spécifier ce qu'on veut écouter ?

2024-05-30 12:27 UTC, Jeyffrey commented on mon-pix/app/components/challenge-statement.js
> +    });
Mettre ce code dans une fonction spécifique `_cancelSpeechSynthesisOnMount` ?

2024-05-30 12:33 UTC, Jeyffrey commented
Aussi, je crois pas avoir vu de tests concernant le non-affichage de la vocalisation dans les épreuves de certification.

2024-05-30 13:01 UTC, La-toile-cosmique requested changes
Nice! 👍🏼 Y'a que le sample.env qui est bloquant pour moi, le reste c'est des pétouilles

2024-05-30 13:01 UTC, La-toile-cosmique commented on mon-pix/app/components/challenge-statement.js
> +  @tracked textToSpeechButtonTooltipText = this.intl.t('pages.challenge.statement.text-to-speech.play');
ça ne marche pas si la propriété n'est pas "tracked" ?

2024-05-30 13:01 UTC, La-toile-cosmique commented on mon-pix/app/components/challenge-statement.js
> +  readInstruction() {
Cette fonction a également en charge de stopper la lecture. toggle ?

2024-05-30 13:01 UTC, La-toile-cosmique commented on api/sample.env
> +# FT_ENABLE_UTTERANCE_BUTTON=false
```suggestion
# FT_ENABLE_TEXT_TO_SPEECH_BUTTON=false
```

2024-05-30 13:01 UTC, La-toile-cosmique commented on mon-pix/app/models/feature-toggle.js
> +  @attr('boolean') isTextToSpeechButtonEnabled;
Ouais ça j'ai pas compris. Pourquoi y'avait rien avant ? C'est pas le seul FT pourtant. Il sert à quoi ce model ? Tellement de mystères !

2024-05-30 13:01 UTC, La-toile-cosmique commented on mon-pix/app/templates/assessments/checkpoint.hbs
> +    />
C'est louche de pas passer `@checkpoint={{true}}` même si c'était déjà comme ça j'en conviens

2024-05-30 13:01 UTC, La-toile-cosmique commented on mon-pix/tests/integration/components/assessment-banner_test.js
> +  module('when the text to speech feature toggle is enabled', function (hooks) {
and when it's not ?

2024-05-30 13:01 UTC, La-toile-cosmique commented on mon-pix/tests/unit/services/feature-toggles_test.js
> +    });
ça répond un peu à ma question précédente

2024-05-30 13:01 UTC, La-toile-cosmique commented on mon-pix/translations/es.json
> +          "activate": "Activar la vocalización",
🇪🇸

2024-05-30 13:07 UTC, La-toile-cosmique reviewed
coucou

2024-05-30 13:17 UTC, La-toile-cosmique commented on mon-pix/translations/es.json
> +          "activate": "Activar la vocalización",
vocalicalización

2024-05-30 13:48 UTC, Libouk commented on mon-pix/app/components/challenge-statement.hbs
> +        <MarkdownToHtmlUnsafe @class="challenge-statement-instruction__text" @markdown={{this.challengeInstruction}} />
C'est du pré-existant utilisé à déjà pas mal d'endroits

2024-05-30 13:50 UTC, Jeyffrey commented on mon-pix/app/models/feature-toggle.js
> +  @attr('boolean') isTextToSpeechButtonEnabled;
Oui ça m'a étonné aussi comme façon de faire.
Mais j'ai trouvé d'autres PR où c'était fait comme ça : https://github.com/1024pix/pix/pull/4611/files#diff-95e59bc460342de44191184818e6126b234b2d2d32f88faa6c20cbf7b187107a

2024-05-30 13:50 UTC, Libouk commented on mon-pix/app/components/challenge-statement.hbs
> +      <div class="challenge-statement__instructions-and-text-to-speech">
Sachant que ce conteneur englobe instructions et text to speech et pas que TTS, que recommandes-tu ?

2024-05-30 13:53 UTC, Jeyffrey commented on mon-pix/app/components/challenge-statement.hbs
> +      <div class="challenge-statement__instructions-and-text-to-speech">
En fait on sait déjà qu'on est dans l'instruction parce que la div parente est `.challenge-statement__instruction-section`.

Et en fait j'ai proposé ce nommage parce que la seule raison pour laquelle cette div semble exister c'est pour la vocalisation.

2024-05-30 14:07 UTC, Libouk commented on mon-pix/translations/fr.json
> +          "stop": "Arrêter la lecture"
Vu avec Alex, trop long pour les affichages mobiles

2024-05-30 14:17 UTC, Libouk commented on mon-pix/app/components/challenge-statement.hbs
>          <div class="sr-only">{{t "pages.challenge.statement.sr-only.alternative-instruction"}}</div>
Après avoir regardé un exemple (/challenges/rec2PY2kIMZxgyyjd/preview) il semble que l'alternative textuelle pourrait plutôt compléter la consigne que la remplacer. Je vois Alex

2024-05-30 14:27 UTC, Libouk commented on mon-pix/app/components/challenge-statement.hbs
>          <div class="sr-only">{{t "pages.challenge.statement.sr-only.alternative-instruction"}}</div>
Alex: "Plutot pas selon moi. La vocalisation vient en renfort de la difficulté à lire un texte et non une image"

2024-05-30 14:40 UTC, Jeyffrey commented on mon-pix/translations/fr.json
> +          "stop": "Arrêter la lecture"
Yes je comprends, sinon on peut avoir un aria-label plus complet sur le bouton ?

2024-05-30 14:42 UTC, Libouk commented on mon-pix/tests/integration/components/assessment-banner_test.js
> +  module('when the text to speech feature toggle is enabled', function (hooks) {
You're right, how dare I forget

2024-05-30 14:47 UTC, Libouk commented on mon-pix/app/components/challenge-statement.js
> +  @tracked textToSpeechButtonTooltipText = this.intl.t('pages.challenge.statement.text-to-speech.play');
Après vérification, non

2024-05-30 14:49 UTC, Libouk commented
> Aussi, je crois pas avoir vu de tests concernant le non-affichage de la vocalisation dans les épreuves de certification.

dans le fichier challenge-statement_test j'ai bien un module ` module('when the assessment is a certification', function () {
          test('it should not render the text to speech button'`

2024-05-30 16:05 UTC, La-toile-cosmique approved these changes

2024-05-31 13:13 UTC, AlexNaudyy approved these changes

2024-05-31 13:18 UTC, Jeyffrey approved these changes

2024-06-03 07:23 UTC, merged