[TECH] Simplifie les infos de certificabilité sur l'espace surveillant (PIX-12854)
1024pix/pix pull request #9251
Opened 2024-06-13 09:38 UTC by aceol

## :unicorn: Problème
L’espace surveillant recupere les infos candidats tout les x secondes (5). Ces infos comprennent l’eligibilité aux certifications complementaires afin d’afficher la duree estimée de la certification ainsi qu’un message si le candidat est inscrit mais pas/plus elligibile.
Techniquement on va passer par le service des badges certificationBadgeServices  qui calcule l’eligibilité sur tout les badges puis ensuite l’eligibilité a la certification complementaire.

## :robot: Proposition
Ce calcul est deja fait lorsque le candidat rentre en certification. Si inscrit + elligible on cree un complementaryCertificationCourse. Pas besoin donc de tout recalculer, il suffit de tester la presence de celui-çi.

## :rainbow: Remarques

## :100: Pour tester
- Inscrire 3 candidats sur une certification complémentaire
- Rendre 2 candidats eligibles à cette certification complementaire
- Faire une reset de completence pour l'un des 2 candidats pour qu'il ne soit plus eligible
- Faire rentrer les 3 candidats en certification
- entrer sur le portail surveillant de la session
- verifier dans le portail surveillant:
  -  que les 2 non eligibles ont un message specifique
  - que la candidate elligible est bien noté comme passant la complementaire et que la duree de la certif est majorée en consequence

2024-06-14 15:25 UTC, aceol commented
Ajout de candidats pour les tests:

```json
{
    "sessionId": 1100013,
    "accessCode": "HDFJ73",
}

[
  {
    "userId": 1100018,
    "firstName": "pro1000003",
    "lastName": "pro1000003",
    "email": "pro1000003@example.net",
    "birthdate": "2000-01-01",
    "complementaryCertification": "Pix+ Édu 1er degré"
  },
  {
    "userId": 1101885,
    "firstName": "pro1000004",
    "lastName": "pro1000004",
    "email": "pro1000004@example.net",
    "birthdate": "2000-01-01",
    "complementaryCertification": "Pix+ Édu 1er degré"
  },
  {
    "userId": 1103752,
    "firstName": "pro1000005",
    "lastName": "pro1000005",
    "email": "pro1000005@example.net",
    "birthdate": "2000-01-01",
    "complementaryCertification": "CléA Numérique"
  },
  {
    "userId": 1105555,
    "firstName": "pro1000006",
    "lastName": "pro1000006",
    "email": "pro1000006@example.net",
    "birthdate": "2000-01-01",
    "complementaryCertification": null
  }
]
```

2024-06-17 15:13 UTC, AndreiaPena commented
> Ajout de candidats pour les tests:
> 
> ```json
> {
>     "sessionId": 1100013,
>     "accessCode": "HDFJ73",
> }
> 
> [
>   {
>     "userId": 1100018,
>     "firstName": "pro1000003",
>     "lastName": "pro1000003",
>     "email": "pro1000003@example.net",
>     "birthdate": "2000-01-01",
>     "complementaryCertification": "Pix+ Édu 1er degré"
>   },
>   {
>     "userId": 1101885,
>     "firstName": "pro1000004",
>     "lastName": "pro1000004",
>     "email": "pro1000004@example.net",
>     "birthdate": "2000-01-01",
>     "complementaryCertification": "Pix+ Édu 1er degré"
>   },
>   {
>     "userId": 1103752,
>     "firstName": "pro1000005",
>     "lastName": "pro1000005",
>     "email": "pro1000005@example.net",
>     "birthdate": "2000-01-01",
>     "complementaryCertification": "CléA Numérique"
>   },
>   {
>     "userId": 1105555,
>     "firstName": "pro1000006",
>     "lastName": "pro1000006",
>     "email": "pro1000006@example.net",
>     "birthdate": "2000-01-01",
>     "complementaryCertification": null
>   }
> ]
> ```

Pour le cli faut remplir toute cette paperasse maintenant ?
Je préfère le faire à la main 😎

2024-06-19 09:42 UTC, alexandrecoin approved these changes

2024-06-19 13:10 UTC, matthieu-octo approved these changes

2024-06-24 12:58 UTC, Steph0 commented
Tests KO, en cours de résolution (HTTP 500 sur les acceptance)

2024-06-24 13:04 UTC, mcampourcy commented on api/tests/certification/session-management/integration/infrastructure/repositories/session-for-supervising-repository_test.js
> +          firstName: 'Janis',
🔥 Janine Jolin ?

2024-06-24 13:04 UTC, mcampourcy commented on api/tests/tooling/domain-builder/factory/build-certification-candidate-for-supervising.js
> +  lastName = 'D Luffy',
Morgan P Lucien ? 😄

2024-06-24 14:45 UTC, Steph0 commented on api/tests/certification/session-management/integration/infrastructure/repositories/session-for-supervising-repository_test.js
> +          firstName: 'Janis',
Done

2024-06-24 14:45 UTC, Steph0 commented on api/tests/tooling/domain-builder/factory/build-certification-candidate-for-supervising.js
> +  lastName = 'D Luffy',
Done

2024-06-27 13:31 UTC, AndreiaPena requested changes
Test func, vu avec @aceol : Lorsque le candidat, éligible à une complémentaire, rempli le formulaire d'entrée en certif MAIS qu'il n'a pas entré son code candidat, le surveillant voit le bandeau "Non éligible" dans l'espace surveillant.

C'est parce que le user est relié à la certif mais le complementary-certification-course n'est pas encore créé.
Solution: ne pas renvoyer d'info (ne pas se fier aux infos des complémentaires) tant que le complementary-certification-course n'a pas été créer.

2024-07-11 14:39 UTC, Steph0 commented
Je cloture ce ticket. Les raisons détaillées sont évoqués dans le ticket interne PIX.

2024-07-11 14:39 UTC, closed without merging