[FEATURE] Ajouter un composant Tabs (PIX-12982).
1024pix/pix pull request #9485
Opened 2024-07-10 14:58 UTC by Jeyffrey

## :unicorn: Problème
À l'heure actuelle, il n'existe pas de composant "onglets" dans PixApp.
Or, nous en aurons besoin pour la nouvelle page de résultats de campagne.

## :robot: Proposition
Créer un composant Tab qui propose ces fonctionnalités : 
- Au focus dans les la liste des onglets, je peux naviguer avec les flèches gauche et droite et sélectionner l'onglet souhaité avec les touches "entrée" ou "espace".
- Une fois un onglet sélectionné, à la tabulation, le focus passe dans le panel associé.
- Sur un écran assez grand :
  - Lorsque la place le permet, chacun des onglets fait la même taille
- Sur un écran trop petit pour affiché tous les onglets :
  - La liste des onglets devient scrollable
  - Des boutons fléchés (cliquables mais pas utilisables au clavier) apparaissent pour permettre de scroller dans la liste des onglets
  - À la navigation clavier avec les flèches gauche / droite, la scroll est optimisé pour toujours bien afficher le nouvel onglet focus

## 💻 Implémentation technique

Ce nouveau composant s'utilise comme ceci :

```hbs
<PixTabs @ariaLabel="Sample tabs" @initialTabIndex={{1}} @onTabChange={{this.handleTabChange}}>
  <:tabs as |Tab|>
    <Tab @index={{0}}>Sed do eiusmod tempor incididunt</Tab>
    <Tab @index={{1}}>Dolor sit amet</Tab>
    <Tab @index={{2}}>Consectetur adipiscing elit</Tab>
    <Tab @index={{3}}>Lorem ipsum</Tab>
  </:tabs>

  <:panels as |Panel|>
    <Panel @index={{0}}>
      <h2>Panel content</h2>
    </Panel>
    <Panel @index={{1}}>
      <h2>Another panel</h2>
    </Panel>
    <Panel @index={{2}}>
      <h2>Coucou</h2>
    </Panel>
    <Panel @index={{3}}>
      <h2>Last one</h2>
    </Panel>
  </:panels>
</PixTabs>
```

ℹ️ On associe un onglet avec son panel grâce à la propriété `@index` présente sur chacun des composants.

ℹ️ La propriété `initialTabIndex` permet de déterminer un onglet spécifique au chargement de la page.<br/>Elle est optionnelle. Si non renseignée, le premier onglet sera affiché.

ℹ️ `onTabChange` permet de renseigner une méthode qui pourra avoir un paramètre qui est l'index du nouvel onglet sélectionné.

## :100: Pour tester

1. Vérifier les tests de ce composant
2. Aller sur la page `/test-tabs` pour visualiser le composant et vérifier son comportement

2024-07-11 13:50 UTC, La-toile-cosmique requested changes

2024-07-11 13:50 UTC, La-toile-cosmique commented on mon-pix/app/components/tabs/index.gjs
> +          ></span>
```sugestion
/>
```

2024-07-11 13:50 UTC, La-toile-cosmique commented on mon-pix/app/components/tabs/index.gjs
> +          ></span>
```sugestion
/>
```

2024-07-11 13:50 UTC, La-toile-cosmique commented on mon-pix/app/components/tabs/index.gjs
> +    this.elementHelper.waitForElement(this.id).then(() => {
await ?

2024-07-11 13:50 UTC, La-toile-cosmique commented on mon-pix/app/components/tabs/index.gjs
> +      window.addEventListener('resize', this.handleResponsiveTablist);
Il faudrait peut etre prevoir un removeEventListener quand le component n'est plus visible

2024-07-11 13:50 UTC, La-toile-cosmique commented on mon-pix/app/components/tabs/index.gjs
> +    if (this.args.id) return this.args.id;
```suggestion
    return this.args.id ? this.args.id : 'pix-tabs-' + guidFor(this);
```

2024-07-11 13:50 UTC, La-toile-cosmique commented on mon-pix/app/components/tabs/index.gjs
> +    let nextTabIndex = [...this.elements.tabs].findIndex((tab) => {
```suggestion
let nextTabIndex = Array.from(this.elements.tabs).findIndex((tab) => {
```

2024-07-11 13:50 UTC, La-toile-cosmique commented on mon-pix/app/components/tabs/index.gjs
> +    let nextTabIndex = [...this.elements.tabs].findIndex((tab) => {
Sinon aussi il faudrait mieux nommer cette variable currentTabIndex et la declarer en constante puis declarer une autre variable nextTabIndex que tu vas muter

2024-07-11 13:50 UTC, La-toile-cosmique commented on mon-pix/app/components/tabs/tab-item.gjs
> +    <div>
pourquoi un div dans le button ?

2024-07-11 13:50 UTC, La-toile-cosmique commented on mon-pix/app/components/tabs/index.gjs
> +      this.elements.tablist.addEventListener('scroll', this.handleTablistArrowsVisibility);
pareil pour celui la

2024-07-11 13:51 UTC, La-toile-cosmique requested changes
je la fait en deux parties

2024-07-11 13:55 UTC, Jeyffrey commented on mon-pix/app/components/tabs/index.gjs
> +      window.addEventListener('resize', this.handleResponsiveTablist);
En fait je pense que je vais attacher l'événement `resize` directement sur l'élément parent, côté template.

2024-07-11 13:56 UTC, Jeyffrey commented on mon-pix/app/components/tabs/index.gjs
> +    if (this.args.id) return this.args.id;
```js
return this.args.id || 'pix-tabs-' + guidFor(this);
```

C'est peut-être encore mieux

2024-07-11 14:00 UTC, Jeyffrey commented on mon-pix/app/components/tabs/tab-item.gjs
> +    <div>
Je crois que c'est une erreur 🤦🏻‍♂️

2024-07-12 08:35 UTC, AlexNaudyy approved these changes

2024-07-12 09:01 UTC, La-toile-cosmique commented on mon-pix/app/components/tabs/index.gjs
> +    const tabToFocus = document.getElementById(this.id + '-' + nextTabIndex);
du coup tu executes qund meme ce morceau de code meme si la touche n'est pas reconnue. c'est pas grave mais c'est pas tres perf

2024-07-12 09:18 UTC, La-toile-cosmique commented on mon-pix/app/components/tabs/index.gjs
> +    this.elementHelper.waitForElement(this.id).then(() => {
ah oui constructor :+1

2024-07-12 09:27 UTC, La-toile-cosmique commented on mon-pix/app/components/tabs/index.gjs
> +  handleArrowClick(direction) {
Peut etre que ce serait mieux de creer deux methodes (leftArrowClick et rightArrowClick) ce qui m embete ici c'est que l'argument "right" ne sert a rien. tu pourrais passer "banane" ca irait quand meme a droite

2024-07-12 11:57 UTC, La-toile-cosmique commented on mon-pix/app/components/tabs/tab-item.gjs
> +<template>
Il faut pas export default le template ?

2024-07-12 12:10 UTC, Jeyffrey commented on mon-pix/app/components/tabs/tab-item.gjs
> +    <div>
Ah non, en fait j'en ai besoin pour gérer l'ellipse (dans le cas où l'intitulé est trop long).
J'ai changé la `<div />` par un `<span />`.

2024-07-12 12:10 UTC, Jeyffrey commented on mon-pix/app/components/tabs/index.gjs
> +      this.elements.tablist.addEventListener('scroll', this.handleTablistArrowsVisibility);
Je déplace cet event dans le template

2024-07-12 12:21 UTC, Jeyffrey commented on mon-pix/app/components/tabs/index.gjs
> +    const tabToFocus = document.getElementById(this.id + '-' + nextTabIndex);
Je vais tout mettre dans un bon vieux `if`

2024-07-12 12:33 UTC, Jeyffrey commented on mon-pix/app/components/tabs/index.gjs
> +      window.addEventListener('resize', this.handleResponsiveTablist);
J'ai ajouté 2 actions `onMount` et `onDestroy` qui sont appelées via les modifiers `didInsert` et `willDestroy` côté template.

2024-07-12 12:33 UTC, Jeyffrey commented on mon-pix/app/components/tabs/index.gjs
> +    let nextTabIndex = [...this.elements.tabs].findIndex((tab) => {
Done

2024-07-12 12:34 UTC, Jeyffrey commented on mon-pix/app/components/tabs/tab-item.gjs
> +<template>
J'ai pas l'impression non.

https://guides.emberjs.com/release/components/template-tag-format/#toc_template-only-components :
<img width="812" alt="image" src="https://github.com/user-attachments/assets/1d029dfa-6960-49a8-923c-8455aa3f2d5c">

2024-07-15 09:04 UTC, La-toile-cosmique approved these changes
:+1

2024-07-15 09:04 UTC, La-toile-cosmique commented on mon-pix/tests/integration/components/tabs_test.js
> +module('Integration | Component | pix-tabs', function (hooks) {
```suggestion
module('Integration | Component | Tabs', function (hooks) {
```

2024-07-15 09:04 UTC, La-toile-cosmique commented on mon-pix/tests/integration/components/tabs_test.js
> +module('Integration | Component | pix-tabs', function (hooks) {
non ?

2024-07-16 14:06 UTC, xav-car commented on mon-pix/app/components/tabs/index.gjs
> +    <div class="pix-tabs" id={{this.id}} ...attributes {{didInsert this.onMount}} {{willDestroy this.onDestroy}}>
**question** : il me semble que le helper `didInsert` est voué à disparaître. il n'y a pas une autre solution afin d'éviter de la dette ?

2024-07-17 07:51 UTC, Jeyffrey commented on mon-pix/app/components/tabs/index.gjs
> +    <div class="pix-tabs" id={{this.id}} ...attributes {{didInsert this.onMount}} {{willDestroy this.onDestroy}}>
Ah, j'ai pas vu passer cette info. 
T'aurais un lien ?

2024-07-17 12:51 UTC, xav-car commented on mon-pix/app/components/tabs/index.gjs
> +    <div class="pix-tabs" id={{this.id}} ...attributes {{didInsert this.onMount}} {{willDestroy this.onDestroy}}>
Actuellement, 
seul le constructor et willDestroy sont disponible en natif dans la class ( et non dans le html )

https://guides.emberjs.com/release/upgrading/current-edition/glimmer-components/

il maintienait une lib pour le moment `[@ember/render-modifiers](https://github.com/emberjs/ember-render-modifiers)`  mais là ça fait 1 ans qu'il n'y a rien eu dessus. 

il ne conseillais de ne plus l'utiliser car tout est disponible autrement (via le constructor notamment depuis Octane). il ont probablement drop le support depuis 1an déjà (plus aucune activité sur leur branche principale). 

ça devait être dans une RFC, ou dans le log d'erreur d'ember template lint. d'où la suppression récente dans PixUI / PixAdmin déjà suite à la montée de version d'ember template lint.

2024-07-17 15:40 UTC, xav-car commented on mon-pix/app/components/tabs/index.gjs
> +    <div class="pix-tabs" id={{this.id}} ...attributes {{didInsert this.onMount}} {{willDestroy this.onDestroy}}>
https://github.com/ember-template-lint/ember-template-lint/blob/master/docs/rule/no-at-ember-render-modifiers.md

`@ember/render-modifiers were meant as a transitional tool from the pre-Octane era, and not long-term usage.`

2024-07-29 10:03 UTC, Jeyffrey commented on mon-pix/app/components/tabs/index.gjs
> +    <div class="pix-tabs" id={{this.id}} ...attributes {{didInsert this.onMount}} {{willDestroy this.onDestroy}}>
C'est modifié en respectant ce qui est indiqué ici : https://github.com/ember-template-lint/ember-template-lint/blob/master/docs/rule/no-at-ember-render-modifiers.md#migration

Merci pour le retour @xav-car !

2024-07-30 10:28 UTC, merged